### ISSUE TITLE
Chybí hláška o nevyplněných M polích

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#100]
Při založení nového objektu (monografie) se objekt uloží, i když nemá vyplněná povinná pole. Prosím přidat hlášku a zvýraznění.

![obrazek](https://user-images.githubusercontent.com/13831946/113970188-bbb83680-9836-11eb-80bb-59bfade3d62e.png)

**Comment by luckajirku** [comment]
Nejen při založení nového objektu. I když vymažu obsah povinného pole u dříve založeného objektu - číslo, datum vydání apod.
Tohle je potřeba opravit.

**Comment by luckajirku** [comment]
Jako tohle je fakt dost šílený - jde založit a ULOŽIT objekt úplně bez metadat, nezařve to vůbec. První hláška je až ve chvíli, kdy pustím export, tak si postěžuje, že objekt nemá urn:nbn.

**Comment by luckajirku** [comment]
Kdy bude vyřešené toto?  Resp. kdy bude k testování verze, na které půjde uspokojivě otestovat celý proces zpracování základních NDK modelů? Nemá smysl testovat drobnosti a vylepšení, když pořád nefunguje základ.

**Comment by honza-rychtar** [comment]
@luckajirku do schůzky příští týden.

**Comment by SmejkalovaAnna** [comment]
stále nefunguje

**Comment by honza-rychtar** [comment]
@SmejkalovaAnna  To by mělo fungovat na všech modelech kromě stran.

<img width="1382" alt="Snímek obrazovky 2021-09-28 v 22 17 26" src="https://user-images.githubusercontent.com/1178142/135159467-58bfbc2b-c906-4e2a-aab4-9c25fe01f312.png">

**Comment by SmejkalovaAnna** [comment]
Dobře a na stranách to bude fungovat?

**Comment by honza-rychtar** [comment]
Ano, #126

**Comment by luckajirku** [comment]
Za nás v pořádku, může se zavřít.

**Comment by luckajirku** [comment]
@pavelkocourek zavírat by se to mělo asi až po schůzce - tohle je jen za nás ostestováno a pro přehlednost tam dávám label, ale měli by to odsouhlasit i z KNAV. Btw bylo by super, kdyby byly ze strany Inovatiky takhle rychlé reakce v těch issues, kde je potřeba komentovat, vysvětlit, diskutovat:-).

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, kouknete na to? To, co jsem zatím vyzkoušela já, bylo ok, ale radši Váš názor, pracujete s tím denně. Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera @nezbedova Já jsem to taky zkoušela a funguje to, ale nefunguje #124

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna ok, díky.

**Comment by ZdenkaSera** [comment]
@pavelkocourek @honza-rychtar Nakonec issue znovu otevírám, Jeden zádrhel tu je. Pokud dám vytvořit nový objekt a ve fázi zobrazeného prázdného formuláře opustím obrazovku, prázdný záznam se uloží. vyzkoušela jsem s NDK monografií a NDK číslem.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera  Zdenko to ale dělá i starý klient..... to je spíš vlastnost.....

**Comment by ZdenkaSera** [comment]
Aha - zatím se mi to nikdy nepovedlo, tohle byl cílený pokus a osobně bych to viděla jako chybu. Takže pokud to jako ok vidí i @luckajirku, znovu to zavřu :-) Děkuji.

**Comment by nezbedova** [comment]
To se ději i v RDflow. Otázkou je, zda tuto vlastnost chceme.

**Comment by SmejkalovaAnna** [comment]
Já bych to taky viděla jako chybu, logicky by se to uložit nemělo, když člověk neklepne na Uložit.  Takže navrhuji opravu - neukládat, pokud se vrátím do jiného okna bez uložení.

**Comment by ZdenkaSera** [comment]
@honza-rychtar Není tohle ukládáni prázdných objektů spojeno s řešením problému [#33](https://github.com/proarc/proarc-client/issues/33) ?

**Comment by ZdenkaSera** [comment]
Na schůzce uzavírám.
