### ISSUE TITLE
OriginInfo/issuance u periodik

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#101]
V klientovi teď je ve “vydávání” na výběr z hodnot: “na pokračování”, “sériové” a “začlěňovací”.

Co se dá opravit hned, je “začlěňovací”, to je zbytečný (a ještě s překlepem) pokus o vlastní překlad, když se běžně léta používá v katalogizační praxi termín “integrační zdroj”.

Ale jak jsem se v tom začala hrabat, koukám, že v šabloně marc-mods už nemají hodnotu continuing, ale překlápí obě hodnoty z LDR/07 s (serial) i b (serial component part) jako “serial”. 

_Revision 1.94 - Leader 07 b changed mapping from continuing to serial tmee 2014/02/21_ 

_<xsl:when test="$leader7='b' or $leader7='s'">serial</xsl:when>_

V NDK standardu pořád jsou všechny tři možnosti, vč. continuing. Co s tím?

**Comment by luckajirku** [comment]
založila jsem issue na standardech https://github.com/NLCR/Standard_NDK/issues/148

**Comment by honza-rychtar** [comment]
@luckajirku Přejmenoval jsem **začlěňovací** na **integrační zdroj** (bude v příští verzi).
Ale dál už se to proArcu netýká. A můžou se udělat 3 věcí mimo ProArc
1. Upravit MARC to MODS šablonu.
2. Upravit standard
3. Nechat to jak to je.

**Comment by luckajirku** [comment]
Odpověď NK z výše zméněného issue na standardech:

_Dobrý den, dle vyjádření LOC je nově vhodné hodnoty z polí LDR/07 "b" a "s" skutečně vhodné zapisovat jako "serial". Hodnota "continuing" není dále podporovaná, nakolik se změnilo mapování v MARC21 (takže do MODS už se hodnota continuing od verze 3.6 nepřeklápí).

Možnosti k zápisu jsou tedy dvě, "serial" a "integrating resource". V Guidelines jsou ponechány všechny tři hodnoty vč. "continuing" z důvodu návaznosti na starší verze MODS._

**Comment by ZdenkaSera** [comment]
@luckajirku Zdá se mi to vyřešené, navrhuji tedy k uzavření - prosím o potvrzení. Děkuji.
