### ISSUE TITLE
podpora pro stránky model:oldprintpage

### ISSUE THREAD

**Issue by fstepanovsky** [proarc/proarc-client#102]
Když se v ProArcu nahrají stránky jako [model:oldprintpage](https://github.com/proarc/proarc/wiki/Konfigurace#star%C3%A9-tisky), tak klient při kliknutí na importovanou stránku pošle ProArcu dotaz:
```
http://proarc.staff.mzk.cz/proarc/rest/v1/object/mods/custom?pid=uuid:bcf5e806-ffa3-4fd4-92cf-be6a2d12aa44&editorId=model:ndkpage&batchId=1492
```

Server mu odpoví status kódem 500, předpokládám, že je to kvůli editorId=model:ndkpage z požadavku.
V ProArcu jako takovém jsem zkoušel, že zpracování stránek funguje, přidávám ještě screenshot, jak to vypadá s konzolí js.

![image](https://user-images.githubusercontent.com/3747619/114507480-77aca380-9c33-11eb-8ff3-05c30e954207.png)

**Comment by honza-rychtar** [comment]
Opraveno. Zobrazení a editace STT stranu už funguje. Nicméně stále nefunguje hromadná editace STT stran - to musíme opravit v jádře Proarcu.
