### ISSUE TITLE
nefunguje tlačítko "Pokračovat v přípravě metadat" ve Správě importních dávek

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#103]
Jsem ve Správě importních dávek, dám Načíst znovu, dávka se načte, vyskočí okénko s tlačítkem Pokračovat v přípravě metadat - kliknu na něj - a nic. Jinak zbylé možnosti fungují, dá se přejít dvojklikem nebo nahoře přes tlačítko Pokračovat, to funguje bez problémů.

**Comment by luckajirku** [comment]
Teď nejsme schopni otestovat, protože nejsou na testovacím serveru vhodné dávky. Ale i tak - visí to tu bez reakce 3/4 roku.

**Comment by ZdenkaSera** [comment]
@luckajirku vyzkoušela jsem u nás, po opětovném načtení dávky pokračovací tlačítko stále nefunguje.

**Comment by ZdenkaSera** [comment]
K testu.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
