### ISSUE TITLE
Výběr nadřazeného objektu - možnost řazení

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#104]
Když se ukládají popsané stránky do nadřazeného objektu, chybí tam možnost seřazení těch objektů. Můžu použít Hledat, ale asi by tam měla být i rychlá cesta, když ukládám do právě vytvořeného objektu - mít možnost seřadit podle Vytvořeno a ty nejnovější mít nahoře...

**Comment by ZdenkaSera** [comment]
K testu.

**Comment by nezbedova** [comment]
Funguje třízení pomocí kliknutí na záhlaví. Ale při menším okně se schová část prvního sloupce a ostatní jsou široké. To by nevadilo, pokud by jako první byl např. model. Teď tam je název, který se schová, což je velmi nepraktické. Roztáhnout sloupec mi nešlo.

![obrazek](https://user-images.githubusercontent.com/13831946/157706348-f0676726-7f4d-4be7-891f-573e73b665de.png)

**Comment by albertoh** [comment]
@pkudela proism podivej se

**Comment by luckajirku** [comment]
Trochu mám pocit, že se zavedením řazení se zase rozbilo hledání... 
- vyplním něco nahoře do "Hledat dokument": na to, co je napsané v "Hledat dokument" + jaké "pole" je vybrané, PA nebere ohled, vyhodí všechny výsledky pro vybraný model (popř. všechny modely u volby "vše"). Navíc možnost řazení výsledků je neaktivní.
- do "Hledat dokument" nevyplním nic, mám jen zvolený model (popř. všechny modely u volby "vše") - vyhodí to opět všechny výsledky, které odpovídají zvolenému modelu, ale možnost řazení je aktivní.
Je potřeba, aby fungovaly obě možnosti - jak hledání, tak řazení.

**Comment by albertoh** [comment]
Doplnena moznost hledat dotaz nebo pokrocilem hledanim (podobne jako hlavni stranka hledani)

![image](https://user-images.githubusercontent.com/5946836/170667832-019be355-026c-4095-9f92-49e7898f0120.png)

![image](https://user-images.githubusercontent.com/5946836/170667876-548d1b46-cd26-48e6-bddd-acf5ddd2da5c.png)

**Comment by luckajirku** [comment]
pořád je to zvláštní...

Když vyplním do vyhledávacího pole cokoli (ať už v pokročilém hledání nebo v dotazu), možnost řazení výsledků není - to je tedy úmyslně?

Pak když dám něco do vyhledávacího pole plus mám zvolený model (např. NDK per.) 
- v dotazu mi to vyhledá výsledky, které obsahují hledané slovo, ale neřeší už model - je tam jak NDK per., tak čísla, tak přílohy...    
- když to dám stejně v pokročilém hledání, tak mi to vyhledá jen výsledky, které obsahují hledané slovo a zároveň splňují i podmínku toho modelu - čili jen model NDK per.

**Comment by albertoh** [comment]
@SykoraLukas  Jadro nevraci spravne razeni pokud mame fulltextovy dotaz (type=phrase)
Taky ignoruje filter pro model.
Muzes se divat?

**Comment by SykoraLukas** [comment]
Ano, je to tak.

V novém klientovi "Dotaz" je to samé jako "Dotaz" ve starém klientovi. Tedy hledá se jen dotaz bez ohledu na další věci a ani se nedá v případě dotazu řadit.

Právě proto se pro nový klient dělalo pokročilé hledání, kde funguje kombinace hledání v danám poli + řazení.

**Comment by SykoraLukas** [comment]
Ja bych spis byl pro to, aby se i dotaz dal filtrovat podle modelu a případně řadit podle zvolených sloupců.

**Comment by albertoh** [comment]
Taky jsem pro. Ale to musi dovolit API.

**Comment by SykoraLukas** [comment]
Api upraveno. Můžete otestrovat.

**Comment by luckajirku** [comment]
- dotaz s filtrováním i řazení vypadá, že funguje správně
- jen tu ještě zbývá ten [problém s prvním sloupcem](https://github.com/proarc/proarc-client/issues/104#issuecomment-1064232900) v případě, že uživatel zmenší okno

**Comment by luckajirku** [comment]
Tohle se může klidně zavřít - to, kvůli čemu jsem issue zakládala, je OK - a na problém se zobrazením v malém okně se může otevřít nové issue, pokud je to na delší řešení.

**Comment by albertoh** [comment]
Jsem nastavil minimalni sirku prvniho sloupce.
Tady bych zavrel. Mely by se vyresit vsechny tabulky v aplikaci, udelat redisajn podle novejsi verzi angularu, na kterou jsem aktualizoval. Ona nam dovoli lepsi uzivatelske rozhrani

**Comment by ZdenkaSera** [comment]
@luckajirku Mně to připadá ok.

**Comment by ZdenkaSera** [comment]
@luckajirku Dobře, zítra se domluvíme s M. a případně pak zavřeme. Díky

**Comment by nezbedova** [comment]
Děkuji. Toto je přesně, jak jsem to potřebovala. Jde pohodlně pracovat i na menších monitorech nebo v menších oknech.

Za nám lze zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
