### ISSUE TITLE
Převod Stran na NDK strany

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#105]
Prosím do klienta přidat možnost "Převést Stranu na NDK stranu" a zpět.
V jádře je tato fce v "Administraci" zde: 
![obrazek](https://user-images.githubusercontent.com/31240271/115226600-b77dfa00-a10f-11eb-9762-db365482d84b.png)
Děkuji, M.

**Comment by zabak** [comment]
taky strany starých tisků - viz https://github.com/proarc/proarc/issues/1359

**Comment by SmejkalovaAnna** [comment]
Vyzkoušela jsem, ze Strany na NDK stranu to funguje i dávkově, ale zpátky z NDK na Stranu to funguje jen po jedné straně a vždycky to napíše stejnou hlášku - v případě zkoušky dávky i po jedné straně - že se to provedlo, ale s chybou....

**Comment by ZdenkaSera** [comment]
Převody nefungují po částech - i při označení jen několika stran se převedou všechny. Převod všech stran naráz je ideální cílový stav, ale převod po částech je potřebný pro případ chyby při převodu.  (Testování převodů v jádře je ok, zlobí to jen v novém klietu.)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Beru zpět, co jsem napsala výše - ve verzi 3.7.3 to nefunguje ani v jádře, zjistila jsem až po aktualizaci zobrtazení.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tak přece jen jádro ok, měla jsem tentýž objekt otevřen 2x. V novém klientovi se to (zatím test na svazku monografie) chová tak, že i při označení několika stran se snaží převest všechny - buď dojede až do konce nebo se v případě chyby zastaví až u ní bez ohledu na původně označené strany.

**Comment by luckajirku** [comment]
Potvrzujeme, v novém klientovi převádí všechny strany v daném objektu místo jen těch vybraných.

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, můžete se na tohle podívat, než to zavřu? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera Dobrý den, omlouvám se, že jsem se nevyjádřila, ale ten účet emirova ani nevím, že existuje, takže mi nepřišlo upozornění. Převod stran nám funguje. Co se týče převodu pouze vybraného množství stran v rámci např. monografie, tak v tom taky nevidím z naší strany využití.

**Comment by ZdenkaSera** [comment]
@erikamirova Děkuji :-) Pokud jde o ten účet, to byla moje chyba, na kterou jsem přišla až dneska. Omlouvám se.

**Comment by albertoh** [comment]
Ony zmizely na zaklade #210. Tam jste rekli, ze mam tlacitka odstranit :o

**Comment by nezbedova** [comment]
@albertoh Děkuji za vysvětlení.

**Comment by ZdenkaSera** [comment]
znovu zavírám na schůzce.
