### ISSUE TITLE
Administrace uživatelů

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#106]
Přidat obrazovku pro správu uživatelů jako je ve starém rozhraní v Menu -> Uživatelé

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Čekala jsem na nasazení nové verze k nám, kde se můžu podívat na klienta pod různými oprávněními. Prosím, jak je to se správou uživatelů? Zdá se mi, že jsou zatím stále jen v jádře. Děkuji

**Comment by albertoh** [comment]
Neni. To musim delat.

**Comment by ZdenkaSera** [comment]
@albertoh OK, děkuji za upřesnění.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Základní administrace uživatelů v novém klientovi už je, Podle testu vypadá, že se chová stejně, jako v jádře, rozdíl jen v organizacích - zde jsou reprezentovány siglami, v jádře jsou zřejmě nalinkovány i názvy. Není na závadu funkčnosti, ale prosím, v jakém konfigu nového klienta jsou  tyto organizace? Děkuji.

**Comment by ZdenkaSera** [comment]
Tak přece jen chyba @albertoh  - v administraci uživatelů chybí za polem Organizace roletka/seznam dostupných možností.

**Comment by ZdenkaSera** [comment]
Výše jsem se ptala na konfig organizací - na wiki to je (APP_GLOBAL.organizations) takže ok.

**Comment by albertoh** [comment]
Je to tam
![image](https://user-images.githubusercontent.com/5946836/193798959-363e1eb4-131d-4885-8227-e92afb6b68aa.png)

**Comment by ZdenkaSera** [comment]
@albertoh Děkuji, na Inovatice seznam vidím.  Proč se od sebe liší seznam zde a ten použitý v ATM objektů? Obsahově jsou stejně, ale chování se liší. Tady se u názvu organizace předpokládají 2 části (název + sigla nebo její náhrada v závorce) a po výběru organizace se zobrazuje právě část v závorce.  V ATM je pouze název.
Je to jen otázka zobrazení nebo  jde o dva samostatné sety v konfiguraci?

**Comment by albertoh** [comment]
Je to jen zobrazeni. Ulozi se sigla. Dal jsem pro prehlednost prelozeny nazev a v zavorkach sigla.
To jsem tady udelal tak, proto ze muze se napsat neco co neni na seznamu.
Muzu to ale zmenit

**Comment by ZdenkaSera** [comment]
Ok, tak ještě dotazy: 
- v konfigu v APP_GLOBAL.organizations jsou sigly; sem tedy přidáme novou organizaci, resp. část, která reprezentuje siglu - př. Inovatika(_**Inovatika**_). Kam zadáme název (překlad názvu) aby se organizace zobrazovala správně i v ATM? Tak podle mého pracujete s první částí tj.  _**Inovatika**_(Inovatika)
- proč se v adminu uživatelů smí ukládat i organizace, která není na seznamu v konfigu? Vyzkoušela jsem - jde to, ale do ATM nově založeného objektu se taková organizace nepřevezme. Nevidím využití, spíš zdroj nepořádku.

**Comment by albertoh** [comment]
1.) Preklady se definujou v souborech assets/i18n.cs.json a en.json. Pro organizace jsou to klice 
```
"organization": {
    "ABA007": "Knihovna Akademie věd ČR",
    "BOA001": "Moravská zemská knihovna",
    "ABA010": "Knihovna Národního muzea",
    "ABA012": "Národní pedagogická knihovna Komenského Praha",
    "HKA001": "Studijní a vědecká knihovna v Hradci Králové",
    "ABE301": "Český rozhlas - knihovna",
    "ABG001": "Městská knihovna v Praze",
    "ABD068": "Univerzita Karlova v Praze - 1.LF a VFN",
    "ABD103": "Univerzita Karlova v Praze - Fakulta sociálních věd",
    "PAG001": "Krajská knihovna v Pardubicích",
    "JIG001": "Městská knihovna Jihlava",
    "HBG001": "Krajská knihovna Vysočiny",
    "226102010": "SOkA Jihlava",
    "226103010": "SOkA Pelhřimov",
    "226101010": "SOkA Havlíčkův Brod",
    "226104010": "SOkA Třebíč",
    "226105010": "SOkA Žďár nad Sázavou",
    "Inovatika": "Inovatika"
  },
```

2.) Zmenim to tak, aby se nedalo volne psat

**Comment by ZdenkaSera** [comment]
Na Inovatice super, díky :-).

**Comment by ZdenkaSera** [comment]
Nikdo další se k funkci nevyjádřil - zatím zavírám.
