### ISSUE TITLE
Přidat tlačítko Zkopírovat objekt

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#108]
Prosím přidat tlačítko Zkopírovat objekt do dolní lišty v obrazovce dříve Správa digitálních objektů nyní Hledat.

**Comment by albertoh** [comment]
Pridano. Zkontrolujte, prosim

**Comment by ZdenkaSera** [comment]
Fce "zkopírovat" přidána k testu a uzavření; projít další funkce "administrativní" a případně založit nová issue.

**Comment by SmejkalovaAnna** [comment]
@nezbedova Martino nevím, jak to bylo myšleno, ale zkopiruje mi to jen úroveň titul, ale když stojím na NDK ročník tak mi ho to nezkopiruje..... mělo by to fungovat na všech úrovních?

**Comment by nezbedova** [comment]
@SmejkalovaAnna Mělo by to zkopírovat výtisk periodika. A monografii.

**Comment by SmejkalovaAnna** [comment]
Negunguje, zkopíruje to jen na úrovni titul, to ano, ale když chci výtisk, tak to napíše jen OK a nezkopíruje ho to.

**Comment by luckajirku** [comment]
Tohle by zase stačilo obšlehnout ze starého rozhraní. Tam nabídka Zkopírovat objekt na úrovni titulu periodika vůbec není, stejně tak není na úrovni ročníku ani na úrovni strany - zato tam je (a i funguje) na úrovni výtisku periodika a svazku monografie.

(Ani ve starém teda není u přílohy periodika, u kapitoly... - tohle asi pak bude chtít projít, kde všude by se to ještě třeba hodilo - ale číslo periodika a svazek monografie jsou jasné.)

**Comment by albertoh** [comment]
Tlacitko je ted k dispozici jen pro modely ndkmonographvolume a ndkperiodicalissue

**Comment by luckajirku** [comment]
Tlačítko je jen pro ty vybrané modely, potud OK. 
Ale když na výtisku periodika (model NDK číslo) dám Zkopírovat, vytvoří mi to ne číslo, ale titul periodika (model NDK periodikum).

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Už to vypadá OK - tvoří se, co má, a na správném místě, ale asi si to ještě zkuste v KNAV, kde to používáte víc @nezbedova.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím Tě, podívala by ses na tohle? Díky.

**Comment by nezbedova** [comment]
Test kopírování monografie:
Po kliknutí na Zkopírovat se nic neděje. Musela jsem dát načíst znovu stránku. Buďo dělám něco špatně nebo to je podivné chování.

když jsem to chtěla otestovat v jádře (také na Inovatice), tak proběhla hláška o vytvoření nového objektu, ale nikde ho nevidím.

Ve verzi 3.8, kterou máme u nás nasazenou se v jádře i v klientovi nový objekt objeví.

**Comment by nezbedova** [comment]
Otestováno na NDK monografii. Funguje.

**Comment by nezbedova** [comment]
Tlačítko chybí u STT. Tam tuto operaci nemohu provést.

**Comment by albertoh** [comment]
Vyse jsme omezili modely :
https://github.com/proarc/proarc-client/issues/108#issuecomment-1139487584

V starem klientovi neni. @SykoraLukas muzu pridat? Jadro to dovoluje?

**Comment by SykoraLukas** [comment]
Ano, mělo by to být v pořádku.

**Comment by luckajirku** [comment]
A zase se nám to rozbilo. Když si dám v Hledat vyhledat podle modelu, pak mám v nabídce u těch správných tlačítko Zkopírovat. Jenže normální cesta k číslu periodika není nahoře přes model NDK číslo, ale přes NDK periodikum a pak až dole přes strukturu toho konkrétního periodika - ale tam už to tlačítko, když najedu na číslo, není.

**Comment by albertoh** [comment]
Omlouvam se, rozbilo se to pri pridani toho stromu do vyberu nadrazeneho.
Opraveno

**Comment by luckajirku** [comment]
Ještě ne:-). Tlačítko už je tam, kde má být, ale když dám vytvořit číslo periodika, zařadí se mi v tu chvíli to nové číslo v horní tabulce do výpisu titulů periodik na konec. NDK Číslo za NDK Periodika... Mělo by zůstat nahoře vybrané to periodikum, kde se kopíruje a dole by se mělo ve stromu ukázat to zkopírované číslo.
Že u monošek se to vytvoří na konci, i když je třeba nastavené řazení od nejnovějšího sestupně, to vem čert, ale u těch periodik to nejde, aby to člověka takhle vyhodilo.

**Comment by albertoh** [comment]
hm. Pri soucasnim disajnu, budu muset udelat reload hledani.
Pokusim se najit vhodne reseni

**Comment by albertoh** [comment]
Opraveno pridavani nespravne mezi periodika.
Pro monografii pridava se objekt hned za vybranem
Pro NDK cislo, vola se obnovit strom. Primi pridani a rozbaleni ted nestihnu

**Comment by luckajirku** [comment]
zatím asi OK, s tímhle se dá fungovat, jestli souhlasí i @nezbedova. Jen nevím, jak pak dál - jestli tohle issue zavřít a udělat extra issue na ta periodika na později, aby se dodělalo rozbalení a vybrání přímo toho zkopírovaného objektu ve spodní části, nebo nechat tohle issue dál otevřené.  

teď stav: 

**NDK Svazek mon. a STT svazek mon.**: Ať se kopíruje odkudkoli, hodí se ten nový objekt v horní části tabulky za ten kopírovaný a je vybraný. Po refreshi se umístí na správné místo podle řazení.

**NDK Číslo periodika**: po zkopírování čísla proběhne automaticky obnovení spodní části tabulky (strom se sbalí) a nový objekt je úplně na konci v tom ročníku, odkud se číslo kopírovalo.

**Comment by SmejkalovaAnna** [comment]
Vyzkoušela jsem na NDK číslo a vypadá to funkčně...za mě OK.

**Comment by luckajirku** [comment]
Na dotažení zařazování (hlavně u periodik) jsem založila nové issue - a tohle se tím pádem bude moct zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
