### ISSUE TITLE
Nelze založit nový objekt

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc-client#11]
Když jsem zkoušela založit nový objekt, tak poprvé to nešlo vůbec. Vybrala jsem model a potvrdila založení nového objektu a začalo se načítat, ale načítalo se pořád dál a nic...

Druhý pokus vyhodil chybu:
![novyobjekt](https://user-images.githubusercontent.com/21309201/79228628-0f7d8300-7e62-11ea-8432-1246eaaf991c.jpg)

Další pokus taky, jen jsem zkusila založit nový objekt s vlastním uuid a taky to nešlo:
![novyobjekt2](https://user-images.githubusercontent.com/21309201/79228662-202df900-7e62-11ea-8348-63a090879e72.jpg)

**Comment by krizovj** [comment]
Zkoušela jsem to ještě s modelem NDK Periodikum.

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 28.7.
