### ISSUE TITLE
Doplnit modely pro STT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#110]
Prosím doplnit všechny modely pro STT. Označení _Kronika_ není přesné.

**Comment by nezbedova** [comment]
Ve Verze 1.0.6 (8.5.2021) vidím jen Kronika. Žádný nový model STT.

**Comment by honza-rychtar** [comment]
Stačí přidat modely v konfiguraci. Doplnil jsem všechny modely do příkladu konfigurace na wiki u **Nasazení klienta** https://github.com/proarc/proarc-client/wiki/Nasazen%C3%AD-klienta#p%C5%99%C3%ADklad-konfigurace
