### ISSUE TITLE
Dotaz na tlačítka

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#111]
Jaký je rozdíl mezi tlačítky Režim detailu a Metadata? přijde mi to stejné. Pokud tomu tak je, navrhuji nechat jen jedno tlačítko a to M jako metadata.

**Comment by honza-rychtar** [comment]
Režim detailu znamená, že mám ve všech panelech stejný objekt.
Režim procházení znamená že mám v levém panelu potomky objektu a v pravém panelu jednoho z těch potomků.
Metadata jsou pak jen jednou z voleb levého panelu v režimu detailu a nebo v pravém panelu.

**Comment by nezbedova** [comment]
Musím to vyzkoušet u periodik.

**Comment by luckajirku** [comment]
U nás pořád nechápeme, v čem je tenhle nový způsob lepší než ten stávající.

**Comment by honza-rychtar** [comment]
Je to vlastně to samé jako je ve stávajícím přepínání 
Editory -> Metadata | Vazby.

**Comment by ZdenkaSera** [comment]
Prosíme o vyzkoušení a reakci s přihlédnutím ke komentáři HR.

**Comment by luckajirku** [comment]
Režim detailu vs procházení: ve starém klientovi je to editor Metadata vs editor Vazby. V editoru Vazby (režim procházení) je vlevo struktura, vpravo zvolený objekt, což zpřehledňuje popis, ale neumožňuje popsat samotný objekt, ve kterém se nacházíme, což je problém na úrovni titulu (tam se výš nedostaneme). V editoru Metadata (režim detailu) popisujeme právě jen na úrovni, na které se nacházíme, což se hodí na úrovni titulu a na nic jiného (všude jinde je snazší/přehlednější jít přes Vazby, tam totiž vidíme strukturu a můžeme ji procházet)

- pokud tam mají zůstat takhle dva editory, byli bychom pro to vrátit se k zažitému a srozumitelnému pojmenování editorů - Vazby a Metadata

- otázka je, jestli by nešlo do editoru Vazby přidat možnost jít až na (resp. nad) úroveň titulu, aby byla možnost pracovat s metadaty titulu rovnou ve Vazbách, stejně jako to jde s metadaty ročníku, výtisku… Je tohle technicky nemožné? (A pak by druhý režim nebyl potřeba.)

**Comment by albertoh** [comment]
Nevim jestli to je stale aktualni vzhledem k zmenam v chovani editoru

**Comment by luckajirku** [comment]
Ta možnost editovat metadata na všech úrovních rovnou v režimu procházení je super, díky! 
Tím už je pro nás zbytečný ten režim detailu, který se využíval opravdu jen pro popis na titulové úrovni. 
Ten Honzou zmíněný rozdíl (Režim detailu: ve všech panelech stejný objekt x Režim procházení: v levém panelu potomci, v pravém jeden z potomků) - vzhledem k tomu, že v režimu procházení jde zapnout třetí panel a můžeme si tak k jakémukoli objektu ve struktuře zapnout třeba metadata + xml apod., tak využití pro ten režim detailu prostě nevidíme. 
Co na to ostatní knihovny?

Co bychom ale pořád rádi každopádně, to je přejmenování toho Režimu procházení na Vazby (a pokud z nějakého - nám skrytého - důvodu musí zůstat režim detailu, pak ten přejmenovat na Metadata).

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím, koukneš na to za nás? Děkuji.

**Comment by luckajirku** [comment]
Kdyby byl jen jeden režim, šlo by pak vrátit i původní praktičtější rozložení obrazovky - první sloupec: popis, druhý sloupec: skeny, třetí: velký náhled, nebo by tomu něco bránilo?

**Comment by albertoh** [comment]
To je na diskuzi. 
To by znamenalo velkou zmenu v logice jak aplikace naklada s oknami.
Nicemu se nebranim, ale je to velka zmena.

**Comment by nezbedova** [comment]
Já jsem pro staré zobrazení. Psát něco mezi skeny a náhledem znamená, že jezdím očima z jedné strany na druhou, což zdržuje a je nepohodlné.

**Comment by luckajirku** [comment]
OK, zkusím to shrnout.

1. **Zrušení režimu detailu**
- počítám, že to spadá pod "velkou změnu" a odkládá se na podzim, ale tak by bylo fajn teď udělat aspoň změnu popisků viz 2.

2. **Popisky při najetí myši:**

 - Režim detailu - změnit na Metadata
 - Režim procházení - změnit na Vazby
 - plus ještě druhý sloupec - velké M / Metadata - popisek změnit z Metadata na Popisná metadata

Jestli teda souhlasí i ostatní - nebo jestli máte pro Vazby lepší pojmenování - vycházím z toho, na co jsme zvyklí...

3. **Rozložení obrazovky, sloupce:**

A co se týká větší změny, aby se vrátilo osvědčené rozložení místo toho, které vzniklo bez konzultace s uživateli, to stejně musíme nechat na podzim. Ale určitě bychom chtěli, aby to nezapadlo - a aby se povedlo zrušit ten přebytečný režim plus vrátit sloupce do logického pořadí.

**Comment by nezbedova** [comment]
Souhlasím s @luckajirku

**Comment by luckajirku** [comment]
Popisky jsou OK - a na zbytek se teda budeme těšit na podzim:-).

**Comment by albertoh** [comment]
Popisky jsou zmenene

**Comment by nezbedova** [comment]
Děkujeme. Zbytek stačí na podzim.

**Comment by ZdenkaSera** [comment]
@albertoh Tady bych vzhledem ke komentářům výše také přidala Development do 30.11.  Souhlasíte?

**Comment by albertoh** [comment]
Ne :)
Bod 3, "Rozložení obrazovky, sloupce:" je velke
To bude znamenat celkem premyslet jak client ma vypadat. Je to velky zasah, predelat celove.
Musime nejdrive o tom mluvit, jak by to vsechno melo vypadat

**Comment by ZdenkaSera** [comment]
@albertoh Dobrá 😉

**Comment by luckajirku** [comment]
Jen na okraj - i když tomu dáme štítek návrh na rozšíření, tak to pořád není skutečné rozšíření/vylepšení, o kterém by se mělo hlasovat, ale návrat k původnímu osvědčenému rozložení, které bylo nevyžádaně změněno.

**Comment by ZdenkaSera** [comment]
Issue zavírám, navazuje  na něj issue [238](https://github.com/proarc/proarc-client/issues/238)
