### ISSUE TITLE
Chybí hláška o načítání u hromadného výběru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#112]
Pokud v Importu vyberu víc než jeden soubor pro načtení, a dám Načíst, neobjeví se info o načítání. Soubory se načítají. Není to chyba, ale je to divné. prosím přidat hlášku.

**Comment by albertoh** [comment]
Nemuzu reprodukovat (nebo nerozumim)
Kdyz dam "Načíst", vidim tohle:
![image](https://user-images.githubusercontent.com/5946836/155128439-a172b44a-9339-4491-af91-4bb43a20e984.png)

Kde je problem?

**Comment by ZdenkaSera** [comment]
Znovu otestovat, přidat komentář do issue - při hromadném načítání hláška nereaguje po odkliknutí.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím o upřesnění. Děkuji.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím, koukla bys na to? Díky.

**Comment by nezbedova** [comment]
Toto je už funkční. Původně se ta hláška nezobrazovala. možná jen u mě.

Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
