### ISSUE TITLE
STT nelze udělat popis jednotlivých stran

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#113]
Není kam zapsat metadata stran. 

![obrazek](https://user-images.githubusercontent.com/13831946/117039672-52c6c000-ad09-11eb-89ac-3f04dbcee990.png)

**Comment by honza-rychtar** [comment]
Opraveno. Zobrazení a editace STT stranu už funguje. Nicméně stále nefunguje hromadná editace STT stran - to musíme opravit v jádře Proarcu.
#102

**Comment by nezbedova** [comment]
Popis jednotlivých stran STT lze udělat. Navrhuji toto issue zavřít a na hromadnou editaci stran vytvořit nové.
