### ISSUE TITLE
Chybí hláška o nevyplnění pole

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#114]
Při metadatovém popise titulu přidám identifikátor Čárový kód. Ale zapomenu ho vyplnit. Po kliknutí na Uložit se neobjeví žádná hláška, ale přidaná neúplná tabulka zmizí.

Prosím přidat hlášku.

**Comment by honza-rychtar** [comment]
Pokud se přidá identifikátor, tak už je potřeba vyplnit jeho hodnotu, která má povinnost **M**.
Tohle řeší validace, která bude v příští verzi.

<img width="888" alt="Snímek obrazovky 2021-05-25 v 12 36 32" src="https://user-images.githubusercontent.com/1178142/119484004-e2362080-bd55-11eb-81e6-5e923aa6c46f.png">

**Comment by SmejkalovaAnna** [comment]
Zásadní problém, trvá stále i ve verzi 1.0.8 (6.9.2021)

**Comment by honza-rychtar** [comment]
@SmejkalovaAnna U kterého dokumentu vám to nefunguje? Ve verzi 1.0.8 se to chová jako na screenshotu výše.

**Comment by luckajirku** [comment]
Za nás OK, hláška tam je.

**Comment by nezbedova** [comment]
Hláška tam je.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
