### ISSUE TITLE
Dotaz na Profil - Identifikátory

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#115]
Jak funguje nastavení Identifikátoru v profilech? Co se stane (má stát), pokud si nastavím preferovaný identifikátor Čárový kód?

**Comment by honza-rychtar** [comment]
Preferované identifikátory, jazyky, typy stran a místa uložení se v pak u daných polí nabízí úplně nahoře, za ně se pak abecedně zařadí zbytek. 
Konkrétně v případě nastavení jako preferovaný identifikátor Čárový kód se nestane vlastně nic, protože Čárový kód je první v abecedě, takže se zobrazí nahoře i bez nastavených preferovaných identifikátorů.

**Comment by nezbedova** [comment]
Děkuji. Navrhuji zavřít.
