### ISSUE TITLE
Dotaz na tlačítko

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#116]
K čemu je u autora označené tlačítko? není u něj nápověda a je šedivé, nelze ho použít. Ani u vyplněného záznamu ani u prázdného záznamu.

![obrazek](https://user-images.githubusercontent.com/13831946/117042929-ddf58500-ad0c-11eb-9cfe-a84334b3de16.png)

**Comment by honza-rychtar** [comment]
Rozdělí to Celé jméno z jednoho pole na Jméno a Příjmení ve dvou polích.
Takže můžu vložit celé jméno a rozdělit ho, než to po částech vkládat.
<img width="626" alt="Snímek obrazovky 2021-05-08 v 19 30 33" src="https://user-images.githubusercontent.com/1178142/117548255-45c10e00-b034-11eb-8125-9469147d696b.png">

<img width="625" alt="Snímek obrazovky 2021-05-08 v 19 31 14" src="https://user-images.githubusercontent.com/1178142/117548260-48bbfe80-b034-11eb-8421-d74a6471f74e.png">

**Comment by nezbedova** [comment]
Děkuji za vysvětlení a přidanou nápovědu.

Navrhuji zavřít.
