### ISSUE TITLE
Chyba - lze provést export pro Krameria bez čísel stran!

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#117]
Že lze připojit skeny bez čísel stran k titulu, to lze považovat i za funkčnost. Ale, že je možné NEPOPSANÉ strany exportovat jako foxml pro Krameria, to už chyba je.

**Comment by honza-rychtar** [comment]
@SykoraLukas tohle by se mělo kontrolovat na backendu.

**Comment by SykoraLukas** [comment]
Opravím. Na backendu se bude kontrolovat, že strana má vyplněný typ, index a číslo. Takto by to bylo v pořádku?

**Comment by nezbedova** [comment]
@SykoraLukas ano. Děkuji.

**Comment by SykoraLukas** [comment]
Ještě se chci zeptat, zda se má kontrolovat i vzrůstající index tak jako u NDK a Archive exportu. Tedy vzrůstající, nepřerušený index.

**Comment by nezbedova** [comment]
Ano. To by bylo dobré. Děkuji.

**Comment by nezbedova** [comment]
Kontrola na chybu indexu funguje - testováno na STT

**Comment by nezbedova** [comment]
Funguje i NDK monografii.
@SmejkalovaAnna Pokud to půjde i na Periodiku, export ročníky, kdy ve výtisku bude chyba, může se zavřít.

**Comment by SmejkalovaAnna** [comment]
U NDK Periodika funguje, nepustí to bez čísel stran a hlídá to i čísla indexů.

**Comment by ZdenkaSera** [comment]
Domluvili jsme se na přidání štítku, kdo otestoval (zatím jen MZK, SVHK, KNAV) - je to proto, že issue je hodně a ztrácí se v tom přehled - a nechceme Vám pod rukama nechat uzavřít něco, co potřebujete případně taky přetestovat. Některá z issue nejsou jen o funkčnosti, ale i o šikovnosti nástroje pro práci, kde se názory můžou lišit. Děkujeme za pochopení. @luckajirku @emirova

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
