### ISSUE TITLE
Po přidělení urn.nbn nezmizí info

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#118]
Pokud dám přidělit urn.nbn naskočí tabulka, která nezmizí po dokončení. Zůstane tam. Lze ji jen Zrušit tlačítkem zrušit. A Zrušit a zavřít jsou rozdílné výrazy.

**Comment by honza-rychtar** [comment]
Opraveno. Zobrazí se hláška o úspěšném přidělení a tlačítko je teď Zavřít místo zrušit.

**Comment by nezbedova** [comment]
Ověřeno funguje. Navrhuji zavřít.
