### ISSUE TITLE
Chybí info o chybě (dřívějším vyplnění) urn:nbn

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#119]
Když zadám urn:nbn k dokumentu, který již urn:nbn má přidělené, neobjeví se info o tomto stavu. Zůstane tam viset tabulka. Viz issue #118

**Comment by honza-rychtar** [comment]
Opraveno, v případě chyby se zobrazí hláška s chybou a u neočekávané chyby se ještě přidá možnost zobrazit log.

**Comment by nezbedova** [comment]
Moc hezké. Takto má vypadat varovná hláška. Děkuji.

Navrhuji zavřít.
