### ISSUE TITLE
Neprojeví se změna názvu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc-client#12]
U jedné už založené NDK monografie jsem zkusila změnit název, připsala jsem za název "1". Změna se uložila, ale nikde, kromě formuláře a xml se to neprojevilo. Mělo by se to změnit taky v seznamu v "hledat".
![zmenanazvu](https://user-images.githubusercontent.com/21309201/79309569-cc232300-7efa-11ea-95c1-0840025d7dd5.jpg)

![zmenanazvu2](https://user-images.githubusercontent.com/21309201/79309585-d04f4080-7efa-11ea-9963-8724c84c85f8.jpg)

**Comment by krizovj** [comment]
Tak, až teď jsem si všimla, že jsou tam dokonce tři verze toho názvu :D 
Logan Museum
Logan Museum bulletin
Logan Museum bulletin 1

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 28.7.
