### ISSUE TITLE
Přílohy k číslu vs k ročníku a jejich zakládání jen na správném místě 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#121]
Jsem v čísle periodika a nechá mě to založit pod tím číslem přílohu k ročníku. Mělo by to nabízet jen přílohu k číslu a jen přílohu k číslu taky nechat pod výtiskem uložit.
Stejně tak pod ročníkem mě to nechalo bez varování založit přílohu k číslu. Tam bych zase čekala, že když jsem pod ročníkem a dám vytvořit přílohu, že to automaticky vytvoří přílohu, která bude mít v žánru předvyplněné "příloha k ročníku", resp. nebude nabízet jinou možnost, nebo aspoň při pokusu o uložení upozorní, že dělám něco, co není OK. 
Ta tabulka povolených vazeb ještě není zapracovaná, nebo u těch příloh to nejde?

**Comment by honza-rychtar** [comment]
On je to v ProArcu (i v Krameriovi) pořád jeden a ten samý model **ndkperiodicalsupplement**, ať už je pod ročníkem nebo pod číslem. Takže i podle tabulky vazeb je tento model povolen pod číslem a ročníkem.

Jediný rozdíl je pak v hodnotě `genre.type` - **volume_supplement** nebo **issue_supplement** a to bychom mohli předvyplnit při vytvoření nové přílohy podle nadřazeného modelu. @SykoraLukas Co myslíš?

@luckajirku  Mají se přílohy pod číslem a pod ročníkem ještě nějak lišit?

Kontrolu před uložením na správnou hodnotu podle nadřazeného modelu můžeme přidat. 
Teď se dělají jen kontroly na přítomnost M pole (podle standardu a modelu), ale budeme přidávat i další kontroly, které už budou obsahovat nějakou vyšší logiku. Jako např. kontrola formátu data u čísla periodika.

**Comment by honza-rychtar** [comment]
Takže po domluvě:
- na klientovi se udělá kontrola obsahu `genre.type` podle nadřazeného modelu před uložením přílohy
- v jádře se udělá automatické vyplnění `genre.type` podle nadřazeného modelu při vytvoření přílohy

**Comment by luckajirku** [comment]
Předvyplnění funguje správně.
Na ty kontroly bude další issue (resp. issues - 1 v klientovi a 1 v jádře)? Pokud ano, lze pak toto zavřít, pokud ne, necháme zatím otevřené.

**Comment by SykoraLukas** [comment]
Ano, prosím o založení issue na kotnroly jak v jádře tak v klientovi.

**Comment by ZdenkaSera** [comment]
Přetestovat v KNAV, uzavřít.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, prosím, zkusila bys ty přílohy vs předvyplňování genre.type podle umístění? Děkuji.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím o test, děkuji.

**Comment by luckajirku** [comment]
předvyplňování funguje, ale ještě je potřeba založit issues na ty kontroly - ať to se zavření tohohle pak nezapadne. 
Teď pod číslem založím přílohu - předvyplní se OK příloha k číslu, pod ročníkem příloha k ročníku, ale když ručně změním tu podčíslovou přílohu na přílohu k ročníku, bez problémů se přepíše.

**Comment by SmejkalovaAnna** [comment]
@luckajirku Lucko a je to teda košér vytvořit ještě jednu úroveň pod výtiskem? Já si právě nebyla jistá..... ale když řeknete, že ano, tak Vám budu věřit :)

**Comment by luckajirku** [comment]
@SmejkalovaAnna asi nechápu dotaz. Ano, je v pořádku založit pod číslem přílohu čísla. 
(A teď při založení přílohy se automaticky přednastaví se genre type - u přílohy čísla issue_supplement. Stejně tak pod ročníkem se automaticky založí příloha k ročníku a přednastaví se genre type volume_supplement.)
Co už není v pořádku, že ten typ pak jde ručně změnit na chybný a bez varování uložit.

**Comment by SmejkalovaAnna** [comment]
@luckajirku Dobře děkuji, to  mi stačí. Rozumím tomu.

**Comment by ZdenkaSera** [comment]
@albertoh  Viz výše ... Co už není v pořádku, že ten typ pak jde ručně změnit na chybný a bez varování uložit.

Prosím, nejsem si jistá, zda tuhle kontrolu při uložení máte zahrnutou v nějakém sběrném issue ke kontrolám  .. Díky.

**Comment by albertoh** [comment]
Jadro by to melo kontrolovat.
@SykoraLukas muzes kontrolu pridat do jadra?

**Comment by luckajirku** [comment]
ještě teď chybí hláška ve smyslu, že akci nelze provést - když ručně zkusím změnit žánr na špatný, problikne to a ve formuláři to vypadá, že změna proběhla (dokud ho znovu nenačtu), ale v xml zůstává ten správný.

**Comment by albertoh** [comment]
Hlaska ted vyskakuje. Akorat nevim, upozorneni je na neco pred tim:

![image](https://user-images.githubusercontent.com/5946836/173008700-848fc9a3-2e06-4a0b-a4ab-5e5e2863bc97.png)

**Comment by luckajirku** [comment]
Tak špatně zvolený objekt na test je jedna věc, když to otestuju na příloze, která nemá jiný problém, a změním přílohu ročníku na přílohu čísla, vyskočí mi toto, a to je OK: 
Varování
MODS rules: Špatná hodnota v elementu "Genre/type". Očekávána hodnota "type=volume_supplement", ale nalezeno "type=issue_supplement". 
Na druhou stranu já bych teda nedávala varování s možností to překonat a uložit i přes hlášenou chybu. Kdyby to byly dva různé modely, což bohužel nejsou, tak bychom tohle vůbec neřešili a pod ročníkem by šla založit/uložit jen příloha ročníku a pod číslem příloha čísla.

**Comment by luckajirku** [comment]
Jen to radši shrnu - tady je potřeba změnit hlášku, nesmí to jít překonat/uložit přes varování.

**Comment by luckajirku** [comment]
To asi je zbytečné, nepřekročitelná hláška by měla stačit.

**Comment by albertoh** [comment]
Abych mohl implementovat na klientovi hlasku neprekrocitelnou potreboval bych od serveru ruzne kody chyb pro rozslyseni:
 prekrocitelne
 neprekrocitelne

@SykoraLukas je to mozne?

**Comment by albertoh** [comment]
Opraveno.
Ted pokud server vrati "cantIgnore" neni moznost ulozit

**Comment by luckajirku** [comment]
Za nás OK, funguje a hází správné hlášky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím o test u nás po instalaci nových verzí PA. Díky.

**Comment by luckajirku** [comment]
Tak ještě jsme na něco narazili. Pokud uložím se správným žánrem a pak chci změnit, tak ta hláška funguje jak má.
ALE - když se změní žánr přímo při zakládání v editačním formuláři, tak to nechá uložit chybný typ přílohy bez připomínek.

**Comment by albertoh** [comment]
@SykoraLukas kouknes na to? Volani je jine tady, ne object/mods/custom (PUT) ale rovnou object (POST)

**Comment by SykoraLukas** [comment]
Při tvorbě objektu se nevaliduji metadata. Je to kvůli tomu, jak to funguje v Jádře. Když stahuji nevalidní data z katalogu, tak pokud by byli nevalidní, tak by nešel založit objekt. Proto se validují data až z formuláře. 

V novém klientovi jak se přidalo to editování dat objektu, který ještě není vytvořen tak v něm se také ještě nevalidují data, až při  práci ve formuláři se validují.

**Comment by luckajirku** [comment]
Díky za vysvětlení. Akorát je to trochu matoucí. Když se pokusím uložit neúplný nově založený formulář, tak mi vyhodí hlášku "Nevalidní data. Nevalidní data, přejete si dokument přesto uložit?" Chápu to teda správně, že v zatím neuloženém novém objektu to kontroluje jen povinnost - a tady to "nevalidní" znamená, že nejsou vyplněna všechna povinná pole, bez ohledu na správnost hodnot, kdežto v už uloženém objektu se kontroluje jak povinnost, tak správnost vyplnění? Nebylo by pak lepší ty hlášky rozlišit?

**Comment by SykoraLukas** [comment]
Ano je to tak jak píšeš. Ale spíš to uděláme jinak. Z nového klienta při tomhle ukládání dáme nový parametr při volání aby se to validovalo (povinnost a správnost), i když je to nový objekt. Ve starém by to bylo tak, že se tenhle parametr nepřidá a tedy se zachová stejný postup jako nyní. Šlo by to takhle?

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Vypadá to, že to funguje dobře....

**Comment by SykoraLukas** [comment]
@luckajirku  nasadil jsem změnu, zkus jestli to takto vyhovuje.

**Comment by luckajirku** [comment]
@SykoraLukas super, takhle je to lepší. 
Akorát při odchodu z neuloženého formuláře se nám točí kolečko, dávám to k issue, kam to asi spíš patří https://github.com/proarc/proarc-client/issues/33#issuecomment-1167038878

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
