### ISSUE TITLE
Přidat kontroly strukturálních metadat

### ISSUE THREAD

**Issue by zabak** [proarc/proarc-client#122]

**Comment by erikamirova** [comment]
Potřebovali bychom přidat do ProArcu podobné kontroly metadat, jako probíhaly v lince NDK. Ideální by za nás byly tyto: 

- **test typu stran** - Kontroluje, jestli jsou označeny povinné typy stran (musíme si určit, které typy stran budou povinné. V lince NDK to byly obsah a titulní strana, protože se na to zapomínalo. 
- **test paginace** - Kontroluje posloupnost, tzn. pokud mi v nějaké číselné řadě něco chybí, vyhodí to hlášku. Je potřeba nadefinovat všechny možné kombinace zápisu číselné řady, vč. abecedního, prefixů, sufixů... 
- **celkový počet stran** - Napíše celkový počet stran dokumentu a vyhodí chybu, pokud je počet stran lichý.
-  **test součástí periodika** - Kontroluje se návaznost čísel periodika a vyhodí hlásku, pokud není dodržena posloupnost, stejně tak u příloh, které jsou kontrolovaný zvlášť ve své řadě. Je tam i kontrola na vyplnění podnázvu u příloh, to se často zapomínalo.

Lze některé z těchto kontrol nasadit i to ProArcu?

**Comment by luckajirku** [comment]
Obsah jako povinný typ strany je nesmysl. Titulů, které obsah nemají, je dost.

**Comment by erikamirova** [comment]
Pokud titul nemá obsah, tak to nevadí a nemusí se označovat. Jde jen o upozornění. U starých tisků se také vyskytují případy bez titulního listu.

**Comment by luckajirku** [comment]
ad test paginace "nadefinovat všechny možné kombinace zápisu číselné řady" - absolutně mi není jasné, jak lze nadefinovat všechny možnosti. Když do standardní řady nám vstupují např. strany s ilustracemi, kde přidáváme a, b atd., mění se v rámci svazku číslování na římské a pak zase zpět apod.

**Comment by erikamirova** [comment]
Máte pravdu, že v případě těch ilustrací by to nešlo. V lince NDK nám to v těchto případech vyhazovalo chybu v paginaci a pracovník věděl, že to chyba není. Je otázka, jestli je toto žádoucí. U některých svazů se může stát, že na uživatele vyskočí třeba 10 chybových hlášek.

**Comment by ZdenkaSera** [comment]
typ stran - ne automatická kontrola, vyvolaná uživatelem (PŽ)
Zvážit podle modelů

**Comment by ZdenkaSera** [comment]
Přidávám zatím štítek "návrh na rozšíření" s tím, že část požadavku je pokryta v jiných issues a tady je třeba domluvit se na zbytku nebo issue zavřít.

**Comment by erikamirova** [comment]
@ZdenkaSera Pokud to jiné knihovny nechtějí, tak to chápu. Pro nás to v tuto chvíli není priorita, takže to můžeme klidně uzavřít.
