### ISSUE TITLE
Chybí hlídání položek u čísla periodika a strany

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#123]
Chybí hlídání a označení nevyplněných mandatory položek u čísla periodik a ten formulář se mi taky moc nezdá, prosím prohlédněte to a porovnejte se šablonou. A když smažu číslo strany v tzv. Vazbách ( editační okno metadat ) a přeuložím, tak mi to nezahlásí, že to chybí.... až při exportu.

**Comment by honza-rychtar** [comment]
> Chybí hlídání a označení nevyplněných mandatory položek u čísla periodik

Nechybí. M pole se hlídají.
<img width="887" alt="Snímek obrazovky 2021-09-28 v 21 21 38" src="https://user-images.githubusercontent.com/1178142/135152213-0db56d35-7f34-4d65-89e9-2eed8512de4b.png">

> a ten formulář se mi taky moc nezdá, prosím prohlédněte to a porovnejte se šablonou.

Šablona čísla kopíruje standard. Mě se to taky nezdá, protože tady se standard dost rozchází s tím, co se používá v Krameriovi. Ani jedno z povinných polí u čísla periodika Kramerius nepoužívá a na druhou stranu hlavní dvě pole, která Kramerius používá (`titleInfo.partNumber` a `originInfo.dateIssues`) povinná nejsou.

<img width="1095" alt="Snímek obrazovky 2021-09-28 v 21 16 58" src="https://user-images.githubusercontent.com/1178142/135158382-ab16226f-07dd-4356-ba74-0be001cf6fe2.png">
<img width="1052" alt="Snímek obrazovky 2021-09-28 v 21 18 45" src="https://user-images.githubusercontent.com/1178142/135158406-25838a84-bccb-4cab-8d1e-1267e95905e3.png">

> A když smažu číslo strany v tzv. Vazbách ( editační okno metadat ) a přeuložím, tak mi to nezahlásí, že to chybí

To se týká validace strany, ta opravdu chyběla. Dodělám.

**Comment by ZdenkaSera** [comment]
je v 1.0.9

**Comment by honza-rychtar** [comment]
- validace čísla je od verze **1.0.8**
- validace strany je od verze **1.0.9** #126 
- hlídání `partNumber` a `dateIssued` budeme řešit tady #124

Takže toto je k uzavření.

**Comment by luckajirku** [comment]
Za nás v pořádku, může se zavřít.
