### ISSUE TITLE
Validace stran

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#126]

**Comment by honza-rychtar** [comment]
Hotovo ve verzi **1.0.9**

<img width="784" alt="Snímek obrazovky 2021-09-29 v 11 08 39" src="https://user-images.githubusercontent.com/1178142/135238898-1f042d47-c97d-433c-9711-d08ca3974d48.png">
<img width="404" alt="Snímek obrazovky 2021-09-29 v 11 08 49" src="https://user-images.githubusercontent.com/1178142/135238912-fedcaa80-9424-4d72-8f62-f971f5edbf2a.png">

**Comment by luckajirku** [comment]
Za nás v pořádku, může se zavřít.
