### ISSUE TITLE
Nakladatel - NDK Vícedílná m. chybí Místo

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#128]
V prázdném formuláři NDK Monografie chybí pole pro Místo, když stáhnu záznam z katalogu, tak se mi placeTerm propíše do MODSu správně, ale ve formuláři to pole chybí.....

**Comment by SmejkalovaAnna** [comment]
Tak v NDK Monografie v Nakladatel už pole Místo je, ale v NDK Vícedílná monografie stále chybí....

**Comment by luckajirku** [comment]
U vícedílky toho nefunguje víc, předpokládám, že se to dá do pořádku, až budeme mít k dispozici nový NDK standard (mon 2.0), podle kterého se vícedílky upraví komplet.

**Comment by ZdenkaSera** [comment]
Otestovat v souvislosti s #48

**Comment by SmejkalovaAnna** [comment]
Ve Vícedílce stále Místo chybí....je už nový standard pro Vícedílky?

**Comment by ZdenkaSera** [comment]
@SykoraLukas  Díky.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
