### ISSUE TITLE
Přesun stran mimo dokument

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#129]
Když chci přesunout strany, co jiného dokumentu, tak mi vyběhne okno, kde si vyberu, kam to je chci, to je super. Ale v tom okně s nabídkou nemohu řadit dokumenty podle datumu nebo vlastníka, jako je to v hlavním okně.  Šloby to prosím udělat, alespoň podle datumu vytvoření a vlastníka ( ne obě najednou, ale buď klepnu na jeden nebo druhý parametr ). Hodně by to usnadnilo práci.

**Comment by SmejkalovaAnna** [comment]
Tak podle vlastníka lze to vytřídit, ale seřadit podle datumu od nejstarších nebo nejmladších nelze.... Chtělo by to, aby to bylo jako #15.

**Comment by luckajirku** [comment]
Za nás je tohle nutná věc, aby to šlo seřadit podle data.

**Comment by luckajirku** [comment]
souvisí ještě s tímhle dříve založeným: https://github.com/proarc/proarc-client/issues/104

**Comment by albertoh** [comment]
Pridam moznost razeni kliknutim na header

**Comment by SmejkalovaAnna** [comment]
Funguje i na Periodiku...
