### ISSUE TITLE
Přidat ročník nebo číslo

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc-client#13]
Mám možná blbý dotaz, ale takhle na první pohled mi to není jasné, tak se radši zeptám :)

Když jsem tady, v režimu procházení, kde jsou všechny ročníky a pak všechna čísla, jakým způsobem přidám nový ročník nebo číslo? Myslím, že z tohoto místa by určitě měla být možnost přidat nový objekt:
![přidatnovy](https://user-images.githubusercontent.com/21309201/79310950-02fa3880-7efd-11ea-8cc2-e6c15e65943b.jpg)

**Comment by luckajirku** [comment]
Stejný problém máme u zakládání kapitoly pod monografií. Zkrátka problém se založením jakéhokoli podřazeného objektu - nevytvoří se na daném místě ve struktuře, ale kdesi ve vzduchoprázdnu.

**Comment by luckajirku** [comment]
Když zkusíme založit ročník periodika pod periodikem, nevytvoří se s vazbou na titul, ale kdesi - vyhledat přes model:NDK ročník lze, pod titulem ale není.

**Comment by luckajirku** [comment]
Ročníky, čísla u periodik OK.
