### ISSUE TITLE
Kurzor ve formuláři a MODsu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#130]
Šlo by udělat, že by se mi označil nějak barevně přesný element v MODsu na základě aktuálního umístění kurzoru ve Formuláři? Byla by to hezká vizuální pomůcka uživatele.... ale nevím, jak moc je to náročné na vývoj.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, není Tvůj požadavek totéž, jako tady [#63](https://github.com/proarc/proarc-client/issues/63) ?
Pokud ano, Markétin uzavřu a sem dám štítek "návrh na rozšíření".

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko je to to samé.... zavři to prosím... děkuji.

**Comment by SmejkalovaAnna** [comment]
Zatím se nepodbarvuje.....

**Comment by luckajirku** [comment]
a k tomu stejnému se váže ještě issue https://github.com/proarc/proarc-client/issues/94 (před založením nového by bylo lepší projet ty stávající, jestli se to už někde neřeší).

**Comment by albertoh** [comment]
Na rozdil od #94, implementace bude dost slozita.

**Comment by ZdenkaSera** [comment]
Při schůzce shoda, že lze uzavřít :-)
