### ISSUE TITLE
Přidání funkce korekce OCR s využitím PERO OCR

### ISSUE THREAD

**Issue by zabak** [proarc/proarc-client#131]
Na dnešním workshopu projektu PERO jsme domluvili přidání nového upload API do webové verze PERO OCR DCGM/pero_ocr_web#70 .

Cílem je umožnit v ProArcu v rámci editace metadat korekce OCR. Workflow: na vstupu se předpokládá dokument včetně OCR (lze vytvořit přes PERO OCR API). Při editaci metadat bude uživateli umožněno přes volbu "vylepšit OCR" předat vybrané stráky do webové verze PERO OCR, tam provést nové OCR (například i s vybráním nového modelu - use case: starý tisk, kde jsou dvě rukopisné stránky - celý se udělá textovým modelem, ty dvě stránky je potřeba udělat rukopisným), ručně opravit výsledek a opravené OCR stáhnout zpět do editovaného dokumentu.

Další use-case (reálný, z KNAV): digitalizuji staré tisky, OCR titulních listů chci ale mít zcela správně = je potřeba manuální korekce OCR).

Na straně PERO OCR web se vytvoří účet pro danou instalaci ProArcu a každý operátor si tam vytvoří svůj účet. Při volání API se autentizuje účtem pro tu instanci ProArcu a pošle jako parametr e-mail = login daného operátora a název dokumentu (nebo uuid, čárový kód...) - ten slouží pro orientaci operátora. PERO OCR převezme obrázky a vrátí id úlohy. Do budoucna možná v api přibudou parametry na přímé spuštění OCR (volba modelu apod), zatím ale toto v API nebude.

Po uploadu vybraných obrázků (a kontrole přes status API, pokud bude existovat na straně PERO OCR) uvidí operátor link do PERO OCR (využije se Id úlohy vrácené při uploadu obrázků). Vedle bude další volba, pro stažení hotových OCR souborů (zase přes Id úlohy). Toto bude zašedlé, dokud nebudou výsledné OCR k dispozici. Operátor se proklikne do PERO OCR, tam spustí OCR dle svých požadavků, provede korekturu a vrátí se do ProArcu, kde vyvolá stažení hotového OCR. To se stáhne a nahradí se jím stávající OCR soubory pro dané stránky.

Prosím všechny o připomínky k tomuto návrhu.

**Comment by nezbedova** [comment]
Nejen titulku bychom chtěli mít správně. Dalšími adepty na přesný přepis jsou obsah, rukopisná poznámka na předních deskách nebo některé názvy kapitol.

**Comment by luckajirku** [comment]
Pro nás tohle není v dohledné době využitelné.

**Comment by zabak** [comment]
Na straně PERO je implementace API pro tento use case hotová, API kyy poskytneme na vyžádání. Dokumentace zatím není sepsaná, doplníme.

Zdrojový kód https://github.com/DCGM/pero_ocr_web/blob/master/app/ocr_api/routes.py

Volání jsou:

curl "$SERVER_URL/ocr_api/new_document/test_document/someone@somewhere.com,someone@somewhere.com" --request POST --header "api-key: $API_KEY"   # tohle vrací DOCUMENT_ID, adresy doporučuji zaměnit za skutečné uživatele :)

curl $SERVER_URL/ocr_api/upload_image/$DOCUMENT_ID --request POST --header "api-key: $API_KEY" -F file=@00000003.jpg

curl $SERVER_URL/ocr_api/list_documents --request GET --header "api-key: $API_KEY"

curl $SERVER_URL/ocr_api/document_images/$DOCUMENT_ID --request GET --header "api-key: $API_KEY"

curl  $SERVER_URL/ocr_api/get_results/text/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"
curl  $SERVER_URL/ocr_api/get_results/page/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"
curl  $SERVER_URL/ocr_api/get_results/alto/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"

curl  $SERVER_URL/ocr_api/delete_document/$DOCUMENT_ID --request POST --header "api-key: $API_KEY"

**Comment by ZdenkaSera** [comment]
Ŕešení/testy v issue https://github.com/proarc/proarc-client/issues/484, tady pouze podklad - navrhuji zavřít.

**Comment by ZdenkaSera** [comment]
@zabak Můžeme zavřít?

**Comment by ZdenkaSera** [comment]
Zavírám jako duplicitní + dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
