### ISSUE TITLE
hromadný výběr stran se shiftem

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#132]
Při hromadném výběru stran přes shift přidávám stránky. Zjistím, že jsem o pár stran "přejela", chci se vrátit, ale nejde to. Můžu nechat označený výběr a ty "chybné" "odznačit" přes ctrl, a nebo celou (správnou) množinu označit přes shift znovu. Ale proč tak složitě? V současném rozhraní se při zapnutém shiftu prostě vrátím o pár řádek výš - a výběr se sám upraví.

**Comment by albertoh** [comment]
Opravim

**Comment by albertoh** [comment]
Upravil jsem chovani vyberu pomoci shiftem. Otestujte, a reknete jestli tak to vyhovuje

**Comment by nezbedova** [comment]
Můžete mi, prosím, napsat, ke které monografii jsou připojené skeny, abych to mohla otestovat? Děkuji.

**Comment by albertoh** [comment]
Napriklad Řecko:
https://proarc.inovatika.dev/document/uuid:797a78c3-8ff2-4caa-ae0f-7a21febe278f

**Comment by nezbedova** [comment]
Už jsem něco našla v uložených dávkách.

**Comment by nezbedova** [comment]
Funguje. I odstranění výběru jednotlivých stran pomocí Ctrl.

**Comment by ZdenkaSera** [comment]
Otestováno, uzavírám na schůzce.

**Comment by luckajirku** [comment]
Tohle už zase přestalo fungovat, znovu otevírám.

**Comment by luckajirku** [comment]
Ne ne, předtím to fungovalo:-). Ale už teď to zas funguje, tohle je ono, díky.

**Comment by ZdenkaSera** [comment]
Zavírám vzhledem k návrhu na zavření od autora issue a zahrnutí opravy v již vydané verzi.
