### ISSUE TITLE
Nelze přesouvat skeny mezi objekty

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#134]
Nové rozhraní by mělo umožňovat přesuny skenů mezi jednotlivými objekty. Funkce tam je (viz obrázek), ale nefunguje. Potom, co si zvolím objekt, pod který chci skeny přesunout, ProArc stále načítá a nic se neděje.

![image](https://user-images.githubusercontent.com/37616300/151522646-58237e67-d4f2-4023-b42d-6db60ef85774.png)

**Comment by luckajirku** [comment]
@erikamirova jak jsem to zkusila, to kolečko se točí, když v tom okně vyberu mám vybraný jen titul. Pokud vyberu přílohu, uloží se bez problémů. Jen mě napadá, jestli není problém s vazbou na povolený/nepovolený model - dělá vám to i při přesunu do takového typu objektu, kde je strana pod tím daným objektem je povolený model?

**Comment by erikamirova** [comment]
@luckajirku Děkuji za radu, máte pravdu, to bude těmi stranami. Nenapadlo mě to. Zpracováváme staré hudebniny pod modelem NDK hudebnina (STT hudebnina nám dělala nějaké problémy v Krameriu, to ještě řešíme) a strany jsou STT strany. Při napojení STT skenů pod NDK model to nedělá problémy. Ale pokud chci STT strany přesunout z jedné NDK hudebniny do druhé, tak to nefunguje, protože to asi není povoleno.

Zkoušela jsem teď přesunout klasické strany v rámci dvou NDK monografií a šlo to bez problému.

**Comment by erikamirova** [comment]
Přesun mezi objekty funguje. Opravdu byl problém s vazbou na povolený/nepovolený model.
