### ISSUE TITLE
URN:NBN

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#136]
Při výběru knihovny při registraci Urn:Nbn se špatně předávají hodnoty o knihovně která chce registrovat.

Správně je parametr: resolverId

Nový klient ale používá: resolverID.

Jde o závažnou chybu, která brání používání. Nutné opravit co nejdříve.

**Comment by albertoh** [comment]
Hotovo. Prosim @SykoraLukas  o testovani

**Comment by ZdenkaSera** [comment]
Otestovat uživatelsky (ruční urn:nbn, zneplatnit, přidat nové z czidla).

**Comment by ZdenkaSera** [comment]
Na Inovatice jsem vyzkoušela - ručně přidělené urn:nbn šlo nastavit jako neplatné a automaticky se nechalo přidělit nové. Navrhuji uzavřít a následně přetestovat ve vlastním systému proti resolveru NK.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
