### ISSUE TITLE
Úpravy ve formuláři pro eMonografie

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#137]
Ve formulářích týkajících se emonografií jsem si všiml několika nesrovnalostí, které by bylo potřeba vyřešit, jinak není možné klienta pro jejich zpracovávání používat:

### NDK Vícedílná eMonografie
- v části “Nakladatel”: nemá být pole Edice nazváno “Edice” ale spíš “Vydání” (současný stav je trochu matoucí...)
- chybí možnost vyplnit originInfo/place
- mezi identifikátory nelze vybrat DOI

### NDK Svazek eMonografie
- v části “Nakladatel”: nemá být pole Edice nazváno “Edice” ale “Vydání”
- v části “Fyzický popis” by se měla dát hodnota pro Formu (<mods:form>) vybrat z kontrolovaného seznamu, jako je to ve starém rozhraní
- v části Autor by pro pole Křestní a Příjmení měla platit povinnost M (ne MA)
- V rámci originInfo nelze vyplnit eventType (viz vícedílná emonografie)
- mezi identifikátory nelze vybrat DOI

### NDK eKapitola:
- část Nakladatel odpovídající <mods:originInfo> nemá u kapitoly vůbec být
- stejně tak část Uložení (<mods:physicalLocation>) nemá u kapitoly být
- Fyzický popis - v části forma by nemělo být možné do pole hodnota doplnit nic jiného než hodnotu “electronic”
- mezi Identifikátory chybí DOI

Díky, FK

**Comment by tumovam** [comment]
Aktualizace k 2.6.2022... 
Testována verze klienta 1.0.10 (26.5.2022), jádro 3.8.1-ALFA na proarc.inovatika.dev

**NDK Vícedílná eMonografie**

- v části “Původ předlohy” (tzn. nakladatelské údaje) je stále matoucí překlad "Edice", lepší než by bylo "Vydání"
- povinnost vyplnění elementu "edition" je nyní "O", ale dle standardu má být "R"
- povinnost vyplnění elementu "originInfo-place" (Místo) má být MA, ne O
- mezi identifikátory chybí DOI, Handle, ISMN, URL 
- mezi identifikátory je navíc ID, LocalID - nevím, zda někdo využívá, proto raději ponechat?

**Comment by tumovam** [comment]
Aktualizace k 20.6.2022... Test v. klienta 1.1.0 (26.5.2022), build 20220620155628, jádro 3.8.1-ALFA, test na proarc.inovatika.dev

**NDK Vícedílná eMonografie**
- se zdá v pořádku
- jen mezi identifikátory už není ID, LocalID - stále nevím, zda někdo využívá a jestli by nebylo lepší tyto identifikátory ponechat... :)

**NDK eMonografie**
- v části "Původ předlohy" je "Point" nyní MA, ale dle standardu má být O
- v části "Původ předlohy" nejde přidat další "Point" (tzn. když vyberu "Point-start", není žádné plus (nebo ho nevidím), kterým by šlo přidat i "Point-end"
- v části "Původ předlohy"  je "Upřesnění data" (qualifier) nyní R, ale dle standardu má být O
- v části "Autor" chybí možnost "Usage" (hodnota "primary" nebo nic "-") , povinnost vyplnění O
- v části "Uložení" chybí "Note", "Usage" (oboje R)
- mezi identifikátory už není ID, LocalID
- trochu matoucí jsou 2x identifikátory (1. identifikátor (povinnost M), kde je UUID, ISBN,...) a 2. identifikátor (povinnost R), kde je classification/@authority a classification/@edition), ale máme to tak třeba i u kapitoly a očividně to nikomu jinému nevadí ;) 

**NDK eKapitola**
- v části "Název" vůbec nemá být "Typ"
- v části "Autor" je "Identifikátor autora" - O, dle standardu RA
- část "Jazyk" je nyní MA, ale má být R, ale pozor - "Jazyk" (= languageTerm) je správně M
- v části "Fyzický popis" - "Forma - Hodnota" prosím primárně předvyplnit hodnotu "electronic"
- v části "Fyzický popis" má být "Autorita" MA, ne M
- v části "Věcné třídění" má být Klíčové slovo/Předmětové heslo - O, ne M

Děkuji

**Comment by kerschfilip** [comment]
Aktualizace k 28.6.2022... Test v. klienta 1.1.0, jádro 3.8.1:

**NDK vícedílná eMonografie** je OK

**NDK svazek eMonografie**
- v části Autorů by měla existovat možnost, jak pod `<name>` vyplnit element `<etal>` - pro upozornění na to, že existuje více autorů, než pouze ti, kteří byli uvedeni v `<name>` elementu
- úplně chybí část odpovídající `<relatedItem>` -> bylo by možné to doplnit?
- v části “Název” je "Typ" nyní správně M, ale vytváří to problém - ačkoliv je totiž M v určitém případě je možné type vůbec nepoužít -> teď nám to v takových případech hlásí, že metadata nejsou kompletní
  - šlo by to, prosím, upravit tak, aby se dalo vybrat "nic" a v takovém případě atribut `type` do xml nepropisovat?
  - nebo (pokud by to bylo příliš složité) vrátit povinnost na MA

**NDK eKapitola**
- v části "Fyzický popis" - "Forma - Hodnota" prosím primárně předvyplnit hodnotu "electronic"

**Comment by albertoh** [comment]
Nasazeno na testu

**Comment by kerschfilip** [comment]
omlouvám se, tady to čeká hrozně dlouho na moje testování. 

**NDK vícedílná eMonografie** je OK

**NDK svazek eMonografie**  
Mám jen jednu připomínku k vyplňování autorů:  
Když vyplňuji korporátního autora, může se stát, že potřebuji použít 2x element `namePart`, třeba takto:
```xml
    <mods:name type="corporate">
        <mods:namePart>Univerzita Karlova</mods:namePart>
        <mods:namePart>Centrum pro ekonomický výzkum a doktorské studium</mods:namePart>
        <mods:nameIdentifier>olak2002113688</mods:nameIdentifier>
    </mods:name>
```
ale ve formuláři to udělat nejde, protože pole nazvané "Celé jméno" nemám jak duplikovat. Ve starém rozhraní vedle něj bylo plus, kterým to šlo: 
![image](https://user-images.githubusercontent.com/57805328/201631301-5b0a1688-2765-4a35-8ada-4fdb3dcb8746.png)

Zároveň v případech korporací, konferencí a rodin nelze vyplnit křestní jméno a příjmení, ale protože jsou M, tak mi při uložení vyskočí upozornění na nevalidní data. 

Stejně tak se tahle hláška ukáže, když vyplním jen element `etal`, což je ale povolená varianta. To ale asi není tak podstatné a ani časté... 

**NDK eKapitola** 
u autora nelze vyplnit `etal` (ale u kapitoly to asi nebude potřeba)

**Comment by kerschfilip** [comment]
výše uvedené připomínky jsou v aktuální verzi zapracovány (`Klient: verze v2.0.1 (17.02.2023)`). Issue tedy zavírám a děkuji
