### ISSUE TITLE
KWIS export

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#138]
Přidat mezi exporty volání KWIS exportu nad všemi objekty.

**Comment by albertoh** [comment]
Prosim @SykoraLukas napis format API volani

**Comment by SykoraLukas** [comment]
Nutné doplnit pro KWIS export pole  "Veřejně dostupné" viz Kramerius Export.
![image](https://user-images.githubusercontent.com/27210823/154944553-45be6a44-95e8-43de-aed7-7dde6be45786.png)

Volá se potom /api/rest/v1/export/kwis
s parametry:
- pid (uuid objektu, na kterém se volá export)
- policy (pokud je veřejně dostupný tak `policy:public` nebo `policy:private`)

**Comment by albertoh** [comment]
Hotovo. @SykoraLukas prosim o testovani

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, je tohle k uzavření? Možná to není otázka pro Vás - prosím tedy o předání. Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera Export pro Kramerius tam máme, ale nemůžeme to otestovat, protože nám nefungují exporty. Je to v řešení, tak snad to půjde co nejdřív. :)

**Comment by ZdenkaSera** [comment]
Je to k už testu, odebírám štítek "návrh na rozšíření".

**Comment by erikamirova** [comment]
@ZdenkaSera již vyřešeno
