### ISSUE TITLE
Sloupce - možnost přidat

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#139]
Možnost přidat sloupce v druhém okně ( po prokliknutí do editace metadat objektu ) 
![obrazek](https://user-images.githubusercontent.com/24409660/154023200-db5da8f3-991f-457e-814b-1151def8fb25.png)

**Comment by pavelkocourek** [comment]
Jde o přidání sloupce do této obrazovky, která je vložena do Issue? 
Ve starém klientovi bylo navíc možno vložit pole PID, to by se vešlo do zobrazení rovnou.

**Comment by SmejkalovaAnna** [comment]
Ano, prostě možnost přidat jakýkoliv sloupec s jakoukoliv informací, jako to jde u starého.... takže i s PID

**Comment by albertoh** [comment]
Pridano

![image](https://user-images.githubusercontent.com/5946836/167582543-25a9f93d-1f97-4bcf-ae9b-83859b637b70.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím o test, díky.

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto super, sloupce jdou přidat, ale i když mám zaškrtnutý PID, tak ten sloupec tam nevidím.... co dělám špatně? Díky

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
@albertoh Super, funguje, díky.

**Comment by luckajirku** [comment]
Když odeberu sloupec, rozkliknu třeba číslo periodika a pak se zas vrátím o úroveň výš, tak mám ten sloupec zpátky a musím ho zase odebrat. Totéž když některý přidám. To je chtěné chování? Nemělo by si to nastavení držet na té stanici nebo u uživatele během přihlášení?

A ještě by asi bylo dobré ty popisky (label, owner...) dát česky, ať je to jednotně.

**Comment by albertoh** [comment]
Upraveno

**Comment by luckajirku** [comment]
místo label je teď search.label

**Comment by albertoh** [comment]
Zkuste reload tvrdy (ctrl + f5)
![image](https://user-images.githubusercontent.com/5946836/168256013-527514ff-6f48-44d4-bedd-24411400c9c7.png)

**Comment by luckajirku** [comment]
> Zkuste reload tvrdy (ctrl + f5)

To jsem udělala několikrát, než jsem sem napsala. A zkusila i odhlásit/přihlásit, kolegyně to samé. Je to zvláštní, předtím to nepomáhalo, teď už je to OK. 

Jinak to držení nastavení teď funguje jak přesně - je to vázané na stanici?

**Comment by albertoh** [comment]
U uzivatele behem prihlaseni

**Comment by nezbedova** [comment]
To nevydrží moc dlouho. Pokud se během dne musím 3x přihlásit, tak si musím také vždy nastavit sloupce.

**Comment by ZdenkaSera** [comment]
@luckajirku @nezbedova Rozumím Vašim komentářům tak, že ideálně by měl mít uživatel možnost uložit si své nastavení a to by mělo zůstat platné při opakovaných odhlášeních/přihlášeních, dokud výběr sloupců cíleně nezmění a neuloží novou verzi? - Pokud ano, navrhuji zatím akceptovat stávající úpravu pro tento release a uložení konfigurace navrhnout jako další rozšíření.  Děkuji za názor ...

**Comment by luckajirku** [comment]
asi nejlepší by bylo vázat to na prohlížeč - stejně jako jsou třeba ty předvolby typů stran apod.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, je návrh @luckajirku realizovatelný? Děkuji.

**Comment by albertoh** [comment]
Ano. Udelam to

**Comment by albertoh** [comment]
Hotovo

**Comment by luckajirku** [comment]
Super, funguje.

**Comment by ZdenkaSera** [comment]
Funguje. Dávám návrh na uzavření - uzavřít až po otestování na vlastním systému.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
