### ISSUE TITLE
Zařízení

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc-client#14]
Zkoušela jsem přidat zařízení, ale neprojevilo se to. Ale po uložení se objevila hláška, že nové zařízení bylo vytvořeno. V seznamu zařízení ale nepřibylo. 

K zařízením mě ještě napadlo, jestli by bylo možné do toho jejich seznamu přidat datum, kdy byl ten záznam vytvořen a případně i změněn?

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 28.7.
