### ISSUE TITLE
Navigace - chybí

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#140]
Chybí navigace, co jsem chtěla, Hozna Rychtář to měl zapsané - aby nahoře byla vypsaná cesta od nejvrchnějšího objektu ( u vícedílů a Periodik )  Např. Biologie -> ročník 42 -> výtisk 1, aby to bylo zde: 
![obrazek](https://user-images.githubusercontent.com/24409660/154023840-2a9fba7d-e3bb-4454-979f-b670a4f50599.png)

**Comment by luckajirku** [comment]
Duplicitní issue, na tohle už je jedno neřešené issue založené tady: https://github.com/proarc/proarc-client/issues/73.
Zavírám.
