### ISSUE TITLE
Tlačítko SMAZAT a oprávnění uživatelů

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#141]
Administrátorovi se po kliknutí na tlačítko `SMAZAT` otevře dialogové okno, ve kterém má možnost objekt "smazat trvale z úložiště". Na to ale nemá právo - to má jen superadmin. Pokud ho zaškrtne a dialog potvrdí, prostředí klienta zamrzne - jakoby se načítá ale nikdy se nic nestane, objekt se nezmaže, ale ani se neukáže žádná chybová hláška

![image](https://user-images.githubusercontent.com/57805328/154482561-24a0df94-5dee-4306-aa83-ce293f6109ae.png)

**Comment by ZdenkaSera** [comment]
@kerschfilip To bude chyba použití špatného dialogového okna, V jádře má oprávnění na trvalé smazání opravdu jen superadmin, takže je to nekonzistentní.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
