### ISSUE TITLE
Povinnost vyplnění pole Edice v Klasifikace 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#142]
Pro povinné vyplnění se označí i pole M, která jsou vnořená do polí R

![obrazek](https://user-images.githubusercontent.com/13831946/155282069-86299bb0-8937-46b2-8bd1-00b48a78b79d.png)

Nyní se to neoznačuje.

Je to tak správně?

**Comment by ZdenkaSera** [comment]
Tady by se povinnost měla řídit tímto:
![image](https://user-images.githubusercontent.com/79305516/157866505-5c569105-1290-4c64-87ce-dad0f76d7600.png)

V PA je založen objekt uuid:8a030862-9e11-4d7d-b26a-7bb667c05bc0, na něm je chyba v nastavení povinnosti vidět;
- je to sysno 000945666 z katalogu KNAV
- pole z katalogu k tomuto uuid, kterých se problém týká:

![image](https://user-images.githubusercontent.com/79305516/157867034-a6af570d-8738-4154-b676-c529ada2ac68.png)

**Comment by luckajirku** [comment]
ono převádění těchhle polí je celé trochu nedořešené - jen pro info: https://github.com/NLCR/Standard_NDK/issues/168

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji.

**Comment by nezbedova** [comment]
V našem járdu tato chyba není. Je to nastavením nebo jádrem nebo čím? @SykoraLukas

**Comment by nezbedova** [comment]
@SykoraLukas Ano. Přesně tohle jsem chtěla vědět.

Takže prosím opravit v novém klientovi.

**Comment by albertoh** [comment]
Z meho pohledu novy klient je spravne implementovan.
Pokud to dobre chapu, Klasifikace je R, totiz nepovinna. Ale jak mile dame tam nejakou hodnotu do jednoho pole, potom musi se vyplnit vsechny, ktere maji M.
Tak pokud nemame zadnou hodnotu v polich, validace probehne.
Pokud mame spravne hodnoty na vsechny pole M, validace probehne
Jinak neprobehne

**Comment by ZdenkaSera** [comment]
V jádře se povinnost podpolí pod R-polem nekontrolovala, v klientu je tomu naopak, kontrolují se v kontextu.
RDA:  M/M pvinnost, pokud je vyplněna klasifikace
@kerschfilip Dořešit se standardy

**Comment by kerschfilip** [comment]
Myslím, že z pohledu standardu tohle není nutné řešit:

@albertoh má pravdu v tom, že pokud je v rámci nepovinného (R) elementu vyplněna nějaká hodnota, pak je nutné vyplnit všechna pole označená (M) a ProArc správně hlásí chybu. Naopak implementace ve starém klientovi = jádře v tomhle nebyla dostatečná.

Problém je v tom, že ta karta "klasifikace" představuje jeden formulář pro dvě různá MARC pole - `072` a `080`

Pro data stažená z pole `072` je takto formulář v pořádku, ale pro data stažená z pole `080` se podle Standardu ani [vyjádření NK](https://github.com/NLCR/Standard_NDK/issues/168#issuecomment-1055279710) nemá atribut “edition” používat. Toto pole se vztahuje jen na data z pole `072`.

Správný zápis převedeného pole 080 vypadá takto: 

```xml
<mods:classification authority="udc">364-787</mods:classification>
```
...a validace by ho tak měla nechat projít.

Myslím, že je tedy třeba rozlišovat, jestli se jedná o Klasifikaci ve smyslu Skupiny Konspektu (`072`), kdy je atribut `edition` povinný, anebo o Klasifikaci ve smyslu MDT (`080`), kdy tam naopak `edition` být nemá.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas V souvislosti s doplněnými formuláři (issue Popisná metadata - formulář neukazuje všechny údaje (vše je vidět jen v xml) https://github.com/proarc/proarc-client/issues/48) - rozlišení kontroly podle zdrojového pole stahovaných dat zatím nefunguje. Test na Inovatice s oběma poli - 15a7cee4-6ddf-4c08-a345-9701ad25f058, sysno 002695932 z kat. KNAV.

**Comment by SykoraLukas** [comment]
Ani fungovat nebude. Data jsou již převedena do modsu, takže informaci o zdrojovém pole nedokážeme zjistit. 

Proto jsou 2 možnosti. Buďto uvedeme pole edition do stavu MA nebo bude při každém uložení uživateli zobrazovat hlášku, aby si zkontroloval dané pole, protože není vyplněné.

K této "nesrovnalosti" z hlediska standardu se vyjadřovat raději nebudu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky za rychlou reakci. Vzhledem k tomu, že do pole Edice se pro údaje převzaté z pole 072 správně doplňuje "Konspekt", nemělo by nastavení pole na MA vadit - zde to bude správně a u dat z 080 to nebude zlobit. Nemůžu tohle ale rozhodnout - prosím o názor ostatní. Děkuji!

**Comment by ZdenkaSera** [comment]
@luckajirku @erikamirova @katerinasirova @nezbedova Prosím, můžete na tohle kouknout? Jde o to nalézt shodu akceptovatelnou pro všechny. Děkuji!

**Comment by ZdenkaSera** [comment]
@luckajirku Paní Jirků, můžu poprosit o názor, abychom se tu případně pohnuli z místa? Děkuji !

**Comment by ZdenkaSera** [comment]
@luckajirku @erikamirova @katerinasirova @nezbedova Prosíííím ....

**Comment by luckajirku** [comment]
tady jsem bez názoru:-)

**Comment by ZdenkaSera** [comment]
@luckajirku To mne mrzí :-) Jak to budete řešit - budete pole vyplňovat? Někdy ta povinnost může dost otravovat - viz např. uuid:d943edfd-e7fe-47ef-ab4e-b0dd2cc9b064 (to je uložené v surovém stavu).

**Comment by luckajirku** [comment]
Zeptám se teda úplně blbě - Lukáši, tam fakt nejdou rozlišit ve formuláři ta pole pro 080 a pro 072, aby se chovala odlišně, i když to v xml vypadá stejně? Vazba mezi jednotlivými řádky v xml a tím kterým polem ve formuláři tam přeci zůstává, ne?

**Comment by SykoraLukas** [comment]
No já se v tom už ztratil. Bral jsem to tak, že pole 080 je pro AACR a tedy pole Edice ve formuláři vůbec není. Pole 072 je pro pravidla RDA a tedy  pole Edice se chová podle pravidel (má povinnost M).

Nebo jsem to celé špatně pochopil? Může být pole 080 i u záznamů RDA?

**Comment by erikamirova** [comment]
Já se v tom popravdě taky ztrácím a netroufnu si to rozhodnout. @zabak Petře, ty jsi to řešil s Vaškem Jirouškem. Ozval se ti ohledně toho?

**Comment by vjirousek** [comment]
@erikamirova v diskusi se tady už taky trochu ztrácím, nicméně pokud by skutečně nešlo rozlišit povinnosti ve formulářích pro 080 a 072, pak se mi návrh od @ZdenkaSera jeví jako možné řešení: 

> @SykoraLukas Díky za rychlou reakci. Vzhledem k tomu, že do pole Edice se pro údaje převzaté z pole 072 správně doplňuje "Konspekt", nemělo by nastavení pole na MA vadit - zde to bude správně a u dat z 080 to nebude zlobit. Nemůžu tohle ale rozhodnout - prosím o názor ostatní. Děkuji!

**Comment by katerinasirova** [comment]
Dostala jsem se k tomu až dnes - pokud nelze primárně rozlišit, jestli data pochází z pole 080 nebo 072 (pro @SykoraLukas  - vyskytují se spolu v záznamu i podle pravidel RDA), tak mi řešení od @ZdenkaSera přijde jako přijatelné, asi nikomu se nechce při každém uložení odklikávat, že nevadí nevyplněné pole... 
@SykoraLukas opravdu to není možné vyřešit upravením transformační šablony (pokud už v MODS ztrácíme přehled o tom, ze kterého pole je která klasifikace), abychom odlišili, ze kterého pole je který údaj a poté, aby se formulář mohl chovat odlišně u 080 a 072? V těch vysvětlení už se taky ztrácím, tak případně promiň za nerelevantní dotaz :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, tohle by šlo ještě udělat? Dám milestone, tohle vážně dost vadí při zpracování. Díky.

**Comment by SykoraLukas** [comment]
V modsu už není poznat z jakého pole element classification vzniknul. I kdybychom tam někam tuto hodnotu dokázali doplnit, tak pak je to problém technický. Vytvoření formuláře pro element je závislé na názvu elementu, ne na jeho obsahu a podpolích. Tedy abychom to rozlišili, museli bychom vytvořit něco jako classification_072 a classification_080 což zase nedovoluje standard MODS.

**Comment by luckajirku** [comment]
Posuňte to kam potřebujete:-). Tady si (pro jednou) s dovolením dopřeju ten komfort a zdržím se hlasování:-)...

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím .... :-)  Díky.

"Vzhledem k tomu, že do pole Edice se pro údaje převzaté z pole 072 správně doplňuje "Konspekt", nemělo by nastavení pole na MA vadit - zde to bude správně a u dat z 080 to nebude zlobit."

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkujeme, povinnost je ok a doplňování hodnot taky. Shodli jsme se s @kerschfilip, že oboje platí pro AACR i RDA (a je pouze matoucí to, že ve standardu je údaj ohledně klasifikace/pole 072 uveden červeně v oddíle, který je nadepsán jako změny relevantní pro RDA). Snad se nemýlíme :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Jen mám ještě prosbu: bylo by možné vrátit ukládání v pořadí authority - edition? Viz 3. ř. na obrázku. Díky.

![image](https://user-images.githubusercontent.com/79305516/176643849-9ded173c-aff3-4802-8ca2-5c6a88a50c93.png)

**Comment by SykoraLukas** [comment]
Pozice ukládání atributu nelze ovlivnit.

**Comment by SykoraLukas** [comment]
> @SykoraLukas Děkujeme, povinnost je ok a doplňování hodnot taky. Shodli jsme se s @kerschfilip, že oboje platí pro AACR i RDA (a je pouze matoucí to, že ve standardu je údaj ohledně klasifikace/pole 072 uveden červeně v oddíle, který je nadepsán jako změny relevantní pro RDA). Snad se nemýlíme :-)

Takže se má pole Klasifikace doplnit i pro formuláře dle pravidel AACR?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ad ukládání - něco se tedy změnilo, stejný titul máme už v Krameriovi (z v3.7.3):
![image](https://user-images.githubusercontent.com/79305516/176649534-7fba1600-2d9c-49f9-b2df-0589a3862c8c.png)

Ad doplnění pro AACR - prosím, počkej s tím, dohledám data a porovnám s chováním jádra v nižší verzi. Díky.

**Comment by ZdenkaSera** [comment]
Pozice ukládání atributu nelze ovlivnit.

@SykoraLukas Tohle opravdu nebudeme řešit - překvapilo mne různé chování u téhož titulu, ale narazila jsem na to, že se v metadatech i historicky vyskytují obě verze pořadí.

**Comment by SykoraLukas** [comment]
Ono to vychazi z toho ze to je definovane xsd sablonou. Která u potomků a ani u atributu neurcuje poradi. Coz z hlediska XML je v poradku, ale pro orientaci je to trosku narocnejsi, protoze to kazdy muze zapsat v ruznem poradi.

**Comment by ZdenkaSera** [comment]
jj, to bude ok :-)

AACR - prosím, uprav formulář taky. Data se stahují do modsu správně (stejně, jako v RDA včetně edition). Vyzkoušela jsem jak v jádře ve starší verzi tak na Inovatice v klientovi. Tam je teď založen objekt uuid:a8bc0f50-1bc6-47ad-98d9-73734f438247, kde je to vidět (stažením sysna = 000000001 z knav). Děkuji.

**Comment by ZdenkaSera** [comment]
Otestovala jsem v KNAV na v3.8.2/1.1.2 a nenašla jsem zatím protipříklad. Navrhuji zavřít, ale budu ráda, když otestují i jiní.

**Comment by ZdenkaSera** [comment]
zavírám na základě štítku.
