### ISSUE TITLE
Rozdílné řazení polí popisu stran

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#143]
Pokud vyplňuji metadata stran hromadně, zobrazují se pole ve stejném pořadí jako to je nyní. Ale pokud chci vyplňovat jednotlivé strany, tak jsou pole pro číslo strany a typ strany prohozené. Velice špatně se s tím pracuje. Mělo by to být stejné.

![obrazek](https://user-images.githubusercontent.com/13831946/155284868-b33b05f9-ab5a-4437-b102-a11e54869d4e.png)
![obrazek](https://user-images.githubusercontent.com/13831946/155284942-4088a461-fdf8-48c4-bb33-2b80834038ba.png)

**Comment by ZdenkaSera** [comment]
LS upřesní AH.

**Comment by SykoraLukas** [comment]
Pro jednotliovu stránku
![image](https://user-images.githubusercontent.com/27210823/155492957-97ec3d04-c253-48fe-9b69-fa2546d68935.png)

Pro hromadnou opravu
![image](https://user-images.githubusercontent.com/27210823/155493013-c052a4fc-aa76-4efa-8c2c-70a98491ec13.png)

Požadovené řazení tedy je: typ strany, index strany, číslo strany

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím, koukneš na to? Díky.

**Comment by nezbedova** [comment]
Je to opravené. Děkuji. Navrhuji toto issue zavřít.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 18.5.2022.
