### ISSUE TITLE
Přidání dat na testování do importní složky 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#144]
Bylo by, prosím, možné přidat alespoň dvě složky po deseti skenech do importní složky.
Děkuji

**Comment by ZdenkaSera** [comment]
LS slíbil výmaz dat na Inovatice a přidání nových.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, přidáte nám nějaké skeny? Výmaz se asi povedl, ale skeny k novému importu nejsou dostupné. nneí na čem tetsovat. Díky!

**Comment by SykoraLukas** [comment]
Přidáno, pár z nich načteno kvůli testu konfigurace. Až bude potřeba umožnit znovu použití dat, dejte prosím vědět.

**Comment by nezbedova** [comment]
@SykoraLukas Prosím 8 skenů do dvou titulů STT. Děkuji

**Comment by SykoraLukas** [comment]
Hotovo

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
