### ISSUE TITLE
Chybí hromadné vytváření více čísel periodika najednou

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#145]
Chybí funkce Vytvořit více  při zakládání nového objektu - čísla periodika ( resp. čísel ) ve starém klientovi viz zde:
![obrazek](https://user-images.githubusercontent.com/24409660/155469307-7cd82874-1405-4b70-b132-e21dd9fa170c.png)

 plus ty možnosti založení: 
![obrazek](https://user-images.githubusercontent.com/24409660/155469380-c5069367-200c-4d00-83dc-34eeb466dc9f.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím o test - děkuji.

**Comment by SmejkalovaAnna** [comment]
Funguje to, ale mám výhradu. Když zadám vytvořit více a vyberu datum od/do, tak u jednociferných datumů se vygeneruje datum např. 05.05.1985. Podle pravidel by to mělo být ale bez nul, ve formátu 5.5.1985. Jde to generování upravit?

**Comment by SykoraLukas** [comment]
Upravíme na strane serveru

**Comment by luckajirku** [comment]
> Podle pravidel by to mělo být ale bez nul, ve formátu 5.5.1985. 

Můžu se zeptat, kde přesně v pravidlech to je? V pravidlech pro popis periodik (v. 8,4 s. 17-18) jsou data právě včetně těch nul (DD.MM. atd.). Je tam, pravda, na s. 18 jeden příklad (11.5.1951), kde nula není, ale to bude spíš chyba v pravidlech. Jinak všechny ostatní příklady tam jsou s nulami.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, nevím, jestli Ti chodí všechno nebo jen to, kde jsi adresovaná - prosím, koukni na to. Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko chodí mi to.

**Comment by SmejkalovaAnna** [comment]
@luckajirku Máte pravdu, díky za upozornění, je to tak. V tom případě se omlouvám a @SykoraLukas Lukáši nechte to prosím tak, jak to bylo. Bylo to tak v pořádku. Koukla jsem se předtím zřejmě na tu s. 18.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Díky - chápu to tedy jako funkční a dávám návrh na uzavření :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, štítek "probíhá"  pak asi bude nepravda ? Díky :-)

**Comment by luckajirku** [comment]
> @luckajirku Máte pravdu, díky za upozornění, je to tak. V tom případě se omlouvám a @SykoraLukas Lukáši nechte to prosím tak, jak to bylo. Bylo to tak v pořádku. Koukla jsem se předtím zřejmě na tu s. 18.

Tak aspoň se díky tomu přišlo na chybu v pravidlech:-) - nahlášeno - a slíbena oprava v příští verzi pravidel...

**Comment by SykoraLukas** [comment]
Změny vráceny do původního stavu. Navrhuji toto issue uzavřít.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Super, díky.

@SmejkalovaAnna Aničko, prosím, zkus to ještě jednou po odstranění úprav. Díky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím koukla bys na můj komentář výše, než to zavřeme. Díky.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas @ZdenkaSera Funguje to jak to bylo, ale prosím, proč naskakuje u výběru v kalendáři prohozený v datumu údaj o měsíci a dnu? Jako v Americe? Může to být jako v Čechách? Je to trochu matoucí....

**Comment by SykoraLukas** [comment]
@albertoh  prosím koukni na ten zápis data. Díky

**Comment by albertoh** [comment]
Je to tam v cestine

![image](https://user-images.githubusercontent.com/5946836/169528688-85e2bc2b-4e9e-464b-894b-cb70c20d375e.png)

**Comment by SmejkalovaAnna** [comment]
@albertoh Super, díky, je to bez chyby. Díky. Může se zavřít.

**Comment by ZdenkaSera** [comment]
Uzavřeme po přetestování na vlastním systému.

**Comment by luckajirku** [comment]
V kalendáři začíná týden nedělí (S-S) - chtělo by to přehodit na český (M-S).

**Comment by ZdenkaSera** [comment]
Koukla jsem ve správě dávek - 👍 kalendář ok, díky.

**Comment by ZdenkaSera** [comment]
@luckajirku Za ten kalendář díky, nikdo z nás si nevšiml ... Vracím návrh na uzavření.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.

**Comment by SmejkalovaAnna** [comment]
Teď jsem to zkoušela a: Dám Vytvořit nový objekt, Nastavím si parametry pro vytvoření více čísel najednou a vyběhne mi to nové okno - Editace nového objektu: NDK Číslo - ale tam se nikde neukáže nebo nepropíšou ty parametry, které jsem nastavila v kroku předtím. A když dám Uložit, tak mi to vytvoří jen to jedno první číslo a ty ostatní v tom datumovém rozmezí už ne......
Nebo postupuju nesprávně?

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, podíval byste se na tohle? Nerozbilo se to při změnách v zakládání nových objektů? Děkuji.

**Comment by albertoh** [comment]
Opraveno.
V tomto pripade jsem nechal stare chovani, tj pri vytvareni vice cisel najednou nove objekty se rovnou ulozi. Jinak by to bylo docela komplikovane, a nemoc pouzitelv praci...
 Zaroven jsem limitoval moznost vytvaret vice cisel pri editaci rocniku, tj, kdyz budou mit nadrazeny objekt

**Comment by luckajirku** [comment]
> Opraveno. V tomto pripade jsem nechal stare chovani, tj pri vytvareni vice cisel najednou nove objekty se rovnou ulozi.

Tohle už funguje správně.

> Zaroven jsem limitoval moznost vytvaret vice cisel pri editaci rocniku, tj, kdyz budou mit nadrazeny objekt

A tohle mi není jasné, co je tím myšleno.

**Comment by albertoh** [comment]
Drive bylo mozne vytvaret "vice" pri vytvoreni objektu tlacitkem "Nový objekt" a ne pluskem.
Ted to neni mozne.

**Comment by luckajirku** [comment]
Aha, jo takhle. Ale to se jen vrátilo k chování jako ve starém rozhraní, tam se to taky vytváří jen přes plusko. Za nás OK.

**Comment by SmejkalovaAnna** [comment]
Testovala jsem, je to OK.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
