### ISSUE TITLE
Příloha periodika - fyzický popis

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#146]
Když vytvořím přílohu a chci jí uložit, vyběhne mi, že nemám vyplněné pole Fyzický popis, který je M, ale ve vnořené Forma/Hodnota je přednataveno Print ( Hodnota je také M ).... nejsem si jistá, jestli je to chyba, nebo jestli tam něco chybí.... mohla by se prosím na to podívat @luckajirku ? Podle mě, by se to mělo uložit bez hlášky,....
![obrazek](https://user-images.githubusercontent.com/24409660/155479615-da0a4ad1-ca81-4bdb-9e99-f15ef80f2950.png)

**Comment by SmejkalovaAnna** [comment]
Objevuje se to i u dalších modelů jako např. NDK číslo atd..... myslím, že by se to mělo uložit bez hlášky, ve starém klientovi to tak funguje.

**Comment by SmejkalovaAnna** [comment]
Už se to ukládá bez hlášky, díky.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
