### ISSUE TITLE
přidat typ strany „část vazby“

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#148]
V MZK digitalizujeme staré tisky. Potřebovali bychom do ProArcu přidat _typ strany_ „**část vazby**“. V metodice pro popis starých tisků je tato strana zmíněna a používá se pro kování, záložky, fragmenty papíru, křidélka apod. V angličtině je to podle pravidel „**fragmentsOfBookbinding**“.

**Comment by ZdenkaSera** [comment]
Za KNAV - v novém klientovi na Inovatice je typ strany "část vazby" k dispozici, tedy ok.

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, je to za Vás ok a k uzavření? děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera Pan Sýkora nám musí nasadit zaktualizovanou verzi, takže to pak vyzkouším a dám vědět. :)

**Comment by erikamirova** [comment]
@albertoh @ZdenkaSera U nás to funguje, takže zavírám. :)
