### ISSUE TITLE
Úpravy ve formuláři pro eČlánky

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#149]
Při testování v KNAV jsme narazili na následující problémy ve formuláři pro eČlánky (pozor: ne NDK články nebo NDK eČlánky, ale jen **eČlánky**) . Celé by se to asi dalo shrnout tak, že by nebylo špatné formulář změnit tak, aby odpovídal tomu, jak vypadá ve starém rozhraní.

Jednotlivé problémy:

- při rozkliknutí eČlánku by bychom ocenili mít režim procházení nalevo a napravo popisná metadata + mít možnost otevřít si třetí okno na případnou kontrolu PDF
- formulář s popismými metadaty se někdy jen dlouho načítá a nic se nezobrazí:
![image](https://user-images.githubusercontent.com/57805328/157205773-d47b9390-5bfa-4405-bf19-512eca08e6a1.png)
- ve formuláři pro e-článek nemá být pole pro název periodika, nakladatelské údaje a žánr – to vše se vyplňuje na úrovní čísla
- zcela chybí možnost rozlišit recenzovaný / nerecenzovaný dokument (důležité pro export CEJSH) a také chybí možnost vybrat typ článku (screen ze starého prostředí, kde je to OK): 
![image](https://user-images.githubusercontent.com/57805328/157203611-bcca03a1-5654-4305-860a-3c558119453f.png)
- jazyky jsou v novém formuláři oddělené, nejsou provázané na jednotlivá pole, potřebujeme jazyk pro celý článek, pak pro názvy článku, dále pro abstrakty a klíčová slova – nedávalo by větší smysl uvést jazyky k jednotlivým polím, jako to je teď – přímo k abstraktu, jednotlivým klíčovým slovům atd., než mít pak za sebou třeba pět polí jen s jazyky. Navíc klíčová slova i abstrakty bývají dvojjazyčné a je potřeba přiřadit správný jazyk ke správným objektům (screen ze starého prostředí, kde je to OK): 
![image](https://user-images.githubusercontent.com/57805328/157203757-db06b6a5-f943-44da-8de0-f9de8f4a9e66.png)
- ve formuláři nejsou pole pro DOI, rádi bychom přidali i pole pro ORCID iD u autorů
- chybí pole pro fyzický popis – to, zda je to tištěná verze periodika, či vychází jen online (screen ze starého prostředí, kde je to OK): 
![image](https://user-images.githubusercontent.com/57805328/157202615-97101e84-6744-414e-abd5-132fda52de18.png)
- rozsah stran bude celý psán do jednoho pole, nebo bude rozděleno? (screen ze starého prostředí):
![image](https://user-images.githubusercontent.com/57805328/157202796-22c74da9-b2b1-42d4-bd74-5e3149664a7e.png)
- úplně chybí pole pro název článku, případně přeložený či variantní – a opět je tu propojení s jazykem
![image](https://user-images.githubusercontent.com/57805328/157202949-a65ae997-7e2d-4296-93eb-72f724f2fef5.png)
- u věcného třídění – tam pak lze doplnit i geografická předmětová hesla, korporace, autority – opět zde vyřešit problém s jazykem
- zcela chybí pole na zpracování recenzí (screen ze starého prostředí, kde je to OK): 
![image](https://user-images.githubusercontent.com/57805328/157203279-d7d3fa46-97f4-4626-8965-5baf5343f2cf.png)

Díky!
FK

**Comment by SykoraLukas** [comment]
Dlouhé načítání a nakonec nenačtení popisných metadat - formulář nejspíše nemá podporu rda pravidel. Pokud jsou pravidla aacr, tak se načte defaultní formulář.

Stejný problém se týká taky všech formulářů pro NDK Zvukových dokumentů.

**Comment by kerschfilip** [comment]
Aktualizace k 15.6.2022
Testována verze klienta 1.0.10 (26.5.2022), jádro 3.8.1-ALFA na proarc.inovatika.dev

- chybí možnost rozlišení článku na recenzovaný a nerecenzovaný
- U pole pro výběr typu média se stává, že pokud se vybere typ "bez média" a potom to chce uživatel změnit, už napodruhé nezafunguje ta rozbalovací roletka, ale musí se to smazat a pak teprve lze vybrat znovu ze seznamu (u ostatních polí to funguje v pořádku)
- u polí se jmény autorů bychom rádi přidali pole pro ORCID iD
  - to nemá úplně oporu ve standardu, ale to celý tenhle náš článkový formát :)
  - v mods bych byl asi pro to, aby se to propisovalo do `name/nameIdentifier` v dc do `<dc:creator>`
  - zpracovatelé by podle mě měli vyplňovat hodnotu v podobě URL, aby bylo zřejmé, že jde o ORCID iD, například by tak do formuláře vyplnily "https://orcid.org/0000-0003-4649-6702"
- Bylo by možné rozšířit pole "recenze na" (relatedItem) o možnosti pro upřesnění 
  - vydání (např. 1. vydání), 
  - počet stran recenzovaného díla (teď máme rozsah stran článku - to si myslím, že skoro nevyužíváme), 
  - edice recenzovaného díla, 
  - ISBN recenzovaného díla. 
...vše to vychází z polí v Alephu, konkrétně pole 787, podpole b (vydání), h (počet stran), k (edice) a z (ISBN)

**Pak se ještě při testování objevily připomínky na pořadí jednotlivých karet a polí:**
- pořadí polí tak jak je to ve starém prostředí Proarcu často odpovídá pořadí polí tak, jak jsou za sebou rovnány v katalogizačním formuláři v Alephu. V novém prostředí je trochu matoucí mít důležité identifikátory úplně dole, klíčová slova skoro nahoře atd. Bylo by možné pro model eČlánek zachovat pořadí polí takové, jaké je ve starém rozhraní?
- U pole název článku, bychom rádi přehodili pořadí názvu části a čísla části. V Alephu je to pole 245 podpole n a p, které uvádí první číslo části a pak až název části. Bylo by fajn, to mít stejně - tedy nejdříve číslo části a pak až název

**Comment by SykoraLukas** [comment]
> * chybí možnost rozlišení článku na recenzovaný a nerecenzovaný

Tohle tu je:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/27210823/174025785-28d2e0a2-75f7-4e52-a91e-28b3f2d5bf6f.png">

> * U pole pro výběr typu média se stává, že pokud se vybere typ "bez média" a potom to chce uživatel změnit, už napodruhé nezafunguje ta rozbalovací roletka, ale musí se to smazat a pak teprve lze vybrat znovu ze seznamu (u ostatních polí to funguje v pořádku)
Jedná se o pole, ze kterého je možné hodnotu vybrat nebo zapsat svou (provázané přes všechny modely). Toto pole nyní neumožňuje funkci, kterou popisujete.


> * u polí se jmény autorů bychom rádi přidali pole pro ORCID iD
Doplněno.

> * Bylo by možné rozšířit pole "recenze na" (relatedItem) o možnosti pro upřesnění.
Ano půjde to.  Potřebuji jen vědět mapování v modsu, jakou mají mít pole povinnost a jaký přesný název.


> * Pak se ještě při testování objevily připomínky na pořadí jednotlivých karet a polí:
Upraveno.

Během dneška dojde k nasazení k nám na test.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle se docela posouvá - prosíme o dokončení teď v červnu. Díky.

**Comment by kerschfilip** [comment]
@SykoraLukas díky za rychlé úpravy. Toho rozlišení recenzovaného/nerecenzovaného článku jsme si asi nějak nevšimli. Ve starém rozhraní bylo hned nahoře přepínání mezi těmi dvěma variantami. Teď je to trochu složitější. Šlo by tam přidat to jednoduché přepínání + samozřejmě nechat i současné pole žánr? 
![image](https://user-images.githubusercontent.com/57805328/174975367-53b1f60f-1002-4d4e-951c-b4287ef26326.png)


> Jedná se o pole, ze kterého je možné hodnotu vybrat nebo zapsat svou (provázané přes všechny modely). Toto pole nyní neumožňuje funkci, kterou popisujete

To byl poznatek kolegyň, které budou s formulářem běžně pracovat. Teď to asi není zásadní, ale pokud by se to dalo do budoucna nějak vyřešit, aby pro ně byla práce s formulářem příjemnější, bylo by to fajn.

> u polí se jmény autorů bychom rádi přidali pole pro ORCID iD

funguje, díky!

> Bylo by možné rozšířit pole “recenze na” (relatedItem) o možnosti pro upřesnění…

Přidávám mapování:
- vydání (např. 1. vydání): `originInfo/edition`
- počet stran recenzovaného díla: `physicalDescription/extent`
- edice recenzovaného díla: stačí do `note`
- ISBN recenzovaného díla `identifier type="isbn"`


Ještě jsem si všiml, že v záhlaví editace metadat se ukazuje nějaký text o kronice, který tam asi nepatří:
![image](https://user-images.githubusercontent.com/57805328/174975529-46de43d1-886d-4c54-a654-dca8bdcf44f0.png)

V textu rozsah článku je překlep:
![image](https://user-images.githubusercontent.com/57805328/174975560-eae3bd75-2149-44d3-97ac-6839ef535515.png)

**Comment by SykoraLukas** [comment]
> * Toho rozlišení recenzovaného/nerecenzovaného článku jsme si asi nějak nevšimli. Ve starém rozhraní bylo hned nahoře přepínání mezi těmi dvěma variantami. Teď je to trochu složitější. Šlo by tam přidat to jednoduché přepínání + samozřejmě nechat i současné pole žánr?

Můžeme toto nechat na podzim? Potřebujeme se nyní věnovat Akubře a tohle je sice v trochu složitější podobě použitelné.

Ostatní opraveno. Bude nasazeno

**Comment by kerschfilip** [comment]
@SykoraLukas můžeme, díky

**Comment by ZdenkaSera** [comment]
@kerschfilip Plánuješ projít ty opravené věci nebo to mám udělat? Díky.

**Comment by kerschfilip** [comment]
Prošli jsme současný stav eČlánků na testovací instanci Inovatiky (k 20.9.2022), ve formuláři jsme narazili ještě na nějaké problémy:

- Údaje o autorech - nelze vyplnit `<etal>` (má být O)
- Údaje o autorech - nelze `<affiliation>` (má být O)
- Chybí pole pro vyplnění údajů o metadatovém záznamu (recordInfo) - v XML ale jsou
- Chybí pole klasifikace
- Chybí pole pro vyplnění `<location>` (má být MA)

To mapování ORCID ID jsem ještě radši zkonzultoval s NK (https://github.com/NLCR/Standard_NDK/issues/175) a poprosil bych o drobnou úpravu
- je potřeba aby současný element `<nameIdentifier>` dál sloužil pro přidání čísla národní autority
- ORCID ID by se mělo mapovat do  `<nameIdentifier type="orcid">`
- mělo by být možné k jednomu autorovi vyplnit víc elementů nameIdentifier - může mít jak číslo národní autority, tak ORCID

Taky nám tu vznikl požadavek na to přiřadit autora k instituci pomocí ROR ID, to ale máme prý vyplňovat do `<affiliation>`, takže stačí když se tam objeví tohle pole...

A nakonec máme dvě nové věci, které vyplynuly z dalšího testování:
- u eČlánků automaticky nevyplňovat hlavního autora. U akademických článků s velkým počtem autorů není často možné rozhodnout, kdo je hlavní autor. Bylo by fajn aby v případě eČlánků nebyl automaticky jeden z autorů označen za hlavního
- Všechna pole formuláře by při založení objektu měla být rozbalená, protože se v podstatě všechny použijí. Vím, že něco souvisejícího se řešilo i tady: #204, půjde to realizovat? 

Mockrát děkuji!

**Comment by kerschfilip** [comment]
ještě doplnění k ORCID a ROR ID: bylo by potřeba, aby se tyhle identifikátory propisovaly i do exportu do Crossrefu. Tam by to mělo vypadat asi takhle (popsané je to případně tady)

**Comment by kerschfilip** [comment]
Díky moc za všechny úpravy, zůstalo tu pár bodů:

- [ ] u eČlánku není v identifikátorech na výběr DOI
- [ ] Ve starém rozhraní bylo hned nahoře přepínání mezi těmi dvěma variantami` recenzovaný článek`/`nerecenzovaný článek`. Teď je to trochu složitější. Dohodli jsme se, že bychom tenhle přepínač chtěli i v klientovi + samozřejmě nechat i současné pole žánr
- [ ] pole "Recenze na" je správně MA, není tedy nutné nic z něj vyplnit. Prázdná pole pro Identifikátory a Název recenzovaného díla ale způsobují, že při uložení se spouští hláška o nevalidních datech:
![image](https://user-images.githubusercontent.com/57805328/211346372-3745a8ea-7b80-455e-a973-b138ca19b53d.png)
- [ ] u eČlánků automaticky nevyplňovat hlavního autora. 
- [ ] Všechna pole formuláře by při založení objektu měla být rozbalená, protože se v podstatě všechny použijí. V Tuhle chvíli musí zpracovat ručně všechna pole rozbalit

**Comment by SykoraLukas** [comment]
> * u eČlánků automaticky nevyplňovat hlavního autora.

Jak vytváříte metadatový záznam? Stažením z katalogu? Mohu poprosit o nějaký záznam?

**Comment by kerschfilip** [comment]
Někdy se vytváří ten záznam ručně a někdy se stahuje z katalogu.

Z katalogu (Knihovna AV CR Analytika) třeba:  
Maximum number of limit cycles for generalized Liénard polynomial differential systems. SYS: 002637509

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tohle je si zatím u tebe?

**Comment by SykoraLukas** [comment]
> Někdy se vytváří ten záznam ručně a někdy se stahuje z katalogu.
> 
> Z katalogu (Knihovna AV CR Analytika) třeba: Maximum number of limit cycles for generalized Liénard polynomial differential systems. SYS: 002637509

Tady asi nechápu problém nebo je už vyřešen. 
Pokud zakládám z nového záznamu, tak se automaticky nezaklikne hvězdička, takže nikdo není označen jako hlavní autor.
Pokud stahuji z katalogu, tak to záleží na datech co přijdou - v případě té ukázky je hlavní autor označen již v záznamu z katalogu, takže proto je i ve formuláři označen.

**Comment by SykoraLukas** [comment]
Jinak body 1 a 3 vyřešené. Bod 2 a 5 se řeší mimo toto issue a na bod 4 je dotaz na @kerschfilip

**Comment by kerschfilip** [comment]
Souhlasím - body 1 a 3 jsou OK, body 2 a 5 jsou mimo toto issue (5 je taky už OK).

Bod 4 Automaticky nevyplňovat hlavního autora - taky vyřešeno, funguje jak je to popsané výše.

Bylo by ještě možné u eČlánku mít vždy na kartě "Údaje o autorech" rovnou dvě pole pro Jméno? Hodně článků se dělá ručně a téměř vždycky se vyplňuje jak jméno tak příjmení. Ušetřilo by to tedy kliknutí :-)
![image](https://user-images.githubusercontent.com/57805328/225061002-deb3171c-5f78-4c6e-90bd-354296fe7baa.png)
 
Děkuju!

**Comment by ZdenkaSera** [comment]
Na schůzce zavíráme.
