### ISSUE TITLE
Přesunout objekty

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc-client#15]
Mám dotaz na přesun objektů. Jak můžu přesunout objekt (například celý ročník, nebo číslo) pod úplně jiný časopis. Při výběru objektu, kam chci označené přesunout se doklikám jen na tu nejvyšší úroveň, tedy ten konkrétní časopis, ve kterém jsem. Ale nepodařilo se mi přijít na to, jak ty objekty přesunu úplně jinam.

**Comment by honza-rychtar** [comment]
<img width="628" alt="Snímek obrazovky 2020-12-03 v 17 31 44" src="https://user-images.githubusercontent.com/1178142/101058518-81d7da80-358d-11eb-8dae-5e095655c97b.png">

Pokud najedu na tlačítko přesunu, tak se mi zobrazí pod sebou 3 typy přesunu
1. **Změna pozice**
Posun vybraného objektu na n-tou pozici
2. **Přesunout v rámci dokumentu**
Přesun v rámci top level dokumentu
3. **Přesunou mimo dokument**
Zobrazí se dialog, kde můžu najít libovolný dokument, tam se proklikávat ve struktuře a do vybraného objektu pak udělat přesun

**Comment by luckajirku** [comment]
když označím strany a kliknu na přesun, v prostředním sloupci mi to nejdřív hodí formulář hromadného výběru - dost nelogicky -  když klikám na přesun, tak proto, že chci přesouvat, ne proto, že chci popisovat. nesouvisí to s problémem jednoduchý/hromadný výběr (https://github.com/proarc/proarc-client/issues/76)?

**Comment by luckajirku** [comment]
přesun do jiného objektu (tady "přesun mimo dokument") je zase složitější než dosud. musím proklikávat na další úrovně, abych se ujistila, že to přesouvám skutečně tam, kam chci. v současném rozhraní je to rozdělené na horní a spodní část stejně jako v úložišti, všechno vidím, ve spodní části mám strukturu dokumentu ve stromu. v novém klientovi musím zbytečně proklikávat níž a níž, abych si to zkontrolovala...

**Comment by honza-rychtar** [comment]
U toho přesouvání mimo dokument se použije stejná obrazovka jako je hledání v úložišti.

**Comment by luckajirku** [comment]
> U toho přesouvání mimo dokument se použije stejná obrazovka jako je hledání v úložišti.

Není to úplně stejné, resp. neumožňuje úplně to stejné jako obrazovka v "Hledat". Viz https://github.com/proarc/proarc-client/issues/129.

**Comment by albertoh** [comment]
Pridam moznost razeni kliknutim na header

**Comment by albertoh** [comment]
Prosim otestovat

**Comment by ZdenkaSera** [comment]
Snazší výběr nadř. objektu díky přidanému třídění - k testu. Prosíme o potvrzení, zda jde o požadavek rozdělené obrazovky na dvě části jako v úložišti.

**Comment by luckajirku** [comment]
Obrazovka je rozdělená na dvě části, je to ale pořád trochu jinak než v úložišti. V úložišti se dají tažením lišty mezi těmi dvěma částmi zvětšovat/zmenšovat jedna/druhá, tady je to napevno, což by možná až tak nevadilo, kdyby tam nebyl ten zbytečný bílý pruh. Horní obrazovka pak dělá dojem, že ukazuje vše, posuvníku si člověk nemusí všimnout, to prázdno mezi je matoucí. 
![bilypruh](https://user-images.githubusercontent.com/6359479/172306089-15ebe7c4-e53f-4680-98be-357f748a7426.png)

**Comment by luckajirku** [comment]
řeší se ještě v i https://github.com/proarc/proarc-client/issues/167

**Comment by albertoh** [comment]
Poopravil jsem disajn dialogu. Kouknete, prosim.
@pkudela podivejse potom na to vsechno, dej to do krasy :)

**Comment by albertoh** [comment]
Muzeme toto zavrit a pokracovat jen v #167 ?

**Comment by luckajirku** [comment]
Jo, to už vypadá líp. A asi se může tady zavřít.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
