### ISSUE TITLE
Úprava zobrazení u NDK ročníku a čísla

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#150]
Zdravím,

u NDK ročníku a čísla by nám v KNAV přišlo lepší mít po otevření nalevo automaticky nastavený režim procházení (vidět strukturu periodika) a napravo popisná metadata – je pro nás zbytečné, aby se zobrazoval režim detailu, MODS při zpracování téměř nepoužíváme a to samé platí i pro administrativní metadata, které není nutné vidět. Teď je proklikávání se do požadovaného vzhledu celkem složité. 

Děkuji,
FK

**Comment by SmejkalovaAnna** [comment]
Funguje, super. Díky.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022

**Comment by kerschfilip** [comment]
issue ještě otevírám kvůli drobnému požadavku, bylo by možné u NDK ročníku vlevo zobrazovat i číslo ročníku spolu s rokem a u NDK čísla i rok spolu s číslem výtisku? Tzn. v podstatě stejně, jako je to ve starém rozhraní? 

Pokud s tím samozřejmě ostatní budou souhlasit.
![image](https://user-images.githubusercontent.com/57805328/195334807-368075a9-e93e-46ca-ad76-41bcda772c3b.png)

**Comment by SmejkalovaAnna** [comment]
Určitě souhlasím (brala jsem to jako specifikum nového klienta, ale když to půjde upravit, budu ráda)

**Comment by luckajirku** [comment]
Za nás určitě souhlas, do starého se to dávalo právě aby člověk měl přehled, kde přesně je.

**Comment by albertoh** [comment]
To je mozne i ted. Lze prepnout pomoci tlacitka:

![image](https://user-images.githubusercontent.com/5946836/195778556-8a35f144-9707-431c-a42c-ca7cd5891c79.png)

**Comment by luckajirku** [comment]
jasně, ale tady to není
![popisek](https://user-images.githubusercontent.com/6359479/195779211-1030d3b6-a526-4b03-905a-2943d20e5d4c.png)

**Comment by luckajirku** [comment]
Aha, tak zpět. To co myslím, tam je - ale za názvem periodika. Což ale u většiny pak vidět není, protože jsou dlouhé názvy a jak se přenastaví šířka sloupce, tohle se schová.

**Comment by albertoh** [comment]
Cili presunout dolu, za modelem, info o objektu, a nechat na hore nadrazene?

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/195783262-4a448211-04dc-47bc-b391-c7ffec6abc5a.png)

**Comment by SmejkalovaAnna** [comment]
Mě se to líbí, jak to teď navrhuje Alberto, to je dobrý nápad.

**Comment by luckajirku** [comment]
A teď nám zmizel název periodika ze všech nižších úrovní, je vidět jen na úrovni titulu. Když se prokliknu níž do ročníku, čísla, tam už vidět není.

**Comment by albertoh** [comment]
jj, uz na tom pracuju

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Funguje, a je to dokonce i klikatelné, super. Stačil by nám i pouhý text, ale tohle je lepší, že jde prokliknout třeba z čísla hned na titul.

**Comment by ZdenkaSera** [comment]
Odebírám štítek "návrh na rozšíření" vzhledem ke stavu úkolu.  
@albertoh Díky!

@SmejkalovaAnna @kerschfilip Prosím, jak to vidíte? Nebude to k uzavření? Děkuju :-)

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Za mě zavřít. Mě to takto vyhovuje.

**Comment by kerschfilip** [comment]
Moc díky, zavírám
