### ISSUE TITLE
Neukládá se nový objekt (NDK Periodikum/svazek monografie/STTmonografie) - na Inovatice

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#151]
Když založím NDK Periodikum, upravím načtená data z katalogu, dám uložit, tak se mi akorát točí kolečko a nic se neděje.... když jsem klepla na F5, tak jsem sice objekt měla založen, ale změny neuloženy....

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Zkouším uložit nový objekt NDK monografie (sysno 000945666 stažené z katalogu KNAV) a "kolečko" běží již několik minut. Nejde tedy zřejmě jen o problém s jedním typem modelu. Prosím, můžete se na to podívat? Tohle nám bohužel zabrání v dalším testování. Děkujeme.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Ještě doplnění: po asi 7 minutách "ukládání" jsem se vrátila šipkou prohlížeče o krok zpět a objekt vyhledala - byl uložen. Po změně názvu a uložení se systém opět tvářil stále v procesu ukládání. Po opětovném opuštění obrazovky šipkou prohlížeče a vyhledání objektu byla změna uložena. Jde o 8a030862-9e11-4d7d-b26a-7bb667c05bc0.

**Comment by SykoraLukas** [comment]
@alberto koukni na to prosím. Myslel jsem, že je to tím, že z API přijde chybova hlaska a klient neumi s tim pracovat, ale podle developeru je response 200 včetně jsonu aktualizovanych dat. Klient tedy data z nějakého důvodu nenačte.

**Comment by nezbedova** [comment]
Přidávám výsledek mého testu.
Založila jsem STTmonografii přes Záměry. To je v járdu, proběhlo dobře. Z RDflow jsem založila nový objekt. Správně. Po rozkliknutí byl hned k dispozici. Provedla jsem úpravu (přidání jazyka) a teď mám točící se kolečko.

**Comment by SykoraLukas** [comment]
Úprava provedena na novém klientu, že?

**Comment by nezbedova** [comment]
Ano. Na novém klientovi.

**Comment by SmejkalovaAnna** [comment]
@nezbedova @SykoraLukas Mě se to právě po refreshi neukládalo.... Jinak to ale vyhazuje hlášky, když jsou data nevadilní, ale mám dojem, že to přestane reagovat, kdyz jsou naopak data validní.....

**Comment by nezbedova** [comment]
Kolečko je i pokud dám "Smazat" . A ani se mi to nesmaže. Ale to asi patří jinam.

**Comment by albertoh** [comment]
Opraveno

**Comment by nezbedova** [comment]
Při změnách v metadatech funguje.
Při zakládání nového objektu funguje

**Comment by SmejkalovaAnna** [comment]
Mě teda při zakládání NDK Periodika nefunguje... točí se dál.... co proto mám udělat? 2x tlesknout, 3x vyskočit a 1x říct HuberoKororo? :)

**Comment by SykoraLukas** [comment]
Jak zakládáte objekt? Stahujete do něj nějaká metadata z katalogu? Pokud ano z jakého a jak záznam hledáte?

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Tak už to funguje, omlouvám se, otevřela jsem si anonymní okno a tam už to jde. Díky.

**Comment by SmejkalovaAnna** [comment]
Můžete asi zavřít toto issue..... vypadá to, že to běhá.....

**Comment by nezbedova** [comment]
Vypadalo to, že to běhá. Dokud jsem nepotřebovala založit NDK přílohu monografie. Mám kolečko a nepomáhá nic.

**Comment by albertoh** [comment]
Chybi sablona pro "NDK přílohu monografie". Muzu pouzit sablonu "NDK Příloha periodika" ? Jsou stejne?

**Comment by SykoraLukas** [comment]
Nejsou, šablony vychází z definic standardů.

Stránka se všemi standardy, které říkají jaká pole jsou pro které modely jsou zde:
https://old.ndk.cz/standardy-digitalizace/metadata

**Comment by albertoh** [comment]
Zalozil jsem s rozdily, ktere jsem nasel. Prosim o kontrolu

**Comment by SmejkalovaAnna** [comment]
@nezbedova Martino ve formuláři je role MA, takže se to může bez ní uložit, a teď jsem koukala do standardu a u Periodik je dokonce Role - R, u Monografií MA.... tak nevím, jak to chceme....

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto proč to neuděláte podle té NDK přílohy monografie ve starém klientovi? Vždyť ty modely už byly hotové z dřívějška.... možná to jen špatně chápu....

**Comment by SykoraLukas** [comment]
@nezbedova  Vyzkoušeno a jde uložit autor jak bez role tak s rolí (zkoušeno na STT příloze monografie). 
@SmejkalovaAnna nenašli jsme ve standardech rozdíl v povinnostech. Všude je povinnost MA.

**Comment by nezbedova** [comment]
@SykoraLukas Děkuji.

**Comment by katerinasirova** [comment]
Problém stále trvá - zkusila jsem založit NDK přílohu monografie a po načtení metadat z katalogu se dívám už 5 min. na točící kolečko. Po obnovení se kolečko v režimu detailu točí dál, v MODSU se tváří, že údaje jsou - minimálně je vidím načtené. Objekt se uloží, ale v seznamu má místo názvu? (staženo z KNAV, SYSNO 000294737).

**Comment by albertoh** [comment]
Opravil jsem tocici se kolecko. Otaznik je jiny problem

**Comment by SykoraLukas** [comment]
Problém s tím otazníkem je ten, že se definovalo, že příloha bere popisek z pole titleInfo:partName a titleInfo:partNumber. Záznam, který uvádíte nemá vyplněné ani jedno pole.  Proto se doplní ?, když není z čeho definovat.

**Comment by katerinasirova** [comment]
Díky, kolečko se netočí a metadata se zobrazují, otazník byl opravdu důsledek nevyplněného příslušného pole a ne toho, že se metadata neuložila.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
