### ISSUE TITLE
Číslování sloupců ( stran )

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#152]
Existují případy, kdy jsou na jedné straně dvě čísla stránek - většinou jde o číslované sloupce, třeba u slovníků. Tyto knihy mají hodně stran a jde to číslovat jen ručně. Šlo by přidat sem 
![obrazek](https://user-images.githubusercontent.com/24409660/157826878-50f62b6b-ee78-423b-badd-a9f07efa87b5.png)
funkcionalita číslování stran podle sloupců? Přidat to i do starého klienta? Ty strany vypadají asi takto:
![PA_sloupce](https://user-images.githubusercontent.com/24409660/157829096-feb0cf33-3640-4be2-8f57-5ac2bc6fe88c.JPG)

**Comment by SmejkalovaAnna** [comment]
![Uploading PA_sloupce..JPG…]()

**Comment by SmejkalovaAnna** [comment]
![Uploading PA_sloupce..JPG…]()

**Comment by albertoh** [comment]
Pro tuto funkcionalitu, bude nutne zmenit API take. Do rozhrani pridat moznost "dvojcisla", nebo neco takoveho, a v API zpracovat toto nastaveni

**Comment by SykoraLukas** [comment]
Jak by vypadaly potom čísla stran?
1,2; 3,4; 5,6; ...

Nebo je i nějakí jiní možnost?
Např.:[1],[2]; [3],[4]; ...

Prosím specifikujte všechny možnosti, ať víme co je možné tam zapsat a na schůzce se o tom pobavíme.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas  Ano tak by to přesně vypadalo (podle pravidel pro popis strany v případě výskytu číslování sloupců),  a  aby šly použít všechny možnosti, které jsou tam doposud, např. 1,2; 3,4; 5,6; ..., nebo :[1],[2]; [3],[4]; včetně římských čísel......  u těch a,b,c,d to si nejsem úplně jistá, to musíme probrat... tak si myslím, že to nebude nutné.... ale třeba se k tomu ještě někdo vyjádří,,,,,

**Comment by katerinasirova** [comment]
Z praxe jsem nezažila, že by při číslování sloupců bylo potřeba použít a, b, c, d.

**Comment by SmejkalovaAnna** [comment]
Já právě taky ne, ale jsem ráda, že nejsem sama. Tak ty a, c, d můžeme vypustit.

**Comment by SykoraLukas** [comment]
API připraveno. @albertoh pokud je potřeba na jedné straně očíslovat 2 sloupce, stačí přidat mezi parametry volání doubleColumns=true.

**Comment by albertoh** [comment]
Pridano

![image](https://user-images.githubusercontent.com/5946836/172123965-3fd10b5d-4b27-437a-9c92-7100fbf7da50.png)

**Comment by nezbedova** [comment]
Testováno v Chromu. Nezobrazuje se správně popisek a jdou udělat dvoje závorky.

![obrazek](https://user-images.githubusercontent.com/13831946/172130432-99456a5e-47d7-47ae-939c-b6a53408a15c.png)

Závorky jdu ještě testovat.

**Comment by albertoh** [comment]
ad popisek: ctrl+f5

ad dvojite zavorky: koukni na to Lukasi

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto pozor, ty čísla sloupců by měly být bez mezery ( v nabídce to je bez mezery, ale zapíše se to s mezerou )
![obrazek](https://user-images.githubusercontent.com/24409660/172137187-c4d5e013-1311-465e-a7a3-ace964b20a2b.png)

**Comment by SykoraLukas** [comment]
Problem je, pokud uživatel zapise do prefixu i suffixu zavorku, ale pak zaklikne i uzavorkovani. Můžeme to tedy udělat tak, že když to je takto tak nahradíme zadané 2 pravé i 2 levé závorky jen jednou? [[1]],[[2]] --> [1],[2]

**Comment by nezbedova** [comment]
@SykoraLukas prosím nahradit dvě závorky jednou.

**Comment by SykoraLukas** [comment]
Kontrola nasazena.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, chápu správně, že jednoduché tlačítko [] přímo ve formuláři editace číslování stran mění funkci ozávorkovat/odzávorkovat a je duplicitní ke dvěma tlačítkům [+], [-] na liště? Aspoň mi to tak z testu vychází ... Díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Beru zpátky, není - horní tlačítka bez "přenastavení" do jednoduchého formulářového nefungují. takže
- stisknu tlačítko [] a musím dát enter v poleii formuláře ->> čísla se ozávorkují
- stisknu tlačítko [] a nedám enetr, místo něj stisknu [+] ->> strany se ozávorkují

Nezdá se mi to úplně šikovné, ale nechám test na kolegyních, které to používají denně.

**Comment by ZdenkaSera** [comment]
Tak jsem ta tlačítka převezla nebo dělám něco špatně:
přidala jsem závorku jen do prefixu, na sufix jsem "zapomněla" 
![image](https://user-images.githubusercontent.com/79305516/173041778-8feb27af-8248-4017-bea8-37e4f90f71ca.png)

dvojitá závorka zůstala:
![image](https://user-images.githubusercontent.com/79305516/173041905-03a85711-755a-434a-9cc8-82e87f391252.png)

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh A tohle celé patřilo do issue #62. S omluvou.

**Comment by SykoraLukas** [comment]
Kde jste tohle prosím testovala? Nemohu tuto chybu zreplikovat na testovacím serveru.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Tady probíhaly úpravy - prosím o přetestování. Díky.

**Comment by SmejkalovaAnna** [comment]
@albertoh https://github.com/proarc/proarc-client/issues/152#issuecomment-1147262102 Alberto, na toto se zapomnělo, jsou tam pořád mezery....i v MODSu i ve formuláři

**Comment by albertoh** [comment]
@SykoraLukas je to v jadru.
https://github.com/proarc/proarc-client/issues/152#issuecomment-1147262102

**Comment by SykoraLukas** [comment]
Jádro opraveno a nasazeno

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím, přetestovala bys to? Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Je to v pořádku na Inovatice...

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Děkuji 👍, dávám tedy návrh na uzavření.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
