### ISSUE TITLE
STT - Nefunguje hromadná editace stran 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#153]
U STT lze přidávat metadata jen po jednotlivých stranách. Popis pro hromadný výběr nefunguje.

**Comment by SykoraLukas** [comment]
Prosím jak jste postupovala? Zkoušeli jsem s @albertoh a funguje. Můžeme poprosit o snímek obrazovky, kde bude vidět, jaké parametry nastavujete?

**Comment by nezbedova** [comment]
@SykoraLukas Už to jde. Ale zkoušela jsem to několikrát v anonymním okně než jsem to sem napsala. Po uložit se nestalo vůbec nic. Ani po refreši.
Asi stačilo, že jste to zkusili.
Děkuji
Zavírám.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
