### ISSUE TITLE
Úprava řazení v roletce Export

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#154]
Prosím upravit řazení v roletce export podle jádra. 
Teď naskočí jako první Skeny. To se exportuje jen výjimečně.

![obrazek](https://user-images.githubusercontent.com/13831946/157832088-2a93d2d6-12f5-468a-a797-86f35b7689b7.png)

**Comment by albertoh** [comment]
Takhle? Nebo i texty maji byt stejne?

![image](https://user-images.githubusercontent.com/5946836/157835923-0e5cdcc4-221d-4894-b2d1-814ffdb8e0c5.png)

**Comment by nezbedova** [comment]
@albertoh Takto. Děkuji.

**Comment by ZdenkaSera** [comment]
@nezbedova Přidávám dodatečně štítky - pokud se mýlím, prosím, uprav. Díky.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
