### ISSUE TITLE
Načtení autora z Authority NKP - nefunguje

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#155]
Zkoušela jsem v NDK Příloze priodika načít autora z Authority NKP - nabídka autorů mi vyjede při zadání nějakého jména - ale po vybrání se mi do formuláře medata nepropíší...

**Comment by ZdenkaSera** [comment]
Duplicitní k issue [#133](https://github.com/proarc/proarc-client/issues/133), to zavírám. @SmejkalovaAnna

**Comment by ZdenkaSera** [comment]
@albertoh Vyzkoušela jsem znovu i v NDK svaku monografie - můžu data vyhledat, ale neuloží se žádná část záznamu z db autorit. V jádře funkční.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
V NDK svazku monografie vypadá funkční :-) Díky.

@[SmejkalovaAnna](https://github.com/SmejkalovaAnna) Prosím, zkusíš periodikum?

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko funguje mi i u Periodik.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
