### ISSUE TITLE
NDK číslo - věcné třídění katalog?

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#156]
V NDK čísle je možnost načtení dat z katalogu ve formuláři u Věcného třídění. Když tu možnost vyberu, tak mi vyjede okno s nabídkou jednoho katalogu Authority NKP plus nabídka Pole.... ale nejsem si jistá, jestli to to správná nabídka k Věcnému třídění.... můžeš se prosím Zdenko @ZdenkaSera  na to podívat do té mé vytvořené struktury?

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím, dáš mi název nebo uuid? Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera 
![obrazek](https://user-images.githubusercontent.com/24409660/157850833-e61ac0b3-f052-4127-89b7-436cc81d09fe.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Díky, nedošlo mi, že tam není moc dat :-)

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem - data opravdu nelze uložit, bez ohledu na zvolenou databázi autorit.

**Comment by ZdenkaSera** [comment]
Doplňujeme: na tomto místě funkci načítání z katalogu autorit nepoužíváme. Je ale matoucí to, že je zde k dispozici. Navrhujeme ji buď zamknout nebo rozchodit.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna @ZdenkaSera Podívat se na načítání autorit v NDK čísle. AKTUALIZOVAT S DOTAZEM PROP DALŠÍ KNIHOVNY.

**Comment by ZdenkaSera** [comment]
Tohle je ok, jen záleží na tom, ve kterém poli stojíme a chceme do něj vyhledat data (tj. nelze všude).

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
