### ISSUE TITLE
Funkce "Připravit ke znovunačtení"

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#157]
V importní obrazovce přidat novou funkci "Připravit ke znovunačtení".
Funkce provede odstranění složky proarc_import a proarc_impost_status.log což znamená, že povolí načíst znovu složku, která je již načtená. Funkci by měl mít možnost spustit zatím jen uživatel s rolí superAdmin. (možnost do budoucna rozšířit o role nebo oprávnění).

Po kliknutí na konkétní složku (již načtenou) povolit uživateli na této složce spustit funkci.

Volání funkce pro složku Monografie/KratkaBezAlto/
url http://localhost:8081/proarc/rest/v1/import/batch/unlockFolder
parametr folderPath=Monografie%2FKratkaBezAlto%2F

dotaz bude vypadat takto:

POST http://localhost:8081/proarc/rest/v1/import/batch/unlockFolder
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&folderPath=Monografie%2FKratkaBezAlto%2F&_textMatchStyle=exact&isc_dataFormat=json}

**Comment by ZdenkaSera** [comment]
Funguje, hezké :-)

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
