### ISSUE TITLE
Validace nové dávky - zamrzne obrazovka

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#158]
Načetla jsem nová data a dala pokračovat. Aniž bych načtené skeny upravila (tj. měly pouze automaticky vytvořený index, ale neměly stránkování) jsem spustila validaci a obrazovka zamrzla (viz níže). V téhle fázi zpracování je sice validace nesmysl, ale dá se spustit omylem (spustila jsem ji ale cíleně a čekala jsem ohlášení chyby). Refresh nebo návratová šipka dovolí obrazovku opustit.

![image](https://user-images.githubusercontent.com/79305516/157891717-6c8c6771-6611-4893-b241-9fdc9ba681a7.png)

**Comment by katerinasirova** [comment]
prosím přidat data na testování do importní složky, díky

**Comment by ZdenkaSera** [comment]
Funguje, díky.
