### ISSUE TITLE
Zřízení podpory pro označování pravých a levých stránek

### ISSUE THREAD

**Issue by zabak** [proarc/proarc-client#159]
Zavést podporu pro explicitní označování jak mají být stránky zobrazovány při dvoustránkovém zobrazení v Krameriu: left, right, singlePage ukládané do MODSu stránky - podobně jako v lince NDK.

**Comment by SykoraLukas** [comment]
Jak s tím pracuje Kramerius nevím, ale ProArc (starý i nový klient) již podporují zapsaní pozice strany do modsu.

![image](https://user-images.githubusercontent.com/27210823/158544135-90bc4324-6492-4695-a378-90649f1e386d.png)

**Comment by zabak** [comment]
Díky, zavírám
