### ISSUE TITLE
Přidání pole   Extent - RA 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#16]
U metadat na titul přidat zobrazení pole "Extent - RA" do levého formuláře/části obrazovky. Je tam počet stran.

**Comment by nezbedova** [comment]
Mezi pole Identifikátor a Poznámka

**Comment by luckajirku** [comment]
Vypadá, že tam je. Jen po přepnutí do anglické verze nejsou OK popisky, ale to blbne u víc polí.
