### ISSUE TITLE
nefunkční tlačítko reindexace

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#160]
Tlačítko reindexovat nám nefunguje (jak při editaci naimportovaných skenů, tak při editaci napojených skenů v editoru připojených objektů). Resp. vyberu si všechny objekty a kliknu na reindexovat. Vyskočí na mě hláška, že objekty byly reindexovány, ale není tomu tak. 

<img width="55" alt="reindexovat" src="https://user-images.githubusercontent.com/37616300/163982850-7d119015-f0b4-4a64-86ef-95c387a26383.PNG">

Proto reindexaci musíme provádět tímto způsobem, jenže to nám pak zmizí zeditované typy stran. (viz [issue 161](https://github.com/proarc/proarc-client/issues/161))
<img width="855" alt="mizející typy stran u reindexace  001" src="https://user-images.githubusercontent.com/37616300/163982920-8f37d5a2-899c-4830-a53e-b1c0052e86b9.PNG">

**Comment by ZdenkaSera** [comment]
@erikamirova Myslím, že pokud chceme použít tlačítko "reindexovat", není zapotřebí vybírat objekty, automaticky to reinedxuje od začátku dokonce. Zkusila jsem to teď na Inovatice a dopadlo to dobře, typy stran nezmizely.

**Comment by ZdenkaSera** [comment]
@erikamirova Ještě doplňuji, že jsem to zkoušela na NDK monografii, ne na STT.,

**Comment by ZdenkaSera** [comment]
@erikamirova A ještě jednou - nasimulované chyby jsem si neuložila, takže se nemělo co reindexovat, moje chyba. Zkusila jsem to znovu a reindexace proběhla správně - ale opravdu bylo nutné objekty označit. Nevím, jestli se tohle nezměnilo oproti nějaké dřívější verzi.

**Comment by erikamirova** [comment]
@ZdenkaSera Zkusila jsem to tlačítko u NDK monografie a reindexace proběhla úspěšně. Ale u STT to nefunguje, což je teda zvláštní.

**Comment by albertoh** [comment]
@SykoraLukas : v core neni moznost reindexovat u STT

**Comment by erikamirova** [comment]
@SykoraLukas Děkujeme za opravu, už to funguje. :)

**Comment by luckajirku** [comment]
Vypadá to, že se vrátila chyba s nefunkčním tlačítkem reindexace. 
- v úložišti nefunguje vůbec
- v importu to funguje tak nějak výběrově. Ale nejsem schopna přesně říct, kdy to jistě funguje a kdy ne, zatím klíč nenašli. V některých případech to zafunguje, jindy ne - navíc se nám stalo třeba několikrát to, že po přesunu strany na jinou pozici a uložení změny se po reindexaci ta strana vrátila na původní místo.

**Comment by SykoraLukas** [comment]
Opraveno, zkuste.

**Comment by luckajirku** [comment]
Tak teď to dělá ještě něco jiného - dám reindexovat v čísle periodika, a hodí mě to do prvního dostupného čísla prvního ročníku.

**Comment by luckajirku** [comment]
Ta poslední věc už se dneska neděje. A reindexuje se OK v importu i ve vazbách.
Jinak ale mám pocit, že ProArc už se intenzivnějšímu testování začíná bránit:-).

**Comment by SykoraLukas** [comment]
Můžeme poprosit o vysvětlení věty:
`Jinak ale mám pocit, že ProArc už se intenzivnějšímu testování začíná bránit:-).`

Nemůžeme se domluvit, co tím bylo myšleno...

**Comment by luckajirku** [comment]
Tím bylo myšleno to, že se nám to někdy chová odlišně i tady na oddělení - a jak jsme tak vypozorovali, tak nejlíp se to chová tomu, kdo testuje nejmíň často. Nevím, jak a kde si co PA pamatuje, ale u některých oprav je docela rozdíl v tom, za jak dlouho se to na kterém počítači začne chovat/zobrazovat správně (refresh ani odhlašování moc nepomáhá)...

**Comment by ZdenkaSera** [comment]
Tlačítko reinedexace je zakleteé - zkusila jsem dnes na inovatoce s tímto výsledkem:
![image](https://user-images.githubusercontent.com/79305516/221860656-262b6116-e5de-474d-98c2-dd68ce56e85e.png)

**Comment by albertoh** [comment]
Muzu se zeptat jaky objekt?

**Comment by ZdenkaSera** [comment]
Zkusila jsem teď znovu na NDK monografii bcb54d57-d9f3-4b30-a7cd-bd1166be0de3

**Comment by albertoh** [comment]
Je to na Lukasi... :)

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Děkujeme, funkční v importu i úložišti.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.

**Comment by bezverec** [comment]
Mohl bych poprosit o nové ověření?
Tlačítko reindexovat mi v klientovi v úložišti nefunguje - zkoušeno v NDK Číslech (splněnou úlohu hlásí, ale indexy se nezmění). Při označení více stran hromadná úprava jde. Typy stran zůstanou. V jádru mi tlačítko reindexovat jde. V importu v klientovi tlačítko reindexovat jde.

Klient 2.2.2
Jádro 4.1.3

**Comment by bezverec** [comment]
Hlásím, že dnes mi to naopak funguje, jak má. Omlouvám se, pokud to byl planý poplach, ale opravdu mi to minule ve specifikovaném případě při všech pokusech nešlo :)
Každopádně to budu ještě dnes a zítra testovat, abych se ujistil, že se opravdu jednalo jen o izolovaný incident.

**Comment by ZdenkaSera** [comment]
@bezverec Můžeme issue znovu zavřít?

**Comment by bezverec** [comment]
@ZdenkaSera Ano, díky.
