### ISSUE TITLE
mizející typy stran u reindexace

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#161]
Tlačítko reindexovat nám nefunguje. (viz [issue 160](https://github.com/proarc/proarc-client/issues/160))
<img width="55" alt="reindexovat" src="https://user-images.githubusercontent.com/37616300/163982850-7d119015-f0b4-4a64-86ef-95c387a26383.PNG">

Takže reindexaci provádíme tímto způsobem. 
<img width="855" alt="mizející typy stran u reindexace  001" src="https://user-images.githubusercontent.com/37616300/163982920-8f37d5a2-899c-4830-a53e-b1c0052e86b9.PNG">

Indexy se úspěšně reindexují, avšak zmizí nám zeditované typy stran. A to jak u STT, tak u NDK modelů. Děje se to v editoru připojených objektů. 
<img width="880" alt="mizející typy stran u reindexace  002" src="https://user-images.githubusercontent.com/37616300/163983004-678106aa-155d-4521-b452-0a43272f1e57.PNG">

**Comment by luckajirku** [comment]
U NDK modelů ten problém nemáme, není to stejně jako u odkazovaného issue taky problém jen u některého STT modelu? (Byť je zde zmiňováno, že je problém i u NDK.)

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by erikamirova** [comment]
@SykoraLukas Děkujeme za opravu, už to funguje. :)
