### ISSUE TITLE
Formulář NDK svazku monografie - systémové číslo

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#162]
**Test k issue Popisná metadata - formulář neukazuje všechny údaje (vše je vidět jen v xml) #48**

Systémové číslo se při stažení z katalogu přebírá do elementu "recordinfo" , v jádře je zároveň dostupné pro editaci ve formuláři. V novém klientovi se do xml přebírá stejně, ale není ve formuláři ve svém specifickém elementu. Místo toho je nově ve výběru možných identifikátorů, odtud se ale ukládá jinak.  Případnou editaci lze sice obejít přes xml, ale to není dobré řešení, zvlášť pokud záznam nestáhnu, založím kompletně ručně a potřebuji sysno zadat, ne jen změnit.

recod info:

![image](https://user-images.githubusercontent.com/79305516/166643750-62aedf1c-ecd5-4ac4-8d49-d027e8139c1f.png)

sysno uložené jako identifikátor:
![image](https://user-images.githubusercontent.com/79305516/166643870-a3805d8d-ffaa-4356-b801-e1ae32a92e26.png)

**Comment by luckajirku** [comment]
Tady je asi jen jeden problém - proč se sysno navíc objevilo v nabídce v "Identifikátor". Sysno bez vazby na zdrojový katalog nedává smysl. 
Jinak ten zbytek je OK, není třeba nic obcházet - při stažení existujícího záznamu se sysno (resp. číslo z pole 001) stáhne do recordInfo - je jak ve formuláři, tak v xml. Stejně to funguje i při ručním vytvoření do čistého formuláře - i tam je dole "Údaje o metadatovém záznamu" vč. "Identifikátor záznamu", který lze vyplnit.

**Comment by ZdenkaSera** [comment]
@luckajirku Ve formuláři je to podle mého od minulého týdne, ale čekala jsem na label k testu :-)

**Comment by albertoh** [comment]
@SykoraLukas pridej label pokud je to hotovo, plz

**Comment by ZdenkaSera** [comment]
@SykoraLukas Formulář je ok, díky (přiznávám, tady jsem neprošla úplně všechny formuláře, :-), Změna sysno se promítá do xml - za mne tedy ok. 
Ještě ale dotaz - sysno zůstalo pro výběr v roletce jako typ identifikátoru - je to něčí požadavek? Pokud ne, byla bych pro je odtud odebrat,  Děkuji.

**Comment by SykoraLukas** [comment]
To nevím, já když jsem začal dělat formuláře, tak sysno bylo jedním z těch co tam už byly, takže jsem přidal jen ty, které chyběly. Pokud tam není a není požadavek na to, aby tam byl, tak bych ho odebral. Co na to @erikamirova  a @svetlym?

**Comment by zabak** [comment]
@ZdenkaSera ještě k tomu sysnu bez vazby na zdrojový katalog: aby bylo sysno jednoznačný identifikátor, mělo by být navázané na katalog a databázi v tom katalogu, jinak stačí mít v Alephu dvě databáze a už je nejednoznačné.

**Comment by ZdenkaSera** [comment]
@zabak Jasně, máme to tak i u nás . ústavy mají svoje virtuální databáze a tentýž titul se může vyskytovat duplicitně. Dokonce i v rámci jedné db může být titul vícekrát aniž by to bylo možné deduplikovat - jednou jako standardní záznam, podruhé jako záznam  k výtisku, který je fyzicky přívazkem. Pokud někdo s těmi dalšími záznamy pracuje už to sysno v roletce nerozporuji :-) @SykoraLukas Tak tedy zavírám.
