### ISSUE TITLE
Formulář NDK svazku monografie - AUTOR - namePart type="termsOfAddress"

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#163]
**Test k issue Popisná metadata - formulář neukazuje všechny údaje (vše je vidět jen v xml) https://github.com/proarc/proarc-client/issues/48**

Ve formuláři jsou samostatná pole pro každý namePart type, kromě "termsOfAddress".

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, je k tomu zapotřebí další info? Díky.

**Comment by ZdenkaSera** [comment]
Ještě doplnění - týká se i ostatních formulářů, kde je "autor". Počkám na info "k testu", teď se nezobrazuje v pravém okně xml, takže není kontrola.

**Comment by SykoraLukas** [comment]
Již se xml zobrazuje.

TermsOfAdress je ve formuláři také. Pokud chcete jiný popis pole, prosím doplňte.

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/27210823/169508830-e0244fd8-cdb5-493c-941e-460c1d1f36cd.png">

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, už jsem si všimla - vlezla jsem asi doprostřed vývoje ... Uložení v xml je ok, diskusi o pojmenování pole nechám na těch, kdo užívají PA denně.

**Comment by SykoraLukas** [comment]
Zatím jsou tyto pole pojmenovány napevno. Ale jak jsem zmiňovali na schůzce, chce se připojit knihovna ze Slovenska, takže se bude muset udělat lokalizace všech polí + nápověd. Rád bych tedy aby s buildem byl dodáván i základní soubor s názvy polí a nápověd, ale aby bylo možné to přejmenovat, pokud to někomu nebude vyhovovat.

**Comment by ZdenkaSera** [comment]
Díky. Po pravdě - měli jsme v KNAV interní diskusi o překladech některých polí, práce s českými názvy je trochu nezvyk. Hledala jsem, jak to bylo s překlady a našla jsem v zápise, že po dokončení prací na novém klientovi se případně udělá revize. Tak ještě počkejme.

**Comment by luckajirku** [comment]
jen na okraj k té lokalizaci - zatím ještě neproběhla ani revize českých pojmenování polí (aby to nebyly na koleně tvořené "překlady", ale vyšlo se z termínů používaných v katalogizační praxi)...

**Comment by luckajirku** [comment]
a koukám, že @ZdenkaSera byla rychlejší:-)

**Comment by SykoraLukas** [comment]
OK, počkáme na revizi překladů.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Nenašla jsme formulář, kde by to u autora nebylo; ukládání do xml jsem zkusila v NDK svazku - za mne ok, děkuji.
