### ISSUE TITLE
Nefunkční listování - správa dávek

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#164]
**Listování ve správě dávek**

V případě zobrazení více než sto položek nefunguje listování. Po kliknutí na další část seznamu se nic nestane a nezobrazí se položky, které následují po stovce (příloha 1 a 2).

Zároveň v případě zobrazení méně než sto položek (např. při filtraci menšího množství výsledků) se nezobrazuje aktuální počet zobrazených položek (1-4 of 100).

![image](https://user-images.githubusercontent.com/37616300/167359925-3c9199aa-f925-4ce4-bd90-d4f4e307a48a.png)

![image](https://user-images.githubusercontent.com/37616300/167359967-025f10e2-7ba5-44f7-8046-14173206188b.png)

![image](https://user-images.githubusercontent.com/37616300/167360037-9e452878-a635-4afc-9340-058e9aed10bd.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, mohla byste zkusit, jeslti je ok? Díky.

**Comment by erikamirova** [comment]
@ZdenkaSera Pan Sýkora nám musí nasadit zaktualizovanou verzi, takže to pak vyzkouším a dám vědět. :)

**Comment by erikamirova** [comment]
@albertoh Listování stále nefunguje. Když si seznam posunu o 100 položek dále, tak se mi to reálně posune pouze o jednu položku. Viz níže. 

V případě zobrazení méně než sto položek (např. při filtraci menšího množství výsledků) je to již v pořádku a ukazuje se reálný počet položek. 

![image](https://user-images.githubusercontent.com/37616300/171139863-8f6bed43-fe00-46de-9269-2f59fae19eeb.png)

![image](https://user-images.githubusercontent.com/37616300/171139720-58b10d25-e5e4-4663-bf3d-1dba80d80c67.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, je tohle už ok? Díky :-)

**Comment by erikamirova** [comment]
@ZdenkaSera Je to v pořádku.
