### ISSUE TITLE
Export původních skenů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#165]
V jádře -  issue [#1368](https://github.com/proarc/proarc/issues/1368). Po vydání další verze klienta přetestovat  - na Inovatoce nelze vzhledem k nepřístupným exportním adresářům.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Funkce exportu surových skenů je v klientovi dostupná a podle mne funkční. Prosím, ověř si to u nás a případně uzavři issue. Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko při Exportu pův. skenů mi to hodí chybu: 
![obrazek](https://user-images.githubusercontent.com/24409660/175252441-62f95086-0095-4822-a7b6-af848268e509.png)

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Při exportu Skenů - mi to vyeportuje bez prefixu, který jsme chtěli podle issue https://github.com/proarc/proarc/issues/1368

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Zkusím, tohle fungovalo.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Tak Export pův.skenů je v pořádku.  export Skeny - chybí ten prefinx, ale podle issue https://github.com/proarc/proarc/issues/1368 jsme to u tohoto ale ani nepožadovali, takže bych to nechala být....jestli to teda nechcete vy, možná by to tam taky mohli dodělat....co myslíš?

**Comment by ZdenkaSera** [comment]
@albertoh U použitého titulu to vypadá na problém s interpretací některých znaků - máme tam tvrdé a měkké znaky používané v cyrilici. Založím nové issue a uvedu do něj sysno toho titulu (v jádře fungoval, máme jej už v Krameriovi)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, díky - export původních skenů navrhuji zavřít a ohledně případné úpravy exportu jpg se napřed domluvit interně :-)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Dle domluvy dávám návrh k uzavření, expork jpg zde neřešíme.

**Comment by SmejkalovaAnna** [comment]
Ok.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku, po jehož přidání issue nikdo nekomentoval.
