### ISSUE TITLE
Možnost zamknout dokončený záznam

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#166]
@SykoraLukas @albertoh Prosím o doplnění funkce do nového klienta  - v jádře issue [#887](https://github.com/proarc/proarc/issues/887). Děkuji.

**Comment by SykoraLukas** [comment]
Request URL: https://proarc.inovatika.dev/api/rest/v1/object/lockObject

pid: uuid:6b1ba220-72a3-4a7b-bdd2-c8300e1d7a1e
pid: uuid:009134ef-4922-434e-ab04-9b648bad9f44
model: model:ndkperiodicalsupplement

###


Request URL: https://proarc.inovatika.dev/api/rest/v1/object/unlockObject

pid: uuid:6b1ba220-72a3-4a7b-bdd2-c8300e1d7a1e
pid: uuid:009134ef-4922-434e-ab04-9b648bad9f44
model: model:ndkperiodicalsupplement

**Comment by ZdenkaSera** [comment]
@SykoraLukas Moc díky, ale pokud to nabízíte jako test, nevyzkouším, nemám oprávnění.

**Comment by SykoraLukas** [comment]
Nene, to jsou informace pro @albertoh aby věděl, jak volat API

**Comment by albertoh** [comment]
Pridano
![image](https://user-images.githubusercontent.com/5946836/168255600-0aa94e76-8db8-4284-8dad-b756053d334a.png)

**Comment by luckajirku** [comment]
1. Jakým způsobem lze zamknout ročník periodika? V horní polovině obrazovky zamknu celé per., ale ono dost často se tohle využije právě jen na jednotlivé ročníky, takže by to tlačítko zamykání/odemykání mělo být i v dolní polovině obrazovky. 

2. Vzhledem k tomu, že právo zamykat budou mít všichni uživatelé, by nebylo od věci mít tam podobný dialog jako u mazání - kdyby někdo klikl nechtěně (přeci jen je to tlačítko dost na ráně), aby se ho PA zeptal, jestli to skutečně chce.

jinak naše testování:
- založit nový objekt v zamčeném objektu - nelze, OK
- snaha smazat zamčený objekt - točí se kolečko
- změna v metadatech zamčeného objektu - točí se kolečko

**Comment by luckajirku** [comment]
a ještě:
- Uzamknout objekt / Odemknout objekt je zbytečně dlouhé a zabírá místo na liště, postačilo by Zamknout / Odemknout

**Comment by albertoh** [comment]
Opraveno.
 - Pridal jsem tlacitko i dole
 - Objevi okno pro podtvrzeni
 - Toci se kolecko opraveno
 - Napis zkracen

**Comment by luckajirku** [comment]
Tlačítka dole OK, okno pro potvrzení OK. Akorát když změním stav zamknuto/odemknuto v dolní polovině obrazovky, vše proběhne, ale vyhodí mě to z toho periodika - v horní tabulce to skočí na první titul a pak si musím tenhle znovu najít, abych si to zkontrolovala. 

Jedna kosmetická ještě k těm popiskům: Uzamknout vs Zamčený - buď bych používala Zamknout/Zamčený, nebo Uzamknout/Uzamčený, ať je to sjednocené,

Snaha o změny v zamčeném objektu:
- hromadný výběr: změním čísla stran apod., odentruju/dám uložit, problikne to - a nic - žádná hláška o tom, že akci nelze provést, protože objekt je zamčený. (Ve starém hláška (byť s překlepem) vyskakuje.)
- jednoduchý výběr: změním číslo strany, odentruju - stále se točí kolečko

Snaha smazat zamčený objekt: OK, nelze, a vyhodí to hlášku (i když nahoře je dost nevýrazná - asi by bylo lepší to větší okno uprostřed - stejně jak je třeba u nevalidních dat). 

S tím nás napadá, jestli by nebylo lepší - to je k diskusi a na další vývoj - kdyby všechny ty volby, které v zamčeném objektu nejdou provést, nešlo zešednout, aby uživatel věděl hned, že to nepůjde.

**Comment by ZdenkaSera** [comment]
@luckajirku Díky !

**Comment by ZdenkaSera** [comment]
V KNAV přetestovaly kolegyně @nezbedova a @SmejkalovaAnna a zatím nemají výhrady, další test po nasazení nové verze u nás.

**Comment by ZdenkaSera** [comment]
Ještě jedna poznámka - na stav objektu můžu sice usuzovat podle funkce zamknout/odemknout na liště, ale v jádře byl navíc indikátor stavu v ATM, v klientovi chybí.

**Comment by albertoh** [comment]
Pridal jsem stav do ATM

Hlasky meli bychom probrat. Zatim, pro test, zmenil jsem chybovou hlasku tak, aby se zobrazovala jako dialog uprostred.
 Neni to stylovano, to poprosim @pkudela az souhlasime.

Pozadavek kontrolu nadrazene na zamykání/odemykání jednotlivých objektu neni ani v jadru. To asi by se melo nejdrive tam vyresit.

**Comment by luckajirku** [comment]
další točící se kolečko - tentokrát při změně v ATM v zamčeném objektu

**Comment by albertoh** [comment]
Opraveno.
Bude jich vic. Ja postupne opravuju co najdu. To co najdete pri testovani udelam prioritne

**Comment by luckajirku** [comment]
Bude jich víc, paráda. Můžeme si dát soutěž programátoři vs uživatelé, kdo jich najde víc... 
Jinak další věc - při snaze o reindexaci stran pomocí tlačítka (https://github.com/proarc/proarc-client/issues/71) v zamčeném objektu to sice neproběhne (potud OK), ale problikne hláška "Objekty byly reindexovány OK".

**Comment by albertoh** [comment]
Opraveno. Zobrazuje se hlaska z jadra

**Comment by luckajirku** [comment]
hláška u reindexace v zamčeném objektu už je OK

**Comment by luckajirku** [comment]
Když odemykám/zamykám, ukáže se změna stavu ve sloupci Zamčený hned jen u toho řádku, na kterém spustím akci, ale ne už u těch podřízených - tam se změna neukáže, byť i tam k ní došlo. Nejde to jinak, než že se musí dát refresh (a tím se ale vyhodím z toho vybraného objektu a jsem zas v tabulce nahoře)? Jen se ptám.

**Comment by albertoh** [comment]
Je to tam

**Comment by luckajirku** [comment]
O kousek jsme postoupili:-). Teď to ukáže aktuální stav správně na té úrovni, na které stojím, plus jednu pod, ale níž už změna stavu vidět není. Př.: jsem na titulu periodika, dám zamknout, vidím Ano u titulu a jednotlivých ročníků, ale u těch čísel a stran pod rozbaleným prvním ročníkem už je Ne, byť změna proběhla. 
Teď mi teda kolega poradil, že nemusím dát refresh, že stačí kliknout na jiný objekt a pak zpátky:-), ale pokud by to mohlo ukázat změny hned a samo a na všech dotčených úrovních, bylo by to uživatelsky přívětivější.

**Comment by albertoh** [comment]
Opraveno.
Jeste dodam, ze to se stavalo, kdyz jste mela rozbalene dalsi urovni.

**Comment by luckajirku** [comment]
Ano, proto jsem to tam i zmínila, že je to pod _rozbaleným_ ročníkem. To, co bylo sbalené, se po rozkliknutí ukazovalo správně. 
Teď už je to OK všude. 

Ještě chybí hláška tady: 
- změna pozice / přesun v rámci dokumentu / přesun mimo dokument - přesunu stranu, kliknu na uložit, nic to nezahlásí. Změna se neprovede, ale měla by vyskočit hláška, že je objekt zamčený.
Jediné, kde jsme zatím narazili na to, že ta hláška u přesunu vyskakuje, je při přesunu u stran, které jsou přímo pod titulem periodika. Ale u přesunů stran uložených pod číslem nebo při přesunu čísel v rámci ročníku nebo přesunu ročníků - tam všude to sice správně neproběhne, ale nic to nehlásí.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
OK, už to hlásí

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.

**Comment by ZdenkaSera** [comment]
@luckajirku @SykoraLukas  Narazila jsem tu na problém s oprávněním - v klientovi jsem zamkla i odemkla objekt pod uživatelem typu "user", který neměl přiděleno ani jedno z oprávnění zamknout/odemknout. Issue otevírám.

**Comment by luckajirku** [comment]
- z čehož vyplývá další věc - že by bylo fajn mít na testování na inovatice uživatele s různými právy...

**Comment by ZdenkaSera** [comment]
@luckajirku No já jsem si právě proto nechala některé testy až na náš systém

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
Díky, otestujeme ale až u nás.

**Comment by ZdenkaSera** [comment]
zamykání/odemykání objektů - podle mého ok:
- superadmin může provést bez ohledu na přidělení speciálního oprávnění pr tuto funkci
- admin a uživatel - mohou provést en s oprávněním

Převody modelů a update objektů zatím v klientovi nejsou dostupné k testu ->> otestováno s výhradami

**Comment by ZdenkaSera** [comment]
Tady odebírám štítky "k testu" a "otestováno", aby nemátly vývojáře - čeká se na další funkce z jádra.

**Comment by ZdenkaSera** [comment]
@albertoh tady jen kopíruji z textu issue, co ještě chybí oproti jádru:
Převody modelů a update objektů zatím v klientovi nejsou dostupné k testu ->> otestováno s výhradami

**Comment by ZdenkaSera** [comment]
Toto je v tabulce k Visku označeno jako hotové - prosím, kde je převod K4 na NDK model dostupný v klientovi?

**Comment by ZdenkaSera** [comment]
Navrhuji zavřít, zbytek se řeší jinde - https://github.com/proarc/proarc-client/issues/217

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku "k uzavření", který nikdo nerozporoval.
