### ISSUE TITLE
Mazání podřízených objektů - chyba v režimu procházení

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#168]
1. Pokud chci po vyhledání objektu v základní obrazovce smazat jen podřízený objekt, dialog vypadá takto - to je ok a objekt se smaže.

![image](https://user-images.githubusercontent.com/79305516/169504601-9dd1ea23-30e4-488c-a350-fe3d8d9e8392.png)

2. Chci-li totéž udělat v režimu procházení, dialog zde zatím nabízí "smazat trvale". To jsem zaklikla a při testu před několika dny tato operace nedoběhla a skončila "kolečkem", dnes je výsledek na obrázku níže, ke smazání objektu nedojde. 

![image](https://user-images.githubusercontent.com/79305516/169505714-592a6e37-f88c-4411-8109-1e7ed53fdd90.png)

**Comment by albertoh** [comment]
Opraveno.  "smazat trvale" jen pro admin

**Comment by ZdenkaSera** [comment]
@albertoh Děkuji, žádné kolečko, žádná chyba :-)  Protože nemám oprávnění, prosím, můžete ověřit, zda je ve smazaných objektech k nalezení uuid:8cd9f397-a502-4011-a957-bdf7c5c3cc52 ? 

Nevím, jestli v klientovi hledání ve smazaných a jejich obnova vůbec je, ve starší verzi (na našem systému) není, v jádře ji má uživatel s admin právy.
Pokud je i tady jen v jádře, prosím, zatím ji do klienta nepřidávejte, chci k dočasnému mazání a obnově objektů otevřít diskusi. Děkuji.

**Comment by SykoraLukas** [comment]
Objekt je ve smazaných. Tedy není odstraněn y fedory.

@albertoh prosím přidat pro admina hledání ve smazaných objektech a možnost smazané objekty obnovit.

**Comment by albertoh** [comment]
Pridano

![image](https://user-images.githubusercontent.com/5946836/170949174-d32adf2c-4be9-43c6-bce4-0ed7850742d1.png)

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, podíval byste  na to ještě? Zkusila jsem toto:
1. Smazala jsem objekt, který byl zřejmě uložen nechtěně (známý problém ukládání nově zakládaných objektů, ze kterých vyskočím  - stejně se uloží).  Byla to NDK monografie - a705e881-55f9-444a-86a1-e86a061cbe1a. Ve smazaných mi nevyskočila. Zkusila jsem při zapnutém "Hledání ve smazaných" třídit - nefungovalo třídění podle žádného sloupce.
2. V podřízených objektech jsem smazala NDK stranu 6a6f7ad9-037b-4ee8-9581-a24f97620074 - zbytek jako v bodě .

Hledám špatně nebo je tam chybka? 
To třídění by se hodilo (mám k funkci dočasného mazání výhrady, protože při obnovení se obnoví samostatný nadřazený objekt a vazby na podřízené objekty jsou ztraceny; pokud nemám jejich uuid a hledám něco smazaného omylem, musím je dohledat podle zpracovatele, nějakého data .... ).

**Comment by ZdenkaSera** [comment]
@albertoh Děkuji, zřejmě jsem udělala chybu, Vypadá to, že "dočasné" mazání, hledání ve smazaných i obnovení objektu funguje jako v jádře. Třídění se řeší jinde, tak zavírám.
