### ISSUE TITLE
Změna metadat titulu s připojenými objekty - chybí upozornění s potvrzením

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#169]
Při změně metadat na úrovni titulu s připojenými objekty (typicky periodikum, které má už založené ročníky s čísly, do kterých se při založení kopírovaly údaje z titulu, nebo třeba vícesvazky...), ve stávajícím rozhraní vyskakuje upozornění, vyžadující potvrzení akce. V novém to chybí.

![hlaska_titul](https://user-images.githubusercontent.com/6359479/170198434-425b3439-3522-47e8-a2f3-9b63750305ac.png)

**Comment by albertoh** [comment]
Opraveno. Uporzorneni vyskoci

**Comment by luckajirku** [comment]
OK, vyskakuje, funguje, zavírám.
