### ISSUE TITLE
Sledování fáze načítání dávky (#967)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#17]
V okně Import - správa importních dávek - by v pravé části, kde je sloupec Vytvořeno, Změněno, Stav, Uživatel, přibyl ještě jeden sloupec nebo ve sloupci Stav - by se během načítání zobrazoval aktuální stav tačítání např. v procentech, abychom věděli u větších dávek, jak dlouho se bude ještě dávka načítat.

**Comment by luckajirku** [comment]
Nelze testovat, nový sloupec tam není a ani ve sloupci Stav se nic neděje.

**Comment by luckajirku** [comment]
Bude s vyřešením tohohle vrácena i možnost práce s jednotlivými sloupci - vytvořeno, upraveno, stav a uživatel? Hlavně Stav - možnost vyfiltrovat si jen dávky v určitém stavu (třeba Chyba načítání) je dost užitečná. 
Nebo to nesouvisí a má na to být zvláštní issue?

**Comment by honza-rychtar** [comment]
> Bude s vyřešením tohohle vrácena i možnost práce s jednotlivými sloupci - vytvořeno, upraveno, stav a uživatel? Hlavně Stav - možnost vyfiltrovat si jen dávky v určitém stavu (třeba Chyba načítání) je dost užitečná.
> Nebo to nesouvisí a má na to být zvláštní issue?

Filtrování podle stavu je tam od začátku. Další filtry přidám #88 

Jinak pokud jde o tohle issue, tak procenta u právě načítané dávky už se zase ukazují.

**Comment by luckajirku** [comment]
Nějak to nechápu. Dala jsem si načítat dávku, otevřu si Správu importních dávek a vidím u té dávky procenta. Ale ta se nemění, je tam pořád stav, který byl v okamžiku otevření Správy. Pokud chci po chvíli vidět aktuální stav, musím dát Obnovit. Takhle to má fungovat?

**Comment by honza-rychtar** [comment]
Původně jsem tam ten autorefresh měl, ale dočasně jsem ho dal pryč. 
Vrátím to, ale ono nestačí jen načítat ta procenta. Když načítaní skončí, tak se změní stav. Pokud mám zapnuty nějaké filtry, tak mi můžou mizet některé záznamy (automatickou obnovou na pozadí se změní vlastnosti, které filtr používá). Měly by se také objevit nové procesy spuštěny jiným uživatelem, protože ten se teď aktuálně může načítat, atd ...

Takže by to by so to pak měnilo pod rukama. Možná by bylo lepší automaticky překreslovat jen tu novou **Frontu načítání** a ve správě dávek si o aktualizaci říct sám přes **Obnovit**.

**Comment by albertoh** [comment]
Pridal jsem checkbox "Automaticky obnovit", ktery zpusobuje obnoveni cele tabulky kazde 10 minut
![image](https://user-images.githubusercontent.com/5946836/155137925-973a02d8-f37b-43d0-8c88-729e9b0c2ab5.png)

**Comment by ZdenkaSera** [comment]
Tlačítko "Zobrazit frontu" zobrazí dávky všech uživatelů, pokud mám omezená oprávnění, budou "vyhvězdičkované"

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, jak to teď vyhovuje Vám? Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Mě to vyhovuje, jak to Alberto udělal.

**Comment by nezbedova** [comment]
@ZdenkaSera Ano, vyhovuje.

**Comment by ZdenkaSera** [comment]
@luckajirku @katerinasirova @erikamirova Můžeme tohle navrhnout k uzavření? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera Za mě by se ještě hodila možnost filtrování dávek dle uživatelů. Jinak je to OK.

**Comment by nezbedova** [comment]
@erikamirova To se, myslím řešilo zde: #109

**Comment by erikamirova** [comment]
@nezbedova Aha, děkuji, toho jsem si nevšimla. Takže tím pádem můžete issue uzavřít. :)

**Comment by luckajirku** [comment]
jen abych to nenechala bez odezvy, když jsem byla označena - vypadá to ok, ale zatím to neřeknu s jistotou - na tom testovacím s minimem (a ještě malých) dávek se to pořádně otestovat nedá, to až v normálním provozu.

**Comment by ZdenkaSera** [comment]
@luckajirku Za sebe souhlasím - bude víc věcí, které so líp vyzkoušíme až na vlastních datech - něco v testu, něco až v ostrém, protože některé věci nepůjdou nasimulovat. 
@erikamirova @luckajirku děkuji

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto, asi se to rozbilo, ve Správě dávek mi to místo počtu procent ukazuje toto:
![obrazek](https://user-images.githubusercontent.com/24409660/175493948-d6e8d341-81c9-43fd-b68d-a367a8c8693d.png)
nemusí to být do 30.6., ale aby to nezapadlo.....

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, prosím, koukla bys na to? Díky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Díky 👍, navrhnu zpátky k uzavření

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku, po jehož přidání issue nikdo nekomentoval.

**Comment by nezbedova** [comment]
Odebírám štítek Návrh na uzavření.

Nezobrazují se procenta průběhu načítání.

Testovány STT a Monografie  na Inovatice. Klient v. 1.1.2

**Comment by nezbedova** [comment]
Hezky se to ukazovalo. A tak jsem si řekla, že to zastavím, abych se podívala jak se budou načítat další. Vyběhla chybová hláška, kterou jsem odklepla, (moje chyba) a vše zamrzlo.

**Comment by ZdenkaSera** [comment]
@nezbedova Stalo se mi totéž - zřejmě při dvojklikiuna "zastavit". Zatím jsem to nehlásila (resp to bylo tady #275), nejsem si jistá tím dvojklikem a zatím jsem nenašla důvody, proč se to někdy stane a někdy ne. Když se odhlásíš z PA a vrátíš, můžeš dál pracovat, z té chyby se nedá vyskočit.

**Comment by nezbedova** [comment]
@ZdenkaSera @albertoh odhlášení nepomohlo. Zkusila jsem i nové anonymní okno a nic. Jsem zaseklá.

**Comment by ZdenkaSera** [comment]
Po novém pokusu doplňuji: zastavení dávky nepadá do chyby (jen) při dvojkliku, taďy se to stalo při označení řádky v seznamu dávek, aniž bych ji mohla vůbec zastavit. Stejná chyba teď vyskakuje při pokusu načíst nové ještě nenačítané dávky

![image](https://user-images.githubusercontent.com/79305516/207588723-84ff27c5-e117-4aa4-81bf-f5053b63bea2.png)

**Comment by ZdenkaSera** [comment]
Tak ještě jinak - chyba na obrázku výše vyskočila a po ní se neotevřelo okno načítání, nicméně proces se spustil na pozadí a dávky jsou ve frontě ve stavu "načítání".. Zkusím to nasimulovat na Inovatice-

**Comment by ZdenkaSera** [comment]
Někdo byl rychlejší - na Inovatice je spadlý import a při pokusu o načtení monograie Metodika krasopisu rovnou padá do chyby. Ale objeví se ve frontě načítání.

**Comment by ZdenkaSera** [comment]
@albertoh @SmejkalovaAnna Chyba vzniká takto:
-  pokud si na dávku jen myší najedu, můžu ji zastavit
- pokud na ni kliknu, abych ji označila a pak kliknu na "zastavit," spadne do chyby

**Comment by albertoh** [comment]
Opraveno na jadre

**Comment by albertoh** [comment]
Klient zobrazuje lepsi hlasku z jadra

![image](https://user-images.githubusercontent.com/5946836/210347063-30a6b49c-7a14-4217-a0d2-15841d1c506c.png)

**Comment by nezbedova** [comment]
Chybí procenta načítání.

**Comment by ZdenkaSera** [comment]
Souvisí s #288 - v načítání dávky úplně vypadlo okno s průběhem načítání, takže uživatel neví, kdy může začít dávku zpracovávat a předčasným pokusem o editaci generuje chyby.

**Comment by ZdenkaSera** [comment]
Okno s průběhem načítání 1 dávky je zpět; při větším počtu načítaných dávek lze % sledovat ve správě dávek. Editace u dávek (tlačítko Pokračování) není u nenačtených dávek dostupné - ok. Zdá se to v pořádku. 

![image](https://user-images.githubusercontent.com/79305516/214084344-0f9870cf-6803-49a6-8e82-2c421f794dd1.png)

![image](https://user-images.githubusercontent.com/79305516/214085895-dae86ca4-30c3-45b7-88fa-1d03c2752635.png)


**Dávám návrh na uzavření.**

**Comment by ZdenkaSera** [comment]
Ještě doplňuji - základní test zastavení dávky,  její opětovné spuštění ( s tím, že počitadlo skenů navázalo a nezačalo znovu od 1)  a spuštění editace ok na monografii. Další testy až za provozu.

**Comment by ZdenkaSera** [comment]
Znovu otevírám - na Inovatice jsem zastavila načítanou dávku na 50 reso. 74%, po opětovném spuštění začalo načítání od začátku.

**Comment by ZdenkaSera** [comment]
Při importech během minulého a tohoto týdne na Inovatice i v KNAV nenastaly chyby, issue zatím zavírám.
