### ISSUE TITLE
Nelze přesunovat NDK Monografie pod vícedílky

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#170]
Tlačítko Přesunout mimo dokument tam je, ale když vlezu do NDK Monografie a dám přesunout mimo dokument, tak se nic nestane. Jde o to, že potřebujeme přesunout celý objekt pod NDK Vícedílnou Monografii.... buď tam přidat tlačítko ( do hlavního okna, jak to bylo ve starém klientovi - Vybrat nadřazený objekt ) nebo ve " Vazbach" - připad do nabídky Zmenit pozici atd. možnost Přesunout celý objekt.

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
@albertoh Přesouvání NDK Monografií pod různé a mezi Vícedílkami funguje, Ale nevím, jak má fungovat to zakroužkované, žádoucí by bylo, aby se zrušila ta vazba na nadřazený objekt bez toho, abych musela vybrat objekt nový.... občas to také potřebujeme jen zrušit Vazbu mezi objekty.  Teď to tlačítko tak nefunguje.....
![obrazek](https://user-images.githubusercontent.com/24409660/170637805-28625c10-b256-4d33-a1df-ddc262a815d9.png)

**Comment by SmejkalovaAnna** [comment]
Pokud by to tak fungovalo, tak bych byla ještě proto, změnit tlačítko dole PŘESUNOUT na ULOŽIT.

**Comment by luckajirku** [comment]
Jen na okraj - jedna věc jsou vícedílky zpracovávané podle dosud platných DMF, kde svazek monografie měl stejný popis, ať byl samostatně nebo pod vícedílkou. Ale nově se bude rozlišovat svazek jednosvazkové monografie a svazek vícesvazkové monografie - a tam se pole trochu liší. Takže ten jednoduchý přesun pak už nebude úplně v pořádku, bude se potřeba nad tím zamyslet, jak by se to mělo chovat, jak dělat kontroly atd.

**Comment by albertoh** [comment]
Zprovoznil a posunul jsem dolu tlaticko. Ten jednoduse odstrani vazbu a necha objekt bez nadrazeneho, jak to dela jadro.
Tlacitko se objevi jen v pripade, ze objekt ma nadrazeneho

![image](https://user-images.githubusercontent.com/5946836/170653480-9ad354ed-897d-4d88-8781-acd3f4acca82.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, přesun svazku pod VD i následné zrušení vazby mi na Inovatice zafungovalo. Nezkoušela jsem přesuny v periodikách.

**Comment by SmejkalovaAnna** [comment]
Já jsem zkoušela Periodika na Inovatice a jde to, u nás to nejde. Přidala jsem poznámku, jak bych chtěla, aby to lépe fungovalo sem: https://github.com/proarc/proarc-client/issues/167

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Díky, tohle tedy navrhuji k uzavření, věci kolem nadřazených objektů se dořeší tam.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
