### ISSUE TITLE
Hláška - export archivu neúplného objektu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#172]
Prosím o úpravu hlášky při exportu archivu objektu bez podřízených objektů - test na Inovatice, uuid:f0763c06-fdac-4833-873f-af5e7a7c9ca7 - přehlédla jsem, že supplement je nedokončený.

Klient:
![image](https://user-images.githubusercontent.com/79305516/170238735-2deb8c90-7f77-4fbe-b7f8-4e1916ed77e1.png)

Jádro:
![image](https://user-images.githubusercontent.com/79305516/170239052-7c415751-2f53-4543-b3dd-1ce7d93480db.png)

**Comment by albertoh** [comment]
Opravil jsem hlasku. Ona je videt po kliknuti na "icko".
Chcete aby hlaska byla videt rovnou? Nebo jde o formatovani?

**Comment by ZdenkaSera** [comment]
Ten dialog s "ičkem" používáte i jinde, tak za mne není problém to nechat jednotné, ale prosím, co si o tom myslí @nezbedova a @luckajirku ?

**Comment by luckajirku** [comment]
Kliknutí na íčko je v pohodě, ale mělo by tam být vypsáno vše - tady se objevuje pouhé "URNNBN identifier is missing" i v případě, že těch chyb, proč export nemůže proběhnout, je víc (např. objekt kromě nemá ani připojené strany).

**Comment by ZdenkaSera** [comment]
@luckajirku Tohle se chová stejně i v jádře a přiznávám, že jsem to tam akceptovala jako fakt :-(

**Comment by luckajirku** [comment]
No ono jak na to teď koukáme, tak to bude asi na revizi těch hlášek celkově...
Třeba když chci vyexportovat titul, který nemá vůbec vyplněná metadata a (ať už má pod sebou strany nebo ne), tak to jako problém hlásí 
Error - missing date issued.
undefined

**Comment by albertoh** [comment]
To je otazka pro @SykoraLukas  :)

**Comment by SykoraLukas** [comment]
To právě nejde, protože kontrola probíhá ve chvílí, kdy se s objektem nějak pracuje. Např kontrola na URN:NBN je ve chvíli, kdy se má vytvořit exportní složka. Další kontrola je kontrola na přítomnost stran, která probíhá ve chvíli, kdy se skládá soubor main_mets a hledají se všechny strany. Ale aby se mohl vytvořit soubor main_mets, tak už pro něj musí existovat složka vytvořená za pomoci urn:nbn.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkuji. trochu jsme si nerozuměli - nečekala bych, že u každého objektu (zde titulu) bude někde trvale uložený protokol, ale právě při spuštění operace - jako např. export - by na jeho začátku proběhl celý cyklus kontrol, které jinak na tomto místě postupně probíhají, chyby/protokol by se ukládaly do interního objektu a na konci po vydání dialogové hlášky/logu by se zase vymazal. Ale vymýšlím si :-) Pokud to tak není, asi teď není na pořadu dne to předělávat :-)

**Comment by ZdenkaSera** [comment]
@luckajirku Za sebe bych tohle zatím zavřela.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
