### ISSUE TITLE
Chyba v zobrazení sloupce "status" - 3.8/1.0.10, systém KNAV

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#173]
@albertoh Prosím o radu, co s tím - pokud se u nás přihlásím pod svým uživatelem (v chromu), je v horní části okna v hledání objektů sloupec "statusy" bez českých textů, ve spodním okně chybí čeština jen u záhlaví sloupce
![image](https://user-images.githubusercontent.com/79305516/170662483-ce89769e-7d7d-438f-83ab-5509ca770291.png)

Pokud se na témže počítači přihlásím jako  uživatel "proarc", je to OK (obrázek níže).  Zkusili jsme jiného "běžného" uživatele (na jiném počítači), taky měl text v pořádku.

![image](https://user-images.githubusercontent.com/79305516/170663213-3871cb0f-f495-406a-ab4b-5aeb1efc5778.png)

**Comment by ZdenkaSera** [comment]
Ještě doplnění: zatím nepomohl výmaz kompletní historie chromu ani použití jiného prohlížeče (MS edge).

**Comment by albertoh** [comment]
Chybely tam ceske texty (pro status undefined). Jinak nevim jak se mohlo u vas stat, ze objekt nema status.
Muzete nahradit soubor v assets/i18n/cs.json s tim to:
 https://github.com/proarc/proarc-client/blob/master/src/assets/i18n/cs.json

Nahradil jsem zip v release (nechtel jsem vydat celou novou)

**Comment by ZdenkaSera** [comment]
Děkuji - to dává smysl - vzhledem k oprávněním vidí každý uživatel jen některé objekty a tedy i různou sadu statusů. Já tam mohu mít objekty, kde jsem chtěla jen vidět metadata stažená z katalogu aniž bych pak ty objekty dál upravovala.

**Comment by PetrKotynek** [comment]
s novým cs.json 
![terrible_UI](https://user-images.githubusercontent.com/37083676/170679033-f212bb26-f1a9-42fd-a552-0ea5a212550a.png)
Petr Kotynek

**Comment by PetrKotynek** [comment]
Omlouvám se, špatně jsem to stáhl / dal jsem raw a zlepšilo se to/. Petr Kotýnek

**Comment by ZdenkaSera** [comment]
@albertoh Potvrzuji, že to pomohlo a texty se už zobrazují, díky za opravu. 
Ale zřejmě je problém ve stanovení statusu na úrovni nadřazeného objektu 👻 trošku tam straší :-). Příklad:
Nedala jsem nic vyhledat, jen jsem v seznamu NDK monografií zarolovala a našla "Protokol ...." na obrázku - strany exportovány, titul bez stavu

![image](https://user-images.githubusercontent.com/79305516/170682601-fcef1df0-a254-4119-910b-d73ab3a9f51d.png)

Pak jsem do vyhledávacího pole dala "protokol" a našla stejný objekt znovu - a už je status i na úrovni titulu:

![image](https://user-images.githubusercontent.com/79305516/170682845-72bb88a9-34d2-413c-940e-30538a61a6a8.png)

**Comment by albertoh** [comment]
Na testovacim nevidim to. Potreboval bych videt jake mate data, proc se jednou nezobrazuje status a potom jo.
Muzu se nejak divat na vas testovaci server?

**Comment by ZdenkaSera** [comment]
@albertoh Řeším to, ozvu se mailem.

**Comment by ZdenkaSera** [comment]
@albertoh Tohle issue zatím zavřu a vrátili bychom se k němu, pokud by se problém objevil u jiného uživatele nebo později v produktivním systému. Děkuji.
