### ISSUE TITLE
Nelze přesunout strany z  monografie do jiného objektu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#174]
Chci přesunout strany z jedné monografie do jiné. Označím, dám přesunout mimo dokument - objeví se Vyberte nadřazený objekt pro
Až se ucho utrhne--: [humoristický román] - tohle je první podivnost, když nepřesouvám celou monografii, ale strany z ní. 
Vyberu jinou monografii atd. a pak mi to vyhodí tohle:

_Chyba
NDK restrictions do not allow: model:ndkmonographvolume<br/> to be in direct relation with: model:ndkmonographvolume<br/> <br/>_
Nevneslo se sem něco s touhle opravou https://github.com/proarc/proarc-client/issues/170?

**Comment by luckajirku** [comment]
a když to zkusím přesunout do  periodika, dostanu obdobnou hlášku

_NDK restrictions do not allow: model:ndkmonographvolume<br/> to be in direct relation with: model:ndkperiodicalissue<br/> <br/>_

**Comment by luckajirku** [comment]
Monografie vypadají v pořádku, z monografie do periodika taky, z periodika do monografie taky... ale ještě je potřeba opravit přesun v rámci dokumentu u periodik. Nebudu na to zakládat nové issue, přidám to sem. 
Přesun stránek z čísla periodika do jiného čísla toho samého periodika: 
_Parent: uuid:b990ce4c-2111-45d5-a5f5-8eaccc7c3eb2 does not contain members: [uuid:7d5f1e61-df53-4fc3-809f-96fbf0dd5cf3, uuid:afca4c84-9b78-4aa0-b2d2-031d49982b79]_

**Comment by luckajirku** [comment]
Pořád to nejde, zkoušeno na Lidové demokracii, Biologických listech, Hudební vědě

**Comment by albertoh** [comment]
Omlouvam se. Porad jsem pouzival pro testovani dialog pro presouvani mimo dokuemntu, ikyzd jsem presouval v ramci dokumentu.
Opravil jsem to.

Ale nevim jestli neni zbytecne mit dva tlacitka, kdyz to same dosahneme v tom dialogu vyberu nadrazeneho

**Comment by luckajirku** [comment]
> Ale nevim jestli neni zbytecne mit dva tlacitka, kdyz to same dosahneme v tom dialogu vyberu nadrazeneho

No my bychom byli pro, tahle přehlídka šipek je nevyžádané "vylepšení". My bychom tam nechali jen tu zahnutou šipku doleva Změna pozice a pak tu rovnou šipku doprava - co je teď Přesunout mimo dokument - nazvat jen Přesunout a tam by se pak vybíral objekt (v rámci stejného titulu nebo jiného) přes výběr nadřazeného objektu.

**Comment by ZdenkaSera** [comment]
@albertoh Tady ještě kosmetika - zkoušela jsem přesun skupiny skenů myší v rámci dokumentu při tabulkovém zobrazení  - to je ok (jednu chvíli to totiž fungovalo jen při zobrazení mřížky nebo náhledů).  Při označené skupině položek v levé části obrazovky se na liště vpravo objeví nápis Hromadný výběr, ale včetně kusu kódu - to navrhuji schovat. Díky.

![image](https://user-images.githubusercontent.com/79305516/173019692-43b982cc-fbad-4005-b919-f8e45fc4df61.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@albertoh Díky, ok.

**Comment by ZdenkaSera** [comment]
Zkoušela jsem přesuny stran mezi různými modely (jako přesun mimo dokument) a nenarazila jsem na problém. Při chybném přesunu jednoho modelu pod jiný to správně nedovolí, jen prosím @albertoh doladit to formátování, děkuji.
![image](https://user-images.githubusercontent.com/79305516/173301087-ad704be8-3ede-46ca-9e9c-9eda9210148b.png)

![image](https://user-images.githubusercontent.com/79305516/173301229-cfcd1bad-45aa-4e8a-971f-cb1e01d34da5.png)

apod.

**Comment by ZdenkaSera** [comment]
@luckajirku Ten přesun v rámci dokumentu neotestuju, definitivně jsem si musela přiznat, že to tlačítko neumím použít. Pro přesun v rámci např. svazku, čísla apod. je to zbytečné, tam funguje myš nebo přesun na jinou pozici. 
Snad prý je určeno jen pro přesuny v rámci víceúrovňových objektů - zkusila jsem strany jednoho svazku vícedílky přesunout do druhého, ale marně a netuším, jestli je to chybou funkce nebo rukama. Prosím o radu. Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera nebojte, nefunguje to. Ale nijak nás to asi netrápí, nepotřebujeme to (a i @albertoh to zmiňoval výš, jestli tam tahle možnost už není nadbytečná). Navrhuji tedy se toho dvoušipkového tlačítka zbavit (nakonec když už nefunguje, tak to ani nebude bolet:-)). 
Jak teď dobře funguje ten výběr nadřazeného objektu, kde se ukazují dole i podřízené objekty, tak vystačíme s myší, přesunem na pozici a přesunem mimo (v rámci kterého lze přesunout i v rámci víceúrovňového objektu).

**Comment by luckajirku** [comment]
S tím, že jak už jsem psala - by se to tlačítko _Přesunout mimo dokument_ přejmenovalo na _Přesunout_, ať to nemate.

**Comment by albertoh** [comment]
Jasne.
Prejmenuju tehdy nazev tlacitka na Přesunout, a dam pryc to nadbytecne

**Comment by albertoh** [comment]
Zmeneno

**Comment by luckajirku** [comment]
Ještě jeden návrh k těm tlačítkům, když na to teď koukáme - mnohem častěji než Změna pozice se bude používat Přesunout - takže by bylo praktičtější, kdyby byla ta tlačítka prohozená - člověk může hned kliknout vs najede myší, posune se kousek dolů a může kliknout. Co na to KNAV?

**Comment by albertoh** [comment]
To bych dal vedle sebe, at nemame tam nejake schovane moznosti

![image](https://user-images.githubusercontent.com/5946836/173527463-0b5211ca-c1f1-46f1-b067-f998e2ec12dc.png)

**Comment by luckajirku** [comment]
No to by bylo vůbec nejlepší. Jestli se to vejde, jsme určitě pro!

**Comment by nezbedova** [comment]
Děkuji. Za nás to je dobré vylepšení. Někdy stačí málo.

**Comment by luckajirku** [comment]
Jen teda ta šipka Přesunout by neměla být v Importu - tam se ukládá celá dávka přes Pokračovat a tohle je tam matoucí (může v uživateli vzbudit dojem, že může rovnou po stránkách rozhodit dávky do jednotlivých objektů - což nefunguje).

**Comment by albertoh** [comment]
Uz neni v importu

**Comment by luckajirku** [comment]
Vypadá to, že už je všechno OK a funkční.

**Comment by nezbedova** [comment]
Zkoušela jsem přesun jednotlivých stran v NDK monografii - funguje.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
