### ISSUE TITLE
NDK Periodikum - datum vydání

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#176]
Nějak divně se stahují roky vydání pro Periodikum - stáhne se to jako interval (vyjimečně se stávalo i ve starém, muselo se smazat a rozepsat do Start a End), ale když dám uložit, tak tam interval zůstane a ještě se to rozhodí do Start a End. Mělo by to tam být jen jednou jako Start a End, viz obrázek: 
![2xdatum](https://user-images.githubusercontent.com/24409660/171341559-ab6c861b-fbcb-4298-aacb-3f09d9bd67ba.JPG)

**Comment by albertoh** [comment]
Opraveno (pokud jsem to pochopil spravne :) )
Otestujte, prosim, jestli jsem to udelal jak si myslite

**Comment by albertoh** [comment]
Nevidim to, nemuzu reprodukovat. U mne to vypada v poradku. Jaky pouzivate prohlizec?

**Comment by albertoh** [comment]
Zuste znovu, prosim

**Comment by SmejkalovaAnna** [comment]
@albertoh Restartovala jsem počítač a už to jde. Díky,

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, dávám tedy návrh na uzavření.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Ano ano.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
