### ISSUE TITLE
Část vynechaná při vyhledávání?

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#177]
Než to napíšu do hlavních issue, nevíte, co znamená toto: 
![tetstovaniPA](https://user-images.githubusercontent.com/24409660/171383180-7667083b-540c-49fb-8df7-56def3e8b317.JPG)

- u výtisku je to tady: 
- 
![obrazek](https://user-images.githubusercontent.com/24409660/171383352-a93d0eb7-2760-4edb-b4a2-58a25183a0f6.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, jde o člen (nonSort(. Napíšu k tomu napřed interně, jak to funguje, je to kombinované s tlačítkem a není to na první dobrou (tj. bez návodu k použití) úplně zřejmé.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Určitě můžeš, jestli je to OK...

**Comment by ZdenkaSera** [comment]
Rozhodla jsem to napsat sem, třeba se bude někomu hodit.
V názvu titulu mám člen "A", který chci vynechat při hledání:

![image](https://user-images.githubusercontent.com/79305516/171386434-d030827d-a1ba-4e4f-96c6-02a9ebe18e49.png)

Po stisku tlačítka se člen (ve skutečnosti část názvu do první mezery) oddělí a přenese do pole "Část vynechaná při hledání". 
Do xml se přidá nonSort s touto vyjmutou částí názvu , 
(Opětovným stiskem tlačítka se  vrátí na původní místo

![image](https://user-images.githubusercontent.com/79305516/171387211-01fada45-337a-4020-b097-cb6f588d79de.png)

![image](https://user-images.githubusercontent.com/79305516/171387303-cb29f32e-d6c6-4d0c-9914-5c46132cc3b1.png)
