### ISSUE TITLE
Formulář NDK svazek - v nevalidním dokumentu lze uložit jen změny v polích, díky kterým je nevalidní

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#179]
Když označím urn:nbn jako neplatné, změna se neuloží. Zkusila jsem s ISBN - taky nelze uložit. (Podle  mého se to při jiné úpravě rozbilo, zneplatnění urn:nbn jsem zkoušela). Test na Inovatice.

**Comment by ZdenkaSera** [comment]
Je to tak - v dokumentu, který nehlásí chyby, šlo uložit vše, co jsem vyzkoušela - zneplatnit cnb, přidat termsofaddress ... 
Pokud jsem ale odklikla v nevalidním dokumentu, že chci změny uložit, nedošlo k tomu.

**Comment by SykoraLukas** [comment]
@ZdenkaSera  Prosím o znovuotestování

**Comment by ZdenkaSera** [comment]
@SykoraLukas Udělám, děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zdá se to ok, děkuji 👍 Zatím to úplně nezavírám, budu zítra zase procházet issues, tak to vyzkouším v dalších kombinacích dat.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
