### ISSUE TITLE
Nefunguje načtení metadat k titulu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#180]
Založím nový objekt, dám Načíst metadata z katalogu - a dostanu prázdná okna, místo objektu s metadaty se uloží jen prázdný objekt.

**Comment by luckajirku** [comment]
Vypadá to, že to nefunguje jen u něčeho - periodikum Panorama z katalogu SVKHK, 001: 000161010

**Comment by albertoh** [comment]
Opraveno.
Duvod byla snaha ukladat nevalidni metadata, a nasledne NEchytani chyb.
Ted chyba vyskoci, a nasledne metadata zustanou neulozene v nevalidnim stavu.

Otestujte, prosim

**Comment by nezbedova** [comment]
Zkoušela jsem to na NDK monografii a STT monografii. Data se mi stáhla.

@luckajirku Prosím, otestujte na tom, co Vám nešlo.

**Comment by luckajirku** [comment]
> Ale tady přetrvává ta chyba, že se titul založí (=zobrazí) ve Správě digitálních objektů, i když je prázdný nebo se neuloží.

jen na okraj - k tomu by nemuselo tolik docházet, kdyby se vrátil zpět ten přirozenější způsob zakládaní objektů - https://github.com/proarc/proarc-client/issues/43

**Comment by albertoh** [comment]
Mate pravdu. Resim tehdy v #43

**Comment by ZdenkaSera** [comment]
@luckajirku Nezavřeme to tady s tím, že pokračuje řešení v https://github.com/proarc/proarc-client/issues/43 ? Děkuji.

**Comment by luckajirku** [comment]
Ano, vypadá to, že se to všechno už dořeší tam. Takže zavírám.
