### ISSUE TITLE
NDK strana - přidání pole pozice do hromadného výběru

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#181]
Do hromadného výběru bude třeba pro NDK stranu přidat pole "pozice" - teď je jen v jednoduchém. 
Jde o to, jak by to mělo vypadat - nejčastější bude střídání pravá-levá-pravá-levá... Použít stejné rolátko jako v jednoduchém (s nabídkou vlevo / vpravo / samostatně) nedává moc smysl, to by se muselo provést nadvakrát, chtělo by to mít už přímo ty řady.

**Comment by albertoh** [comment]
@SykoraLukas pridal jsem do UI parametr pagePosition. Mozne hodnoty:
   'left', 'right', 'singlePage', 'left_right' , 'right_left'

![image](https://user-images.githubusercontent.com/5946836/172574146-de842c3f-c2e4-4d02-898b-34757d33146e.png)

![image](https://user-images.githubusercontent.com/5946836/172574201-c00bcb61-814b-46dd-bf56-68c1d0f5127b.png)

**Comment by luckajirku** [comment]
pokud to pořadí v rolátku nebude nastavitelné uživatelem, bude třeba pořadí ještě upravit - úplně nahoře by měla být ta nejčastější volba: pravá-levá-pravá...

**Comment by albertoh** [comment]
Je to konfigurovatelne. V globals.js 
pagePositions: [ 'left', 'right', 'singlePage', 'left_right', 'right_left']
Treba na 
  pagePositions: [ 'left_right', 'right_left', 'left', 'right', 'singlePage', 'right_left']

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, přidáte později s novou verzí upozornění na novou konfiguraci také na wiki? Moc díky.

**Comment by albertoh** [comment]
Je to na Wiki

**Comment by luckajirku** [comment]
- v tom příkladu máte dvakrát right_left, odmázla bych to, ať to nemate:-)
- ale stejně bych se přimlouvala za výchozí řazení od righ_left a pak až ty další volby... A to tím spíš, že právě u tohohle určování stran už došlo ke zcestnému výkladu (řešilo se u kram. klienta)

**Comment by albertoh** [comment]
Opraveno dvakrat right_left .
Vychozi tehdy bude:
 ['right_left', 'left_right', 'left', 'right', 'singlePage']

**Comment by zabak** [comment]
Můžu se zeptat na ty hodnoty 'right_left', 'left_right'? Nikdy jsem o nich neslyšel a pokud vím, tak je nepodporuje ani Kramerius - dohoda byla na left, right a singlePage. K čemu mají sloužit?

**Comment by luckajirku** [comment]
> Můžu se zeptat na ty hodnoty 'right_left', 'left_right'? Nikdy jsem o nich neslyšel a pokud vím, tak je nepodporuje ani Kramerius - dohoda byla na left, right a singlePage. K čemu mají sloužit?

Mělo by to popsat v hromadném výběru pozice stran - při volbě right_left ti tu první označenou stranu ve výběru popíše jako right, druhou jako left, třetí right, čtvrtou left atd.

**Comment by luckajirku** [comment]
Vypadá to dobře, ale ještě to otestujte i ostatní.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, koukněte na to ještě, něco se se tam "polámalo". Roletka teď vypadá takto, navíc zaškrtávátko "včetně první strany" je nedostupné. Testovala jsem jen na NDK monografii. Děkuji.
![image](https://user-images.githubusercontent.com/79305516/173034526-37c3aaed-f387-4b3b-8ef7-07ceb54ab0b6.png)

**Comment by ZdenkaSera** [comment]
@albertoh Díky, zobrazení už ok :-)

**Comment by ZdenkaSera** [comment]
Editace pozice funguje, v xml propsáno - tak teď jen co na to K7 :-)

**Comment by ZdenkaSera** [comment]
@luckajirku @erikamirova @nezbedova Nehodilo by se pro rychlou kontrolu mít ve výběru sloupců k zobrazení i pozici?
![image](https://user-images.githubusercontent.com/79305516/173056094-5ae26cdd-445f-4360-8a4f-25810344bde9.png)

**Comment by luckajirku** [comment]
hodilo, ale půjde tam přidat pozice, když tam nejde přidat třeba index?

**Comment by albertoh** [comment]
Ja to neudelam. Muzu pridavat sloupce, ktere jadro vraci do hledani. Nevidim ani index, ani pozice.
@SykoraLukas co je mozne? Chapu to tak, ze nekazda hodnota ve xml ma sloupec.

**Comment by SykoraLukas** [comment]
S tímhle bych prosím počkal na Akubru. Jakmile bude nasazena Akubra a Solr na hledání, není problém přidat obě pole. Do té doby by se to muselo vyčíst pro každou stranu z foxml a tím by se výrazně zpomalilo načítání.

**Comment by ZdenkaSera** [comment]
Aha - díky, tak třeba časem.

**Comment by luckajirku** [comment]
Dávám pryč "k testu", Do toho importu je potřeba to ještě doplnit, většina hromadné editace se děje právě tam.

**Comment by SykoraLukas** [comment]
Opraveno, můžete otestovat.

**Comment by luckajirku** [comment]
Funguje i v importu.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
