### ISSUE TITLE
Hromadný výběr - nelze entrem uložit typy stran

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#182]
U hromadného výběru se po zadání čísla strany a po použití Entru zapíší čísla stran.

Pokud chci editovat typy stran musím kliknout na uložit. Uložení pomocí Entru nefunguje.

Entrem nelze ukládat ani výběr Aplikovat na každou 2. stranu.

Pomocí Entru lze ukládat index strany.

Takže to vypadá, že uložit pomocí Entru lze to, co se zapisuje, ale to, co se vybírá z roletky nejde.

Mělo by jít všechno jako v jádře.

Souvisí s #68 

Založila jsem samostatné issue pro popis stran pomocí hromadného výběru.

**Comment by luckajirku** [comment]
A ještě přidám uložení Pozice strany - taky nelze entrem uložit

**Comment by albertoh** [comment]
Opraveno

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, tohle nechám na Tvém posouzení.

**Comment by luckajirku** [comment]
ještě tady nefunguje enter při hromadném výběru u číselné řady - v jádře to funguje

**Comment by luckajirku** [comment]
u číselné řady už OK - jak v importu, tak ve vazbách

**Comment by nezbedova** [comment]
Zkouším na STT a při hromadném výběru mi nejde uložit číselnou řadu ani Entrem ani přes ikonku.

A ještě se "vypne" zaškrtávátko u Editovat čísla stran.

**Comment by nezbedova** [comment]
U NDK monografií hromadná editace číselné řady funguje.

**Comment by nezbedova** [comment]
U NDK monografií hromadná editace typu stran - uložit pomocí Entru - funguje.

**Comment by albertoh** [comment]
> Jen se po uložení pomocí Entru vypne zaškrtávátko.
> 
> Pro NDK monografie to tolik nevadí, ale pro STT by to vadilo (číslování ob stranu)

 Smysl vypnuti zaskrtavatka je, aby jednoduse se potom dalo vybrat globalne "ozavorkovat/odzavorkovat" viz #62

**Comment by nezbedova** [comment]
Smysl vypnuti zaskrtavatka je, aby jednoduse se potom dalo vybrat globalne "ozavorkovat/odzavorkovat" viz https://github.com/proarc/proarc-client/issues/62``

Tak to jsme trochu v kolizi. Vyzkouším to až bude nasazeno u nás. Ale mám obavy, že to u STT bude dost zdržovat. 

Myslela jsem si, že to obejdu přes "Označit řadu", ale to v novém klientovi nemohu najít.

**Comment by luckajirku** [comment]
Za nás se přiznám, že nejsme schopni z popisu pochopit, v čem přesně je problém.

**Comment by nezbedova** [comment]
@luckajirku 
![obrazek](https://user-images.githubusercontent.com/13831946/174237038-a5ab5456-1612-4293-afba-1cbcb8b182e5.png)
Zaškrtnu, vyplním, Uložím.

Dříve - zůstalo zaškrtnuté = mohla jsem něco opravit, a hlavně při popisu listů jsem změnila Sufix z r na v (to šlo číslování ob stranu, které nyní nejde).

Nyní musím znovu zaškrtnout, abych mohla něco opravit nebo změnit. 

Zdá se to jen jeden klik navíc, ale pokud budete mít archy po čtyřech listech (to bývá často), tak se to nastřádá.

A ještě jdu založit issue na "Označit" řadu.

**Comment by luckajirku** [comment]
Jo takhle, už asi chápu. Takže zůstáváte ve stejném výběru stran, jen přepnete na jinou volbu v Aplikovat na (teda až to zas bude fungovat) a změníte číslování.

**Comment by albertoh** [comment]
OK, muzu zmenit chovani, a nechat zaskrtnuto. To jsem delal pro kontrolu neulozenych zmen.

**Comment by nezbedova** [comment]
@albertoh Děkuji. V jádře to nikomu nevadilo, neměl by to být problém ani v novém klientovi. Nám to hodně pomůže.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Asi se tam vnesla teď další chyba, jestli to teda není úmysl - na horní tlačítka ozavorkovat/odzavorkovat lze kliknout a použít (úspěšně), i když jsou vyšedlá.

**Comment by albertoh** [comment]
Nebyl to umysl :( Opraveno

**Comment by luckajirku** [comment]
Za nás tohle už OK, jen jsme při testu narazili na další věc, založila jsem na to nové issue https://github.com/proarc/proarc-client/issues/201.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
