### ISSUE TITLE
Pojemenování tlačítek pro připojení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#183]
Drobná připomínka.

Po připojení popsaných stran k titulu objeví možnost Otevřít objekt v editoru a zavřít. Zavřít přepne do Hledání

Nebylo by lepší přejmenovat tlačítka?

Navrhuji pojmenovat tlačítka:
Otevřít v Editoru
Přejít do Úložiště

Protože po Zavřít, očekávám, že zůstanu na místě (což nepotřebuji).

Je to jen informace, kterou můžeme probrat, ale nespěchá to.

**Comment by luckajirku** [comment]
To Otevřít objekt v editoru mě taky zaujalo, ale velké E to nevyřeší, to zas dělá dojem, že přejdu do obrazovky pojmenované Editor.

**Comment by SykoraLukas** [comment]
Nebylo by lepší to přejmenovat například takto?

Přejít na nadřazený objekt
Přejít do hledání

**Comment by nezbedova** [comment]
Přejít na nadřazený objekt - není ideální. Tam bych očekávala, že budu přímo v metadatech na titul.

A jak se vlastně ta obrazovka jmenuje?

Názvy obrazovek už nemají svůj řádek, což mi pro testování komplikuje popisy situací.

![obrazek](https://user-images.githubusercontent.com/13831946/172769935-b2142b62-e74e-4a35-9495-6ab8eb9b27cf.png)

**Comment by ZdenkaSera** [comment]
@nezbedova @luckajirku Po domluvě ze schůzky prosím o závěrečné shrnutí, jak se má které tlačítko přejmenovat. 

@albertoh Protože jde podle Vašich slov o malou úpravu, přidávám milestone (i když nejde o zásadní funkčnost).

**Comment by luckajirku** [comment]
Jak je tam teď _Otevřít v editoru_ / _Přejít do hledání_ bychom zatím nechali - na podzim se k tomu stejně vrátíme, až se bude řešit úprava obrazovek, rozložení sloupců atd. - až bude jasné, kde co bude a jak to bude vypadat, tak se pak dopilují i ta pojmenování.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
