### ISSUE TITLE
PAGE - při hromadné editaci čísla strany ve vazbách se nezmění hodnota extent unit="pages"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#184]
extent na úrovni PAGE - vytvoří se ve chvíli, kdy doplním v importu čísla stran - přebere do <mods:extent unit="pages"> hodnotu z pagenumber. Tady se chová stejně v jednoduchém i hromadném výběru. Stejně tak se v importu dá toto následně editovat a jak v jednoduchém, tak hromadném výběru se hodnoty mění podle hodnoty v pagenumber.

ALE v úložišti se chová jinak - jednoduchý výběr je OK (při změně čísla strany se změní na stejnou i hodnota v extent), ale v hromadném výběru se přepíše jen číslo strany - a hodnota v extent zůstane ta původní.

**Comment by luckajirku** [comment]
Teda popravdě ani při opakovaném čtení standardu jsem nepochopila, k čemu je to dobré, když jen dubluje informaci z pagenumber, takže ani nejsem schopná posoudit, jestli to vlastně děláme správně, jen upozorňuju na to odlišné chování.

**Comment by SykoraLukas** [comment]
@luckajirku tohle dříve zjišťovala @krizovj jak to má vlastně být a došli jsem ke stejnému závěru - dubluje to informaci z jiného pole. Každopádně opravím toto chování v API, aby se to chovalo jako jinde.

**Comment by krizovj** [comment]
@luckajirku nevím, jestli význam toho údaje vůbec někdo zná :) Podle mě to je to teda zbytečný. Tady je ten dotaz na NDK: https://github.com/NLCR/Standard_NDK/issues/114

**Comment by luckajirku** [comment]
Díky, ještě sem přihodím odkaz na tohle issue https://github.com/proarc/proarc/issues/1054, ale stejně s tím nějak nejsem srovnaná. Ráda bych v tom našla logiku (která tam zřejmě není:-))...

**Comment by luckajirku** [comment]
Chyba v PA byla opravena, chová se to v hromadné stejně jako v jednoduché editaci a je to podle standardu, takže OK. 
(A že se mi to celkově pořád nezdá, je věc jiná:-), tady dávám k zavření.)

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
