### ISSUE TITLE
chyby v selekci skenů

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#185]
1. Při selekci více různých skenů za pomocí Ctrl + kliknutí myši se nemění obrázek (příloha selekce1; selekce2; selekce3). Není tedy možné hned vidět, jaké textové strany označuji a typy textových stran jdou občas poznat dost těžko z náhledu vlevo.

2. Selekce celého bloku za pomocí levého/pravého Shift tlačítka + kliknutí myši - při označení bloku dolů vícekrát za sebou to funguje jak má a vždy zůstane označený celý blok (selekce4; selekce5); při označování nahoru zůstane označená pouze poslední část mezi posledními dvěma kliky a nezůstane označený celý blok (selekce6; selekce7) + i zde platí bod 1, tedy při označování víc části bloků se nemění zobrazení skenu v pravé části a sken zůstává vždy stejný.

selekce 1
![image](https://user-images.githubusercontent.com/37616300/172787426-2df1590a-497e-4698-bc25-9f3543a9d90c.png)

selekce 2
![image](https://user-images.githubusercontent.com/37616300/172787640-7eb807e1-3369-4725-bd6a-f3ad2e869ec1.png)

selekce 3
![image](https://user-images.githubusercontent.com/37616300/172787815-76afbf6f-49c4-4503-99b8-0f61afec6520.png)

selekce 4
![image](https://user-images.githubusercontent.com/37616300/172787904-073743fb-83e6-4c9c-b4f8-8d27a4b892c6.png)

selekce 5
![image](https://user-images.githubusercontent.com/37616300/172787943-28961d31-a0a4-4f54-b1ac-72bbba473be2.png)

selekce 6
![image](https://user-images.githubusercontent.com/37616300/172787982-86088ae4-0843-4341-a784-895a4894de5c.png)

selekce 7
![image](https://user-images.githubusercontent.com/37616300/172788018-ff7213a6-d33b-42a0-b81e-68ffc9ad2b6a.png)

**Comment by albertoh** [comment]
Nevim jak by se to melo chovat spravne... 
 a) Jako ted, tj, zobrazit jen prvni vybrany sken
 b) Zobrazit posledni vybrany sken
 c) Nezobrazovat zadny, kdyz je jich vice vybranych
 d) zobrazovat vsechny. To by mohlo zpusobovat problemy vykonosti, pokud ten vyber je velky. Jak bycho to zobrazovali? pod sebou v pravem okne? To by taky nebyly videt hned vsechny obrazky.

Napiste nazory, prosim

**Comment by luckajirku** [comment]
b) je správně

**Comment by erikamirova** [comment]
ano, za b)

**Comment by albertoh** [comment]
Opraveno. Je videt posledni vybran

**Comment by ZdenkaSera** [comment]
Za KNAV: 
- zobrazení posledního vybraného - ok
- označování bloků se shiftem směrem nahoru - dál se zachovává jen označení posledního - neopraveno

**Comment by albertoh** [comment]
> označování bloků se shiftem směrem nahoru - dál se zachovává jen označení posledního - neopraveno

  Nerozumim. Pochopil jsem to tak, ze zobrazime posledni vybrany objekt, a ne posledni objekt ve vyberu.
  Prosim o vyjasneni :-)

**Comment by ZdenkaSera** [comment]
@albertoh Když skáču shiftem směrem dolů (tj. ve směru zvyšujícího se indexu skenů), postupně přibývají označené skeny, bloky se spojují a správně se zobrazuje poslední označený sken.
Když ale začnu označovat někde dole na obrazovce a skáču shiftem směrem nahoru k začátku, nezůstávají mi označené všechny bloky, ale vždycky jen ten poslední, o který jsem chtěla výběr rozšířit - to je problém lustrovaný na obrázku 6 a 7 výše. Blok se nerozšiřuje, ale stěhuje.

**Comment by albertoh** [comment]
Pochopil (asi) :-)

Opraveno

**Comment by ZdenkaSera** [comment]
Koukla bych se, ale před chvíli jsem se odhlásila a už se nepřihlásím ... prosím, pomůžete?

**Comment by luckajirku** [comment]
Nám taky nejde se přihlásit.

**Comment by ZdenkaSera** [comment]
@luckajirku Už jsem napsala mail na @albertoh a @SykoraLukas

**Comment by ZdenkaSera** [comment]
@luckajirku Přístup už ok s původním heslem.

**Comment by ZdenkaSera** [comment]
@albertoh Označování skenů pomocí shiftu i směrem nahoru už funguje hezky, ale vloudila se asi jiná chyba - v pravém okně teď místo obrázku naskočí formulář pro hromadnou editaci.

**Comment by albertoh** [comment]
V tretim okne? 
V druhem, jo. Tak to bylo vzdycky (a nevim jestli bych mohl to zmenit), a zda se mi v poradku

**Comment by ZdenkaSera** [comment]
@albertoh Samozřejmě ve druhém ... ve třetím je to ok. Omlouvám se! Za mne tedy ok, děkuji.

**Comment by erikamirova** [comment]
@albertoh Děkuji za opravu a otestování. :) V MZK to ještě nemáme nasazené, ale pak to otestujeme a snad to bude ok.

**Comment by erikamirova** [comment]
@albertoh Už jsme to otestovali a většinou to funguje tak, jak jsme chtěli. Narazila jsem ještě na toto. 

Označím si např. strany 20-30 směrem dolů. Pak k tomu chci přidat strany 10-19, zmáčknu ctrl+shift, kliknu na stranu 10 a výběr se mi posune jen na strany 10-20 (ne na strany 10-30).

Když postupuji obráceně směrem nahoru a označím strany 30-20, tak už mi to směrem nahoru funguje. Problém asi nastává, když kombinuji označování více směry. Snad to popisuji srozumitelně...

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Nevím úplně z popisu, jestli MZK chce to samé co my, ale jestli označit více skupin skenů i těch, které na sebe nenavazují, tak to zatím pořád nefunguje správně. (Ve starém shiftem označím skeny 1-10, pak přes ctrl označím sken 25 a se shiftem pokračuju na 30. Označeno mám pak 1-10 plus 25-30.)

**Comment by albertoh** [comment]
Ted to funguje jako Windows Explorer.
Pokud neni to dulezite (kriticke), radsi bych se nepokusil napodovovat jak to delal stary client. Aspon pro zatim, neni to jednoduchy ukol :)

**Comment by luckajirku** [comment]
Kritické to není, ale je to věc, která se používá. 
Ono jako obecně chování ve starém rozhraní je vychytané na základě x-letého používání v praxi (resp. v mezích, co umožnilo SmartGWT - teď samozřejmě navíc přibyly v novém i některé věci, které dřív nešly).

**Comment by ZdenkaSera** [comment]
@erikamirova @luckajirku @nezbedova Na schůzce @albertoh požádal o vyjasnění, zda 
a) je současný stav akceptovatelný a případné vylepšení se může odložit na podzim nebo 
b) jsou nezbytné další úpravy 
Pokud platí b) pak prosí o jasné finální zadání. Děkuji.

**Comment by luckajirku** [comment]
Pokud to bude podzim letošní:-), tak se dočasně spokojíme se současnými možnosti práce se skeny. 
Ale neříkala bych tomu vylepšení, jde o vrácení původní funkčnosti.

**Comment by ZdenkaSera** [comment]
Děkuji, dám sem tedy zatím "odloženo"

**Comment by luckajirku** [comment]
Za nás tady platí letošní termín - tady určitě nepřesouvat do vývoje na další rok.

**Comment by ZdenkaSera** [comment]
Díky, štítek "odloženo" je tak míněn, takhle to má Alberto ještě potvrzené.

**Comment by albertoh** [comment]
Hotovo. Lze vybrat skeny pomoci shift jako pred tim, tj, pokracuje vyber podle posledniho

**Comment by ZdenkaSera** [comment]
@luckajirku @erikamirova Prosím, zkusíte, zda vám touž vyhovuje? Děkuji.

**Comment by albertoh** [comment]
Nedari se mi to reprodukovat. Kde se to stava, v importu? Uloziste? Po ulozeni? Jake mate rozlozeni obrazovky? (mozna neco s toho to zpusobuje...)

**Comment by luckajirku** [comment]
@albertoh teď jsem to chvíli taky nemohla vyvolat, ale asi to nastává, když označuju v tabulce a v jiném panelu mám zároveň otevřený strom, při téhle kombinaci se nám to tady děje všem.

**Comment by albertoh** [comment]
Hm... ten strom mi dava prace... :(

**Comment by albertoh** [comment]
opraveno

**Comment by erikamirova** [comment]
otestovala jsem to v mzk a je to v pořádku :)

**Comment by luckajirku** [comment]
za nás OK

**Comment by nezbedova** [comment]
Narazila jsem na toto.
Pokud označím větší množství strana dám hromadně upravit např. typ strany, tak se to udělá, nechá se to označené, ale skočí to na začátek na první sken (řádek)

Přesněji:

Označím 34 stran. Změní např. Typ strany. Dám enter nebo uložit disketkou. Editované strany zůstanou označené, ale v náhledech mi to poskočí nahoru.
Mám řádky po 4 skenech.
Pokud bych uprostřed knihy označila 4 skeny ilustrací, tak by se mi po uložení objevil začátek všech náhledů.

**Comment by albertoh** [comment]
Opraveno. Po ulozeni panel scrolluje na prvni oznaceni objekt

**Comment by luckajirku** [comment]
Za nás je teda ta poslední změna k horšímu. Že to poskočí tak, aby to naposled editované bylo nejvýš, jak to jde. 
Je žádoucí, aby ve všech panelech ty objekty, se kterými se zrovna pracuje, byly vidět - takže když edituju metadata vybraných stran, vidím tyhle strany jak v panelu s tabulkou, tak v náhledech. 
Ale proč by to mělo skákat nahoru, když ten výběr je vidět v panelu tak jako tak?

**Comment by luckajirku** [comment]
Příklad - mám velkou dávku stran periodika, chci si popsat první 4 strany a pak je použít jako řadu. Nahoře mám 1-4, když u 4. strany změním typ strany, poskočí mi to po uložení tak, že mám, stranu 4 úplně nahoře a zas to musím odrolovat dolů, abych viděla i s. 1-3.

**Comment by ZdenkaSera** [comment]
@albertoh Na schůzce domluveno, že dnes zkusíte upravit/navrhnout úpravu. 
vyjádření všech knihoven prosím.

**Comment by albertoh** [comment]
Je to tam. Zkuste

**Comment by luckajirku** [comment]
Nám to takhle vyhovuje.

**Comment by ZdenkaSera** [comment]
@erikamirova @katerinasirova @nezbedova  Tohle by se mohlo týkat všech - prosím, můžete se na to také podívat a přidat svůj štítek "otestováno" Moc díky 😊

**Comment by erikamirova** [comment]
Já jsem to zkoušela v MZK i v testovacím rozhraní. Narazila jsem na to, že u načtených ani u uložených skenů nefunguje označování většího množství stran pomocí crtl+shift. A to v jakémkoliv zobrazení (tabulka, mřížka, náhledy).

**Comment by ZdenkaSera** [comment]
@erikamirova Teď jsem na Inovatice zkusila u načtených skenů při všech třech zobrazeních (tabulka, mřížka, náhledy) označit pár skenů se shiftem, pak jsem k nim přidala další na jiném místě přes ctrl - obrázek níže. Ale možná jen špatně rozumím, v čem je problém  Odpovídá obrázek tomu, čeho chcete dosáhnout? Děkuji.

![image](https://user-images.githubusercontent.com/79305516/214090888-34f10dc9-087f-4211-9642-ff062bed181e.png)

**Comment by erikamirova** [comment]
@ZdenkaSera Myslela jsem to tak, že např. potřebuji označit s. 1-10. Kliknu na stranu 1, pak ctrl+shift a na stranu 10. Označí se mi jen strana 1 a 10 a ne 1-10.

**Comment by erikamirova** [comment]
@ZdenkaSera Aha, máte pravdu, funguje to. Omlouvám se. Já jsem mačkala ctrl+shift, a proto to nešlo. Takže za MZK je to v pořádku. :)

**Comment by ZdenkaSera** [comment]
@erikamirova Moc díky.

**Comment by nezbedova** [comment]
Funguje. Otestováno na STT ve Správě dávek i Úložišti.

**Comment by katerinasirova** [comment]
otestováno, řešení nám vyhovuje

**Comment by ZdenkaSera** [comment]
@erikamirova Vzhledem k vyjádření všech dávám k uzavření.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
