### ISSUE TITLE
NDK kapitola - ve formuláři chybí "part"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#186]
Ve formuláři pro NDK kapitolu chybí element part, není kam zapsat rozsah stran.

**Comment by SykoraLukas** [comment]
Doplním

**Comment by luckajirku** [comment]
Ve formuláři v novém klientovi to pořád není.

**Comment by SykoraLukas** [comment]
Nasazeno.

**Comment by luckajirku** [comment]
- pod type je na výběr hodnota volume, která tam nemá co dělat - místo pageNumber a pageIndex

**Comment by luckajirku** [comment]
teď ještě koukám, že ono je to i zvláštně propojené - volume je pod part, ale propisuje se do physicaldescription. A tam type nepotřebujeme, ale pod part ano (jen s jinými hodnotami).

**Comment by SykoraLukas** [comment]
U sebe mám opraveno. Nasadíme

**Comment by luckajirku** [comment]
@SykoraLukas prosím tě, je tohle už k testu, nebo ne (když nemá label)?

**Comment by luckajirku** [comment]
NDK kapitola založená pod NDK monografií (přes plusko):

- při pokusu o uložení píše: 
Chyba
Not found! PID: uuid:9e33ed96-b38f-4af4-80bc-662173ad57a1, uuid:9e33ed96-b38f-4af4-80bc-662173ad57a1

- při pokusu o smazání vyhodí tak dlouhou chybu, že to sem ani kopírovat nebudu.

NDK kapitola přes Nový objekt:

- když zkusím založit kapitolu úplně samostatně s tím, že bych ji tam potom přesunula a udělám změnu v metadatech - hodí to taky chybovou hlášku. 
A když se pak podívám v úložišti, tak prázdná kapitola (bez té úpravy v popisu) tam v tom čase založená je. 

Předtím jen chyběla některá pole, ale teď se to nějak rozbilo komplet.

**Comment by albertoh** [comment]
Souvisi s #43

**Comment by luckajirku** [comment]
part už funguje, ale ještě to chce projít - není tam vše ze standardu, nesedí některé povinnosti..., v subject nám nejde založit nic jiného než topic - u name pod subject to háže tuhle chybu:
Column:33 Line:22 cvc-complex-type.2.3: Element 'name' cannot have character [children], because the type's content type is element-only.

**Comment by ZdenkaSera** [comment]
Na tohle issue jsem zapomněla - zkusila jsem přes plusko založit NDK kapitolu pod NDK monografií, formulář je prázdný. Nepotřebujeme urgentně,, můžeme dořešit s novými standardy.

![image](https://github.com/proarc/proarc-client/assets/79305516/22bc3a09-dad8-46da-84a3-affa238f076c)

**Comment by albertoh** [comment]
Opraveno. Chybela sablona na serveru

**Comment by ZdenkaSera** [comment]
Moc díky @albertoh, je to ok.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
