### ISSUE TITLE
Problémy s přesuny objektů tažením myši

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#187]
Problémy s přesuny objektů tažením myši:

tabulka OK
- mám označených více stran = můžu přesouvat kamkoli včetně poslední pozice, a to jak při označení jednoho, tak i více objektů

mřížka a náhledy
- mám označených více stran = pro přesun je potřeba stát na kterékoli jiné než první označené straně (tu, co je nejvíc vlevo, nelze "chytit")
- mám označenou jednu stranu, nelze přesunout tažením té označené strany, ale lze ji přesunout tažením za následující stranu (tou jedinou lze potáhnout - a původní musí zůstat označená)
- pokud neoznačím žádnou stranu, jen jednu stranu potáhnu myší, ve skutečnosti přesouvám tu stranu předchozí

Jako je to zajímavý hlavolam (a možná tam budou ještě další vtípky, na které jsme zatím nenarazili), o tom žádná, ale uživatel by ocenil předvídatelnější chování.

**Comment by ZdenkaSera** [comment]
@luckajirku Aha - já zkoušela jen skupinu a zřejmě jsem tedy jen náhodou táhla za některou z prostředních stran... To by asi nebyl takový problém, ale @albertoh tažení jedné strany vedlejší k označené je chyba

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@luckajirku Za nás - zdá se mi to ok, snad jsem zase něco nepřehlédla :-) (i tady ale platí, že jakmile označím více stran k přesunu, obrázek v pravém okně je nahrazen formulářem #185)

**Comment by nezbedova** [comment]
Já s tím trochu bojuji. Např. mi (ani v Editoru ani ve Vazbách)  nejde udělat více přesunů. Vždy jen jedna strana (nebo blok) a musím uložit.

**Comment by albertoh** [comment]
> Já s tím trochu bojuji. Např. mi (ani v Editoru ani ve Vazbách) nejde udělat více přesunů. Vždy jen jedna strana (nebo blok) a musím uložit.

Tomu nerozumim. Co znamena nejde delat vice presunu? Mne to jde (chrome/mozilla - uloziste/sprava davek - monografie/priodikum/STT )

**Comment by nezbedova** [comment]
@albertoh - test v Chrom - obrazovka Import - STT

1) Myší přetáhnu jeden sken (např Titulku) na konec, aby byla na posledním místě.

2) Musím kliknout myší na Uložit.

3) Až teď mohu přetáhnout další sken, kam chci a zase myší Uložit.

Ve jádru to funguje tak, že udělám přesun všeho, co potřebuji a pak dám Uložit.

Z praxe:
Jako první sken budu mít Hexatabulku, která patří na konec, za poslední sken. Na konci budu mít hřbet, který chci jako třetí sken. A třeba dosken, který chci zařadit na správné místo. Tech skenů mohu mít třeba 500. 
V jádru to přesunu a pak Uložím všechno najednou. V novém klientovi musím jít sken po skenu.

**Comment by albertoh** [comment]
Uz vidim. Opraveno

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
