### ISSUE TITLE
Tlačítko "Vybrat vše" ve vazbách (#924)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#19]
Praktické by bylo přidat v okně Vazby tlačítko "Vybrat vše"

**Comment by krizovj** [comment]
Tlačítko vybrat vše by mělo fungovat na všechny objekty, a v pravé části se objeví varování, že jsou vybrané různé objekty (takže nelze hromadně editovat).

**Comment by luckajirku** [comment]
Proč je issue zavřené, když nikdo z testujících nenapsal, že tlačítko funguje jak má?

**Comment by honza-rychtar** [comment]
@luckajirku Protože je to přepsané z předchozího ProArcu 
**Tlačítko "Vybrat vše" ve vazbách (#924), Praktické by bylo přidat v okně Vazby tlačítko "Vybrat vše"** 

Tlačítko Vybrat vše tam je. 
Zavírám jen issues, které jsou přepsané ze starších issues a buď se vůbec netýkají nového klienta nebo ten původní problém je řešený. 

Na nové problémy udělejme nové issue, ať je poznat z názvu, že je to nové a o co jde.

**Comment by luckajirku** [comment]
Ok, ale ta issues tady už jsou a takhle je to dost matoucí. Pokud už to Pavel udělal nejjednodušším způsobem a bez přemýšlení tam přeházel všechno, tak uzavírat to stejným způsobem taky není řešení. Bylo by fajn při uzavírání takových issues to nejenom zavřít, ale napsat tam pár slov - buď že se netýká nového klienta a nebude se řešit, nebo se to řeší v jiném issue a přidat odkaz na něj atd.
