### ISSUE TITLE
Tlačítko Obnovit a další rozdíly staré/nové rozhraní v importu 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#191]
Tlačítko Obnovit v importu - když nechtěně člověk něco udělá, ujede mu třeba ruka při přesunu stran atp., tak ve starém je šikovné tlačítko Obnovit, které vrátí skeny do původního stavu. V novém tlačítko zmizelo a je třeba obnovit celé okno v prohlížeči. 

Ve starém se ve chvíli, kdy změním pořadí skenů, editor metadat vypne. Lze pouze uložit nebo obnovit - což je fajn, protože to uživatele upozorní na to, že udělal nějakou změnu, kterou by měl potvrdit. Kdežto v novém přesunu sken v levém okně, neuložím, ale formulář v pravém mi zůstává. Udělám úpravu ve formuláři a tam uložím, uloží se mi jen změna v metadatech, ale sken se vrátí na původní pozici, protože jsem neodklikla uložit i v tom levém okně.

**Comment by albertoh** [comment]
Tlacitko obnovim pridam.
Chovani pri zmene poradi bych nechal jak ted, tj, muzu editovat stranku. Ale v ramci #33 bych pri snahu odejit z editoru, bud tlacitkem "Pokracovat" nebo v menu, bych varoval, je nejsou ulozene zmeny

**Comment by luckajirku** [comment]
V tom případě, který jsem popsala, si to nedovedu představit, jak by to mohlo fungovat. V prvním sloupci přesunu bez uložení stranu s indexem 1 na pozici 3. Ve formuláři ve druhém sloupci se mi ta strana logicky načte s původním indexem, který je v metadadech, takže když v tom formuláři změním číslo strany a uložím, vrátí se mi logicky ta strana na původní pozici.

**Comment by albertoh** [comment]
Kouknete na to, prosim

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
