### ISSUE TITLE
Možnost mít názvy ve formulářích anglicky

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#192]
Uvítali bychom možnost ve formulářích vypnout český "překlad" a mít tam vše anglicky, tak jak je to v xml (a jak je to ve starém rozhraní). Jako volitelnou možnost v cfg.
Diskuse kolem toho už kdysi na schůzce proběhla, ale třeba teď po testování přibude těch, kteří by uvítali návrat ke starým dobrým anglickým termínům:-).

**Comment by albertoh** [comment]
Pripravime to.
Behem priprav, uvidite v rozhrani misto nazvy (ceske, nebo anglicke) cesty v modsu
Tech prekladu je hodne, potrva nam chvilku

**Comment by luckajirku** [comment]
Tady to ještě radši upřesním, protože nějaké změny se tam dějí. Třeba je to jen mezistav, ale pro jistotu: nešlo nám o to mít volbu celý PA česky x celý PA anglicky (ale chápu, že je to asi třeba kvůli cizím knihovnám). 
Co jsme chtěli zpět, je mít možnost vidět anglicky ty "modsové" názvy v NDK formulářích, ale jinak mít PA v češtině a i nápovědy k těm polím (ze standardu) v češtině.

**Comment by ZdenkaSera** [comment]
Tady přidám za KNAV příklad, kde si na český překlad asi nejhůře zvykáme: formulářové pole "vydání" místo issuance a k němu hodnoty monografické/jednotkové/vícedílná.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ujasnili jsme si telefonicky: na liště klienta funguje přepínání CS/EN, tím se řídí nastavení lišt klienta. Ve formulářích při obou volbách zůstávají výrazy z modsu, tj. v angličtině (vyzkoušela jsem)
Pokud bude požadavek, lze další verzi kompletně v CS dodělat.

**Comment by ZdenkaSera** [comment]
Po interní diskusi se vracíme k tomu, že bychom byli rádi, kdyby i kompletně česká verze byla k dispozici pro individuální nastavení uživatele. Tj. například při zvoleném jazyce aplikace CS by pak ve svém profilu mohl uživatel dodatečnou volbou (checkbox) vybrat plně lokalizovanou verzi (založenou na té, která předcházela současné hybridní).

**Comment by ZdenkaSera** [comment]
Shrnuji domluvu ze schůzek: budou k dispozici 3 varianty, přepínat se mezi nimi bude na liště jako mezi běžnými jazykovými mutacemi CS/EN/CSH (?)
- zde diskutovaná "hybridní", tj. anglické texty ve formulářích zasazené do českého prostředí (lišty ...)
- kompletně anglická verze
- kompletně česká verze (s využitím již existujících překladů z verze p. Rychtáře)

Uživatelé je zkontrolují a založí issues na konkrétní úpravy jednotlivých verzí.

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh @pkudela Prosím, je šance, že by tohle mohlo být v nejbližším releasu (který by snad měl vyjít v řádu dní :-)) ? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, s Albertem @albertoh jsme mluvili o vydání verze v pondělí 15.1.  - máme počítat s tímhle issue nebo až s první verzí oprav? Nechceme už verzi oddalovat, aby v MKP a SVKHK mohli pracovat (u nás na verzi není teď závislý produktivní provoz). Díky za info.

**Comment by SykoraLukas** [comment]
Čistě česká verze je doplněna v překladech.

**Comment by ZdenkaSera** [comment]
Lukáši , díky.  Koukala jsme na to zatím jen v rychlosti - je to tak, že pod cs-en je teď verze, která dosud byla jako cs?

**Comment by albertoh** [comment]
> Lukáši , díky. Koukala jsme na to zatím jen v rychlosti - je to tak, že pod cs-en je teď verze, která dosud byla jako cs?
Presne tak. 

Uz je tam i plne ceska verze

**Comment by luckajirku** [comment]
teď to vypadá, že je cs verze (ne cs-en) jako default - je to tak ok?

**Comment by albertoh** [comment]
Ano. Je to v globals.js
Zmenim to na cs-en

**Comment by kerschfilip** [comment]
Prosím přidat aktualizovanou česko-českou verzi překladu: 
[cs.json](https://github.com/proarc/proarc-client/files/14418332/cs.json)

Bylo by možné upravit tu roletku pro výběr jazyka tak, aby po rozkliknutí nabízela podrobnější informace o tom, co si uživatel vybírá? (Pokud teda ostatní budou souhlasit, samozřejmě):
![image](https://github.com/proarc/proarc-client/assets/57805328/dda585eb-7b0d-48d7-bfe9-30a31d2708cb)

**Comment by albertoh** [comment]
Je to na Inovatice

**Comment by kerschfilip** [comment]
@albertoh děkuju, vloudila se mi tam jen drobná chyba, tak prosím o opravu v cs.json:

teď (špatně):
```json
"originInfo/dateOther/value:": "Hodnota",
"originInfo/dateOther/@type:": "Typ",
```

oprava:
```json
"originInfo/dateOther/value": "Hodnota",
"originInfo/dateOther/@type": "Typ",
```

**Comment by ZdenkaSera** [comment]
Prosíme opravit english na English

**Comment by ZdenkaSera** [comment]
Popis jazykových verzí v roletce odsouhlasen na schůzce 1.3.2024, English už na masteru opraveno. 👍.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
