### ISSUE TITLE
Výběr nadřazeného objektu - pamatování naposled použitého objektu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#195]
Při ukládání stran do nadřazeného objektu by si měl PA pamatovat naposled vybraný objekt, jako je to ve stávajícím.
(Určitě to tady už bylo někde v jiném issue zmíněno, ale nejsem schopná to najít.)

**Comment by albertoh** [comment]
Je to #167 
Ale delal jsem to tam. Pamatuje posledni vybrany objekt.
Ono to vybira ve spodni casti, ale neni to spravne oznacene. Upravim

**Comment by luckajirku** [comment]
neotestuju, přesun jinam přestal fungovat

**Comment by albertoh** [comment]
Nasazeno znovu. Ted by to melo fungovat

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
