### ISSUE TITLE
Hromadný výběr - ne/odznačení vybraných stran po uložení

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#196]
Je tady rozdíl v chování v hromadném výběru - po uložení provedených změn se to chová rozdílně:
- stávající rozhraní
import - označené/vybrané strany se po uložení změny odznačí
vazby - označené/vybrané strany zůstávají i po uložení ve výběru
- nový klient
v importu i ve vazbách označené/vybrané strany zůstávají i po uložení ve výběru

Má to takhle zůstat? Za nás - ve vazbách nám to je asi jedno, ale v importu bychom uvítali, kdyby se to po akci odznačilo.

**Comment by nezbedova** [comment]
```
stávající rozhraní
import - označené/vybrané strany se po uložení změny odznačí

```
Odznačí, ale výběr zůstane. 
Za STT je to takto lepší, protože je vidět, co je označené. U monografíí to otestuji při práci. Až to půjde u nás.

**Comment by luckajirku** [comment]
no ono to, že se to odznačí, ale výběr zůstane, je dost špatně - a hrozí, že člověk bude editovat něco, o čem neví.

**Comment by nezbedova** [comment]
@luckajirku Souhlasím s Vámi. To je současný stav. 

Myslela jsem, že mi vyhovuje to, co je v testu - označené je vidět.

**Comment by luckajirku** [comment]
OK, v tom případě to nechme v novém klientovi jak to je.

A pak je jen otázka na @SykoraLukas, jak dlouho se stávající rozhraní bude používat, jestli má ještě smysl opravit to chování v jádře - aby když už to zůstává i po uložení ve výběru, bylo i vidět, co je vybrané.

**Comment by ZdenkaSera** [comment]
@luckajirku @nezbedova Prosím, rozumím tomuhle "OK, v tom případě to nechme v novém klientovi jak to je." správně, že tohle je akceptovatelné a lze to uzavřít? Nebo sem dáme "K testu" a uzavřeme až po domácím přetestování? Děkuji.

@SykoraLukas Lukáši, prosím, koukni na dotaz p. Jirků. Díky.

**Comment by luckajirku** [comment]
@ZdenkaSera ano, rozumíte správně. Nedávala jsem tam label k uzavření jen kvůli tomu jádru, jestli se to ještě nějak bude řešit, nebo ne.

**Comment by SykoraLukas** [comment]
Nové rozhraní chceme začít nasazovat co nejdříve, hned jak budete spokojeni s těmi pár body co jsou v zápise. Chování ve starém klientovi se již upravovat nebude (zůstane v té podobě jaké je nyní).

Do kdy bude dostupný starý klient zatím neumíme odpovědět, musí se nejprve uzavřít editace a práce s objekty a poté dodělat správu uživatelů a RDFlow.

**Comment by nezbedova** [comment]
V klientovi zůstává zaškrtnuto a také je vidět, co bylo vybráno. Za nás se může zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
