### ISSUE TITLE
Návrh na změnu umístění polí věcného třídění ve formuláři 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#197]
Nyní jsou pole "Jazyk", "Fyzický popis" a "Identifikátor" umístěna mezi mods.subjekt a mods.genre.

Navrhuji posunout je před pole mods.subjekt. 

Zmíněná pole jsou u nás upravována častěji než mods.subjekt.

A proč je u všech polí _mods._ ? V jádře jsou popisky samostatně.

**Comment by luckajirku** [comment]
> A proč je u všech polí _mods._ ? V jádře jsou popisky samostatně.

protože je to rozpracované:-) https://github.com/proarc/proarc-client/issues/192#issuecomment-1155070288

**Comment by albertoh** [comment]
@luckajirku  diky za odpoved. @SykoraLukas pracuje na preklady vsech elementu v rozhrani. Az to bude, budeme mit celou aplikaci i v anglictine, s moznost jednoduse pridavat dalsi jazyky

**Comment by ZdenkaSera** [comment]
Protože se neobjevil žádný komentář v souvislosti s přiřazením štítku "k realizaci", odebírám štítek "návrh na rozšíření".

**Comment by ZdenkaSera** [comment]
Všichni - návrh uspořádání formulářů - do příští schůzky.

**Comment by nezbedova** [comment]
Za nás :

> Až k poli Uložení nechat stejné, jak je to nastavené teď v Inovatice na verze v2.0.1 (04.03.2023)

> Pod pole Uložení - dát Identifikátory

>Pod Identifikátory - dát jazyk

> Pod Jazyk - dát Fyzický popis a Abstrakt a  Obecná poznámka k titulu.

**Comment by katerinasirova** [comment]
Za nás návrh pořadí polí:
- název
- autor
- původ předlohy
- uložení
- identifikátory
- jazyk
- fyzický popis
- abstrakt
- poznámka
- typ zdroje
- žánr
- klasifikace
- věcné třídění
- info o části
- údaje o metadatovém záznamu
- informace o souvisejících dokumentech

**Comment by ZdenkaSera** [comment]
Prosím o revizi - MZK, SVHK.

**Comment by erikamirova** [comment]
V MZK toto nevyužíváme, stahujeme si vše z katalogu, takže je nám to jedno.

**Comment by SykoraLukas** [comment]
Kam zařadit pole element tableOfContents.

**Comment by ZdenkaSera** [comment]
Na schůzce doplněno do seznamu elementů výše.

**Comment by luckajirku** [comment]
za nás OK, nemáme s tou změnou problém

**Comment by katerinasirova** [comment]
Prošla jsem na několik periodicích a monografiích, zatím vše v pořádku, takže za nás se může zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
