### ISSUE TITLE
Nefunkční popis "Aplikovat na"

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#198]
Při hromadném popisu stran nelze provádět hromadný popis ob jednu (nebo více) stran.

Po přidání Editovat pozice stran se tato funkce oddělila a nefunguje.

![obrazek](https://user-images.githubusercontent.com/13831946/173794115-08c02d02-e816-493e-ae71-017fa91b3f0d.png)

Jádro:
![obrazek](https://user-images.githubusercontent.com/13831946/173794360-77c7a3a9-ce94-429b-970c-c4c987605cf6.png)

**Comment by luckajirku** [comment]
- v importu to nefunguje (načísluje všechny strany bez ohledu na vybranou možnost v Aplikovat na) 
- ve vazbách funguje bez problémů (testováno na NDK)

**Comment by albertoh** [comment]
> v importu to nefunguje (načísluje všechny strany bez ohledu na vybranou možnost v Aplikovat na)
 @SykoraLukas podivas se na to? je to jadro

**Comment by luckajirku** [comment]
Tohle vypadá, že už funguje i v importu.

**Comment by nezbedova** [comment]
Funguje. Zaškrtnutí zůstává. Pracuje se v tom jako v jádru. Děkuji.
Za nás můžeme zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
