### ISSUE TITLE
V roletce Typ stránky lze vyhledat jen podle 1. písmene

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#199]
V roletce Typ stránky lze vyhledat jen podle 1. písmene. V jádru to šlo i na víc písmen.

Pro vyhledání "titulní strana" - musím 3x kliknout na písmeno "T". 
v jádru lze zapsat "Ti".

**Comment by luckajirku** [comment]
Nám to jde i tady, i na dvě, i na tři písmena... jen je třeba klikat rychle

**Comment by nezbedova** [comment]
@luckajirku Děkuji za ověření.  Jsem pomalejší. "Ti" ještě dám, ale "Pr" mi dělá problémy. V jádru to používám běžně. 
 Budu trénovat :-)
Zavírám.
