### ISSUE TITLE
Hromadný výběr - lze psát do polí i při vypnutém zaškrtávátku

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#201]
Teď jsme narazili na to, že při hromadném výběru lze psát do jednotlivých polí, i když není ta oblast zaškrtnutá. Tlačítko Uložit je sice správně vyšedlé, ale do polí se dá psát a uživatel může třeba změnit číslo strany, odklepne enter - a má pocit, že to upravil. Sice žádná změna neproběhne, ale nemělo by to vůbec být umožněno - jako je to ve starém.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@luckajirku Procházím issues, abych ještě doplnila, pokud někde chybí nutnost dokončení do 30.6.. Prosím, jak tady?

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Super, dokonce je to vypnuté i u Aplikovat na. Zavírám.
