### ISSUE TITLE
Organizace uživatelů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#203]
V jádře je k tomu issue [#109](https://github.com/proarc/proarc/issues/109), tam se nebude dodělávat, řeší se v novém klientovi.

Souvisí s #45      

@SykoraLukas napsal:

Nyní na Inovatice mají všichni uživatelé stejnou organizaci takže hledání přes organizaci najde něco jen v případě, že organizace je Inovatika. V opačném případě se nenajde nic.

Ve verzi 3.8-beta to ještě není plně funkční (funkční od verze 3.8.1-alfa).

Uživatel bez role SuperAdmin vidí jen svou organizaci, ať hledá jakoukoli organizaci. Uživatel s rolí SuperAdmin může filtrovat podle organizace.

Editor organizací není, je tam defaulní seznam s tím, že nabídka je v novém klientovi editovatelné při konfiguraci Klienta.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Máme taky issue https://github.com/proarc/proarc-client/issues/106 - předpokládámm, že tam šlo o základní správu uživatelů (založení, oprávnění ...), ale nejspíš se tahle dvě issue budou řešit společně ? odkaz tady pro jistotu :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Pokud uživatel už založil nějaké objekty a já mu teprve přiřadím v administraci organizaci, do výběru objektů podle organizace se to nepromítne. Rozumím tomu správně, že výběr probíhá jen na základě organizace uložené v ATM? Děkuji.

**Comment by ZdenkaSera** [comment]
@luckajirku @svetlym @erikamirova 
Vrátila jsem se k testu - ve verzi 3.8.2/1.1.2 je správa uživatelů podle mého už funkční tak, jak je popsáno tady #109 kromě uživatelsky editovatelných organizací (ty jsou v konfiguraci).   Prosím o test ostatní, zda můžeme takto ponechat. Issue je v seznamu návrhů na rozšíření, zřejmě už zbytečně. Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera My uživatele (a další věci, které je potřeba otestovat přímo na jednotlivých pracovištích), teď neotestujeme - vlastní testovací ProArc nemáme a s nasazením klienta na ten ostrý čekám, až budou vychytané ještě některé mouchy, zatím stále používáme staré rozhraní.

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji, já vždycky zapomenu .... Přiznávám, že mi tady jde ale taky o princip toho požadavku. Nebyla jsem u diskusí kolem toho zadání a když jsem je četla, napadlo mě ještě jiné využití než jen rozčlenění organizace - např. možnost vyfiltrovat objekty podle projektů ... Ale to by při současné verzi nešlo úplně jednoduše :-)

**Comment by erikamirova** [comment]
@ZdenkaSera My taky nemáme přístup do testovacího ProArcu. Myslím, že bychom rozdělení do organizací ani nevyužívali.

**Comment by luckajirku** [comment]
Ono hlavně potřeba rozdělit to do organizací vznikla v době, kdy se na jednom ProArcu v Incadu zpracovávaly/opravovaly věci pro několik institucí naráz, bylo tam hodně uživatelů odevšad - a mohli se hrabat ve věcech, které vůbec vidět neměli. Tak je otázka, jestli to vůbec někdo užije ještě dneska - jedině snad jestli KNAV...

**Comment by krizovj** [comment]
Bylo to určeno pro uživatele z ústavů AV (z redakcí časopisů), protože si sami zpracovávali záznamy článků ze svých časopisů a nechtěli jsme, aby viděli a mohli manipulovat s jinými než jejich záznamy.
