### ISSUE TITLE
Formulář nového objektu - automaticky rozbalit Datum vydání

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#204]
Formulář nového objektu - to sbalené Datum vydání, vzhledem k tomu, jak důležité to pole je, je dost nepraktické. (Navíc jak je hned  pod tím viditelné  Datum vytvoření, tak to svádí k tomu psát to tam, místo do pole Hodnota, které je schované.) 
Přitom třeba pod Fyzickým popisem je Forma hned rozbalená. Šlo by to udělat stejně?
Takhle to umožní ten objekt založit i bez vyplněného dateIssued, a až když do toho objektu přejdu a dám uložit v editoru - teprve hodí varování, že to pole není vyplněné.

**Comment by luckajirku** [comment]
To ten problém úplně neřeší. Červeně vyznačený je celý Původ předlohy, ale Datum vydání je pořád sbalené. A to Datum vytvoření hned pod tím bude svádět k tomu datum psát tam.
Jestli to správně chápu, tak se to automaticky nerozbaluje proto, že pod tím jsou max. MA pole?

Takhle to teď je:
![date1](https://user-images.githubusercontent.com/6359479/175006428-f15d4fe4-9146-4d32-b2f5-b2c8dd837b0a.png)
A takhle by to bylo lepší:
![date2](https://user-images.githubusercontent.com/6359479/175006448-8d7bf724-5449-475e-80c5-3457091523ed.png)

**Comment by albertoh** [comment]
Muze to byt rozbalene cervene? Jinak bych musel kod uplne prepsat.
Podivejte se, jestli tak to staci

**Comment by luckajirku** [comment]
Naopak, takhle je to i lepší, je to hned vidět. 
Jen v čísle periodika je to pořád sbalené a nevýrazné - uvítali bychom stejné chování i tam, jestli to jde. 
V čísle se to teda chová jinak kvůli tomu, že je to "jen" MA? V jádře se to v čísle per. vysvítí aspoň při validaci, tady ani to. Ale vlastně na ty validace v čísle je tu issue https://github.com/proarc/proarc-client/issues/124.

**Comment by SmejkalovaAnna** [comment]
@luckajirku Já jsem teď zkoušela na Inovatice založit ročník po periodikem a i když vyplním červeně zářící datum vydání a číslo ročníku, tak mi to hlásí, že jsou data nevalidní....(Periodiku mám validní)...je to pod tou úrovní uuid:304ea00d-885f-4e23-bda9-95e7f19f47f6...můžete to Lucko prosím zkusit? Díky moc....

**Comment by luckajirku** [comment]
To vypadá na chybu. Když si stejný ročník, který v novém řve, dám validovat ve starém, tak je OK. 
Navíc u ročníku to řve už ve chvíli, kdy se objekt zakládá, a stejně tak při znovuuložení už vytvořeného objektu ve vazbách.
Oproti tomu u čísla to při zakládání neřve, ale při znovuuložení ano.

**Comment by SmejkalovaAnna** [comment]
@albertoh Mrknete na to prosím? Aby to v další verzi bylo ok....

**Comment by albertoh** [comment]
Udelal jsem drobnou zmenu. Pri zalozeni noveho objektu vsechny elementy oznacene jako "M" jsou rozbalene, a modre.
Pri editaci vsechno zustava po staru, provede se kontrola validnosti pred tim, jak chceme ulozit. A tam bude oznaceno cervene.
Ta kontrola je take jenom na povinnosti (M)

 Reknete, jestli to staci. Pokud ne, to bude na vetsi diskusi, a hlavne pro me, vetsi zmenu kodu.

**Comment by luckajirku** [comment]
Chápu to z pohledu nastavení systému, ale z pohledu uživatele je to nepraktické. Máme v čísle periodika rozbalená pole, která se vytváří kopírováním nebo se hodnoty doplní automaticky, ale zrovna to pole, do kterého musí uživatel vlézt a vyplnit tam datum ručně (pokud nepoužije hromadnou tvorba čísel), je sbalené.

**Comment by luckajirku** [comment]
Ještě radši upřesním, že nám jde o NDK číslo per. a NDK přílohu per. - kde je MA.

**Comment by luckajirku** [comment]
No je, ale jen někde (číslo přes Nový objekt je rozbalené). Ale hlavně to potřebujeme při vytváření přes plusko, jak se ta čísla/příloha tvoří nejčastěji - a tam se to pořád nerozbaluje.

- příloha přes Nový objekt - je sbaleno a musí se rozkliknout (a nadvakrát) 
- číslo přes plusko - je sbaleno a musí se rozkliknout
- příloha přes plusko - je sbaleno a musí se rozkliknout (a nadvakrát)

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, je tady nějaká změna? Děkuji.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Super, funguje, rozbaluje se všude, kde má. 
Jen škoda, že to (vzhledem k důležitosti toho pole) nejde zvýraznit stejně jako ty M pole - ale to asi necháme na vývoj.

**Comment by ZdenkaSera** [comment]
@luckajirku @SmejkalovaAnna Tohle mi - s výjimkou to zatím nerealizovatelného zvýraznění pole - připadá dořešené. Zkoušela jsem teď znovu na Inovatice a zdá se mi to ok. Můžu dát návrh na uzavření? Děkuji.

**Comment by luckajirku** [comment]
jj, automatické rozbalování funguje, může se zavřít, zbytek řešíme v https://github.com/proarc/proarc-client/issues/124

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Můžeš Zdenko...

**Comment by ZdenkaSera** [comment]
Díky oběma.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku "k uzavření", který nikdo nerozporoval.
