### ISSUE TITLE
Přidat/vrátit tlačítko Obnovit i do hledání v úložišti

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#205]
Šlo by vrátit tlačítko Obnovit i do Hledat? (Jako je to ve starém.)

**Comment by albertoh** [comment]
Koukam na stary kliengt, a nerozumim co dela to tlacitko "Obnovit". Neni totez, co tlacitko "Vyhledat" v novem?

**Comment by albertoh** [comment]
Pridano (dole)

**Comment by luckajirku** [comment]
OK. Dole je a funguje.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku, po jehož přidání issue nikdo nekomentoval.

**Comment by luckajirku** [comment]
Znovu otvírám, tlačítko Obnovit bychom potřebovali vrátit i do horní části.

**Comment by luckajirku** [comment]
Už je i v horní části, funguje, za nás možno zavřít.

**Comment by katerinasirova** [comment]
Za nás také OK.

**Comment by ZdenkaSera** [comment]
Za nás taky ok.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
