### ISSUE TITLE
Formulář NDK periodikum - opakováni pole signatura

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#206]
Nový formulář NDK periodika neumožňuje replikaci samostatného pole "signaura", pouze v rámci zopakování celého elementu "location". Prosím o opravu, sigla by se opakovat neměla.
(Opakování signatury se používá, viz neuzavřená diskuse zde   [#1394](https://github.com/proarc/proarc/issues/1394) )

**Comment by luckajirku** [comment]
Když se zakládá nový prázdný objekt přes Nový objekt, ve vyskakovací editaci plusko je.
Když se zakládá objekt stažením metadat z katalogu, tak tam v editoru jsou v xml i další signatury správně, ale ve formuláři je vidět jen jedna a plusko na přidání přímo u signatury tam není.

**Comment by luckajirku** [comment]
Dobrý, už to zabralo. Se nechá ukecávat obrazovku po obrazovce... Takže za nás už OK.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
