### ISSUE TITLE
Při založení nového objektu mít na výběr: přejít do objektu x zůstat v původní obrazovce 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#207]
To vyskakovací okno na zakládání nových objektů, kde to jde hned i editovat, je super. A inspirovalo nás k možnému podzimnímu vylepšení klienta:-). Díky tomu oknu by už nemuselo být nutné pracovat současně ve dvou záložkách (nebo postupně ve dvou obrazovkách), když potřebuje uživatel při popisu stran v Importu založit objekt, do kterého ty strany uloží. 

Teď jsem v Importu, mám popsané strany. Chci založit odpovídající objekt, dám nahoře Nový objekt, v tom vyskakovacím okně ho založím - potud skvělé, že jsem pořád v té samé obrazovce - ale pak mě to hodí automaticky do toho právě založeného objektu.
A v téhle chvíli by bylo fajn vylepšení, kdyby měl uživatel na výběr - buď tam mít dvě tlačítka (1. založit a přejít do toho objektu, 2. založit a po zavření okna s objektem zůstat v Importu), nebo to řešit jinak - třeba zaškrtávátkem (po založení přejít do objektu), ale prostě aby byla po založení objektu i možnost zůstat v té obrazovce, kde uživatel byl, když klikl na Nový objekt. Pak můžu hned v Importu pokračovat a strany do právě vytvořeného objektu uložit. 

Technicky by to počítám problém být neměl, takže spíš nechávám k diskusi - jak přesně by se to mělo chovat, jestli tlačítka nebo zaškrtávátko - a pak jak pojmenovat tlačítka v případě, že by byla dvě tlačítka...

**Comment by ZdenkaSera** [comment]
Protože se neobjevil žádný komentář v souvislosti s přiřazením štítku "k realizaci", odebírám štítek "návrh na rozšíření".

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/195785802-454c82de-5395-4443-964d-c8a1fcda5430.png)

**Comment by luckajirku** [comment]
Perfektní, díky!!! (Zatím se nám ukazují angl. popisky, ale to si počítám sedne samo.)
Pro monografie je tohle ideální, na periodika pak založíme další issue - aby se dala vytvořit celá struktura periodika bez nutnosti pracovat ve dvou záložkách - částečně to s tímhle taky souvisí - ale záleží na tom, jak nakonec budou import i vazby vypadat celkově.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku "k uzavření", který nikdo nerozporoval.
