### ISSUE TITLE
Přidat tlačítko SMAZAT

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#209]
Prosím přidat funkční tlačítko SMAZAT i na spodní lištu v hlavním okně. Teď je jenom na té horní....Děkujeme.
![obrazek](https://user-images.githubusercontent.com/24409660/175499770-d18a12aa-50c7-4303-aa14-652579a15afd.png)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, můžu sem dát "odloženi", tj. stačí řešit v září?

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Určitě.

**Comment by ZdenkaSera** [comment]
Tlačítko "smazat" ve spodním okně má umožnit mazat objekt na nejvyšší úrovni, ale hlavně je určen pro jednoduché mazání podřízených objektů. Zkusila jsem mazat 

1. strany monografie - lze označit jen 1 stranu, po smazání se "kurzor"  v horním okně vrátí na začátek seznamu vyfiltrovaných objektů, tj. nepamatuje si, který objekt jsem upravovala
2. podřízené svazky vícedílné monografie - mohu označit ke smazání jen jeden podřízený objekt, ale smazala se celá vícedílka (periodikum tedy zatím raději nezkouším, abych někomu nesmazala celé)

Prosím, kouknete na to? Děkuji.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Díky. Po provedení operace zůstává kurzor na původním objektu - to je super! 
- Při mazání svazku vícedílné monografie nebo čísla/ročníku periodika se smaže jen označená úroveň - to je ok 👍
 
trvá chyba: ve spodním okně stále nelze ke smazání označit více stran nebo svazků/čísel/ročníků, tj. stále lze mazat jen po jednom kousku.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, půjde tady umožnit označení více objektů ke smazání ve spodním okně? Děkuji.

**Comment by albertoh** [comment]
To bych poprosil vice casu. Pouzivana komponenta pro strom vubec nepodporuje multi-vyber. To budu muset predelat

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko já bych to nechala, aby se to dalo smazat po jednom.... po více kusech pak ve Vazbách. Je to lepší i pro bezpečnost.  Alespon to Alberto nemusí složitě předělávat.

**Comment by SmejkalovaAnna** [comment]
Takže za mě bych to prohlásila za hotové a issue navrhuji zavřít....

**Comment by ZdenkaSera** [comment]
@albertoh @SmejkalovaAnna Děkuji oběma za reakci, navrhuji tedy k uzavření.

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, máte k tomuhle něco? Jinak to zavřu :-) Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera ono ty lišty tady budou potřebovat ještě revizi, ale issue je na přidání tlačítka do spodní lišty, to tam přibylo, takže OK. Jinak ve starém tam jde jít až na úroveň strany a smazat i stranu, tady končím o úroveň výš.

**Comment by ZdenkaSera** [comment]
@luckajirku Díky - já jsem původně čekala mazání až na nejnižší úrovni, navíc s možností označení většího počtu objektů. Dala jsem pak na hlas Aničky a netrvala na tom. Navrhuju, že to zatím zavřu a pokud praxe ukáže potřebu změnit to, vrátíme se k tomu.

**Comment by ZdenkaSera** [comment]
@luckajirku Ještě doplnění k úpravě lišt obecně - souhlasím, Rozložení nechám na zkušených uživatelích, ale na spodní liště např. ještě chybí některé funkce, budu to psát.

**Comment by ZdenkaSera** [comment]
zatím zavírám.
