### ISSUE TITLE
Vylepšení - nabídka Typu stran (#881)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#21]
Při rozbalení nabídky typů stran by bylo praktické, kdyby se zobrazily jen ty nejčastěji používané strany ( podle četnosti užívání přihlášeného uživatele ) - např. jen 8 nejčastěji používaných, a pod tím to omezeným seznamem by byla možnost rozbalení ostatních typů...... co myslíte?

**Comment by luckajirku** [comment]
A ještě lepší by bylo, kdyby navíc to okénko s nabídkou typů stran bylo vyšší (na 8-10 typů) nebo roztáhnutelné do výšky.

**Comment by luckajirku** [comment]
@honza-rychtar Jak přesně funguje ta četnost používání? Marně se snažím typ strany "obsah" dostat do top nabídky... Je to vázané na počet jednotlivých takto označených stran, nebo na počet kliknutí na tu změnu (čili hromadná změna u padesáti stran se počítá jen 1x)?

**Comment by honza-rychtar** [comment]
Nebere se to z používání ale s nastavení, kde jsou přímo vyjmenované typy stran, které mají být nahoře. Stejně jako to je u jazyků.

@luckajirku Má to být vázané na uživatele?
Udělat to vyloženě podle počtu ručních změn konkrétního uživatele je nejsložitější řešení (ale samozřejmě možné).
Pak je možnost to mít jako teď, že je to nastaveno na úrovni konfigurace konkrétní instalace, kde je seznam daný a pro všechny uživatele stejný.
Pak je ještě něco mezi, že se to udělá jako u zobrazení sloupců u hledání, že si to každý uživatel může sám zvolit, které typy stran zobrazovat nahoře.

**Comment by luckajirku** [comment]
Nejvíc by nám vyhovovala ta poslední možnost - nastavení u konkrétního uživatele. Co na to @nezbedova, @tumovam a další?

**Comment by nezbedova** [comment]
souhlasím s @luckajirku

**Comment by honza-rychtar** [comment]
V **Profil -> Nastavení -> Preferované hodnoty** si může každý zvolit libovolné množství preferovaných stran.
Preferované strany se pak abecedně seřazené zobrazí nad zbylými stranami.
Stejně tak lze nastavit preferované jazyky a identifikátory.
Nastavení se zapamatuje na úrovni prohlížeče.

**Comment by luckajirku** [comment]
Super, funguje, může se zavřít.
