### ISSUE TITLE
Nový objekt přes tlačítko "Nový objekt" vs přes "+"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#211]
Ještě k zakládání objektů. Těmi změnami s novým objektem se to totiž docela změnilo - někde k lepšímu, ale jinde k horšímu. Třeba když se vytváří čísla pod ročníkem, tak zas není praktické vidět jen ten vyskakovací formulář bez struktury periodika... Navíc pokud zakládám v periodiku přes plusko, tak chci objekt založit na tom konkrétním místě. A strukturu chci vidět. 
Určitě to pak bude k diskusi - ale tak rámcově - je možné, aby se to chovalo odlišně, když se bude nový objekt tvořit přes tlačítko Nový objekt nahoře (vyskakovací formulář a vytvoří se samostatně mimo strukturu) a přes plusko (zůstává panel se strukturou nadřazeného a objekt se zakládá přímo na tom místě, odkud se akce volá)?

**Comment by luckajirku** [comment]
A teď teda nevím - než jsem issue založila, tak jsme to párkrát otestovali a přes plusko se nám objekty zakládaly mimo strukturu, teď když to zkouším znovu, tak se objekty založí správně...

**Comment by ZdenkaSera** [comment]
" přes plusko se nám objekty zakládaly mimo strukturu, teď když to zkouším znovu, tak se objekty založí správně..."

@SmejkalovaAnna Aničko, prosím Tě, zkusila bys to u nás? Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Mě se zakládají správně ve struktuře....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, díky.
@luckajirku Paní Jirků, tohle tedy necháme na Vás.

**Comment by ZdenkaSera** [comment]
Díky. Takže pak je na nás všech (resp. na uživatelích, kteří s tím opravdu pracují)  se shodnout, jestli to vadí nebo s tímhle budeme počítat ...

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, prosím o test - vzhledem k datu úpravy by to mělo být v té vydané verzi, tj. i na našem testu. Děkuji.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem na Inovatice: 
1. Pokud zakládám další svazek k vícedílné monografii "plusem", uloží se mi do struktury jak stažený z katalogu, tak založený z volné ruky. Při otevření okna pro založení nového objektu se mi rovnou nabízí model zde relevantní, tj. NDK svazek.
2. Pokud chci nový podřízený objekt založit z lišty tlačítkem "nový objekt", nabízí se mi poslední hledaný model  (zde tedy vícedílná monografie), ale k dispozici mám všechny modely dostupné z konfigurace a zakládám nezávislý objekt mimo strukturu.
3. U periodika jsem vyzkoušela zakládání ve struktuře plusem (ročník a číslo) z volné ruky - fungovalo, k dispozici jsou tam jen povolené modely. Založení z lišty se chová jako v bodu 2 - mám k dispozici všechny modely a zakládám nezávislý ojekt.

@luckajirku  Vzala bych tohle chování jako vlastnost a akceptovala je, zdá se mi to ok. Ale možná Vás z praxe napadá, kde by to vadilo. Prosím, jak to vidíte? Děkuji.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, popsala, jsem výše,  jak to teď funguje na Inovatice - prosím, zkus to ještě Ty. Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko projela jsem to a přijde mi to takto v pořádku, nevidím v tom problém, u NDK Monografií i periodik se to chová správně. Na Inovatice. Zkoušela jsi to pro eMonografie? Filip výše psal, že to nešlo a Alberto píše, že to opravil.....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prima, moc díky. eMonografie jsem zatím nezkoušela.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku "k uzavření", který nikdo nerozporoval.
