### ISSUE TITLE
Import - soubory (kromě základních skenů) nelze označit k importu 

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#213]
V klientovi nelze označit k importu (= zakliknout checkbox) archiv ani Kramerius. Pokud ale soubor nahraji ve starém prostředí, lze je v klientovi vybrat pro opětovné nahrání. Tohle je dost důležité, proto ještě přidávám milestone. Na Inovatice nebudeme schopni otestovat.
![image](https://user-images.githubusercontent.com/79305516/176128805-c3930e77-79cf-4ece-a3a2-e332a33071e7.png)

**Comment by albertoh** [comment]
Zmenil jsem cely modul importu. Tam toho chybelo vic. Otestujte, prosim

**Comment by luckajirku** [comment]
Nevím, jestli to takhle divně bylo už předtím, ale je zvláštní, že jde zaškrtnout i ten vyšedlý čtvereček. Když pak dám Načíst, tak se (správně) nic nestane, ale logičtější chování by bylo, aby ty zašedlé vůbec nešly zaškrtnout - aby se nejdřív muselo kliknout na tu zatočenou šipku (Připravit ke znovunačtení), tím se zešedlý čtvereček zviditelnil, a pak až šel zaškrtnout.

**Comment by ZdenkaSera** [comment]
Souhlasím s @luckajirku. Navíc archivní balíček pořád nejde načíst (u něj je jen ten zašedlý checkbox, po jehož označení se import neprovede).

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, co se skrývá pod tím uuid, resp. jak se měl chovat při načtení? Zkusila jsem načíst a čekala jsem, že pak pod tímhle uuid najdu naimportovaný objekt, ale natáhly se odtud jen čisté skeny ke zpracování. Děkuji.
![image](https://user-images.githubusercontent.com/79305516/176847612-ed2db3d5-836c-47d9-b7f0-d520d7c6845d.png)

**Comment by SykoraLukas** [comment]
Požadavek byl, aby uživatel mohl nejprve vybrat složku se kterou chce pracovat a teprve potom vybrat profil se kterým pracuje. Proto se povolilo i zaškrtnutí zašedlých políček. Poté když změní profil tak se zašedlé políčko může aktivnit.

Načtení se pak dočkají jen ty složky, které jsou aktivní a zaškrtnuté. Zašedivělé zaškrtnuté pole se ignorují.

**Comment by luckajirku** [comment]
- uživatelsky je to nesrozumitelné 
- ve výběru profilu a skeneru chybí prázdná možnost "vybrat", která donutí uživatele tomu výběru věnovat pozornost (v jádře je)

**Comment by luckajirku** [comment]
ač se fakt snažím, tak to pořád nepobírám:-). @SykoraLukas ono to už v okamžiku zaškrtnutí dokáže vyhodnotit, zda ta složka je kompatibilní s vybraným profilem?

**Comment by SykoraLukas** [comment]
Ano, ve chvíli zobrazení složek se nově ke všem složkám dotáhnout informace o možnosti načtení pro všechny profily.

Takže uživatel vybere složky co chce a pak teprve muže změnit profil a pak třeba znovu a porad zůstávají zaskrtnute stejně složky jen se mění to, jestli jsou zasedle nebo ne.

**Comment by luckajirku** [comment]
To jsme se dostali už trochu jinam, než na co bylo issue, ale proč ne... Jako je asi zajímavé vidět, když si zvolím nějaký profil, které složky lze pod ním importovat (asi to někdo takhle užije při meganačítání, asi Brno?). Co by chtělo ještě u toho vylepšit, když už to tam je - teď se automaticky nerozbalí ty podsložky. Takhle vidím Monografie šedé, ale pod tím jsou složky, které jsou importovatelné, ale pokud to cíleně nerozbalím, nedozvím se o tom. 

Ale standardně si myslím, že se postupuje tak, že mám svoje složky, vím, které chci importovat a pod jakým profilem... Takže výběr složky - výběr profilu (buď ručně, nebo nastavit defualt v cfg tam, kde se třeba 95% načítá pod jedním profilem) a skeneru (zase ručně / default).

A to, že jde něco zaškrtnout a kliknout a uživatel nedostane ani hlášku, že akce neproběhne, to je špatně.

**Comment by ZdenkaSera** [comment]
Z textu výše mi vyšlo, že jsem ten úplně první test udělala špatně, protože jsem neznala nastavený princip. Zkusila jsem tedy znovu - chová se to, jak popsal @SykoraLukas
- S výjimkou, že soubor ve složce monografie byl k dispozici pro import i s profilem "hudebnina", což asi není ok (test na inovatice) 
- Pokud něco nejde naimportovat, ve správě dávek je pak status "chyba" a pod ikonkou vykřičníku je důvod - ne uživatelsky přehledný na první pohled, ale lze to. Povedlo se mi nasimulovat jen chybu kvůli duplicitě - to je ok.

Souhlasím s poznámkami @luckajirku. 
Nejsem ji jistá, jak bylo míněno označování adresáře s více soubory - pokud mám v označeném adresáři všechny soubory k importu, stejně se mi neoznačí (nezdědí zaklikávátko). Pokud jsou některé soubory k importu a některé ne, zůstane mi (asi správně) ten hlavní adresář zašedlý a více se zase dozvím až po rozbalení a ručně zaklikám ...
 
![image](https://user-images.githubusercontent.com/79305516/181011464-228de7fa-9165-48ef-af63-5c1891bfd471.png)

1. jako občasný uživatel s tím můžu žít, ale hlavní slovo by tu měli mít jiní @erikamirova @nezbedova - prosím 🙏
2. prosím @SykoraLukas @albertoh, aby tady popsali finální řešení (až bude :-)), aby se návod dal převzít do dokumentace. Díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, ten princip rozeznávání vhodnosti kombinace vybraného profilu a složek k importu asi opravdu není šťastná volba. Podle čeho se ta relevance stanovuje? 

Testujeme u nás STT a u nich načítání nefunguje. Zkusila jsem na Inovatice, taky nelze:

![image](https://user-images.githubusercontent.com/79305516/182132411-b7dac97e-14bb-4824-9439-d7813f70549a.png)

@nezbedova info

**Comment by luckajirku** [comment]
Mně nějak pořád není jasné, proč to nejde jednoduše, jak @SykoraLukas psal tady https://github.com/proarc/proarc/issues/484#issuecomment-491713806
_"Po kliknutí na tlačítko importovat/načíst se spustí kontrola, zda je možné danou složku v kombinaci s profilem načíst. Pokud je tato kontrola v pořádku, spustí se import. Pokud není, zobrazí se uživateli hláška Není možné načíst danou složku pod vybraným profilem"_

**Comment by ZdenkaSera** [comment]
@luckajirku Podle mého dobře míněno, ale je tam někde chyba v tom určení, co lze kombinovat.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas V KNAV jsme se shodli, že toto teď nebudeme urgovat, lze obejít importem v jádře. (@nezbedova)

**Comment by ZdenkaSera** [comment]
Na Inovatice jsem v importu chtěla načíst skeny ze složky staré tisky/krátká - s profilem "Staré tisky" nelze (zašedlý checkbox), s profilem Default skončilo hláškou, že chybí OCR - viz obrázek.. Ve správě dávek jsem ale našla uloženo.

![image](https://user-images.githubusercontent.com/79305516/194545965-b4f0d499-ceef-432d-a4f2-27869b7cbac0.png)

**Comment by ZdenkaSera** [comment]
Pardon, není uloženo, přehlédla jsem se (uložena je krátká monografie ze 4.10.). Jak tedy mohu načítat data specifická pro STT? Děkuji.

**Comment by ZdenkaSera** [comment]
Na Inovatice načítám monografie/krátká - systém se zastaví na hlášce (viz níže). Tj. systém nevydá info o průběhu/dokončení procesu. Po uzavření hlášky má ale dávka status načtená a jsou k dispozici 4 skeny

![image](https://user-images.githubusercontent.com/79305516/194546795-20dde457-f9d7-4515-8dd2-26029da9d412.png)

**Comment by SykoraLukas** [comment]
Nasazeno na test Inovatiky. Prosím o otestování.

**Comment by ZdenkaSera** [comment]
@SykoraLukas 

- Podařilo se mi načíst STT/Krátká2 s profilem STT  - ok
- Počtadlo načítaných skenů - ok
- opakované načtení s profilem STT není možné - chyba
- naopak je matoucí, že mohu označit i zašedlé složky - chyba   (načíst nejdou - ok)

![image](https://user-images.githubusercontent.com/79305516/195344788-efa86a46-9dbf-41ad-b023-016762c168b3.png)

- profil Default nabídne opakované načtení u chybné sady modelů včetně STT; pokud tady odkliknu opakované načtení, s STT profilem je pak můžu znovu načíst -je to matoucí, opakované načtení by mělo fungovat taky jen s relevantním profilem
- 
![image](https://user-images.githubusercontent.com/79305516/195345399-19b377cc-bd97-412c-bb65-2cbc31f25b8c.png)

**Comment by ZdenkaSera** [comment]
S načítáním jsme si zatím všichni poradili, takže issue označím jako otestované, ale běžný provoz možná ještě odhalí potíže. Takže nezavírám.

**Comment by ZdenkaSera** [comment]
Po dalších testech dávám návrh na zavření. Štítek "dokumentace" nechávám.

**Comment by SykoraLukas** [comment]
V závislosti na vybrané složce se pro každou profil zjistí, zda je pod daným profilem možné složku načíst či nikoli. 
Níže uvádím podmínky rozhodující pro jednotlivé profily:

- Archive import - nutný soubor `mets.xml`
- Kramerius import - obsahuje alespoň jeden soubor `.xml`
- Zvukový import - obsahuje alespoň jeden soubor s mimeType pro WAVE nebo FLAC
- Default a z něj odvozené - obsahuje alespoň jeden soubor s mimeType pro JP200, JPEG nebo TIFF.

Zároveň je podmínka, pokud složka obsahuje soubor `proarc_import_status.log` tak nejde importovat pod žádným profilem.
