### ISSUE TITLE
WIKI - doplnit konfiguraci APP_GLOBAL.exports

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#214]
Prosím o doplnění archivace starých tisků do konfigurace na wiki. Děkuji.
![image](https://user-images.githubusercontent.com/79305516/176145548-c7e34a83-5764-4c28-92b3-8f7771934e11.png)

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
@albertoh Díky! 👍
