### ISSUE TITLE
Hlídání povolených vazeb i při ukládání stran do úložiště

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#215]
Bylo by dobré hlídat povolené vazby i při ukládání stran z importu do objektů v úložišti. Je dost divné, že jdou v pohodě uložit třeba STT strany do NDK monografie... Dalo by se to omezit?

**Comment by ZdenkaSera** [comment]
@luckajirku Podle mého by se k tomuhle měli vyjádřit hlavně v MZK @erikamirova, ta potřeba převodu STT zřejmě vznikla u nich.

**Comment by erikamirova** [comment]
@luckajirku Ano, vzniklo to u nás, protože jsme neměli funkční model STT hudebnina (nešel export) a museli jsme založit NDK hudebninu s STT stranami. Nyní nám to už funguje, takže jak píšete, je nesmysl, aby pod NDK modely vznikaly STT strany.

**Comment by ZdenkaSera** [comment]
Protože se neobjevil žádný komentář v souvislosti s přiřazením štítku "k realizaci", odebírám štítek "návrh na rozšíření".

**Comment by luckajirku** [comment]
Jen tady doplním, že ty STT strany byl jen jeden příklad, ale šlo obecně o hlídání povolených vazeb, nejen o ten uvedený příklad.

**Comment by luckajirku** [comment]
A teď nevím, jestli tahle věc nevznikla kvůli řešení tohohle issue, že když chci uložit strany do objektu, tak mi to nabídne jen některé modely. Ale jedna věc je mít možnost ten titul jednoduše vyhledat v úložišti (tam bych ty modely neomezovala) a druhá pak to samotné ukládání. To nejde oddělit? Titul periodika si tedy teď najdu jen tak, že dám model:vše a vyhledat podle názvu apod.?

**Comment by ZdenkaSera** [comment]
Myslela jsem si, že se seznam pro založení nového objektu a pro hledání v úložišti řídí stejným konfiguračním soborem, ve kterém můžu mít všechno nebo můžu vyřadit u nás nepoužívané modely. O seznamu pro připojení objektů jsem se domnívala, že má (resp. bude mít) kromě odkazu na (jiný?) konfigurační soubor ještě zabudovanou logiku řízenou povolenými kombinacemi modelů. Ale můžu se mýlit.

**Comment by ZdenkaSera** [comment]
Souvisí s #292

**Comment by albertoh** [comment]
Lze testovat. viz https://github.com/proarc/proarc-client/issues/282#issuecomment-1375219969

**Comment by luckajirku** [comment]
za nás OK

**Comment by nezbedova** [comment]
Otestováno. STT strany nelze ani uložit ani přesunout do NDK monografie ani NDK číslo ani hudebnina. Víc jsem toho netestovala.

**Comment by ZdenkaSera** [comment]
Navrhuji k uzavření - @katerinasirova @erikamirova - ok?

**Comment by katerinasirova** [comment]
Ano, můžete zavřít.

**Comment by erikamirova** [comment]
@ZdenkaSera můžete zavřít

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
