### ISSUE TITLE
Funkce převod modelů a update objektů chybí - v3.8.1/1.1.1

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#217]
V jádře bylo na výběrové/přehledové obrazovce v administraci

![image](https://user-images.githubusercontent.com/79305516/176371007-655e5cb9-3a0f-4e51-8ced-524efb2680e5.png)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/194048050-160eb7e5-bda1-4e7f-a54d-2e41bb83fb7d.png)

![image](https://user-images.githubusercontent.com/5946836/194048173-37d3a8da-8d36-45f1-b424-9f9f12ece768.png)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/194051353-b45ae4af-a5c2-477b-994f-6aa201a4f856.png)

**Comment by ZdenkaSera** [comment]
Na Inovatice nejsou vhodná data, otestujeme až v našem systému.

**Comment by ZdenkaSera** [comment]
Test převodu monografií před schůzkou byl neúspěšný (monografie padala do chyby i v jádře a nešla otestovat). Dnes lepší, ale: 
1. prosím o umístění funkcí _Převod NDK modelů_ a _Update všech objektů_ do lišty spodního okna a umožnit převody i po jednotlivých úrovních, jako je to v jádře. Je sice výhodné spustit převod na horní úrovni, ale budeme na ostrých datech potřebovat i možnost postupného převodu, 
2. Chybí překlad
![image](https://user-images.githubusercontent.com/79305516/209957186-bf999be5-02a0-497f-8dad-41d1b80d802f.png)

3. Chybí možnost převodu K4 monografie zkonvertované do NDK na vícedílnou NDK monografii - viz obrázek z jádra:


![image](https://user-images.githubusercontent.com/79305516/209955695-cd4a8758-45f9-41db-bef0-2e879a0dd3ef.png)

**Comment by ZdenkaSera** [comment]
Teď jsem na funkci převodu modelů klikla, když jsem měla označenou NDK monografii (která jako ND monografie vznikla, nebyl to převod). Obrazovka pak vypadá jinak, než ta ofocená výše:

![image](https://user-images.githubusercontent.com/79305516/209958890-bb3724da-5671-48b2-ba56-65904e54fe3c.png)

**Comment by albertoh** [comment]
Pridal jsem prevod dolu.
Zbytek probereme po novem roce, nerozumim dobre kde je problem

**Comment by ZdenkaSera** [comment]
Našla jsem na Inovatice K4 periodikum - podle úrovně, na které stojím ve stromě, se zobrazují jen relevantní možnosti převodu - to vypadá super. Funkce pro převod K4 monografií také dostupné. Převod ale otestuji až na vlastním systému, takže tohle issue zavírám a případně otevřu nové, pokud bude problém v metadatech

![image](https://user-images.githubusercontent.com/79305516/214812024-a693635d-0ed2-44a3-80fb-55e344bcf744.png)
