### ISSUE TITLE
Přidělení urn:nbn víceúrovňovým objektům - v3.8.1/1.1.1

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#218]
Přidělení urn:nbn víceúrovňovým titulům se chová jinak, než v jádře, níže příklady.

**Comment by ZdenkaSera** [comment]
Příklad 1. - vícedílná STT s chybou v jedné části: 
Při pokusu přidělit urn:nbn vícedílné STT monografii byla nalezena chyba v jedné části a ta zabránila přidělení urn:nbn. To bylo přiděleno jen druhé bezchybné části, aniž by o tom klient vydal hlášení. 
Ověřila jsem stav přidělení v jádře, tam se zobrazila tato tabulka:

![image](https://user-images.githubusercontent.com/79305516/176377062-6a28b348-f874-4920-82bc-0ba2f6bccdbc.png)

V klientovi se opakovaně zobrazuje jen hláška, která je v jádře ve spodní části přehledové tabulky., tj. informace pro uživatele je neúplná.

**Comment by ZdenkaSera** [comment]
Příklad 2 - úspěšné **nové** přidělení urn:nbn sice klient oznámí, ale uvede jen první ze seznamu přidělených urn:nbn:

![image](https://user-images.githubusercontent.com/79305516/176378530-5d21f083-b2db-4435-958e-e0a9503de222.png)


Příklad 3 - při **opakovaném** přidělení také klient informuje jen o prvním nalezeném urn:nbn (opakovaně přidělíme omylem, ale také se děje při přidělování urn:nbn nově přidaným částem z nejvyšší úrovně, někdy používáme záměrně k ověření, že všechny části mají urn:nbn)
![image](https://user-images.githubusercontent.com/79305516/176379658-881d7d74-67d7-4c99-ae57-36540f06d3b6.png)

Stejná funkce v jádře vydá úplný přehled existujících nebo nově přidělených urn:nbn (indikátorem je druh "smajlíka")
![image](https://user-images.githubusercontent.com/79305516/176380192-3520e376-4507-409a-8f8b-061eb0adeb31.png)

**Comment by luckajirku** [comment]
Také jsme pro návrat kompletní tabulky (a nejen u víceúrovňových objektů, postrádáme ji i u přidělování jednomu nekomplikovanému objektu). S odebráním smajlíků jsme se zatím nesrovnali - zmizela ta jediná trocha lidskosti, kterou systém projevoval:-)...

**Comment by ZdenkaSera** [comment]
@luckajirku tak pár smajlíků aspoň od nás: 😊😊😎

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Tady máme prio - prosím, posunulo se to? Děkuji.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas  Po diskusi na dnešní schůzce odebírám prio, stačí na podzim - chybějící zobrazení lze obejít přidělením ve starém klientovi.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem na NDK monografii - 1) přidělení urn:nbn titulu s chybou, - vydá hlášku o chybě. 2) první přidělení - ok, 3) opakované přidělení - ok, vydá info o již existujícím urn:nbn.
Totéž jsem otestovala pro vícedílnou monografii a periodikum s 1 ročníkem/číslem- zatím jsem nenašla chybu, hlášky byly správné, vždy pro všechny části.  za tím tedy ok.

**Comment by ZdenkaSera** [comment]
@albertoh Moc díky, je to super 👍 Prosím, je při hromadném přidělování urn:nbn (jde hlavně o periodika) nějaký limit, kolik čísel se dá spustit společně?, tj. zda má vyskakovací okénko nějako omezenou délku. Děkuji.

**Comment by albertoh** [comment]
Client nema zadny limit. Zobrazi vsechno co prijde z jadra

**Comment by ZdenkaSera** [comment]
Skvěle, dobrá zpráva  👍

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem přidělení urn:nbn STT svazku s chybou, bez chyby, opakovaně, totéž s vícedílným STT - chová se stejně, jako monografie a periodika, takže ok. S výjimkou nezobrazeného urn:nbn - viz zápis výše.

**Comment by ZdenkaSera** [comment]
Bude zapotřebí přetestovat, až půjdou načíst STT strany. Převod NDK stran na STT strany nefunguje, takže jsem zkoušela cice na STT titulu, ale s NDK stranami.

**Comment by ZdenkaSera** [comment]
Přidělení urn:nbn k STT je ok.  @albertoh nechávám tedy otevřené kvůli přidání hodnoty urn:nbn do tabulky, jak je popsáno výše. Děkuji.

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/207004673-a87c033d-e4be-42db-a4a1-8f3315901b19.png)

**Comment by ZdenkaSera** [comment]
@albertoh Díky, to vypadá dobře - otestuju.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem na Inovatice - v okně už je všechno,, podle mého je to ok, děkujeme! 
Osobně bych jen volila světlejší barvu pro podbarvení označeného záznamu. 
@luckajirku Prosím, jak to obsahem i formou vidíte Vy? Děkuji.

![image](https://user-images.githubusercontent.com/79305516/207286517-4659a257-7e01-4454-8e1c-412df832545b.png)

**Comment by pkudela** [comment]
@luckajirku ano, jak pises, tyto a podobne veci zatim neresme, jestli to chvili prezijete, pak doladime pri redesignu, ted resme spise funkcnost.

**Comment by pkudela** [comment]
Pripadne doresim ja jako tento konkretni dialog, nemusi nutne souviset s redesignem.

**Comment by ZdenkaSera** [comment]
@pkudela @luckajirku Děkuji oběma - tu barvu  bych tedy zatím neřešila, máme zásadnější věci :-) Navrhuji k uzavření.

**Comment by pkudela** [comment]
@ZdenkaSera ano, muze se uzavrit, ja na to drive nebo pozdeji pri dalsich zmenach stejne narazim a vyresim.

**Comment by pkudela** [comment]
hotovo, @luckajirku & @ZdenkaSera viz. screenshot, az bude nasazeno, oznacim k testovani
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/211055676-6b90b4af-c91c-4c38-a5fb-2d2c24724a00.png">

**Comment by pkudela** [comment]
Nasazeno na server, k testovani.

**Comment by ZdenkaSera** [comment]
@pkudela Původně jsem chtěla trošku protestovat, že ti smajlíci jsou až moc vylepšení, protože není dobře vidět, jak se tváří - ale barevné rozlišení je super, já jsem úplně spokojená. Děkuji 😊

**Comment by pkudela** [comment]
@ZdenkaSera dival jsem se do toho stareho rozhrani a oni ty smajlici s rovnou a usmevavou pusou take nebyly uplne poznat, proto jsem zvolil ikony a odlisil barevne. Barvy 3 stavu jsou opet definovane v poli v promennych, takze az se bude resit barevnost aplikace, lze to bez problemu jeste zmenit.

**Comment by luckajirku** [comment]
My bychom byli pro si s tím ještě pohrát:-), resp. to odlišit logičtěji: 
- zelený smajlík, ale se širokým úsměvem (jak se teď usmívá ten oranžový) - pro nově (bez problémů) přidělená urnnbn, která nemají chybovou hlášku
- oranžový smajlík s opatrným úsměvem - pro případy, kdy už bylo urnnbn přiděleno dříve
- červený zamračený tam, kde urnnbn přidělit nelze - to tam teď je, ale hlášku o chybě by to chtělo podbarvit červeně, ne zeleně jak je teď (tady by neměla být uklidňující hláška)

**Comment by ZdenkaSera** [comment]
@luckajirku No s tím musím souhlasit, ač bych spokojeně žila i se současným stavem :-)

**Comment by pkudela** [comment]
@luckajirku neni problem, upravim, jen poprosim, muzes mi poslat url nejakeho vyhledaneho dokumentu treba dle identifikatoru, kde budou vsechny 3 stavy? Abych to mohl otestovat.

**Comment by luckajirku** [comment]
@pkudela zkus tenhle ročník 8d30230a-f6a3-470b-bcb6-e314d99acc43, mělo by tam být 1 číslo s přiděleným urnnbn, 2 s nepřiděleným, a jedno bez skenů,

**Comment by pkudela** [comment]
hotovo, nasazeno, @luckajirku prosim zkontroluj, jestli je to pozadovane chovani

**Comment by luckajirku** [comment]
částečně:-). Ten zelený smajlík se širokým úsměvem by měl být u NOVĚ přiřazených urnnbn a ten oranžový u těch, co už urnnbn měly.

**Comment by pkudela** [comment]
@luckajirku tak zkus, nasazeno, snad jsem se uz trefil, mel jsem spatne prirazenou barvu v poli promennych.

**Comment by luckajirku** [comment]
jj, už to vypadá pěkně:-). ještě přemýšlím o tom podbarvení hlášky u urnnbn exists, jestli má být zelené, ale to je asi jedno. Smajlíci už jsou od pohledu jasní, jaký stav reprezentují, takže dobrý. 
Otestováno na NDK periodiku.

**Comment by pkudela** [comment]
@luckajirku ano, melo by to odpovidat asi barve smajlika, to neni problem, mam to prizpusobit?

**Comment by pkudela** [comment]
hotovo, nasazeno na serveru, prosim o test

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/16591052/211786088-1cdab3ef-6384-4167-b328-d95fcf1ce224.png">

**Comment by pkudela** [comment]
+ pripadne zavreni

**Comment by ZdenkaSera** [comment]
Díky - zkusila jsem zatím žluté a červené na STT vícedílné monografii, za mne ok. Ale jinak jsem se nedostala do metadat, nelze přepnout nastavení obrazovky - asi nějaký update, takže víc zkusím později.

**Comment by luckajirku** [comment]
barvičky už sedí, za nás OK

**Comment by nezbedova** [comment]
Moc hezké. Děkuji. za nás také OK.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
