### ISSUE TITLE
Hromadný výběr - nelze změnit index strany (import i vazby)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#219]
V hromadném výběru přestala fungovat změna indexu strany - jak v importu, tak ve vazbách.

**Comment by luckajirku** [comment]
A při použití tlačítka Reindexovat se to sice přečísluje, ale musím dát Obnovit, aby se ty změny i ukázaly.

**Comment by albertoh** [comment]
Opravil jsem nutnost "obnovit" pri reindexaci
V hromadnim vyberu nemuzu reprodukovat problem. Mne to funguje. @luckajirku muzete napsat na jakem objektu testujete?

**Comment by luckajirku** [comment]
Hm, teď už to taky nejsme schopni znovu vyvolat, asi měl PA v čase oběda slabou chvilku - ale dělalo nás to několik a chovalo se nám to stejně. Každopádně teď už OK.
A po reindexaci už není třeba obnovovat, takže OK, zavírám.
