### ISSUE TITLE
úložiště/hledat - vybraný model po uložení stran do objektu (#737)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#22]
Po uložení stran k objektu se automaticky přepne na úložiště/hledat na úvodní volbu - tedy pokud máme nahoře model NDK per., ukáží se periodika, i když jsme ukládali do monografie. Nebylo by možné, aby se nabídl právě použitý model?

Nevyřešilo by se to tou funkcí zapamatovat poslední vybraný model? #499

To bude asi jiný případ. Jestli to správně chápu, tam bylo třeba dát zapamatovat, čili defaultně mám periodika, dám zapamatovat monografie, hodí mě to pak po refreshi nebo novém přihlášení na monografie. Ale o to mi nejde. Jde mi o to, aby základní nabídka zůstala jak je, ale při ukládání do monografie, kdy to samo přehodí do úložiště, si to chytře našlo ten právě použitý model. A jinak v tom úložišti, pokud tam půjdu normální cestou, bude nastaven model defaultně.

**Comment by luckajirku** [comment]
Teď to funguje trochu jinak. Přepne se to po uložení stran přímo do toho objektu, kam se uložily strany. Což je asi nakonec lepší, než když nás to házelo do úložiště, jen by to sem bylo dobré napsat, že se to celé chová teď trochu jinak, čili ten problém, který se tu měl řešit, vlastně není.

**Comment by luckajirku** [comment]
...takže asi lze zavřít.
