### ISSUE TITLE
Formulář NDK monografie - 2x povinná signatura (test na Inovatice 30.6.)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#221]
Při vytvoření nového NDK svazku monografie vyžaduje systém signaturu 2x, druhý výskyt se mi nepodařilo smazat. Test. data - katalog KNAV, sysno = 002714840.

![image](https://user-images.githubusercontent.com/79305516/176633092-bb6c4792-2abc-4623-b69f-0ec03d09609b.png)

**Comment by ZdenkaSera** [comment]
Doplnění: Zkusila jsem i druhou signaturu vyplnit, aby nesvítila červeně - při uložení vyběhla chyba:

![image](https://user-images.githubusercontent.com/79305516/176634107-f93c270c-5227-4ad6-b61b-8bdc626c1416.png)

**Comment by luckajirku** [comment]
Tohle dělají ty záznamy s odkazem v 856, že to udělá další výskyt. Nám se to děje třeba u živých periodik s online verzí.

**Comment by luckajirku** [comment]
Ale mám za to, že to tak dělalo vždycky, že to není novinka tohohle klienta - jeden výskyt se vytvořil z 910 a druhý (nebo i víc) z 856.
