### ISSUE TITLE
Klient po hromadném přeindexování zobrazuje staré indexy

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc-client#223]
Dobrý den,

když dáme přeindexovat celý titul, nový klient dál zobrazuje původní indexy. Starý klient u toho samého titulu zobrazuje indexy změněné. Zkoušeli jsme refresh stránky i kompletní zavření a znovuotevření klienta a nepomohlo to.

**Comment by ZdenkaSera** [comment]
@svetlym Zkusila jsem u nás a chybu se mi nepovedlo nasimulovat, klient po reindexaci ukazuje nové hodnoty (test na monografii)

**Comment by svetlym** [comment]
Zjistili jsme, že problém se netýká jen přeindexování, ale prakticky jakýkoliv změny - nově přidaná kapitola se v novym klientovi neukazuje, ve starym ano. Po několika desítkách minut se ale změny v novym klientovi objeví.

Problém nastává i při práci z počítače ve vnitřní síti, takže proxynou to nebude.

**Comment by svetlym** [comment]
Dobrý den,

na poslední schůzce jsme se domlouvali, že to vyzkoušíme v testovacím Proarcu Inovatiky. Vyzkoušeno, tam nám to funguje. U nás ovšem problém přetrvává.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
