### ISSUE TITLE
Vyhledávač/filtr - nepamatuje si poslední hledanou/vyfiltrovanou položku

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#225]
Ve Správě dávek si např. vyfiltruju svoje načtené dávky, otevřu si jednu dávku a pak když se chci hned vrátit zpět, tak musím znovu filtrovat.

To stejné se děje i v Hledat. Např. si vyhledám objekt podle uuid, otevřu si ho a pak dám hned zpět a zase to uuid musím zadávat znovu.

**Comment by albertoh** [comment]
Opraveno

**Comment by erikamirova** [comment]
V MZK funguje, děkujeme. :)
