### ISSUE TITLE
Chybí identifikátor BCBT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#226]
V roletce s Identifikátory chybí možnost vybrat BCBT. V jádru je.
Prosím o doplnění. Děkuji

**Comment by albertoh** [comment]
Pridano

**Comment by ZdenkaSera** [comment]
Děkujeme, v STT je v BCBT v nabídce identifikátorů, Za mne ok (na Inovatice). @nezbedova Martino, případně koukni, díky.

**Comment by ZdenkaSera** [comment]
Doplnění - ověřeno i uložení BCBT do xml.

**Comment by nezbedova** [comment]
Je to doplněné. Souhlasím se zavřením.

**Comment by ZdenkaSera** [comment]
Děkuji, zavírám.
