### ISSUE TITLE
Editace čísel stran - chyba v přírůstku

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#227]
Pokud chci zadat stejná čísla (písmena) zadám Přírůstek 0. Stejně se udělá řada místo toho, aby došlo k opakování zadání čísla strany jako to je v poli Ukázka.

Dělá to v řadě i ve výběru.

V jádru to funguje jak má.

Prosím o opravu. Děkuji.

**Comment by albertoh** [comment]
@SykoraLukas podivas se?

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, podle mého je to na Inovatice ok, ale prosím o Tvé odsouhlasení. Děkuji.

**Comment by nezbedova** [comment]
Otestováno. Funguje. Děkuji.
