### ISSUE TITLE
Chyba filtrace ve správě dávek

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#228]
Vyfiltruju si všechny uložené dávky. Přejdu např. na list 101-120.
![image](https://user-images.githubusercontent.com/37616300/191006352-4e988c5c-4db9-4044-a02f-532c648ed1b0.png)

Poté se chci podívat na načtené dávky. Filtr nereaguje ani po kliknutí na Obnovit nebo ikonku filtru. Zastaví se totiž na listu 101-120 a jelikož mám méně načtených než uložených dávek, nevrátí se začátek na list 1-20 (viz screenshot). Musím tedy kliknout znovu na Správu dávek a filtrovat jakoby od začátku.
![image](https://user-images.githubusercontent.com/37616300/191006455-6c37b4b6-ff42-4381-b4d6-4195a375ba07.png)

**Comment by erikamirova** [comment]
@albertoh Nyní nejde přecházet mezi listy vůbec. Viz https://github.com/proarc/proarc-client/issues/244.

**Comment by albertoh** [comment]
Opraveno

**Comment by erikamirova** [comment]
V testovacím PA to funguje, ale v MZK nemáme ještě nasazeno. @SykoraLukas

**Comment by erikamirova** [comment]
Tak pan Kudela nám to už nasadil a vše je ok. :)
