### ISSUE TITLE
Úpravy ve formulářích ePeriodik

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#230]
Při testování nového klienta jsme narazili na následující problémy ve formulářích pro ePeriodika:   
(testováno na Inovatice, 22.9.2022):

### NDK ePeriodikum
- Název, typ - nemá být možné vybrat "Zkrácený název"
- Autor - nelze vyplnit `<etal>`
- Autor - nelze vyplnit  `<affiliation>`
- Autor - role je MA, má být RA
- Žánr - vyplňuje se `electronic title`, ale má to být `electronic_title`
- Uložení - nelze vyplnit `<physicalLocation>` (MA) a `<shelfLocator>` (MA)
- Chybí pole pro poznámku
- Chybí pole pro abstrakt
- Chybí pole pro `<relatedItem>`

### NDK eRočník
- Název, číslo části je MA - má být M
- Autor - nelze vyplnit `<etal>`
- Autor - nelze vyplnit  `<affiliation>`
- Autor - role je MA, má být R
- Chybí pole pro poznámku
- Žánr - vyplňuje se `electronic volume`, ale má to být `electronic_volume`

### NDK eČíslo
- Název (titleInfo) nelze vyplnit `"type"`
- Název, část vynechaná při hledání je O - má být R
- Název, podnázev je O, má být R
- Název, Jméno části je O - má být R
- Autor - nelze vyplnit `<etal>`
- Autor - nelze vyplnit  `<affiliation>`
- Žánr - vyplňuje se `electronic issue`, ale má to být `electronic_issue`
- Chybí pole pro poznámku
- Chybí pole pro abstrakt
- Fyzický popis, poznámka je RA - má být O
- Zdroje digitálního dokumentu - automaticky by se mělo vyplňovat "born digital"
- Klasifikace - Autorita je M - má být MA
- Klasifikace - Hodnota - je M, má být MA
- Uložení - nelze vyplnit `<physicalLocation>` (MA) a `<shelfLocator>` (MA)

### NDK eČlánky
- Název, typ - nemá obsahovat možnost "zkrácený název"
- Název, část vynechaná při hledání - je O, má být R
- Údaje o autorech, Identifikátor autora - je MA, má být RA
- Údaje o autorech - nelze vyplnit `<etal>` (má být O)
- Chybí pole pro vyplnění poznámky (note) - (má být O)
- Chybí pole pro vyplnění abstraktu (abstract) - (má být RA)
- Žánr - nelze vyplnit peer-review - šlo by udělat stejné přepínání jako u eČlánků?
- Fyzický popis, forma - je R, má být RA
- Fyzický popis, forma - nyní chybně Ra (malé A), předvyplněná hodnota by měla být „electronic“
- Klasifikace je RA - má být R
- chybí část Recenze na (relatedItem) (má být O)
- Informace o části - jsou O, mají být MA

----

Zároveň se mi bohužel nepovedlo vytvořit NDK PSP - to jsem testoval na našem serveru (Verze 3.8.2 Build 20220703203944), hlásí to nějaký problém s PDF: 
[proarc_export_status.log](https://github.com/proarc/proarc-client/files/9624398/proarc_export_status.log)

**Comment by SykoraLukas** [comment]
Aktualizováno podle https://old.ndk.cz/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf

27. listopadu 2020 Dokument verze 1.0

**Comment by kerschfilip** [comment]
testováni na inovatika.dev 11.11.2022:

**NDK ePeriodikum**
- [ ] Číslo části je MA, má být RA
- [ ] Autor - etal - překlad je nyní "Více autorů etal"
- [ ] Autor - role je MA, má být RA
- [ ] Fyzický popis - form - předvyplněná hodnota by měla být „electronic“, ne "print"
- [ ] Uložení - url - je O, má být MA
- [ ] Uložení - url - Užití - je O, má být R
- [ ] Uložení - url - Poznámka - je O, má být R
- [ ] Uložení - url - po vyplnění adresy, nelze uložit
- [ ] Identifikátor záznamu je R, má být M
- [ ] Poznámka je O, má být RA
- [ ] Věcné třídění - Klíčové/Předmětové heslo je R, má být O
- [ ] Věcné třídění - Geografické věcné třídění je R, má být O
- [ ] Informace o souvisejících dokumentech nyní MA, mý být O

**NDK eRočník**
- [ ] Autor - Celé jméno (namePart) je nyní R, má být M
- [ ] Autor - Identifikátor autora (nameIdentifier) je nyní MA, má být RA
- [ ] Autor - etal - překlad je nyní "Více autorů etal"
- [ ] Poznámka - Hodnota je nyní RA, myslím, že by mělo být O jako celý element
- [ ] Původ předlohy - Datum vydání - Hodnota je nyní MA, myslím, že by mělo být M jako celý element
- [ ] Původ předlohy - Datum vydání - Point je nyní M, má být MA
- [ ] Identifikátory - Platný/Neplatný je nyní MA, má být M

**NDK eČíslo**
- [ ] Autor - Typ je nyní M, má být MA
- [ ] Autor - Celé jméno (namePart) je nyní R, má být MA
- [ ] Autor - Identifikátor autora (nameIdentifier) je nyní MA, má být RA
- [ ] Autor - etal - překlad je nyní "Více autorů etal"
- [ ] Poznámka - Hodnota je nyní RA, myslím, že by mělo být O jako celý element
- [ ] Původ předlohy - Datum vytvoření - nemá tam vůbec být
- [ ] Fyzický popis je R, má být O
- [ ] Fyzický popis - Zdroje digitálního dokumentu - automaticky by se mělo vyplňovat "born digital"
- [ ] Abstrakt - Hodnota je R, myslím, že by mělo být RA jako celý element
- [ ] Věcné třídění - Klíčové/Předmětové heslo je R, má být O
- [ ] Věcné třídění - Geografické věcné třídění je R, má být O
- [ ] Klasifikace - Hodnota - je MA, má být R
- [ ] Identifikátory - Platný/Neplatný je nyní MA, má být M

**Comment by kerschfilip** [comment]
**NDK eČlánky**

* [ ] Autor - Celé jméno (NamePart) je nyní MA, má být M
* [ ] Autor - etal - překlad je nyní "Více autorů etal"
* [ ] Autor - chybí poznámka (O), v praxi asi nepoužívá, ale...
* [ ] Žánr - prosím rozlišení recenzovaný/nerecenzovaný vyřešit stejným přepínačem, jako jsme se dohodli u eČlánků [tady](https://github.com/proarc/proarc-client/issues/149#issuecomment-1162777835)
* [ ] Jazyk - není kam zapsat "objectPart" - resp. o jakou konkrétní část se jedná (např. "summary", "table of contents" apod.)
* [ ] Jazyk - Jazyk (languageTerm) - celý element je správně R, ale "hodnota" M, ale myslím, že by mělo být R jako celý element
* [ ] Fyzický popis - Zdroje digitálního dokumentu je M, má být MA
* [ ] Fyzický popis - Zdroje digitálního dokumentu - automaticky by se mělo/mohlo :) vyplňovat "born digital" (je to v nabídce, ale zpracovatel musí vybrat - zbytečně kliknutí navíc)
* [ ] Fyzický popis - Forma - předvyplněná hodnota by měla být „electronic“
* [ ] Fyzický popis - Forma - chybí poznámka - kdybychom náhodou měli dosken, měla by zde být možnost, kam tuto informaci napsat
* [ ] Abstrakt - Hodnota je nyní R, ale myslím, že by měla být RA jako celý element
* [ ] Klasifikace - Vydání nyní M, má být MA
* [ ] Identifikátory - Platný/Neplatný je nyní MA, má být M
* [ ] Recenze na (relatedItem), ale nyní je MA a má být O

**Comment by SykoraLukas** [comment]
NDK eČlánky: Autor - chybí poznámka (O), v praxi asi nepoužívá, ale... tohle pole jsem nenašel ani ve standardu ani v možnostech MODSu.

**Comment by kerschfilip** [comment]
> NDK eČlánky: Autor - chybí poznámka (O), v praxi asi nepoužívá, ale... tohle pole jsem nenašel ani ve standardu ani v možnostech MODSu.

je to tak, omlouvám se, poznámka patří na stejnou úroveň jako element `name` a tam správně je.

Ještě jsme ale koukali na část **Fyzický popis u NDK eČlánku**, která odpovídá standardu pro elektronická periodika a ne pro skládaná periodika. Teď je tam tahle možnost výběru hodnot ”marcform”, ”marccategory”, ”marcsmd” a ”gmd”:
![image](https://user-images.githubusercontent.com/57805328/224748846-f4fb97b6-2faf-473a-9829-865fd12f2bf6.png)
...jenže ty se ve standardu pro skládaná periodika vyskytují jen na úrovni titulu, u jednotlivých článků má být jen možnost vyplnit : 

- Poznámku `<note>`, možnosti: `-` (nic) /`dosken` --> předvyplněná hodnota by měla být  `-`
- údaje o fyzické podobě `<form>`, možnosti: `electronic`/`dosken` --> předvyplněná hodnota by měla být `electronic`
- Indikátor zdroje digitálního dokumentu `<digitalOrigin>`, možnosti: `born digital`/`-` --> předvyplněná hodnota by měla být `born_digital`

Ideální by byl výběr z roletek, pokud by to šlo:
![image](https://user-images.githubusercontent.com/57805328/224751193-84cd5ff3-46df-4dbb-83d7-0b00b3eaa252.png)

**Comment by SykoraLukas** [comment]
Opraveno, i nasazeno.

**Comment by kerschfilip** [comment]
Testováno ve verze `v2.0.2` (28.03.2023)Jádro: verze `4.0.2` - build `20230326105845`. Vypadá to skvěle! Moc díky. Žádných dalších problémů s NDK ePeriodiky už jsme si nevšimli, takže issue zavírám.
