### ISSUE TITLE
Integrace prohlížeček dokumentů z Krameria do ProArcu (VISK 2022)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#232]
Issue k popisu realizace části bodu 3) z dokumentu [Rozvoj ProArcu (VISK)](https://docs.google.com/document/d/1qZSoyGb9MBoAFnYDmumTKs-mDAU96cE3joOxgAv4i3g/edit#)

**Comment by kerschfilip** [comment]
Současná prohlížečka PDF se v aktuálním klientovi (v2.0.1 (09.01.2023)) nějak rozbila a nejde roztáhnout na celou výšku obrazovky: 
![image](https://user-images.githubusercontent.com/57805328/211339209-06ea7e92-a245-453c-92cd-3894903c781c.png)

**Comment by pkudela** [comment]
@kerschfilip prosim poslete mi konkretni url, at to nemusim hledat, dekuji

**Comment by kerschfilip** [comment]
@pkudela třeba tady: https://proarc.inovatika.dev/repository/uuid:a225d7a4-b297-4298-b8f8-fe3b351ba336

**Comment by pkudela** [comment]
opraveno, nasazeno na server k testovani

<img width="827" alt="image" src="https://user-images.githubusercontent.com/16591052/211500771-297fd494-7c92-4abc-bdce-465132dfb6db.png">

**Comment by ZdenkaSera** [comment]
@kerschfilip Prosím, koukni na to a případně zavři. Podle mého to vypadá ok. Díky

**Comment by kerschfilip** [comment]
Vypadá to OK, ale chová se to bohužel trochu divně. Vrátil se zpátky problém, který už jsme jednou, myslím, řešili. Panel se dá roztáhnout do šířky směrem od PDF k ostatním panelům, ale zmenšit ho zpět nejde - respektive musí se myší najet až do modrého záhlaví, aby to šlo.
[screen-capture (3).webm](https://user-images.githubusercontent.com/57805328/215780470-31d46f1a-5442-48aa-8bc2-2590bc1e841c.webm)

Ukázalo se taky, že kolegyně ze zpracování časopisů pracují poměrně často ve starém klientovi (jádře) s možností zobrazit PDF jako "Ikonu", kdy se místo celého PDF zobrazuje datastream=THUMBNAIL. Šlo by tam tohle, prosím, přidat? 
![image](https://user-images.githubusercontent.com/57805328/215781656-ab853f12-dd64-453c-8da3-dab63b951a60.png)

----

Druhá věc je potom projektový úkol integrace prohlížeček z Krameria - v současnosti je v klientovi použitá prohlížečka, která je vlastní browseru, který uživatel používá. Je to tak hodně podobná prohlížečka, která byla v klientovi už dřív (srovnejte se screenshotem v #66). Trochu jsem myslel, že by se pro PDF dalo integrovat něco takového, jako je třeba tady: https://kramerius.lib.cas.cz/view/uuid:b2697744-7d58-4c6a-96cc-5c1eb8f0fba7

Taky se mi nepodařilo načíst v současné prohlížečce epub

**Comment by pkudela** [comment]
@albertoh zkusel jsem s tim soupat a ten panel PDF - s tim se soupe spatne, spatne reaguje se mi zda, kdyz pdf panel vypnu, tak uz je to v pohode, neni to nahodou zalezitost generovani toho pdf?

**Comment by albertoh** [comment]
Pridal jsem novy typ panelu "media", ktery umi pracovat s digitalnim obsahem ruznych typu.

![image](https://user-images.githubusercontent.com/5946836/220634208-fa262639-76ff-4f74-83c6-a102d2fa7f72.png)

Zobrazuje novou prihlizecku pdf

![image](https://user-images.githubusercontent.com/5946836/220634701-d3cd46c4-efcb-419b-88dc-ee49c0b47adb.png)

Lze vybrat mezi formaty existujici v proarcu pro dany objekt (za predpokladu, ze prohlizec zobrazit)

![image](https://user-images.githubusercontent.com/5946836/220634063-ba394b00-0080-485f-a25e-db3dd244087f.png)

**Comment by kerschfilip** [comment]
Čtečka PDF vypadá dobře, díky!  
Epub to ale asi zatím neumí, předpokládám. Nebo se mi ho tam aspoň nepodařilo procpat :-)

Panel Media je taky fajn, ale u těch e-born věcí nefunguje úplně dobře:

- pokud nemám u eMonografie nebo eČlánku už PDF přidané, tak přes panel Media ho přidat nejde - chybí tam tlačítko `+`
- ještě bychom potřebovali tu možnost zobrazit PDF jako "Ikonu", kdy se místo celého PDF zobrazuje datastream=THUMBNAIL. Teď jde vybrat jen `Originál`

**Comment by albertoh** [comment]
Kde muzu testovat e-pub? Mame nejaky objekt?

Pridam + pro nahrani digitalni objekt

Lze vybrat datastreamy, ktere existujou v uloziste. Ta rolekta ukazuje seznam datastreamu, ktery jadro vraci. Pokud mate nejaky objekt, ktery ma THUMBNAIL, to by melo byt v nabidce

**Comment by albertoh** [comment]
- E-pub pridano
 - Pridana moznost nahrat digitalni obsah

**Comment by kerschfilip** [comment]
Epub funguje - díky! Bylo by možné ještě nějak doplnit možnost přecházet mezi stránkami pomocí šipek? U PDF mi to jde, u epubu ne.

Pořád mi blbne to roztahování a zužování panelu s pdf nebo epub, jak jsem psal výše. 

S těmi datastreamy to chápu, dává to smysl, ale my máme v ProArcu, kde s eborny pracujeme, u těch PDF možnost vidět Ikonu - viz screenshot nahoře. Kde se teda ten datastream pro ni vzal a proč v současné verzi není?

**Comment by albertoh** [comment]
Jake to jsou objekty? Napis, prosim uuid (pdf, a epub)

**Comment by kerschfilip** [comment]
epub jsem nahrál k uuid:3b7095bb-9116-4a53-9cfd-002f25d283bf

Příklad toho datastreamu s ikonou jsem na Inovatice nenašel a nepovedlo se mi ho při nahrání PDF vytvořit. Na našem produkčním PA, ale jsou. Máme tam nasazenou verzi 3.8-DEV-BETA

**Comment by albertoh** [comment]
Sipky pro strankovani e-pub jsou vpravo. Tam je mozne videt seznam kapitol, a prejit na ne.

![image](https://user-images.githubusercontent.com/5946836/222439203-bc1633f8-beae-4ac5-b1ee-dffd38520e81.png)

Opravil jsem automaticka velikost pri roztahovani panelu.

**Comment by kerschfilip** [comment]
pardon, myslel jsem šipky na klávesnici, že mi nefungují u epubu, zatímco u pdf ano.

**Comment by albertoh** [comment]
Pridano

**Comment by kerschfilip** [comment]
> Pridano

Prohlížečku v současné podobě považujeme za dostatečnou. Plánuje se tam ještě nějaký vývoj?

----

> Příklad toho datastreamu s ikonou jsem na Inovatice nenašel a nepovedlo se mi ho při nahrání PDF vytvořit. Na našem produkčním PA, ale jsou. Máme tam nasazenou verzi 3.8-DEV-BETA

Na našem testu funguje "Ikona" i na verzi 4.0.1. Nerozumím ale tomu, kde se bere a proč na Inovatice není - je to nějakou konfigurací? Dalo by se to prosím zdokumentovat? @SykoraLukas 

----

Jako trochu zbytečné se mi teď jeví ikona PDF v panelu "Popisná metadata" - nebylo by nejlepší ji odstranit? @albertoh 
![image](https://user-images.githubusercontent.com/57805328/225064450-21e27c2f-511c-4f06-a680-a77ce8e9a28e.png)

**Comment by SykoraLukas** [comment]
Prosím o screen jak vypadá ikona a případně ikony jiných datastreamu

**Comment by ZdenkaSera** [comment]
K dokončení - smazat ikonu

**Comment by albertoh** [comment]
Odstraneno

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
