### ISSUE TITLE
označování left/right/single page + reprezentativní strany u STT stran

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#233]
Potřebovali bychom zavést podporu pro označování left/right/single page u STT stran. Plus označování reprezentativní strany. U NDK stran to již funguje.

**Comment by SykoraLukas** [comment]
<img width="310" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/b99d2171-f2a4-4680-b500-e4c08b13f105">

**Comment by ZdenkaSera** [comment]
@SykoraLukas Stydím se a děkuji 😊 takže ok i v klientovi. Díky

**Comment by ZdenkaSera** [comment]
@ZdenkaSera v Knav dotestovat včetně zobrazení v K7

**Comment by ZdenkaSera** [comment]
U označení pozice strany je roletka vlevo/vpravo/samostatně - to je ok, ale pokud hodnotu zadám omylem, můžu ji vymazat jedině v xml. Asi to ničemu nevadí, ale s K7 otestovat zobrazení, pokud označím jen některé strany, případně označím chybně. Platí nejen pro STT.

**Comment by ZdenkaSera** [comment]
Jinak značení včetně repre strany ve verzi v4.1.1./2.2.1 nasazené lokálně funkční.

**Comment by ZdenkaSera** [comment]
@erikamirova Navrhuji zatím uzavřít a nečekat, až bude s importovanými označeními umět pracovat Kramerius. Pokud se pak najde chyba, znovu otevřeme. Souhlasíte?

**Comment by erikamirova** [comment]
@ZdenkaSera Určitě, můžeme to zavřít.
