### ISSUE TITLE
mazání většího počtu stran v editoru připojených objektů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc-client#235]
```
Při mazání v editoru připojených objektů nelze smazat najednou větší 
počet stran. Asi od 150 označených stran hlásí Transport error - HTTP 
code: 414 ...
```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 5 Mar 2015 at 1:29

**Comment by ZdenkaSera** [comment]
Protože se neobjevil žádný komentář v souvislosti s přiřazením štítku "k realizaci", odebírám štítek "návrh na rozšíření".

**Comment by albertoh** [comment]
@SykoraLukas Problem je delka url string. Ted to posilam jako method "delete"
 Muzu to zmenit na post.
 Pro uloziste volam:
   `api/object?purge=${purge}&hierarchy=true&${query}`
Pro import:
   `api/import/batch/item?batchId=${batchId}&${query}`

**Comment by SykoraLukas** [comment]
@albertoh mužes to upravit na posilani JSONu?

```
DELETE http://localhost:8081/proarc/rest/v1/object
Content-Type: application/json

{"pid":["uuid:83702174-8d13-496c-b6e7-b435c0ae0a12"],"hierarchy":true, "purge":true, "restore":false}

###

DELETE http://localhost:8081/proarc/rest/v1/import/batch/item
Content-Type: application/json

{"pid":["uuid:83702174-8d13-496c-b6e7-b435c0ae0a12"],"batchId":"135"}

```

**Comment by albertoh** [comment]
Upraveno

**Comment by ZdenkaSera** [comment]
na inovatice jsem zkusila smazat cca 200 skenů z monografie, vše ok, díky. V KNAV bez dalšího testu, budeme sledovat chování v našem testu a produkci. Zatím navrhuji k zavření, případné  další testy na ostatních knihovnách :-)

**Comment by ZdenkaSera** [comment]
Zatím zavírám.
