### ISSUE TITLE
Rozložení obrazovky (pokračování issue 111)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#238]
Z issue [111](https://github.com/proarc/proarc-client/issues/111)  přebírám body, které jsou k realizaci:

**1. Zrušení režimu detailu**
**2. Rozložení obrazovky, sloupce.**

O upřesnění prosím zkušené uživatele ve spolupráci s vývojáři. Děkuji.

**Comment by ZdenkaSera** [comment]
Na prioritě tohoto issue jsme se shodli na schůzce 5.10.2022 - jak z pohledu uživatelů, tak z pohledu vývojáře (návaznost dalších změn  klienta na tuto zásadní úpravu).

**Comment by albertoh** [comment]
Je k testovani nova verze rozlozeni.
Nakonec jsem pristoupil k moznosti vlastniho nastaveni, pro uloziste a import zvlast. Nastaveni se uklada v prohlizeci.
Muzete to zkouset pomoci noveho tlacitka

Pro uloziste:
![image](https://user-images.githubusercontent.com/5946836/198281422-2e248434-012d-4e27-ac70-0d0bb66962ac.png)
![image](https://user-images.githubusercontent.com/5946836/198281633-9c567219-7ffc-4e19-961b-6be6ba3a6e42.png)

Pro import (#241):
![image](https://user-images.githubusercontent.com/5946836/198281804-ebcd7be1-23ff-40a5-afe0-39fdc48474b3.png)
![image](https://user-images.githubusercontent.com/5946836/198281918-512696d7-ef08-4bf2-8ff2-6917fbe38d96.png)

Musel jsem menit kod hluboko... Mozna se najdou chyby chovani, ikdyz jsem se snazil vsechno zkontroloval.

**Comment by pkudela** [comment]
Jen doplnim Alberta, pokud se nenactou preklady, tak je nutne provest tvrdy reload prohlizece.

**Comment by luckajirku** [comment]
Tak tohle je ale moc pěkný dárek k zítřejšímu státnímu svátku:-). A asi jediné řešení, aby byli všichni spokojení, když se ani mezi knihovnami nemůžeme dohodnout, jaké rozložení je nejlepší. Víc budeme testovat příští týden, ale na první proklikání super!!!

**Comment by pkudela** [comment]
@luckajirku pokud budes chtit, tak prosim dodej texty pro napovedu, psal jsem to z patra, nevim, jestli bude vyhovovat + nazvy jednotlivych panelu, bral jsem to dle popisku tlacitek, jak me naved @albertoh

**Comment by nezbedova** [comment]
Nevydržela jsem a rychle to proklikala. Je to skvělé!

**Comment by luckajirku** [comment]
Když si něco nastavím přes tu funkci Rozložení, je to OK, drží to. Ale pokud si pak šířku/výšku nastavím pak už podle těch konkrétních náhledů apod., tak se mi to po provedení jakékoli akce zase vrátí k tomu rozložení nastavenému přes Rozložení. 
Není to dobré - jako je super, že si v tom Rozložení můžu nastavit rámcově, co kde chci mít, ale potom jak přesně široké a vysoké má které okno být, to je potřeba ladit už s těmi konkrétními objekty...

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
@albertoh omlouvám se, ale nějak tam nikde nevidím možnost přidat PDF u eČlánku a NDK eČlánku, můžu poprosit o návod? Nebo doplnění, pokud to chybí. Díky.

**Comment by luckajirku** [comment]
nad každým tím panelem se nám objevil šedý pruh (jak v úložišti, tak v importu), který pak ubírá místo. 
![sedepruhy](https://user-images.githubusercontent.com/6359479/201050883-623dae6c-e370-4a34-b701-e48f0b41da2b.png)

**Comment by luckajirku** [comment]
U editace popisných metadat JEDNÉ strany chybí posuvník (jak v importu, tak ve vazbách), u hromadné editace se objeví, stejně tak na jiných úrovních je. I vzhledem k tomu, jak vysoké jsou řádky a moc se toho tam nevejde, je potřeba se v tom formuláři posouvat. 
![posuvník](https://user-images.githubusercontent.com/6359479/201055366-afbbe30d-e221-4dd3-bf18-52bd40380e24.png)

**Comment by albertoh** [comment]
@pkudela Kouknina to. To jsou vsechno css

**Comment by luckajirku** [comment]
ještě doplním k těm šedým pruhům - ty se dělají, pokud je nad tím: tabulka, mřížka, náhledy, komentář. 
A když je nahoře tohle, tak je to OK, pruhy nejsou: popisná metadata, mods xml, ATM, scan/OCR

**Comment by luckajirku** [comment]
Jsem v periodiku, mám založené ročníky, čísla, ale nemám tam nahrané strany. V liště v panelu mám možnosti zobrazení jen tabulka a mřížka, ale protože přes Rozložení jsem si předtím nastavila do toho panelu Náhledy, zobrazují se takové pseudonáhledy. Což je divné, navíc ikonka pro náhledy tam není (ta se ukazuje jen pokud tam jsou skeny). A pak když si tam přepnu do řádkového zobrazení a pak dám Obnovit, vrátí se zase zpět to nastavení pro náhledy.

**Comment by luckajirku** [comment]
Přemýšlím ještě o těch panelech. Jestli třeba tabulka má být typ panelu, když je to spíš jen typ zobrazení objektů/vazeb a panel (s tlačítky na liště) je stejný jako u mřížky nebo náhledů... Stejně tak třeba metadata - formulář a xml...
Přišlo by mi asi lepší to přes Rozložení nastavit hlavně rámcově - CO tam je - a pak JAK to chci vidět už podle potřeby přepínat spíš v panelu (i když by ta možnost mohla být i v tom Rozložení). 
Hlavně by ale přednost měla mít poslední provedená změna, ať už změna nastavení proběhla v panelu, nebo přes Rozložení.

**Comment by erikamirova** [comment]
Tak už máme toto rozložení nasazeno i v MZK a máme k tomu několik připomínek. Na první pohled je to super, ale je potřeba hodně věcí doladit. Mám pocit, že po tomto nasazení nefunguje hodně věcí, které předtím fungovaly. :( 

1. Nefunguje označení více skenů pomocí ctrl+shift.
2. Označím si např. 10 skenů, u kterých potřebuji označit foliaci (tzn. zvolím číslování u každé druhé strany). Jakmile uložím změnu (disketou), zruší se označení 10 skenů a musím je označovat znovu.
3. Občas se stává, že když změním číslo strany a uložím změnu enterem, dostanu se do jiného objektu. Ale nevypozorovali jsme, kdy a u jakých objektů/modelů se to děje. Někdy zůstaneme ve stejném objektu, jindy nás to přehodí do jiného objektu. Kolegyni to dokonce na chvíli hodilo do jiného objektu a pak ji to vrátilo zpět do původního. :D Pokud to uložím disketkou, je to ok.
4. V „Tabulce“ chybí u úložiště u náhledů, mřížky a tabulky typy stran. 
5. V „Tabulce“ chybí u importu u náhledů a tabulky typy stran. Mohlo by to vypadat třeba takto:
![image](https://user-images.githubusercontent.com/37616300/201881105-28b5b0c6-e6af-4ad4-8a22-25ef1541ebc1.png)
6. Naše nastavení Rozložení v úložišti i importu vypadá takto. 
![image](https://user-images.githubusercontent.com/37616300/201877139-36279cde-a5ed-4067-b0e9-b26d2cd13590.png)

**Comment by pkudela** [comment]
Na posledni schuzce se nekdo zminil, ze pri mensim rozliseni zmizi cast nastaveni layoutu a musi se horizontalne scrollovat, toto jsem jiz opravil viz. screenshot, tato oprava bude dostupna v nasledujicim buildu.
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/16591052/203016497-ed5c71ef-cb31-4afa-85f5-40d38981717d.png">

**Comment by albertoh** [comment]
jj, pocitame s tim. @pkudela chce jeste neco dotahnout... Odpoledne vydam draft, abyste si mohli instalovat soucasny stav

**Comment by ZdenkaSera** [comment]
Moc díky!

**Comment by nezbedova** [comment]
@pkudela @albertoh Na schůzce jsem zmiňovala mizení části vyskakovacího okna.

V okně cca 17 palců vidím toto:

![obrazek](https://user-images.githubusercontent.com/13831946/203023606-1110b2d2-dc65-4cc9-b089-e1f4d86ba88d.png)

Obsah vyskakovacího okna se nezmenší. 
Řešilo se to u vyskakovacího okna, ve kterém se vybírá nadřazený objekt, ke kterému chci přidat skeny.

Není nutné to opravit hned. Stačí to zahrnout do nějaké další verze.

Děkuji

**Comment by pkudela** [comment]
@nezbedova z Vaseho sceenshotu je patrne, ze se od vyskakovaciho okna / dialogu nevejdou ani zeleno/cervene nahledy, tak ani rozlozeni po tim, to jste mela na mysli, je to tak? Pokud ano, tak toto je opraveno, viz. muj screenshot odeslany pred tim.

**Comment by nezbedova** [comment]
@pkudela Ale já to vidím tak, jak to je v náhledu ode mě. Zkusila jsem  se odhlásit a znovu přihlásit  a stále mi tam kousek na pravé straně chybí. Test anonymní okno Chrom. 

![obrazek](https://user-images.githubusercontent.com/13831946/203058581-3a7f4ff0-9474-4e17-8a12-42c465eff454.png)

**Comment by pkudela** [comment]
@nezbedova aha, tak ted uz je mi to jasne, vyse jsem psal: "tato oprava bude dostupna v nasledujicim buildu." - cili jeste to neni nasazene na nasem vyvojovem serveru.

**Comment by pkudela** [comment]
@nezbedova nasadime behem dneska nekdy odpoledne, napisi to sem

**Comment by nezbedova** [comment]
@pkudela Děkuji. Těším se.

**Comment by pkudela** [comment]
Nektere upravy jsou slozitejsi, nez jsme prepokladali, nasadime behem zitra dopoledne, dam sem vedet. Diky za pochopeni.

**Comment by pkudela** [comment]
@nezbedova jak bylo zmineno na schuzce, ten dialog uz je opraveny a k testovani na https://proarc.inovatika.dev/, porovnavat s puvodni verzi, kde jeste nebylo sahnuto do layoutu ani do designu muzete na teto domene -> https://proarc-old.inovatika.dev/ - tuto adresu asi jeste pani @ZdenkaSera rozesle

**Comment by kerschfilip** [comment]
@pkudela @albertoh zkoušel jsem nastavení rozložení s PDF (ečlánky, emonografie) a docela mi zlobí posuvník pro nastavení velikosti bloku - když ho chytím a chci okno zmenšit tak, že myší najedu do bloku s PDF, tak posuvník nijak nereaguje, je potřeba vyjet myší až na úroveň nad PDF a teprve potom jde blok tažením myši zmenšit. Nevím, jak lépe to popsat, tak jsem vám to natočil, snad to bude pochopitelné :-)

https://user-images.githubusercontent.com/57805328/203572477-54fbf4cf-6b6e-496a-8147-96b451319d01.mp4

**Comment by nezbedova** [comment]
@pkudela Ve vyskakovacím okně je vidět vše, i když je to okno malé. Děkuji.

**Comment by albertoh** [comment]
> Jsem v periodiku, mám založené ročníky, čísla, ale nemám tam nahrané strany. V liště v panelu mám možnosti zobrazení jen tabulka a mřížka, ale protože přes Rozložení jsem si předtím nastavila do toho panelu Náhledy, zobrazují se takové pseudonáhledy. Což je divné, navíc ikonka pro náhledy tam není (ta se ukazuje jen pokud tam jsou skeny). A pak když si tam přepnu do řádkového zobrazení a pak dám Obnovit, vrátí se zase zpět to nastavení pro náhledy.

Jake chovani ma byt spravne?
  a. - pokud nejsou nahledy stran , nezobrazovat panel
  b. - zobrazit panel v modu "mrizka" nebo "tabulka", schovat ikonku pro nahledy
  c. -  zobrazit "pseudonahledy" a ikonku

Podle mne, pri obnoveni panel by se mel chovat podle nastaveni v "Rozlozeni", ale taky muzu to zmenit, a automaticky ulozit ho pri zmene pres ikonku

**Comment by albertoh** [comment]
> Přemýšlím ještě o těch panelech. Jestli třeba tabulka má být typ panelu, když je to spíš jen typ zobrazení objektů/vazeb a panel (s tlačítky na liště) je stejný jako u mřížky nebo náhledů... Stejně tak třeba metadata - formulář a xml... Přišlo by mi asi lepší to přes Rozložení nastavit hlavně rámcově - CO tam je - a pak JAK to chci vidět už podle potřeby přepínat spíš v panelu (i když by ta možnost mohla být i v tom Rozložení). Hlavně by ale přednost měla mít poslední provedená změna, ať už změna nastavení proběhla v panelu, nebo přes Rozložení.

 V predchozim komentari jsem napsal, ze podle mne panel by se mel chovat podle Rozlozeni...
  To jsem tak navrhl, aby se dalo snadne nastavovat vychozi rozlozeni, a zaroven mit moznost videt vazby jako tabulka a nahledy.
 Tady, samozrejme, nejvhodnejsi varianta by byla, kdyby se mi podarilo rychle udela panel "Structura" :)

Prosim, napiste jak to vidite

**Comment by albertoh** [comment]
> Tak už máme toto rozložení nasazeno i v MZK a máme k tomu několik připomínek. Na první pohled je to super, ale je potřeba hodně věcí doladit. Mám pocit, že po tomto nasazení nefunguje hodně věcí, které předtím fungovaly. :(
> 
> Nefunguje označení více skenů pomocí ctrl+shift.
 
  Opraveno (problem videl v Importu, v ulozisti chovalo se spravne)


> Označím si např. 10 skenů, u kterých potřebuji označit foliaci (tzn. zvolím číslování u každé druhé strany). Jakmile uložím změnu (disketou), zruší se označení 10 skenů a musím je označovat znovu.

  Opraveno (problem videl v Importu, v ulozisti chovalo se spravne)
> Občas se stává, že když změním číslo strany a uložím změnu enterem, dostanu se do jiného objektu. Ale nevypozorovali jsme, kdy a u jakých objektů/modelů se to děje. Někdy zůstaneme ve stejném objektu, jindy nás to přehodí do jiného objektu. Kolegyni to dokonce na chvíli hodilo do jiného objektu a pak ji to vrátilo zpět do původního. :D Pokud to uložím disketkou, je to ok.
> V „Tabulce“ chybí u úložiště u náhledů, mřížky a tabulky typy stran.
> V „Tabulce“ chybí u importu u náhledů a tabulky typy stran. Mohlo by to vypadat třeba takto:

**Comment by luckajirku** [comment]
> > V „Tabulce“ chybí u úložiště u náhledů, mřížky a tabulky typy stran.
> 
> Typy stran jsou videt pokud nemame zvoleno "Zobrazovat zkrácené popisky"
> 
> > V „Tabulce“ chybí u importu u náhledů a tabulky typy stran. Mohlo by to vypadat třeba takto:
> 
> Opraveno podle screenshotu

V importu to v tabulce nevidím, jen v mřížce a u náhledů. Tam se to tedy dodělá až s těmi sloupci viz https://github.com/proarc/proarc-client/issues/84?
V úložišti to je i v tabulce, ale součástí názvu (opět - v samostatném sloupci to bude až s řešením https://github.com/proarc/proarc-client/issues/84?).

**Comment by albertoh** [comment]
Ja bych to tak delal, sloupec az bude #84

**Comment by luckajirku** [comment]
K tomu ukládání voleb za nás - za nás by si to mělo pamatovat poslední volbu, ať už byla provedena přes Rozložení nebo přes ikonky. 
A ten zbytek jsem taky psala už výš - přijde nám rozumnější způsob, kdy se přes Rozložení nastaví rámcově rozložení obrazovky (tohle je výborná věc), ale pak způsob zobrazení těch samých dat v konkrétním panelu si může uživatel volit ikonkami (jako se ve starém přepínalo mezi editory), nemělo by to být nastavitelné jen v tom Rozložení (kde to vyžaduje víc klikání a tlačítko není zrovna po ruce).

**Comment by luckajirku** [comment]
A teď úplně nevím, jestli ty šedé pruhy mají být už úplně opravené - u většiny panelů je to OK, ale u panelu s obrázkem tam kus šedého pruhu zůstává a obrázek před tím jakoby uskakuje, místo aby ho ten právě zvětšovaný panel prostě překryl jako to dělá u ostatních panelů.

**Comment by pkudela** [comment]
@luckajirku posli prosim konkretni url z testovaciho serveru inovatiky, kde se to deje + screenshot, diky! Jinak ohledne panelu, tam jsem sjednotil barvu pozadi tak aby byla jednotna a byly jasne videt posuvniky pro zmenu rozlozeni, ale tato uprava jeste neni nasazena, bude dostupna brzy pro testovani a opet napisi sem ja nebo Alberto.

**Comment by luckajirku** [comment]
@pkudela děje se to u čehokoli, kde je v panelu obrázek (např. uuid:c1a97ea5-8b89-4617-9517-990eee85bb2d)

Takhle se šoupání panely chová normálně - jedu lištou nahoru, zakrývá mi to postupně odspodu obsah horního panelu, vršek horního panelu je na místě.
![posuv1](https://user-images.githubusercontent.com/6359479/204482700-2e4b0780-2c24-4cb4-8df3-9e4b07edbece.jpg)

Kdežto u obrázku se obrázek posouvá nahoru a spodní panel ho překryje až po čase. A ještě tam má tu (byť teď už tenkou) šedou čáru

![posuv2](https://user-images.githubusercontent.com/6359479/204482724-a25d5d4a-f86a-4a2b-9c29-982db4212e3d.jpg)

**Comment by luckajirku** [comment]
Jinak by bylo (aspoň za nás) lepší, kdyby ten který panel, i když v dané chvíli nemá být čím vyplněn, nemizel, ale prázdný tam zůstal. Nebo ne prázdný, ale s nějakou vysvětlující hláškou. Takhle je to třeba u procházení periodika nepříjemné, jak se rozložení obrazovky mění.

**Comment by luckajirku** [comment]
Když mám v objektu víc než pár stran a potřebuju v panelu rolovat, tak se mi schová i lišta s ikonami a popis sloupců. Když pak chci třeba označit strany, které jsou dál, a něco s nimi dělat, nemám jak - nevidím ikony pro přesun stran apod.
![lista](https://user-images.githubusercontent.com/6359479/205303080-e6f6967f-ca4e-4bac-880b-24220a1e8959.png)

**Comment by pkudela** [comment]
@luckajirku ano, o tom vim, upravim spolecne s nekterymi obsahovymi castmi, jamkile mi to Alberto preda

**Comment by albertoh** [comment]
@pkudela Mas to! :)

**Comment by pkudela** [comment]
@albertoh uz se na tom pracuje, mam 90% fixnute. V pondeli nasadim na server.

**Comment by pkudela** [comment]
@luckajirku co se tyce toho odsazeni obrazku viz. Tvuj comment vyse, tak se jedna o ochranou zonu je tam padding 8px. Podobne odsazeni je u ostatnich typu panelu, napr. ocr, popis stranky atd. nize posilam screenshoty.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/16591052/205369531-a8c75202-cd17-4f0b-8e24-d27ee3d957b4.png">
<img width="272" alt="image" src="https://user-images.githubusercontent.com/16591052/205369569-2d2a5e6a-6f87-4b1a-92a3-f3421dfbaa90.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/16591052/205369636-cb59e2e4-c3bf-4245-8a10-01c0a0260541.png">

Az budu delat obsahove casti jednotlivych panelu, tak to sjednotim, bude to ulozene v jedne promenne a bude se s tim dat pripadne hybat, kazdopadne neboj, nemam v planu plytvat s mistem.

**Comment by pkudela** [comment]
Scrollovani v panelu se zachovanim pevne pozice toolbaru - FIXED, nasazeno na server @luckajirku prosim o otestovani.

**Comment by luckajirku** [comment]
> Scrollovani v panelu se zachovanim pevne pozice toolbaru - FIXED, nasazeno na server @luckajirku prosim o otestovani.

tohle je v pořádku

Co mi ještě není v tom rozložení jasné, k čemu je v dialogovém okně Rozložení to tlačítko Nastavit rozložení. Pokud v něm udělám změnu a kliknu mimo to okno, tak se mi změny uloží tak jako tak. Má to ještě nějakou funkci, nebo to je z té fáze, kdy se počítalo s tím, že se vše bude nastavovat v tom dialogu a ne taky přímo v panelech?

**Comment by albertoh** [comment]
Nema. Zmenim nazev na "zavrit"

**Comment by luckajirku** [comment]
za nás OK

**Comment by ZdenkaSera** [comment]
Prosím ostatní knihovny - můžeme tohle souhrnné issue uzavřít? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera za MZK můžete

**Comment by nezbedova** [comment]
@ZdenkaSera  Já bych se neunáhlovala. Snímek z 12:35.

![obrazek](https://user-images.githubusercontent.com/13831946/211541892-6d82313d-6af7-4c0c-b691-aa59bd5b4af4.png)

**Comment by ZdenkaSera** [comment]
@nezbedova To ses podle mého jen trefila do nějaké aktualizace  :-) Více na schůzce. Díky.

**Comment by nezbedova** [comment]
Asi dělám něco špatně. Obrazovka hledat. 2x klik v dolní tabulce na to, co chci editovat. Dostanu se na popisná metadata na titul a dál ne. 

Obrázek je z Chromu.

Firefox má ještě toto.
![obrazek](https://user-images.githubusercontent.com/13831946/211542731-8d3c1f7c-53af-4131-8fce-fb6e81049159.png)

**Comment by nezbedova** [comment]
Problém přetrvává. Nemohu otestovat nic ve Vazbách, protože se tam nedostanu. 

![obrazek](https://user-images.githubusercontent.com/13831946/212606772-6c2bf8bb-4501-4f8b-a2f4-539a387322ff.png)

**Comment by albertoh** [comment]
Opraveno. Byl preklep v seznamu povolenych vazeb pro oldprintvolume, a nefungovalo presne pri te kombinaci v rozlozeni obrazovky

**Comment by nezbedova** [comment]
@albertoh Děkuji. Už mi to jde.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, můžu tvůj poslední komentář interpretovat jako "otestováno knav" a navrhnout uzavření? Díky.

**Comment by ZdenkaSera** [comment]
@katerinasirova Prosím, chcete se k tomuhle issue vyjádřit, vzhledem k "prio1"? Děkuji.

**Comment by katerinasirova** [comment]
Otestováno, obecně se nám rozvržení líbí. Jediná zásadní připomínka se týká využití místa na obrazovce (vzhledem k předchozím komentářům předpokládám, že tohle se ještě bude řešit u designu).

**Comment by nezbedova** [comment]
Otestováno. Rozvržení nám vyhovuje. 

Neduhy v zobrazení se budou řešit jinde.

**Comment by erikamirova** [comment]
za nás je to taky v pořádku

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření
