### ISSUE TITLE
Chování editoru Vazby

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#239]
V návaznosti na řešení rozložení obrazovky (https://github.com/proarc/proarc-client/issues/238) se při testování v KNAV objevila ještě  připomínka k fungování Vazeb:

- V editoru Vazby je vlevo struktura vybraného objektu a vpravo jeho popisná metadata
    - Ve starém rozhraní se při vstupu do Vazeb otevřela automaticky vpravo možnost editovat metadata prvního objektu ze struktury zobrazené vlevo
    - nyní je nutné si první objekt ve struktuře označit a teprve potom je možné upravovat jeho metadata
    - například když otevřu ročník periodika, vidím ve Vazbách vlevo NDK Čísla a vpravo popisná metadata NDK ročníku, chtěl bych ale vidět vlevo NDK Čísla a vpravo metadata prvního z těch NDK čísel
- Pokud je ve Vazbách označený nějaký objekt ze struktury vlevo, není možné (nebo jsme nepřišli na to), jak jeho označení zrušit a dostat se tak k možnosti editovat metadata nadřazeného objektu
    - Například pokud mám otevřený NDK Ročník, vlevo mám NDK čísla - jedno z nich označím a tím se vpravo objeví možnost editovat metadata onoho čísla. Jak se dostanu na možnost editovat metadata Ročníku?
    - měla by existovat možnost “odznačit” objekt ze struktury vlevo
- Změnu chování bychom preferovali i v případě vytvoření nového objektu: když vytvořím třeba číslo pod ročníkem, tak aby se v pravé části po uložení objevila metadata k tomu nově vytvořenému číslu.... (teď tam po vytvoření čísla zůstávají metadata k ročníku) 

V KNAV se na tom shodly kolegyně jak z digitalizačního centra, tak ze zpracování časopisů. Prosím, jak se na to dívají zástupci dalších knihoven (@luckajirku @erikamirova @katerinasirova @svetlym)?

Mockrát děkuji

**Comment by luckajirku** [comment]
>   * měla by existovat možnost “odznačit” objekt ze struktury vlevo
> 
řekla bych, že tohle řeší vlevo nahoře kouzelné tlačítko Obnovit

**Comment by albertoh** [comment]
Lze odznacit vyber pomoci "ctrl". Pokud je jenom jeden objekt vybran, a kliknu na nej pri drzeni "ctrl", vyber je prazdny, a tim se dostavam k editaci nadrazeneho.
Muzu ale to umoznit i bez "ctrl"

**Comment by ZdenkaSera** [comment]
@kerschfilip Filipe, Vyzkoušela jsem -  to odznačení objektu/ů v levém okně funguje jak na "obnovit", tak kliknutím s "ctrl". navrhuji tuhle část nechat, jak je.

**Comment by kerschfilip** [comment]
OK, souhlasím, díky

**Comment by luckajirku** [comment]
> * V editoru Vazby je vlevo struktura vybraného objektu a vpravo jeho popisná metadata
>   
>   * Ve starém rozhraní se při vstupu do Vazeb otevřela automaticky vpravo možnost editovat metadata prvního objektu ze struktury zobrazené vlevo
>   * nyní je nutné si první objekt ve struktuře označit a teprve potom je možné upravovat jeho metadata
>   * například když otevřu ročník periodika, vidím ve Vazbách vlevo NDK Čísla a vpravo popisná metadata NDK ročníku, chtěl bych ale vidět vlevo NDK Čísla a vpravo metadata prvního z těch NDK čísel

Za nás je tohle v pořádku, jde spíš jen o zvyk. Asi to souvisí s tím, že se tady přidala možnost jít ve struktuře až na úroveň titulu (to ve starém nejde). 

> * Změnu chování bychom preferovali i v případě vytvoření nového objektu: když vytvořím třeba číslo pod ročníkem, tak aby se v pravé části po uložení objevila metadata k tomu nově vytvořenému číslu.... (teď tam po vytvoření čísla zůstávají metadata k ročníku)
> 

K tomuhle bodu bychom se přidali, nově vytvořené číslo by se mělo automaticky "vybrat" a v panelu s popisem by se měla ukázat metadata toho nově vytvořeného čísla. (Jde o rychlou kontrolu, jestli je vše OK, ve chvíli, kdy nechci využít možnost přejít přímo do objektu, protože pak chci zakládat další čísla.)

**Comment by albertoh** [comment]
> K tomuhle bodu bychom se přidali, nově vytvořené číslo by se mělo automaticky "vybrat" a v panelu s popisem by se měla ukázat metadata toho nově vytvořeného čísla. (Jde o rychlou kontrolu, jestli je vše OK, ve chvíli, kdy nechci využít možnost přejít přímo do objektu, protože pak chci zakládat další čísla.)

Opraveno

**Comment by ZdenkaSera** [comment]
Pokud zakládám např. nový ročník periodika a zvolím "vytvořit" (ne "vytvořit a přejít do objektu") v tabulce je po návratu do periodika označen sice nový ročník, ale v pravém panelu zůstávají metadata objektu, který byl v tabulce naposledy označen.

![image](https://user-images.githubusercontent.com/79305516/209943611-b3484e8e-bd21-4c73-a0a3-162174176a42.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
> - V editoru Vazby je vlevo struktura vybraného objektu a vpravo jeho popisná metadata
>     - Ve starém rozhraní se při vstupu do Vazeb otevřela automaticky vpravo možnost editovat metadata prvního objektu ze struktury zobrazené vlevo
>     - nyní je nutné si první objekt ve struktuře označit a teprve potom je možné upravovat jeho metadata
>     - například když otevřu ročník periodika, vidím ve Vazbách vlevo NDK Čísla a vpravo popisná metadata NDK ročníku, chtěl bych ale vidět vlevo NDK Čísla a vpravo metadata prvního z těch NDK čísel

> > Za nás je tohle v pořádku, jde spíš jen o zvyk. Asi to souvisí s tím, že se tady přidala možnost jít ve struktuře až na úroveň titulu (to ve starém nejde).

Za KNAV je preferovanou verzí, aby se to zobrazovalo, jak je to popsané výše -tj. jako dřív. Člověk musí vícekrát klikat na objekty, aby se dostal, tam kam se dřív dostal hned

**Comment by luckajirku** [comment]
> Za KNAV je preferovanou verzí, aby se to zobrazovalo, jak je to popsané výše -tj. jako dřív. Člověk musí vícekrát klikat na objekty, aby se dostal, tam kam se dřív dostal hned

Nám je to asi jedno, tady jsme schopni fungovat se starou i novou verzí, takže se přizpůsobíme.

Co je ale pro nás problém, je to chování v případě vytvoření nového objektu - aby nově vytvořený objekt ve struktuře byl označený a v panelu s popisem byla metadata toho nového objektu. To už mělo být opravené, ale stále to nefunguje.

**Comment by albertoh** [comment]
Jaka cast vytvoreni objektu nefunguje spravne, "Vytvořit", "Vytvořit a přejít do objektu"?
Ted jsem poupravil "Vytvořit" tak, aby zustal na miste, ale vybral prave vytvoren objekt.

Co se tyce chovani pri otevreni editoru jak pise @kerschfilip :
  - pri otevreni editace objektu, pokud mate panel s metadata, v tom panelu se otevre pave ten objekt z ktereho jiste prisli na tuhle obrazovku. To se mi zda jako spravne chovani. Pokud chci editovat prvni potomek, prijdu na tohle obrazovku prave vybranim prave jim. Jak to popisete vy, jak se dostanu rovnou na ten objekt ktery chci editovat pokud neni zrovna prvni potomek?
  -  Prijde mi divne, ze kdyz chci editovat nejake cislo, mel bych vybrat rocnik.
  - V importu se chova jak jinak. Tady je vybran prvni sken. Tady ale to se mi zda logicky, protoze hlavne jde o editaci skenu.
  
Samozrejme, chovani musi vyhovovat vam, ne mne :) Takze prizpusobim to, podle toho

**Comment by luckajirku** [comment]
> Jaka cast vytvoreni objektu nefunguje spravne, "Vytvořit", "Vytvořit a přejít do objektu"? Ted jsem poupravil "Vytvořit" tak, aby zustal na miste, ale vybral prave vytvoren objekt.

Super, to je ono, funguje.

**Comment by katerinasirova** [comment]
> Za KNAV je preferovanou verzí, aby se to zobrazovalo, jak je to popsané výše -tj. jako dřív. Člověk musí vícekrát klikat na objekty, aby se dostal, tam kam se dřív dostal hned

Za nás je to jedno, nevadí nám ani jedna varianta a přizpůsobíme se.

**Comment by kerschfilip** [comment]
na schůzce 9.2. se domluvilo, že současné chování klienta je OK, vazby se upravovat nebudou.
