### ISSUE TITLE
Výraznější ohraničení rámečků

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#240]
Při testování nám ještě vznikla připomínka k přehlednosti formulářů: Pokud je v metadatech více autorů, klíčových slov apod. hůře se ve formuláři orientuje. Řešením by byly výrazněji ohraničené rámečky. Zkusili jsme udělat návrh jak by za nás bylo lepší: 
![image](https://user-images.githubusercontent.com/57805328/195335344-e0b14f2d-184c-43d0-83fe-3c8fb2a1c20b.png)

Prosím @luckajirku @erikamirova @katerinasirova @svetlym, co si o tom myslíte?

A @albertoh jak komplikované by bylo to případně upravit? V návrhu jsem to udělal jednoduše přes Chrome Inspectora, kde jsem příslušné třídě prostě přidal rámeček, ale na úrovni aplikace to asi bude složitější... 

Děkuji!

**Comment by erikamirova** [comment]
@kerschfilip Za mě je návrh určitě přehlednější, takže jsem pro. :)

**Comment by luckajirku** [comment]
Teda upřesním to - **při zakládání nového objektu** jsou ve formulářích barevně zvýrazněná některá pole. Jde o to, aby v třeba ty  modře zvýrazněné rámečky na jednom místě neznamenaly "nezapomeň to vyplnit" a na druhém místě jen prosté zpřehlednění stránky.
![pa_uloziste_novyobjekt](https://user-images.githubusercontent.com/6359479/195352837-a357cf0f-0d71-46f0-b9cd-84511166d834.png)

**Comment by kerschfilip** [comment]
Děkuji za doplnění, určitě máte pravdu, bude potřeba dát pozor na to, aby případné nové rámečky nějak tohle zvýraznění konkrétních polí nerozbily.

**Comment by albertoh** [comment]
Trochu jsem pridal

![image](https://user-images.githubusercontent.com/5946836/195783983-b9dac486-1d89-4028-ace1-0094e3ba3950.png)

**Comment by kerschfilip** [comment]
Díky @albertoh, ale prý by to bylo ještě lepší, kdyby to bylo ještě výraznější :-) Možná kdyby ten rámeček nebyl šedý, ale černý?
![image](https://user-images.githubusercontent.com/57805328/196985942-232c3e56-3a8f-426c-8cb2-2a1d61a212b4.png)

**Comment by luckajirku** [comment]
za nás taky ještě přidat, ty černé rámečky by vypadaly dobře

**Comment by luckajirku** [comment]
no černá sama o sobě je teď dobrá, ale zase ta modrá vedle ní už nevypadá tak výrazně, jako když ty rámečky byly světlé:-)... takže se ten účel trochu ztrácí. Tohle ještě budeme muset doladit.

**Comment by ZdenkaSera** [comment]
@pkudela @kerschfilip Navrhuji k zavření - domnívám se, že je vyřešeno v https://github.com/proarc/proarc-client/issues/514.
