### ISSUE TITLE
Rozložení obrazovky - Import

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#241]
srovnání starého a nového klienta - k diskusi o tom, jak by měl vypadat Import:

**_starý klient_** 
toto rozložení naprosto vyhovuje, člověk naráz vidí vše, co potřebuje. Takto je to ideální minimálně pro zpracování monografií a periodik (nevím, jak pro jiné typy dokumentů). Otázka je, co vše z toho lze v novém zachovat: 

1. **levý sloupec:** 

- řádkové zobrazení skenů vlevo nahoře (volitelné sloupce, vidím název souboru, index strany, číslo strany, typ strany atd.)
- editace metadat stran(y) ve spodní části - s nastavitelnou výškou (u editace jedné strany stačí polovina, u hromadné editace se sloupec dá snadno upravit, aby vyhovoval)

 
2. **prostřední sloupec:** pás náhledů (jednoduše nastavitelný do šířky, posouváním lišt lze nastavit potřebný počet náhledů na řádek) 
3. **pravý sloupec:** velký náhled vybraného skenu
 

![pa_import_stary](https://user-images.githubusercontent.com/6359479/195336281-fe47ac98-cc5c-4157-a7c9-92257c697561.png)

**_nový klient_**
- nevyhovuje jak řazení sloupců, tak to, že je tu o jednu část pracovní plochy méně než ve starém: 
v levém sloupci buď náhledy, nebo řádkové zobrazení, nikde ne současně (pro kontrolu při popisu to opravdu chybí!)
- extra sloupec jen pro metadata v importu nedává smysl, na metadata stran(y) stačí část sloupce

![pa_import_novyklient](https://user-images.githubusercontent.com/6359479/195336320-44fc31e2-b48c-466e-a117-2d019f3b7a4d.png)

![pa_import_novyklient_radky](https://user-images.githubusercontent.com/6359479/195336337-57355e2c-9680-45a0-a41d-e88b7ae1c98b.png)

**Comment by albertoh** [comment]
Mam to predelat tak, aby vypadalo jako ve starem? 
Prosim o vyjadreni ostatnich

**Comment by nezbedova** [comment]
Za DC by se nám nejvíce líbilo zobrazení:
Náhled jedné strany vlevo, uprostřed malé náhledy a vpravo popisná část.

![obrazek](https://user-images.githubusercontent.com/13831946/195565584-bc4907dc-be42-4681-8aca-545e16876c31.png)

**Comment by ZdenkaSera** [comment]
@albertoh Navrhuji počkat ještě na ostatní knihovny a pak budeme hledat kompromis :-)   

@katerinasirova @erikamirova Prosím, kouknete na to? Děkuji.

**Comment by luckajirku** [comment]
@nezbedova a v DC vám nevadí, že ubyla jedna část obrazovky? Že místo čtyř je to rozdělené jen na tři části a je nutné přepínat? Pro nás je právě tohle dost velká nevýhoda nového klienta oproti starému.
Jinak za nás to navrhované prohození ne, výhodu v tom nevidíme, navíc v úložišti pak je náhled strany úplně vpravo, tady by byl úplně vlevo, spíš by to mátlo.

**Comment by luckajirku** [comment]
náš obrázkový návrh - s tím, že tam nejsou ještě dořešená tlačítka:-)
![import](https://user-images.githubusercontent.com/6359479/195575543-d7bbe837-9477-43e5-b565-0e9c8250b312.png)

**Comment by SmejkalovaAnna** [comment]
Martina to myslela tak, že je to opticky přirozenější číslovat vpravo a náhledy mít vpravo, a ano mít tři okna, ...... a ty malé náhledy v prostřed si ano přepínat, ale s tím, že by bylo možné uložit si nastavení pro konkrétního uživatele a zůstalo i po odhlášení/znovupřihlášení.....

**Comment by nezbedova** [comment]
@luckajirku Přepínání malých náhledů a seznamu nám vyhovuje, protože seznam v járdu je pro nás krátký (i ten Vámi navrhovaný). Možná by bylo řešení čtvrté oko jako sloupec, ale pak už by asi nastal problém s šířkou celého zobrazení. 

V úložišti by to mělo být stejné jako při popisu. Za nás tedy náhled vlevo, popis vpravo. Je přirozenější opisovat z levé strany.

Ideální by bylo variabilní nastavení, kdy by si uživatel navolil umístění oken podle svých zvyklostí a uložil si to do svého profilu, aby to nemusel po každém odhlášení znovu nastavovat.

**Comment by luckajirku** [comment]
> V úložišti by to mělo být stejné jako při popisu. Za nás tedy náhled vlevo, popis vpravo. Je přirozenější opisovat z levé strany.

Tohle už vůbec nedává smysl. Mít strukturu / strom v úložišti vlevo je logické umístění - a sken jako volitelný náhled pak úplně v vpravo - uživatel ho může, ale nemusí použít, navíc ne na všech úrovních je ten sloupec čím vyplnit...

**Comment by erikamirova** [comment]
Já jsem pro návrh paní Jirků. Zachovat to tak jak to je ve starém ProArcu. Vlevo seznam skenů, pak menší náhledy všech skenů a vpravo náhled vybraného skenu. Struktura logicky od celku po jednotlivé skeny. Tak jako čteme zleva doprava. Prosím rozhodně to nepřevracet. 

V NDK lince to máme podobně (bohužel nám chybí náhled skenů a musíme si to rozklikávat). 
![image](https://user-images.githubusercontent.com/37616300/198039933-6012a523-9ff3-4c4c-8bb4-b197b0700e71.png)
![image](https://user-images.githubusercontent.com/37616300/198040099-ec72e240-6584-4e52-ae70-4e885fee548b.png)

Líbilo by se mi, kdyby byly jednotlivé sloupečky vizuálně rozděleny - index, číslo strany, typ strany, ... Nemusí to být jako v lince NDK, stačila by třeba jen svislá čára jako v excelové tabulce - v rychlosti jsem to načrtla. Momentálně to celkem splývá. 
![image](https://user-images.githubusercontent.com/37616300/198041780-6072c1ac-333d-42d0-a513-e01805150087.png)

**Comment by SmejkalovaAnna** [comment]
Já bych to nechala tak, jak to to teď je v tom novém klientovi, plus se mi líbí návrh paní Mírové s čárami... to je moc pěkný... co říkáš @nezbedova ?

**Comment by luckajirku** [comment]
@erikamirova - a ty čáry myslíte takhle i v importu? Ilustrační obrázek máte z úložiště, issue je k Importu, to jen abychom v tom měli pořádek:-).

**Comment by erikamirova** [comment]
@luckajirku Já bych to dala klidně k obojímu.

**Comment by ZdenkaSera** [comment]
V importu  se při popisu stran nezobrazuje xml 
![image](https://user-images.githubusercontent.com/79305516/200545558-78d1f96e-7dbb-4ad7-864c-613caa4825bc.png)

**Comment by albertoh** [comment]
XML opraveno

**Comment by ZdenkaSera** [comment]
@albertoh  Díky 👍

**Comment by luckajirku** [comment]
Tohle lze asi vzhledem k upravitelnému rozložení https://github.com/proarc/proarc-client/issues/238 zavřít. 
To výraznější oddělení sloupců atp. se pak bude řešit až v rámci celkového redesignu.

**Comment by ZdenkaSera** [comment]
Necháme zase štítek chvilku, kdyby se někdo ozval ...

**Comment by ZdenkaSera** [comment]
Vzhledem ke komentáři @luckajirku "Tohle lze asi vzhledem k upravitelnému rozložení https://github.com/proarc/proarc-client/issues/238 zavřít." a návrhu na zavření od 10.11. zavírám. Moc díky všem zúčastněným!
