### ISSUE TITLE
správa dávek - chyby

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#244]
Objevila jsem pár chyb ve správě dávek. Nejde to ani na testovací inovatice. 

1. Když si v novém ProArcu vyfiltruju ve správě dávek např. stav - uloženo, uživatel - tester a dám filtrovat, filtr nereaguje. Pokud ale nekliknu na filtrovat a posunu se místo toho na další list, filtr zareaguje, ale reálně se o další list/page neposunu. 😄
2. Nefunguje posouvání mezi jednotlivými listy/pages.

**Comment by albertoh** [comment]
Opraveno

**Comment by erikamirova** [comment]
V testovacím PA to funguje, ale v MZK nemáme ještě nasazeno. @SykoraLukas

**Comment by erikamirova** [comment]
Tak pan Kudela nám to už nasadil a vše je ok. :)
