### ISSUE TITLE
nefunkční vyhledávání 

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#245]
Ve vyhledávání nefunguje vyhledávání, pokud mám zvolený model: vše. Ani podle názvu, ani podle uuid. Ani na testovací inovatice to nejde. 

![image](https://user-images.githubusercontent.com/37616300/198032590-38a03635-c414-447f-90b2-06ef225e9c10.png)

**Comment by nezbedova** [comment]
Ve vyhledávání přes Dotaz mi nešlo vyhledat ve Vše ani STT Svazek monografie. Zkoušela jsem Název a čárový kód. V Pokročilém hledání lze vyhledat jen podle modelu. 
Testováno na inovatice.

**Comment by albertoh** [comment]
Opraveno.

**Comment by erikamirova** [comment]
Tak pan Kudela nám to už nasadil a vše je ok. :)
