### ISSUE TITLE
Zbytečně volný prostor v řádkovém zobrazení, ve formulářích atd.

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#246]
V novém klientovi je zbytečně moc volného prostoru nad a pod textem - ať už jde o řádkové zobrazení nebo o formuláře. 
Na obrazovku se toho potom moc nevejde a člověk musí pořád rolovat. Přitom písmo je relativně malé, jen nad a pod textem je prázdno, Nevím, jestli to má výrazně oddělit jednotlivé položky, nebo to má jiný důvod (u řádků v úložišti asi aby se pohodlně vešly ikony Přejít na objekt), každopádně za nás je to plýtvání místem. 
Hodně je to vidět, když se dá vedle sebe nový a starý - přikládám srovnání řádkového zobrazení. 
Jak to vidí ostatní knihovny, vám to takhle vyhovuje? 

import
![radky_import](https://user-images.githubusercontent.com/6359479/198206693-ec798bcb-69e8-48ed-b461-30735bcdce96.png)
úložiště
![radky_uloziste](https://user-images.githubusercontent.com/6359479/198206715-e65f5141-3e6e-48e4-af5f-d8972749b0cf.png)

**Comment by luckajirku** [comment]
Můžete na to prosím mrknout, jestli se tady shodneme, nebo jestli vám to takhle roztahané vyhovuje? 
@nezbedova @erikamirova @kerschfilip @svetlym @SmejkalovaAnna 
Díky.

**Comment by luckajirku** [comment]
a ještě @katerinasirova :-)

**Comment by SmejkalovaAnna** [comment]
Já bych nechala ten prostor takhle velký jak je, ale navrhuji zvětšit trochu písmo, aby dovyplnilo rámeček.... větší písmo bude i příjemnější...

**Comment by erikamirova** [comment]
Já bych ty mezery klidně zmenšila. Taky mi to připadá zbytečné. Myslím, že i mezery mezi sloupci by mohly být menší. A např. číslo strany a typ strany od sebe více oddělit. Takto to dost splývá. Opět sem připojím inspiraci z linky NDK. :)

![image](https://user-images.githubusercontent.com/37616300/199224530-c0a675b1-1403-44d3-8866-a6e827ca2274.png)

**Comment by nezbedova** [comment]
Také si myslím, že mezery jsou příliš velké. Ve sloupcích je také dost prostoru, ale tam nevím, co by zmenšení mezer dělalo při změně šíře okna. Aby se to nepřekrývalo nebo nemizelo jako v #104.

**Comment by luckajirku** [comment]
@pkudela výška řádků v tom nově udělaném zobrazení ve stromu je ideální, šlo by to pak prosím tě stejně i v tom zobrazení Tabulka?

**Comment by pkudela** [comment]
@luckajirku upraveno zatim jen pro material table, az budu sahat do obsahovych casti sjednotim vsude stejne, ulozeno do jedne promenne. Az nasadim na server, dam sem info.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/16591052/205596801-4ce364f0-596a-4e13-b787-4f42e0c4ed14.png">

**Comment by pkudela** [comment]
Vyska radku pro tabulku zmensena, definovana ve variables, nasazeno na server, @luckajirku prosim o otestovani.

**Comment by luckajirku** [comment]
Za nás takhle super. (Řádky jsou dost vysoké, aby to bylo přehledné, ale ne zas tolik, aby se na obrazovku vešlo jen pár objektů.)

Jinak ještě by bylo dobré vrátit i to podbarvení pro odlišení lichých a sudých řádků, až se to bude celé dolaďovat, ale to už je zas jiná věc.

**Comment by pkudela** [comment]
Tak to jsem rad, ze to takto vyhovuje. Liche a sude radky udelam, s tim pocitam, az zacnu predelavat vnitrky, coz bude co nevidet. Davam si to do poznamky.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, jak to vyhovuje vám? Děkuju.

**Comment by SmejkalovaAnna** [comment]
Za mě taky super, v tomhle jsem s Luckou za jedno.

**Comment by erikamirova** [comment]
Vypadá to dobře, děkujeme. :)

**Comment by ZdenkaSera** [comment]
Všichni zúčastnění spokojen, tak to zavřeme 😊
