### ISSUE TITLE
Complete code refactoring & redesign

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#247]
Pro budouci vyvoj aplikace vcetne novych pozadavku je nezbytne nutne postupne prepsat kod, nastavit nove layout, sjednotit opakovana chovani prvku a tim zjednodusit a zprehlednit kod atd. V dalsim kroku muze probehnout redesign aplikace.

**Comment by ZdenkaSera** [comment]
@pkudela Prosím budete na příští schůzce k ProArcu (9.11., 9:30) ? Děkuji.

**Comment by pkudela** [comment]
Dobry den vsem, cast tykajici se zmeny layoutu jednotlivych panelu a jejich nastroju krome obsahove casti, o ktere jsem mluvil na schuzce, je hotova. Bude pokracovat Alberto a ja se jeste podivam na nejake issues. Az budeme mit dasi verzi vydame a dame vedet sem. Kazdopadne komentar z tohoto issue tykajici se prazdneho mista v panelech pod obsahem, myslim, ze psala @luckajirku , je prave v dusledku kompletniho predelani layoutu pryc viz. screenshot nize. Zduraznuji zatim to neni nasazene.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/204008584-6fb57dbf-e983-422a-b9ba-b891d003a38b.png">

**Comment by ZdenkaSera** [comment]
@pkudela Moc děkujeme, prima zpráva :-)   Hezký víkend @pkudela @albertoh

**Comment by pkudela** [comment]
- Search page - tree - complete code recatoring - preklady, sjednoceni vzhledu, chovani a vytvoreni globalni tridy pro zobrazeni stromu na ruznych urovnich
- Editor - tree - complete code recatoring - preklady, sjednoceni vzhledu, chovani
- Import - tree - complete code recatoring - preklady, sjednoceni vzhledu, chovani

**Comment by pkudela** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/16591052/217591994-21683c4a-a515-4581-8ae6-3abe267c5ce4.png">

**Comment by pkudela** [comment]
- novy object (dialog) - complete code refactoring, redukce kodu, zmeny designu, preklady - code refactoring, nove preklady atd.
- zarizeni - complete code refactoring - vsechny akce/pohledy, redukce kodu, zmeny designu, preklady - code refactoring, nove preklady atd.

**Comment by pkudela** [comment]
Administrace uzivatelu:
- complete code refacroring
- complete translation refactoring
- new design
- old code deleting

Puvodni:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/221198241-cae2950a-2353-42fb-8731-893b99c3ef2a.png">

Novy:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/221198378-33732820-77c6-4d3d-99f0-41b3cc970e45.png">

**Comment by ZdenkaSera** [comment]
@pkudela Děkujeme, blíže se podívám v pondělí - teď jsem si jen všimla duplicitního "uzamknutí" - nevím, zda funkce nebo jen text. prosím o opravu - děkuji.
![image](https://user-images.githubusercontent.com/79305516/221201203-31e8314f-790c-4c13-9350-97270e24e68a.png)

**Comment by pkudela** [comment]
diky za upozorneni, chyba v prakladu, opraveno zatim jen u me, toto jeste neni nasazane, nasadim jeste dnes

**Comment by pkudela** [comment]
Jeste jsem nenasadil, nasadi Alberto, az opravi problem s ukladanim noveho uzivatele #319

**Comment by pkudela** [comment]
Setting page:

- complete code refactoring
- new layout
- new design
- translation refactoring
- mat slide toggle override
- complete related dialogs refactoring - layout, translation, html, scss

Puvodni stav: 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/224494874-431441a6-dfc3-46cb-a2ab-a02048ea6ebd.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/224494895-e60c04e6-951b-4a30-a87a-1144baac63b5.png">

Soucasny stav:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/224494947-08de94ac-5525-4db6-87a1-21867900eecb.png">

**Comment by pkudela** [comment]
Nasadil jsem na server verzi, kde jsou refactorovany vsechny dialogy na strance hledani, snackbary vcetne prekladu + akce z navigace - novy objekt. Pokud nekdo budete mit cas, prosim zkontrolujte.

**Comment by luckajirku** [comment]
jestli sis hrál s novým objektem, tak prosím tě mrkni na tohle https://github.com/proarc/proarc-client/issues/385 - tam teď zmizelo tlačítko s ikonou a vrátilo se to dlouhé s popisem

**Comment by pkudela** [comment]
V dedikovanem branch “redesign2023" jsem zacal pracovat na redesignu cele aplikace tak, jak jsme se dohodli na schuzce, ktera se tykala tohoto tematu. Pro testovani a predevsim pro porovnani se soucasnou verzi aplikace jsem vytvoril domenu -> https://proarc-redesign.inovatika.dev/ kam jsem umistil build posledni verze.

Upravy jsou uz temer finalni, jeste budu na par vecech pracovat, nicmene od vas bych potreboval, abyste celou aplikaci proklikali a sdelili mi jestli vam nize popsane zmeny vyhovuji.
------
- tu tezkotonazni modrou jsem ponechal stale jako primarni barvu, nicmene s ni pracuji v novem designu velmi opatrne, aby aplikace napusobila tak zatezkane a predevsim aby se lepe dalo pracovat se zvyraznenim nekterych elementu, apliace byla vice prehledna a celkova pusobila vzdusneji
- navbar, drobenkova navigace, toolbary jsou nyni lehce sedive a ikony standardne cerne - zde je prave prostor pro to nektere dulezite ikony pripadne vice barevne zvyraznit, coz pred tim nebylo mozne, protoze na tmavem modrem pozadi je prostor pro barevene zvyrazneni velmi omezeny
- zmensil jsem take rozestupy mezi ikonami v toolbaru v editoru, tak jak jste pozadovali
- celkove jsem take zmensil vysku radku u techto elementu
- navigace
- drobenkova navigace
- toolbar v search
- toolbar v editoru
- tabulka
- strom
- atd.
-----
behem celkoveho redesignu jsem narazil na par nedodelku, pripadne me napadlo vylepseni / sjednoceni chovan atd.i napr. v dialogu “Vyberte nadrazeny objekt” jsem doplnil moznost zruseni filtru u jednolivych poli stejne jako to mame ve vyhledavacni + vylepsil jsem celkovy vzhled atd. viz. screenshot nizePastedGraphic-1.png

primarni barva - pouzita napr. v logu, v buttonech u dialogu - tam je otazka, jestli ji nechcete zmenit na jinou, nebo ji ponechame tak jak je
accent barva - pouzita napr. u checkboxu, podtrzeni vybranych polozek, zvyrazneni nekterych elemntu atd. - tu jsem ponechal  defaultni, lze ji pripadne zmenit
------
Tuto verzi jsem zmergoval s Lukasovym branch kde jsou implementovany posledni upravy tykajici se NDK standardu. Prosim tedy, otestujte, proklikejte jednotlive pohledy a predevsim porovnavejte se soucasnou verzi.

**Comment by ZdenkaSera** [comment]
- V KNAV a MKP budeme testovat během srpna, zkusíme cca do jeho poloviny. 
- Rozhodně bude důležitý názor @luckajirku, až se tomu bude moci věnovat.
- @erikamirova Zapojíte se v MZK?

**Comment by erikamirova** [comment]
@ZdenkaSera Zkusíme otestovat během srpna.

**Comment by pkudela** [comment]
@luckajirku ahoj, diky za reakci, zas tak to nespecha, je to spis kvuli dalsimu vyvoji abychom nemuseli drzet 2 vetve, snazil jsem tam promitnout to co jsem od vas vsech a od Tebe pochytil a co jste zminili v nekterych issues, pocitam, ze to neni finalni, jeste s muze doladovat a az to bude hotove, tak bych se po prazdninach rad vrhnul konecne na ty formulare

**Comment by erikamirova** [comment]
@pkudela Tak jsme v MZK zkusili něco otestovat a máme k tomu pár poznámek. Nevím, jestli je všechny vypisovat do tohoto issue, takže posílám odkaz na sdílený dokument. :) Pokud by ti to nevyhovovalo, tak to přepíšu sem. 

https://docs.google.com/document/d/1fdudNMG2dEVpvcjoWjxs-HxFU4EE0cKF8KyVdsFaKZ0/edit?usp=sharing

**Comment by ZdenkaSera** [comment]
@pkudela Petře děkujeme. Nechala jsem se inspirovat Erikou a taky vkládám jen  odkaz neb jsou posbírané komentáře trochu neučesané. Komentáře, které chválily, jsem zredukovala, ale rozhodně byly 😉

Na rozdíl od kolegů z MZK nám ta modrá barva trošku chybí ;.-) Resp. ne nezbytně modrá, ale hlavní výhrady u nás souvisely s celkovou nevýrazností, všechno trochu splývá, téměř nevystupují důležité prvky. Sjednocením všech lišt do světle šedé chybí aplikaci něco jako "hierarchie". 

https://docs.google.com/document/d/1SwfyxyQIbjbTvBLqaadp4V2cPpbi8ulT/edit?usp=sharing&ouid=114357690539817185782&rtpof=true&sd=true

**Comment by pkudela** [comment]
ahoj @ZdenkaSera jsem ted na dovolene v zahranici do pristiho patku, ale castecne pracuji, tak jen strucne, jeste nez si prectu poznamky

- u verze k testovani redesignu by se mel testovat pouze design, nikoliv funkcionalita, cili proklikat si vsechny mozne pohledy a stranky
- co se tyce te modre, tak ja si nemyslim, ze by ty modre listy chybely,  pripadalo mi to jako jedna velka modra "briketa" ve ktere jsem se naopak ztracel, cerpal jsem take z vasich podnetu ze schuzek - "lepe vypadal stary proarc", nebo podobne vypadaji jine moderni aplikace napr. github - jenoduchy, cisty design., Pouziti defaultni sedive barvy pro navigacni listy a toolbary ma svuj vyznam a to je prave to, ze lze barevne lepe pracovat s prvky aplikace, ktere jsou pro vas dulezite a ktere chcete nejak barevne vypichnout a to je prave to, na cem chci v dalsi fazi pracovat na zaklade vasich podnetu.

To jen jen prvni postreh, az si prectu ten dokument, udelam k jednotlovym bodum poznamku, uvidime, jak se vyjadri jeste ostatni.

**Comment by luckajirku** [comment]
Taky jsme si dělali poznámky do sdíleného dokumentu:-), ten náš je tady: https://docs.google.com/document/d/1a4_jjakzK-OLcCVf88sB-PItTv1gBfBTFUSuuONtNPs/edit?usp=sharing. Každopádně myslím, že by bylo potřeba udělat schůzku jen na design a tam to proklikat a probrat na místě, stejně jako v tom dubnu, to je nejjefektivnější. 
Obecně pokud chceme "jednoduchý, čistý design", který Petře zmiňuješ, tak pořád je tam zbytečně moc barev. A už vůbec do toho nezapadají ty invazivní barevné labely, které se ze správy dávek rozšířily i do úložiště...

**Comment by pkudela** [comment]
Cisty design Lucko, neznamena zadne barvy. Pokud si dobre pamatuji, tak ty barevne labely ve sprave procesu se vsem mimo Tebe libili, to si pamatuji z prvni, nebo druhe schuzky a davali smysl, stejne jako je to v K7 admin klientovi u spravy procesu, nebo v jinych aplikacich, jde o barevene odliseni stavu, vlastnost labelu, stejne jako je pouzivate u issue na githubu. Ale rozhodne souhlasim, ze k designu si muzeme zase dat separatni schuzku, to mas pravdu, je to nejefektivnejsi. Muzeme naplanovat az se sejdeme zacatkem zari.

**Comment by luckajirku** [comment]
To jsem taky neřekla. Mezi "žádné barvy" a "moc barev" je ještě docela dost prostoru...

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, ted jsem si precetl vase postrehy a neco rozhodne dava smysl. Napr. s tema tlacitkama, tam jsem to zamerne nechal vsude v sede, abyste si rekli, jestli chcete primarni barvou vypichnout jen nektere akce / tlacitka, podobne jak je to prave na zminovanem githubu atd. Dale co se tyce toho ostatnbiho, napr. sjednoceni barevnosti checkboxu, pripadne zmenit accent barvu, to take neni problem, to muzeme probrat prave na te schuzce, kterou zminila @luckajirku  Snazil jsem se ty checkboxy sjednotit, ale nekde jsem asi zapomel, ale to doresime, jak jsem psal, redesign jeste neni finalni, ted prijdou na radu vase pripominky a navrhy.

**Comment by pkudela** [comment]
@luckajirku muzes poslat doodle, ja se vracim ze zahranici zitra, pracovne na dovolene funguju castecne, takze kiidne posli, at je to co nejdrive. Na Tvoje poznamky se chystam :-)

**Comment by luckajirku** [comment]
> @luckajirku muzes poslat doodle, ja se vracim ze zahranici zitra, pracovne na dovolene funguju castecne, takze kiidne posli, at je to co nejdrive. Na Tvoje poznamky se chystam :-)

No já doodle nepošlu, netuším, jak je v KNAV obsazená zasedačka... To leda že byste si chtěli udělat výlet do Hradce:-)

**Comment by ZdenkaSera** [comment]
Pošlu během dneška.

**Comment by ZdenkaSera** [comment]
Doodle ke schůzce v mailu a zde:

https://doodle.com/meeting/participate/id/eExokgkd

**Comment by pkudela** [comment]
ahoj @luckajirku procetl jsem Tve poznamky a vetsina pripominek je ok, zkusim udelat nejake upravy do planovane schuzky, na zaklade vasich podnetu, ktere se zdaji byt spolecne pro vsechny

**Comment by pkudela** [comment]
jinak mzk pripominky, take ok, @erikamirova dekuji

**Comment by pkudela** [comment]
ahoj @luckajirku, @ZdenkaSera, @erikamirova procetl jsem ty dokumenty, ktere jste mi poslali a chci se zeptat, jelikoz tam neni nic zasadniho, nektere pripominky jsou podobne, nebo stejne, muzeme tuto verzi zmergnout s branch visk23 a pokracovat s dalsimi upravami, ktere budou reflektovat vase pripominky, uz tam? Bylo by to pro nas jednodussi a uvolnila by se jedna polozka z rozcestniku. Souhlasite s tim?

**Comment by ZdenkaSera** [comment]
@pkudela Ahoj Petře, odpoledne jsme se v KNAV domluvili, že souhlasíme - a já jsem pak issue omylem zavřela bez "OK" pro Tebe. Promiň, za nás je to v pořádku. Díky.

**Comment by pkudela** [comment]
toto issue zaviram, pripadne dalsi designove veci se resi v ramci separatnich issues
