### ISSUE TITLE
Nelze založit nový objekt

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#248]
V poslední verzi nejde založit nový objekt - ani přes plusko, ani přes Nový objekt.

**Comment by luckajirku** [comment]
Otestováno NDK mon a NDK per. / ročníky / čísla, vypadá to OK.

**Comment by SmejkalovaAnna** [comment]
Nejde mi založit NDK Periodikum přez katalog, když v katalogu něco chybí viz obr. Když klepnu zavřít chybu, tak mě to hodí do okna obr.č.3
1)
![obrazek](https://user-images.githubusercontent.com/24409660/200754935-a2cf5c1e-3721-4d14-b5ed-de5061ca1ca3.png)
2)
![obrazek](https://user-images.githubusercontent.com/24409660/200755035-d17034c5-b63c-48da-a89e-20f78794c614.png)
3)
![obrazek](https://user-images.githubusercontent.com/24409660/200755254-ce4e8d66-17ad-4b25-b12b-b3e66062bed6.png)

**Comment by SmejkalovaAnna** [comment]
Ani na Inovatice ani u nás....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna včera jsem otevřela na stejnou chybu issue v jádře - https://github.com/proarc/proarc/issues/1501.  Prosím, přetestuj na Inovatice v jádře. Díky.

**Comment by SmejkalovaAnna** [comment]
Stejné a taky neotevře formulář pro editaci: 
![obrazek](https://user-images.githubusercontent.com/24409660/200758081-4ce192c3-7a13-4a81-aee3-49986544bda9.png)

**Comment by luckajirku** [comment]
Ten původní problém, kvůli kterému jsem issue zakládala, vypadá, že je vyřešen. To další si prosím zkontrolujte @SmejkalovaAnna @ZdenkaSera a kdyžtak pak zavřete.

**Comment by ZdenkaSera** [comment]
@albertoh Zkusila jsem založit stejné periodikum, jako @SmejkalovaAnna  (Knihovna AV-periodika, signatura PF 11). založit lze, v datech je chyba - nechala jsem objekt i s chybou založit
- při prvním uložení ve formuláři už chybu nehlásil
- při opětovném uložen (aniž bych cokoli v datech změnila) se chyba objevila, ale v uživatelsky nepřívětivé podobě - viz níže
- můžeme řešit tady nebo radši nové issue? Děkuji.
![image](https://user-images.githubusercontent.com/79305516/208084089-826a4487-178e-4da7-be12-6b7e800a66e7.png)

**Comment by albertoh** [comment]
Muzeme tady pokracovat. @SykoraLukas nechapu co znamena tu chybu.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Tohle navrhuji k uzavření, je funkční (jiné problémy ohledně zakládání se řeší v dalších issues.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
