### ISSUE TITLE
Zmizení sloupce s náhledem při označení všech malých náhledů

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#249]
Při označení všech malých náhledů zmizí pravý sloupec s náhledem - v současném rozhraní při označení všech zůstává vpravo náhled s posledním označeným skenem. 
![nahledy1](https://user-images.githubusercontent.com/6359479/199193009-37c5550a-8da7-45cc-b0d1-1fee49a4f871.png)
![nahledy2](https://user-images.githubusercontent.com/6359479/199193020-c9b0afde-a309-43cc-8625-462275baee1b.png)

**Comment by albertoh** [comment]
Schovavam panel s obrazkem vzdy, kdyz neni vybran prave jednu stranku. Panely se tak chovaji celkem podle toho co je aktivni.
Muzu ale v pripade, ze je vybrane vice objektu, zobrazit posledni vybran, pokud je to stranka (vyber muze obsahovat ruzne modely).
Tak to chcete?

**Comment by luckajirku** [comment]
Ano, zobrazovat poslední vybraný sken - už se to řešilo v červnu v rámci https://github.com/proarc/proarc-client/issues/185, tam jsme si to vyjasnili, bylo to opraveno, ale s předělávkou rozložení to zmizelo. 
V importu už to vypadá v pořádku, ukazuje to poslední vybraný, ale v úložišti ne, tam to pořád mizí.

**Comment by albertoh** [comment]
Opraveno i pro uloziste

**Comment by luckajirku** [comment]
Když jsem v per. v ročníku, sloupec mizí, prokliknu se do čísla, sloupec s náhledy pořád není - dobře, nemám označený žádný sken, tak budiž. Ale když na jeden z těch skenů kliknu poprvé, pořád se nic neděje, náhled se zobrazí až po druhém kliknutí (ať už na ten samý sken, nebo na jiný).

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Už funguje na první kliknutí.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku "k uzavření", který nikdo nerozporoval.
