### ISSUE TITLE
ProArc 3.2 problém s výběrem profilu a skeneru (#484)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#25]
Je nutné nejprve nastavit profil a skener a až pak vybrat soubory pro načtení. Mělo by to jít i obráceně - vybrat titul a k němu nastavit profil a skener (viz verze 2.1)

https://github.com/proarc/proarc/issues/484

**Comment by luckajirku** [comment]
Vypadá OK, možno zavřít.
