### ISSUE TITLE
Chyba při editaci stran v importu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#250]
Při editaci stran v Importu to při snaze o změnu vyhodí chybu.  Akce se ale provede - a po dvojím kliknutí na Zavřít chybové hlášení zmizí.

**Comment by albertoh** [comment]
Nemuzu reprodukovat... Mozna byl zrovna vypadet jadra...
Co se presne deje? Ja muzu editovat, treba cislo stranky

**Comment by luckajirku** [comment]
Hm, tak dneska už to nedělá, včera jak jsme to zkoušeli, tak nám to všem házelo chyby. A nešlo toho včera v editaci víc, krom těch chybových hlášek třeba při hromadné editaci čísla strany, když se zaškrtlo vkládat do závorek, tak odentrování v poli s číslem strany jen přehodilo volbu vkládat do závorek na nevkládat a nic se neuložilo. Dneska už to vypadá OK. Takže zavírám.
