### ISSUE TITLE
náhledy skenů během editace - vylepšení 

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#251]
Při editaci popisu strany po kliknutí na enter přejdu sice v levém sloupci automaticky na další sken, ale náhled skenu se mi nezmění.

Stejně tak pokud mažu sken, tak v levém sloupci se mi smaže a přejdu automaticky na další sken, avšak v náhledu stále vidím náhled smazaného skenu, což je dost matoucí. 

Děje se to jak během editace ve fázi import, tak i během editace již uložených skenů pod objektem.

**Comment by luckajirku** [comment]
To jste na tom ještě dobře, pokud se vám nezmění jen náhled. Nám to teď ani v tom řádkovém neskočí na další sken, resp. u první strany to zůstane na první, a u druhé a dalších to po uložení změny překvapivě skočí taky zpět na první.
A při mazání tu stranu smaže, náhled smazané strany zůstane, ale neskočí to na další, musím zase nějakou ručně označit.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Mně to opravené nepřijde. Otestujte to prosím ještě někdo další...

**Comment by nezbedova** [comment]
Pokud kliknu na další stranu v malých náhledech, tak popis strany lze udělat, ale náhled zůstává.

**Comment by luckajirku** [comment]
Nevím, jestli je to ještě probíhajícími úpravami, ale moc otestovat to nejde. Při mazání stran v importu to ukáže náhled první strany, v úložišti mě to vykopne úplně.

**Comment by ZdenkaSera** [comment]
@albertoh zatím mažu štítek k testu, z issue se mi zdá, že tady čekáme. Díky.

**Comment by albertoh** [comment]
Opraveno. Souviselo s #235

**Comment by luckajirku** [comment]
problém s mazáním trvá:

v úložišti označím v tabulce stranu, dám smazat, a vykopne mě to o úroveň výš (mažu strany v čísle, vyhodí mě to do ročníku)

v importu označím v tabulce stranu, dám smazat, v náhledech zmizí, v tabulce zůstává a je označená. Každá další smazaná strana zůstává taky označená. Velký náhled při smazání mizí, ale... 

![mazani1](https://user-images.githubusercontent.com/6359479/208424567-77f6c529-c65e-4390-90f2-8a25727f96aa.png)

...když nakliknu v tabulce řádek s tou smazanou stranou (která v tu chvíli v malých náhledech už není), tak se v panelu Obrázek objeví.

![mazani2](https://user-images.githubusercontent.com/6359479/208424584-8feb7978-85fc-4b97-984e-8e411d9d8259.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
mazání už vypadá OK - jak v importu, tak v úložišti

**Comment by luckajirku** [comment]
Ještě je chyba v posunu na další stranu po uložení změny. Přes enter to už funguje, ale pokud uložím změnu v metadatech strany přes ikonku, tak to na další sken neskočí. Jak v importu, tak v úložišti.

**Comment by albertoh** [comment]
Podle mne to tak bylo vzdy schvalne, enter posouva, tlacitko ne (aby clovek mohl tam zustat). Muzu to menit, ale otazka bude kde zustane focus

**Comment by luckajirku** [comment]
Nevím, jestli schválně, ale ve starém ani teď v jádru to tak není. Tam ať uložím změnu jakkoli, skočí to na následující sken.

**Comment by albertoh** [comment]
Nemam problem zmenit. Jen bych prosil vyjadreni ostatnich...

**Comment by luckajirku** [comment]
@nezbedova @erikamirova @SmejkalovaAnna prosím vyjádřete se, zda chcete, aby se to chovalo jako doposud (stejné chování při ukládání přes ikonu i přes enter), nebo zda vítáte tuto inovaci - při uložení změny v popisu přes ikonu se to na další sken neposune, při uložení enterem ano.

**Comment by SmejkalovaAnna** [comment]
Za mě ano, já tuto inovaci bych uvítala, přijde mi to podobné, ale to bylo dřív.

**Comment by erikamirova** [comment]
za MZK se nám líbí toto: při uložení změny v popisu přes ikonu se to na další sken neposune, při uložení enterem ano

@SykoraLukas nasadil bys nám prosím změny od Alberta? Díky

**Comment by pkudela** [comment]
Dobry den @erikamirova, novy build jsem nasadil k vam na mzk server viz. screenshot.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/16591052/210336788-ed5eec81-8c15-450c-b1e4-3eb47b9bdd9b.png">

**Comment by luckajirku** [comment]
A můžete prosím nahodit nějaké příklady, kdy se to odlišné chování při ukládání přes ikonu hodí, kdy konkrétně to využijete? My jsme pro zachování chování jako ve starém klientovi (stejné chování při uložení enterem i přes ikonu), tohle je nepraktické, bude to zdržovat.

**Comment by SmejkalovaAnna** [comment]
Teď to nedokážu přesně specifikovat, ale líbí se mi, že ikona a enter má prostě trošku jinou funkci, je to fajn, je to variabilnější....např. budu chtít si změnu na stránce pro jistotu uložit a ještě s ní potom pracovat, bez toho abych se musela překlikem zase vrátit. Člověk bude vědět, že to takhle funguje a bude použivat jinak ikonu a v jiném případě enter.

**Comment by nezbedova** [comment]
Nevím, kdy by se to dalo využít u jednotlivých stránek. Možná u hromadného popisu více stran. Protože tam by se to mělo chovat stejně.

@erikamirova Můžete napsat nějaký příklad?

**Comment by erikamirova** [comment]
Dává mi to smysl asi jen u hromadného popisu stran, kde bychom to právě využili, např. při foliaci 1r, 1v, 2r, 2v. Tzn. že když si označím třeba 10 skenů, očísluju každý druhý 1r, 2r, 3r... uložím, tak mi ten výběr zůstane označený a očísluju zbytek stran 1v, 2v, 3v. 

Takže u těch hromadných popisů stran bychom byli rádi, kdyby ten výběr zůstal po uložení disketou označený. A pak když bychom měli editaci těch 10 skenů hotovou, můžeme zmáčknout enter a posunout se na další skeny.

**Comment by luckajirku** [comment]
Ale u hromadného je to takhle i teď a má to tak zůstat, to jsme nerozporovali. 
Jde o ukládání u jednoho skenu, aby se zachovalo chování ze starého klienta - aby se to chovalo stejně bez ohledu na způsob uložení - aby jak po uložení přes enter, tak přes ikonu, to skočilo na další sken.

**Comment by erikamirova** [comment]
Jj, tomu rozumím, myslela jsem, že se paní Nezbedová ptá na ten hromadný popis. :D 

U toho jednoho skenu mě asi žádný příklad nenapadá. Není to pro nás zas tak podstatné jako ten hromadný popis. U nás je to ve starém tak, že při importu nás enter i ikona posune na další sken. V úložišti enter posouvá, ikona ne. Takže to máme každý úplně jinak. :D Doteď nám nevadilo, že to je v importu jinak než v úložišti, protože to pro nás není tak podstatné.

**Comment by luckajirku** [comment]
Ve starém v úložišti neposouvá na další sken ani enter, ani ikona. Ale ve starém není v úložišti možnost procházet náhledy, tam je jen tabulka + velký obr. 
Pokud se to má teda chovat rozdílně, tak ne ikona vs enter, ale import vs úložiště:
- v importu posouvat vždy na další sken - ať uložím přes enter či přes ikonu
- v úložišti neposouvat na další sken (tady to i dává smysl, protože se většinou jen cíleně opravují jednotlivosti)

**Comment by nezbedova** [comment]
V předchozím klientovi i v tomto se chová enter a ikona stejně. 

V jádru není ikona. A teď jsem zjistila, že tam není vidět podbarvení označených skenů.

**Comment by ZdenkaSera** [comment]
@erikamirova Můžeme tohle považovat za ok z Vaší strany a navrhnout uzavření? Díky.

**Comment by erikamirova** [comment]
@ZdenkaSera Můžete to klidně uzavřít, to ukládání přes enter nebo ikonu pro nás není tak podstatné a zbytek je myslím v pořádku. :)

**Comment by luckajirku** [comment]
@ZdenkaSera za nás to k zavření není. Teda pokud je cílem mít zavřené tohle konkrétní issue, pak ho klidně zavřete, ale pokud je cílem snížit počet otevřených issues, pak si nepomůžeme, protože pokud se tohle zavře, tak na ten enter/ikonu založím nové - nám ta inovace nevyhovuje.

**Comment by ZdenkaSera** [comment]
Děkuji. @luckajirku Nechci zavírat jen pro uzavření - nebylo mi z posledního zápisu jasné, zda se tohle má předělávat. nechám tedy a jen odeberu štítky naznačující "hotovo", aby se v tom vývojářům líp orientovalo.

**Comment by SmejkalovaAnna** [comment]
Souhlasím s navrhovaným řešením s @luckajirku, jak to potřebují oni. Prosím upravte to tak.

**Comment by albertoh** [comment]
Takze jak ? :)

Tak:
> - v importu posouvat vždy na další sken - ať uložím přes enter či přes ikonu
> - v úložišti neposouvat na další sken (tady to i dává smysl, protože se většinou jen cíleně opravují jednotlivosti)

Nebo stejne posouvat pro oba?

**Comment by luckajirku** [comment]
za nás je nejpraktičtější to výše popsané: import posouvat, úložiště neposouvat

**Comment by SmejkalovaAnna** [comment]
Souhlasím s Luckou Jirků @luckajirku

**Comment by albertoh** [comment]
Je to k testovani

**Comment by luckajirku** [comment]
teď v importu posouvá na obojí, to je OK
v úložišti se to při uložení disketou neposouvá, při uložení enterem ano - mělo by to neposouvat i při uložení enterem

**Comment by albertoh** [comment]
Aha, spatne jsem to precetl. Hned opravim

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Ještě ne úplně. Při odentrování v polích, kam se vpisuje, to už je OK, ale při odentrování v polích, kde je rolátko (typ strany, pozice strany, repre strana), to skočí na další řádek.

**Comment by ZdenkaSera** [comment]
@albertoh zatím odebírám štítek "k testu" (komentář LJ).

**Comment by albertoh** [comment]
Aha, omlouvam se, nenapsal jsem, ze uz jsem to opravil. Vratim stitek

**Comment by luckajirku** [comment]
Ještě nám tu vyskočila jedna věc. Je to spíš taková perlička, ale... Jsem v importu, odentruju v povinném poli a vyskočí mi hláška o nevalidních datech. Pokud si neuvědomím, že musím hlášku odkliknout myší a místo toho odentruju (a ono to k tomu svádí, ta červená hláška vypadá jako předvybraná), tak vyskočí další hláška a když takhle pokračuju, mám sbírku hlášek... A když pak myší začnu ty hlášky postupně odklikávat, tak se mi to s každou odkliknutou hláškou posouvá na další sken, i když odklikávám hlášku, ne pole ve formuláři. Ona asi tady není chyba v tom posunu, ale v tom množení hlášek.

**Comment by albertoh** [comment]
Opraveno

**Comment by katerinasirova** [comment]
Otestováno, hláška se po odentrování zavře. Za nás OK.

Při té příležitosti objevena jiná perlička  - označení nevalidních stran po dokončení validace  - kromě výstražného symbolu, že je objekt nevalidní je také podbarvený červeně, ale u prvních třech objektů jsou podbarveny všechny a poté ob jeden - viz obrázek:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/8912422/214515562-3675a70c-a5c8-4763-a0fd-717f3487b097.png">

**Comment by luckajirku** [comment]
@katerinasirova ono to asi nepřebarví tu šedou - ale když na ten nevalidní šedý řádek klikneš, tak v tu chvíli červený je:-)

**Comment by katerinasirova** [comment]
@luckajirku máš pravdu, za mě je to jen marginálie, teď se to řešit nemusí, spíš aby to bylo někde popsáno a až někdy budete mít čas, tak se to může řešit :-)

**Comment by luckajirku** [comment]
jinak i ten posun po odentrovávání v polích s rolátky už je OK, posuny fungují jak mají.

**Comment by albertoh** [comment]
@pkudela koukni na barvy, plz

**Comment by ZdenkaSera** [comment]
@erikamirova @nezbedova @SmejkalovaAnna Prosím, podívaly byste se na to? Je to prio1, tak raději ok od všech :-) Děkuji.

**Comment by nezbedova** [comment]
Otestováno na STT - v importu i na úložišti funguje. Po označení více stran a enter nebo myš se výběr neposune.

**Comment by erikamirova** [comment]
@ZdenkaSera za nás je to v pořádku

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
