### ISSUE TITLE
použití výrazných barev

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#252]
Při pohledu na to nové logo v poslední verzi klienta musím hned reagovat, prosím, ať jsou výrazné barvy jen tam, kde to dává smysl z hlediska zpracování. Ten žlutý ARC nesmyslně poutá pozornost a bude rušit - a přitom tam to logo zpracovateli k ničemu není (ten ví, v čem dělá). Nechme výrazné barvy jen pro ty případy, kdy se má zdůraznit chyba, povinnost apod. 
To logo má předpokládám (doufám) i nějakou šedavou verzi - a tady bych byla rozhodně pro použít verzi, která nebude rušit v práci (a barevnou nechat do prezentací).

**Comment by luckajirku** [comment]
jj, a ještě to je nesmyslně velké. Já bych to viděla na menší a nejlíp jen tak nenápadně barevné jako jsou třeba ty neaktivní ikony.

**Comment by pkudela** [comment]
Toto logo neni finalni verze, k dispozici je vice variant/navrhu, pocitam s dalsi vyvojem. Nasazeno pouze na vyvojovy server inovatiky jen pro testovani. S dalsim buildem nasadim novou verzi.

**Comment by pkudela** [comment]
Prosim porovnejte ze screenshotu z aplikace, ktere bezi momentalne u me.

Puvodni stav, ktery je nyni na vyvojovem serveru
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16591052/200552411-1ccf30f1-a26b-4e72-a8d4-ef695ef99bce.png">

Zmensena varianta - kombinace pruhlednosti a bile
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16591052/200552682-74feafb2-2691-4baf-9dad-024c079f1d9e.png">

Zmensena varianta - jednobarevna - pruhlednost 80%
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16591052/200552873-75415051-5c43-4908-bbc5-c6f7d3f9e232.png">

Na logu se da jeste nadale pracovat, to pak bude souviset i s celkovym redesignem aplikace, ted jde ale predevsim o to, aby vas to nerusilo pri praci tak hrozne moc :-)

**Comment by luckajirku** [comment]
No klidně bych na něm pracovala k ještě většímu zmenšení:-). Jinak to průhledno-bílé vypadá líp, byť to teda vyvolává mylný dojem, že ta archivační fce je důležitější než vlastní produkce. 
Každopádně když jsme u toho zvýraznění, tak by bylo praktické, kdyby na horní liště byla vždycky zvýrazněná ta agenda, ve které zrovna člověk je (tím spíš, že teď import a úložiště vypadá dost podobně).

**Comment by nezbedova** [comment]
Souhlasím s @luckajirku Logo by mohlo být ještě menší. Nejvíc se mi líbí poslední, průhledná, varianta.

**Comment by pkudela** [comment]
Zmensil jsem logo jeste o 2px, vice uz to  ale neni mozne, to bychom tam mohli nechat necitelny flek. Tech ruznych navrhu loga mam v krivkach mnohem vice, nekdy az nastane cas, muzeme to projit. Nicmene logo jsem delal nejen pro uziti v aplikaci, ale treba i v budoucnu pro nejakou prezentaci, nebo cokoliv jineho, zkratka aby proarc mel nejakou specifickou a moderni "znacku" pro sirsi pouziti. Nevim presne @luckajirku , co tim myslis, ze "Pro" je dulezitejsi nez "Arc", respektive asi chapu, ale rozhodne bych logo v ramci aplikace dynamicky nemenil, to kde se nachazis lze vyjadrit najekou zmenou designu, primarni barvou atd. Udelal jsem tedy jeste obracenou verzi v jeste mensi velikosti + pro pani @nezbedova vkladam screenshot zmenseneho logo cele pruhledne. Ta prvni varianta pro @luckajirku  je ted nasazena na vyvojovem serveru.
![image](https://user-images.githubusercontent.com/16591052/200782306-5f5201e4-1acc-4eda-8b5f-cd75d7781131.png)
![image](https://user-images.githubusercontent.com/16591052/200782591-384a4675-8e27-43f1-9bca-35315c6b0d0f.png)
jinak ve velkem detailu to logo vypada takto, lze vyexportovat v jakekoliv velikosti
![image](https://user-images.githubusercontent.com/16591052/200782986-49898012-f5d0-4499-876b-49f319435e71.png)

**Comment by luckajirku** [comment]
> Nevim presne @luckajirku , co tim myslis, ze "Pro" je dulezitejsi nez "Arc", respektive asi chapu, ale rozhodne bych logo v ramci aplikace dynamicky nemenil, to kde se nachazis lze vyjadrit najekou zmenou designu, primarni barvou atd. Udelal jsem tedy jeste obracenou verzi v jeste mensi velikosti + pro pani @nezbedova vkladam screenshot zmenseneho logo cele pruhledne. Ta prvni varianta pro @luckajirku je ted nasazena na vyvojovem serveru. 

Myslím tím to, že to vzniklo z PROdukční a ARChivační systém, a to produkční užití je podstatnější, ale to bylo jen tak na okraj. V podstatě my ani nemáme co mluvit do toho, jak bude vypadat logo, to je na zadavateli (ale jinak ta verze s výraznějším PRO je lepší:-)). Jinak tady mi šlo hlavně o to, aby to nerušilo v klientovi, kterého budeme denně používat (to velké žluté nás trochu vyděsilo). 
A měnit logo dynamicky v rámci aplikace jsem nemyslela, tou zvýrazněnou agendou jsem myslela to Import, Správa dávek atd., nějak vybarvit jinak to, kde člověk zrovna je. Ale to bude pak patřit do jiného issue.

**Comment by pkudela** [comment]
Ahoj Lucko, chapu a rozumim. Ted tedy nechame logo v posledni variante a az hrabnu do redesignu aplikace, respektive, az cely redesign vcetne refactoringu kodu bude hotovy, tak pak se k logu muzu se zadavatelem vratit.

**Comment by pkudela** [comment]
Jestli muzes, toto issue zavri a otevreme nove, ktere se bude tykat loga jako takoveho, az to bude aktualni.

**Comment by luckajirku** [comment]
ook, zavírám.
