### ISSUE TITLE
umístění šipek Přejít na předchozí/nadřazený/následující objekt

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#253]
Šipky Přejít na předchozí/nadřazený/následující objekt jsou teď přemístěny doprava k tlačítku Rozložení - pokud mám strukturu v levém sloupci, je to hodně nepraktické.

**Comment by albertoh** [comment]
Jsem to tam daval docasne. Hlavne mi to slo o tom, ze to ted nepatri k panelu "vazby". Takovych panelu muze byt vice.
Je to globalne, navigace daneho zaznamu, s cestou.
 Samozrejme, muzu to zase dat k panelu(m) vazeb. Nebo jine umisteni. Co si myslis @pkudela  ?

**Comment by luckajirku** [comment]
teď šipky zmizely úplně - vrátí se?

**Comment by albertoh** [comment]
Vrati :)

**Comment by luckajirku** [comment]
A víme kdy ;-) ?

**Comment by ZdenkaSera** [comment]
šipky tam jsou, v okně se strukturou a zůstaly i v pravém okně - nevím, jestli je i tam chcete nechat, za mne ok @luckajirku

**Comment by luckajirku** [comment]
A je to fakt už k testování? Mi to moc nepřijde.

**Comment by ZdenkaSera** [comment]
@luckajirku Aha - přiznávám, že jsem zkoušela v periodiku přecházet mezi objekty a zdálo se mi, že se to chová mravně. @albertoh prosím, byla vaše poznámka míněna tak, že to je připravené k testu nebo předbíhám? Díky oběma.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, kouknul byste na poznámky nýše a dal vědět, jestli je to k testu? Děkuji.

**Comment by albertoh** [comment]
Je to k testovani

**Comment by ZdenkaSera** [comment]
Díky, vracím tedy štítek :-)

**Comment by luckajirku** [comment]
Nevím, nakolik se ty lišty ještě budou měnit, až se bude předělávat design. Základní funkčnost je OK, ale to, že tam nejsou ty šipky (všechny, vč. té dolů) stabilně, mi až jako taková výhoda nepřijde. Jak se před očima ta lišta průběžně mění, není úplně příjemné.

**Comment by albertoh** [comment]
Sipky ted zustavaji, akorat neaktivni

**Comment by luckajirku** [comment]
To zneaktivnění je super. 
Jinak mi tam chybí ta šipka dolů, ale jako jo, dá se proklikávat i jiným způsobem, takže se bez ní asi dá být.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, kouknete na to? Díky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Vzhledem k tvému komentáři označím "otestováno KNAV".

**Comment by ZdenkaSera** [comment]
@katerinasirova @erikamirova navrhla jsem tady uzavření, ale vzhledem k prio1 - nebudete se k tomu chtít také vyjádřit? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera za nás je to v pořádku

**Comment by katerinasirova** [comment]
Mně taky chybí šipka dolů, ale na jiné použití si zvykneme. Za nás OK.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
