### ISSUE TITLE
KWIS export - nastavení viditelnosti

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#254]
Potřebovala bych, aby byla v novém klientovi při KWIS exportu možnost zvolit si viditelnost objektu. Momentálně to funguje jen ve starém rozhraní. Pokud exportuju v novém rozhraní, tak se mi to automaticky zveřejní. 

![image](https://user-images.githubusercontent.com/37616300/199521294-73905881-7de3-42cb-b8fa-d73720d83b63.png)

**Comment by zabak** [comment]
Upozorňuji na přechod Krameria od public/private k rights labelům, včetně labelu public. Ideální stav by tedy byl, kdyby bylo možné nastavit buď že se jede podle starého public/private, nebo podle labelů a v případě že se jede podle labelů, tak je všechno označeno jako private a k tomu se přidává licence z nakonfigurované nabídky, která reflektuje licence používané v daném Krameriu.

**Comment by albertoh** [comment]
Pridal jsem moznost jako pro Kramerius. Licence budeme resit v #255

![image](https://user-images.githubusercontent.com/5946836/199713749-b0c0e873-cdec-46d9-ba5a-8d4744feddc8.png)

**Comment by erikamirova** [comment]
V testovacím PA to funguje, ale v MZK nemáme ještě nasazeno. @SykoraLukas

**Comment by erikamirova** [comment]
Tak pan Kudela nám to už nasadil a vše je ok. :)
