### ISSUE TITLE
Příprava ProArcu na práci s licencemi Krameria (public/private)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#255]
V návaznosti na poznámku @zabak v issue #254 zakládám nový požadavek.

"Upozorňuji na přechod Krameria od public/private k rights labelům, včetně labelu public. Ideální stav by tedy byl, kdyby bylo možné nastavit buď že se jede podle starého public/private, nebo podle labelů a v případě že se jede podle labelů, tak je všechno označeno jako private a k tomu se přidává licence z nakonfigurované nabídky, která reflektuje licence používané v daném Krameriu."

**Comment by ZdenkaSera** [comment]
čeká na NK

**Comment by ZdenkaSera** [comment]
@SykoraLukas Podle dohod ze schůzky 7.11. - prosím, zjisti možnosti ze strany Krameria. Díky.

**Comment by SykoraLukas** [comment]
získání licenci z {krameriusUrl}/admin/v7.0/licenses

**Comment by SykoraLukas** [comment]
Doplněna funkcionalita na backend. Nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#nastaven%C3%AD-instanc%C3%AD-krameri%C5%AF).

``` properties
# (4.1.1)
# Pouze pro verzi 7
# URL adresa pro stažení seznamu licencí dané instance
krameriusInstance.kramerius7.urlLicense=/search/api/admin/v7.0/licenses
```

**Comment by SykoraLukas** [comment]
Při dotazu na seznam krameriusInsance se nově vrací i list licencí pro danou instanci krameria.

```
{
        "krameriusInstanceId": "kramerius7",
        "krameriusInstanceName": "Kramerius 7 - Inovatika",
        "krameriusInstanceLicenses": [
          {
            "krameriusInstanceLicenseName": "onsite",
            "krameriusInstanceLicenseDescription": "Accessible only in library"
          },
          {
            "krameriusInstanceLicenseName": "covid",
            "krameriusInstanceLicenseDescription": ""
          }
          ]
}

```


Volání na backend je pak stejné jako pro Kramerius resp. KWIS export. Jen s tím rozdílem, že uživatel vybere jednu hodnotu a do parametru license se napíše jméno vybrané licence.

```
POST {{proarcLocalHostUrl}}/rest/v2/export/kramerius4
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

pid=uuid%3Ae5031795-e913-4cb4-9d7b-074fdb5d400c&license=onsite&krameriusInstance=kramerius7
```


Důležité ale je, jak to prezentovat uživateli. Navrhuji 2 exportní dialogy. Jeden tak jak je nyní s parametrem policy a nový bez parametru policy ale s možností licence. Na úrovni konfigurace klienta by si uživatel zvolil, jakou možnost chce používat.

**Comment by albertoh** [comment]
@SykoraLukas prosim o kontrolu

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Při exportu FOXML nebo NDK PSP do Krameria se licence nabízejí, jindy ne - funguje :-). Otestováno lokálně v KNAV.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
