### ISSUE TITLE
Import - umístění tlačítka Pokračovat

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#256]
Tlačítko Pokračovat v importu by mělo být vázané k bloku, kde je tabulka/mřížka, stabilní umístění vpravo nahoře je dost nepraktické.

**Comment by ZdenkaSera** [comment]
Tohle bych podpořila, docela jsem tuhle pátrala, než jsem je našla skrčené v koutku :-)

**Comment by nezbedova** [comment]
Používám dvojklik.

Ale souhlasím s tím, že by umístění tlačítka v řádku bylo oproti stávajícímu umístění praktičtější. Pod sebou by pak byla vidět možnost zastavení, chyba nebo pokračovat. Symbolem by tam mohla být třeba šipka.

**Comment by luckajirku** [comment]
> Používám dvojklik.

Teď si asi nerozumíme, nemyslím Správu dávek, ale Import (viz obr.). Mám popsané strany a chci pokračovat k uložení.
![import_pokracovat](https://user-images.githubusercontent.com/6359479/201606891-a42c34d5-79b1-4322-b0d2-8efdaed42ea1.png)

**Comment by nezbedova** [comment]
@luckajirku Omlouvám se, to jsem si spletla obrazovky. 

Tady mám nastavený ve třetím sloupci Popis stránky, takže mi to nepřišlo divné.  Ale je potřeba počítat s různým rozložením sloupců.

**Comment by albertoh** [comment]
Premisteno

**Comment by luckajirku** [comment]
Za nás OK, dávám k zavření.

**Comment by ZdenkaSera** [comment]
No, to je moje oblíbené tlačítko, kterým jsem chtěla pokračovat v načítání zastavené dávky neb mi nedošlo, že to je tohle přemístěné:-) Mně se to teď zdá prima - **@nezbedova @SmejkalovaAnna** prosím, koukly byste na to, jestli vám umístění tlačítka Pokračovat taky vyhovuje? Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Za mě dobrý, myslíš to nahořevedle Načíst znovu? Mě to přijde přirozené....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Ano - díky!

**Comment by nezbedova** [comment]
Takže to tam je nyní 2x ? To nepovažuji za chybu. Jen jestli se zase dívám na něco jiného.

![obrazek](https://user-images.githubusercontent.com/13831946/210551058-7bb4bd2f-3661-402b-a27a-1adf9ff8d50c.png)

**Comment by katerinasirova** [comment]
Při testování jsem byla chvíli zmatená, na které tlačítko tedy mám klikat. To dvojí použití je zvláštní, ale chápu, že se to při zpracování hodí. Takže za nás OK.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
