### ISSUE TITLE
Přesun stran - v řádkovém zobrazení zůstává (do obnovení) řádek viset 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#257]
Přesun stran z objektu do objektu - v řádkovém zobrazení dám přesunout stranu do jiného objektu, strana se přesune, v náhledech či mřížce v původním objektu zmizí, ale v řádkovém zobrazení je stále vidět, byť se přesunula (zmizí až po kliknutí na Obnovit).

**Comment by albertoh** [comment]
opraveno

**Comment by luckajirku** [comment]
Funguje, zavírám.
