### ISSUE TITLE
úložiště - zobrazení struktury ve stromu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#258]
V úložišti v panelu se zobrazením Tabulka a Mřížka by se hodila i možnost zobrazení ve stromu, aby se nemuselo postupně proklikávat po úrovních.

**Comment by nezbedova** [comment]
@luckajirku To je dobrý nápad.

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/204514902-95da6b28-b1a6-4089-9210-f427b3140144.png)

![image](https://user-images.githubusercontent.com/5946836/204515090-4ec86623-8bcd-4bc0-b22c-9993b746a016.png)

**Comment by luckajirku** [comment]
Vyberu si ve stromu číslo periodika, udělám změnu v popisu strany, dám uložit - a strom se mi sbalí. Nejde to udělat tak, aby zůstal rozbalený, jak byl?

**Comment by luckajirku** [comment]
Ještě se zeptám. Je technicky možné to potom předělat tak, aby ten strom nefungoval jen jako informativní zobrazení té struktury, ale že by se v něm dalo pracovat? Aby měl stejnou lištu jako tabulka a šlo v něm třeba vytvářet a přesouvat objekty (typicky ročníky a čísla u periodik)? Jen se ptám, jestli by to vůbec šlo.

**Comment by albertoh** [comment]
Pujde to. Ale nebude to okamzite. Ted jsem pouzil strom, ktery mame od zacatku.
Pro implementaci vsech tech funkcionalit bych mel vytvorit uplne nove. Ale, slo by to :)

**Comment by luckajirku** [comment]
Tak to je super. Ono se to bude hodit mj. pro zjednodušení zakládání nových ročníků/čísel/příloh periodik (kde to nejde udělat přes "vytvořit více") a rozřazování stran do objektů... že už by pak nebylo nutné pracovat ve dvou záložkách.
Mám na to zakládat nové issue, nebo budeme pokračovat tady?

**Comment by albertoh** [comment]
Klidne tady. Muzeme definovat vsechno co bude umet ten strom.

**Comment by luckajirku** [comment]
Teď jsem narazila na další věc. Jsem v periodiku, mám otevřené různé panely vč. stromu. Udělám na úrovni ročníku změnu v metadatech, uložím. Změna se mi ukáže okamžitě v tabulce, mřížce... Ale ve stromu se ukáže jen v případě, že v tom panelu mám označenou právě tu úroveň, kterou měním. Pokud mám tam označenou jinou úroveň, musí dát refresh, aby se změna ukázala i ve stromu. 
![strom_akt1](https://user-images.githubusercontent.com/6359479/209297613-a0e66dbd-3dd7-4b26-81e4-861e45728de6.png)
![strom_akt2](https://user-images.githubusercontent.com/6359479/209297625-fb3131f2-1ec6-4c04-9795-010f1bae315d.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím, koukni se na tuhle novou funkci - díky.

**Comment by luckajirku** [comment]
Oprava metadat už se propíše hned i do stromu, to už je OK.
Ale ještě se strom neaktualizuje, pokud přesunu sken na jinou pozici. Abych to ve stromu viděla, musím dát refresh.

**Comment by albertoh** [comment]
To bych probral na schuzce... Me se nelibi, a myslim si, ze bude delat problemy pravem se stromem stavajici zpusob chovani: menime poradi, ale jen docasne nez ulozime zmeny. Pro strom je to problem, proto, ze pri kliknuti na polozku stazneme data z jadra, a tam nejsou zmeny. To je duvod proc jsem pri tahani objektu do stromu hned se objevi hlasku pro podtvrzeni zmen.

**Comment by luckajirku** [comment]
Trochu nás překvapilo, že nastavení sloupců stromu, které mají být vidět, funguje jen v Hledat, ale u stromu v panelu ne. Nedalo by se to přebírat i sem? Nebo to bude potřeba řešit jako extra nastavení?

**Comment by albertoh** [comment]
Presunu

**Comment by luckajirku** [comment]
> To bych probral na schuzce... Me se nelibi, a myslim si, ze bude delat problemy pravem se stromem stavajici zpusob chovani: menime poradi, ale jen docasne nez ulozime zmeny. Pro strom je to problem, proto, ze pri kliknuti na polozku stazneme data z jadra, a tam nejsou zmeny. To je duvod proc jsem pri tahani objektu do stromu hned se objevi hlasku pro podtvrzeni zmen.

tohle bychom určitě měli řešit minimálně při rozřazování stran - viz https://github.com/proarc/proarc-client/issues/282#issuecomment-1486623383

**Comment by ZdenkaSera** [comment]
Prosím, proberete to na schůzce 18.3.? Dávám sem štítek redesign a odebírám k testu.

**Comment by ZdenkaSera** [comment]
@luckajirku @albertoh Navrhuji tohle řešit společně s issue https://github.com/proarc/proarc-client/issues/419 - do rozvoje bychom to zahrnuli jako společný bod něcoi ve smyslu rozvoje funkcí stromového zobrazení v klientovi. Souhlasíte?

**Comment by albertoh** [comment]
Souhlas

**Comment by luckajirku** [comment]
jo, já jsem to psala včera i do té tabulky

**Comment by ZdenkaSera** [comment]
Domluva na schůzce 8.10.2024: zavíráme, budeme zakládat issues na jednotlivé požadavky úpravy chování stromu.
