### ISSUE TITLE
Možnost "uzamknout" zvolený panel v obrazovce

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#260]
Ikona připínáček uzamkne panel
Nereaguje na změny aktivního elementu
(graficky oodlišený panel - např. šedá)

Use case je prohlížečka / přihrávačka při zpracování zvukových dokumentů

**Comment by SykoraLukas** [comment]
NA schůzce domluveno, že se jedná pouze o panely, které mají multimedia (obrázek, pdf, zvuk).

**Comment by zabak** [comment]
... a epub

**Comment by albertoh** [comment]
Lze uzamikat panel "media"

![image](https://user-images.githubusercontent.com/5946836/220635705-0dedb54b-b7f4-400b-be27-d0224923ce3f.png)

**Comment by katerinasirova** [comment]
Vyzkoušeno, u zvuku a obrázků funguje dobře, u PDF se tváří, že drží pozici, ale po překliknutí na jinou úroveň popisu se PDF nezobrazí, EPUB jsem nikde nenašla.

**Comment by pkudela** [comment]
@pkudela dodelat design toolbaru - mat-select-field atd.

**Comment by kerschfilip** [comment]
funguje u PDF i EPUB

**Comment by pkudela** [comment]
Z me strany hotovo:

- layout
- preklady
- alerty
- select input

Pred upravou:
![image](https://user-images.githubusercontent.com/16591052/225283946-e18a6851-40fb-47a0-845b-e562fed1721c.png)

![image](https://user-images.githubusercontent.com/16591052/225284072-5449ea86-161e-4b67-b9d4-891cad9da459.png)

Nove:
![image](https://user-images.githubusercontent.com/16591052/225284158-e5f8bc15-f58e-4229-b95e-4aed60fc2f31.png)

![image](https://user-images.githubusercontent.com/16591052/225284287-9afc3195-fb18-4cf4-adcc-494cffa7fb7a.png)

**Comment by pkudela** [comment]
Nasazeno na dev serveru, k testovani.

**Comment by nezbedova** [comment]
Obrázek v NDK monografii i STT si po uzamknutí drží pozici.

Jenom by mě zajímalo, proč má obrázek v NDK monografii pro uzamčení pozice zámeček a Média v NDK emonografii mají pro uzamčení špendlík.

**Comment by katerinasirova** [comment]
Za nás funguje, otestováno na zvukových dokumentech, MON a PER.

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
