### ISSUE TITLE
Jméno jako věcná autorita - chyba formuláře NDK monografie

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#261]
Prosím o opravu formuláře NDK monografie (ale zřejmě i dalších, zatím jsem nezkoušela další modely) - problém popsán v https://github.com/proarc/proarc/issues/1497. Děkuji.

**Comment by luckajirku** [comment]
v NDK mon. za nás OK

**Comment by ZdenkaSera** [comment]
Chyba ve formuláři zpět, osoba zmizela z věcného třídění - nahlášeno zde https://github.com/proarc/proarc-client/issues/327

**Comment by SykoraLukas** [comment]
Opraveno a nasazeno. Prosím o znovuotestování.

**Comment by ZdenkaSera** [comment]
Je to ok, díky.

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
