### ISSUE TITLE
Import - dvojklik na vybrané straně vyhodí do prázdné obrazovky

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#266]
Import - když v řádkovém zobrazení, v náhledech nebo mřížce na některé straně udělám dvojklik, vyhodí mě to do prázdné obrazovky. Ve starém se to při dvojkliku chová stejně jako při jednoduchém kliknutí.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
vypadá OK, dávám k zavření

**Comment by ZdenkaSera** [comment]
Klik a dvojklik se chovají stejně - @luckajirku zdá se ok, zavírám
