### ISSUE TITLE
Klient 2.0.0 (nasazená 23.11.2022) jádro 3.9.1 - vytváření ročníků a čísel

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#267]
Když dám vytvořit ročník nebo číslo (pod titulem, pod ročníkem), tak je tam tlačítlo Vytvořit a přejít do objektu:
![obrazek](https://user-images.githubusercontent.com/24409660/204232924-4113c56f-b5c1-4b8d-9623-203a82ef48ac.png)
když na to ale klepnu, tak bych očekávala, že mě do hodí do toho objektu dovnitř, ale nehodí mě to tam, viz obr. níže
![obrazek](https://user-images.githubusercontent.com/24409660/204233208-c88ccc54-215c-4642-abb3-7d2cfe53e260.png)

**Comment by SmejkalovaAnna** [comment]
Je to chyba nebo vlastnost? :)

**Comment by SmejkalovaAnna** [comment]
Ještě jedna věc, pokud mám označené číslo, viz obrázek, tak  mi to další číslo vytvoří uvnitř toho čísla, což by nemělo. Pokud ho mám odznačené, tak ho vytvoří správně. Dřív bylo jedno jestli ho mám označené nebo ne, prostě to další číslo vytvořilo v tom ročníku, kde jsem právě byla. To vidím, jako chybu....
![obrazek](https://user-images.githubusercontent.com/24409660/204234285-daaf15c8-06a9-4136-91d3-7b0673d052aa.png)
![obrazek](https://user-images.githubusercontent.com/24409660/204234487-e453c36e-5a60-48ad-b6cc-e739bde02a79.png)

**Comment by albertoh** [comment]
Opraveno. Oboji

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto, už se nevytváří ročník nebo výtisk uvnitř, když je označený, to je super. Ale pořád nefunguje toto:
![obrazek](https://user-images.githubusercontent.com/24409660/207004140-949e7e6e-1a72-43eb-b62a-47233ab2d6d9.png)
odklepnu to a hodí mě to někam do háje:
![obrazek](https://user-images.githubusercontent.com/24409660/207004388-c040e770-b281-4570-9507-7d79e660c488.png)
 ještě k tomu, když poklepu  2x na ročník, tak mě to do něj nevleze, resp. vypadá to, že máte v ročníku zase ty samý ročníky, co jsem vytvořila. Pak už na ně 2x klepnput nejde, máte to nějaký zacyklený, mrkněte se prosím na to, zkouším to na Inovatice a smazala jsem cash paměť i historii v Mozzille.

**Comment by SmejkalovaAnna** [comment]
Teď jsem ještě zkusila vytvořit číslo v ročníku a vytvoří se mi ne pod ročníkem ale na urovni ročníků, nejak se to celé rozhodilo:
![obrazek](https://user-images.githubusercontent.com/24409660/207041309-aaa04654-b758-465c-b1a7-b29d72528cf8.png)
po Vytvořit, to vypadá, že tam nic není: 
![obrazek](https://user-images.githubusercontent.com/24409660/207041520-2531eb1b-07e6-4ef9-8a83-db706380315c.png)
ale je to tady: 
![obrazek](https://user-images.githubusercontent.com/24409660/207041692-e168b656-34bf-4838-b3ff-10caa3344d18.png)

**Comment by ZdenkaSera** [comment]
@albertoh Tady mažu štítek k testu - pokud sem přece jen patří, prosím o nápravu. Díky :-)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím o test - díky.

**Comment by SmejkalovaAnna** [comment]
Ročníky i výtisky se vytvářejí už na správném místě, Jen se zeptám jestli někdo víte, třeba @luckajirku jak má fungovat tlačítko 
![obrazek](https://user-images.githubusercontent.com/24409660/210565379-a7a695c4-fe9f-416a-8c4d-d4e040ab400c.png)
 To první me hodí na metadata toho objektu (čekala bych, že to skočí rovnou dovnitř toho objektu) a to druhý mi ho jen vytvoří a kurzor zůstane na tom předchozím objektu.

**Comment by luckajirku** [comment]
> Ročníky i výtisky se vytvářejí už na správném místě, Jen se zeptám jestli někdo víte, třeba @luckajirku jak má fungovat tlačítko ![obrazek](https://user-images.githubusercontent.com/24409660/210565379-a7a695c4-fe9f-416a-8c4d-d4e040ab400c.png) To první me hodí na metadata toho objektu (čekala bych, že to skočí rovnou dovnitř toho objektu) a to druhý mi ho jen vytvoří a kurzor zůstane na tom předchozím objektu.

Ano, má to fungovat tak, že "vytvořit a přejít do objektu" hodí přímo do toho nově vytvořeného. Teď to chybně zůstává na stejné úrovni, kde se nový objekt tvořil (tzn. chovají obě tlačítka stejně).

**Comment by SmejkalovaAnna** [comment]
Takže ještě pořád malá chybka, ale přece chybka: "Ano, má to fungovat tak, že "vytvořit a přejít do objektu" hodí přímo do toho nově vytvořeného. Teď to chybně zůstává na stejné úrovni, kde se nový objekt tvořil (tzn. chovají obě tlačítka stejně)."

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, prosím o test. Díky.

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto, je to nějak divně, fakticky to do objektu dovnitř skočí, ale vlevo zůstane viset původní okno, viz: 

![obrazek](https://user-images.githubusercontent.com/24409660/211482658-d0331ddc-0a4c-4bc5-9fc1-9723846637c0.png)

**Comment by SmejkalovaAnna** [comment]
Chová se to divně, teď u dalšího ročníku to funguje v pořádku: 
![obrazek](https://user-images.githubusercontent.com/24409660/211482966-10db8c61-292b-4ebd-b641-d389fa9ef6ce.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
Funguje to, vypadá to, že na 100% :) 💯

**Comment by ZdenkaSera** [comment]
Vzhledem ke štítkům "otestováno" přidávám návrh na uzavření.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
