### ISSUE TITLE
Popisek zakryje volbu o řádek níž

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#268]
Když přejedu myší přes ikonku, tak popisek zakryje to, co je na řádku pod tím. Čili když chci použít ikonu, která je pod tím, nebo kliknout na objekt atd., tak musím myší jet nejdřív dostatečně mimo, aby popisek přestal tu ikonu zakrývat a pak až na ni můžu kliknout. 
Vypadá to jako prkotina, ale trochu to otravuje.
![popisek2](https://user-images.githubusercontent.com/6359479/204278317-e9849fff-1acc-4ccb-96d0-6b21e95a0b7e.png)

**Comment by pkudela** [comment]
Mrknu na to.

**Comment by pkudela** [comment]
Toto je hotove, nasazeno na server, @luckajirku prosim o otestovani. Nyni definuji pozici toolbaru globalne v service pro vsechny buttony ve vsech typech toolbaru, nyni je nastavena pozice zobrazovani nahore. Nicmene pri specifickem chovani i tato pozice muze mit sve slabiny, ale to nikdy nelze osetrit na 100% pro vsechna rozliseni prohlizece.

**Comment by luckajirku** [comment]
Jo takhle nahoře je to určitě praktičtější. A přijde mi, že ten popisek teď i rychleji zmizí, když kurzorem popojedu kousek vedle.

**Comment by luckajirku** [comment]
...a teď jsem teda zrovna narazila na pár případů, kdy to překáží i nahoře:-). A nezkoušel jsi, že by ten popisek vyskakoval blíž? On celkem daleko od té ikony.

**Comment by ZdenkaSera** [comment]
@luckajirku Nepřidávám k tomu zatím štítek chyba s tím, že to není kritické - ok?

**Comment by luckajirku** [comment]
@ZdenkaSera jo, tohle není problém, to jen že by to šlo asi ještě vylepšit, ale je to v pohodě k používání.

**Comment by albertoh** [comment]
Zmenil jsem globalne chovani popisku (zatim v editoru vazeb, abyste mohli testovat). Ted popisek zmizi kdyz odejdeme z tlacitka, ikdyz najedeme na popisek.

**Comment by ZdenkaSera** [comment]
Zkusila jsem v importu - zdá se mi to ok, popisek jednak opravdu mizí, když myší odjedu z tlačítka, navíc se teď zobrazuje nad tlačítkem, takže do panelu s náhledy/mřížkou ani nezasahuje.

**Comment by luckajirku** [comment]
za nás už OK

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
