### ISSUE TITLE
Nekonečný sroll při slučování (#462)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#27]
Při slučování (přesouvání) objektů z Editoru připojených objektů do Editoru nadřazených objektů se aplikace po každém přesunu obnovuje. Třebaže naposledy editovaný adresář (čísla) ve stromové struktuře úložiště zůstane označen, musí k němu operátor vždy znovu rolovat myší. Při zpracování několika desítek čísel najednou je to zbytečný čas navíc. Dalo by se nějak dosáhnout toho, že se po obnovení aplikace zobrazí stejné místo ve struktuře?

**Comment by ZdenkaSera** [comment]
Navrhuji uzavřít - @luckajirku souhalsíte?

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
