### ISSUE TITLE
správa dávek - přidat tlačítko znovu exportovat

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#270]
Bylo by dobré přidat do správy dávek u exportních chyb tlačítko „znovu exportovat“. 

Např. když při exportu spadne svazek do chyby kvůli reindexaci, já si ho opravím a dám svazek opět exportovat, vznikají ve správě dávek 2 řádky se stejným uuid. Jeden má stav: chyba exportu a druhý: exportováno. Což je matoucí, protože to působí tak, že máte hodně uuid v chybě exportu, i když už dávno exportována jsou.

**Comment by nezbedova** [comment]
Takhle to bylo v jádru dříve. Pak se to opravilo tak, že nový export přepíše ten dřívější chybný.

**Comment by nezbedova** [comment]
Omlouvám se, spletla jsem si Správu dávek s exporty z PA.

**Comment by SykoraLukas** [comment]
Do klienta přidat funkci na znovu export. Na API poslat id batche, podle hodnot v batche proarc spustí odpovídající export.

**Comment by albertoh** [comment]
Klient pripraven. @SykoraLukas pridas api point?

**Comment by SykoraLukas** [comment]
Jádro připraveno.

**Comment by ZdenkaSera** [comment]
Na Inovatice jsem vyzkoušela opětovný export chybného archivu - ve správě dávek to vypadá ok, výsledek ale ověříme až u nás.

**Comment by ZdenkaSera** [comment]
Na schůzce zavíráme.
