### ISSUE TITLE
Nezobrazuje se velký náhled v panelu Obrázek

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#271]
Na testu na Inovatice se s posledními úpravami přestal zobrazovat velký náhled (panel Obrázek). Týká se jen klienta, v jádru vidět je.

**Comment by albertoh** [comment]
Opraveno. Souviselo s novym panel pro strom

**Comment by luckajirku** [comment]
obrázek už se ukazuje (v importu i vazbách)

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem v importu i vazbách  - @luckajirku souhlasím a zavírám.
