### ISSUE TITLE
Po uložení změny v popisu stran se ukáže prázdná obrazovka (import i vazby)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#272]
Po uložení změny v popisu stran (číslo strany, typ strany apod.) se objeví prázdná obrazovka. Ta změna ale proběhne, po refreshi už je to OK. Týká se importu i vazeb. 
Narazili jsme na to začátkem týdne, mysleli jsme, že to je jen chvilkové, jak se opravovalo hodně věcí najednou, tak jsme čekali, ale dělá to pořád. Takhle hezké to je:
 
![prazdno](https://user-images.githubusercontent.com/6359479/206642608-27b013db-a68e-4095-8afa-a7cbc0351c39.png)

**Comment by albertoh** [comment]
Opraveno. Souviselo s novym panel pro strom

**Comment by luckajirku** [comment]
Chtěla jsem testovat, ale teď je to rozbité ještě víc, po načtení dávky nebo při přechodu ze správy dávek se dávka vůbec neukáže a jsou rozhozené i ikony atd.

**Comment by ZdenkaSera** [comment]
Až teď jsem si v mailu všimla komentáře - narazil ajsem na totéž, novou dávku si teď nelze vyrobit. Zkusila jsem se vrátit do správy dávek a "pokračovat" odtud, ale se stejným výsledkem.

**Comment by albertoh** [comment]
Uz je funkcni

**Comment by luckajirku** [comment]
otestováno v importu i vazbách, vypadá OK.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem v importu i vazbách  @luckajirku - souhaksím, zavírám.
