### ISSUE TITLE
Uložení typu strany Entrem v obrazovce Import - přeskočí nastavení obrazovky

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#273]
Když odklepnu vybraný typ strany nebo číslo strany entrem a nalevo mám Náhledy, tak mi to přeskočí vlevo do nastavení Tabulka: 
![obrazek](https://user-images.githubusercontent.com/24409660/207022832-59df6b94-9528-4174-9a63-13c1a0b1a0c9.png) - před Entrem

- po entru: 
![obrazek](https://user-images.githubusercontent.com/24409660/207023009-97ca97df-edb4-478f-a48f-a9c1ea167128.png)

- další věc - když označím víc stran a vyberu římská čísla, tak mi zmizí možnost Ozávorkovat:
![obrazek](https://user-images.githubusercontent.com/24409660/207022630-6c4814a4-63b7-4062-a9dd-e80d78abb76a.png)

**Comment by albertoh** [comment]
@SmejkalovaAnna to se deje u nas na Inovatice? Podle screenshotu se mi zda, ze testujete vasi instalaci.

**Comment by SmejkalovaAnna** [comment]
Tohle je na naší instalaci.... zkusím to ještě na Inovatice

**Comment by SmejkalovaAnna** [comment]
@albertoh Tak na Inovatice to drží a nepřeskakuje to zobrazení. Ale problém s aktivním Ozávorkováním je stejný.

**Comment by SmejkalovaAnna** [comment]
Jojo našla jsem, tak to funguje, alespoň tam.

**Comment by SmejkalovaAnna** [comment]
Teď ale funguje enter zase blbě, když vyberu několik stran a dám Editovat číla stran a potvrdím entrem, tak mě to hodí až úplně dovnitř na úrovni jedné nějaké strany. A nemůžu se vrátit, ta navigace nahoře označená nefunguje jako odkaz.... ale už předtím fungovalo....
![obrazek](https://user-images.githubusercontent.com/24409660/207570383-2b47dc59-85bd-4c63-8727-1da92b19cb09.png)

**Comment by ZdenkaSera** [comment]
Zkusila jsem, stejný výsledek - @albertoh označím jako chybu

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, prosím o test - díky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Zkusila jsem - zdá se mi to ok, ale prosba o tvůj test trvá

**Comment by luckajirku** [comment]
za nás OK

**Comment by nezbedova** [comment]
Funguje.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
