### ISSUE TITLE
nefunkční tlačítko Uložit

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#274]
V panelu tabulka/mřížka/náhledy je nefunkční tlačítko Uložit.

**Comment by ZdenkaSera** [comment]
@luckajirku Koukala jsem na to - možná mi něco uniká, ale zdá se mi, že ve vyjmenovaných zobrazeních není žádná funkce, ve které by se něco měnilo a zároveň potřebovalo ruční uložení. např. reindexace se ukládá automaticky.

**Comment by luckajirku** [comment]
třeba když ručně přesunu objekt na jiné místo

**Comment by ZdenkaSera** [comment]
Pravda - moje chyba, nezkusila jsme refresh a měla jsem za to, že to se taky ukládá rovnou. takže máte pravdu :-)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Při změně už se tlačítko vysvítí, dá se na něj kliknout - a změny se uloží. Dávám k zavření.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem, zdá se ok - @luckajirku tedy to zavřu, děkuji.
