### ISSUE TITLE
Správa procesů - importy

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#276]
V KNAV (3.9.1/2.2.) i na Inovatce nelze zastavený proces znovu spustit - tlačítko "Pokračovat" je dostupné jen u dávek "načtených", dávky zastavené lze jen "znovu načíst".

**Comment by luckajirku** [comment]
Ale Pokračovat znamená Pokračovat do popisu, ne? U zpola načtené dávky by to nedávalo smysl.

**Comment by ZdenkaSera** [comment]
Jasně - dneska se mi exrta nedaří. Hledala jsem tlačítko, které umožní pokračovat v načítání zastavené dávky - tohle "pokračovat to nebude" :-(( Díky!

@albertoh Prosím, poradíte? Děkuji.

**Comment by albertoh** [comment]
Hm, nevim jestli to jde. Ve starem neni. Pokud jadro to dovoli, pridam. @SykoraLukas , je to mozne?

**Comment by SykoraLukas** [comment]
Ve starém to je řešeno pod tlačítkem "Znovu načíst". Rozšířil jsem pro to logiku na serverové části aplikace. 

Tlačítko načíst má tedy 2 funkce. U načtených spustí generování odzačítku, u přerušených spustí generování od posledního celkového setu souborů. (Tedy pokud mám vše pro soubor 1.tiff, ale u 2.tiff mi chybí preview, tak poračuji od souboru 2). Z hlediska logiky na pozdí totiž v obou případech dělá to samé, tak jsem nevytvářel nové tlačítko.

Stejně to funguje i u nového klienta (na povážení je tedy případné přejmenování onoho tlačítka).

**Comment by ZdenkaSera** [comment]
Děkuji za objasnění. Tlačítko "Znovu načíst jsem" jsem původně vybrala, ale když se chovalo výhradně jako při novém načítání, tj. 1) varovalo před smazáním metadat a 2) chtělo znovu zadat profil (aniž by zohledňovalo ten, který byl použit při prvním načítání), zavrhla jsem je. S tím se asi můžeme - minimálně zatím - naučit žít, ale  časem by to chtělo vylepšit.. 

- Nešlo by zachovat zobrazení %, na kterém se dávka stopla? V poslední verzi  (tj. v KNAV 3.9.1/2.2. i na Inovatice) se zobrazování 0% načítání zase rozbilo, zmíněno i v issue #17

**Comment by ZdenkaSera** [comment]
Jen kosmetika - Sprána dávek se myslím měla přejmenovat na Správu procesů. Ale to jen abychom nezapomněli ...

**Comment by ZdenkaSera** [comment]
K výše zmíněnému načítání: při posledním pokusu o načtení (viz issue #17) se příprava importu změnila v načítání během vteřiny - zřejmě se tedy někdy navzájem brzdí některé procesy ... Není to tedy tak, že by okno navždy zamrzlo.

**Comment by ZdenkaSera** [comment]
zavírám jako duplicitní k https://github.com/proarc/proarc-client/issues/17
