### ISSUE TITLE
V tabulce zůstávají přesunuté skeny (do obnovení panelu) viset v původním objektu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#278]
Při přesunu stran do jiného objektu zůstanou V TABULCE strany po přesunu viset, dokud panel neobnovím. V mřížce a náhledech skeny po přesunu hned zmizí, tam je to OK. 
![presunstran1](https://user-images.githubusercontent.com/6359479/208919203-68b33ae5-79bd-4a40-b7c9-31d80a21bf86.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
vypadá OK, dávám k zavření.

**Comment by ZdenkaSera** [comment]
Zkusila jsem, zdá se ok.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
