### ISSUE TITLE
Hláška při automatickém odhlášení (#437)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#28]
Při neaktivitě v "Editoru digitalizovaných dat" mě ProArc automaticky odhlásí. Když se ale vrátím k práci a chci přidat plný text, tak je mi to umožněno, nicméně přidání pdf se nedokončí a zobrazí se chyba 403, která nejspíš znamená, že jsem odhlášená.
Prosím tedy, aby tak jako v jiných editorech i v "Editoru digitalizovaných dat" po automatickém odhlášení vyskakovalo přihlašovací okno.

**Comment by ZdenkaSera** [comment]
myslím, že jde o duplicitu k https://github.com/proarc/proarc-client/issues/367 a navrhuji uzavřít.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
