### ISSUE TITLE
Řešení ukládání stran do různých objektů - rozřazování do čísel per. apod. 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#282]
Současné řešení ukládání stran do jiných objektů klikáním na Přesunout dost zdržuje. Ta fce je fajn, když člověk potřebuje jen výjimečně přesunout pár špatně umístěných stran, ale třeba na rozukládání celého ročníku periodika do čísel to není.
Ve starém člověk přepnul do editoru, tam měl rozbalený strom toho periodika a postupně uložil vše do jednotlivých čísel. Přitom krásně viděl celé per. a mohl si to kontrolovat, strom zůstával rozbalený. Jak by to šlo řešit tady? Současné řešení je nepoužitelné - resp. je to pomalé a méně přehledné - a spíš se takhle udělá chyba, že se uloží ty strany jinam než patří. 
Mrkněte na to prosím vás z jiných knihoven, já si moc nedovedu představit takhle dělat nějakou větší dávku.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, mohly byste se na tohle podívat z pohledu rutinního provozu - periodika, stt přívazky ... ? Moc děkuji.

**Comment by SmejkalovaAnna** [comment]
Já se na to podívám, až to bude zase fungovat, teď jsem zadávala issue https://github.com/proarc/proarc-client/issues/292, nicméně @luckajirku Lucko nestačilo by jen to vyřešit tak, kdyby při dalším otevřením okna (klepnutím na šipičku) tam zůstalo naposledy otevřený  (resp. cílový objekt) v rozbaleném stromě? Jako dřív?

**Comment by luckajirku** [comment]
> Já se na to podívám, až to bude zase fungovat, teď jsem zadávala issue #292, nicméně @luckajirku Lucko nestačilo by jen to vyřešit tak, kdyby při dalším otevřením okna (klepnutím na šipičku) tam zůstalo naposledy otevřený (resp. cílový objekt) v rozbaleném stromě? Jako dřív?
To je ale jenom část. Jedna věc je, že si to má pamatovat, kam jsem naposledy přesouvala. Druhá pak, že pokud přesouvám třeba 300 stran do 50 výtisků nebo příloh, potřebuju mít tu agendu otevřenou, dokud nepřesunu poslední strany. A ne padesátkrát klikat na přesouvací ikonu. Vyskakovací okno dává smysl, pokud se dá pracovat jen v něm - pokud musím překlikávat, tak je to zdlouhavější než ve starém, kde se to dělalo po přepnutí do editoru nadřazených objektů.
@albertoh, nedalo by se to vyskakovací okně rozdělit (stejně jako u fce Označit řadu), abychom tam pak měli v levém sloupci otevřený ten původní objekt s uloženou celou dávkou, a až ve druhém sloupci pak hledání v úložišti? A v levém bych si to označila, v pravém našla, kam to chci uložit, uložila, zaktualizovaly by se automaticky oba sloupce, zas bych vlevo označila další strany, vpravo bych naklikla další výtisk atd. A okno by se zavřelo až po posledním přesunu.

**Comment by SmejkalovaAnna** [comment]
Rozumím, v tom případě s Vámi souhlasím.

**Comment by luckajirku** [comment]
A tohle je ještě ten jednodušší případ, kdy jde čísla vytvořit přes více a nachystat si je předem - a v tomhle kroku se "jen" rozřazuje. 
Pak je ten případ, kdy se čísla zakládají jednotlivě a je potřeba mít k tomu skeny a opisovat údaje z nich - to se teď dělá ve dvou záložkách (v jedné otevřené skeny, ve druhé periodikum - struktura + metadata) a bylo by fajn najít způsob, jak to moci dělat v jedné obrazovce a hned ukládat do nově vytvořeného objektu i ty skeny.

**Comment by albertoh** [comment]
Nasadil jsem novou verzi kde je mozne menit nadrazeneho pomoci pretahovani objektu z panelu vazeb do panelu se stromem.
Pri pohybu se mozne cile obarvy zelene nebo cervene podle povolenych vazeb. (@pkudela udela peknejsi disajn, zatim jde o funkcnosti)

![image](https://user-images.githubusercontent.com/5946836/211261023-30835168-7efa-4980-a769-bd000adc9dfb.png)


 Zaroven, dialog zmeny nadrazeneho objektu jsem zmenil tak, ze lze hledat vsechny modely, ale tlacitko "presunout" je aktivni jen pri vyberu objektu s povolenou vazbou

![image](https://user-images.githubusercontent.com/5946836/211261360-969497ba-254e-4800-9c66-b2771f23f905.png)

![image](https://user-images.githubusercontent.com/5946836/211261511-bf9301ee-ccde-4fdf-9056-0937fd851cf1.png)

**Comment by luckajirku** [comment]
To hledání a (ne)umožnění uložení podle vazeb je super.
Ale to rozukládávání do čísel je pořád nevyřešené.

**Comment by albertoh** [comment]
Rozukladavani jsem resil pomoci tahani z panelu vazeb na strom

**Comment by luckajirku** [comment]
On problém je v tom, že ten strom zrcadlí tabulku/náhledy..., kdežto ten editor nadřazených objektů ve starém umožňoval mít to PŘEHLEDNĚ otevřené na jiné úrovni. 
A je otázka, nakolik je to tahání myší dobré (je to rychlé, ale zas snadněji se strany uloží jinam, než patří) - k tomu už kdysi probíhala diskuse:-).

**Comment by SykoraLukas** [comment]
Předělat dialog ukládání do objektu tak, aby zůstal označený poslední objekt, do kterého bylo uloženo. Pokud ukládám poprvé není označené nic, ale musím objekt vyhledat.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Tohle zatím není?

**Comment by luckajirku** [comment]
Toto je opravdu potřeba dodělat - pro instituce, které dělají periodika, je to dost zásadní.

**Comment by ZdenkaSera** [comment]
Na schůzce 15.3. potvrzeno, že zadání je v této fázi postačující.

**Comment by albertoh** [comment]
Predelal jsem chovani dialogu pro vyberu nadrazeneho objekta.
Ted si pamatuje posledni pouzivany, a pri otevreni se automaticky vybere.

**Comment by luckajirku** [comment]
@albertoh pořád to není ono:-). Člověk musí označit strany, kliknout na přesunout atd. a pak zase označit další, zase kliknout na přesunout... Zbytečné klikání - a pro rozukládávání velkého množství stran je to nepoužitelné. Už jsem to psala tady https://github.com/proarc/proarc-client/issues/282#issuecomment-1372176991.

**Comment by luckajirku** [comment]
@albertoh je k tomu od nás potřeba ještě něco dovysvětlit, ukázat, jak se to používá atd.? a bude to v té verzi, která bude od pondělí k testu, už dořešené?

**Comment by albertoh** [comment]
Ne ne, uz na tom delam. 
Jakmile budu mit funkcionalitu, predam Petrovi aby to dal do krasy.
Kazdopadne, pracuju na tom tak, ze nove, ten dialog bude mit tri casti (jako Oznacit radu):
 - vlevo seznam objektu na presouvani v tabulce
 - uprostred hledani
 - vpravo strom hledaneho objekta
 -
Pri posouvani objektu zustavame tam, aby se dalo vybirat dalsi v leve tabulce.

Je to ono?

**Comment by luckajirku** [comment]
možná bych to radši zkoukla dřív, než se to "dá do krásy", ať se to kdyžtak nečeše zbytečně:-). nevím, jestli to dobře chápu.
teď v tom vyskakovacím okně bude ve druhém a třetím sloupci to, co je teď ve starém pod sebou? uprostřed bude jen výběr titulu a vpravo bude strom toho vybraného?

**Comment by albertoh** [comment]
Je to na testu (osklive :) ).

**Comment by luckajirku** [comment]
Ošklivé je v pohodě, jen je tam dost cestování po obrazovce. Označím vlevo, najdu uprostřed, pak musím úplně doprava, tam si označím, pak zas úplně doleva potvrdit přesun. Ve starém bylo celé to hledání vč. stromu pod sebou. Málokdy se jedna dávka rozřazuje do různých titulů, takže tu prostřední část využiješ na začátku a pak už ne. No, dá se to asi řešit tak, že si vyhledám titul a pak ten prostřední sloupec zúžím tak, že už nepřekáží, ale zas tím přijdu o takovou tu ujišťovací pohledovou kontrolu, že jsem ve správném titulu...

**Comment by albertoh** [comment]
Takze radsi vlevo vyber objektu k presouvani, a vpravo hledani a pod nim cil?

**Comment by luckajirku** [comment]
jj, tohle je lepší, už to může do salónu:-)

**Comment by luckajirku** [comment]
Tak ještě něco - chybí tam náhled. Takže přeci jen by tam měl být třetí sloupec, ale v něm by měl být náhled (poslední nakliknuté) stránky. (Stejně jako to je v tom okně pro Označit řadu.)

A další věc - bylo by možné, aby v hlavičce toho prvního sloupce bylo vidět, odkud se to přesouvá? Ve starém vidím číslo a datum vydání - ideální by teda bylo, kdyby tam byl vidět i titul. Šlo by to tam přidat? Aby tam bylo něco takového, jak je to na liště v Hledat, když se proklikávám níž:
![hlavickazdroj](https://user-images.githubusercontent.com/6359479/227466848-abf30668-e02f-4b06-aefd-f076703ca65a.png)

**Comment by nezbedova** [comment]
@albertoh 

`Málokdy se jedna dávka rozřazuje do různých titulů, takže tu prostřední část využiješ na začátku a pak už ne.` 

A u nás z jedné dávky  STT rozdělujeme do různých titulů (i 80 adligátů), takže jsem to chtěla vyzkoušet, ale nejde mi to. Naskočí tabulka a točí se kolečko. Nevím, zda postupuji správně.

**Comment by SmejkalovaAnna** [comment]
@nezbedova možná to ještě češe kadeřník @pkudela

**Comment by albertoh** [comment]
> Tak ještě něco - chybí tam náhled. Takže přeci jen by tam měl být třetí sloupec, ale v něm by měl být náhled (poslední nakliknuté) stránky. (Stejně jako to je v tom okně pro Označit řadu.)

Treti sloupec vpravo, nebo pod prvnim seznamem objektu?

**Comment by pkudela** [comment]
@luckajirku jak se ma prosim jmenovat ten dialog? "Vyberte nadrazeny" nebo "Vyberte nadrazeny objekt" nebo neco jineho?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/16591052/227544735-f96842b8-1a3d-4636-bfa0-af227c9622f8.png">

**Comment by nezbedova** [comment]
@pkudela Za KNAV: Vyberte nadřazený objekt

**Comment by pkudela** [comment]
hotovo,nasazeno na serveru, prosim otestujte

**Comment by nezbedova** [comment]
@pkudela Mám problém při testování. Po zavření okna mám mlhu.

![obrazek](https://user-images.githubusercontent.com/13831946/227606448-a22ba32e-7d52-4b6f-9ef3-0daa662ffb29.png)

A když jsem chtěla připojit soubory po novém importu k titulu pomocí tlačítka Pokračovat, tak mám chybu. A nevídím Orázek. 

@albertoh Netestuji brzy? Neděláte na tom ještě?

**Comment by albertoh** [comment]
Zkuste smazat cache v browseru

**Comment by nezbedova** [comment]
@albertoh Zkusila jsem. Mám i nové okno i anonymní okno. Po pokusu o změnu nastavení rozložení oken pro editaci mám mlhu. Musím dát refresh nebo kliknout jinam (např. Správa dávek). Pak se vrátím/pokračuji k metadatovému popisu a to už vidím zobrazení jak jsem to nastavila. obrázek nevidím ani při editaci ani při přesunu.
Po Pokračovat mám chybu.
![obrazek](https://user-images.githubusercontent.com/13831946/227611341-c896b9b3-a649-4f21-9f54-f8a1db6ff1bb.png)

Chrom i Mozila.

**Comment by albertoh** [comment]
Nebylo to nasazeno spravne, chybel jeden soubor. Ted je tam

**Comment by nezbedova** [comment]
@albertoh Obrázek vidím, ale nemohu připojit do objektu.

![obrazek](https://user-images.githubusercontent.com/13831946/227620439-d34e6139-e762-40aa-b58c-903958f0c39f.png)

**Comment by nezbedova** [comment]
@albertoh Ale z okna hledat to jde přesunout dobře.

**Comment by ZdenkaSera** [comment]
@nezbedova @luckajirku Prosím, máme chtít s tímhle omezením vydat verzi klienta? Osobně bych byla pro ji vydat a tento týden testovat podle plánu. Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera za nás je to v pořádku, i ve starém se celá dávka ukládá na jedno místo - a to, jestli by to šlo rozřazovat už třeba v importu, a jak přesně by to mělo fungovat, to je na další vývoj.

**Comment by SykoraLukas** [comment]
Ne, toto v současnosti není možné a bylo by to velmi komplikované to dovolit už v importu. 

Buďto je možnost si to rozřadit ještě před importem nebo to udělat až když je uloženo do aplikace.

**Comment by luckajirku** [comment]
Tak pokud tohle není příprava na tu možnost už v importu, tak by se to mělo chovat a vypadat asi malinko jinak - jestli tam jdu z importu přes Pokračovat, nebo jestli rozukládávám v úložišti přes Přesunout. V importu by měla být jiná obrazovka, kde nebude Přesunout, ale Uložit dávku atd. 
Jinak teď nevím, kam to psát, protože se to týká toho prvotního uložení z importu, ale teď je to tak divně spojené tím stejným vyskakovacím oknem. Narazili jsme ještě na to, že když dám uložit/přesunout tu dávku v importu a po uložení dám Otevřít v editoru, tak se to pod tím otevře, ale to vyskakovací okno tam zůstává viset. Zavřít ho můžu, ale pokud volím možnost otevřít v editoru, očekávám, že se mi tohle zavře a ocitnu se hned v tom objektu v editoru.

**Comment by ZdenkaSera** [comment]
@luckajirku @nezbedova Můžeme se v tom případě domluvit, že tohle bude k diskusi na schůzce 18.4.?

**Comment by katerinasirova** [comment]
Jsem pro si to vyříkat na schůzce 18.4.

**Comment by nezbedova** [comment]
Přidávám se k tom, probrat to na schůzce 18. 4.

**Comment by ZdenkaSera** [comment]
Děkuji za reakce.

@albertoh Prosím, vydáš tedy během dneška verzi, abychom mohli nasadit s novým jádrem? Děkuji.

**Comment by albertoh** [comment]
Nejde vydat release. Asi github ma problemy. Zkusim jeste pozdeji

**Comment by luckajirku** [comment]
Třeba se github kousl, protože tuší, že je tam potřeba ještě nějaké věci opravit:-)

**Comment by albertoh** [comment]
viz https://github.com/proarc/proarc-client/issues/332#issuecomment-1486481528

**Comment by luckajirku** [comment]
V základu to funguje dobře, ale měl by se po uložení stran zaktualizovat strom. Uživatel by měl mít možnost si hned zkontrolovat, že se tam ty strany přesunuly. Ve starém po přesunu sice ten editor s uložením zmizí, ale po vybrání další strany se tam objeví a přesunuté strany jsou už vidět na novém místě. V klientovi zmizí ze starého umístění, ale v novém vidět nejsou.

**Comment by katerinasirova** [comment]
Souhlasím s @luckajirku. Při rozřazení např. do čísel periodik je třeba kontrolovat, jestli se to přesunulo správně a logičtější je to dělat přímo v tom vyskakovacím okně. Jinak ostatní chování otestováno a je OK.

**Comment by luckajirku** [comment]
@albertoh prosím tě, jak tohle vidíš? vím, že jsi v tom issue pro strom psal, že je problém s aktualizací, pokud se přesune objekt v tabulce a ještě není uložená změna, ale tady k uložení změny už došlo, takže to je trochu jiný případ a problém by tam být neměl, ne?

**Comment by albertoh** [comment]
Tenhle je jiny strom. On neovlivnuje veci editoru. Tady to udelam. Ale ne tenhle tyden, jak jsme se domluvili

**Comment by albertoh** [comment]
Strom se obnovuje

**Comment by albertoh** [comment]
Pravda, jsem to delal v monografii. Jdu na to

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Pořád ne:-). Strom se obnovuje, ale po uložení není vybraný poslední objekt, do kterého se přesouvalo. Pokud okno zavřu a znovu otevřu, pak se to posune na ten správný, ale jinak si to drží ten poslední objekt z předchozího použití fce Přesunout. Potřebujeme, aby se to posouvalo na poslední vybraný objekt už během toho jednoho rozukládávání, jako to funguje ve starém.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Jo, tohle už je ono, aktualizuje se to správně a označuje se to, co má. 
Jen ta hláška asi musí ještě dozrát... Zatím se ukazuje tohle:
editor.children.relocate_dialog.titleRepo
editor.children.relocate_dialog.messageRepo

**Comment by luckajirku** [comment]
Za nás už OK, takhle se to má chovat.

**Comment by luckajirku** [comment]
tak už se nám to zase rozbilo - asi s tou opravou posouvání lišty. Když přesunu strany, uložím a dám zavřít, tak mám v úložišti krásně šedé prázdno - až po F5 se obsah načte.

**Comment by albertoh** [comment]
Funguje to dal. Akorat je tam vterina v sede. Nesouvisi to s tim posouvanim. 
Stava se kdyz mam editor metadat. Hledam pricinu

**Comment by luckajirku** [comment]
No ona to nebyla vteřina, bez refreshe nám to nešlo. Ale dneska už je to OK, tak nevím, jestli už jsi s tím něco dělal, nebo se ProArc jen potřeboval prospat.

**Comment by albertoh** [comment]
Zatim nic nedelal, ale chci to zlepsit. Ten editor metadat ted se nacita hodne dlouho. To je kvuli to rozbaleni...

**Comment by albertoh** [comment]
Ted se pri obnoveni objevuje "loading bar" nahore, aby bylo jasne, ze obrazovka neztuhla, jen dumaaa :)

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
