### ISSUE TITLE
Funkce "Smazat" - odlišné chování v importu a úložišti

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#283]
Na inovatice má uživatel tester oprávnění mazat objekty v úložišti trvale.

![image](https://user-images.githubusercontent.com/79305516/209939744-a6490799-e511-4ed9-8df7-c4f4d653dbb0.png)

V importovaných skenech není možné trvalé mazání mělo by to být stejné, prosím o opravu.

![image](https://user-images.githubusercontent.com/79305516/209939469-0caf66d2-eb11-4036-b369-251cf662b3c7.png)

**Comment by albertoh** [comment]
tester je superAdmin

**Comment by ZdenkaSera** [comment]
@albertoh Souhlasím, to je ok, jen si myslím, že by se to oprávnění mělo chovat všude stejně a v importech by se tedy také měla nabízet možnost "smazat trvale".

**Comment by albertoh** [comment]
Ale v importech neexistuje moznost smazat z uloziste... skeny jeste tam nejsou. Vzdy to bude trvale

**Comment by ZdenkaSera** [comment]
Jasně - moje blbost. díky.
