### ISSUE TITLE
Spodní pruh s infem o aplikaci

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#284]
Jak se objevil v poslední verzi ten pruh s informacemi o aplikaci - musí tam být? Info o verzích klienta i jádra potřebujeme, ale stačí nám to po kliknutí na O aplikaci. Tady ty informace zbytečně zabírají místo na obrazovce.

**Comment by albertoh** [comment]
Je to nastavitelne v globals.js:
showFooter: true

Jsem to zapnul, abychom videli verzi.

**Comment by luckajirku** [comment]
Díky za vysvětlení, pak je to OK:-) a zavírám.

**Comment by pkudela** [comment]
@luckajirku jak psal Alberto, paticka neni porvina, mame to zapnute jen na vyvojove verzi na inovatice, je to volitelne stejne jako u k7admin kienta
