### ISSUE TITLE
Panel Popisná metadata se neaktualizuje při přechodu na jiný titul

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#285]
Mám zapnutý panel Popisná metadata, vidím metadata toho titulu. Přes Hledat přejdu na jiný titul, stále však vidím popis předchozího (přitom náhledy apod. už jsou ze správného titulu), zabere až refresh.
![popis_visi](https://user-images.githubusercontent.com/6359479/210235211-fd3c57b1-687b-4912-b273-2d7d5347244e.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
vypadá OK

**Comment by ZdenkaSera** [comment]
Zdá se ok, nenašla jsem protipříklad.

Zavírám na základě testů a nerozporovaného návrhu na uzavření.
