### ISSUE TITLE
Vytvoření objektu - chybí přededitační okno

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#287]
Při vytváření jakéhokoliv objektu včetně ročníku a výtisku, se nezobrazí přededitační okno - najde knížku v katalogu, pak dám Vytvořit objekt a pak to hodí prázdné okno, kde běží proužek a nic se neděje:
![obrazek](https://user-images.githubusercontent.com/24409660/210536941-a01dd040-2a9b-49f8-89f7-25dbe10ae096.png)
když dám Vytvořit a přejít do objektu, tam mě to hodí do toho velkého klasické editace, problémy nastávají v případě, že je chyba v katalogu např. chybí role u autora a pod. to objekt nevytvoří.... v minulé verzi klienta to fungovalo moc pěkně:
![obrazek](https://user-images.githubusercontent.com/24409660/210537689-f82d7d18-228e-42ce-98dc-96a238320aa1.png)
a když byla chybka, tak: a člověk to mohl upravit, chceme toto zpátky!!!
![obrazek](https://user-images.githubusercontent.com/24409660/210538360-30d08ba7-1d9c-407e-85fc-7774fe92787d.png)

**Comment by luckajirku** [comment]
Na tohle jsme narazili taky - tak ono nechybí, jen nefunguje:-)...

**Comment by albertoh** [comment]
Chybu vidim. Byla zanesena pri oprave #285

**Comment by albertoh** [comment]
Je na testu

**Comment by ZdenkaSera** [comment]
Zkoušela jsem zatím na STT mono a STT VD mono - funguje ok, nechám ale k testu všem. Díky.

**Comment by kerschfilip** [comment]
v případě vytvoření eČlánku se se mi stále zobrazuje to prázdné okno, jak popsala nahoře @SmejkalovaAnna 
![image](https://user-images.githubusercontent.com/57805328/211333118-7afdbe75-8460-493b-a768-2bf01c165533.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
Funguje i u NDK Periodikum, ročník, výtisk....

**Comment by luckajirku** [comment]
za nás OK

**Comment by ZdenkaSera** [comment]
@kerschfilip Zkusila jsem e-článek z volné ruky - okno je tam, tak snad i tady ok.

@SmejkalovaAnna Vzhledem k Tvému komentáři a svým testům z minulého týdne označím jako "otestováno KNAV"

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
