### ISSUE TITLE
Import - hromadné načítání adresářů - hláška

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#288]
Pokud označím více adresářů a dám je načítat, hodí to chybu Importní dávku nelze editovat! Chci pokračovat do správy dávek - na Zavřít u té hlášky je ale nutné kliknout tolikrát, kolik adresářů se právě načítá.

**Comment by ZdenkaSera** [comment]
Chtěla jsem založit nové issue, ale tady bude souvislost, tak přidám sem. Problém je i u jednotlivých dávek.

V importech zmizelo okno, ve kterém se dal sledovat postup načítání dávky. Rovnou se zobrazí  okno - viz níže - už ve chvíli, kdy dávka ve skutečnosti není načtená. Pokud oknu uvěřím a zkusím "Pokračovat", dostanu hlášku, že nelze editovat. Pokud počkám  dostatečně dlouho, aby se dávky opravdu stihla načíst, lze editovat. 
Pokud dostanu hlášku o nemožnosti editace, odkliknu ji a přejdu do správy dávek, tam dám obnovut, stejná hláška se mi zobrazuje, dokud se dávka nenačetla komplet.
Platí obecně - zkusili jsme na mono, stt a per.

![image](https://user-images.githubusercontent.com/79305516/210540895-78fcc51f-98c0-45be-83aa-ed6497df9701.png)

![image](https://user-images.githubusercontent.com/79305516/210541851-a18d5889-5272-4a37-b8ce-19254134ac76.png)

**Comment by ZdenkaSera** [comment]
Chtěla jsem založit nové issue, ale tady bude souvislost, tak přidám sem. Problém je i u jednotlivých dávek.

V importech zmizelo okno, ve kterém se dal sledovat postup načítání dávky. Rovnou se zobrazí  okno - viz níže - už ve chvíli, kdy dávka ve skutečnosti není načtená. Pokud oknu uvěřím a zkusím "Pokračovat", dostanu hlášku, že nelze editovat. Pokud počkám  dostatečně dlouho, aby se dávky opravdu stihla načíst, lze editovat. 
Pokud dostanu hlášku o nemožnosti editace, odkliknu ji a přejdu do správy dávek, tam dám obnovut, stejná hláška se mi zobrazuje, dokud se dávka nenačetla komplet.
Platí obecně - zkusili jsme na mono, stt a per.

![image](https://user-images.githubusercontent.com/79305516/210540895-78fcc51f-98c0-45be-83aa-ed6497df9701.png)

![image](https://user-images.githubusercontent.com/79305516/210541851-a18d5889-5272-4a37-b8ce-19254134ac76.png)

**Comment by ZdenkaSera** [comment]
Tohle se zdá v pořádku.

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, narazili jste ještě na potíže nebo bychom to mohli zavřít? Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera Ten problém, kvůli kterému jsem zakládala, už tam není. Takže ano, je to možné zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
