### ISSUE TITLE
Popisky přes náhledy

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#289]
Import / Správa dávek / editace
V náhledech je teď přes obrázek dole popis, který ale může zakrýt text - může být problém rozlišit prázdnou a normální stranu. Ve starém rozhraní byl popisek až POD náhledem, nic nezakrýval. 
A ani zobrazení nejkratší možné verze popisků není řešením, ten text může být úplně malý (typicky copyright v rohu).
![nahledyklient](https://user-images.githubusercontent.com/6359479/210540013-99121ff3-5984-4a71-968d-ed0cc1d41178.png)
![nahledystaryklient](https://user-images.githubusercontent.com/6359479/210540026-b5dd4e41-7635-4f60-aae7-7e7538c6abd5.png)

**Comment by pkudela** [comment]
to bylo i u starsiho "honzoveho" klienta viz. screenshot nize:
![image](https://user-images.githubusercontent.com/16591052/210542236-ed061ccc-4082-49e8-8582-4e3807fb2e07.png)
Mam to tedy udelat tak, aby popisek ani zcasti nezakryval obrazek, chapu to spravne? Pokud ano, to neni problem, jen dej prosim vedet.

**Comment by luckajirku** [comment]
Za nás ano.

**Comment by nezbedova** [comment]
Za nás také ano.

**Comment by pkudela** [comment]
@luckajirku , @nezbedova vyhovuje takto?

![image](https://user-images.githubusercontent.com/16591052/210739794-8d986195-56a1-4797-9211-7516d3386996.png)

![image](https://user-images.githubusercontent.com/16591052/210740032-e817db51-b9e7-48bf-a822-218414a64310.png)

**Comment by nezbedova** [comment]
Takto nám to vyhovuje. Děkuji.

**Comment by pkudela** [comment]
Nejsou tucne, ted se na to divam, z nejakeho duvodu to udelalo to vlozeni screenshotu.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/16591052/210748248-833fda4b-be01-4714-a79b-ed4d89ce3d50.png">

**Comment by luckajirku** [comment]
Ne, pořád stejně. Ale jasně, ony tam tučně vypadají i všechny ostatní popisky, takže si to zkusím představit:-). Za nás takhle OK.

**Comment by pkudela** [comment]
tan posledni screenshot, co jsem posilal, tak tam uz popisky tucne nejsou, divne, ale nevadi, az uvidis na zivo, tak se kdyz tak ozves

**Comment by pkudela** [comment]
Nasazeno na server, k testovani.

**Comment by ZdenkaSera** [comment]
To vypadá pěkně.

**Comment by luckajirku** [comment]
Za nás taky OK.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
