### ISSUE TITLE
opakování jazyku klíčových slov (#424)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#29]
Je možné ve zjednodušeném formuláři pro eČlánek opakovat jazyk klíčových slov tak, aby se při přidání nového pole pro další klíčové slovo zopakoval jazyk z toho předcházejícího?

**Comment by SykoraLukas** [comment]
@kerschfilip je stále relevantni?

**Comment by kerschfilip** [comment]
@SykoraLukas ano, je to stále požadavek na rozvoj zařazený do letošního VISKu

**Comment by kerschfilip** [comment]
Představa je taková, že když kliknu na + na kartě klíčová slova, tak se klient podívá, jaký jazyk jsem použil na té předchozí kartě Klíčová slova a rovnou ho doplní.

<img width="501" alt="Snímek obrazovky 2024-07-17 v 14 01 24" src="https://github.com/user-attachments/assets/5f2cdfd1-3872-4f53-a2a8-d3f798b63a59">

Na té úrovni "Klíčová slova/Předmětové heslo" by navíc to + vůbec nemělo být. Pod každým elementem `subject` má být totiž pouze jeden element `topic`. 

<img width="495" alt="image" src="https://github.com/user-attachments/assets/a19fc2b9-b4cd-4ea7-8dcf-c792610b3da0">

**Comment by kerschfilip** [comment]
Super, funguje to dobře. 

@albertoh bylo by ale ještě možné zrušit tohle červeně označené +? Jen u těch klíčových slov. Může to svádět k tomu ho použít, ale je to vlastně špatně, protože pod každým elementem subject má být totiž pouze jeden element topic.

![image](https://github.com/user-attachments/assets/f72c0c0a-5627-4a99-8795-e70563309a30)

**Comment by albertoh** [comment]
Tlacitko je disabled

**Comment by kerschfilip** [comment]
za mě je to OK, díky!

**Comment by kerschfilip** [comment]
nakonec k tomu mám ještě jednu drobnost: i když mám v profilu nastavené, že se mi má formulář ečlánku vždy rozbalovat, tak po kliknutí na "Přidat s jazykem" mi ta nově vytvořená karta pro předmětové heslo zůstane sbalená: 
![image](https://github.com/user-attachments/assets/d00de7e7-3e16-475c-8251-d9bf8c1f2525)

Všiml jsem si ještě, že tlačítko pro přidání s jazykem je i u věcného třídění v rámci NDK eČlánku, ale nefunguje. Jde to nějak opravit, aby to fungovalo i tam?
![image](https://github.com/user-attachments/assets/c002e527-34ef-4164-8b89-964b3a25f67f)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
OK, děkuju!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by tumovam** [comment]
Znovu otvírám, protože...

Ve formuláři pro **NDK eČlánek**:
✔️  přidání s jazykem ![obrazek](https://github.com/user-attachments/assets/b2cbf393-36d9-4ed0-95ad-763319cd0ae6) v pořádku, ale 
- nerozbalí se karta s nově přidaným klíčovým slovem 
- není zašedlé plus (+) u přidávání "Topic": 
![obrazek](https://github.com/user-attachments/assets/c05c0403-3726-4bc3-8e3a-9b105918d08b)

Ve formuláři pro **eČlánek** chybí chybí možnost pro vyplnění temporal a geographic:
Nyní: 
![obrazek](https://github.com/user-attachments/assets/5d4c1493-cc6b-4fdd-a489-c29cd243ee8e)

Lepší by bylo:
![obrazek](https://github.com/user-attachments/assets/3fc5bc8d-ae4d-446b-8a57-360162e18bc3)

_(test v2.3.2, 4.2.3)_

**Comment by SykoraLukas** [comment]
K testování od 29.11.2024

**Comment by tumovam** [comment]
Formulář eČlánek:

- [ ] přidání s jazykem ![obrazek](https://github.com/user-attachments/assets/b2cbf393-36d9-4ed0-95ad-763319cd0ae6) 🆗 
- [ ] rozbalí se karta s nově přidaným klíčovým slovem (ano, v Profilu musí být nastaveno rozbalování formuláře) 🆗 
- [ ] zašedlé plus u přidávání "subject/topic" 🆗 
- [ ] v klientovi chybí pole pro vyplnění temporal (subject/temporal), geographic (subject/geographic ) a autor (subject/name), na api v pořádku

Formulář NDK eČlánek
- [ ] přidání s jazykem ![obrazek](https://github.com/user-attachments/assets/b2cbf393-36d9-4ed0-95ad-763319cd0ae6) 🆗 
- [ ] rozbalí se karta s nově přidaným klíčovým slovem (ano, v Profilu musí být nastaveno rozbalování formuláře) 🆗 
- [ ] není zašedlé plus u přidávání "subject/topic", "subject/temporal" a "subject/name"

**Comment by SykoraLukas** [comment]
- [ ] Zašednutí u NDK eČlánku 
- [ ] Chybí pole pro vyplnění temporal (subject/temporal), geographic (subject/geographic ) a autor (subject/name) u eČlánku

**Comment by tumovam** [comment]
- [ ] u eČlánku už jsou pole pro vyplnění temporal, geographic a autor
- [ ] zašedlé plus u přidávání "subject/topic" u eČlánku u NDK eČlánku
- [ ] stále chybí zašednutí u temporal a name u eČlánku i u NDK eČlánku (smazaé cache, zkoušela jsem i v anonymních oknech různých prohlížečů)

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
