### ISSUE TITLE
Přesuny skenů v tabulce vs v náhledech

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#290]
Pokud v tabulce prohodím dvě strany, v náhledech se to ihned vizuálně projeví - OK. Pokud prohodím dvě strany v náhledech, v tabulce se to neprojeví nijak (dokud nedám uložit a v tabulce aktualizovat).

**Comment by albertoh** [comment]
Opraveno.

**Comment by luckajirku** [comment]
Vypadá OK.

**Comment by ZdenkaSera** [comment]
Zdá se ok.

Zavírám na základě testů a nerozporovaného návrhu na uzavření.
