### ISSUE TITLE
Ikony v panelech

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#291]
Až se bude dělat redesign, chtělo by to umravnit ikony, aby se řadily do řádků a nevznikalo při úpravě sloupců to, co je na obr.
Dál některé by vůbec nemusely být hned na ráně, třeba ikony pro “převést strany” a “změna pozice” nebo i další, které se nepoužívají tak často, by mohly být v panelu pod “...” v rozbalovacím menu.
![ikony](https://user-images.githubusercontent.com/6359479/210547398-d7f333ae-cd3e-40bc-8536-dd5eac54cb17.png)

**Comment by nezbedova** [comment]
A k tomu by bylo ještě dobré upravit šoupátka při zobrazení v Google Chrome. Tam jsou velmi tenká.

Na obrázku vlevo je Firefox a vpravo Chrome.

![obrazek](https://user-images.githubusercontent.com/13831946/210548768-57aed727-1063-49a6-acc4-6ae794211662.png)

**Comment by pkudela** [comment]
@luckajirku ano, s tim pocitam, az budou vsechni vnitrni casti hotove a predelane, pustim se do techto a podobnych uprav. Dropdown pro ikony, ktere se casto nepouzivaji je reseni, ktere pouzivam i v jinych projektech a je dle meho spravne, setri se tim misto a zvysuje se prehlednost ovladacich prvku, ktere chce mit uzivatel na ocich. Pred podobnymi upravami bych ale rad vse probral pri prezentaci jak pracujes s aplikaci, jak jsem se o tom zminil na jednom z meetingu. @nezbedova co se tyce srollbaru, tak to je vec interpretace prohlizece, nektere prohlizece vizualni zmenu definovanou v css akceptuji, nektere nikoliv, tak jako tak, je mozne scrollbary vubec neupravovat a nechat tak jak je interpretuje prohlizec, pak ale musite pocitat s tim, ze takovy scrollbar zabere vic mista. To muzeme probrat potom v ramci te prezentace. 
Pro podobne issue, ktere se tykaji opravdu jen designu, jsem vytvoril novy label "redesign", tak prosim, pri zadavani podobnych podnetu tento label pridejte a priradte i me jako resitele, abych si tato issue pak mohl vyfiltrovat a snazte se separovat kazdy podnet do samostatneho issue, lepe se v tom pak bude orientovat me i vam.

**Comment by luckajirku** [comment]
Label bereme na vědomí (dobrá barva btw). Jinak ono to tak ve starém je, že spousta věcí je schovaných - a pro práci nám to vyhovuje. Ta spousta ikonek (které jsou si leckdy podobné a pletou se, nebo evokují něco úplně jiného) přišla až s novým klientem. Pokud se domluvíme na úpravách, aby to bylo přehlednější a praktičtější, budeme jedině rádi. 
K té prezentaci - počítám, že si řekneš, až budeš chtít.

**Comment by pkudela** [comment]
@luckajirku ano, reknu, to se neboj :-)

**Comment by nezbedova** [comment]
@pkudela Děkuji za vysvětlení. U nás pracujeme ve Firefoxu. Záleží na ostatních. Jen mě to zarazilo, protože testuji v obou prohlížečích.

**Comment by luckajirku** [comment]
@pkudela ty samotné ikony ano, ale řeší se tam někde v těch nových issues i to zarovnávání?

**Comment by pkudela** [comment]
ano, ja to resil pri tech issues, ktere jsem delal, ted se ikony na leve strane zarovnavaji za sebou a vpravo zustava

<img width="387" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/2901daa2-dac7-490f-8ae3-b82a4b8e7d06">

<img width="211" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/55f7ffd1-67d9-4379-a0c2-9ab6dfc66ba0">

**Comment by pkudela** [comment]
pokud uz je prostor prilis maly, tak s tim uz nic neudelam, ale tamto chovani by uz melo byt fixnute

**Comment by luckajirku** [comment]
za nás se může zavřít

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
