### ISSUE TITLE
Omezená nabídka Objektů

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#292]
Když chci přesunout stránky mimo objekt, je omezená nabídka v Hledat - Model, v minulé verzi klienta bylo všechno.
Teď:
![obrazek](https://user-images.githubusercontent.com/24409660/210559781-e0379b40-9c29-4db8-a5c3-b2b0df2ca612.png)

předtím:
![obrazek](https://user-images.githubusercontent.com/24409660/210560101-711bc1c8-0f24-4081-b98e-f899adc37597.png)

**Comment by albertoh** [comment]
viz https://github.com/proarc/proarc-client/issues/282#issuecomment-1375219969

**Comment by SmejkalovaAnna** [comment]
Vypadá to, že to funguje....

**Comment by luckajirku** [comment]
za nás OK

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Na základě Tvého komentáře dávám otestováno KNAV.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
