### ISSUE TITLE
Chybí podbarvení textu po označení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#293]
Ve formuláři ani v xml se nepodbarví vybraný text. Např. když chci v xml vytvořit nového autora kopií.

V jádru to jde. V předchozí verzi to také jde. Testováno na Firefox i Chrom.

 v2.0.1
![obrazek](https://user-images.githubusercontent.com/13831946/210710994-c1483ebc-70df-41c8-ae97-132d5f0f7e15.png)

3.9.1-dev
![obrazek](https://user-images.githubusercontent.com/13831946/210710931-2cef0f47-0ad1-470f-a25c-fcd576ad127d.png)

 2.0.0 (draft)
![obrazek](https://user-images.githubusercontent.com/13831946/210710864-9a860aba-3dea-4879-bd26-175ecb8602e1.png)

**Comment by pkudela** [comment]
@nezbedova tusim, kde je problem, souvisi to s upravami v issue #200 aby se nezamodroval text u oznacenych polozek, opravim.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, podle mého super, zkus si to.

**Comment by nezbedova** [comment]
Modré podbarvení je skvělé. Děkuji.
