### ISSUE TITLE
Panel popisných metadat - po uložení změny je prázdný

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#294]
Když změním něco v metadatech (třeba číslo výtisku) a dám uložit, proběhne uložení, ale panel je prázdný, je nutné dát refresh, aby se formulář s popisem zas objevil.
Souvisí asi taky s touhle opravou https://github.com/proarc/proarc-client/issues/285?

**Comment by nezbedova** [comment]
Je to i při změně v xml. 
Pokud se něco změní v xml a dá uložit, tak panel s metadaty je prázdný a musí se znovu načíst. Panel s xml je vidět.

**Comment by albertoh** [comment]
Je to tak, souvisi :(

**Comment by albertoh** [comment]
Pridal jsem

**Comment by nezbedova** [comment]
Funguje. Děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
