### ISSUE TITLE
Chybí tlačítko Validovat na úrovni ročníku a výtisku

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#295]
Chybí tlačítko Validovat na úrovni ročníku a výtisku, ve starém je (a používá se).

**Comment by albertoh** [comment]
Funkcne hotove. @pkudela dodela disajn

**Comment by pkudela** [comment]
hotovo, nasazeno, pripraveno k testovani, predpokladane chovani a vzhled viz. screenshot nize:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/16591052/211289575-06786577-ccb0-44c4-b44c-72f4631dfd45.png">

**Comment by ZdenkaSera** [comment]
Zkusila jsem na úrovni čísla periodika smazat už přidělené číslo strany. Moc hezky výrazně se označí chyby, to je 👍. Ale v tomhle případě si s tím pak neporadí validace, biz obrázek
![image](https://user-images.githubusercontent.com/79305516/211305995-be30561a-06c4-44c7-8f74-c6a1deeecee5.png)

**Comment by albertoh** [comment]
To je otazka na me :)
Validuje spravnost metadat daneho objektu, nepodrazene.

Opravil jsem chovani na urovni cisla.

**Comment by ZdenkaSera** [comment]
@albertoh Děkuji, na úrovni čísla to vypadá ok, Za mne ok, vracím label "k testu" pro ostatní.

**Comment by ZdenkaSera** [comment]
Ještě k validaci na úrovni ročníku - něco tu nesedí - v klientovi mne validace chválí, v jádře pravý opak:

![image](https://user-images.githubusercontent.com/79305516/211310689-ca33f228-6671-4557-80f5-fcedac3474c9.png)

**Comment by albertoh** [comment]
Jadro nevaliduje kvuli "location". Ale je to MA. Nevim jestli chyba je v jadre nebo klientovi

![image](https://user-images.githubusercontent.com/5946836/211315478-968afa22-6d2b-48ba-87aa-369b72032781.png)

**Comment by luckajirku** [comment]
Tlačítko je a funguje. A s tou siglou a signaturou - je to správně v jádře a v takových případech má i klient zařvat.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím o finální test za nás. Dávám si to na seznam k dořešení časem, tohle není kritické, protože chyby v metadatech se kontrolují i při ukládán.. Díky.

**Comment by luckajirku** [comment]
Za nás tohle není k dořešení časem, validace by fungovat měly. Tím spíš, že to na nějaké úrovni funguje a na jiné ne, takže uživatel by si musel pamatovat, že na titulu varování dostane, ale ve výtisku si to má hlídat...

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji za upřesnění. @albertoh

**Comment by SmejkalovaAnna** [comment]
My tento typ validace při běžném zpracování NDK Periodik nepoužíváme, protože se to v podstatě zvaliduje už při zakládání. ALE souhlasím s @luckajirku, že by to tam být mělo a mělo by to fungovat. Je to další dobrá funkce systému pro někoho dalšího, kdo to rád použije nebo používá.  Můžeme se na schůzce v únoru pobavit o tom, jak řešit hlášení některých MA polí, které bychom případně chtěli....

**Comment by luckajirku** [comment]
> ... Můžeme se na schůzce v únoru pobavit o tom, jak řešit hlášení některých MA polí, které bychom případně chtěli....

jen to propojím - k validacím MA polí ve výtisku je ještě jedno starší issue tady: https://github.com/proarc/proarc-client/issues/124

**Comment by ZdenkaSera** [comment]
Mám už oboje na seznamu, příští týden půjde mail s přípravou.

**Comment by ZdenkaSera** [comment]
@SykoraLukas společně s reuired podle jádra

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, dle domluvy se ptám na stav - tohle zřejmě není k testu?

**Comment by SykoraLukas** [comment]
Doplněny Required pole podle starého klienta.

**Comment by ZdenkaSera** [comment]
Na schůzce zavíráme, chyby z provozu do nových issue kvůli přehlednosti.
