### ISSUE TITLE
Nevalidní strana není označená

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#297]
Po validaci naskočí tabulka s počtem nevalidních objektů, ale v seznamu nevidím, které strany to jsou.

![obrazek](https://user-images.githubusercontent.com/13831946/210728418-b6a9fcf5-51bd-4e8d-be36-cd38274cb19b.png)

Jádro:

![obrazek](https://user-images.githubusercontent.com/13831946/210728233-b52b88a1-a629-4c1b-a694-1229c734e717.png)

V předchozí verzi to také není.

Šlo by to, prosím, nějak vyznačit?

**Comment by ZdenkaSera** [comment]
@albertoh Není tohle k testu? Podle mých testů je to ok, úprava svezla s https://github.com/proarc/proarc-client/issues/295

**Comment by albertoh** [comment]
jj, je k testu. Uz se ztracim v tech labelech

**Comment by nezbedova** [comment]
Nevalidní strana je označená. děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
