### ISSUE TITLE
Nelze přesunout strany do jiného ročníku periodika

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#298]
Při snaze přesunout stránky periodika jinam než na stejnou úroveň nahlásí klient ProArcu chybu. A to jak u nově vzniklého periodika, tak u již vyexportovaného. Týká se přesunu jedné i více stránek. Zkoušela jsem přesun v rámci stejného titulu i do jiného titulu periodika, hlásí stejnou chybu. Přesun hlásí chybu i u starého klienta.

Klient Verze 1.1.1 (26.5.2022)
Jádro Verze 3.8.3-dev, Build 20221104121835
 
![PA_klient_chyba_presun_stranek_PER](https://user-images.githubusercontent.com/8912422/210743535-c240999a-f54a-4a20-a1b6-fe8db415deb0.jpg)

**Comment by ZdenkaSera** [comment]
@katerinasirova Nebude problém v tom, že chcete stranu přesunout na místo, kde nemá být? Zkuste kouknout sem #99

**Comment by luckajirku** [comment]
A pokud ale ukládáš do čísla periodika, tak to funguje, ne? Ono při prvotním uložení bohužel jde uložit stránky pod titul perodika, ale dál se to pak už řídí podle těch povolených vazeb. A tady to ukládáš na místo, kam nemáš.

**Comment by katerinasirova** [comment]
Díky, vyzkoušeno. Takže prvotní uložení mi umožní uložit stránky přímo pod titul, ale potom si je už nemůžu přesunout pod ročník. Kolegyně si takto rozhazuje nejdřív stránky pod ročníky a potom si vytváří čísla. Tohle byly doimportované stránky, proto ji už nešly přesunout. Díky za vysvětlení. Vyřešeno.

**Comment by ZdenkaSera** [comment]
" ... při prvotním uložení bohužel jde uložit stránky pod titul perodika"  - chceme tohle řešit a zakázat?

**Comment by katerinasirova** [comment]
Optám se u nás na zpracování, jaké by to mělo pro ně následky, ale jinak myslím, že to dává smysl, aby se hlídaly i vazby při ukládání stran do úložiště, když pak jako v tomto případě nemůžeme s těmi stranami nic dělat. A při validaci by to stejně nahlásilo chybu. Jde jen o to, jestli ještě někdo nepoužívá modely úplně přesně podle standardu, podobně jak to bylo u STT a NDK. Za nás zjistím a dám vědět.

**Comment by ZdenkaSera** [comment]
Jasně, děkuji za připomenutí.

**Comment by ZdenkaSera** [comment]
zuavírám na základě návrhu autora issue. Dál v issue #215
