### ISSUE TITLE
Nekonzistence v názvech modelů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#299]
Tohle odkládám už delší dobu - nejde o chybu funkčnosti, jen dotaz na kosmetiku. Názvy modelů v horním a dolním okně vyhledávací obrazovky se liší - chceme to sjednotit nebo to nikomu nevadí? Děkuji za reakci.

Např.
- NDK Příloha monografie / NDK Příloha
- STT Svazek monografie / STT Svazek 
- NDK Svazek eMonografie / NDK Svazek

**Comment by albertoh** [comment]
Opraveno. Bylo to zpusobeno starym disajnem. @pkudela ma to v planu predelat komplektne

**Comment by ZdenkaSera** [comment]
Děkuji, nenašla jsem protipříklad, tak to zavírám, protože nikdo další nereagoval.
