### ISSUE TITLE
řazení výsledků vyhledávání (#416)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#30]
Bylo by možné přidat řazení výsledků vyhledávání ve správě digitálních objektů podle abecedy ve sloupci popis?
Když máme v ProArcu více objektů, se kterými opakovaně pracují různí uživatelé, tak už to začíná být docela nepřehledné.

**Comment by honza-rychtar** [comment]
Výsledky už jdou řadit podle všech sloupců

**Comment by tumovam** [comment]
Ve v2.3.2 nefunguje **řazení ve sloupci Název**. Předpokládám, že řazení by mělo být abecední (A-Z, příp. Z-A), nebo je tam jiný klíč?

Příklad z masteru.in.dev:
![řazení](https://github.com/user-attachments/assets/e9699084-2c32-4222-958f-00745988e222)

Testováno i lokálně s obdobnými výsledky. Test modelů: monografie vč. STT, periodika, články.  Nemyslím si, že je chyba v "titleInfo/nonSort". 

Sloupce Vytvořeno a Upraveno seřadí výsledky vyhledávání správně. ✅

**Comment by tumovam** [comment]
Abecední řazení už na masteru funguje ✅ . Nejspíše souvisí s _"Pozn: Musí se změnit jak soubor managedSchema tak soubor solrConfig, do kterého se přidala podpora pro správné abecední řazení."_ v https://github.com/proarc/proarc/issues/1734#issuecomment-2493828078 ?

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
