### ISSUE TITLE
Nelze přesunout objekty

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#300]
Zkusila jsem přesunout strany od jedné STT monografie k jiné a pak STT monografii (3e5cc676-7fc7-482b-882e-3f1b50f53840) pod STT vícedílnou mono (920a1b3b-9824-49c3-8613-5acb1201fedb) - nelze:

![image](https://user-images.githubusercontent.com/79305516/211328656-6aa95070-35b1-4896-8560-e7a9ec8e0fd9.png)

**Comment by ZdenkaSera** [comment]
Nově importované skeny bylo možné přiřadit k nadřazenému objektu, to je ok.

**Comment by albertoh** [comment]
Nemuzu reprodukovat. Jake monografie?

**Comment by ZdenkaSera** [comment]
Pod vícedílnou STT monografii 920a1b3b-9824-49c3-8613-5acb1201fedb jsem zkoušela přesunout  STT monografii 3e5cc676-7fc7-482b-882e-3f1b50f53840.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem znovu - STT monografii f10d4996-d320-4f50-80b1-dfcc33bc95ae chci přesunout pod STT vícedílnou monografii 9acdee0b-2a5c-453e-b283-6b1b6287bf6b (Specula physico-mathematico-historica ...). Chyba trvá.
Svazek pod vácedílnou SKK mono lze ale založit přes "+", tak byl založen podřízený objekt be41ccea-d364-4e61-8e5b-6447e9bb1c2b


![image](https://user-images.githubusercontent.com/79305516/216958457-fcc0dbc3-0bfd-4fd2-b054-c0f191f34621.png)

Založeno přes "+":
![image](https://user-images.githubusercontent.com/79305516/216959699-d2af3cd0-f903-40bc-add4-5a87c39c69ab.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by albertoh** [comment]
Ted jsem to presunul bez problemu  uuid:0c124488-92c8-4ce8-b9b4-e7f7c016ce94  (nemel nadrazeneho) do NDK vícedílku "test" (uuid:a8893f8a-2a47-4cf9-a697-0db33d2c34a4)

Jak jste se k chybe dostali?

**Comment by ZdenkaSera** [comment]
Teď se mi to už taky povedlo - zjistila jsem, že při dopoledním pokusu se svazek také uložil, ale zároveň jsem dostala chybové hlášení a funkce "přejít na objekt" mne do něj nepřepnula, tak jsem uložení neověřila. Tedy děkuji, navrhuji k uzavření.

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, zase s to nějak rozbilo - skeny nově naimportované lze přiřadit pod nadřazený objekt, to je ok. 
Ale pokud mám už založenou např. monografii, pod vícedílnou monografii ji nelze přidat.  Ať má monografie přiřazené strany nebo ne, nabízí se okno pro zrušení vazby, kde moje monografie sama figuruje jako nadřazený objekt.

![image](https://user-images.githubusercontent.com/79305516/232776119-22697eea-f9fe-4826-8ca0-03fed8eeb0a9.png)

**Comment by ZdenkaSera** [comment]
Tohle se zatím neposunulo, objekty (kromě stran) pořád nelze přesunout. Nová testovací data na Inovatice: 
- NDK monografii **9bb210dd-690b-41ce-bdf3-a04a8891098a** nelze přesunout pod vícedílnou monografii **2e089677-e699-499b-9882-80ab1d4d68f4**

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto u Periodik to funguje, u monografií to nefunguje.... nic to neudělá....

**Comment by ZdenkaSera** [comment]
@albertoh Znovu jsem zkoušela přesunout monografii pod vícedílku -  stále nelze.

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
Funguje!!!

**Comment by ZdenkaSera** [comment]
Přesun je možná i u STT

**Comment by ZdenkaSera** [comment]
Mám omylem přiřazenou NDK moo pod vícedílkua chci jen zrušit vazbu, ne ji přesunout jinam. Tlačítko pro zrušení vazby někam uteklo (na obrázku nahoře je máme) @albertoh prosím, vrátil bys je? Děkuji.

![image](https://github.com/proarc/proarc-client/assets/79305516/23e3a6ad-803c-43b8-bda9-0cb12384235d)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prosím, jak rychle bys tohle mohl opravit? Nepotřebujeme to urgentně, jen nechceme pouštět do verze jasnou chybu. V případě potřeby to jde udělat v jádře. Díky.

**Comment by ZdenkaSera** [comment]
@katerinasirova Díky za potvrzení, @pkudela díky za štítek, tady to prio je - ;-)

**Comment by pkudela** [comment]
@ZdenkaSera ten stitek je docasny, hlavne pro nas a Albertem, abychom vedeli na co se zamerit a rychlo to vyfiltrovat.

**Comment by ZdenkaSera** [comment]
@pkudela Jojo, tak jsem to brala, ten díky platí ...

**Comment by albertoh** [comment]
@ZdenkaSera vazbu lze zrusit pokud otevres ten dialog z toho objektu.

**Comment by ZdenkaSera** [comment]
@albertoh Jasně, jde to - předpokládala jsem, že zrušení vazby lze udělat z úrovně vícedílky, což je špatně, vždycky musím začít z editace podřízeného objektu. Díky za trpělivost.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
