### ISSUE TITLE
Hledat - závorka za názvem modelu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#301]
Za názvem modelu v úložišti se teď objevuje závorka.

![zavorkymodel](https://user-images.githubusercontent.com/6359479/211535987-d9aa5f47-a2d0-49bf-bdb2-d269384c877d.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
jo, závorka jako daň za to, že přibylo odlišení lichých a sudých řádků:-)? Už se těšíme, až to bude i jinde, hlavně v importu...
Každopádně závorka je pryč, dávám k zavření.

**Comment by pkudela** [comment]
@luckajirku nene, neslo jen o zobrazeni sudych a lichych radku, to jsem jen doplnil pro lepsi orientaci, ale prepsani celeho kodu. Tabulka byla pred tim generovana jako div elementy s pevnymi velikostmi, coz v kombinaci se scrollovanim melo za nasledek, ze sloupce v hlavicce nebyly zarovnene se sloupci v obsahove casti viz. screenshot. Nyni se generuje jako table elementy tak jak by tabulka mela byt dle meho generovana.

stare zobrazeni a spatne zarovnane sloupce hlavicky a obsahu
<img width="269" alt="image" src="https://user-images.githubusercontent.com/16591052/211631334-ec65633f-bc51-46e9-89a9-aba04e052502.png">

soucasne zobrazeni, spravne zarovnane sloupce
<img width="299" alt="image" src="https://user-images.githubusercontent.com/16591052/211631517-f5c55859-5270-4347-b8db-dbe74801d584.png">

Az se bude resit design globalne, tak tech zmen bude mnohem vic.

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
