### ISSUE TITLE
Hledat - nastavení sloupců v horní tabulce

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#302]
Bude možné pak upravit i horní část tabulky v úložišti, aby si člověk mohl nastavit, které sloupce chce v hledání vidět? Nikde v issues jsem to nenašla, ale třeba jen blbě hledám.

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/212333481-b26b7d7c-4a99-40a5-9150-1694f983703c.png)

**Comment by luckajirku** [comment]
Aha, já to myslela nejdřív jako dotaz (protože se ztrácím v tom, co nejde zatím kvůli Akubře a co není z jiných důvodů), s tím, že se pak třeba pobavíme o tom, kde/jak by se to mělo nastavovat. Teď je spodní půlka nastavitelná v profilu, kdežto ta horní na liště, což je uživatelsky trochu nepraktické. 
Pak se teda ještě domluvíme, jestli by to mělo být jako ikona na liště (a jestli viditelně, nebo v nějakém skrytém výběru těch méně často používaných funkcí), nebo stejně jako to nastavení spodní půlky přes Profil/Nastavení.

**Comment by ZdenkaSera** [comment]
Přimlouvala bych se tady ty předělávky nekomplikovat - takto je to trochu nekonzistentní, ale nejsou to funkce, které člověk potřebuje použít denně/často. Každý asi bude chvilku ladit, co mu nejvíc vyhovuje, ale pak to nejspíš nebude pořád měnit...

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, co si o tom myslíte? Díky.

**Comment by katerinasirova** [comment]
Za mě souhlasím s tím se na schůzce domluvit, abychom to neměli nekonzistetní.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Já také souhlasím s tebou Zdenko.

**Comment by ZdenkaSera** [comment]
Díky všem. 

Issues se štítkem "otestováno s výhradami" zůstávají otevřená k diskusi

**Comment by SykoraLukas** [comment]
Prosím vývojový tým o specifikaci, co má být v nastavení uživatele a co na liště.

Hledat - seznam sloupců v tabulce, sloupce ve vazbách, sloupce ve stromě
Import - seznam sloupců v tabulce, sloupce v přehledu všech stránek konkrétního

**Comment by luckajirku** [comment]
stručně: 
**Hledat** - tabulka i strom - **nastavení přes Profil**
**Vazby** - tabulka i strom - **ikona na liště skrytá v dropdown menu**
**Import** - tabulka - **ikona na liště skrytá v dropdown menu**

Hledat: 
- výběr sloupců v tabulce v horní části - nastavitelný přes Profil. (Nastaví se jednou a pak už s tím člověk pracuje, málokdy potřebuje změnit volbu. Na liště to tak zbytečně zabírá místo.)
- výběr sloupců ve stromě v dolní části obrazovky - také nastavitelný přes Profil. (Nastaví se jednou a pak už s tím člověk pracuje, málokdy potřebuje změnit volbu. Na liště to tak zbytečně zabírá místo.)
 
Vazby:
- tabulka - tlačítko na výběr sloupců v liště, ale skrýt pod jedno s dalšími méně často používanými tlačítky (viz https://github.com/proarc/proarc-client/issues/291)
- strom - zatím tam není lišta, ale až tam bude, tak stejné chování jako tabulka výš - tlačítko skrýt v dropdown menu

Import: 
- tabulka - stejně jako ve vazbách - skrýt v dropdown menu

**Comment by nezbedova** [comment]
Souhlasíme s @luckajirku

**Comment by ZdenkaSera** [comment]
@albertoh  je to tvoje :-)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prosím, bude tohle ve verzi k testování od pondělka? Děkuju ...

**Comment by albertoh** [comment]
To nestihnu... Ja bych to delal spolu s #331 
Tj, to nastaveni sloupcu by melo byt podle modelu

**Comment by ZdenkaSera** [comment]
Pokud se má realizovat společně s https://github.com/proarc/proarc-client/issues/331, dávám i tady návrh na rozšíření.

**Comment by luckajirku** [comment]
tady si jen odložím poznámku, že se to nakonec udělalo jinak než podle https://github.com/proarc/proarc-client/issues/302#issuecomment-1447733705 - že je teď vše v nastavení přes Profil.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
