### ISSUE TITLE
NDK článek - chybí možnost vyplnit `pageNumber`/`pageIndex`

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#303]
Ve formuláři pro NDK článek chybí v části "informace o části" --> "Rozsah" rozlišení rozsahů podle indexu (`pageIndex`) a stránkování (`pageNumber`).

![image](https://user-images.githubusercontent.com/57805328/211581812-21a9866f-9a3f-4362-9191-84d5b37d6673.png)

oproti tomu ve starém rozhraní: 
![image](https://user-images.githubusercontent.com/57805328/211582050-1eee6379-64ff-4370-90ff-10894fe7fee8.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Funguje, díky!

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
