### ISSUE TITLE
NDK periodikum - chyba při zakládání

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#304]
Kolegyně ze zpracování časopisů narazily při testování klienta na problém se založením periodika. Možná souvisí s #248 a https://github.com/proarc/proarc/issues/1501, ale dělalo mi problém ho reprodukovat, tak je třeba problém ještě někde jinde.

**postup:**
- `nový objekt` - NDK periodikum - načíst metadata z katalogu
- vyberu KNAV AV CR Periodika - Název - "Střed"
- vyberu záznam s titulem "Střed / Centre"
- `vytvořit objekt` - otevře se editace nového objektu
- V první části _Uložení_ vyberu místo uložení "Knihovna AV ČR", doplním signaturu "AP 102"
- Dám `Vytvořit a přejít do objektu`
- Objeví se hláška o nevalidních datech, dám `Uložit`

![image](https://user-images.githubusercontent.com/57805328/211589798-8dce32d9-7541-4643-8872-78f681f95c80.png)

V jádře obdobný postup funguje. Testováno na Klient: verze v2.0.1 (10.01.2023)J ádro: verze 4.0-dev - build 20230110113908 

Díky!

**Comment by luckajirku** [comment]
A když odmažete ty další výskyty physicalLocation, kde jsou jen samotné url, tak to taky háže chybu?

**Comment by ZdenkaSera** [comment]
@kerschfilip Zkusila jsem na inovatice - výmaz 2 nadbytečných location pomohl, uloženo bez chyby. navrhuji uzavřít.

**Comment by kerschfilip** [comment]
pokud nechám jeden výskyt uložení a v něm siglu, signaturu a URL, tak mi to pořád hází chybu. Když URL odmažu, tak je to OK. 

Je asi otázka, jestli by takhle chyba měla jít překonat, nebo by se mi alespoň měla vrátit nějaká relevantní chybová informace místo anglické hlášky o parsování XML

**Comment by kerschfilip** [comment]
Tak ještě jednou a lépe, snad se mi buď povede vysvětlit, kde vidím problém, nebo mi vy vysvětlíte, co dělám špatně :-)

Při zakládání toho periodika nechám jeden výskyt Uložení a v něm signaturu a URL (stáhne se to takhle z katalogu + je to podle standardu povolená kombinace). Výsledek je, že to nejde uložit, viz chybová hláška nahoře. Když smažu to URL, tak to uložit jde. 
![image](https://user-images.githubusercontent.com/57805328/215789686-ee8a078b-3636-4f4c-bdaa-4ea301a3d254.png)

Navíc, když se v editaci toho periodika potom k Uložení vrátím a URL zpět doplním, tak už to uložit jde 🤯

**Comment by ZdenkaSera** [comment]
Znovu jsme zkoušeli, tohle se zatím nikam neposunulo, chybové hlášení trvá:

![image](https://user-images.githubusercontent.com/79305516/217201919-81d6bd0e-c244-4a6d-9c58-b161f34df522.png)

**Comment by luckajirku** [comment]
Ten záznam z vašeho katalogu nemá signaturu v 910 b. Pokud stáhnu z katalogu záznam, který signaturu má (plus pak má i url v 856), tak sice upozorní na chybějící signaturu (standardní validační hláška), ale založit mě to nechá. 
Skoro bych řekla, že rozdíl je v tom, že při chybějící signatuře na vstupu se to snaží dát do jednoho location, kdežto když ve stahovaném záznamu signatura je, tak to udělá extra výskyt location pro signaturu a další pro url:

![url](https://user-images.githubusercontent.com/6359479/217215107-37cac9f5-f1e5-4f1c-a356-ce6b6258acee.png)

**Comment by ZdenkaSera** [comment]
Máte pravdu, že naše záznamy v 910 signaturu nemají, zatím se nám tedy nestahuje a jsme zvyklí ji doplnit ručně (standardní hláška, kterou lze překonat, jen svítí červeně prázdné pole pro signaturu. Pokud tedy není vyplněné pole 856, vytvoří se nám jeden element location a chce signaturu - to je ok.
Jakmile ale stahujeme záznam, kde je 856, automaticky se vytvoří 2x location, kde v prvním chybí signatura a ve druhém (s url) chybí sigla i sigantura. Ten obrázek nahoře je po ručním sjednocení, kdy jsme siglu, signaturu i url přesunuli do jednoho location a druhé smazali - myslíme si, že tohle by mělo jít uložit. I když v reálu url nepotřebujeme a můžeme je odmazat.

**Comment by luckajirku** [comment]
No jde asi o to, jestli se to takhle chová správně nebo ne. Ve výskytu pro url by neměla být pole pro siglu a signaturu, otázka je, jestli to odlišné chování v jednotlivých výskytech, pokud ani jeden neobsahuje ty povinné údaje (sigla+signatura), jde v šabloně ošetřit. Jestli se PA všemožně nesnaží to aspoň někam dostat, protože ví, že potřebuje alespoň jeden výskyt, kde ta M pole vyplněná budou:-).
Btw ten převod signatur do pole 996 u vás zatím neproběhl? viz https://github.com/proarc/proarc/issues/411

**Comment by kerschfilip** [comment]
problém se objevuje jen u několika málo periodik - spočívá v tom, že data z katalogu se nám stáhnou tak, že pokud se doplní signatura do prvního výskytu physicalLocation, vznikne XML nevalidní vůči MODS. Lze vyřešit jednoduchou ruční úpravou při zakládání periodika. Navrhujeme tedy dále to neřešit. Díky!
