### ISSUE TITLE
Přesun stran v tabulce myší na určitou pozici

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#305]
V tabulce se teď při přesunu stran myší nedá přesunout na přesné místo, kam potřebuju. Nebo teda dá, když si to předem spočítám:-) - vždy se ten počet pozic, o které se posouvám, zdvojnásobí. Posouvám o jednu níž, hodí mi to o dvě, posouvám o dvě, hodí mi to o 4 atp. 
V náhledech přesuny fungují jak mají, týká se to jen tabulky.

**Comment by albertoh** [comment]
Opraveno

**Comment by nezbedova** [comment]
Myší jde přesunout v náhledu, mřížce i řádku.

**Comment by luckajirku** [comment]
vypadá to OK, jak v importu, tak v úložišti

**Comment by katerinasirova** [comment]
za nás OK

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
