### ISSUE TITLE
Správa dávek - defaultně Načteno

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#306]
Ve Správě dávek bychom uvítali, kdyby byl defaultně nastaven ve výběru stav Načteno místo Vše. Jako je to ve starém - dokud to ručně nepřehodím na jiný stav, vidím jen ty načtené dávky. To je pak otázka konfigurace toho kterého ProArcu?

**Comment by nezbedova** [comment]
S @SmejkalovaAnna souhlasíme s @luckajirku. Také by nám více vyhovovalo přednastavení Načteno.

**Comment by albertoh** [comment]
Hotovo

**Comment by luckajirku** [comment]
za nás OK

**Comment by SmejkalovaAnna** [comment]
za nás taky OK

**Comment by ZdenkaSera** [comment]
Zavírám na základě testů a nerozporovaného návrhu na uzavření.
