### ISSUE TITLE
Podivné zobrazení Údaje o metadatech

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#307]
Z vazeb jsem šla do  metadatového popisu na úrovni titulu. Všechny rámečky jsou hezky rozložené a jejich šíře se mění podle posunu. Až na poslední rámeček. Údaje o metadatovém popisu, ten je jiný. Ničemu to nevadí, běžně ho nepoužívám, ale pro úplnost to sem dávám.

![obrazek](https://user-images.githubusercontent.com/13831946/212662689-6a36080e-baad-4b75-9351-0af5377f9f6e.png)

**Comment by ZdenkaSera** [comment]
Komentář jsem už psala, ale buď je v jiném issue nebo jsem jen neuložila ... @nezbedova Martino, takhle se to při velkém zúžení panelu chová na těch místech formuláře, kde jsou použity vnitřní rámečky k ohraničení souvisejících údajů,  např. u autora. 

![image](https://user-images.githubusercontent.com/79305516/214602995-cd317fa2-fdcd-418f-8bc6-db81e9abd214.png)

**Comment by ZdenkaSera** [comment]
issue jako námět vylepšení v rámci redesignu - @pkudela viděl na schůzce, akce ze strany uživatelů zatím netřeba.

**Comment by nezbedova** [comment]
Testováno ve verzi Klient: verze v2.2.0 (30.11.2023)Jádro: verze 4.1.1-SNAPSHOT - build 20231205112206

Rámečky se drží a jsou přehledné až do zúžení na 15 cm (to je tak málo, že to asi nikdo nepoužívá).

Pokud ostatní souhlasí. navrhuji zavřít.

**Comment by katerinasirova** [comment]
Tento problém souvisí spíš s designem formulářů obecně - ten se bude řešit až v příštím roce. Ale problém by neměl zapadnout. nechávám na vás, jestli prolinkujeme na sběrné issue k formulářům nebo zavřeme a jen poznamenáme info do sběrného issue.

**Comment by ZdenkaSera** [comment]
@katerinasirova Díky, Katko. Chtěla jsem link do sběrného issue https://github.com/proarc/proarc-client/issues/446 přidat, ale je tam už v zadání od Tebe. Tím se to neztratí. @nezbedova
