### ISSUE TITLE
STT - nevaliduje při připojení k objektu

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#308]
Pokud nevyplním číslo stránky, nedám validovat a hned připojím pod objekt, tak se neobjeví chyba, ale uloží se to pod objekt bez čísla strany.

![obrazek](https://user-images.githubusercontent.com/13831946/212879447-07fb1eda-c1e4-48e2-b7c7-1c4213fb4b04.png)

Exportovat nelze - tam je chyba - to je správně, ale pozdě. 

V jádru je validace, která zabrání uložení stran pod objekt, pokud chybí číslo strany.

![obrazek](https://user-images.githubusercontent.com/13831946/212879947-30da8f12-41f1-4f62-ac3a-8b76ef81c49a.png)

**Comment by ZdenkaSera** [comment]
Netýká se jen STT - v importu se validace nespouští ani pro NDK monografie. Periodika jsem nezkoušela.

**Comment by SykoraLukas** [comment]
V importu před uložením zkontrolovat, že všechny stránky obsahují všechny povinná pole (číslo, index, typ).

**Comment by albertoh** [comment]
Pred pokracovanim se spusti validaci stran. Pokud nejsou validni, objevi se varovni dialog.

![image](https://user-images.githubusercontent.com/5946836/218754620-ace2cbcb-e7a6-4ede-a749-8735ca85d6a6.png)

**Comment by luckajirku** [comment]
Jako není to nepravdivá hláška:-), ale nešlo by to zpřesnit? Jako u jiných validací, kdy to napíše Počet nevalidních objektů X z Y.

**Comment by albertoh** [comment]
Upraveno

![image](https://user-images.githubusercontent.com/5946836/218963146-4ff1fa1d-d6cf-49be-91b6-9417abefc319.png)

**Comment by nezbedova** [comment]
Funguje. Hláška po zadání Pokračovat i hláška, když se dá validovat. 
Zbývá už jen drobný estetický detail, aby všude, kde není validace byl jeden znak s vykřičníkem. Za mě trojúhelník.

Teď to vypadá podivně.

![obrazek](https://user-images.githubusercontent.com/13831946/218973256-45f30c58-d4cd-42fa-aed2-d132a9671d64.png)
