### ISSUE TITLE
Validace v importu - rozdílné ikony tabulka vs náhledy

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#309]
Jedna malá kosmetická - při validaci v importu je u náhledů použitá jiná ikonka než v tabulce a v okně s hláškou (viz obr.). V úložišti jsou všude stejné (osmiúhelníky).

![ikony_validace](https://user-images.githubusercontent.com/6359479/214521395-397a5827-1268-49e1-9faa-cc8693e32e2e.png)

**Comment by pkudela** [comment]
@luckajirku sjednoceno, jeste jsem pritom fixnul oznaceni, respektive neoznaceni  cervenym pozadim radky, ktere jsou sedive, tam to ty liche radky prebijeli, je to patrne i z toho screenshotu.

**Comment by luckajirku** [comment]
@pkudela asi ne úplně, teď s tou https://github.com/proarc/proarc-client/issues/308 jsou u náhledů zas trojúhelníky.

**Comment by pkudela** [comment]
> @pkudela asi ne úplně, teď s tou #308 jsou u náhledů zas trojúhelníky.

hm, podivam se na to, nicmene pani @nezbedova by rada trojuhelniky, tak prosim, nez se na to podivam, domluvte se, jakou ikonu tam chcete, na vyber jsou tyto -> https://fonts.google.com/icons?selected=Material+Icons&icon.query=warning

Trojuhelnik, kulata, nebo osmiuhelnik s vykricnikem.

**Comment by luckajirku** [comment]
Mně je to jedno, jde mi o to, aby to bylo jednotné. A dostatečně výstražné, což trojúhelník je ještě víc než osmiúhelník. Takže klidně trojúhelník.

**Comment by pkudela** [comment]
Jasne, cili sjednotim to a dam tam trojhuhelnik jako hrom :-)

**Comment by nezbedova** [comment]
@pkudela @luckajirku Děkuji za pochopení a za úpravu.

**Comment by pkudela** [comment]
Ahoj @luckajirku , tak ted to snad je uz vsude sjednocena na trojuhleniky, vcetne radku viz. screenshoty nize, ty jsou take obarvene vsechny, ktere jsou nevalidni, prosim o test a pripadne zavreni.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/16591052/225087850-d6e264c6-2ea3-4db6-b021-9e88fa2337f9.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/16591052/225087971-189f8c6e-3791-404f-afd7-b46513b96791.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/16591052/225088261-4cadca77-7d7d-4998-8c53-60a9ba2800c3.png">

**Comment by pkudela** [comment]
Testovano na tomto uuid -> https://proarc.inovatika.dev/repository/uuid:6277b8c9-adcc-42ed-8fcf-f704cb7f3ba0 & nasazeno na serveru k testovani.

**Comment by nezbedova** [comment]
Otestováno. za nás OK.
