### ISSUE TITLE
RDflow:UI “Rostoucí” poznámka (#386)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#31]
Formulář Záměr pole Poznámka bude mít rostoucí velikost v závislosti na obsahu.

**Comment by luckajirku** [comment]
Tohle jsme chtěli před lety, kdy jsme mysleli i my, že budeme RDFlow používat. Teď je to spíš na @nezbedova - jestli to chcete, nebo jestli se to má zavřít, ať to tu kdyžtak nestraší zbytečně. 
(přidávám pro jistotu odkaz na původní issue, kde je k tomu víc https://github.com/proarc/proarc/issues/386)

**Comment by ZdenkaSera** [comment]
@nezbedova Prosím okomentovat.

**Comment by nezbedova** [comment]
Za DC se to může zavřít. Rostoucí poznámku nepotřebujeme.
