### ISSUE TITLE
Design klienta - přehledové issue

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#310]
Issue k zaznamenání komentářů k designu, které se objevily při řešení/testování funkčních issues.

**Comment by ZdenkaSera** [comment]
Podbarvení nevalidních stran "označení nevalidních stran po dokončení validace - kromě výstražného symbolu, že je objekt nevalidní je také podbarvený červeně, ale u prvních třech objektů jsou podbarveny všechny a poté ob jeden" - #251

**Comment by luckajirku** [comment]
> Podbarvení nevalidních stran "označení nevalidních stran po dokončení validace - kromě výstražného symbolu, že je objekt nevalidní je také podbarvený červeně, ale u prvních třech objektů jsou podbarveny všechny a poté ob jeden" - #251

Tady bych to asi upřesnila, ať si tu nejasnost nepřenášíme do dalšího issue. Nejde vždy o první tři objekty, ale o to, že to zvýraznění není vidět u řádků, které jsou kvůli zpřehlednění šedé, kdežto ty jakože bílé se zvýrazní. A u těch šedých se to ukáže  ve chvíli, když člověk právě na tom řádku stojí (což je vidět i na tom obrázku, který Katka dávala).

**Comment by nezbedova** [comment]
Upravit řádky ve všech roletkách. Zmenšit mezery.

**Comment by pkudela** [comment]
@nezbedova jestli mate na mysli to co je zmineno v issue #325 tak to je provedeno globalne pro vsechny dropdown a je to nasazeno na serveru k testovani. Jinak prosim vsechny, pro kazdy navrh tykajici se designu zakladejte sepratni issue, az se budu designu venovat jako celku, tak se mi v tom bude lepe orientovat. Dekuji

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, myslis, ze bys toto issue mohla zavrit? Nektera issues zminena zde jsou jiz zavrena a me to trochu mate. Ja se stejne ridim predevsim pridelenym labelem "design" u kazdeho konkretniho issue a mit pro kazdy navrh designu konkretni komponenty separatni issue je pro je prehlednejsi, nez mit jedno issue, kde je nekolik ruznych issues zmineno. Dekuji ;-)

**Comment by ZdenkaSera** [comment]
@pkudela Jasně :-)
