### ISSUE TITLE
NDK formuláře - physical location / sigla

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#313]
Dotaz do pléna - z jakého důvodu se vlastně udělala změna v NDK formuláři v Physical location, že se tam už neukazuje sigla, ale jen přepsaný název instituce a pro kontrolu sigly se musím podívat do xml? 
Když se stejně musí používat kontrolovaný slovník a volná tvorba nejde, v čem je ta výhoda?

**Comment by ZdenkaSera** [comment]
zobrazovat jen siglu.

Domluva: bude EN verze + hybridní cs verze se schová

**Comment by albertoh** [comment]
Prozatim, nez udelame hybridni, vratil jsem do roletky i siglu pred nazvem

![image](https://user-images.githubusercontent.com/5946836/218999890-9482a8e3-6917-4ed4-8bbf-2fca18917954.png)

**Comment by luckajirku** [comment]
A další otázka je, jestli tam má být ta roletka, dřív to bylo normální pole. Pro stahování záznamů z katalogu nedává smysl - byl to požadavek od těch, co vytváří záznamy bez katalogu? A pokud to zůstane takhle - půjdou aspoň v konfiguraci nastavit jen ty sigly, které ta instituce používá, a zbytek aby se vůbec nenabízel? Vím, že preferované sigly má uživatel nahoře, ale proč tam mít všechno a riskovat, že se někdo uklepne - a že to jde snadněji při hledání řádku než při ručním přepisu sigly...

**Comment by albertoh** [comment]
Prosim o vyjadreni ostatnich

**Comment by nezbedova** [comment]
U nás preferujeme zapisovací pole. Pokud zakládám záznam ručně, tak si tam siglu doplním. Pokud je těchto záznamů více, tak ji kopíruji pomocí klávesové zkratky. Roletka zdržuje a hrozí chyba. U stahovaných záznamů to nemá smysl.

I

**Comment by ZdenkaSera** [comment]
@erikamirova @katerinasirova Prosím, co preferujete u vás?

**Comment by erikamirova** [comment]
@ZdenkaSera My záznamy ručně netvoříme, vše stahujeme z katalogu.

**Comment by katerinasirova** [comment]
My stahujeme a pokud by z nějakého důvodu bylo třeba doplnit, raději ručně než roletka.

**Comment by luckajirku** [comment]
@albertoh vypadá to, že mezi uživateli panuje shoda - rádi bychom zpět zapisovací pole;-)

**Comment by ZdenkaSera** [comment]
závěr: volné pole pro zapsání textu. @albertoh

**Comment by ZdenkaSera** [comment]
doplnění: v konfiguraci - slovník ke kontrole - na něj proběhne kontrola při uložení objektu.

**Comment by SykoraLukas** [comment]
Nasazeno k testu u klienta (kontrolovany slovnik je ukol na jadro)

**Comment by luckajirku** [comment]
Zapisovací pole je zpět a kontrola při snaze o uložení neexistující sigly funguje. Za nás k zavření.

**Comment by katerinasirova** [comment]
Mně se na testu inovatiky podařilo uložit i neexistující siglu - ABG009.

**Comment by luckajirku** [comment]
> Mně se na testu inovatiky podařilo uložit i neexistující siglu - ABG009.

ale ta existuje

**Comment by luckajirku** [comment]
mně to neuloží...
![sigla](https://user-images.githubusercontent.com/6359479/228460615-3b66f82e-7f9c-4785-9cec-67577224a9b2.png)

**Comment by luckajirku** [comment]
jo, teď už to po odklepnutí první překonatelné hlášky vyhodí ještě tu nepřekonatelnou k sigle.

**Comment by SykoraLukas** [comment]
Takhle to mělo fungovat, že?

**Comment by katerinasirova** [comment]
Ano, nejdřív mi to vyhodilo jinou hlášku a po jejím odkliknutí - ať už potvrzení či ne, to hodilo hlášku se siglou, která už překonat nešla. Tohle je správné chování, takže za nás OK.

**Comment by nezbedova** [comment]
Otestováno na STT - nelze uložit neexistující siglu. Objeví se hláška.

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
