### ISSUE TITLE
Kramerius Export

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#314]
Přidat roletku pro instance Krameria. Seznam instancí přebírat z API (tak jako to funguje u Kramerius Export v API)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/218756539-24e02805-3692-4d1e-880d-e555f4e37c87.png)

**Comment by SykoraLukas** [comment]
API ano

**Comment by ZdenkaSera** [comment]
na schůzce zavíráme
