### ISSUE TITLE
Formuláře přepínač

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#315]
Přepínátko AACR a RDA  - předat nad formulář přepínání Pravidel Popisu. Podle vybrané hodnoty v Přepínátku zobrazit adekvátní formulář aacr / rda.

**Comment by albertoh** [comment]
@SykoraLukas pri ulozeni posilam parametr "standard" pokud ho mam
@pkudela oprav prosim radio buttony

![image](https://user-images.githubusercontent.com/5946836/218734773-94606d6e-06c5-4174-b9ce-bfd5e99ff15c.png)

**Comment by pkudela** [comment]
hotovo, nasetovano globalni chovani napric aplikaci, velikosti rb definovany ve variables, dedikovane chovani (barvy) pro toolbar

<img width="538" alt="image" src="https://user-images.githubusercontent.com/16591052/219317751-b339647f-18e3-4476-aefe-304f09cc8346.png">

**Comment by albertoh** [comment]
Neni hotovo. Jeste jadro

**Comment by ZdenkaSera** [comment]
Přepínač nezohledňuje povinnost podle pravidel  - zatím vím o chybě v  "eventType" - je teď nesprávně povinné i u AACR (nejen při přepnutí, ale i při stažení aacr záznamu z katalogu).

**Comment by ZdenkaSera** [comment]
Tak ještě upřesnění - jak píše Lukáš:: aacr záznam stáhnu, to je ok. Ve chvíli, kdy dám "uložit a přejít do objektu" se zkontroluje a ukáže chyby, mezi nimi i nevyplněný "eventType". Chybu lze ignorovat a objekt založit, stejná chyba se pak hlásí i v editaci v úložišti.

**Comment by SykoraLukas** [comment]
Podařilo se nám to nasimulovat achová se stejně, jak píšeš - řešíme.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Tahle část je ok - v aacr se eventType nekontroluje, přepnu-li do rda, tak ano. Při opětovném návratu do aacr se kontrola opět vypne. Děkujeme.
Issue nezavírám, nejsou důkladně přetestovány rozdíly mezi rda a aacr.

**Comment by ZdenkaSera** [comment]
Na schůzce zavírám, případné chyby do nových issue.
