### ISSUE TITLE
Přepínátko Peer-review

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#316]
Pro NDK ečlánky a ečlánky přidat přepínátko zda je hodnota review nebo ne. 
Přepínátko:
![image](https://user-images.githubusercontent.com/27210823/217806773-0ffb4d45-89e6-4bdb-aa50-5c898db29e08.png)

Pokud je hodnota: `<mods:genre type="peer-reviewed">article</mods:genre>` vybrat hodnotu "Recenzovaný článek", pokud hodnota není, vybrat hodnotu "Nerecenzovaný článek".

**Comment by kerschfilip** [comment]
ještě pro jistotu doplním:

- u **ečlánků** má element `genre` vypadat tak, jak je to výše, tedy: `<mods:genre type="peer-reviewed">article</mods:genre>` 
- stejné přepínatko by ale bylo potřeba i u **NDK eČlánků**, kde je ale[ podle standardu](https://standardy.ndk.cz/ndk/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf) předepsaná hodnota "electronic_article", takže `<mods:genre type="peer-reviewed">electronic_article</mods:genre>`

**Comment by albertoh** [comment]
@SykoraLukas pri ulozeni metadat api vraci prazdny genre (pro bdmarticle a ndkearticle). Podivas se na to?
Jinak prepinatko pridan. Az se opravi jadro bude hotovy.

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/220636468-6432f2b5-2563-4080-8f46-888eb0f2ea2c.png)

**Comment by ZdenkaSera** [comment]
@albertoh prozkoumá, @kerschfilip případně doplní.

**Comment by ZdenkaSera** [comment]
@albertoh Tady taky prosím - koukl bys na to, jestli to stíháte do té nejbližší verze? Děkuji.

**Comment by albertoh** [comment]
jj, pracujeme na tom. Neni to vubec jednoduche to dosahnout v soucasnem disajnu aplikace

**Comment by albertoh** [comment]
Je to na testu

**Comment by kerschfilip** [comment]
Přepínátko funguje, moc díky! Jen u ečlánku není v poli žánr (pro typ obsahu) předvyplněný ten text "article". U NDK eČlánků tam předvyplnění je. Nesouvisí to s #335? :-)

Z roletky u žánru by teď mělo být možné odebrat hodnotu "recenzováno"

**Comment by SykoraLukas** [comment]
Hodnota "Recenzováno" odstraněna

**Comment by kerschfilip** [comment]
Funguje to docela dobře, jen v tom poli `Genre` není předvyplněna ta hodnota "article", takže ji musím dopisovat ručně, měla by tam ale být automaticky:

![image](https://github.com/proarc/proarc-client/assets/57805328/2aaf8513-df76-4cdf-83d2-2e0d3b226c76)

Pozor - platí to jen pro eČlánek a pro NDK eČlánek. S tím rozdílem, že u NDK eČlánku se předvyplňuje hodnota electronic_article. Jinde se to objevovat nemá :-)

**Comment by albertoh** [comment]
@SykoraLukas pridas to pri zalozeni noveho objektu v jadru?

**Comment by albertoh** [comment]
Opraveno

**Comment by SykoraLukas** [comment]
Ještě projdu formuláře ve starém klientovi a doplním defaultní hodnoty pro všechny formuláře.

**Comment by kerschfilip** [comment]
@SykoraLukas nevím, jestli něco nedělám špatně, ale ty předdefinované hodnoty article/electronic_article se mi u eČlánků/NDKeČlánků v tom žlutě označeném poli pořád neukazuji:
![image](https://github.com/proarc/proarc-client/assets/57805328/a5304d58-d660-4ce8-9679-275208103475)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Děkuju, hodnota je předvyplněná. Ještě jsem narazili na následující problém:

když vyplním ečlánek (mám nahoře vyplněno nerecenzovaný článek) a uložím, ale pak zjistím, že jsem se překlikl a chci jen opravit na recenzovaný, tak mi to nejde uložit (ikona uložení je neaktivní). Musím sáhnout do formuláře a něco změnit, aby se tlačítko na uložení zaktivovalo

**Comment by kerschfilip** [comment]
Obdobný problém nastává obecně když mám vyplněný a uložený ečlánek (respektive asi jakýkoliv objekt) a chci v něm jen nějaké pole smazat (ne editovat), opět to nenabízí možnost změnu uložit.

**Comment by albertoh** [comment]
Opraveno, prepinatko, a mazani

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
