### ISSUE TITLE
Šířka sloupců v tabulce nastavitelná uživatelem

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#318]
Ve starém rozhraní lze nastavovat šířku sloupců v tabulkách ručně, jak uživatel potřebuje (někdo chce vidět spíš delší název a z modelu mu stačí pár prvních písmen atp.), v novém to nelze. Chybí mi to tam, tak se ptám ostatních uživatelů - používali jste nastavování šířky, chybí vám to?

**Comment by nezbedova** [comment]
Nám to také chybí.

**Comment by katerinasirova** [comment]
Taky jsme používali nastavení šířky sloupce.

**Comment by pkudela** [comment]
Na tom uz Alberto pracuje, ale nefunguje to zatim idealne, zitra na schuzce vysvetlime.

**Comment by luckajirku** [comment]
letmo jsem to zkusila - a dost tam chybí nějaké viditelné předěly mezi sloupci (to bude asi pak na design), někde je dost problém to šoupátko trefit. Někdy je přesně mezi sloupci, ale někdy jde přes tlačítko (tam kde se asi sejde blbá šířka a nezkrácený název, nevím...).

**Comment by pkudela** [comment]
@luckajirku podivam se na to, on ten default nevypadal dobre, tak jsme tam to oddeleni nedavali, funcknost je ale v poradku, ne? Zitra se na to podivam, udelam s Albertem pripadne upravy a nasadime pro dalsi test.

**Comment by pkudela** [comment]
pohral jsem si s tim, nasazeno na serveru k testovani

**Comment by pkudela** [comment]
zatim k testovani ve vyhledavani a v repozitari

**Comment by luckajirku** [comment]
oddělení čárkou super (z toho gradientní podbarvení moc nadšená nejsem, ale asi chápu, že se to má odlišit od toho plnobarevného o lištu výš)...ale OK, to je design. Jinak funkčnost vypadá dobře, jen teda když v úložišti zajedu moc doprava, tak to udělá tohle... Posunem té svislé lišty mezi panely se to většinou srovná, ale někdy taky úplně ne. 

![soupatkovpravo](https://github.com/proarc/proarc-client/assets/6359479/3eff1bf6-a3c0-4f08-8a9b-b9451de38f83)

to

**Comment by pkudela** [comment]
Ja myslel, ze ti tim gradientem udelam radost, ve starem klietnovi je gradient take, proto jsem ho tam dal :-) Je to sice design, jak pises, ale davat ho tam nemusim, chtel jsem jen, aby bylo nejak patrne, s jakym sloupcem hybes. Na ten problem se podivam.

**Comment by pkudela** [comment]
@luckajirku musel jsem koumat jak to udelat, vim, kde je problem, bohuzel bunce tabulky nelze dat minimalni delku, vyresil jsem to tim, ze orezavam text i textu v headeru tabulky, ted uz by to nemelo delat. Nasazeno na serveru, prosim otestuj.

Dotaz: moznost zmeny velikosti sloupcu ma byt ve vsech tabulkach napric aplikaci? Jde mi o to, abych s tim pocital pri sjednoceni chovani tabulek.

**Comment by kerschfilip** [comment]
@pkudela bylo by ideální kdyby možnost změny velikosti sloupců byla ve všech tabulkách napříč aplikací, pokud to nebude příliš velký problém. Díky!

**Comment by luckajirku** [comment]
Snažím se přijít na to, jak přesně to nastavování funguje, jako kdy začnou uskakovat sloupce vlevo, kdy vpravo, který sloupec zůstane stejně široký a které se změní a na kterou stranu... Zatím jsem to moc nerozklíčovala. Jakože třeba mám tři sloupce, vezmu lištu mezi druhým a třetím a jedu doleva, že rozšířím ten třetí na úkor druhého. V domnění, že lišta mezi prvním a druhým se nehne. Ale ona mi jde naproti a první sloupec se rozšiřuje, třetí sloupec se rozšiřuje, a mezi tím chudák ten prostřední není pak skoro vidět. A to mi přišlo, že tohle už se chvíli chovalo líp, ale třeba se pletu. 
Další věc pak bude ještě pamatování nastavení - tady se ani člověk nemusí odhlásit a nastavení je pryč, stačí jen obnovit. Ve starém si to pamatuje i po odhlášení.

**Comment by pkudela** [comment]
@kerschfilip zatim jsme tuto funkcionalitu udelali na 2 mistech pro testovani, pokud se schodneme, ze je to ok, tak nasadim to vsech tabulek napric aplikaci. Jen podotykam, ze strom neni tabulka, tam to udelat nelze, respektive bysme museli zkoumat, jestli to tam pujde udelat.

**Comment by SmejkalovaAnna** [comment]
Mě to nepřijde teď až zas tak hrozný.... ale asi by to chtělo to používat denně, abychom zjistili, jestli je to vyhovující....

**Comment by ZdenkaSera** [comment]
@pkudela Přidala bych se s dorazem na nutnost pohynu všech sloupců. Třetí sloupec roztahuji směrem doprava, takže všechny napravo od něj se mi zužují - to bych v zásadě čekala, ale zužují se mi i ty vlevo. Je to tím, že se snažíš zachovat nějaký poměr u ostantích sloupců a každému z nich "dopřát" nějaké procento zbylé šířky?

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji za rychlou reakci na mail!

@pkudela Petře, prosím, jak náročná  (tj. dokdy) by mohla být úprava, aby se změny v šířce sloupců chovaly stejně jako v jádře? Děkuju!

**Comment by pkudela** [comment]
@ZdenkaSera tohle opravdu nedokazi odhadnout, bude to vyzadovat laborovani, testovani, zkouseni, neni to tak jednoduche jak se na prvni pohled zda a je to spise na @albertoh. Domluvime se, kazdopadne mame toto v tuto chvili brat jako prioritu?

**Comment by ZdenkaSera** [comment]
@pkudela Pokud se nic dalšího neobjeví, tak kromě problémů v editaci (=prio1) by tohle zůstávalo jako jediný špunt na cestě k vydání verze - takže kromě té editace je teď tohle prio1. Moc díky.

**Comment by pkudela** [comment]
ok, rozumim

**Comment by ZdenkaSera** [comment]
@katerinasirova Díky za potvrzení, @pkudela díky za štítek.

**Comment by albertoh** [comment]
Nasadil jsem na server zmeny. Zkontrolujte, prosim, jestli chovani ted vyhovuje.
Aby sloupce se nastavovaly hladce, musel jsem zrusit sirku tabulky na 100%. To znamena, ze ted tabulka muze byt vetsi nez panel.
Ted se nastaveni pamatuje

**Comment by ZdenkaSera** [comment]
Zkoušely jsem s @SmejkalovaAnna, zde několik pozorování:
- pokud jeden sloupec upravuji, ostatní sloupce si pořád nedrží šířku
- poslední sloupec vpravo je pevně svázán s okrajem tabulky, jeho šířku nelze měnit a při některých kombinacích "zaleze" a nelze jej zobrazit, posuvník nepomůže - viz printscreen níže, poslední sloupec "vlastník" je skryt

Zdálo by se nám šikovnější, kdyby si sloupce držely šířku, kterou jim nastavíme a pokud některý rozšiřuji/zužuji, ty vlevo od něj by se nehýbaly vůbec, ty napravo od něj by se pouze posouvaly, aniž by se měnila jejich šířka. Ale počkejme na ostatní.

![image](https://github.com/proarc/proarc-client/assets/79305516/07983598-d111-4cdd-9ae9-d24cba9f122e)

**Comment by luckajirku** [comment]
Ale už je to na dobré cestě:-)...
- to odskakování tam je jen někdy - a co jsem tak vypozorovala, přijde mi, že to správně funguje, když mám širší tabulku než panel (vidím posuvník), pak to opravdu drží a posouvám jen tím, čím chci (žádoucí chování). Ale pokud se tabulka do panelu vejde celá, pak odskakují i další sloupce (to, co nechceme). 
- pamatování mi přijde, že nefunguje
- a další věc pak je, když změním sloupce (přidám, odeberu), tak se šířka u všech hodí do toho původního nastavení

**Comment by albertoh** [comment]
Znovu.
Jen neni hezky pri resetovani nastaveni. Vsechny sloupce maji nastaveno vychozi sirku 100px (neco jsem musel dat).
Pamatovani mi funguje

**Comment by albertoh** [comment]
@pkudela potom ti vysvetlim co jsem vsechno zmenil v css

**Comment by pkudela** [comment]
Testoval jsem to jak ve starem klientovi, tak v novem a chovani se mi zda totozne. Ve starem klientovi tabulka nemela take nastavenou 100% delku, takze by to melo byt +/- totozne chovani.

**Comment by luckajirku** [comment]
Mám problém s posledním sloupcem, který mám zapnutý, s tím se při rozšiřování doprava nedá pracovat tak jako s ostatními. Neřeší tohle u starého ten jeden prázdný úzký sloupec, který je vždycky poslední?

**Comment by ZdenkaSera** [comment]
@luckajirku S tím jsem bojovala v předchozí verzi, ale v téhle už mi jde myší roztáhnout i ten poslední sloupce doprava (zkouším v hledání nahoře)

**Comment by luckajirku** [comment]
jakože vám to jde i tam plynule (a jedním rychlým pohybem)? Když si dám třeba jako poslední PID, ať je to něco s delším obsahem, tak u těch levých sloupců v pohodě chytnu a hned posunu, kam potřebuju. Ale když je to ten poslední, tak musím opravdu jemně a znak po znaku pomalinku posouvat (a ještě s nejistým výsledkem)... 
![posunpravysloupec](https://github.com/proarc/proarc-client/assets/6359479/2b48e6d4-11b5-4849-8ef8-7c10f3339329)

**Comment by ZdenkaSera** [comment]
@luckajirku Ještě doplním - je ale třeba ten sloupec upravit ve velkém okně, kde nemám posuvník, s ním se mi to nedaří, k pravému okraji posledního sloupce se nedostanu. Ale to mi nepřipadá jako problém a jinak se mi to zdá prima, kolegyně také odsouhlasily.

**Comment by ZdenkaSera** [comment]
Aha - naše maily se minuly - ještě zkusím s dlouhým polem.

**Comment by ZdenkaSera** [comment]
Máte pravdu, měla jsem jako poslední kratičké pole, roztáhnout PID se skoro nedá. Jediným řešením teď je přidat si na konec vpravo pole, které ve skutečnosti nepotřebuju, ostatní pole si nastavit a tohle pole pak zase vypnout. Je to trochu krkolomné, ale nastavení zůstane,.

**Comment by ZdenkaSera** [comment]
Ten poslední pokus  byl v editaci monografie.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím tě, dá se manipulace s posledním sloupcem vpravo vylepšit?

**Comment by albertoh** [comment]
Zuste ted

**Comment by ZdenkaSera** [comment]
Za mne o 100% lepší 😊

**Comment by luckajirku** [comment]
Za mě taky. S pravým jde hezky posouvat, pamatování funguje, při odebrání/přidání jiných sloupců to předchozí nastavení šířky u všech drží..., takže super. Jako může se ještě něco vyvrbit, ale tohle už vypadá dost použitelně.
Ještě bych se později mrkla na to zkracování - počet znaků vs šířka sloupce (mělo by to jít víc nadoraz jako ve starém, tady už to dává tři tečky a pak vedle je zbytečné prázdno), ale to už není něco, co by bránilo normálnímu používání.

**Comment by pkudela** [comment]
@luckajirku ten prostor v bunce tabulky je ochrany prostor pro text, nicmene to melo smysl kdyz se text neorezaval a nebylo mozne hybat sloupci, nejaky ochrany prostor tam necham, ale minimalni, podivam se na to.

**Comment by pkudela** [comment]
Nynejsi stav
<img width="316" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/a26e346d-bdb1-4f54-b86d-09b90222fd28">

Stav po uprave
<img width="329" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/3f23a116-a871-4e93-a687-7ca31856dd04">

Vyhovuje?

**Comment by luckajirku** [comment]
jj, to je ono. Vy jste nějak výkonní v pátek odpoledne...

**Comment by ZdenkaSera** [comment]
Za mne super - @luckajirku Troufneme si tohle pustit už dál bez čekání na ostatní? Já bych to riskla. Zbýval by pak už jen ten otazník kolem neaktivního tlačítka ukládání..

**Comment by pkudela** [comment]
@luckajirku jako kazdy den :-) Nasadim na server k testovani.

**Comment by pkudela** [comment]
nasazeno na server, prosim jen potvrdte, ze to misto v bunce je ok

**Comment by luckajirku** [comment]
dobře, tak jen potvrzuji, že místo v buňce je OK a už mlčím (jen pro @ZdenkaSera jj, už je to v pohodě, tady asi není třeba čekat na ostatní)

**Comment by ZdenkaSera** [comment]
@luckajirku Prima. děkuji.

**Comment by ZdenkaSera** [comment]
@pkudela Petře, moc díky! Prosím tě, máš v úmyslu to hned nasazovat na další lišty /Hledání/spodní okno ..) nebo to raději až v dalším kole a po vydání releasu? Pokud se povede opravit ty neaktivní ikony ukládání, chtěla bych požádat o vydání verzí jádra i klienta v pondělí ráno a nechtěla bych spustit nic, co by to mohlo ohrozit. Co myslíš?

**Comment by pkudela** [comment]
@ZdenkaSera pokusim se to nasadit vsude, kde je tabulka, ale co se tyce stromu viz. dolni okno v hledani, tak tam to nelze udelat, to uz jsem nekde zminil, neni to tabulka i kdyz to tak na prvni pohled pusobi, nekdy to muzeme zkoumat, jestli to pujde, ale ted by se to nestihlo.

**Comment by pkudela** [comment]
V pondeli bych to zkusil doplnit vsude tam, kde ta tabulka je. Cekali jsme vlastne jen na pozitivni vysledek testovani tabulky v search a editoru.

**Comment by ZdenkaSera** [comment]
@pkudela Dobře, díky, budu se tedy s novými verzemi upínat k pondělnímu večeru :-)  - jojo, ten strom jsi zmiňoval, uvědomuju si to,  já jsem jen v rychlosti sáhla po nejbližším (špatném) příkladu.

**Comment by pkudela** [comment]
@ZdenkaSera pockam tedy na vyjadreni ostatnich, ja bych je osobne zobrazoval bud vsude, nebo nikde, i jiny sloupec nez nazev muze byt delsi, napr. v administraci cesta k domovskemu adresari.

<img width="188" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/34a0e509-d8cf-4e3d-a6f2-fa5ac2d9e344">

**Comment by luckajirku** [comment]
Tak ve starém jsme se bez toho obešli, tady bychom se obešli taky, když teď jde těmi sloupci hýbat. Ono když to vyskakuje všude, tak to celkem i ruší. @pkudela - když to teď dáš pryč, tak bude složitější to kdyžtak dát pak zpátky než to tam rovnou nechat a upravit? Já bych to teď spíš neřešila a uvidíme, jestli vyvstane potřeba to mít.

**Comment by pkudela** [comment]
@luckajirku ted je to myslim jen v hledani a v editoru a to na vsech sloupcich, ve vicero pripadu tooltip neni, takze odstranit to z hledani a z editoru je pro me jednodussi. A souhlasim, muze to byt rusive a hlavne dle meho to ted postrada smysl, kdyz se da se sloupci hybat, stejne tak si to zminila i Ty. Cili udelam to vsude bez tooltipu a kdyby v budoucnu byla potreba, tak to budeme resit? Doplnit ho nazpatek neni tak slozite. Souhlasite?

**Comment by ZdenkaSera** [comment]
Pojďme to tak tedy udělat (tj. bez tooltipů), ať se posuneme dál.  Díky oběma @luckajirku @pkudela

**Comment by pkudela** [comment]
ok, udelam

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, mam to hotove, jen potrebuji jeste neco rano probrat s Albertem, potvrdim zde, az upravy nasadim na server

**Comment by ZdenkaSera** [comment]
@pkudela 4etla jsem večer, děkuju za info

**Comment by katerinasirova** [comment]
Omlouvám se, že jsem nereagovala, u nás otestováno - s manipulací se sloupci jsme spokojeni a souhlasím s tím, že tooltipy odebereme a pokud bychom při testování zjistili, tak přidáme. Za nás vyřešeno

**Comment by pkudela** [comment]
Ahoj, pri tom predelavani tabulek jsem narazil na jeden problem. Jak a kde budete menit sloupce, ktere chcete v dane tabulce zobrazovat u dialogu viz. screenshoty nize? Tam to totiz neni jeste doresene, cili budete chit 3 tecky a pod tim nastaveni sloupcu? Jen podotykam, ze v dialogu si lze na leve a prave strane zobrazit tabulku, ktera ma kazda jine sloupce, takze by to muselo byt nastavitelne v obou.

<img width="1444" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/a28edb7b-a734-4b6c-9418-0de77bd4c951">

<img width="1436" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/77b750cf-a524-43a1-b6b8-5ceadb045492">

**Comment by pkudela** [comment]
Nasadil jsem na server a volba velikosti sloupcu by mela byt ve vsech tabulkach napric aplikci, krome devices, tam mi to prislo zbytecne, pokud bude potreba, dodelam. Provedl jsem tedy nasledujici upravy:

- ze vsech tabulek odstranil tooltipy
- ze vsech tabulek odstranil elementy, ktere delaly orez textu (to bylo potreba pred implementaci resize tabulky, kdy sloupce nemely svoji sirku)
- nyni je orez nastaveny globalne na vsechny bunky tabulky
- volbu sirky sloupcu jsem implementoval do: sprava procesu, administrace, dialog Oznacit radu, dialog Vyberte nadřazený objekt, 
- search a editor tam to bylo hotove, jen doslo k odstraneni tooltipu a orezovych elementu

Vsechny tabulky by si mely pamatovat posledni stav, prosim otestujte a pripadne dejte vedet, pokud bych na nejakou tabulku zapomel.

**Comment by ZdenkaSera** [comment]
@pkudela Petre díky., prošla jsem všechna místa, kde by to mělo být nasazeno - za mne super👍. 👍
Mohla jsem ale něco přehlédnout resp. nevidět uživatelským okem, takže počkám na vyjádření ostatních. Pokud by se k tomu kolegyně @luckajirku @katerinasirova @erikamirova během dneška nedostaly, zítra ráno bych to pustila dál a požádala o vydání verze jádra i klienta (ještě si znovu projdu další issues).

**Comment by ZdenkaSera** [comment]
Pokud jde o výběr zobrazovaných sloupců, zatím tam jsou sloupce všechny  - v levých oknech v obou případech by to podle mého  nemělo vadit. Pravá okna mohou být méně přehledná, ale navrhuji tohle dodělat až v dalším kole (verzi).

**Comment by pkudela** [comment]
@ZdenkaSera ano, je to na vas jak se k tomu postavit, proto jsem to tady zminil, kdyz jsem na to narazil.

**Comment by ZdenkaSera** [comment]
@pkudela Jasně, my jen nechceme za KNAV tyhle věci kolem "uživatelské přítulnosti" rozhodovat sami, názor ostatních je tu důležitý. Takže tohle bych brala jako prozatímní a k diskusi :-), založíme na to samostatné issue.

**Comment by luckajirku** [comment]
co se týká fce Označit řadu, řešilo se to v https://github.com/proarc/proarc-client/issues/200 a tam jsme se shodli, že stačí název souboru, typ strany, číslo, index, pozice, že nic víc se stejně nevyužije. Takže by ten výběr neměl být potřeba. Skoro bych do toho radši nesahala, ať se to nerozbije.

**Comment by luckajirku** [comment]
a k tomu Nadřazenému objektu - tam by to chtělo ty tři tečky. Ale nevím, jak moc na to spěchat. Pokud si ten první sloupec přebírá výběr sloupců z editace v úložišti, tak s tím se pro tu jednu verzi fungovat dá a můžeme to řešit až pak... 
A ten druhý si to přebírá z hlavní tabulky Hledat? V té se teď děje zajímavá věc. Nastavení šířky si pamatuje, OK. Pokud nastavení resetuju, nastaví se sloupce do nějaké defaultní šířky, taky OK. Ale když si sloupce přenastavím v nastavení v profilu, dostanu tohle a musím si je zas roztahat:
![uzkesloupce](https://github.com/proarc/proarc-client/assets/6359479/4f0bf861-9777-4caf-99cf-eb22492ef58f)

**Comment by pkudela** [comment]
Ahoj, otestoval jsem to a mas pravdu, vime kde je problem, az opravime hodime na testovani.

**Comment by luckajirku** [comment]
Potvrzuji, že je opraveno:-)

**Comment by ZdenkaSera** [comment]
@luckajirku @albertoh @pkudela Děkuji velice!

Budu tohle issue považovat za hotové s tím, že nastavení pro volbu sloupců v "Nadřazeném objektu" dořešíme jinde a později.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
