### ISSUE TITLE
Chyba pri ukladani noveho uzivatele

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#319]
Pri refactoringu administrace uzivatelu jsem narazil na problem s ukladanim noveho uzivatele, zahlasi nize uvedeny error:

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/16591052/221225032-0c9abbe9-063c-438e-a82f-af5d6bd1f9dd.png">

@albertoh muzes se na to prosim podivat? Dik

**Comment by albertoh** [comment]
Hlaska povida "Invalid username". Ted jsem zalozil uzivatel test4 bez problemu. @SykoraLukas jake jsou pravidla pro uzivatelska jmena?

**Comment by ZdenkaSera** [comment]
@albertoh přidá kontrolu

**Comment by ZdenkaSera** [comment]
Otestováno v KNAV - pokud dodržím výše popsaná pravidla, uživatele lze založit, jinak uživatelsky nepřívětivá chybová hláška. . Kontroly jsou zatím jen na povinnost polí.

**Comment by albertoh** [comment]
Pridana kontrola a hlaska

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, vidím u každého pole nápovědu, to je super 👍 Ale při pokusu o uložení nesmyslných hodnot to pořád vyhazuje stejnou nevlídnou chybu. Co dělám špatně? Reloadem by to být nemělo ... Díky.

![image](https://user-images.githubusercontent.com/79305516/231443970-a1429d00-9922-402b-937c-8bb800d2a1e9.png)

**Comment by SykoraLukas** [comment]
Opraveno, prosím o vyzkoušení.

**Comment by ZdenkaSera** [comment]
Uživatel je kontrolován na tvar, heslo na délku - za mne ok, děkuji.

**Comment by luckajirku** [comment]
Uživ. jméno je červené, když není OK. Ale heslo, i když nesplňuje podmínky, zůstává šedě - nemělo by se taky probarvit?

**Comment by ZdenkaSera** [comment]
Nechám rozhodnutí na ostatních, v tomhle případě se mi zdá zásadní funkční kontrola. Děkuji.

**Comment by pkudela** [comment]
Toto by melo byt opraveno, udelal jsem novou kontrolu poli, ted uz nevyskakuji dialogy, ale pole se oznaci a vygeneruje hlasku.

![image](https://user-images.githubusercontent.com/16591052/232684302-867945d7-3fef-42af-b3d3-08d62258e1f0.png)

Jakmile bude nasazeno, oznacim k testovani.

**Comment by pkudela** [comment]
nasazeno

**Comment by luckajirku** [comment]
Btw ty fce převodu, updatu, uzakmknutí/odemknutí objektu nemají superadmin a admin přednastavené? Musí se to i u nich navolit?

**Comment by ZdenkaSera** [comment]
Tady ještě detail - mám chybu v uživateli, přesto se rozhodnu záznam uložit. Správně se neuloží, ale mohla by ta hláška být přátelštější ? Není prio.
![image](https://github.com/proarc/proarc-client/assets/79305516/7e7f9386-cf6b-4baa-8640-c8399dbf1a38)

**Comment by ZdenkaSera** [comment]
Takže je to ještě jinak - admin má zřejmě právo jen zobrazit uživatele z vlastní organizace, založit nového uživatele můžu jen jako superadmin. Tak zatím ok, praxe ukáže.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
