### ISSUE TITLE
šířka rámečků ve formulářích (#335)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#32]
Šlo by nějak udělat, aby všechny rámečky ve formulářích byly stejně široké? Zlepšila by se tím přehlednost při vyplňování a formuláře by byly mnohem přívětivější pro čtení.

https://github.com/proarc/proarc/issues/335

**Comment by luckajirku** [comment]
Tohle už je, ne?

**Comment by honza-rychtar** [comment]
Ano

**Comment by luckajirku** [comment]
issue lze zavřít
