### ISSUE TITLE
Bagit export

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#320]
Na Objednávku NM implementovat rozšíření NDK exportu o vytvoření BAGIT balíčku ze vzniklého exportu.

**Comment by SykoraLukas** [comment]
Na API hotové. @alberto prosím o přidání parametru isBagit pro NDK a Archive Export. Možné hodnoty true / false. Uživatel si ttuto hodnotu vybírá ve chvíli kdy chce spustit NDK nebo Archive Export.

Udělat to obdobně jako u Kramerius Export hodnota Veřejně dostupné.
![image](https://user-images.githubusercontent.com/27210823/221412704-d75e443c-0729-4875-8668-95d1e89ee399.png)

**Comment by luckajirku** [comment]
Jenom se zeptám - to zaškrtávátko se tam bude objevovat všem u NDK exportu?

**Comment by albertoh** [comment]
Jo. Ma to byt jinak?

**Comment by ZdenkaSera** [comment]
@luckajirku Navrhovala bych je tam takto (defaultně nezaškrtnuté) nechat a až pokud by to dělalo uživatelům potíže, navázat jeho zobrazení na konfiguraci. Ok?

**Comment by luckajirku** [comment]
No mně to přilepení k nejčastějšímu exportu nepřijde šťastné. Přišlo by mi rozumnější to vyhodit jako extra možnost exportu - čistý NDK export a NDK vč. Bagit - a nechat instituce, ať si navolí v cfg, co se jim má nabízet. Kolik institucí tohle bude používat?

**Comment by katerinasirova** [comment]
Zatím asi jen Národní muzeum, do budoucna možná i MKP. Nevíme, kam se nástroj LTP na Cesnetu vyvine, možná, že to bude alternativa pro všechny druhy dokumentů, zatím se testuje na zvukových. 
Za nás buď varianta NDK vč. Bagit nebo alespoň možnost nakonfigurovat - ať to tam nevisí všem. Co je jednodušší?

**Comment by luckajirku** [comment]
Tak ono jde i o to, že se to sem dalo až ve chvíli, kdy to bylo hotové, bez předchozího zadání a možnosti se k tomu vyjádřit. Přitom domluva je, že věci dělané v rámci jiných projektů/zakázek se budou přidávat do hlavní větve až po schválení vývojovým týmem. Nebo to už neplatí?

**Comment by ZdenkaSera** [comment]
Na schůzce 15.3. jsme se shodli na tom, že checkbox bude nahrazen seznamem možností exportu s/bez bagitu v roletce. Obsah roletky by měl jít ovlivnit konfigurací.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím, nasměroval bys mne na doku, co se musí přidat do konfigurace, abychom mohli vyzkoušet exporty s bagitem? Nedokázala jsem to najít na wiki k jádru ani klientovi. Děkuji.

**Comment by albertoh** [comment]
Pridano tri nove typy exportu:

"archive_bagit"
"archive_stt_bagit"
"ndk_psp_bagit"

@SykoraLukas je potreba je dodat v jadru podle modelu podle #330

**Comment by SykoraLukas** [comment]
Doplněno

**Comment by SykoraLukas** [comment]
@ZdenkaSera [dokumentace ](https://github.com/proarc/proarc/wiki/Konfigurace#bagit-export) doplněna.

**Comment by ZdenkaSera** [comment]
V KNAV jsme otestovali exporty archivu a NDK_PSP s bagitem - zatím se zdá ok. Je třeba počítat s tím, že stejný druh exportů s bgitem a bez něj k témuž objektu se navzájem přepisují v exportním adresáři.

**Comment by ZdenkaSera** [comment]
Tady jen doplňuji, že došlo ke změně - balíčky s bagitem mají v názvu na začátku bagit_, takže jsou od "běžných" odlišitelné.
