### ISSUE TITLE
Import - nefunkční "převod stran"

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#321]
Funkce převodu stran na NDK strany a zpět je funkční v editaci v úložišti, ale ne v importu

**Comment by luckajirku** [comment]
Já se teda přiznám, že té potřebě převádět strany v importu moc nerozumím. Chápu to u nějakých dodatečných oprav v úložišti,  ale v jakém případě je to potřeba měnit v importu?

**Comment by ZdenkaSera** [comment]
@albertoh Poznámka "Vidim... chyba tam, musim menit na pole timestamp" asi patří do issue ohledně sloupce "změnit" 😉

**Comment by ZdenkaSera** [comment]
@luckajirku Osobně si myslím totéž, ale netuším, zda ji můžeme nechat jednoduše vypnout. Skeny se importují do modelu podle konfigurace, takže tady by manipulace neměla být zapotřebí. resp. v jádře tahle možnost taky nebyla. Takže podpoříte vypnutí?

**Comment by albertoh** [comment]
> @albertoh Poznámka "Vidim... chyba tam, musim menit na pole timestamp" asi patří do issue ohledně sloupce "změnit" 😉

Jejda, patri tam

**Comment by luckajirku** [comment]
> @luckajirku Osobně si myslím totéž, ale netuším, zda ji můžeme nechat jednoduše vypnout. Skeny se importují do modelu podle konfigurace, takže tady by manipulace neměla být zapotřebí. resp. v jádře tahle možnost taky nebyla. Takže podpoříte vypnutí?

:-) tak jako celkově bych podpořila diskusi o tom, co je potřeba v importu, co v úložišti.., co v klientovi přibylo aniž by to kdo chtěl a dávalo to smysl, a co ve starém naopak je, používá se a tady chybí - a jak se to bude řešit...

**Comment by ZdenkaSera** [comment]
@luckajirku S tím souhlasím, ale až v dalším kole :-)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, nevím, do jaké míry spolu lišty tlačítek v úložišti a importu souvisejí (tj. co technicky sdílejí), takže: prosím, udělej, co je jednodušší - buď tlačítko v importu vypni (preferovaná varianta) nebo oprav. Díky!

Jinak vypínání nepotřebných tlačítek v různých obrazovkách budeme řešit později, prosím uživatele o trpělivost.

**Comment by albertoh** [comment]
Muzu schovat v importu bez problemu

**Comment by ZdenkaSera** [comment]
@albertoh tak prosím převod stran v importu vypni. Děkuji.

**Comment by albertoh** [comment]
Vypnuto

**Comment by ZdenkaSera** [comment]
Děkuji, ok.
