### ISSUE TITLE
Import - nefunkční tlačítko "pokračovat

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#322]
Test na krátké KNAV monografii: načtu skeny, očísluji, zvaliduji a chci pokračovat k vyhledání nadřazeného objektu - tlačítko "Pokračovat" je teď nefunkční.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Díky, první test ok, více zítra.

**Comment by ZdenkaSera** [comment]
Zdá se to ok, díky. zatím zavírám.
