### ISSUE TITLE
využití zobrazení Mřížka

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#324]
Dotaz na uživatele - používáte někdo na něco zobrazení Mřížka? Objevilo se s novým klientem, my jsme na smysluplné využití nepřišli, tak je otázka, jestli pak řešit schování ikony v dropdown menu, nebo jestli tuhle věc nezrušit úplně, pokud by to nikdo nepoužíval.

**Comment by katerinasirova** [comment]
Já jsem ji při testování využila minimálně, kolegyně vůbec. Za nás navrhuji nechat chvíli na testování na vlastních instancích v "běžném" provozu a potom se rozhodovat.

**Comment by ZdenkaSera** [comment]
Navrhuji probrat na schůzce k redesignu 18.4.2023. Děkuji.

**Comment by pkudela** [comment]
ano, probereme tam, pred tim jeste jako pripravu vytvorim separatni issue tykajici se prave jednotlivych polozek v toolbarech.

**Comment by luckajirku** [comment]
Dávám k zavření. 
Řeší se v nově založených issues pro jednotlivé panely. Na schůzce 18. 4. jsme se shodli, že tohle zobrazení chceme zrušit (s tím, že  ikonka, co je teď pro mřížku, se použije pro zobrazení náhledů).
