### ISSUE TITLE
Přidat k názvům jazyků a rolím autora i kódy

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#325]
Za KNAV bychom uvítali vrácení kódů jazyků k názvům. Preferujeme kód jazyka a druhý sloupec s českým názvem. Informace o typu a autoritě zde pro nás není tak důležitá.

![obrazek](https://user-images.githubusercontent.com/13831946/223692998-1f42175f-11f5-4095-8646-e64ee5975eeb.png)

![obrazek](https://user-images.githubusercontent.com/13831946/223693171-acd34c22-c65d-4cf3-9051-cf16c0ab87ee.png)

A rolí u autorů.

![obrazek](https://user-images.githubusercontent.com/13831946/223694000-0aae4cc1-24fb-46dc-830b-0a70fa698335.png)

![obrazek](https://user-images.githubusercontent.com/13831946/223694224-1d9140a2-ecfb-4d9e-8f6e-46f242ffd77d.png)

V obou případech prosíme upravit mezery mezi řádky, je tam zbytečně moc místa.

**Comment by albertoh** [comment]
Kody jsem pridal.
@pkudela prosim, zmen radky

**Comment by pkudela** [comment]
hotovo, vyska radku definovana ve variables a prepsana globalne pro vsechny mat-select / option elementy - pri celkovem doladovani designu s tim lze pak jeste bez problemu hybat
 
![image](https://user-images.githubusercontent.com/16591052/224938120-769702d0-8f39-4f0a-bcdf-3f2ebd431da2.png)

**Comment by pkudela** [comment]
nasazeno na serveru, prosim otestovat

**Comment by nezbedova** [comment]
Otestováno. Upravené řádky nám vyhovují.

V jádru je výběr rolí, v klientovi jsou všechny. Je to dlouhé. Nám výběr vyhovoval. Co na to ostatní?

**Comment by luckajirku** [comment]
> V jádru je výběr rolí, v klientovi jsou všechny. Je to dlouhé. Nám výběr vyhovoval. Co na to ostatní?

Za nás určitě návrat k výběru těch nejpoužívanějších. @SykoraLukas nejde to tam zkopírovat z jádra? 
Už zase řešíme, co už jsme řešili v r. 2015... Které role tam mají být, to už jsme si časem vychytali a vyhovuje to.

**Comment by SykoraLukas** [comment]
Defaultně jsou všechny role ale dají se omezit na úrovni instalace. Vydrž chvilku vrátím tam původní hodnoty, co jsou ve starém klientovi.

**Comment by katerinasirova** [comment]
Pokud tam zůstanou i ty role související se zvukem a pokud jde upravit na úrovni instance, tak za nás OK.

**Comment by SykoraLukas** [comment]
Teď už tam jsou jen ty, co jsou ve starém. Pokud tam chce někdo někdo nějaké jiné, stačí si je nakonfigurovat.
