### ISSUE TITLE
Exporty v klientovi - timeout

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#326]
@SykoraLukas Navazuji na náš rozhovor a raději zakládám issue - prosíme o radu. Děkuji.
Při exportu objektu pro Krameria s volbou instance "local" dochází někdy (zřejmě u větších souborů) k chybě (viz obrázek), export je ale dokončen a ve správě procesů chyba není v logu. Log operace stažený ze serveru v příloze. @PetrKotynek 

![image](https://user-images.githubusercontent.com/79305516/223724240-173fe24b-8347-4d46-be1c-a0bbad5c52a2.png)

[chyba_exportu_8_3_400dev.txt](https://github.com/proarc/proarc-client/files/10921008/chyba_exportu_8_3_400dev.txt)

**Comment by SykoraLukas** [comment]
I když to z hlášky není zcela jasné mám pocit, že podle chování jde o Proxy error - vypršení na timeout. Ideální je v nastavení proxy nastavit timeout na cca 5 minut.

**Comment by PetrKotynek** [comment]
#
# Timeout: The number of seconds before receives and sends time out.
#
Timeout 300
a modproxy je zakomentovaný celý. 
V celé konfiguraci virtuálky není jediná klauzule 
 ProxyPass něco  timeout=

Těch 5 minut vidím jako splněno se zpětnou platností, PK

**Comment by PetrKotynek** [comment]
5 minut je opravdu málo ? Petr Kotýnek

**Comment by PetrKotynek** [comment]
centrální timeout v apache 
Timeout 300 na 480
ssl.conf
SSLSessionCacheTimeout  300 na 480

vypadává stále po 5 minutách PK

**Comment by pkudela** [comment]
@PetrKotynek muzete prosim poslat screenshot konfigurace proxy apache? dekuji

**Comment by PetrKotynek** [comment]
[apache2.zip](https://github.com/proarc/proarc-client/files/10941364/apache2.zip)

**Comment by PetrKotynek** [comment]
Nastaveno dle doporučení na PA jens-test. PK

**Comment by SykoraLukas** [comment]
Opakuje se problém?

**Comment by ZdenkaSera** [comment]
Ano. Pokud čas přesáhne 5 minut, vyskočí chyba uvedená nahoře následovaná zprávou "export se nezdařil". Ten však pokračuje dál a výsledek se zdá v pořádku. Dnes jsem otestovala i na exportu archivního balíčku - také s chybou po 5 min.

**Comment by ZdenkaSera** [comment]
Prosím, je naděje, že v nejbližší verzi (27.3.) tahle potíž nebude? V jádře lze exportovat bez problémů.

**Comment by SykoraLukas** [comment]
Pokud to nejde resit na strane nastaveni serveru, tak se musi predelat exporty a tim padem je to narocna zmena. Takže jistě to nebude

**Comment by SykoraLukas** [comment]
Ano, pošli mi to.

**Comment by ZdenkaSera** [comment]
Doplňuji:
- chyba jako dialogové okno se objevuje jen při exportech v novém klientovi
- nezáleží na druhu exportu (K4, archiv, NDK ..), podstatná je délka trvání nad 5 minut
- soubor, který v KNAV generoval chybu, byl jako archiv importován a následně bez chybového hlášení exportován na Inovatice (test @SykoraLukas )

@pkudela Petře, prosím, mohl by ses v úterý po schůzce sejít s panem Kotýnkem @PetrKotynek  kvůli tomuhle problému? Předběžně to navrhoval @SykoraLukas s tím, že toto je obvykle Tvá parketa. Děkuji.

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, nevim jestli v tom mohu byt napomocen, konfiguraci apache jsme uz zkusili zmenit, toto mozna bude jiny problem, chtelo by to i Lukase mozna, pokud budeme patrat kde je problem, me nic jineho uz nenapada. Pripadne muzeme dat separatni online meeting a zasdilet si obrazovky, kdyby to v utery neklaplo.

**Comment by PetrKotynek** [comment]
Oprášil jsem instanci s Fedorou, kam šlo nainstalovat zkušební data.
Nenašel jsem jinou možnost jak protáhnout timeout nad .htaccess a index.html aplikaci jinak než zvednout obecný apache2 timeout v  v apache2.conf

Timeout 1500
KeepAlive On

ve VirtualHost  pak
ProxyPass "ajp://127.0.0.1:8009/proarc/$1" timeout=1500 Keepalive=On


S úlohou jsem se dostal těsně nad 5 minut. Petr Kotýnek
 
![test1](https://user-images.githubusercontent.com/37083676/232317477-ac857fe0-030a-431a-8d53-2876d38855c7.png)
![test2](https://user-images.githubusercontent.com/37083676/232317523-a3b3460a-db10-4fcd-86ca-3d8ca8a58b63.png)

**Comment by ZdenkaSera** [comment]
@pkudela Děkuji, zdá se to na dobré cestě.

**Comment by ZdenkaSera** [comment]
@PetrKotynek Děkuji, další info jsem poslala mailem.

**Comment by pkudela** [comment]
@PetrKotynek dobry den, takze jestli to chapu, tak nastaveni timeoutu pouze ve virtual hosts nezabrala? Musel jste zvysit timeout i v konfiguraci apache? To je divne, pokud zvysujeme timeout, tak ho menime vzdy v konfiguraci virtual hosts, do konfigurace apache nesahame, ale jestli to pomohlo, tak je to dobre, mozna mate konfiguraci apache postavenou jinak. Kazdopadne dekuji za info.

**Comment by PetrKotynek** [comment]
Ano, ve virtual hostu jsem protáhl pouze ajp. Kde je tam  /var/www/html jsem zatím netrefil. Ale ten apache2.conf zabral. PK

**Comment by PetrKotynek** [comment]
Já to ještě zkusím nacvičit, i když bez certifikátů je to dost jalové.
Mám takový pocit, že jsem to zkoušel na virtual host:80 a že ani :443 není úplně to samé jako apache2.conf.
V každém případě na jenstejn test bylo aktivní pouze ajp.
PK

**Comment by PetrKotynek** [comment]
Timeout  = něco do úrovně Virtual Host. ajp nemá vliv.  Ověřeno i na úloze, která přesáhla timeout. PK 
![timeout_ve_VH](https://user-images.githubusercontent.com/37083676/232543382-892c8f04-9482-4818-a84c-b0d4331dca3b.png)

**Comment by ZdenkaSera** [comment]
Na testovací instanci žádný timeout, exporty se staví do fronty se statusem "naplánován". Zdá se ok, díky.

**Comment by SykoraLukas** [comment]
Díky téhle změně se rozbila ta kontrola na URN:NBN u starých tisků. Nějak to vymyslím, aby to šlo dělat postupně a zároveň byla hláška na přeskočení chybějícího URN:NBn u STT.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
