### ISSUE TITLE
Věcné třídění - chyba v povinnosti

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#327]
Po úpravě povinností se ve věcném třídění stal povinným typ autora - ve všech "boxech" věcného třídění daného objektu, i když je to nerelevantní. Prosím o opravu, děkuji.

![image](https://user-images.githubusercontent.com/79305516/224304729-cc6f4893-811c-49c8-8d0d-c5b381b3d47b.png)

**Comment by SykoraLukas** [comment]
Opraveno, odpoledne nasadíme.

**Comment by ZdenkaSera** [comment]
ve verzi v4.0.2/v2.0.3 zase zmizela osoba z formuláře věcného třídění, v xml je - test v KNAV a na Inovatice (obrázek z uuid:0d73570b-3565-4984-95eb-3fbe20aace89). 


![image](https://user-images.githubusercontent.com/79305516/228462007-077d5a63-37f3-4400-a756-a504c71f6752.png)

![image](https://user-images.githubusercontent.com/79305516/228462455-384365e3-c218-4f2d-9bc5-082e0dd5d721.png)

**Comment by ZdenkaSera** [comment]
Je to spravené, díky.

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
