### ISSUE TITLE
Potlačit zalamování textů v zobrazení

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#329]
Zalomení textů ve sloupcích upravuje výšku řádků, což není žádoucí. Prosíme tedy texty nezalamovat - všude, kde je to relevantní.

**Comment by pkudela** [comment]
@ZdenkaSera prosim, muzes mi poslat screenshot kde se tak deje? V tabulkach a stromu delku textu automaticky orezavam, tak aby nedochazelo k tomu co popisujete. Dekuji

**Comment by ZdenkaSera** [comment]
@pkudela Pokud si ze schůzky dobře pamatuji, tak šlo i o zobrazení v hledání - tam je název objektu oříznutý, ale v dalších sloupcích se pak zalomí a řádky se zvýší. @luckajirku Prosím, mohla byste pro jistotu potvrdit? Děkuji oběma.

![image](https://user-images.githubusercontent.com/79305516/225563726-be73c508-1e0a-4af2-a449-1cabad6123d9.png)

**Comment by luckajirku** [comment]
jj, i v hledání. Název se sice ořízne a dotečkuje, ale další sloupce ne - a ty to pak roztáhnou - ve větším okně to vidět není, ale stačí si ho zmenšit. Potřebujeme tohle nezalamovat, a až pak bude i to ruční upravování šířky, tak budeme spokojení:-)...

**Comment by pkudela** [comment]
@luckajirku @ZdenkaSera rozumim, ted uz vidim, nedokazal jsem to najit kde to bylo. Aplikuji tedy pro jistotu orez textu na vsechny sloupce, s moznosti zmeny velikosti sloupcu pocitame.

**Comment by pkudela** [comment]
hotovo, nasazeno prosim otestujte

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/16591052/225708388-181c1cdd-879e-4478-8d2c-9128dd210315.png">

**Comment by pkudela** [comment]
@luckajirku ja to bral tak, ze jde o to, aby vse zustalo na jednom radku, cili zalamuju text tam kde muze byt delsi, al emuzu to aplikovat na kazdy sloupec, jde jen o to, ze u kazdeho musim definovat procentualni delku. Udelam rychly fix a nasadim a das mi vedet, jestli je to tak ok.

**Comment by pkudela** [comment]
Ahoj, nakonec jsem to upravil, ze by se mel text orezavat vsude, ale! Funguje to tak, ze se text orezava pouze tehdy pokud je text delsi nez nazev sloupce, cili Inovatiku to nezarizne z toho duvodu, ze obsah bunky je kratsi nez nazev sloupce - Organizace vs Inovatika, samotneho me to zmatlo, kdyz jsem to debugoval. Takze ted je orez nastaven vsude, ale text se zarizne jen v pripade, ze bude obsah bunky na pocet znaku delsi nez nazev sloupce. Nasazeno na server.
