### ISSUE TITLE
Smazání dat bez varovné hlášky (#300)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#33]
Pokud zadávám metadata do formuláře a překliknu se do jiného, tak se bez 
varování smažou všechna vyplněná data. Šla by přidat nějaká chybová 
hláška, by mě varovala, když opouštím formulář bez uložení.

**Comment by SmejkalovaAnna** [comment]
Funguje, dává hlášku, když chci odejít z neuloženého formuláře.

**Comment by luckajirku** [comment]
Teď při testování úpravy validace příloh jsme narazili na to, že když u hlášky Opouštíte formulář bez uložení atd. odklepnu, že chci pokračovat, roztočí se kolečko a je potřeba refresh.

**Comment by luckajirku** [comment]
Pokud při tvorbě objektu ve vyskakovacím okně kliknu kamkoli do prostoru mimo, tak:
- pokud je to přes plusko, tak tabulka bez upozornění zmizí a dostanu se o krok zpátky
-  pokud jdu přes Nový objekt, tak tabulka zmizí a začne se točit kolečko

**Comment by ZdenkaSera** [comment]
@albertoh tady jsem přidala label chyba, aby to nezapadlo. Nevím, jestli tady chcete mít "probíhá " :-)

**Comment by albertoh** [comment]
Odstranil jsem moznost zavrit okno kliknutim mimo.

**Comment by luckajirku** [comment]
OK

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
