### ISSUE TITLE
Volitelnost sloupců - různá na různých úrovních Periodika

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#331]
Bylo by příjemné mít možnost navolit si různé sloupce v různých úrovní periodik. Protože takto je  to trochu podivné, pokud je to pro všechny úrovně společné ( na úrovni ročníku nebo výtisků zůstavá nastavení sloupců jako až na nejnižší úrovni ):
![obrazek](https://user-images.githubusercontent.com/24409660/225911342-7da0c8b2-eca4-4aa8-a682-1fd1d2fd5862.png)

**Comment by luckajirku** [comment]
Jo tak tohle jsme nedomysleli:-). Ve starém jsou všude jen sloupce popis, model, popř. PID, čili to, co lze použít na všech úrovních. Tohle asi musí nejdřív říct @albertoh @pkudela, jak by se to dalo řešit - jak by šla ta nabídka sloupců omezit v závislosti na úrovni - resp. jestli by ta nabídka rovnou byla osekaná, nebo jestli to řešit až v tom nastavování sloupců pro uživatele nebo nějaká kombinace toho...

**Comment by SmejkalovaAnna** [comment]
Poznámka pro další práce - teď jsem vypozorovala, na úrovni pod ročníkem, když zaškrtnu sloupec Název, tak se mi zobrazí číslo výstisku:
![obrazek](https://user-images.githubusercontent.com/24409660/227883853-9532f0d6-7d3e-4f39-9b03-97b35839bdb9.png)

**Comment by luckajirku** [comment]
takhle jen na první pohled 
- držme se termínů, na které jsou uživatelé zvyklí - místo Editace v repozitáři by mělo být Editace v úložišti
- ještě tam ale přijde úprava té části pro Hledat, aby se dalo nastavit zvlášť horní část a dolní část, ne? https://github.com/proarc/proarc-client/issues/302

**Comment by albertoh** [comment]
Spise bych se zeptal, jestli chcete nove nastaveni pro tenhle strom, nebo pouzivat nastaveni podle modelu z uloziste?

**Comment by albertoh** [comment]
To je hloupost. Ve stromu se zobrazujou ruzne modely...
Dodelam to, aby dolni cast byla samostatna od horni

**Comment by albertoh** [comment]
Pridano

**Comment by albertoh** [comment]
i text upraven

**Comment by katerinasirova** [comment]
Nastavení sloupců z tabulce nahoře i dole otestováno, v první chvíli se sice při zaškrtnutí jakéhokoli tlačítka v nastavení vyhledávání zaškrtlo automaticky i to ve vyhledávání (strom), ale po uložení a druhé zkoušce už funguje správně.
Ještě prosíme o přejmenování funkce "Editace v repozitáři" na "Editace v úložišti".

**Comment by luckajirku** [comment]
A ještě kosmetika:
- teď tam je "Importu" - to by asi mělo být "Import"
- dole tlačítko "Resetovat všechny lokální nastavení" opravit na "Resetovat všechna lokální nastavení"
- "Vyhledávání" bych změnila na "Hledat" a "Hledat (strom)", ať je to pojmenované stejně jako nahoře na liště.

**Comment by SmejkalovaAnna** [comment]
Já jsem si teda teď zkusila na uživateli USER nastavit v Editaci úložišti  sloupce na úrovni NDK strany a nic mi to neudělalo.... nechalo mě to zaškrtnout, ale změna se neprojevila. Ještě jedna věc: bylo by fajt tam dát tlačítko na vyskočení z toho Lokálního nastavení...ale možná dělám něco špatně....

**Comment by luckajirku** [comment]
V Hledat dole ve stromě jde odškrtnout Název, ale nic to neudělá. U jiných sloupců se změna projeví, tady ne. Teda ne že by to dávalo smysl, aby někdo chtěl nezobrazovat sloupec Název, ale když už tam ta možnost zaškrtnutí je...

**Comment by pkudela** [comment]
>

**Comment by luckajirku** [comment]
tak úplně dokonalé by to bylo, kdyby už v té nabídce pro každý model byly jen ty možnosti, které pro daný model jdou použít - a teprve z nich uživatel vybíral. Aby nemusel začít tím, že u každého modelu vyháže ty, které tam nedávají smysl.

**Comment by luckajirku** [comment]
Jako má to trochu mouchy... Když si bude chtít uživatel navolit sloupce, které se mu zobrazí, když otevře NDK Periodikum, tak automaticky v nastavení jde do NDK periodikum. Jenže tady musí uvažovat ne, ve kterém modelu je, ale které modely vidí pod tím, ve kterém je. Čili když si chci vybrat sloupce, které uvidím v modelu NDK periodikum, musím nastavovat v NDK ročník. Když chci nastavení sloupců v ročníku, čili vidím čísla, volím ne nastavení NDK ročník, ale NDK číslo... A ve chvíli, kdy se pod tou úrovní sejde těch modelů víc, tak to přebije nastavení toho modelu, které má těch sloupců víc (např. pod NDK ročník mám NDK číslo i NDK přílohu).

**Comment by luckajirku** [comment]
No mně jde spíš o to, pod čím to v tom nastavení je, jestli mi rozumíš. Že uživatel pod NDK periodikum bude očekávat, že si nastaví sloupce, které se mu zobrazí, když vleze do NDK periodikum - a ono ne. No mrkněte na to i ostatní.

**Comment by luckajirku** [comment]
Prosím @SmejkalovaAnna @katerinasirova @kerschfilip @erikamirova podívejte se na to. Mně tohle z pohledu uživatele nedává smysl. Jakože nejdřív si musím představit, které všechny modely se mi pod tím můžou vyskytnout a každý z nich extra nastavit (přičemž u všech modelů je stejná nabídka, ať už jsou pro ten model relevantní nebo ne). Pak bude ale třeba příloha periodika - kterou ale nastavím jak? Mám ji tam jednou, stejný model pro přílohu ročníku i čísla, čili pro různé úrovně...

Byla bych pro, aby se to bralo shora, ne zdola. Aby se pod názvem toho kterého modelu přímo nastavovaly sloupce, které se pod tím modelem mají zobrazovat (bez nutnosti nastavovat to ve všech možných podřízených objektech). A v nabídce v nastavení by byly u každého toho modelu jen ty sloupce, které se tam mohou vyskytnout.

**Comment by katerinasirova** [comment]
Souhlas s Luckou - nastavení shora dává větší smysl. A také mi trochu vadí to, že se mi sice v nevybraných sloupcích hodnoty nezobrazují, ale sloupce jako takové tam zůstávají.

**Comment by kerschfilip** [comment]
Mně ta současná podoba nijak zásadně nevadí, ale je pravda, že nastavování zabere nějaký čas a člověk u toho musí docela přemýšlet... Nastavování shora mi dává smysl, bylo by to určitě uživatelsky přívětivější

**Comment by ZdenkaSera** [comment]
schůzka 30.5.: 
1. vrátit ikonku pro nastavení sloupců na lištu  (pod tečky)
2. vrátit nastavení sloupců pod ni
3. nastavení v profilu zůstane paralelně, uživatel si bude moci zvolit způsob nastavování (bude přepínač)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Pod třemi tečkami je to super, protože člověk vidí zároveň tu editaci v úložišti a nemusí ji mít otevřenou v další záložce. Ale pořád se to nenastavuje na té úrovni, kde jsem. Jsem v NDK periodikum a vidím ročníky, ale nastavovat sloupce chci u NDK periodikum, ne u NDK ročník. Tohle je neintuitivní a bude to potřeba uživatelům vysvětlovat, jak si mají sloupečky nastavit.

**Comment by luckajirku** [comment]
A v importu by pod třemi tečkami měla vyskakovat ta tabulka Editace v importu, ne Editace v úložišti

**Comment by albertoh** [comment]
Opraveno pro import

**Comment by katerinasirova** [comment]
Okno importu vyzkoušeno. Funguje. 
Jen mám stejnou připomínku jako Lucka - tj. pokud necháme nastavení takhle, tak budeme muset hodně vysvětlovat. A je to škoda...

> Pod třemi tečkami je to super, protože člověk vidí zároveň tu editaci v úložišti a nemusí ji mít otevřenou v další záložce. Ale pořád se to nenastavuje na té úrovni, kde jsem. Jsem v NDK periodikum a vidím ročníky, ale nastavovat sloupce chci u NDK periodikum, ne u NDK ročník. Tohle je neintuitivní a bude to potřeba uživatelům vysvětlovat, jak si mají sloupečky nastavit.

**Comment by SmejkalovaAnna** [comment]
Jako jo, je to divné, souhlasím s Katnou a Luckou, že by tam měla naskočit ta úroveň, ve které jsem..... nicméně, funguje to. Ale je to škoda.... šlo by to učesat?

**Comment by luckajirku** [comment]
No ono je ta právě ještě víc matoucí, protože sice naskočí jakože úroveň, kde člověk je (když si přepnu na titul, naskočí mi NDK per., nakliknu ročník, nabídne se mi NDK ročník...) - ale uživatele nenapadne, že ta úroveň, kterou mu to nabídlo (a která odpovídá tomu, co vidí), není to, kde může nastavit to, co vidí. Za nás tohle fakt ne. Ten nový klient jinak už vypadá dobře a vesměs intuitivně, ale tohle je špatně. Je to logické z pohledu systému, ale uživatel do tohohle uvažování nepřepne.

**Comment by albertoh** [comment]
![image](https://github.com/proarc/proarc-client/assets/5946836/681f447a-77fa-46eb-8e3a-677d1d6eab2c)

**Comment by luckajirku** [comment]
Super, už je to na dobré cestě:-). 
- v defaultu bych to nechala zaškrtnuté - kdo to má rád komplikovanější, ať si to sám odškrtne
- v tom okně pod třemi tečkami je to zaškrtávátko umístěné uvnitř rámečku, čili dělá dojem, že se ta volba vztahuje jen na ten jeden model, což není pravda (v profilu je až pod rámečkem). Jako popravdě mě nenapadlo ani tak, že se to vztahuje pak ke všem modelům, možná by to tam mohlo být nějak napsané, nevím. Každopádně by to i u toho třítečkového okna mělo být mimo rámeček.
![dlenadr_tecky](https://github.com/proarc/proarc-client/assets/6359479/49410554-76b9-47e4-8070-2563feecf774)
![dlenadr_profil](https://github.com/proarc/proarc-client/assets/6359479/33b10925-9251-47f1-9039-426b0c60ffbf)

**Comment by pkudela** [comment]
upravil jsem dle vzhledu v settings

<img width="667" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/073ddb81-9cce-4c03-bdbd-2f86c7615660">

**Comment by SmejkalovaAnna** [comment]
@pkudela Pěkný...

**Comment by pkudela** [comment]
Nasazeno na server k testovani.

**Comment by luckajirku** [comment]
umístění zaškrtávátka OK, ale ještě by bylo fajn to defaultní zaškrtnutí u Dle nadřazeného

**Comment by albertoh** [comment]
Defaultni nastaveno

**Comment by luckajirku** [comment]
A už je to k testování? Mně se to neprojevilo, ani přes refresh ani přes odhlášení/přihlášení... Resetuju nastavení - a Dle nadřazeného zaškrtnutý není.

**Comment by pkudela** [comment]
nasazeno k testovani na server, prosim o kontrolu

**Comment by ZdenkaSera** [comment]
Za KNAV ok, je to tam.

**Comment by luckajirku** [comment]
ještě jedna věc pro fajnšmekry:-). Týká se to teda toho hlavního Hledat+stromu. Když v nastavení v profilu resetuju lokální nastavení a jdu hned naklikat úpravy, tak když klikám do hledat, úplně ta samá pole se mi souběžně označují/odznačují i ve vedlejším stromě. (A stejně tak i opačně, když označuju ve stromě.) Je to schválně? (Dělá to naráz jen to označování, uložit je třeba každý sloupec samostatně, aby se změny projevily.)
A pokud to okno s nastavením nezavřu a po naklikaných úpravách dám znovu Resetovat, hodí hlášku Reset lokálního nastavení byl proveden - ten proveden je (když to zkontroluju v jiném okně), ale ta zaškrtávátka se tam neudělají, je třeba stránku znovu načíst, aby se to zaškrtalo.

**Comment by albertoh** [comment]
Nebylo to naschval. Opraveno

**Comment by luckajirku** [comment]
zkontrolováno, už je to OK

**Comment by ZdenkaSera** [comment]
otestovala jsem asi jen částečně, ale všechny pokusy s resetem lokálního nastavení a odděleného nastavování jednotlivých (pod)obrazovek bylo ok, tak za nás také dávám 👍

**Comment by ZdenkaSera** [comment]
Označím k uzavření, nepovedlo se mi v issue najít nic otevřeného.

**Comment by ZdenkaSera** [comment]
@pkudela Tady je label "Probíhá" - půjde to sbalit to tohoto  releasu?

**Comment by pkudela** [comment]
odstranil jsem label

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
