### ISSUE TITLE
Import - pokračovat / výběr nadřazeného objektu - nejsou vidět objekty

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#332]
Když v importu kliknu na Pokračovat a chci uložit stránky do objektu, vyskočí mi prázdná tabulka. Teda jen naoko, když na nějaký řádek kliknu, tak ožije, řádky se najednou objeví. Je to jen při cestě z importu - když si okno pro výběr nadřaz. objektu vyvolám z úložiště, tak jsou objekty vidět hned. 
![nadrazobj](https://user-images.githubusercontent.com/6359479/226326894-920cfcfd-ee5b-4d8b-9d83-657b4a55d49a.png)

**Comment by luckajirku** [comment]
A ještě to pokračuje. Když si označím řádek s periodikem a otevřu si titul ve spodní části, na první nakliknutí atd. to nereaguje, musím na to číslo klikat tak dlouho (třeba 5x), než se mi nabídne, že do něj můžu uložit.

**Comment by albertoh** [comment]
Resim v #282

**Comment by albertoh** [comment]
jj

**Comment by ZdenkaSera** [comment]
@albertoh Tohle asi do verze ještě opravíš, prosím, že? Na Inovatioce to teď ani nezkusím, nedostanu se ani k importním souborům. Děkujeme.

**Comment by ZdenkaSera** [comment]
@albertoh Ještě doplnění - ať po přesunu zvolím přejít do editoru nebo do hledání, v obou případech se na pozadí otevře požadované okno - to je ok ale okno, kde proběhl přesun, zůstane na popředí otevřené a musí se ručně zavřít. Pokud to není vyžádaná vlastnost, která mi někde v diskusi utekla, zdálo by se mi lepší okno při volbě dalšího kroku rovnou zavřít. Ale je to kosmetika.

**Comment by luckajirku** [comment]
Jak to bylo původně (že se v importu ukazovala jen tabulka Hledat, následovalo uložení všech stran z dávky do vybraného objektu a pak si uživatel vybral, jestli chce přejít přímo do objektu - a pokud ano, tak ho to hodilo hned do toho objektu, kam uložil strany), tak to bylo v pořádku a vyhovovalo to, jen jsme chtěli ty řádky vidět. 
Místo toho se tohle nahradilo oknem, které je pro rozřazování stran v úložišti. A které, ač na obou místech vypadá stejně, v jedné agendě umožní rozřazování a v druhé jen pouhé uložení. Za mě tohle není až na schůzku k designu, ale na řešení teď.

**Comment by luckajirku** [comment]
A co se týká automatického zavírání vyskakovacího okna - v importu je to žádoucí - najdu objekt, uložím strany - a pak už chci přímo do objektu, tak v úložišti naopak to okno hned zavírat nechci - mám ho otevřené tak dlouho, dokud nerozřadím všechny strany.

**Comment by ZdenkaSera** [comment]
@luckajirku Díky - změna obsahu je mi jasná. Chápu i to, že okno je otevřené dokud není všechno rozřazené, jen jsem předpokládala, že přechod do editoru/hledání volím ve chvíli, kdy už mám všechno hotové. Takže mi asi opravdu unikl kus diskuse. Mea culpa :-)

**Comment by luckajirku** [comment]
Tohle už teď vypadá v pořádku, funguje, jak má - uložení stran, přechod do editoru nebo do hledat... Vše OK.

**Comment by SykoraLukas** [comment]
Pošlete ale asi budeme muset smazat současnou databázi objektů a bude se plnit znovu. Máme problém s místem a řekl bych, že nejjednodušší bude smazat a jen načisto.

**Comment by SykoraLukas** [comment]
@katerinasirova doplněno

**Comment by luckajirku** [comment]
Teď už jen takové kosmetické věci:-). Aby to byla na první pohled jasné, víc bych odlišila ukládání dávky do úložiště od přesouvání (už uloženého) v rámci úložiště. 

Oranžová lišta dole: 
_Uložit objekt/y do:_ bych změnila na **Uložit dávku do:** 
(protože objekt/y si tady vybrat nemůžu, musím uložit celou dávku)

po odsouhlasení toho vyskočí hláška:
_Přesun objektů
Opravdu chcete přesunout vybrané objekty do nově zvoleného objektu?_
(Nepřesouvám, ale ukládám, a nemůžu "nově" zvolit, když jsem ještě předtím žádný jiný objekt neměla.)

to by mělo být spíš :
**Uložení dávky do úložiště
Opravdu chcete uložit dávku do vybraného objektu?**

**Comment by SykoraLukas** [comment]
Na serveru zbývalo 30 MB. Pokud bych to neudelal tak dneska mazene všechny objekty a začínáme od prázdné DB

**Comment by luckajirku** [comment]
Tak ono už by skoro bylo lepší začít odznova než jen s tímhle. Navíc v monoškách toho zůstalo poměrně dost. Každopádně bychom se o tom mohli v úterý pobavit, jestli to nenastavit jinak. Nedělat všichni pod tím sdíleným uživatelem, ale ideálně (jestli už teď bezproblémově fungují ty organizace a uživatelé), aby každá instituce měla pod sebou svoje uživatele, měli bychom tam svoje importní adresáře, svoje objekty, navzájem bychom si do toho nelezli a hlídali bychom si, abychom tam toho neměli moc.

**Comment by ZdenkaSera** [comment]
Dávám si to na seznam bodů schůzky.

**Comment by ZdenkaSera** [comment]
Chybí jen přejmenování - @pkudela @albertoh

**Comment by albertoh** [comment]
Prejmenovano

**Comment by luckajirku** [comment]
Zkusila jsem a nevím, jestli to už je fakt k testování.

v tom oranžovém pruhu je pořád Uložit objekt/y do: 
když to odklepnu, dostanu: 
editor.children.relocate_dialog.titleImporteditor.children.relocate_dialog.messageImport

![import_hlasky](https://user-images.githubusercontent.com/6359479/231157805-71c47fab-aa37-404b-8b47-96b851131679.png)

**Comment by albertoh** [comment]
To bude cache. Tak to vidim ja.

![image](https://user-images.githubusercontent.com/5946836/231364306-9a5be3da-dfeb-4804-a1e4-143b2b9739d5.png)


Prosim tvrdy reload

**Comment by luckajirku** [comment]
Dobrý, tak už to mám. Standardní cesta přes Ctrl/Shift+F5 nefunguje, u nás to chce kouzelné tlačítko F12 a pak vymazat nahoře u adresního řádku přes načtení.

**Comment by luckajirku** [comment]
Ještě jsme narazili na jednu věc - co se týká objektu, do kterého se bude dávka ukládat. Tady (na rozdíl od té obrazovky pro rozřazování stran) to pamatování posledního objektu, kam se ukládalo, smysl nedává.  Ve starém tady vyskočí tabulka, defaultně vybraný model per. a nejnovější nahoře. A pak si doklikám, kam potřebuju. Potřeba ukládat další dávku na to samé místo, kam se ukládalo posledně, moc nebývá.

**Comment by pkudela** [comment]
@nezbedova pak to ale nemuze byt alert box, ten musi mit stejne chovani / pozici napric celou aplikaci. Lze to udelat jako normalni barevnou vetu.

**Comment by nezbedova** [comment]
@pkudela Navrhuji probrat to na úterní schůzce. Záleží na ostatních.

**Comment by ZdenkaSera** [comment]
@pkudela Přidala jsem štítek kvůli filtrování na schůzce.

**Comment by katerinasirova** [comment]
Za nás dává smysl mít hlášku po levé straně tam, kde se hledá, jak psala Lucka.

**Comment by luckajirku** [comment]
Lucka nic takového nepsala:-), ta řešila jiný problém - s chováním hledací tabulky při ukládání dávky:-)

**Comment by pkudela** [comment]
co se tyce hlasky, tak ta se resi v separatnim issue vytvoreneho na dnesni schuzce -> #369

**Comment by pkudela** [comment]
@albertoh ten posledni dotaz od Lucky se tyka tebe?

**Comment by albertoh** [comment]
> Ještě jsme narazili na jednu věc - co se týká objektu, do kterého se bude dávka ukládat. Tady (na rozdíl od té obrazovky pro rozřazování stran) to pamatování posledního objektu, kam se ukládalo, smysl nedává. Ve starém tady vyskočí tabulka, defaultně vybraný model per. a nejnovější nahoře. A pak si doklikám, kam potřebuju. Potřeba ukládat další dávku na to samé místo, kam se ukládalo posledně, moc nebývá.

Opraveno podle komentare

**Comment by SmejkalovaAnna** [comment]
Za nás asi v pořádku, nevidím v tom žádnou záludnost. Jediné co, tak když si chci prodloužit nebo zkrátit nahoru nebo dolu myší to prostřední spodní okno, tak to skáče zpátky a nedrží to tam, kde chci, takže to v podstatě nefunguje, je to na skákání, ale ne posouvání :) asi @pkudela ?
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/f180fd63-b813-4ac6-bd84-bcde55ab0011)

**Comment by luckajirku** [comment]
@SmejkalovaAnna ten problém s lištou už má svoje issue tady https://github.com/proarc/proarc-client/issues/364

**Comment by ZdenkaSera** [comment]
Prošla jsem si issue - myslím, že je to k uzavření, dávám štítek.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
