### ISSUE TITLE
Tabulka - zafixovat řádek s popisem sloupců

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#333]
V tabulce (v importu i v úložišti) by měl být ten řádek s popisem sloupců napevno, posuvník by měl fungovat až od prvního objektu - teď se při posunu posune i ten řádek s popisem. 

![listasloupce1](https://user-images.githubusercontent.com/6359479/226825129-8b71557d-81be-4169-a467-f95a339a95a6.png)
![listasloupce2](https://user-images.githubusercontent.com/6359479/226825141-c25ab631-0cb6-4a3e-8605-0898735542b1.png)

**Comment by pkudela** [comment]
@luckajirku provedl jsem zmenu u repository -> https://proarc.inovatika.dev/repository/uuid:133b0b00-c67f-43c6-a09f-3b5b4e91404d, nevim, jestli se tato komponenta sdili i v importu jak si psala, prosim, podivej se na to a dej vedet, jestli je to vsude ok, pripadne prosim posli priklad url, kde je to spatne. Spolu s fixni hlavickou tabulky jsem splachnul i orez textu, jako je to napr. ve vyhledavani. Chci se zeptat, ma byt ten orez aplikovany vsude v tabulkach napric aplikaci? Podobny problem se zalamovanim textu je napr. u tabulky viz. issue #282 ktery budu zitra resit.

**Comment by ZdenkaSera** [comment]
@pkudela Děkujeme :-)

@erikamirova @katerinasirova @SmejkalovaAnna @nezbedova  Dávám návrh k uzavření - pokud nebudete rozporovat, uzavřu 4.4.. Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera můžete klidně zavřít :)

**Comment by katerinasirova** [comment]
V současnosti OK, @ZdenkaSera můžete zavřít.
