### ISSUE TITLE
Validovat - funguje jen na strany

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#334]
Validovat - zafunguje jen na úrovni, kde není pod tím nic jiného než strany. Když jsou pod tím ročníky, čísla, přílohy..., validace nedoběhne.
![image](https://user-images.githubusercontent.com/6359479/228209193-e972ddbf-91e3-41b3-aebd-da336c6e9c84.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Za nás už ok, validuje na všech úrovních.

**Comment by SmejkalovaAnna** [comment]
Za nás taky Ok, validuje na všech úrovních, i jsem nasimulovala chybu a našel jí.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
