### ISSUE TITLE
NDK číslo periodika - žánr, autor

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#335]
V NDK čísle periodika je teď předvyplněná hodnota žánr s hodnotou article + to vyžaduje vyplnit i autora...

**Comment by luckajirku** [comment]
- ten article je tam zřejmě úplně nedopatřením. Ale je nezničitelný - smažu ten výskyt, dám uložit, překonat chybu - a article je zpátky... 
- autor tam v některých případech patří, ale vzhledem k tomu, že u většiny běžných periodik se v čísle vyplňovat nebude, je to vyžadování vyplnění problém. V každém čísle bychom museli ignorovat tu červenou, i když bychom měli popis v pořádku, pořád to bude upozorňovat.

**Comment by luckajirku** [comment]
Toto bychom potřebovali mít opravené, neprochází to pak validací.

**Comment by albertoh** [comment]
Opraveno. Nepridava genre + article

**Comment by luckajirku** [comment]
Genre-article už to nepřidává, ale pořád tam je ta kontrola povinnosti u autora a hlášky, že je objekt nevalidní. U NDK čísla periodika je to nesmysl - je to MA a standard říká "použití u ročenek, specializovaných per., tematických čísel nebo zvláštních vydání" - čili občas, a tam si to člověk pohlídá, aby si autora vyplnil, pokud je třeba. U běžných čísel takhle kontrola způsobí jen to, že označí všechno jako nevalidní, i když budou čísla úplně v pořádku.

**Comment by SykoraLukas** [comment]
Opraveno, jakmile bude nasazeno tak změníme label.

**Comment by SykoraLukas** [comment]
@luckajirku můžeš vyzkoušet.

**Comment by luckajirku** [comment]
Super, teď už to vypadá v pořádku, takže opatrně - a už se toho nedotýkat:-)

**Comment by SmejkalovaAnna** [comment]
Funguje to, už to nehlásí, bezva.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
