### ISSUE TITLE
Nelze načíst metadata z katalogu přímo v objektu

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#337]
Nedaří se mi stáhnout metadata z katalogu k již založenému objektu:

**Postup**
- Založím prázdný objekt (např. ečlánek)
- otevřu objekt 
- použiju ikonu pro stažení popisných metadat z katalogu ![image](https://user-images.githubusercontent.com/57805328/229580157-6bbb2338-7ab5-4c15-9b33-517117b4f467.png)
- vyhledám článek (třeba v KNAV analytika podle názvu "Vratislav Ebr")
- Dám `Nahrát metadata k objektu`

**Výsledek:** nic se nestane, formulář se neupraví.

**Comment by ZdenkaSera** [comment]
Zřejmě jde o stejný problém i při opakovaném stažení metadat z katalogu - příklad níže je monografie.

V jádře funguje opětovné stažení dat z katalogu:

![image](https://user-images.githubusercontent.com/79305516/230070365-8f4105cb-ec19-4cee-9efe-37fbd0fdf022.png)

V klientovi sice funkce nabídne data z katalogu nahrát, ale nestane se tak, objekt se nezmění:

![image](https://user-images.githubusercontent.com/79305516/230071393-ae2ee266-f673-446b-a4b2-510ab076a61f.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@albertoh Zatím základní test na monografii - nekontrolovala jsem detailně všechna pole, ale podle polí názvu a uložení je to ok, aktualizuje se. Díky.

**Comment by ZdenkaSera** [comment]
@kerschfilip Nedávám otestováno KNAV, nechám na test článků. Díky.

**Comment by kerschfilip** [comment]
otestováno, funguje

**Comment by ZdenkaSera** [comment]
Zavírám podle domluvy ze schůzky 4.4.2023.
