### ISSUE TITLE
Inovatika - testovací uživatelé

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#339]
Za knihovny prosím doplnit, jaké uživatele (tj. kolik a s jakými oprávněními) potřebujete na testovací instanci Inovatiky. Děkuji.

**Comment by luckajirku** [comment]
Pro SVK HK by se nám to líbilo takhle:
- **uživatelé**
    - 3 uživatelé s různými právy (user, admin, superadmin) - s tím, že je budeme sdílet (mezi sebou si to pak už ukočírujeme).
- **složky v importu** 
    - monografie Kavafullndk (60 stran) + krátká -tu, co je teď jako krátká v periodiku (10 stran), (ne tu superkrátkou mon čtyřstránkovou)
    - periodika pak stejně jako teď rozdělit na složky 1 až 4 a pod každou složku: větší dávku + krátkou.

**Comment by katerinasirova** [comment]
Za MKP prosím takto:

- **uživatelé** - 3x s různými právy - user, admin a superadmin (stejně jako Hradec)
- **složky v importu** 
    - monografie: Kavafullndk + krátká (4 stránky)
    - periodika - 3 složky s větší dávkou + 2 složky s krátkou dávkou
    - zvukové dokumenty - všechny, co tam jsou

**Comment by ZdenkaSera** [comment]
Za KNAV prosíme:
- **uživatelé** - 2x sadu po 3 (user, admin, superadmin) - tj. 1 sada pro DC Jenštejn a 1 pro Národní (OZČ a ODK)
- **Složky v importu**
  - monografie: 2x složka o cca 20 skenech + 1x větší dávka (Kavafullndk) + 1 krátká, všechno s OCR
  - periodika: 4x složka o cca 20 skenech + 1x složka cca 60 skenů
-  - STT: 1x krátká bez OCR (cca 10 skenů) + jednu bychom dodali (cca 65 skenů s OCR z PERO) - @SykoraLukas Může @nezbedova poslat ten zmíněný STT? Díky.

**Comment by SykoraLukas** [comment]
Email byl poslán. Data musela být redukována, aby se tam dalo pracovat.

**Comment by ZdenkaSera** [comment]
tohle navrhuji zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
