### ISSUE TITLE
NDK Ročník periodika (Standard 1.9)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#341]
- [x] mods:name:namePart - povinnost R
- [x] mods:name:namePart:type - povinnost M
- [x] mods:name:role - povinnost R
- [x] mods:originInfo:dateIssued:point - povinnost O

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by luckajirku** [comment]
K povinnosti namePart:type - naprostá většina zakládaných ročníků je bez autora - takže tam jen zbytečně vyskakuje červená hláška o nevalidnosti. Nemělo by si to vynucovat vyplnění Value jen v případě, že bude vybraný Type?

**Comment by SykoraLukas** [comment]
Udělal bych to se standardy, ale zatím netuším jak. Teď je u těch polí nastavené co se má kontrolovat. Tady se musí ale udělat nějaký nový druh kontroly pokud to je required a zaroven pokud existuje jiny element, ktery ma hodnotu ... Zatím si to nedovedu představit.

**Comment by ZdenkaSera** [comment]
@luckajirku My dneska taky prolézáme povinnosti, zkusím to zítra dopoledne shrnout v jednom issue, ještě to chci konzultovat v DC. Ale obtěžující povinnosti v MA elementu jsme někdy řešili výmazem souvisejícího "boxu" celého elementu z formuláře, což není ideální, ale teď stejně nefunguje.

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
