### ISSUE TITLE
NDK Vícesvazková monografie (Standard 2.0)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#345]
- [x] mods:name - přidat
- [x] mods:originInfo:place - povinnost MA
- [x] mods:originInfo:dateIssued - povinost M
- [x] mods:originInfo:dateIssued:qualifier - povinnost R
- [x] mods:originInfo:dateIssued:point - povinnost MA
- [x] mods:originInfo:dateIssued:encofing - povinnost R
- [x] mods:originInfo:dateOther - povinost R
- [x] mods:originInfo:copyrightDate - povinost R
- [x] mods:originInfo:dateCreated - povinost R
- [x] mods:abstract - přidat
- [x] mods:note - přidat
- [x] mods:subject - přidat
- [x] mods:classification - přidat
- [x] mods:location - přidat

**Comment by SykoraLukas** [comment]
Nutné více probrat, co se změnilo s vícesvazkem, jestli má cenu opravit stávající model nebo jaké jsou důvody pro vytvoření nového modelu. Dle polí v MODSu to zatím vypadá jen na úpravu formuláře.

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
Prošli jsme si formulář podle standardu a pár věcí jsme tam našli. Vkládám to sem včetně našich poznámek k (sub)elementům, , které nejsou přesně podle standardu, ale nechceme současné nastavení rozporovat, protože je už zažité z minulosti a nedělalo potíže.  samozřejmě je to k diskusi ostatním. Díky.

**Comment by ZdenkaSera** [comment]
- [ ] mods:titleInfo:type - chybí ve formuláři
- [ ] mods:name:namePart:Type - je R, má být MA
- [ ] mods:name:namePart:Value - je M a required, neměla by být vzhledem k tomu, že namePart je MA - když je element name použit, musí tam být hodnota, takže bychom to nechali povinné
- [ ] mods:originInfo:placeTerm:type - chybí, má být O - nebyl ani dřív, dotahuje se z katalogu do xml a nebudeme rozporovat
- [ ] mods:originInfo:dateCreated - chybí, má být R
- [ ] mods:physicalDescription:form:type - u AARC záznamu nemá existovat
- [ ] mods:physicalDescription:form:authority - u AARC záznamu má být M, je MA
- [ ] mods:identifier:invalid - spíš by mělo být M, standard to explicitně nezmiňuje - M je tady dáno roletkou, pole nelze nechat bez hodnoty, nerozporujeme to
- [ ] mods:subject:topic - nelze nic vyplnit
- [ ] mods:classification - správně R, ale pole jsou M a nemají být když celá klasifikace je R - to je sice další případ kdy jakmile je element použit, nesmí být prázdný, takže bychom to nerozporovali ALE nelze všechny elementy "classification" z objektu vymazat, poslední zůstává prázdný i po smazání popelnicí a hlásí chybu díky povinnosti polí - chyba, i když to v praxi spíše nenastane
- [ ] mods:recordInfo:descriptionStandard - je MA, má být M
- [ ] mods:recordInfo:languageOfCataloging - chybí, má být R
- [ ] mods:recordInfo:languageOfCataloging:languageTerm - chybí, má být R - u dvou položek k jazyku si myslíme, že není třeba, aby to uživatel jakkoli modifikoval, stahuje se to xml  a spíše bychom to do formuláře nenutili

pro RDA navíc:
- [ ] mods:originInfo:placeTerm:authority - chybí, má být MA
- [ ] mods:originInfo:dateOther:type - chybí, má být M, měla by to být roletka s výběrem “production”, “distribution”, “manufacture”

**Comment by ZdenkaSera** [comment]
Classification
Tohle sice není úplně o standardu, ale asi tady je to správné místo. Prosím, mohl by se i ve VD automaticky doplňovat "Konspekt" do pole "Edition" ? Řešili jsme to tady  - https://github.com/proarc/proarc-client/issues/142

**Comment by ZdenkaSera** [comment]
Tak ještě oprava ke klasifikaci - měla jsem neúplná testovací data. Je to tedy tak, že 
- [ ] Knspekt se dotahuje tam, kam má - problém je s elementy, ke být nemá, ale pole je tam povinné (viz už zmiňované issue https://github.com/proarc/proarc-client/issues/142)

![image](https://github.com/proarc/proarc-client/assets/79305516/edfe7793-13bc-4c38-a765-a1b2deeb65b5)

**Comment by ZdenkaSera** [comment]
- [ ] V "plovoucím okně" při zakládání nového objektu je překlep "mnografie" místo monografie

![image](https://github.com/proarc/proarc-client/assets/79305516/ce3623c3-5d14-412c-95eb-eb45f872d211)

**Comment by SykoraLukas** [comment]
Doplňuji: 
mods:originInfo:placeTerm:type ma byt O - nene, tady má být M
mods:originInfo:dateCreated - chybí, má být R - podle nápovědy by se mělo nejspíše jednat o RDA pravidla, ale je to i v AACR @kerschfilip mohl bys to ověřit?

**Comment by SykoraLukas** [comment]
dateCreated - i když je v nápovědě zmíněno pole 264 0 $c? Já to bral vždy tak, že AACR = 260 a RDA 264. Ale můžeme to dát i do AACR, to samozřejmě není problém.

**Comment by kerschfilip** [comment]
myslím, že to je ve standardu asi špatně - v části, která se týká AACR by mělo být napsáno, že z katalogu se převezme z 260 $g

**Comment by SykoraLukas** [comment]
@kerschfilip diky za vysvetleni :)

**Comment by SykoraLukas** [comment]
> Tak ještě oprava ke klasifikaci - měla jsem neúplná testovací data. Je to tedy tak, že
> 
> * [ ]  Knspekt se dotahuje tam, kam má - problém je s elementy, kde být nemá, ale pole je tam povinné (viz už zmiňované issue [Povinnost vyplnění pole Edice v Klasifikace  #142](https://github.com/proarc/proarc-client/issues/142))
> 
> ![image](https://user-images.githubusercontent.com/79305516/262664807-edfe7793-13bc-4c38-a765-a1b2deeb65b5.png)

@ZdenkaSera opravím podle dohody v #142, ok?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ano prosím. Když to zjednodušíme - Edition bude MA. Děkuju.

**Comment by ZdenkaSera** [comment]
Date other - chybí text Type k M mods.originInfo/dateOther/@type (CS i EN)

![image](https://github.com/proarc/proarc-client/assets/79305516/acfb180e-4e9f-4c34-9051-4b29a7e844c0)

**Comment by ZdenkaSera** [comment]
Nefunguje kontrola sigly na definovaný seznam

**Comment by SykoraLukas** [comment]
Nad jakým záznamem? Při vytvoření pole Location přes formulář mi to funguje.

**Comment by ZdenkaSera** [comment]
Na ttps://proarc-2023.inovatika.dev jsem v editaci uložila chybu do 0ae8a422-646d-4a47-801e-6064d730ee41

![image](https://github.com/proarc/proarc-client/assets/79305516/cd6676f4-fc85-4b49-9e7f-bcb20064f3a7)

**Comment by ZdenkaSera** [comment]
Standardně jsem založila přes formulář se správnou siglou a později jsem ji zase ve formuláři v editaci změnila na chybnou. XML jsem Ti ofotila jen pro info.

**Comment by SykoraLukas** [comment]
Ok tak to tam musi být někde chyba. Kontrola probíhá jen v případě, ze je authority="siglaADR". Pokud je Authorita jiná nebo není, tak se sigla nekontroluje

**Comment by ZdenkaSera** [comment]
@SykoraLukas Porovnala jsem založení NDK monografie a NDK vícesvazku, máš pravdu s authority 
1. v monografii se po stažení dat z katalogu (aacr i rda) založí sigla včetně authority a ve formuláři nejde změnit na neplatnou
![image](https://github.com/proarc/proarc-client/assets/79305516/27e5428b-6715-4732-90b2-4c2ddaa49666)

2. ve vícedílné monografii bude chyba - při stažení z katalogu (rda i aacr) se authority do xml nedoplní (a nepovedlo se mi to nasimulovat se změnami v reálném čase, jak jsi říkal, authority se do xml nedostane, ledaručně)
![image](https://github.com/proarc/proarc-client/assets/79305516/a2b9e056-a500-4636-aa7a-c0e530573472)

**Comment by SykoraLukas** [comment]
Doplněn formulář a tím pádem by mělo být veřešeno.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ve VD jsme ještě něco našli - prosím, koukni na to. Děkuji.
- [ ] mods:titleInfo:type - to jsem já chybně hlásila jako chybějící, ale podle v2.0. ve formuláři být nemělo. Protože se ve verzi 2.1. už má vyskytovat, necháme to jako ok
- [ ] mods:genre - na úrovni VD se má vyskytovat je neopakovatelný element s hodnotou "title"
- [ ] mods:originInfo - povinné má být pouze dateIssued, ale v AACR se chová jako povinný i publisher, i když je správně označen MA

**Comment by ZdenkaSera** [comment]
Poslední kontrola ve verzi 4.1.2./2.2.1. na základě dat stažených z katalogu, nikoli zakládaných z volné ruky. Prosím ostatní knihovny/uživatele o případné doplnění. Děkuji.

**Comment by SykoraLukas** [comment]
> * [ ] mods:originInfo - povinné má být pouze dateIssued, ale v AACR se chová jako povinný i publisher, i když je správně označen MA

Jak se to projevuje? Navrhuji řešit při redesignu formulářů

> * [ ]  V RDA mi Date other dovolí uložit element s vyplněným typem, ale bez hodnoty
Vychází ze standardu - pole je R, i když je type M. Nedá se tedy s tím nic dělat pokud se máme držet standardu. Navrhuji Type převést na MA.

**Comment by ZdenkaSera** [comment]
> > * [ ]  mods:originInfo - povinné má být pouze dateIssued, ale v AACR se chová jako povinný i publisher, i když je správně označen MA
> 
> Jak se to projevuje? Navrhuji řešit při redesignu formulářů

Při uložení formuláře dostanu dialogovou hlášku o nevalidních datech. Pokud je nedám uložit a vrátím se do formuláře, zčervená rámeček a název elementu - viz obrázek. Chybu lze překonat, ale pokud uživatel bude ukládat takové "(ne)chyby", příště může překonat a uložit skutečnou chybu. V RDA objektu ten problém není, tam publisher není vyžadován - proto jsem doufala, že to je řešitelné.

![image](https://github.com/proarc/proarc-client/assets/79305516/50ae1505-0554-4aae-abb5-fb9390d5041f)

**Comment by ZdenkaSera** [comment]
> > * [ ]   V RDA mi Date other dovolí uložit element s vyplněným typem, ale bez hodnoty
> 
> Vychází ze standardu - pole je R, i když je type M. Nedá se tedy s tím nic dělat pokud se máme držet standardu. Navrhuji Type převést na MA.

Pokud to nelze nějak snadno programově ošetřit, navrhuji to neřešit. Když mám naopak vyplněnou jen hodnotu (rok), prázdný type se hlásí jako chyba - a to je správně.

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
