### ISSUE TITLE
NDK Svazek Vícesvazkové monografie (Standard 2.0)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#346]
Zcela nový model dle standardu - jméno modelu: model:monographUnit (vychází z hodnoty v DC)

**Comment by SykoraLukas** [comment]
- [ ] Vytvořit nové funkce na převod modelů:
  - NDK Svazek monografie - NDK Svazek Vícesvazkové monografie
  - NDK Svazek Vícesvazkové monografie - NDK Svazek monografie



- [ ] Omezit ve vazbách propojení modelů
  - pod Vícesvazkem nejde již založit NDK Svazek monografie
  - pod Vícesvazekem jde založit NDK Svazek Vícedílné monografie.



- [ ] Přesně definovat názvy modelů
  - ndkMonographTitle  NDK vícesvazková monografie
  - ndkMonographVolume - NDK Svazek monografie (NDK monografie v novém klientovi)
  - ndkMonographUnit (nový model) - návrh NDK Svazek Vícesvazkové monografie

**Comment by ZdenkaSera** [comment]
Upravit tabulku modelů https://docs.google.com/spreadsheets/d/1H_afNvAt8SLdXH1Dpst8R3Vl7AaC0556kIpD44vftLw/edit#gid=0

na schůzce 15.6.2023 - shoda ohledně názvů

**Comment by SykoraLukas** [comment]
Zapsal jsem zde špatný současný název vícesvazku, správně je NDK vícedílná monografie, proto navrhuji upravit název nového modelu na NDK Svazek Vícedílné monografie

**Comment by ZdenkaSera** [comment]
- [ ] mods:originInfo:placeTerm:type - nelze vyplnit, měl by být M - stahuje se jen do xml jako dřív, nerozporujeme
- [ ] mods:originInfo:placeTerm:authority - nelze vyplnit, měl by být MA - stahuje se jen do xml jako dřív, nerozporujeme
- [ ] mods:originInfo:dateOther - u AACR nemá být k dispozici
- [ ] mods:originInfo:copyrightDate - u AARC nemá být k dispozici
- [ ] mods:subject:topic - nelze vyplnit
- [ ] mods:recordInfo:descriptionStandard - je MA, má být M
- [ ] mods:recordInfo:languageOfCataloging - chybí, má být R
- [ ] mods:recordInfo:languageOfCataloging:languageTerm - chybí, má být R - u dvou položek k jazyku katalogizace si myslíme, že není třeba, aby to uživatel jakkoli modifikoval, stahuje se to xml a spíše bychom to do formuláře nenutili

pro RDA:
- [ ] mods:originInfo:dateOther:type - nelze vybrat, měla by to být roletka s výběrem “production”, “distribution”, “manufacture”
- [ ] mods:identifier:invalid - je MA, má být spíš M (ve standardu to ale není samostatně vypsané) - - M je tady dáno roletkou, pole nelze nechat bez hodnoty, nerozporujeme to

**Comment by ZdenkaSera** [comment]
Kromě výše uvedeného:
- [ ] automaticky doplňovat issuance = multipart monograph
- [ ] upravit povinnost Edition u klasifikace stahované z pole 080 - viz https://github.com/proarc/proarc-client/issues/345

**Comment by ZdenkaSera** [comment]
Issuance multipart_monograph se v současné době doplňuje podle pravidel katalogizace - tj. pokud je na 7. pozici návěští hodnota "m" a na 19. pozici některá z hodnot "a", "b" nebo "c". Zjistili jsme, že druhá podmínka není vždy splněna.
Navrhujeme, aby se zde doplňování issuance vyřešilo v kódu místo v šabloně tak, že se do modelu svazek vícesvazkové monografie bude vždy doplňovat multipart_monograph.


@SykoraLukas Je to realizovatelné?

@luckajirku @katerinasirova @erikamirova  Prosím, souhlasíte?

**Comment by SykoraLukas** [comment]
Ano, není s tím problém.

**Comment by ZdenkaSera** [comment]
Na schůzce 7.11.2023 shoda o návrhu výše - @SykoraLukas prosíme o úpravu. Díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle se  i zdá na inovatice-masteru funkční, resp. k testu - pokud opravdu ano, prosím, přidej label,. Děkuju

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím o opravu, děkuji.

- [ ] V RDA mi Date other dovolí uložit element s vyplněným typem, ale bez hodnoty
- [ ] u všech objektů se automaticky zakládá "Related item" s vyplněným issuance:

![image](https://github.com/proarc/proarc-client/assets/79305516/3d267eb0-db1f-49ae-b399-c770c9f9bb30)

**Comment by ZdenkaSera** [comment]
Poslední kontrola ve verzi 4.1.2./2.2.1. na základě dat založených přes plusko a stažených z katalogu, nikoli zakládaných z volné ruky nebo pomocí tlačítka "vytvořit" . Prosím ostatní knihovny/uživatele o případné doplnění. Děkuji.

Nové issue ke kopírování hodnot z úrovně VD zde https://github.com/proarc/proarc-client/issues/506)

**Comment by SykoraLukas** [comment]
> V RDA mi Date other dovolí uložit element s vyplněným typem, ale bez hodnoty

nerelevantní - špatně navržený standard

**Comment by ZdenkaSera** [comment]
navrhuji tedy neřešit, viz https://github.com/proarc/proarc-client/issues/345#issuecomment-1969712707

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
