### ISSUE TITLE
NDK Svazek monografie

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#347]
- [x] mods:name:etal - povinnost O
- [x] mods:classification:edition - povinnost M
- [x] mods:relatedItem - povinnost RA

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
@SykoraLukas Po naší včerejší diskusi jsem znovu prošla monografii tak, že jsem do prázdného formuláře doplňovala data - šlo o to zjistit, co se dotahuje jako konstanta i bez katalogu a bez ručního vstupu a co uživatel bez katalogu do metadat nedostane, pokud mu to nedovolí formulář. Uvádím tedy i některé položky, které zřejmě nevyžadují změnu. Opravu od tebe a ostatních uživatelů uvítám - děkuji!

- [ ] mods:name:namePart:type – je R, má být MA
- [ ] mods:name:namePart:Value - je M a required, neměla by být vzhledem k tomu, že namePart je MA – ale když je element name použit, musí tam být hodnota, takže bychom to nechali povinné, při výmazu celého elementu to nehlásí chybu - ok
- [ ] mods:name:role:roleTerm:type – není ve formuláři, má být M  - konstanta se doplňuje do xml – to je ok
- [ ] mods:name:role:roleTerm:authority - není ve formuláři, má být M - konstanta se doplňuje do xml – to je ok
- [ ] mods:originInfo:placeTerm:type - nelze vyplnit, měl by být M - stahuje se jen do xml jako dřív; při vyplnění z volné ruky se automaticky doplní type = text, hodnotu „code“ ručně nelze zadat
- [ ] mods:originInfo:placeTerm:autority – nelze zadat, má být MA; je relevantní pouze pro type „code“, který také nelze ručně
- [ ] mods:originInfo:dateIssued – sice označeno správně M, ale ve skutečnosti není povinné – pole Value by asi tedy mělo být M místo MA
- [ ] mods:language:languageTerm:type – nelze vyplnit, má být M – doplňuje se do xml konstanta – to je ok
- [ ] mods:language:languageTerm:authority – nelze vyplnit, má být M - – doplňuje se do xml konstanta – to je ok
- [ ] mods:physicalDescription:form:authority – je MA, má být M (ve skutečnosti se chová jako povinná, povinná, i když popisek je MA)
- [ ] mods:subject:name:name type – značené jako M, ale nechová se tak (mělo by být stejně jako v mods:name MA)
- [ ] mods:classification:authority – pole je sice správně M, ale mělo být povinné až při vyplnění Value, teď si vždy vynucuje hodnotu v R-elementu classification
- [ ] mods:classification:edition – není ve formuláři pro AACR (v RDA je), do xml se stahuje; má být M, podle dohody necháme MA
- [ ] mods:recordInfo:descriptionStandard - je MA, má být M  (povinnost je ale hlídaná roletkou bez možnosti vynechat hodnotu)
- [ ] mods:recordInfo:languageOfCataloging - chybí, má být R
- [ ] mods:recordInfo:languageOfCataloging:languageTerm - chybí, má být R

**RDA navíc**
- [ ] mods:originInfo:dateOther:type - nelze vybrat, měla by to být roletka s výběrem “production”, “distribution”, “manufacture”
- [ ] mods:physicalDescription:form:authority – je M, má být MA – myslím ale, že to je chyba ve standardu a má opravdu být M

**Comment by SykoraLukas** [comment]
Odklikávám, ale nebudu řešit, kdyžtak se k tomu vrátíme:

- mods:name:role:roleTerm:type – není ve formuláři, má být M - konstanta se doplňuje do xml – to je ok
- mods:name:role:roleTerm:authority - není ve formuláři, má být M - konstanta se doplňuje do xml – to je ok
- mods:language:languageTerm:type – nelze vyplnit, má být M – doplňuje se do xml konstanta – to je ok
- mods:language:languageTerm:authority – nelze vyplnit, má být M - – doplňuje se do xml konstanta – to je ok
- mods:recordInfo:languageOfCataloging - chybí, má být R - LS: tohle uživatel stejně needituje, tak mi to přijde zbytečné
- mods:recordInfo:languageOfCataloging:languageTerm - chybí, má být R - LS: tohle uživatel stejně needituje, tak mi to přijde zbytečné

**Comment by ZdenkaSera** [comment]
Na nic závažného jsem nenarazila, poslední kontrola ve verzi 4.1.1./2.2.1. na základě dat stažených z katalogu, nikoli zakládaných z volné ruky. Prosím ostatní knihovny/uživatele o případné doplnění. Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tak přece jen - i tady platí, že
- [ ] V RDA mi Date other dovolí uložit element s vyplněným typem, ale bez hodnoty

**Comment by SykoraLukas** [comment]
Vychází ze standardu - který je špatně navržen. Nedá se softwarově ošetřit, jestliže má být zachována povinnost elementu R a type = M.

**Comment by ZdenkaSera** [comment]
Zavírám, pokud se v provozu objeví problém, založíme nové issue.
