### ISSUE TITLE
NDK Mapa

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#348]
- [x] mods:language - povinnost M
- [x] mods:physicalDescription - povinnost M
- [x] mods:subject:geographic - povinnost MA
- [x] mods:subject:topic - povinnost R
- [x] mods:classification:edition - povinnost M

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
@SykoraLukas Kartografický dokument se mi nedaří založit. Zkusila jsem na inovatice-masteru. 
Test na záznamu z katalogu Z39.50 MZK01, sysno=000473102 (případně kat. NKP (base NKC), pole 001= cpc19990702775)
![image](https://github.com/proarc/proarc-client/assets/79305516/2eddedba-b34e-4dad-a5cc-28f4d85a2915)

**Comment by ZdenkaSera** [comment]
Založení na Inovatice funguje.
