### ISSUE TITLE
NDK Hudebnina

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#349]
- [x] mods:name:etal - povinnost O
- [x] mods:physicalDescription:form:authority - povinnost MA
- [x] mods:classification:edition - povinnost M
- [x] mods:relatedItem - povinnost RA

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle jsem zmiňovala, řešili jsme např. tady přepnutím na MA, i když M je podle standardu správně, Díky.
https://github.com/proarc/proarc-client/issues/142#issuecomment-1168620634

![image](https://github.com/proarc/proarc-client/assets/79305516/43a378b2-618a-4fa9-b907-71a009124c83)

**Comment by SykoraLukas** [comment]
Ano, bude nutné přepnout Edition na hodnotu MA, protože se smí vyskytovat v různých elementech Classification

**Comment by ZdenkaSera** [comment]
Lokálně ve verzi 2.2.2/4.1.3 je to ok, díky.
