### ISSUE TITLE
NDK Kapitola

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#350]
- [x] mods:classification:authority - povinost M

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by SykoraLukas** [comment]
Bod 1 se generuje až při exportech.
Bod 3 se odkládá.

**Comment by ZdenkaSera** [comment]
Lokálně ve verzi 2.2.2./4.1.3. je to ok, díky.
