### ISSUE TITLE
NDK Příloha monografie

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#351]
- [x] mods:name:etal - povinnost O
- [x] mods:language - povinnost MA
- [x] mods:physicalDescription:form:type - povinnost M
- [x] mods:classification:edition - povinnost M

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
Poslední kontrola ve verzi 4.1.2./2.2.1. **na základě dat převzatých z hlavního titulu**, nikoli dat stažených z katalogu nebo zakládaných z volné ruky. Příloha je tedy založena plusem pod NDK monografií. Prosím ostatní knihovny/uživatele o případné doplnění. Děkuji.

AACR+RDA
- [ ] Part Number – označené správně MA, ale chová se jako povinné M
- [ ] Origininfo je MA a má se vyplnit jen pokud se liší od monografie – stahuje se ale dateissued

RDA navíc
- [ ] Díky přebírání dateissued se stává povinným eventype, hodnota se však nepřebírá a hlásí se jako chyba
- [ ] Date created v příloze vůbec nemá být, trochu nekonzistentně zde má být pro změnu copyright date (R)
- [ ] pro form authority="marcform" je vyžadován type

![image](https://github.com/proarc/proarc-client/assets/79305516/b57ba4ce-53c1-4663-8124-7b823cdbdb55)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Máš pravdu, v monografiích je to taky tak vyřešené.

**Comment by ZdenkaSera** [comment]
Ve verzi 4.1.3./2.2.2 v KNAV se zdá ok, díky. nNvrhuji k uzavřenní.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
