### ISSUE TITLE
Aktualizace standardů NDK

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#352]

**Comment by katerinasirova** [comment]
Počítá se s aktualizací všech standardů, tedy i zvukových dokumentů? Raději uvádím i tady, abychom na příští schůzce nezapomněli probrat. Letos jsme v MKP opět získali pokračování projektu digitalizace gramodesek z pozůstalosti V. Smetáčka z VISK 7.

**Comment by SykoraLukas** [comment]
Když byl projekt naceňován, tak se počítalo se všemi (ndk monografie, ndk periodika, ndk emonografie, ndk eperiodika skladana, ndk zvukovy dokument, ndk fonograficky valecek.
