### ISSUE TITLE
Rozbalit v Hledat neukáže/nerozbalí celý strom

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#353]
Fce Rozbalit v Hledat neukáže nebo nerozbalí vždy celý strom. Zřejmě to je nějak závislé na tom, jestli pod ročníkem jsou čísla a pod číslem strany. 
Vypadá to, že když je na konci třeba ročník, pod kterým nejsou čísla, nebo je tam číslo, pod kterým nejsou stránky, neukáže ho vůbec. Pokud je prázdný ročník někde jinde než na konci, tak blokne rozbalování těch následujících. 
Ve starém se ukáže celý strom a rozbalí vše, co jde.

**Comment by albertoh** [comment]
Nemuzu reprodukovat. Testoval jsem to na ruznych objektech.
Jen doplnim, ze robalit zvoleny objekt dolu, ne cely strom. Tj, pokud mam vybrany jeden rocnik, vedlejsi rocniky nerozbaluje, jen ten a dolu.

**Comment by luckajirku** [comment]
Zkus třeba tohle per.: uuid:eaa0123d-af0a-48ef-b90e-1311e4006216. Končí to ročníkem 1953, pod kterým je jedno prázdné číslo. Když jsem na titulu a dám rozbalit, tak tenhle ročník mi dole zůstane nerozbalený. 
A když na něj zkusím kliknout, že ho rozbalím ručně, tak mi to místo rozbalení skočí o ročník výš na 1952.

**Comment by albertoh** [comment]
Opraveno.
Problem byl ne ve fce rozbalit, ale celkem nebyl videt posledni radek ve strukture.
@pkudela pridal jsem novou css classu app-body-height

**Comment by ZdenkaSera** [comment]
Chci uvést na pravou míru  info o nezobrazovaném posledním řádku ze schůzky 19.9.2023 k redesignu - jak v úložišti tak v editaci 
 v tabulce se poslední objekt (strana, příloha ...) zobrazuje, vyzkoušeno v KNAV produkci na verzi klienta z 24.7.2023.  S omluvou.
