### ISSUE TITLE
NDK svazek eMonografie (Standard 2.3)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#354]
- [x] mods:titleInfo:type - povinnost M
- [x] mods:originInfo:dateIssued:point- povinnost M
- [x] mods:originInfo:dateIssued:qualifier- povinnost R
- [x] mods:physicalDescription - povinnost MA
- [x] mods:subject:authority - povinnost MA
- [x] mods:location:physicalLocation - doplnit

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tady to sice je správně podle standardu, ale přihlédneme-li k textu v popisu elementu, prosíme o úpravu. Díky.
- [ ] mods:titleInfo:type - povinnost M změnit na MA
- [ ] mods:originInfo:dateIssued:point- povinnost M změnit na O

**Comment by kerschfilip** [comment]
Bylo by možné upravit kartu "Form" tak, aby bylo pole `Value` výběr z roletky stejně, jako ve starém rozhraní? 
![image](https://github.com/proarc/proarc-client/assets/57805328/a5902363-aa48-46b3-986b-0e47550504ef)

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
