### ISSUE TITLE
NDK zvukový dokument (Standard 0.5)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#359]
- [x] mods:originInfo:dateIssued:hodnota - povinnost M
- [x] mods:physicalDescription:form:type - přidate element
- [x] mods:genre:hodnota - povinnost MA
- [x] mods:relatedItem - přidat element

**Comment by katerinasirova** [comment]
@SykoraLukas - chtěla jsem se zeptat, jak to vidíš s realizací? Dnes jsme se s Bárou R. domlouvaly, že se gramodesky začnou zpracovávat na začátku srpna, tak ať víme, co a jak. Díky

**Comment by katerinasirova** [comment]
Díky @SykoraLukas  - jakmile se vrátím příští týden z dovolené, tak se pustím do testů na inovatice.

**Comment by katerinasirova** [comment]
formulář:
mods:name:hodnota MA - při stažení záznamu z katalogu se vyplní autority, které potřebujeme umazat, po umazání všech autorit se při snaze uložit záznam zobrazí hláška nevalidní data (požaduje se vyplnění povinného podpole), kterou je nutné překonat - je to docela matoucí, protože uživatel má potom pocit, že musí něco vyplnit

**Comment by katerinasirova** [comment]
Zdravím po návratu z dovolené, @SykoraLukas  - jak to vypadá s mými dotazy k implementaci nových standardů  - tady i u issue #360, #361?
Díky za info.

**Comment by SykoraLukas** [comment]
Nasazeno na testovaci 2023. Můžeš otestovat. https://proarc-2023.inovatika.dev/search

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
