### ISSUE TITLE
zachovani sloupcu (#10)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#36]
pokud si v indexovani v leve casti obrazovky upravim zobrazovane sloupce, tak 
pri pristim prihlaseni jsou jiz opet defaultni. bylo by mozne zapamatovat si je 
pro kazdeho uzivatele?

**Comment by luckajirku** [comment]
Pamatování na stanici funguje.

**Comment by luckajirku** [comment]
za nás lze issue zavřít
