### ISSUE TITLE
NDK úroveň skladby (Standard 0.5)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#360]
- [x] mods:classification:edition - povinnost M
- [x] mods:classification:hodnota - povinnost R
- [x] mods:subject:name:type - povinnost RA
- [x] mods:subject:name:namePart - povinnost R
- [x] mods:subject:name:nameIdentifier - povinnost RA
- [x] mods:relatedItem - doplnit element

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by katerinasirova** [comment]
mods:subject:temporal - při stažení metadat z katalogu se chronologické věcné třídění (v tomhle případě  hodnota "20. století") vytvoří jako samostatný záznam a požaduje vyplnění min. hodnotu v mods:subject:topic - jenže ta je vyplněna v jiném samostatném záznamu

<img width="343" alt="image" src="https://github.com/proarc/proarc-client/assets/8912422/83c97a02-8e2d-4358-a7cd-eb4d01afefde">


XML:
<mods:subject authority="czenas">
        <mods:temporal>20. století</mods:temporal>
    </mods:subject>

Je chyba u nás v datech, jak se stahují přes OAI? Koukala jsem do DK v Hradci (ze 2022/07) i tam mají stejně uvedené klíčové slovo "20. století"

Př. název=Lašské tance, uuid: f476b73b-75a0-471b-a76d-f760bec83521, pro stažení metadat z Koniáše: 001=4531699

**Comment by SykoraLukas** [comment]
Tak to netusim. Ted to mate tak, ze to je ve více elementech tak se to i stejně stáhne do aplikace. Pole Topic je ale v subjectu, ktery je cely R, takže by neměl být Topic povinný, pokud není vyplněno nic. Pokud je ale vyplněno alespoň něco, tak by to povinné být mělo, aspoň takhle chápu tuto povinnost. Takže dotaz na popis asi spíše na nějaké jiné knihovníhy, kteří by snad mohli poradit.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, zvukové dokumenty nezpracováváme, na nich to nevyzkoušíme. Ale až půjde klient na Inovatice, zkusím chování v nových formulářích monografií.

**Comment by katerinasirova** [comment]
Díky, tenhle problém nám vyvstal právě u monografií, ale tam mi to přišlo už "spravené" - že se chyba nevyskytuje tolik, tak proto se ptám, jak jsou na tom ostatní - a rovnou doplním do původního dotazu že nejde o zpracování jen zvukových dokumentů, které vím, že kromě nás zpracovává v PA jen NM/ČMH, ale obecně o převod tohohle pole - nemám to raději vytáhnout jako samostatné issue?

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, máme sysno = 002695932 (monografie v katalogu KNAV - https://katalog.lib.cas.cz/KNAV/Record/002695932). Obrázek ukazuje, jak se 20. století stáhlo - samostatný subject, což je myslím správně. Nic jiného se do toho elementu nevnucuje, chybu to nehlásí. Je to na inovatice pod 243c3f38-ed05-459e-a052-ac0bf1bb06aa, jako superadmin bys to mohla i měnit.


![image](https://github.com/proarc/proarc-client/assets/79305516/9f6e0e55-92af-4ba8-9a54-91ba4b250a43)

**Comment by ZdenkaSera** [comment]
@SykoraLukas @katerinasirova Ještě poznámka k to povinnosti Topicu, resp. odděleným elementům. Podle mého se pro každý "subject" v katalogu vytváří vlastní element a není v jednom elementu společně např. "geographic" a "temporal" nebo "topic", je to buď a nebo. Jen formulář obsahuje vždycky všechna pole. Takže při vyplněném "temporal" by si Topic myslím neměl nic vynucovat.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Máš pravdu, už jsem to taky zjistila a chtěla jsem to zkusit na příkladu kapitoly, tam je Topic taky M. Ale ve formuláři je chyba, topic nejde vůbec doplnit. Ale to ještě napíšu do patřičného issue. Jinak jsem porovnávala popisy modelů ve standardu a zřejmě je Topic jako povinný na nejnižších úrovních.

**Comment by katerinasirova** [comment]
Díky @ZdenkaSera za testování.
Takže je to tak, jak jsem myslela - tzn., že se kontroluje povinnost pro celý blok a pokud je tam M pro Topic, tak to bude vyžadovat vyplnění vždy. Dá se to nějak vyřešit jinak než tak, že změníme standard na MA? To bude zase nějakou dobu trvat...

**Comment by SykoraLukas** [comment]
Změníme to hned na MA, ale nebude to odpovídat standardu. Jinak se to těšit nedá, M pole se kontrolují napříč všemi elementy u všech modelu, takže se nedá udělat výjimka u tohoto elementu. Druhá možnost je, že to bude křičet a nikdo tomu nebude věnovat pozornost, což není dobre, protože se díky tomu přehledne jinak chyba, která je opodstatnění.

**Comment by ZdenkaSera** [comment]
@katerinasirova Někde je topic R, někde MA a někde M, těžko říct, jestli to byl omyl nebo je za tím nějaký úmysl.  Napadá mě teď jediné řešení: protože víme, jak to má fungovat a že se topic správně stahuje z katalogu, pokud je tam uveden, shodneme se v týmu na tom, že necháme nastavit MA místo M .... A paralelně to otevřeme s NK.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Naše komentáře se minuly  - ok, na schůzce si to potvrdíme.

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
