### ISSUE TITLE
NDK část skladby (Standard 0.5)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#361]
- [x] mods:name:type - povinnost MA
- [x] mods:name:nameIdentifier - povinnost RA
- [x] mods:typeOfResource - povinnost M
- [x] mods:relatedItem - doplnit element

**Comment by SykoraLukas** [comment]
Toto issue je součástí https://github.com/proarc/proarc-client/issues/352

**Comment by katerinasirova** [comment]
Ve formuláři:
- mods:name - hodnota nemusí být vůbec vyplněna (je správně RA), ale při snaze celou autoritu umazat hlásí nevalidní data , je třeba hlášku překonat, uložit a teprve potom se celý záznam opravdu smaže - můj dotaz - má to vůbec hlásit, když není povinné cokoli vyplnit?
- mods:typeOfResource - defaultně při vytváření vyplnit hodnotu "sound recording" (teď se automaticky z metadat nevyplní a zbytečně klient hlásí nevalidní data)
- mods:relatedItem - když se z metadat stažených z katalogu propíšou data do related item, klient po umazání při snaze uložit hlásí nevalidní data (stejný případ jako mods:name - viz první bod)

**Comment by katerinasirova** [comment]
Díky, prosím o nasazení na test co nejdříve, Olga čeká na pokyn ke zpracování a bez těchto oprav to nepůjde.

**Comment by katerinasirova** [comment]
Otestováno v proarc-master:
- mods:name - i po odstranění položky name a následné úpravě jiných metadat to při uložení hlásí, že jdeo nevalidní data a chce znovu vyplnit name, i když je R
- mods:typeOfResource - nabízí jako jedinou vybranou hodnotu, ale samo o sobě není automaticky vyplněno - @SykoraLukas je možné, aby se prostě vždy u NDK části skladby vyplnila automaticky hodnota "sound recording"?
- mods:relatedItem - vypadá opraveně

**Comment by SykoraLukas** [comment]
@katerinasirova jsou to veci z Visku23, musi se to testovat ve vetvi proarc-2023.
https://proarc-2023.inovatika.dev/repository/uuid:9e740adf-d245-47cc-9ea4-85b9dbc489eb

**Comment by katerinasirova** [comment]
Já si říkala, kde mám testovat :-) Otestováno, opraveno, díky.
@SykoraLukas můžeš nám prosím vydat verzi, abychom mohli nainstalovat u nás a konečně umožnit Olze zpracování gramodesek do VISKu? Díky

**Comment by SykoraLukas** [comment]
Vydat to můžeme, ale je tam dost věci, které nejsou otestované. Takže se s tím musí počítat.

**Comment by SykoraLukas** [comment]
Vzhledam k tomu, že jsou nové standardy a probíhá na ně update v issue https://github.com/proarc/proarc-client/issues/527, zavírám toto issue.
