### ISSUE TITLE
Import - reindexovat nefunguje u skenů popsaných přes Označit řadu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#363]
Při testování reindexace přes tlačítko reindexace v importu jsme narazili na to, že někdy se ta dávka reindexuje a jindy ne. A vypadá to, že to nefunguje u stran, které byly předtím načíslovány přes fci Označit řadu. Pokud tam pak ručně změním nějakou hodnotu nebo přesunu sken a uložím, tak při reindexaci se u tohohle skenu změní index na správný, ostatní skeny to ignoruje. Je to tak úmyslně? Ta fce by se měla chovat stejně v celé dávce nezávisle na tom, jak se k hodnotám dospělo, ne?

**Comment by SykoraLukas** [comment]
Opraveno pro nové dávky. Doplněno i dogenerování Indexů, pokud uživatel odklikne u importu, že nechce generovat.

**Comment by luckajirku** [comment]
@SykoraLukas Co znamená "nové dávky"? Jako úplně nové, ty, co teprve dostaneme do nových složek? Totiž teď jsem načetla nově dávku, načíslovala přes Označit řadu - a reindexace pořád nezabírá.

**Comment by luckajirku** [comment]
A dělal jsi to předtím přes tu řadu? Teď jsem ti tu tvoji dávku přeindexovala přes řadu - a reindexace pak nic. Zkus si to.

**Comment by SykoraLukas** [comment]
Ted jsem to vratil do puvodniho stavu a funguje to. Muzes to prosim udelat jeste jednou ale udelat snimek toho jak jsi se do toho stavu dostala? 

Idealne jen hromadnou editaci (co mas zaklikane) + pak hned poustis tu reindexaci pres tlacitko? Ja vidim, ze to bylo rozbite (vytvoril se jeden element part navic, ale nedokazu zreplikovat jak se ten element navic vytvori).

**Comment by luckajirku** [comment]
Hromadná editace a následná reindexace přes tlačítko je OK. Problém nastává, pokud je to předtím předindexované ne hromadnou editací v tom základním okně, ale přes Označit řadu. Čili popíšeš si pár stran, označíš, stiskneš tlačítko Označit řadu, v tom vyskakovacím okně pak označíš další strany, na které zkopíruješ popis (vč. indexu) z těch vybraných stran (viz obr). Pak v hlavním okně klikneš na tlačítko reindexace - a nestane se nic, zůstávají indexy tak, jak byly v tom vyskakovacím okně. 
![reindex_rada](https://user-images.githubusercontent.com/6359479/233384807-f5430374-fbb8-4b86-bf03-7defc46211b1.png)

**Comment by SykoraLukas** [comment]
Díky, tak ja opravil jinou chybu co tu byla. Opravím i toto.

**Comment by SykoraLukas** [comment]
Opraveno (jestli jsem to pochopil).

**Comment by luckajirku** [comment]
Vypadá to, že pochopil:-). Opraveno.

**Comment by ZdenkaSera** [comment]
Funkční jak po úpravách v "označit řadu", tak po importu bez generovaného iniciálního indexu.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
