### ISSUE TITLE
Hledat - nastavení lišty do libovolné výšky

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#364]
Když chci v "Hledat" tažením lišty zmenšit (nebo zvětšit) horní část obrazovky, jsou teď trochu omezené možnosti. Zmenšení jde, pokud si nahoře nechám dva řádky - na míň ani víc to nejde, lišta skočí hned zpátky. A to samé v okně pro rozřazování stran, jen tam to nahoře jde místo dvou na jeden řádek (a to je ještě potřeba hodně dobře to trefit, aby se lišta chytla, jinak zase skočí zpátky).

**Comment by albertoh** [comment]
Vyska lze menit. Je nutne vyresit prvni nastaveni.

**Comment by pkudela** [comment]
fixed, alberto opravil

**Comment by luckajirku** [comment]
V tom základním hledacím okně už je to OK, ale u rozukládávání stran lišta pořád nedrží a skáče zpátky.

**Comment by albertoh** [comment]
Uz je to i tam

**Comment by luckajirku** [comment]
Za nás OK. Je to tam, funguje - a jde dokonce vytáhnout až úplně nahoru. V Hledat se zasekne u té šedé hlavičky pro hledání, u rozřazování jde lištu vytáhnout přes ni až úplně nahoru. Nevím, jestli to byl úmysl, ale vlastně je to fajn, protože se ten prostor hezky komplet využije.

**Comment by pkudela** [comment]
U hledani ano, tam se to zasekne u hlavicky s vyhledavanim, to uz je jiny element stranky.

**Comment by luckajirku** [comment]
Aha, tak ještě něco. Ono si to pamatuje, do jaké výšky byla lišta naposled vytažena, ať se ukládá dávka z importu do úložiště, nebo se rozukládává v rámci úložiště. Rozřazuju strany, vytáhnu si lištu úplně nahoru, abych viděla ze stromu co nejvíc. A pak jdu popisovat další dávku, chci uložit do objektu - a lišta je nahoře... 
Musí to být tak, že buď si pamatuje pozici a projeví se to všude (tahle varianta za nás ne), nebo si ji nepamatuje vůbec a pak bude ta lišta vždy při novém otevření úložiště defaultně v půlce? Nebo to jde vázat na to, jestli je to při ukládání z importu nebo přesun v rámci úložiště? 
![lista_nadrazobjekt](https://github.com/proarc/proarc-client/assets/6359479/c8a50ce7-c3ac-4ebf-b14e-c34f583ab7c7)

**Comment by albertoh** [comment]
Muzu delat cokoli: pamatovat vsude, pamatovat jen nekde, nepamatovat...
Dokonce muzu i pri znovu otevreni overit nejaky minimum.
Napiste vy co radsi

**Comment by luckajirku** [comment]
Tak jestli cokoli:-), viděli bychom to takhle:
- hlavně - nevázat na sebe lištu v hlavním Hledat a lištu v rozukládávání - každé si pamatuje svoje nastavení.
- ta hlavní obrazovka Hledat - jako je to ve starém - při přihlášení je lišta v polovině, pak si to pamatuje nastavení lišty v průběhu toho jednoho přihlášení, po odhlášení a novém přihlášení se zase vrátí do defaultního nastavení.
- přesun - rozukládávání stran - tam by bylo nejlepší, kdyby při přihlášení byla lišta v polovině, potud stejně jako v tom hlavním, ale potom aby si to pamatovalo nastavení jen v průběhu toho jednoho rozukládávání. Čili jak zavřu to vyskakovací okno, při dalším rozukládávání i při tom samém přihlášení se posune lišta zase do poloviny. (Pokud by tohle bylo už moc, tak to udělej stejně jako u hlavního Hledat - pamatovat do odhlášení a po přihlášení vrátit do poloviny.)

**Comment by albertoh** [comment]
Hotovo podle zadani

**Comment by luckajirku** [comment]
super, hotovo dle zadání, funguje, za nás už bez připomínek:-)

**Comment by ZdenkaSera** [comment]
Pěkné

**Comment by katerinasirova** [comment]
Otestováno, super.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
