### ISSUE TITLE
Hledat - vyhledavaci formular se nevejde na obrazovku pri malem rozliseni

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#365]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/16591052/232709843-a687a872-2827-47ce-9a7f-dee374e2d362.png">

**Comment by pkudela** [comment]
- [ ] vyhledavaci formular se nevejde na obrazovku pri malem rozliseni
- [ ] dodekat moznost zrusen aktivniho filtru krizkem, stejne jako je to v k7admin

**Comment by pkudela** [comment]
toto je hotove, prosim o otestovani

<img width="816" alt="image" src="https://user-images.githubusercontent.com/16591052/233163865-693758be-a5e7-45ea-bc37-72391d6ef795.png">

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by ZdenkaSera** [comment]
Poznámky k rozlišení také zde https://github.com/proarc/proarc-client/issues/370.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
