### ISSUE TITLE
Administrace uzivatelu

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#366]
- [x] predelat do tabulky, aby byly videt na prvni pohled vsechny nastavene parametry uzivatele
- [x] vytvoreni uzivatele bude smerovat na dedikovanou stranku
- [x] editace uzvivatele bude smerovat na dedikovanou stranku
- [x] vytvorit breadcrumbs

**Comment by ZdenkaSera** [comment]
zatím ok, praxe ukáže. díky

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
