### ISSUE TITLE
Pokud se aplikace automaticky odhlasi -> presmerovat na login stranku

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#367]
Pokud aplikace automaticky odhlasi uzivatele tak presmerovat na prihlasovaci stranku.

**Comment by ZdenkaSera** [comment]
Tady jen info o současném chování klienta (i jádra): neodhlašuje viditelně, zůstává na poslední použité obrazovce a člověk zjistí, že je session "mrtvá" až při pokusu o novou operaci.

**Comment by pkudela** [comment]
toto je na @SykoraLukas a @albertoh

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh  Díky, jen tohle neurgujeme do nejbližší verze (viz můj mail ze 6.9., který má Lukáš (a možná i ostatní) ve spamu)

**Comment by SykoraLukas** [comment]
Na API hotové. Volání je následující:

```
### SESSION IS LOGGED
GET {{proarcUrl}}/isLogged
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

```

**Comment by albertoh** [comment]
@pkudela formatuj, prosim, v navbar.html posledni element

**Comment by pkudela** [comment]
@albertoh hotovo, nasazeno, pripraveno k testovani

**Comment by albertoh** [comment]
Pro ucely testovani mame na nasem serveru jen 5 min

**Comment by ZdenkaSera** [comment]
@albertoh @pkudela Už jsem neplánovaně vyzkoušela při sledování exportu - funguje, díky. (Nemám úplně jasno, které operace resetují počitadlo a které ne, ale to ukáže praxe :-))

**Comment by pkudela** [comment]
Jeste jsem fixnul preklad u popup okna po odhlaseni, nasazeno.

**Comment by pkudela** [comment]
+ jeste davam na vyber jinou variantu, decentnejsi, na screenshotu, zde v zavislosti na zbyvajicim casu do odhlaseni neubyva cele tmave pozadi, ale pouze dolni bila cara

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/75b4baa9-0fa3-4a85-8ec1-87e579bae70e">

**Comment by ZdenkaSera** [comment]
@pkudela Do konfigurace instance přidat on/off pro zobrazení počitadlo - varinanta s bílou šárou.

**Comment by pkudela** [comment]
Hotovo, do konfigurace pridat `showLogoutCounter: true / false`, pricemz pokud tato properta neni v konfiguraci zadana, tak vychozi stav je, ze se pocitadlo zobrazi a to na zaklada reakci ze schuzky, ze vetsine to pocitadlo nevadi.

Na zaklade hodnoty teto property se bud pocitadlo odhlaseni zobrazi, ci nikoliv viz. screenshoty nize.

<img width="476" alt="image" src="https://github.com/user-attachments/assets/2e58e590-4b27-4976-a72d-ab94a22e074e">

<img width="512" alt="image" src="https://github.com/user-attachments/assets/7feb4cea-34df-4b08-afa0-5d6b87717278">

Zapracoval jsem tu decentnejsi variantu dle dohody.

**Comment by ZdenkaSera** [comment]
@pkudela Díky. Dovolila jsem si označit to k testu :-)

**Comment by pkudela** [comment]
> @pkudela Díky. Dovolila jsem si označit to k testu :-)

Jeste jsem to nenasadil na server, ale to nevadi, udelam to ted.

**Comment by pkudela** [comment]
hotovo, nasazeno na serveru

**Comment by ZdenkaSera** [comment]
Po odladění jsme už v KNAV nenarazili na technické potíže, nikdo jiný také nerozporoval - issue navrhuji k zavření a @pkudela prosím o zařazení posledních úprav do nejbližší verze. Děkuji.


(U některých operací si jako uživatelé nejsme jisti, proč nemají vliv na refresh počitadla, ale  dotazy k tomu možná po delší době provozu.)

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
