### ISSUE TITLE
Správa dávek - editace

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#368]
Tlačítka
- [x] Tlačítko `Mřížka` odstranit
- [x] Tlačítko `Zkrácené popisky` odstranit
- [x] Tlačítko `Změna pozice` odstranit
- [x] Tlačítko `Vybrat sloupce` - přesunout do Nastavení v Profilu
- [x] Tlačítko `Náhledy` budou mít nově ikonu od tlačítka `Mřížka`
- [x] Tlačítko `Vybrat vše` bude nově ikona `Validace`
- [x] Poslat sadu ikonek ať si uživatelé mohou vybrat adekvátní ikonu Validace, Označit řadu (případně nové dle nově založených issue)

Tabulka
- [x] Tabulka / Typ Strany  - data v tomto sloupci se se nezalamují

Popis stránky
- [x] Tlačítko `Komentář` odstranit
- [x] Tlačítko `Obrázek` odstranit
- [x] Tlačítko `Vrátit původní` přejmenovat na `Obnovit` a změnit ikonu na `Obnovit`
- [x] Lišty `popis objektu` a lišta s ikonama (MODS, OCR, ...) sjednotit do jedné lišty
- [x] Ikona `Administrativních a technických metadat` nahradit textem `A`

Obrázek
- [x] Ikony stáhnout doleva
- [x] Popisek lišty odstranit

Úprava / Hromadná úprava
- [x] při změně zobrazit bar, že změna probíhá
- [x] po uložení zobrazit bar, že změna byla provedena

**Comment by luckajirku** [comment]
Teď si jen nejsem jistá - tu ikonu pro změnu pozice jsme chtěli tady odstranit úplně? Měla jsem za to, že jenom hodit pod tři tečky (i když teď to vypadá, že by tam byla asi sama).

**Comment by ZdenkaSera** [comment]
Myslím, že ji chcete (skrytou) zachovat jen v editaci s tím, že v importu nemá význam. Snad si to pamatuju správně :-)

**Comment by luckajirku** [comment]
To právě nevím, ono tam nejdřív zaznělo, že to není třeba, protože to jde dělat jinak, že přesun zvládne fce "pozice strany" ve formuláři - ale to jsme si tam pak vysvětlili, že je to něco jiného (pravá-levá...). To by asi mohla rozseknout @nezbedova ?

**Comment by ZdenkaSera** [comment]
To je pravda, ale pořád si myslím, že se to týkalo editace @nezbedova

**Comment by nezbedova** [comment]
Spletla jsem si tlačítka _Změna pozice_ a _Pozice stránky_ Raději to nyní rozepíši.

Změna pozice se používá pro přesun strany na určité místo. Např. hřbet z posledního místa (tak bylo pořadí skenování)
na 3. místo (podle pravidel popisu). 
Na schůzce se ukázalo, že to nikdo nepoužívá. Proto jsme se dohodli, že to v Import/Správa dávek/Editace - odstraníme.
Ale aby tu tato možnost úpravy byla, tak zůstane skrytá  za tečkami v Hledat

**Comment by luckajirku** [comment]
@pkudela pro fci označit řadu by se nám víc líbila tahle ikona (ale převrácená, s bílou výplní):
![oznacitradu](https://github.com/proarc/proarc-client/assets/6359479/13d803f7-a3a6-4d84-a089-50a4f250e71d)

**Comment by luckajirku** [comment]
a pro vybrat vše by byla dobrá jedna z těchle dvou. Ta původní validační, kterou jsme tam chtěli dát, už se nám moc nepozdává takhle při pohledu na tu lištu teď... Tyhle ikony mají jen dva řádky, takže se nebude na pohled plést s reindexací atd. (navíc nám teď do Nastavení zmizí i nastavení sloupců, které má podobnou ikonu, takže je to úplně OK).

![vybratvse](https://github.com/proarc/proarc-client/assets/6359479/6015ce09-25d6-4272-bb7e-c438d287fc3c)

**Comment by pkudela** [comment]
hotovo
<img width="678" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/b33a55c9-f1d3-45c6-b5c5-b0ec769286ea">

**Comment by luckajirku** [comment]
ještě za nás návrh na změnu pořadí ikon, aby to šlo v logičtějším pořadí (jde jen o pořadí, menších/větších mezer netřeba si všímat):
![ikony_import_poradi](https://github.com/proarc/proarc-client/assets/6359479/789ce094-baaa-4d40-8ad1-b273ffdaa4d2)

**Comment by pkudela** [comment]
@luckajirku rychly dotaz k bodu 
<img width="228" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/8657fdd6-eb38-4ffa-abe6-144a1aae479c">
Mam toto udelat i u ostatnich component, odtranit popisek a ikony dat do leva, jak napr. ocr, media, premis, komentar atd. at je to sjednocene?

**Comment by pkudela** [comment]
poradi ikon zmeneno, je to tak jak si to chtela? Ty designove veci, mezery atd. budu resit az vsechny tyto zmeny budou hotove a od vas schvalene, je toho hodne

<img width="617" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/5afeb582-520c-47a2-b230-2817aaa0258f">

**Comment by luckajirku** [comment]
> Mam toto udelat i u ostatnich component, odtranit popisek a ikony dat do leva, jak napr. ocr, media, premis, komentar atd. at je to sjednocene?
no na schůzce jsme se tak dohodli. A že se všude, i v tom pravém sloupci, ikony srazí doleva, s tím jsi přišel přímo ty:-). Uživatelsky je to rozhodně lepší. A k tomu řádku s popisem - ono člověk ví, co si navolil do toho kterého panelu (teda doufejme:-)). A potom jen pro tu vizuální kontrolu bude fajn, když bude pak výrazněji vyznačená ta právě aktivní volba na liště (jak to teď dost splývá, ta modro-modrá).

**Comment by pkudela** [comment]
ok, z te schuzky si nemuzu vsechno pamatovat, pamatuji si, ze zarovnani jsem navrhl ja, ale nebyl jsem si jist, jestli odstraneni popisku mam provest i u tech ostatnich komponent. Barvy atd. budu resit az po tech strukturalnich zmenach.

**Comment by pkudela** [comment]
hotovo, posledni 3 body prosim @albertoh 

<img width="660" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/ab6ce058-d3f0-4fd0-aef6-44164162a1a9">

+ tu zmenu tykajici se presunu nadrazeneho toolbaru do editor component

**Comment by nezbedova** [comment]
S výběrem ikon i nastavením souhlasím.

**Comment by erikamirova** [comment]
Za MZK taky souhlasíme. :)

**Comment by albertoh** [comment]
Neni to na me :)
Vratim

**Comment by katerinasirova** [comment]
ZA MKP také souhlasíme.

**Comment by luckajirku** [comment]
už jsem to psala i do issue ke sloupcům, ale patří to i sem - tady pod třemi tečkami se v nastavení sloupců nabízí nastavení pro úložiště, mělo by se ukázat nastavení pro import

**Comment by luckajirku** [comment]
Tohle je taková záhada. Včera se nám ten výběr sloupců pod třemi tečkami chvíli ukazoval jako import, ale teď už se zas objeví nabídka editace dle modelů v úložišti.

**Comment by luckajirku** [comment]
Nevím, jestli je to zas jen něco dočasného - nabídka už je správně, ale když uložím změnu sloupců, napíše mi to Nastavení sloupců bylo upraveno, ale obrazovku mám šedou a musím dát refresh, abych se vrátila do editace.

**Comment by albertoh** [comment]
Docasne :) Uz je

**Comment by SmejkalovaAnna** [comment]
za nás také v pořádku

**Comment by ZdenkaSera** [comment]
Prošla jsem tohle issue a zdá se mi, že je to opravdu hotové - @katerinasirova prosím, potvrdíte i vy? Díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
