### ISSUE TITLE
Správa dávek - editace - vybrat nadřazený objekt

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#369]
Hláška o tom, kam chci ukládat - přisunout doleva, tučně černě (tak jak to je nyní jen odebrat barvy a zarovnat doleva)

**Comment by pkudela** [comment]
hotovo, nasazeno na server vypada takto:

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/16591052/233033596-09219306-e119-409f-8e20-b8139dd94b23.png">

**Comment by pkudela** [comment]
@luckajirku , @nezbedova , @SmejkalovaAnna , @katerinasirova prosim o kontrolu a pripadne uzavreni.

**Comment by SmejkalovaAnna** [comment]
@pkudela Za mě dobrý, spokojenost.

**Comment by nezbedova** [comment]
@pkudela Moc pěkné. Děkuji.

**Comment by luckajirku** [comment]
za nás taky OK

**Comment by katerinasirova** [comment]
za nás též OK

**Comment by erikamirova** [comment]
Za MZK taky OK.

**Comment by ZdenkaSera** [comment]
Všechzny knihovny ok, dávám návrh na uzavření.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
