### ISSUE TITLE
Hledat - editace

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#370]
Tabulka
- [x] Tlačítko `Mřížka` odstranit
- [x]  Tlačítko `Zkrácené popisky` odstranit
- [x]  Tlačítko Vybrat sloupce - přesunout do Nastavení v Profilu
- [x]  Tlačítko Náhledy budou mít nově ikonu od tlačítka Mřížka
- [x]  Tlačítko Vybrat vše bude nově ikona Validace
- [x]  Poslat sadu ikonek ať si uživatelé mohou vybrat adekvátní ikonu Validace, Označit řadu (případně nové dle nově založených issue)
- [x] Založit ikonu `3 tečky` (ostatní funkce)
- [x] `Vybrat všechny objekty` převést do 3 teček
- [x] `Změna pozice` převést do 3 teček
- [x] Přidat šipku `Dolu` a upravit do pořadí jako ve starém klientovi - @albertoh ikona dodana, prosim mrkni na tu metodu

Titulní metadata
- [x] Udělat klikací cestu o objektu (Monografie, Periodika, Zvuk)
- [x] Disable nepoužitelných ikon

**Comment by pkudela** [comment]
@luckajirku ahoj, posilam odkaz na ikony, lze v nich i vyhledavat, narp. na slovo validace to vyhleda nekolik ikon, ale ne vzdy to vylozene souvisi s nazvem ikony -> https://fonts.google.com/icons?icon.style=Filled&icon.set=Material+Icons
Prosim, dodejte ikonu pro tlacitko validace vzi. bod 6, pripadne specifikujte dalsi pripadne zmeny ikon.

**Comment by luckajirku** [comment]
@pkudela tuhle ikonu určitě ne, nic dalšího se šipkama tam, kde to není nutné. Původně jsme mysleli, že se prohodí ty ikony pro validaci a vybrat vše. Ale kulatý tvar by byl možná fajn - pokud se tam nedá ta, co je teď pro vybrat vše, tak za nás pro validaci jedna z těchhle (nejlíp ta první, ale inverzně, aby výplň byla bílá):

![validace](https://github.com/proarc/proarc-client/assets/6359479/043bfe7e-9be8-4381-b8d1-b57b27a605d8)

**Comment by pkudela** [comment]
ahoj @luckajirku supeer, nevadi, dulezite, ze jste si vybrali, cili dam tu prvni. Jeste se chci ujistit u tohoto bodu - "Tlačítko Vybrat vše bude nově ikona Validace" - to souvisi s bodem "Vybrat všechny objekty převést do 3 teček" - jestli je to to same, tak vybrat vse nebude mit zadnou ikonu, protoze je to v menu navigaci, kde se zobrazuji cele nazvy akce viz. screenshot, tak se jen ptam, jestli jsem to pochopil dobre, ze se jedna o tu samou polozku zminenou ve dvou vyse uvedenych bodech

<img width="797" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/9660b7a5-128b-477b-bfbb-4dd27bae8a0d">

**Comment by pkudela** [comment]
Jestli dobre rozumim, tak na adrese http://localhost:4200/repository/uuid: ...... bude "vybrat vsechny objekty" schovane pod 3 tecky, jak jsem poslal v tom screenshotu, ale na adrese http://localhost:4200/import/edit/.... ma byt viditelna? Pokud ano, tak v repo bude pod 3 teckama 2 polozky - "zmena pozice"a "vybrat vsechny objekty" a v importu jen 1 polozka - "zmena pozice", je to tak :-)?

**Comment by luckajirku** [comment]
ty odkazy mi nefungují, ale jo, to jsme se přeci bavili už na schůzce, že to teď tak vychází, že v importu bude pod ... jen 1 položka. Na druhou stranu nemyslím, že to tak bude navždycky, časem se vyvrbí nějaké fce, které tam přijdou.

**Comment by pkudela** [comment]
jo, to je v pohode, ja se jen chtel ujistit, jestli to chapu spravne, protoze obe url pouzivaji stejnou listu, takze to musim nejak v kodu podminit, jinak jak pises, casem tam muze byt neco navic, pripadne treba zjistite, ze se casem jeste neco pod 3 tecky presune

**Comment by luckajirku** [comment]
ale tak těch rozdílů tam máš přeci víc, v Hledat je převod stran, v Importu ne, naopak zas v Importu je Označit řadu, ale v Hledat ne...

**Comment by pkudela** [comment]
ikona validace vymenena

<img width="598" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/cd873bc5-8748-424b-8cd8-abab5106d797">

**Comment by luckajirku** [comment]
@pkudela jen taková drobnost:-) - není ta ikonka validace dole trochu uřízlá?

**Comment by pkudela** [comment]
ano, opraveno
<img width="549" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/2a355d98-ba44-4659-b9f1-95ac9685afd9">

**Comment by luckajirku** [comment]
a ještě návrh na změnu pořadí ikon + na změnu pluska k vytváření objektů, aby bylo výraznější - je to tady hodně důležitá fce, tak ať je pořádně vidět
![ikony_hledat](https://github.com/proarc/proarc-client/assets/6359479/309ca7a9-c243-4997-8fca-1beb9a7c7f60)

**Comment by pkudela** [comment]
hotovo, je to tak spravne?

<img width="597" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/60572650-b223-4903-80f7-5c2abb68073d">

**Comment by luckajirku** [comment]
A ještě bych se teda zbavila toho slova Home. Zbytečně zabírá místo - a o to míň znaků se tam pak vejde z názvu. Samotná ikona domečku úplně stačí - pokud už teda musí být na tomhle místě ta fce, když to samé dělá i klik na logo PA.

**Comment by pkudela** [comment]
zatim jsem odstranil jen text

**Comment by katerinasirova** [comment]
@nezbedova a @SmejkalovaAnna a já se domluvit na použití ikon budíčků

**Comment by SmejkalovaAnna** [comment]
@pkudela Petře já se omlouvám, úplně se nepamatuji, co jsme přesně chtěli s těmi budíky, můžete mi zavolat prosím do Jenštejna na 315315382? Abychom si to ujasnili...

**Comment by pkudela** [comment]
Prosim, muzete mi nekdo poslat link na testovaci server, kde je problem v nize uvedenem bode?

**Udělat klikací cestu o objektu (Monografie, Periodika, Zvuk)**

Proklikaval jsem to, Alberto take a zda se mi, ze vsude klikaci cesta je, dekuji.

**Comment by luckajirku** [comment]
Jestli se nepletu, tak tam byl problém, jak se vracet na metadata titulu. Přijdu do periodika, vidím metadata titulu. Nakliknu nějaký ročník - a už vidím metadata ročníku a nemám jak se vrátit na metadata titulu. To samé u monografie, když nakliknu nějakou stranu, už nemám jak se dostat na metadata titulu. Svádí to k tomu kliknout na název - ale ten není v tu chvíli klikací, protože právě tu úroveň má člověk otevřenou. V těchhle případech funguje dát Obnovit - a metadata titulu jsou zpátky - ale není to moc intuitivní. Nemohlo by to fungovat tak, že ta titulová úroveň by byla neklikací pouze v případě, že by nebylo nakliknuté nic pod ní, a ve chvíli, kdy označím stranu, ročník atd. a dostanu se na metadata podřízeného modelu, už se odkaz na titul zaktivní?

**Comment by pkudela** [comment]
Udělat klikací cestu o objektu (Monografie, Periodika, Zvuk) - toto je take hotovo, nasazeno na serveru, prosim otestovat

**Comment by luckajirku** [comment]
ještě k bodu "Přidat šipku Dolu a upravit do pořadí jako ve starém klientovi" - šipka tam je, ale popisek při najetí myší je stejný jako u šipky nahoru:-).

**Comment by SmejkalovaAnna** [comment]
@pkudela Už asi vím ty budíky. Navrhuji: 

- Aby v okně Formuláře, bylo primárně nastavená ikona diskety jako neaktivní. Ve chvíli, kdy klepnu do formuláře, že chci něco upravit, tak by naskočila aktivní a po odklepnutí zase změnila na neaktivní (aby bylo jasno, že jsem to uložila nebo že je to v editaci):

![obrazek](https://github.com/proarc/proarc-client/assets/24409660/e4417a9b-7092-4ed0-913b-2ab92bc8a359)
Zároveň, by se při editaci formuláře podbarvoval element v MODSu a po uložení formuláře by se zároveň uložila i změna v MODSU. 

- v okně MODS - vyhodit oba budíky, nechat jen obnovit a disketku, která bude zase neaktivní pokud nezačnu měnit formulář nebo samotný MODS, zaktivní se pro uložení změn. Zároveň zase pokud bude něco opravováno v MODSU a bude na to chlíveček, promítne se to v reálném čase do formuláře. (teď to jde jen obráceně - z Formuláře se to v reálu propisuje do MODSU, když mám odklepnutý správný budík) 

- a co na to @luckajirku ?

**Comment by luckajirku** [comment]
jo a ještě jedna věc k té šipce dolů - na téhle liště zatím chybí - když už se přidává do těch panelů, tak by měla i sem
![spikadolu](https://github.com/proarc/proarc-client/assets/6359479/d36f5b73-cf72-4fe1-a142-cf70616d0491)

**Comment by luckajirku** [comment]
Budíky bych reklamovala u Lukáše, že to nedostatečně zapsal:-). Já se od nich distancuju, šlo to trochu mimo mě a nepamatuju si to. Byla tam nějaká diskuse k tomu, že se ty budíky pletou, taky jakou verzi přesně to načte atd. Myslím, že když se @SykoraLukas zasnaží, tak si to vybaví. A nebo to rozsekne @katerinasirova, ta se k tomu na poslední schůzce hlásila.

**Comment by luckajirku** [comment]
ještě k té ukládací ikoně - v metadatech strany u formuláře je taky vysvícená pořád, asi by se to mělo změnit i tam

**Comment by SmejkalovaAnna** [comment]
@luckajirku Dobře, díky, já si to právě taky moc nepamatovala, ale tohle jsem vymyslela, jak by to mohlo fungovat relativně intuitivně. Ještě poprosím zítra @ZdenkaSera, aby se mrkla, jestli jsem tam nevymyslela nějaký nesmysl....

**Comment by SmejkalovaAnna** [comment]
@pkudela Petře za mě perfektní 👍  Dokonce je to tak chytrý, že když něco smažu v MODSu a napíšu tam to samý, tak to pozná, že už to tam bylo a zneaktivní uložení, to jsem fakt nečekala 🥇

**Comment by pkudela** [comment]
Ja tedy budicky zatim neresim do doby, kdy dostaneme jasne zadani na kterem se vsichni shodnou, Alberto to od @SmejkalovaAnna procital a jestli to pochopil spravne, tak by to nebylo zas tak jednoduche, tak abysme nedelali neco zbytecne z nepochopeni, souhlasis Anicko?

Co se tyce te ukladaci ikony @luckajirku Lucko, tak na to se podivame a pripadne opravime, dik za upozorneni.

**Comment by SmejkalovaAnna** [comment]
@pkudela Souhlasím.

**Comment by pkudela** [comment]
Disable ikony "save" na strance Alberto opravil.

**Comment by albertoh** [comment]
Jsou k testovani

**Comment by katerinasirova** [comment]
K budíčkům - když jsme to testovali, tak mi přišlo, že tak jak to bylo nastavené všechny ikony dávaly smysl, ALE podle mě to nikdo takhle nepoužíval.
Nevím, jestli někdo měl ideu, že se mu z nějakého důvodu změny nemají propisovat z XML do MODS. Ale za nás to nikdo nikdy nepoužil.
Přemýšlím, jestli je dobré mít na první dobrou do kliknutí v XML možnost hned něco měnit. Tam se totiž může ukliknout a napsat něco někam, ani nevíš jak. Takže za mě by mohla zůstat jen ikona upravit a uložit (a ta disketa už se může chovat tak jak bylo popsáno výše). Pokud bude fungovat podbarvení, budeme jen rádi, práce se pěkně zpřehlední. 
Dávám dotaz na ostatní, jak s ikonou upravit? Jinak souhlasím s @SmejkalovaAnna  - viz níže.

> @pkudela Už asi vím ty budíky. Navrhuji:
> 
> * Aby v okně Formuláře, bylo primárně nastavená ikona diskety jako neaktivní. Ve chvíli, kdy klepnu do formuláře, že chci něco upravit, tak by naskočila aktivní a po odklepnutí zase změnila na neaktivní (aby bylo jasno, že jsem to uložila nebo že je to v editaci):
> 
> ![obrazek](https://user-images.githubusercontent.com/24409660/241201076-e4417a9b-7092-4ed0-913b-2ab92bc8a359.png) Zároveň, by se při editaci formuláře podbarvoval element v MODSu a po uložení formuláře by se zároveň uložila i změna v MODSU.
> 
> * v okně MODS - vyhodit oba budíky, nechat jen obnovit a disketku, která bude zase neaktivní pokud nezačnu měnit formulář nebo samotný MODS, zaktivní se pro uložení změn. Zároveň zase pokud bude něco opravováno v MODSU a bude na to chlíveček, promítne se to v reálném čase do formuláře. (teď to jde jen obráceně - z Formuláře se to v reálu propisuje do MODSU, když mám odklepnutý správný budík)
> * a co na to @luckajirku ?

**Comment by SmejkalovaAnna** [comment]
@katerinasirova s Katkou souhlasím, přesně, jak píše. Ikony disable save jsem otestovala, viz víše.

**Comment by katerinasirova** [comment]
> Provedl jsem nasledujici zmeny:
> 
> * tooltip pro ikonu dolu jsem zmenil, mrknete, jeslti text vyhovuje
> * ikonu dolu jsem pridal do toolbaru a dodrzel poradi ikon, jako je to v editaci
> * nasazeno na serveru - prosim tyto 2 body otestujte vcetne te ikony save, respektive jejiho zneaktivneni
> 
> Co se tyce tech budiku, pockame s Albertem na vyjadreni @luckajirku , jinak stav ikony "save" je opraveny, nyni je disablovana jak si chtela v tom prvnim bode @SmejkalovaAnna

Otestováno:
* text tooltipu OK
* ikona také OK
*  zneaktivneni ikony save u metadat strany není, ale nechápu, jak se má chovat v kombinaci "metadata strany" a "toolbaru u tabulky" - v toolbaru u tabulky je zneaktivněná stále, u metadat je zase stále aktivní

![image](https://github.com/proarc/proarc-client/assets/8912422/b7c1f7a1-413d-40ed-9eb6-1f819e7921fb)

**Comment by katerinasirova** [comment]
Při testování na notebooku jsem objevila, že ikony šipek jsou hodně široké a při běžném zobrazení se ta čtvrtá přidaná šipka posune dolů a zbytečně roztáhne toolbar na dva řádky. Dotaz na @pkudela  - šířka/velikost těch ikon je daná nebo se dá upravit? Tady by totiž možná bylo vhodnější, aby ty 4 ikony byly víc u sebe... případně poprosím o komentář ostatní, jak to vidí oni.

**Comment by luckajirku** [comment]
o té šířce jsme se už bavili a Petr říkal, že to prověří

**Comment by pkudela** [comment]
ano, toto budu testovat az budu menit design cele aplikace, jak jsme se bavili na schuzce, kazdopadne to budu muset zmenit globalne, ale nikdy se nevyhneme tomu, ze nektera ikona bude mit kolem sebe vice mista, vsechny maji stejnou sirku, ale vizualne muzou nektere ikony pusobit tak, ze maji kolem sebe vice mista, protoze vypln kazde ikony je jina

**Comment by luckajirku** [comment]
no tady nejde ani tak o to, jak to působí vizuálně, ale z hlediska praktičnosti, je lepší, když jsou ty šipky blíž u sebe. Jako chápu, že nejde přizpůsobovat každé tlačítko ikoně a je to i nesmysl, ale kdyby byly dvě šířky (stávající pro normální tlačítka a užší pro ty šipky), to by se dalo, ne?

**Comment by pkudela** [comment]
@luckajirku asi by to slo, pokud by se to omezilo na 2 velikostii, udelam globalni class pro tyto ucely

**Comment by katerinasirova** [comment]
> @luckajirku asi by to slo, pokud by se to omezilo na 2 velikostii, udelam globalni class pro tyto ucely

Právě, díky. U ostatních ikon to není tak výrazné a tam je to jedno, ale tady by se to vyloženě nabízelo.

**Comment by ZdenkaSera** [comment]
@luckajirku @katerinasirova Snažila jsem se zorientovat a otetotvat - prosím, je to kromě potíží se zobrazením na notebooku hotové? Zdá se mi, že ano, ale prosím o info, zda bychom tohle mohli navrhnout k uzavření. Děkuji.

**Comment by luckajirku** [comment]
No já původně čekala, že to ještě zkontroluju, až půjde vyzkoušet i reindexace. Jestli jde teď jen o to, jestli jsou tlačítka tam, kde mají být, a vypadají tak, jak mají vypadat, tak ano (resp. v tuto chvíli, kdy to píšu, jsou OK). Klikací cesta do objektu už je taky funkční včetně přístupu k titulovým metadatům.

**Comment by luckajirku** [comment]
jj, myslím otestování bez toho, aby člověk musel proklikávat jednotlivé strany, jestli ty indexy sedí.

**Comment by ZdenkaSera** [comment]
@albertoh @pkudela Musím to znovu otevřít - funkce neaktivní ikony pro ukládání změn má svá úskalí.
1.ve formuláři jsem vymazala celý element (např. note) - nemám jak uložit, ale element zmizel, v xml zůstává vidět
2. použiju funkci obnovení na horní liště v edita ci - eleemnt ve formuláři stále není, v xml ano
3. vrátím se na obrazovku "hladat" a po zpětném otevření titulu v editaci je "vymazaný" element zpět i ve formuláři

Podle mého se stejného problému týkají i poslední poznámky  od @kerschfilip zde https://github.com/proarc/proarc-client/issues/316.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Vidíš Zdenko, toho jsem si nevšimla.... já zkoušela, že jakmile hrábneš do buňky ve formuláři, tak se ukládání zaktivní..... ale @albertoh a @pkudela mělo by to samozřejmě fungovat stejně, i když smažeš element....jakmile se jakkoliv něco začne měnit, tak zaktivnit ukládání.... 

- tu kontrolu chyb bych nechala, to není na škodu....

**Comment by albertoh** [comment]
Opraveno. Po mazani ulozit je aktivni

**Comment by ZdenkaSera** [comment]
@albertoh Funguje jen někde. Ikona se aktivovala např. při výmazu "Title info" v Related items, ale ne při výmazui alternativního názvu, note nebo elementu name. Můžeš si to zkusit na NDK monografii  841375be-9a7f-441a-a9c6-fdd7b893ed77

**Comment by ZdenkaSera** [comment]
@katerinasirova Díky za potvrzení, @pkudela díky za štítek.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Vypadá to dobře, zatím se mi v nepovedlo najít příklad změny ve formuláři, která by neaktivovala ikonu ukládání.

**Comment by ZdenkaSera** [comment]
@albertoh Doplňuji: V v STT a NDK dokumentech (mono, vicedílky, příloha, periodika ..) jsme zatím nenašli příklad, kde by byl problém s mazáním elementů nebo jejich částí, to bych za nás pustili dál.

**Problém je u e-článků** - prosím koukneš na to?
u eČlánku se mi ikona k uložení neaktivuje, když smažu - physicalDescription (celý element, u pod elementů funguje), part, name/role/roleTerm, subject, Location, relatedItem. Uvnitř relatedItem se mi ikona pro smazání neaktivovala při smazání namePart a Part

**Comment by albertoh** [comment]
Opraveno. Prosim o kontrolu

**Comment by ZdenkaSera** [comment]
Zkoušeli jsme v různých objektech a protipříklad jsme nenašli, tak snad jsme nic nepřehlédli :-) @albertoh Díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
