### ISSUE TITLE
Hledat

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#371]
posouvání lišt - nastavit na jakoukoli úroveň uživatel zadá
zvýraznit lišty tabulek

- [x] `Nastavení sloupců` do Nastavení v Profilu
- [x] Přidat tlačítko `Obnovit`
- [x] Zrušit tlačítko `Otevřít`
- [x] Vytvořit tlačítko `3 tečky`
- [x] `FOXML` přidat pod `3 tečky`
- [x] `Převod modelů` pod `3 tečky`
- [x] `Update všech objektů` pod `3 tečky`
- [x] `Indexovat` pod `3 tečky`
- [x] Přidat tlačítko `Převody stran` pod `3 tečky`
- [x] Defaultní hledání od nejnovějšího pokud není vybráno jinak (u rozukládání čísel zachovat aktuální chování)
- [x] Při návratu na tabulku Hledat si pamatovat model, na kterém jsem stál
- [x] Pamatovat si i druh řazení a pole řazení při jakékoli změně a požadavku na nový search

**Comment by SykoraLukas** [comment]
Při návratu na tabulku Hledat si pamatovat model, na kterém jsem stál.

**Comment by SykoraLukas** [comment]
Pamatovat si i druh řazení a pole řazení.

**Comment by luckajirku** [comment]
Ještě si říkáme, jestli by nemohla pro Obnovit ikonka místo textu. Že by to pak bylo všude stejné (a taky lišta bude kratší).

**Comment by nezbedova** [comment]
Souhlasím s @luckajirku Ikonka by byla vhodnější.

**Comment by pkudela** [comment]
@albertoh tlacitko indexovat je v kodu pripravene, zakomentovane, prosim tedy o zprovozneni a poprosim Te jeste o posledni 3 body.

**Comment by albertoh** [comment]
Tlacitko indexovat bude mozne testovat, az budeme mit akubru pripravenou

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto tyto body tam ještě nejsou: 
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/4f775136-e1b1-4d73-9d4d-18661c8c559f)

**Comment by albertoh** [comment]
Jsou ale:
  - Indexovat pro superAdmin a kdyz je akubra
  - Prevod pro superadmin, nebo uzivatele s pravem na fce

**Comment by SmejkalovaAnna** [comment]
@albertoh Já jsem se přihlásila jako superadmin u Vás a ty tlačítka pod tečkama jsem ale neměla stejně....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, jako superadmin tam tlačítka  mám, jinak jsem stejnou věc řešila taky tady https://github.com/proarc/proarc-client/issues/391

![image](https://github.com/proarc/proarc-client/assets/79305516/fb3f9eae-4a2f-4c4e-be6a-763e338f357c)

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto, tak se moc omlouvám, je to v pořádku!

**Comment by ZdenkaSera** [comment]
Ještě jsem si to znovu prošla vzhledem ke kombinaci labelů - @pkudela Petře, je to podle tebe hotové?
Nechci se do issues zapojovat z pohledu designu, ale tady dotaz na funkčnost.

![image](https://github.com/proarc/proarc-client/assets/79305516/8a974628-a8a6-45cb-ad9e-4cffba2d8293)

Předpokládám, že modelem se tu rozumí objekt - pokud se z Editace vrátím zpátky do Hledání, vždycky se označí první objekt na seznamu (kritéria třídění a výběru zůstávají zachovaná, to se mi zdá ok). Je to k dodělání nebo mi něco uteklo? Díky!

**Comment by albertoh** [comment]
To je na me. Ale jako model, jsem rozumel model. Pokud chcete, aby i objekt byl zvoleny, to musim dodelat

**Comment by ZdenkaSera** [comment]
@albertoh Aha, tak pokud šlo opravdu o model, tak to je pak asi ok. Prosím tě, považuješ to jinak za hotové? Díky moc.

**Comment by ZdenkaSera** [comment]
@luckajirku @katerinasirova Můžu poprosit o status ještě tady? Za nás dávám otestováno, i když si stále nejsem jistá tím bodem ohledně pamatování modelu. 
Při návratu z editace si aplikace pamatuje ne model, na kterém jsem stála, ale model, který jsem měla jako poslední ve výběru, ten zůstává vyplněn. Jinak po návratu stojím na prvním objektu seznamu 
Příklad: výběr -  vše, první na seznamu model "strana", v editaci si otevřu NDK mono. Po návratu z editace stojím opět na prvním objektu "strana", výběr :vše: je zachován - editovaný objekt je zapomenut. Nevím, zda tohle byl požadavek,  Děkuji!

**Comment by luckajirku** [comment]
Jako těžko říct. Ve starém sice zůstává označený ten poslední otevřený objekt, ale pokud je někde níž, tak ani není v okně vidět a člověk si k němu musí dorolovat. Ten první objekt seznamu mi přijde možná i lepší, že jsem hned na posledním založeném, beztak to je většinou to, co člověk chce. 
To pamatování posledního vybraného objektu je důležité hlavně u rozukládávání stran do objektů (ten bod "u rozukládání čísel zachovat aktuální chování", a tam to je teď úplně v pořádku.

**Comment by ZdenkaSera** [comment]
@luckajirku Moc díky!

**Comment by pkudela** [comment]
@ZdenkaSera ted jsem se v tom ztratil, plyne z toho, co Lucka napsala pro nas nejaky pozadavek, nebo je toto issue hotove a  na uzavreni?

**Comment by luckajirku** [comment]
jo, tady už asi není co řešit - zavřela bych to a uvidíme, jak se to pak osvědčí v praxi

**Comment by ZdenkaSera** [comment]
@luckajirku @pkudela 👍 Díky oběma.

**Comment by katerinasirova** [comment]
Souhlasím s tím, že v praxi uvidíme jak s funkcí pamatování modelu, za nás OK a přetestujeme si potom u sebe.

**Comment by ZdenkaSera** [comment]
@pkudela Tady je label probíhá - půjde to do tohoto  releasu?

**Comment by pkudela** [comment]
@ZdenkaSera  tohle by melo byt take hotove, ostranen label probiha

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
