### ISSUE TITLE
Indexovat

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#372]
Pokud v importu nezakliknu "Vytvořit index stran" nedá se dogenerovat Index.

**Comment by luckajirku** [comment]
Za nás OK, vypadá to opraveně.

**Comment by katerinasirova** [comment]
Otestováno, za nás také OK.

**Comment by SmejkalovaAnna** [comment]
Otestováno, funguje. OK.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
