### ISSUE TITLE
RelatedItem - location - physicalLocation

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#373]
Doplnit kontrolu na jádro.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Kontrola v related items je, ale za polem je roletka. Mělo by to být stejně jako v základní části formuláře pole pro vstup z volné ruky s kontrolu na konfiguraci při uložení.

**Comment by SykoraLukas** [comment]
Opravíme.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, pořád je tam roletka.

**Comment by SykoraLukas** [comment]
Zkus, případně s Ctrl + F5.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
