### ISSUE TITLE
Po uložení do objektu se nic neobjeví

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#376]
Po uložení očíslovaných stran pod titul se objeví hláška:

![obrazek](https://user-images.githubusercontent.com/13831946/233466938-873aaf2d-adce-46e7-81ff-afe3b23fba01.png)

Když kliknu na Otevřít v editoru nebo Přejít do hledání, tak mám mlhu.

![obrazek](https://user-images.githubusercontent.com/13831946/233467256-65c202d8-a02c-4b52-bc57-6e10e2505e1c.png)

**Comment by albertoh** [comment]
Bylo nespravne nasazeno na serveru. Zkuste znovu.
