### ISSUE TITLE
vybrat nadřazený objekt

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#377]
Při napojování skenů na objekt se nyní musí vybrat po levé straně všechny skeny, které chci na objekt napojit? Toto bude hodně zdržovat. 

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/37616300/234588559-34e78996-ad51-49d6-89c6-c8c80a9b4085.png">

Původně to bylo takto a připadalo mi to lepší, vybrala jsem si konkrétní objekt a pod něj se uložily automaticky všechny skeny. 

![image](https://user-images.githubusercontent.com/37616300/234589614-09fef72c-36ca-4b37-9756-083992dd5ddb.png)

![image](https://user-images.githubusercontent.com/37616300/234589668-e2f6db50-c350-4084-be9f-7feb849c027e.png)

**Comment by luckajirku** [comment]
@erikamirova asi nerozumím problému 
- pokud ukládáte nově popsanou dávku (to prvotní uložení), uložíte celou dávku do vybraného objektu, strany označovat nemusíte
- pokud tu už uloženou dávku pak potřebujete rozukládat do jiných objektů (přes Přesunout), pak strany musíte vybrat - přeci nechcete přesouvat celou dávku, ale jen část, která patří např. do dalšího čísla periodika

**Comment by erikamirova** [comment]
@luckajirku Jde mi o ten první krok, co píšete. Pokud je nemusím všechny označovat, tak tím líp, ale defaultně se mi označí první sken, což pak působí tak, že se mi pod objekt napojí jen označený sken. Takže musím sken zřejmě „odoznačit“, což je krok navíc.

**Comment by erikamirova** [comment]
@luckajirku Jj, tam to je v pořádku. 

@SykoraLukas Mohl by ses mrknout, jakou máme verzi a případně nám nasadit tu aktuální? Díky

**Comment by erikamirova** [comment]
@pkudela Díky za nasazení, už nám to funguje tak, jak má. :)

**Comment by pkudela** [comment]
@erikamirova ted jsem ti chtel napsat, ze je to hotovo, api i lclient po upradu

**Comment by pkudela** [comment]
prosim zavri toto issue, dik
