### ISSUE TITLE
Date issued ve zkopírovaním objektu - neúplný formulář

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#379]
Založila jsem objekt kopií jiného (např. se hodí u vícedílné monografie) - formulář pro date issued je neúplný, není kam vložit hodnotu. Jde to sice vyřešit přidáním nového boxu a výmazem neúplného, ale radši dávám k opravě.

![image](https://github.com/proarc/proarc-client/assets/79305516/0fa5f5c2-b2cd-4622-ad05-9c1fe871c7db)

**Comment by SykoraLukas** [comment]
Při tvorbě záznamu kopií bylo domluveno, že se zahodí pole DateIssued a PartNumber https://github.com/proarc/proarc/issues/188.  Informace o tom, že se jedná z záznam z kopie a je potřeba změnit tyto 2 pole se doplní právedo PartNumber. 

Protože je date Issued prázdné je pole sbalené. Pokud ho rozkliknete šipkou dolu můžete doplnit informace.

**Comment by SykoraLukas** [comment]
Nemyslím si tedy, že jde o chybu, ale kdyžtak to zítra projdeme na schůzce

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle je jasné
![image](https://github.com/proarc/proarc-client/assets/79305516/01cb7460-764b-476d-83fb-a419b3537bb8)

A tohle je moje chyba, neuvědomila jsem si, že je formulář jen sbalený :-( a šipka to řeší, tu jsem nevzala v úvahu
![image](https://github.com/proarc/proarc-client/assets/79305516/443069e9-e9d2-4583-94e0-77b3d33208ae)

Díky, zavírám.
