### ISSUE TITLE
Kramerius Export s Bagit balíčkem

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#380]
Kvůli modelům co nejsou dle NDK specifikace (Grafika, Konvolut) MZK potřebuje vytvořit archivní Kramerius Export. Proto bych poprosil o tvorbu Kramerius Exportu s podporou BAGIT, tak jako je u NDK a Archive. Jediným volitelným parametrem bude zda to má být veřejné nebo privátní. Instance je vždy Local (tudíž se nemusí a nemělo by se uživateli zobrazit toto pole pro změnu hodnoty).

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, funguje to v MZK?

**Comment by erikamirova** [comment]
@ZdenkaSera ano, funguje to, některé grafiky nám sice nejdou archivovat, ale to řešíme s Lukášem individuálně

**Comment by ZdenkaSera** [comment]
@erikamirova Prima, moc děkuji. My jsme se shodli, že tohle nebudeme v KNAV nastavovat a testovat, asi je to specificky jen pro MZK -  necháme ne Vás, kdy to issue zavřete :-) Díky!

**Comment by erikamirova** [comment]
@ZdenkaSera Jj, dobře. Já myslím, že tím pádem ho můžu uzavřít. :)
