### ISSUE TITLE
Kramerius Export - instance

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#381]
Při vybrání instance Krameria, do které chci exportovat je potřeba aby se defaultně nastavila první hodnota ze seznamu. Nyní zůstává prázdná a pokud ji nevyplním, export padá do chyby.

![image](https://github.com/proarc/proarc-client/assets/27210823/78bcbdc4-26d4-44f6-8d58-eeaf7e32e6ce)

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
