### ISSUE TITLE
Chyby klienta v lokální instanci vs Inovatika-master (Lokálně teď verze z 13.9.)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#382]
Do verze 2.0.2 se nedostaly nělteré funkce, které už byly (a teď jsou) funkční na Inovatice.

**Hledání v úložišti:**

1. FOXML zobrazí prázdný formulář

2. Převod modelů - chybí lokalizace (seznam funkcí pod tlačítkem je ok)
![image](https://github.com/proarc/proarc-client/assets/79305516/c2a4daf1-74b7-4778-9b40-c27bde59b756)

3. Nelze  zastavit import - ale to jsem teď zkusila na Inovatice  a tam je taky rozbité, Založím na to samostatné issue.

**Comment by albertoh** [comment]
To lze testovat az budete mit novy build

**Comment by ZdenkaSera** [comment]
1. FOXML ve verzi 2.1.0 stále nevidíme (to není kritické)
2. Převody modelů mají text ok
3. Zastavit dávku lze, ale je je tam vážná chyba https://github.com/proarc/proarc-client/issues/404

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, tohle issue sice není kritické, ale poslouží jako příklad neúplných verzí (máme na testu klienta z 19.9.)
1, FOXML se stále nezobrazuje, otevírá se prázdná strana
2. Texty k převodům modelů jsou ok, ale zase se nepřenesla funkce se zobrazením chybové hlášky - to řešíme tady https://github.com/proarc/proarc-client/issues/424
3. Křížek na zastavení importní dávky chybí (zkoušela jsem jako superadmin a jako uživatel proarc)

**Comment by ZdenkaSera** [comment]
@albertoh Tady jsem udělala chybu ohledně chybějícího křížku z zastavení importní dávky - není v importních procesech, ale tam asi nikdy nebyl, není tam ani na Inovatice. Ve správě všech procesů je, dávku lze zastavit, Bod 3 výše tedy škrtám tady i v issue https://github.com/proarc/proarc-client/issues/404

**Comment by ZdenkaSera** [comment]
Ve sloučené verzi na masteru všechny vyjmenované body ok, issue uzavřít až po vydání verze a ověření na lokální instanci.

**Comment by ZdenkaSera** [comment]
Ve verzi v2.2.0 (31.10.2023) na lokální instanci v KAV stále nelze zobrazit FOXML. Ostatní body issue ok.

**Comment by albertoh** [comment]
Problem je v pouzivani api pres /rest/v1 nikoli rest/v2
Muzete, prosim, v novem otevrem okne zmenit v1 na v2?
Zmenim to v kodu

**Comment by ZdenkaSera** [comment]
Nevím, jestli to bude jen tím - foxml se možná vůbec nevolá; okno foxml vypadá takto
![image](https://github.com/proarc/proarc-client/assets/79305516/1c438679-a425-4c74-807d-ecb178a4bf0c)

A když do něj vložím celou adresu, funguje s v1 i v2, problém není v tom, že by foxml nebylo k dispozici
![image](https://github.com/proarc/proarc-client/assets/79305516/380493dd-90e6-4dad-aab8-2c9d40757479)



Bude prima mít k foxml přístup, ale hlásili jsme to hlavně proto, že se rozešly verze na inovatice s těmi vydanými. Díky.

**Comment by albertoh** [comment]
Co mate v konfiguracnim souboru globals.js pro "proarcUrl" ?

**Comment by ZdenkaSera** [comment]
// proarcUrl: "https://proarc-test.libj.cas.cz/proarc/",   proarcUrl: "/proarc/" - nemá být  ...proarcUrl: "/api/" ?

**Comment by albertoh** [comment]
Muzete testovat tohle s tim novym nasazenym buildem?

**Comment by ZdenkaSera** [comment]
@albertoh Můžeme - a funguje to 😊 Díky.
