### ISSUE TITLE
Import - nelze zastavit dávku

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#383]
Ve verzi 2.0.2. v KNAV ani na Inovatice nelze zastavit import:

![image](https://github.com/proarc/proarc-client/assets/79305516/faee5579-4137-4357-9ac7-1e5810869507)

**Comment by ZdenkaSera** [comment]
Napadlo mě, že tady může být problém v oprávnění - a je,, jako superadmin dávku zastavím. Dává to smysl,, superadmin může pozastavit i cizí dávky, běžný uživatel je ani nevidí. tak se jen ptám - uniklo mi, že to bylo takhle domluveno?

**Comment by ZdenkaSera** [comment]
Ještě doplňuji - tohle byl až další pokus, ten první s chybou byl jako admin.

**Comment by SykoraLukas** [comment]
OK, Prosím o omezení zastavení importu jen na roli superAdmin.

**Comment by SykoraLukas** [comment]
Jen doplnim, ze to vychází ze zadání v issue #1202. Hned  v první větě zadání psala paní Nezbedová, že to má jít jen pro SuperAdmina.

**Comment by ZdenkaSera** [comment]
Děkuji - v issue https://github.com/proarc/proarc/issues/1202 to nikdo nerozporoval, tedy není třeba znovu ověřovat a prosím jen upravit chybové hlášení, pokud se o zastavení pokusí uživatel bez oprávnění.
vyzkoušela jsem ještě jako superadmin zastavit dávku spuštěnou userem - to je ok. Díky.

**Comment by erikamirova** [comment]
@ZdenkaSera Já bych to udělala tak, že superadmin má možnost pozastavit dávky všech userů. A user si může pozastavit jen svoji dávku.

**Comment by ZdenkaSera** [comment]
@erikamirova Za KNAV může být - pak tedy user + admin by mohli zastavit jen svou dávku, superadmin jakoukoliv. Shodneme se na tomhle @luckajirku @katerinasirova ?

**Comment by luckajirku** [comment]
@ZdenkaSera může být

**Comment by katerinasirova** [comment]
@ZdenkaSera souhlasíme

**Comment by albertoh** [comment]
Client pripraven. @SykoraLukas dodelej, prosim, kontrolu v jadre

**Comment by ZdenkaSera** [comment]
Zkusila jsem na inovatice a buď to ještě není ono nebo dělám něco špatně:¨
- jako user ani jako admin jsem nedokázala svou dávku zastavit, hláška se žádná neobjevila
- jako superadmin můžu zastavit jakoukoliv dávku, jen musím na křížek pro zastavení kliknout 2x
- - jako user nebo admin můžu znovu spustit svou dávku zastavenou superadminem - to je trochu sporné, ale pokud mám mít jako user možnost vlastní dávku zastavit, měla bych mít možnost ji znovu pustit, takže bych tohle nechala a nenutila někde ukládat, kdo dávku zatavil

**Comment by ZdenkaSera** [comment]
Tady sice není viditelný další vývoj, ale chování  se změnilo a je skoro ok - user a admin můžou zastavit a znovu spustti své dávka, superadmin může zastavit cokoli. 
Když jsem ale jako superadmin chtěla znovu spustit zastavenou dávku původně načítanou jiným uživatelem, dostala jsem chybovou hlášku (viz níže).
Prosím, nebude tohle zastavování resp. opětovné spuštění cizích dávek vyžadovat nějaké mapování/oprávnění pro superadmina k cizím importním složkám? Díky.

![image](https://github.com/proarc/proarc-client/assets/79305516/78f7fcb4-d80a-4908-aaee-c5aee11eaee3)


java.lang.IllegalStateException: The folder tracked by another batch import!
folder: /data/proarc/.proarc/users/knavuser/import/Monografie/Methodika krasopisu
found ID: 117
	at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:250)
	at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:230)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ZdenkaSera** [comment]
![image](https://github.com/proarc/proarc-client/assets/79305516/a898bb82-fcc0-457f-a5ee-b2d6dd5490fb)

@pkudela Petře, prosím, je tohle dotaz na tebe? Díky.

**Comment by SykoraLukas** [comment]
Jak dávku spouštíš? Ve správě procesů nebo jako novou dávku?

**Comment by SykoraLukas** [comment]
Problém je v tom, že původní dávka se načítala, pak ji někdo zastavil. Poté si někdo stejnou složku nechal připravit znovu k importu a tedy smazal celý obsah té již načítané, ale pozastavené dávky. I  tato dávka byla zastavena. Poté jsi asi chtěl pokračovat v načítání té, co jsi zastavila první. Ale chyba je, že tato dávka už patří pod jiný proces. Takže vyletí chyba. 

Z mého pohledu je vše správně nastavené. Vyletí chyba, že dávku nelze načíst + stacktrace s popisem chyby a zanořením v programu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, šlo mi o test situace, kdy superadmin zastaví cizí dávku a pak ji chce znovu spustit, tj. sahá na data v cizím importním adresáři. To je to, co  mi nešlo (zastavit ano, znovu spustit ne), ale hlavně k tomu by ta funkce měla sloužit. Zkusím to u nás s touhle verzí. Zbytek je ok, tak to navrhnu k uzavření a případně pak znovu otevřu.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
