### ISSUE TITLE
Nový objekt z katalogu - pořadí polí v náhledu metadat

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#384]
Při zakládání nového objektu stažením z katalogu jsou v náhledu metadat teď nějak zvláštně zpřeházená pole. Začíná to jazykem a končí informacemi o titulu.

**Comment by luckajirku** [comment]
aktuální nový klient vs PA 3.7.2


![novyobj_lang](https://github.com/proarc/proarc-client/assets/6359479/d5134140-e3cb-47ea-a690-365b699f1d7a)

![novyobj_postaru](https://github.com/proarc/proarc-client/assets/6359479/586536d1-10c7-45f0-bbed-e16f9e83bd45)

**Comment by ZdenkaSera** [comment]
Myslím, že teď jsou pole zobrazována v tom pořadí, v jakém pak jsou uloženy odpovídající elementy v metadatech v xml. Není to moc šikovné, ale to jsme zatím nerozporovali, protože nebrání funkčnosti.

**Comment by luckajirku** [comment]
Funkčnosti to sice nebrání, ale je to dost nepraktické. Jak velká by ta oprava, aby se to řadilo stejně jako ve starém, byla?

**Comment by luckajirku** [comment]
dávám štítek Návrh na rozšíření, aby to nezapadlo - i když to teda rozšíření není, jen návrat k tomu, co bylo ve starém nastaveno lépe.

**Comment by luckajirku** [comment]
Na tuhle otázku jsem nedostala odpověď, takže se připomínám. Ono to vypadá jako prkotina, ale není. Když si člověk chce zkontrolovat před založením, jestli je to ten správný záznam, tak teď musí nesmyslně rolovat, než zjistí, o jaký titul jde. 
> Jak velká by ta oprava, aby se to řadilo stejně jako ve starém, byla?

**Comment by albertoh** [comment]
Nemela by byt moc velka: 
 - pridat novou moznost v konfiguraci (razeni poli)
 - zohlednit tuto konfiguraci v rozhrani

**Comment by luckajirku** [comment]
asi úplně nerozumím, jakože by to mělo být nastavitelné? To nepotřebujeme, tady myslím, že snad nikdo nechce mít na prvním místě věcné třídění...

**Comment by albertoh** [comment]
Nekde musi byt definovano spravne razeni poli. Muze to byt prehledne v konfiguraci, nebo muzu to dat natvrdo do kodu.

Kazdopadne ja to v idim i ve starem tak:
![image](https://github.com/proarc/proarc-client/assets/5946836/0cb04073-c168-4a25-9208-7ad67b62baa7)

**Comment by luckajirku** [comment]
Aha, no v našem PA (3.7.2) se to řadí správně - takže to řazení polí se už teď bere z cfg? Já do toho souboru nevidím, takže nevím.

**Comment by albertoh** [comment]
Nebere. Klient zpracuje to co prichazi z API.
@SykoraLukas podivej se, prosim, proc API vraci jinak u nas a v Hradci

**Comment by SykoraLukas** [comment]
Zjistili jsme, že změna souvisí s upravou vicenasobneho origin info. Protože je tam potřeba převést pole do MODSu, tak se změní pořadí. Řešíme, jak to změnit tak, aby pořadí zůstalo, ale aplikované změny se nezahodili.

**Comment by SykoraLukas** [comment]
Mám to upraveno. Jen už nedokážu dohledat pořadí, které bylo dříve. Přebral jsem pořadí z formulářů v novém klientovi, je to tedy ok?

Pořadí je:
1. TITLE_INFO
2. NAME
3. ORIGIN_INFO
4. LOCATION
5. IDENTIFIER
6. LANGUAGE
7. PHYSICAL_DESCRIPTION
8. ABSTRACT
9. NOTE
10. TYPE_OF_RESOURCE
11. GENRE
12. CLASSIFICATION
13. SUBJECT
14. PART
15. TABLE_OF_CONTENTS
16. RECORD_INFO
17. RELATED_ITEM

**Comment by luckajirku** [comment]
Netřeba dohledávat, takhle je to super podle toho pořadí z formulářů.

**Comment by SykoraLukas** [comment]
Je k testu, vyřešeno na straně API, takže změna se projevila na všech testovacích instancích.

**Comment by luckajirku** [comment]
za nás OK, to podstatné už je nahoře
