### ISSUE TITLE
Nový objekt - zakládání podřízených objektů přes plusko - tlačítka

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#385]
Jedna věc k diskusi. Jak to tak zkoušíme, tak narážíme při tvorbě ročníků, čísel atd. přes plusko na to, že není zrovna praktické mít nejprve to dlouhatánské tlačítko pro stahování z katalogu a pak až normální Vytvořit. Ono mně tady třeba to tlačítko nedává smysl vůbec, ale třeba to tam někdo z vás používá. Něco jiného je to při tvorbě titulových záznamů z lišty nahoře, tam jasně, že první volba je katalog, ale u těch podřízených úrovní to už smysl nedává. Být tam jen malá ikonka, tak asi OK, ale jak je to katalogové tlačítko dlouhé, tak se hůř trefuje na to odsunuté tlačítko Vytvořit. 
Co na to vy ostatní, vyhovuje vám to takhle? @SmejkalovaAnna @kerschfilip @katerinasirova @erikamirova

**Comment by SmejkalovaAnna** [comment]
@luckajirku Lucko za nás určitě jako Vy, taky mi to smysl nedávalo, ale nereklamovala jsem to, protože tam bylo hodě jiných horších věcí. Určitě budeme rádi, když to tam u ročníků a výtisků nebude. Nicméně bych to, ale u úrovně NDK Příloha periodika a NDK Příloha monografie nechala, protože se může stát a stalo, že měla příloha samostatný záznam, tak se tam použil....

**Comment by erikamirova** [comment]
@luckajirku My to požíváme třeba u konvolutů, kdy mají přívazky samostatné záznamy a nijak nás to neruší. Prostě když tak klikneme o kousek vedle. :)

**Comment by ZdenkaSera** [comment]
@luckajirku Přimlouvala bych se, aby konfigurovatelnost - pokud byste se pro ni rozhodli - byla předmětem dalšího rozvoje, abychom teď napřed měli hotové to bolestivější věci. Souhlasíte?

**Comment by kerschfilip** [comment]
za zpracování e-publikací v KNAV doplním, že nám nijak nevadí mít tam to delší tlačítko, kdyby se to vyměnilo za ikonu té knihy, tak je to taky jedno. Souhlasím se Zdeňkou, že nabízet tlačítko podle modelu bych nechal na případný další rozvoj

**Comment by SmejkalovaAnna** [comment]
My souhlasíme za Jenštejn také s Filipem a Zdenkou.

**Comment by erikamirova** [comment]
Já bych to podle modelů nekomplikovala a klidně bych tam dala pro všechny modely tlačítko s ikonou.

**Comment by albertoh** [comment]
Ikona je tam

**Comment by ZdenkaSera** [comment]
@albertoh Tu kousnutou obrazovku dávám sem neb sem patří - je to po stažení z katalogu a volbě "vytvořit a přejít do objektu". Myslím, že to prázdné okénko je místo toho, které upozorňuje na chyby v objektu . Zatím tedy radši odebírám "k testu"- Díky za opravu.

![image](https://github.com/proarc/proarc-client/assets/79305516/b456f44a-6896-4292-97c4-ffa2d8319aed)

**Comment by albertoh** [comment]
Aha, to jsem nevedel. Zmenim to

**Comment by luckajirku** [comment]
super, to je ono. Ono se to mohlo zdát jako prkotina, ale tam jde nejen o to, že by měla být v každém tom místě víc vidět fce, která se tam používá častěji, ale je to dobré i v tom, že odlišný vzhled zafunguje i jako kontrola, že si člověk uvědomí, kde je - jestli nový objekt zakládá do prázdna, nebo někam ve struktuře.

**Comment by katerinasirova** [comment]
Vyhovuje nám nynější nastavení, občas se při zakládání příloh stahují metadat z katalogu, ale rozhodně méně často, takže nám se líbí spíš lepší přístup k tlačítku vytvořit.

**Comment by luckajirku** [comment]
Tak tohle se zase nevím proč vrátilo k dlouhému tlačítku...

**Comment by luckajirku** [comment]
mám na mysli tohle - nám se tu nikomu neukazuje to, co jsi sem dal. Po té předchozí úpravě se tam přes plusko objevovala ikona knížky - a jestli si dobře pamatuju, barvy byly opačně a vypadalo to líp (to Vytvořit pak víc vyskočilo).
![nobjekt_dlouhetlacitko](https://github.com/proarc/proarc-client/assets/6359479/0fdc8d09-1c21-43f8-a61d-205f581e8b8c)

**Comment by luckajirku** [comment]
a důvod, proč právě tady by měla být ikona, i když je místo na celé tlačítko, je vysvětlen výš, to nebudu psát znovu

**Comment by luckajirku** [comment]
> ... sjednoceni chovani a vzhledu tlacitek napric velou aplikaci. Nyni jsou 2 typy tlacitek:
> 
> * standardni tlacitka s textem tam, kde je na to prostor a neni duvod vyjadrit podstatu tlacitka celym textem
> * tlacitka pouze s ikonou - ta se pouzivaji spolecne s popisem v tooltipu tam, kde neni na standardni tlacitko s textem misto napr. v toolbaru atd.

no a já bych tu přidala ještě třetí typ - tlačítko s ikonou tam, kde by bylo místo i na tlačítko s textem, ale uživatelsky je lepší použít malé tlačítko jen s ikonou - a to je třeba případ té ikony katalogu při přidávání nového objektu přes plusko, nebo tlačítko Obnovit v Hledat.

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, je tohle a) míněno jako shrnutí pro přehlednost nebo b) uvažujete o výměně některých tlačítek? Pokud je pravdou b), navrhovala bych současný stav napřed chvilku testovat v reálném životě a pak případně ještě vylepšovat (to se netýká té ikony výše - katalogu v zakládání pluskem :-)).

**Comment by luckajirku** [comment]
to je jen shrnutí pro Petra, že to rozdělení na dva typy úplně nestačí a bylo by fajn už rovnou počítat i s tím třetím typem - který vychází z uživatelských potřeb

**Comment by pkudela** [comment]
Ahoj, Alberto mi vysvetlil historii tohoto problemu. Co se tyce tretiho typu - tlacitko "obnovit" v hledani je trochu jiny pripad, nachazi se v liste  "toolbaru", stejne jako je umistene v toolbaru editace, proto je tam take ikona, aby tato akce byla sjednocena v ramci vsech komponent kde se pouziva. Pokud chcete aby tlacitko pri otevirani z pluska bylo potlacena, aby nelakalo na kiknuti, tak bych volil inou a standardni cestu a to je odebrani primarni barvy tlacitka:

![image](https://github.com/proarc/proarc-client/assets/16591052/c4c375f3-5cd6-4752-8c00-3d173d29c4be)

S tretim typem tlacitka je vlastne uz pocitano viz. toolbar v hledani, ktery zminila Lucka a ja v tomto komentari,  ale zde mi to zkratka nesedi. Nicmene na druhou stranu, pokud je vam ikona blizsi a mysliste si, ze je to pro prehlednost lepsi reseni, nechci to zahazovat, aplikaci budete preci jen pouzivat vy, cili jeste puvodni stav:

![image](https://github.com/proarc/proarc-client/assets/16591052/28379d3e-f8f6-4eb1-9536-ba27ebf34aa3)

Reknete a ja udelam jak budete chtit, jen jsem chtel vysvetlit o co mi jde.

**Comment by luckajirku** [comment]
Tak ono nejde jen o to zvýraznění, ale právě i o to umístění. Nápis Načíst metadata z katalogu je prostě strašně dlouhý a odrazí tak tlačítko Vytvořit (které na tomhle místě potřebuješ používat v 99% případů) nesmyslně doprava. Za nás určitě návrat k té ikonce, jak máš na posledním screenshotu. Ale JEN u zakládání přes plusko:-).

**Comment by katerinasirova** [comment]
Souhlas s Luckou, za nás určitě návrat k ikonce z posledního printscreenu.

**Comment by pkudela** [comment]
ok, ukecali jste me :-)

**Comment by pkudela** [comment]
pres plusko

<img width="863" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/a9e8429b-473e-408f-aa2e-554aa8c53b16">

z navigace

<img width="761" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/b52d3689-d341-4175-bfe2-c109b54a8906">

**Comment by pkudela** [comment]
jeste jsem sjednotil delku dialogu pro oba pripady

**Comment by pkudela** [comment]
nasazeno na server, prosim o kontrolu

**Comment by luckajirku** [comment]
Tím sjednocením délky dialogu myslíš (pro nás lamy:-)) šířku tabulky? 
U čísla přes plusko teď vzniklo tohle - úmyslně? Úplně dobře to nevypadá...
![cislopresplus](https://github.com/proarc/proarc-client/assets/6359479/99415ba1-3e45-4a8a-8115-80889d4856f7)

**Comment by luckajirku** [comment]
třeba tady https://proarc.inovatika.dev/repository/uuid:472e3c05-11af-486e-8187-1b39b170ddfc. Ale můžeš otevřít jakýkoli ročník jakéhokoli periodika a když dáš založit číslo přes plusko, dostaneš tohle. Když zakládáš z horní lišty, tak tam ta možnost s parametry není, takže tam se to všechno vejde.

**Comment by ZdenkaSera** [comment]
Jen předběžně - zkusila jsem přes plusko mono a STT mono - to vypadá dobře už teď, později  přetestuju.
![image](https://github.com/proarc/proarc-client/assets/79305516/8a8c9bbc-1c49-4481-88ba-1df59b87fe44)

**Comment by pkudela** [comment]
@luckajirku dik, vidime to, tam delaji neplechu ty formularove pole, pak se na to podivam, fixnu a nasadim

**Comment by ZdenkaSera** [comment]
Při zakládání objektů pod NDK mono (příloha, kapitola ..) - taky ok.

**Comment by pkudela** [comment]
fiixed, nasazeno na server, prosim o kontrolu -> https://proarc.inovatika.dev/repository/uuid:472e3c05-11af-486e-8187-1b39b170ddfc

**Comment by luckajirku** [comment]
Super, tohle už vypadá dobře. Za nás OK.

**Comment by ZdenkaSera** [comment]
Přetestované plusko pod NDK VD, STT VD a NDK mono - vše ok.

**Comment by SmejkalovaAnna** [comment]
Za nás taky dobrý!

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
