### ISSUE TITLE
Import/správa dávek/editace - tlačítko "obnovit"

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#386]
Pokud v obrazovce pro očíslování nové dávky  použiju tlačítko obnovit, dostanu šedou obrazovku a musím se k datům vrátit přes menu. 

![image](https://github.com/proarc/proarc-client/assets/79305516/46c20957-c695-4094-993a-9b8a557acf77)

![image](https://github.com/proarc/proarc-client/assets/79305516/799d8db2-214e-4c96-b013-21ed194413c3)

**Comment by albertoh** [comment]
Ted se pri obnoveni objevuje "loading bar" nahore, aby bylo jasne, ze obrazovka neztuhla, jen dumaaa :)

**Comment by katerinasirova** [comment]
Při mém testování fungovalo, lišta probíhala, za nás OK.

**Comment by ZdenkaSera** [comment]
je to ok, zavírám.
