### ISSUE TITLE
Uložení do nadřazeného objektu - Otevřít v editoru - vede na šedou obrazovku

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#387]
Něco se rozbilo - po uložení nově přiřazeného objektu k nadřazenému nelze přejít rovnou do editoru (zatím jsem zkoušela jen s nově importovanými skeny) - místo editoru jen šedá obrazovka

![image](https://github.com/proarc/proarc-client/assets/79305516/36a723c1-5498-4101-9d54-750d434829bc)

![image](https://github.com/proarc/proarc-client/assets/79305516/74682d23-f3c4-4b43-a72f-8c8ba1456281)

**Comment by albertoh** [comment]
Zda se, ze se menili objekty na serveru (zmizely), a zrovna jsi trefila uprostred.
Zkus znovu. Mne to funguje

**Comment by ZdenkaSera** [comment]
@albertoh Děkuju, došlo mi, že  se asi motám do probíhajícího vývoje, Spadly mi pak další akce (např. z nově zakládaného objektu nepřejdu do editoru, to se kousne a zatuhne obrazovka). Zkusím později nebo večer/brzy ráno, abych negenerovala zbytečná issues.

**Comment by albertoh** [comment]
OK

**Comment by albertoh** [comment]
Ted se pri obnoveni objevuje "loading bar" nahore, aby bylo jasne, ze obrazovka neztuhla, jen dumaaa :)

**Comment by ZdenkaSera** [comment]
@albertoh Já ti nechci kazit radost, ale např. tahle obrazovka fakt asi nedumá, 

![image](https://github.com/proarc/proarc-client/assets/79305516/a71c2109-256b-4e27-9a0c-10c15cf3e323)
