### ISSUE TITLE
V Rozložení zrušit možnost Mřížka

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#388]
V nabídce Nastavení rozložení - úložiště se pořád nabízí možnost Mřížka, měla by přijít pryč.

**Comment by pkudela** [comment]
@luckajirku prosim posli mi url z testovaciho serveru jako priklad, dik

**Comment by luckajirku** [comment]
Jaké url? Zrušilo se zobrazení Mřížka, ale v Rozložení to jako možnost v panelech zůstalo. Jen to tam má zmizet z nabídky. 

![rozlozeni](https://github.com/proarc/proarc-client/assets/6359479/9679da34-053d-4606-864b-a03a990fec33)

**Comment by pkudela** [comment]
aha, chapu, ono je to v tom dialogu v nastaveni layoutu

**Comment by luckajirku** [comment]
je to tak, mřížka je pryč, za nás k zavření

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
