### ISSUE TITLE
Vylepšení zpětné vazby při mazání objektů

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#389]
Při mazání objektů z PA v novém klientovi se objevilo několik připomínek, které by, myslím, stály za zpracování:

- [x] Při výběru více objektů ukazovat, kolik objektů je vybraných ke smazání, obdobně jako ve starém rozhraní: 
![image](https://github.com/proarc/proarc-client/assets/57805328/fe334f87-b4cb-431e-a07f-68c683406edf)
- [x] Při mazání zobrazit informaci o tom, že mazání probíhá (nyní se jakoby nic neděje a uživatel si nemusí být jistý, v jaké fázi mazání je). Opět pohled na staré rozhraní:
![image](https://github.com/proarc/proarc-client/assets/57805328/c2ed202a-a062-4cdb-9d7f-e94bad5cbde5)
- [x] Na Základní obrazovce "Hledat" nemůžu ve spodní části vybrat víc objektů než jeden a ty smazat. Tlačítko smazat tam je, ale nejde vybrat víc věcí - typicky chci vybrat určitý počet stran (ale ne všechny) a ty smazat.

**Comment by luckajirku** [comment]
Tady nejde ani tak o vylepšení, jako o doplnění/opravu - když jde o věci, které ve starém klientovi jsou. 
Co se týká hlášek, ty by se měly projít všude, kde ještě co chybí (je https://github.com/proarc/proarc-client/issues/171).

**Comment by pkudela** [comment]
Ano, postupne se snazime hlasky doplnovat / upravovat, bohuzel tech ruznych akci je tolik, ze  to nejde tak rychle, jak bych si predstavoval. Toto issue bereme @kerschfilip na vedomi a zapracujeme.

**Comment by albertoh** [comment]
Hlaska opravena. Ted je videt "loading bar"

**Comment by ZdenkaSera** [comment]
Při hromadném výběru ve spodní části obrazovky povolit jen mazání.

**Comment by albertoh** [comment]
Spodni cast upravena

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
