### ISSUE TITLE
Chyba založení STT vícedílné monografie

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#390]
Při pokusu o založení STT vícedílné monografie se záznam z katalogu nepřevzal do formuláře. Testovací záznam: sysno = 000737900,  katalog knav monografie.

![image](https://github.com/proarc/proarc-client/assets/79305516/b1ad093b-6163-4d80-9204-20069b152b9a)

**Comment by albertoh** [comment]
@SykoraLukas chybi tam template OldprintMonographtitle.aacr.template.json6
Pridas?

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Díky, STT VD mono už jde založit.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Utekla mi chyba na Inovatice, takže je i v KNAV - stažením z katalogu lze STT VD založit, ale pokud ji chci založit "z volné ruky" bez katalogu, formulář je prázdný.

**Comment by albertoh** [comment]
Problem je v nazvu souboru sablony, velka/mala pismena. 
Opravime

**Comment by katerinasirova** [comment]
A při snaze obejít vytvoření objektu, abych mohla u nás otestovat celý proces vytvoření NDK balíčku zvukového dokumentu, jsem zjistila, že to nezobrazuje formulář ani když vytvořím nový objekt ve starém klientovi. Údaje v XML se už zobrazí.

**Comment by SykoraLukas** [comment]
Opraveno, bude nasazeno.

**Comment by katerinasirova** [comment]
Vyzkoušeno a metadata stažena jak k NDK Zvukovému dokumentu, tak k NDK Fonografickému válečku i k STT vícedílné monografii. Za nás OK.

**Comment by ZdenkaSera** [comment]
Nenašla jsem chybu, takže za nás taky ok, navrhuji k uzavření.
