### ISSUE TITLE
Nástroj "převést strany" je nefunkční

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#391]
Převádění Stran na NDK strany a zpět se přesunulo zpátky na hlavní obrazovku v hledání pod 3 tečky, ale nic nedělá. V jádře to fungovalo tak, že stačilo postavit se na úroveň titulu (u periodik šlo spouštět i na nižší úrovni) a  spustit tak funkci pro srany na všech podřízených úrovních. Pokud u větších souborů nedoběhl převod až k poslední straně, systém nevydal ok hlášku, funkce se spustila znovu - až po převedení všech stran se zobrazilo "OK hlášení"

![image](https://github.com/proarc/proarc-client/assets/79305516/df680162-399d-47ea-825f-01476330dcce)

**Comment by albertoh** [comment]
Dodano

**Comment by pkudela** [comment]
ahoj @ZdenkaSera dnes jsem na proarc nedelal, ale koukam na server a ta polozka tam je

<img width="649" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/61f0e05d-4a39-467e-b507-d02fc232a738">

<img width="584" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/1c45d5d2-d017-4639-97da-ce20e664c664">

**Comment by ZdenkaSera** [comment]
@pkudela Petře díky za nakopnutí, @albertoh Alberto, tobě se omlouvám - bylo to oprávněním, jako superadmin  to vidím. Bojujeme s tím i na našem ostrém systému, potřebovali bychom tady to oprávnění asi předělat. Na to ale bude nové issue, az tohle znovu přetestujeme. Díky!

**Comment by ZdenkaSera** [comment]
S oprávněním "převod modelů! má oprávnění i uživatel, funguje to ok. V předchozí verzi (máme u nás na ostrém) je chyba - systém vydával hlášení o provedeném převodu i tehdy, když byla převedena jen část. Tady nemám na čem otestovat, ->> lokální test.

**Comment by ZdenkaSera** [comment]
@pkudela Petře, tady je label "Probíhá" - bude to zahrnuto v tomto releasu? Děkuji.

**Comment by pkudela** [comment]
@ZdenkaSera jak jsem pochopil z predchozi komunikace s Albertem a se mnou, tak je to snad otestovane, takze jsem label "probiha" odstranil.

**Comment by ZdenkaSera** [comment]
Na testovací instanci KNAV ok, díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
