### ISSUE TITLE
Výmaz uživatele z ProArcu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#393]
Přidat možnost výmazu uživatele z ProArcu
- Nová funkce v administraci
- Definovat, za jakých podmínek lze uživatele smazat 
- Analyzovat dopady na data, kde se uživatl vyskytuje ("živá" v ProArcu, importovaná z Krameria nebo archivu ..)
- Oprávnění na výmaz - superadmin nebo superadmin s dodatečným dedikovaným oprávněním ?

**Comment by SykoraLukas** [comment]
Pokud uživatel nemá objekty, tak ho lze smazat.

Pokud uživatel objekty má, je nutné nejprve objekty převést na nového uživatele.
Předpokladem převodu je #455.

**Comment by SykoraLukas** [comment]
Na API hotové.

volání je: 

```
### DELETE USER
DELETE {{proarcUrl}}/rest/v2/user?userId={{userId}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```

- Pokud je uspech, vrati se status = 1 a data jsou prazdna.
- Pokud je neuspech, vrati se status = -4 a json:

```
"errors": {
      "user": [
        {
          "errorMessage": "This user (tester3) has 1 objects."
        }
      ]
    }
```

**Comment by albertoh** [comment]
Klient pripraven

**Comment by ZdenkaSera** [comment]
@SykoraLukas Na schůzce 18.11. jsme řešili, zda workflow blokuje výmaz uživatele z ProArcu. Znovu jsem založila na masteru nového uživatele a pod jeho přihlášením jsem pouze založila záměr. Ten opravdu blokuje výmaz uživatele. Hláška je sice trochu uživatelsky nepřívětivá, ale lze to z ní vyčíst. Issue ponechávám označené k výmazu.

![image](https://github.com/user-attachments/assets/f52ccbf2-3a7c-43e4-8dcc-4b71a3074a67)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zkusila jsem ještě výmaz uživatele, který má pouze otevřený nebo dokončený úkol ve wf - i to blokuje jeho výmaz.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
