### ISSUE TITLE
Obrázek - nezobrazuje se (v importu i v úložišti)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#394]
Když si nakliknu nějakou stranu, v panelu Obrázek nevidím nic.
Když tu stranu nakliknu dvakrát, dostanu opět nic, ale v nové obrazovce a o něco větší:-).

**Comment by luckajirku** [comment]
Jen radši poznamenám, že tohle je věc, bez jejíž opravy nelze vydat novou verzi, bez velkých náhledů se nedá pracovat.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, podával by ses na to? Moc díky.

**Comment by luckajirku** [comment]
V importu i úložišti už OK.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
