### ISSUE TITLE
Import - nelze po uložení dávky přejít přímo do editoru 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#395]
Při ukládání popsaných stran z importu do objektu, když dám pokračovat do editoru, dostanu prázdnou obrazovku. 
Když pak dám obnovit, dostanu tohle:
![unnamed](https://github.com/proarc/proarc-client/assets/6359479/e22d5dc3-292e-40f6-a488-48bd62db46a1)

Když do toho objektu pak jdu přes Hledat, strany tam uložené jsou.

**Comment by albertoh** [comment]
Muzes mi to opakovat a napsat uuid?
Ted jsem to dvakrat zkusil, a proslo mi bez chyb

**Comment by luckajirku** [comment]
Teď už to funguje normálně. Tak nevím, jestli na to měla vliv oprava toho předchozího issue... Ale už se to neděje, takže zavírám.
