### ISSUE TITLE
V Označit řadu zrušit zobrazení Mřížka

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#396]
Na tohle okno jsme zapomněli - zobrazení Mřížka ještě zůstalo viset u fce Označit řadu, mělo by přijít pryč i tady z těch prvních dvou panelů. Stejně jako v editaci - zrušit zobrazení mřížka a ikonu použít pro náhledy, současnou ikonu náhledů vyhodit.

**Comment by luckajirku** [comment]
Ono je to blbé v tom, že teď ta samá ikona na jednom místě aplikace funguje pro jiné zobrazení než na druhém.

**Comment by albertoh** [comment]
Opravim.  Necham ikonu
![image](https://github.com/proarc/proarc-client/assets/5946836/d68d9dd9-8240-4229-bc1f-3c5e53dc4158)

**Comment by albertoh** [comment]
Je to tam

**Comment by luckajirku** [comment]
super, za nás k zavření

**Comment by ZdenkaSera** [comment]
za knav ok

**Comment by katerinasirova** [comment]
Za MKP také OK

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
