### ISSUE TITLE
Blokování změn objektu - znemožnění jiných fcí do uložení změny

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#397]
V importu i při editaci stran v úložišti nastává tahle situace. Přesunu strany v rámci jednoho objektu - změním jejich pořadí, vyskočí mi ikona uložit - ale pokud na ni nekliknu, nedostanu žádné upozornění. Pak klidně dám Reindexovat a nedozvím se, že se mi předchozí změna neuložila, že reindexace proběhla na tom původním pořadí stran.
Ve starém se při neuložené změně pořadí stran změní nabídka ikon a ty další fce jako Reindexovat, Nový, Označit řadu atd. zmizí. 
Tohle se budeme muset dohodnout, jak řešit - jestli se to má chovat stejně jako starý (což by bylo určitě lepší, tenhle způsob nedá uživateli možnost to přehlédnout), nebo se to vyřeší aspoň nějakou hláškou/upozorněním.

**Comment by albertoh** [comment]
Delat tlacitka neaktivni, kdyz mame neulozene zmeny je jednoducha uprava

**Comment by luckajirku** [comment]
A to se pak aplikuje všude, nebo to jde teď omezit na změny v přesunu stran?

**Comment by luckajirku** [comment]
resp. ono to nebude jen u stran, ale v úložišti i u ročníků, čísel... Když člověk něco přesune a neuloží a v jiném panelu hrábne třeba do formuláře... Mám pak změněné pořadí objektů, v metadatech edituju, tu změnu v metadatech uložím, v tu chvíli se mi propíše i v tabulce, mám pocit, že je to OK, ale pak dám obnovit a objekt se mi vrátí na původní pozici a vůbec si toho nemusím všimnout. Tohle budeme muset pořádně promyslet.

**Comment by ZdenkaSera** [comment]
Schůzka 15.6.
jakmile jsou neuložené změny v kterémkoli okně v editaci (tj. včetně importu), nelze do uložení změn editovat v jiném okně
/

**Comment by albertoh** [comment]
Je mi jasne. Ale pockal bych s tim, jelikoz to bude mit dopad na rychlost.
Az bude rychlost vyhovujici, pustim se do tohoto issue

**Comment by ZdenkaSera** [comment]
@albertoh Prosíme o návrh/řešení k testu.

**Comment by luckajirku** [comment]
Vím, že to má prioritní label a že se s tím počítá, ale stejně to radši ještě vypíchnu:-). Pro nás už je to teď poslední věc, kterou je třeba dořešit, abychom začali klienta normálně používat. Máme představu, kdy by to mohlo být k testu?

**Comment by albertoh** [comment]
Delam na tom...
Zkusim neco mit na pristi tyden

**Comment by albertoh** [comment]
Je to na serveru.
Prosim o testovani.

**Comment by luckajirku** [comment]
Na první vyzkoušení super - stránky se přesunou, ostatní panely zašednou (tohle je lepší než v původním, kde přestal ten obsah být vidět úplně). Na přesuny stran to zdá se funguje dobře. Ale když edituju ve formuláři, tak nastává problém u hromadné úpravy. Editace jedné stránky se jeví v pořádku (změním pozici, číslo strany atd., ostatní panely zešednou, uložím enterem nebo přes disketu, a vše se zviditelní). U hromadné editace uložím změnu, problikne Změna byla uložena OK - ale disketa pořád svítí a ostatní panely jsou šedé. V tuhle chvíli můžu jediné - obnovit v prohlížeči - a pak se mi vše zviditelní (a ty provedené změny tam jsou).
![hromadnaeditace_ulozenizmeny](https://github.com/proarc/proarc-client/assets/6359479/6db1ceb0-03c0-4bb6-b865-d964aa3fa49f)

A pak se nám stalo několikrát, že obsah těch VŠECH panelů zmizel úplně a dávka se nedala už znovu otevřít a házela chybu - ale to bude asi zas jiný problém.

**Comment by katerinasirova** [comment]
Stejná zkušenost. U hromadné editace stačí, když člověk odklikne/odznačí, co vše chce editovat. Ještě jsem si říkala, že když si tam člověk hromadně upravuje "jen" typy stran, tak to jde, ale když by tam měl naklikáno více úprav, tak to by to uživatelsky nebylo příjemné. Asi nějaké storno nebo pokud to půjde upravit vývojářsky. V úložišti na to stačí obnovit ikonou refresh a vše, co člověk nechtěl uložit se stornuje.

**Comment by albertoh** [comment]
Opraveno (hromadna editace stran)

> A pak se nám stalo několikrát, že obsah těch VŠECH panelů zmizel úplně a dávka se nedala už znovu otevřít a házela chybu - ale to bude asi zas jiný problém.
  Je to nahodne? Pri jakych podminkach?

**Comment by luckajirku** [comment]
> > Je to nahodne? Pri jakych podminkach?
Kdybych to byla schopná popsat, tak to udělám, ale tady fakt nevím. Udělala to třeba dávka monografie/methodika krasopisu načtená svkhkadminem dnes v 11:45. Visí tam jako Načteno, ale skeny jsou pryč.

**Comment by ZdenkaSera** [comment]
@albertoh Tohle issue jsem vzhledem k jeho důležitosti konzultovala s @luckajirku - potvrdila mi, že blokování je ok. Náhodné chyby zřejmě mohou mít souvislost s tím, co řešíme v https://github.com/proarc/proarc-client/issues/487

**Comment by luckajirku** [comment]
ještě mi není jasné, proč při hromadném výběru všechno zešedne u Editovat typy stran a Editovat indexy stran už ve chvíli, kdy zaškrtnu tu volbu - ještě předtím, než nějakou změnu udělám

**Comment by albertoh** [comment]
U editovat typy stran, i prazdna hodnota znamena "normalni strana". Pro system to uz je znak, ze editujeme.
Indexy stran totez, uz tam mame jednicku, tj, jsme pripravene na zmeny.

Aby to se nestalo, mel bych projit vsechny vybrane strany a porovnavat aktualni stav s budoucim pri ulozeni... Zda se mi zbytecne komplikovane a navic potrebuju soucinnost bacjendu pro spravnosti

**Comment by luckajirku** [comment]
> U editovat typy stran, i prazdna hodnota znamena "normalni strana". 

a zrovna tohle mi přijde trochu divné - to se mi stalo, že jsem si přehodila hodnotu na prázdnou - a zařvalo to na mě, jestli chci uložit nevalidní data - tak odkliknu, že jo - a co udělá systém? - dá mi tam normální stranu. Pak mi nedává smysl, proč mi tvrdí, že ukládám nevalidní hodnotu, když mi tam sám doplní co chce, aby to nevalidní nebylo. A proč tam ta prázdná hodnota je, když nejde použít. 
Ono by totiž teoreticky tam bylo i využití pro prázdnou hodnotu - třeba ve chvíli, kdy si nebudu jistá typem některých stran a chci si je tam nechat vysvícené pro pozdější dořešení.

**Comment by albertoh** [comment]
To bylo pri hromadnem vyberu?

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prosím, udělal jsi tady nějakou změnu, kterou máme přetestovat (viz reference výše před pár minutami)?

@albertoh @SykoraLukas Jinak jsme se s @luckajirku domluvily, že otázka povolení nevyplněného typu strany a související otázky jsou na diskusi na schůzce, tak prosím tohle zatím nijak neměňte, verzi lze vydat takto. Děkuji 😊

**Comment by albertoh** [comment]
> @albertoh Alberto, prosím, udělal jsi tady nějakou změnu, kterou máme přetestovat (viz reference výše před pár minutami)?

Nene, to bylo ze vcerejska. Zapomnel jsem to sem pushnout

**Comment by ZdenkaSera** [comment]
Typ strany zůstane povinný - při nevyplněné hodnotě bude svíti červeně jako dosud. Rozdíl bude v tom, že se automaticky nedoplní defaultní hodnota.
Při importu: zaškrtávátko "generovat typ strany normální", defaultně zaškrtnuté (analogie ke generování indexu) - založit nové issue ZŠ

K dořešení: má se týkat strany, NDK strany a STT strany? 
Kontroly při exportu - pro strany není type povinný, negeneruje se do metadat - popsat, jak mají probíhat kontroly při exportu.
STT se nově už chová jako NDK STT strana (od zavedení repre/levá/pravá strana)

**Comment by ZdenkaSera** [comment]
NDK strana - typ strany normální by se měl zobrazovat, aby se prázdné místo nezaměňovalo s nevyplněným typem

**Comment by ZdenkaSera** [comment]
@luckajirku Lucko, prosím Tě, máte tohle u Vás nasazené? Zkusila jsem u nás na verzi 2.2.3 toto:
- přesunula jsem v rámci objektu 2 strany na jiné místo a neuložila
- klikla jsem na jinou stranu, změnila její typ a uložila ikonou v záhlaví formuláře této stránky nebo enterem
->> tím se provedl i celkový refresh a ty dvě přesunuté strany se vrátily na původní místo, disketa na horní liště ale zůstala aktivní  - myslím, že to ještě není úplně hotové - nebo se na ten problém dívám nesprávně? Díky za reakci.

**Comment by luckajirku** [comment]
@ZdenkaSera a máte verzi z jakého data? ve 2.2.3 z 29. 5. (na testu) i z 6. 5. (máme u nás) je to OK, po přesunu stran se bez uložení do formuláře ke změně typu strany nedostaneme.

**Comment by ZdenkaSera** [comment]
@luckajirku Aha - moc díky, v tom bude ten problém.

**Comment by ZdenkaSera** [comment]
@luckajirku Ještě - tohle issue tedy můžeme navrhnout k uzavření?

**Comment by luckajirku** [comment]
@ZdenkaSera jj, za nás je to OK

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
