### ISSUE TITLE
Profil/nastavení - Lokální nastavení jako primární

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#398]
V Nastavení je jako první nabízí osobní nastavení, ale to se mění opravdu zřídka. Většinou tam uživatel poleze kvůli lokálnímu nastavení - a teď musí zbytečně nejdřív kliknout na druhou záložku, místo toho, aby se mu to nabídlo rovnou.

**Comment by pkudela** [comment]
Ok, to zni logicky, zmenim.

**Comment by pkudela** [comment]
nasazeno, prosim otestovat

**Comment by luckajirku** [comment]
super, takhle je to lepší

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
