### ISSUE TITLE
Hromadné označení/editace stran

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#40]
hromadné označení/editace stran 
- nevidím, které náhledy jsou označené - naklikám je ručně, vidím “Hromadný výběr 8 objektů”, ale nevidím, které náhledy jsou označené. Vidět to je jen v “Tabulka”, což nestačí!!!
- označit řadu - chybí přednastavené řady, kde výsledkem bude 1a, 1b, 1c atp. a další možnosti typu aplikovat na každou x-tou stranu
- chybí uložení volby enterem bez nutnosti klikat na “uložit”

**Comment by honza-rychtar** [comment]
> nevidím, které náhledy jsou označené - naklikám je ručně, vidím “Hromadný výběr 8 objektů”, ale nevidím, které náhledy jsou označené. Vidět to je jen v “Tabulka”, což nestačí!!!

Už jdou vidět označené strany ve všech 3 zobrazeních.

> označit řadu - chybí přednastavené řady, kde výsledkem bude 1a, 1b, 1c atp. a další možnosti typu aplikovat na každou x-tou stranu

Doplněno.

> chybí uložení volby enterem bez nutnosti klikat na “uložit”

Enterem je teď možné ukládat, když jsem v input poli (index od, prefix, přírůstek, ...).
Pokud mám focus na dropdown menu při výběru ze slovníku (typ strany, řada, ...), tak je použití enteru pro uložení v konfliktu s tím, že v dropdown menu má enter svou funkci (výběr položky, kterou jsem vybral šipkami a nebo rozbalení položek).

**Comment by nezbedova** [comment]
Při hromadném výběru se mi nezapíše číslo strany ani po použití entru ani po kliknutí na uložit. Typ strany se zapíše.

**Comment by nezbedova** [comment]
`chybí uložení volby enterem bez nutnosti klikat na “uložit”` - to mi také chybí. Ve starém to funguje. Tohle hrozně to zpomaluje. Pokud vyplňuji postupně strany po jedné, tak musím z klávesnice na myš na posunutí a ještě kliknou do pole Číslo strany. Zkuste za sebou vyplnit čísla stran: FC, FS, SP, F1, F2, A1r, A1v.

**Comment by nezbedova** [comment]
Vadí mi, přednastavené číslo strany 1. Prosím nechat prázdné stejně jako tomu je u popisu jednotlivých stran

**Comment by nezbedova** [comment]
Ukázka po nastavení číslování od [1a] je
![obrazek](https://user-images.githubusercontent.com/13831946/90471394-72d43600-e11e-11ea-9b5e-e3bc2aa7eb14.png)

Nemohu ověřit, co se ve skutečnosti uloží, protože mi to nejde viz výše.

**Comment by nezbedova** [comment]
Po hromadném vyplnění typu strany (na číslech to nemohu zkoušet) zustávají označené strany pro další editaci a musím výběr zrušit. 

Chci to tak, jak to bylo. Označím hromadné, entr, automatický posun na následující obrázek, hromadné označení zmizí.

**Comment by tumovam** [comment]
Paní Nezbedová: Ukládání enterem funguje.

**Comment by hosak** [comment]
Stav k 14.9.2020:
Původní bod 1 je pořád s drobnou výhradou. Při zobrazení tří panelů (seznam objektů, metadata a náhled obrázku stránky) se při hromadném výběru vypne náhled obrázků, takže nevidím, co popisuji. 

Bod 2 je vyřešen. 

Bod 3 je vyřešen.

**Comment by tumovam** [comment]
Pro bod 1 založeno nové issue (https://github.com/proarc/proarc-client/issues/67)

Bod 2 (ozn. řady 1a, 1b, 1c,...) je OK 

Bod 3 (ukládání pomocí Enter) je OK

Navrhuji toto issue zavřít.

**Comment by nezbedova** [comment]
Enter funguje, ale neposunuje do dalšího okna. Založím na to nové issue, ať se tohle zavře.

**Comment by luckajirku** [comment]
samostatné issue na enter tady: https://github.com/proarc/proarc-client/issues/68

**Comment by luckajirku** [comment]
Část vyřešena, zbytek přesunut do nových issues, takže zavírám.
