### ISSUE TITLE
Volitelná barevnost aplikace

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#400]
Jubilejní čtyřsté issue si zaslouží něco pro radost:-), ne jen další hlášení nějaké chyby... Tak jen aby to nezapadlo - jak jsme se bavili na dubnové schůzce k designu, bylo by hezké, kdyby šlo změnit si barvy aplikace na jiné. Že by vedle téhle modromodré byly předpřipravené i jiné sady barev a v cfg by se to na úrovni jednotlivých instancí mohlo změnit na jinou sadu (jako kdyby to pak třeba i šlo na úrovni uživatele, bylo by to úplně nejlepší, ale to už bychom byli asi moc nároční...).

**Comment by pkudela** [comment]
@luckajirku s celkovou upravou barev aplikace, velikosti nekterych elementu, samozrejme stale pocitam, na to jsem nezapomel, jen ted byly jine priority a za me jeste kousicek chybi, aby bylo hotove issue #247 takze teprve pak se do toho budu moct pustit.

**Comment by luckajirku** [comment]
@pkudela však tě nehoním, jen jsem si to pro přehlednost potřebovala dát zvlášť (a taky zabrat tu 400:-))

**Comment by ZdenkaSera** [comment]
V konfiguraci se bude nastavovat primární barva instance.

**Comment by pkudela** [comment]
Prozatim jsme se dohodli, ze bude mozne zmenit v konfiguraci pouze barvu horni listy / navigace. Az bude na to prostor a vyhrazeny cas, bude mozno menit barvy cele aplikace, to bude ale vyzadovat upgrade celeho frameworku.

**Comment by albertoh** [comment]
Pridana moznost menit barvu horni listy v globals.js klicem navbarColor
Napr: 
navbarColor: '#449900'

**Comment by luckajirku** [comment]
za nás otestováno, fungují nám jednotlivé proarcy s modrou, zelenou, a nádherně růžovou lištou:-). je to fajn, že hned člověk vidí, ve kterém z nich je. a budeme se těšit, že někdy bude možno změnit barvu celé aplikace, jak bylo v plánu původně:-)

**Comment by ZdenkaSera** [comment]
Na základě domluvy na schůzce vývojového týmu 3.9.2024 issue zavírám. Další rozvoj po upgradu sw.
