### ISSUE TITLE
Chybné přebírání rolí z katalogu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#407]
Pokud mám v katalogu autora v poli 100 a další v 700, vyplní se k oběma stejná role převzatá z pole 700. Test v KNAV a na Inovatice.

**Příklad**
- Katalog KNAV, sysno = 000875010
- autor v poli 100 - role aut
- autor v poli 700 - trl
- do ProArcu se oběma autům doplní role trl

![image](https://github.com/proarc/proarc-client/assets/79305516/e7bcb5a2-6fd6-4e85-b6b1-eb7cfb5fe8c9)

**Comment by ZdenkaSera** [comment]
**Příklad, kde se role vůbec nepřevzaly**
- Katalog KNAV, sysno = 001939531 (vícedílná monografie)
- dva autoři, oba v poli 700
- role se do NDK svazku monografie nestáhne ani k jednomu (je jedno, jestli svazek zakládám samostatně nebo "plusem" pod vícedílkou)

![image](https://github.com/proarc/proarc-client/assets/79305516/2ce3694e-7255-4991-92a1-f7031afb4ae1)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím, podíval by ses na tohle? Je to sice ručně opravitelné, ale musí se kontrolovat katalog, co v něm původně bylo, pokud chceme mít metadata podle katalogu. Moc díky.

**Comment by hosak** [comment]
Bug potvrzuji. Máme monografii, autorka ve 100 s rolí aut, překladatel v 700 s rolí trl. 
![image](https://github.com/proarc/proarc-client/assets/19148958/764e915a-592e-4be0-835b-5dde23073b02)

Při stažení do proarcu mi to ale k oběma přiřadí roli trl, takže z autorky je bugem vytvořena překladatelka a knize chybí autor. 
![image](https://github.com/proarc/proarc-client/assets/19148958/88e6e76a-5f3e-4b40-acb2-54633fa88692)

**Comment by SykoraLukas** [comment]
@albertoh prosím o opravu.
Nejspíše to je v nějakém načítání dat z formuláře, protože ihned po stažení je to v xml správně a ve dormuláři už to je špatně.

<img width="1277" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/cb2ea4cb-d8fe-4a92-8dd7-b594846fd4ce">

**Comment by albertoh** [comment]
Opraveno. Je na testu

**Comment by ZdenkaSera** [comment]
Tohle za nás vypadá ok, nenašla jsem protipříklad. Díky.
