### ISSUE TITLE
Omezit možnost přidat PDF pouze na born-digital modely

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#408]
Na úroveň NDK Vícedílné eMonografie je možné nahrát PDF skrze panel Media. Nemělo by to ale jít, jedná se jen o metadatovou úroveň, PDF se přidávají až k jednotlivým svazkům. Soubor se dokonce dostane i do NDK SIP exportu, kde nemá být. 

Díky

**Comment by ZdenkaSera** [comment]
Prosím, je tady nějaký posun? Jen to otáčím, prio1 to není. Díky.

**Comment by kerschfilip** [comment]
Problém je obecnější. Nový klient (testováno na verzi 4.1.1-Plus - Build 20240102105644) umožňuje přidat PDF asi úplně ke všem modelům (povedlo se mi to u NDK Monografie i STT konvolutu). Správně by to mělo být umožněno jen u eČlánku, NDK eČlánku, NDK Svazku eMonografie a NDK Přílohy eMonografie.

Šlo by to, prosím, nějak ošetřit? Díky!

**Comment by ZdenkaSera** [comment]
@albertoh Pokud se správně koukám, tohle je přidáno v globals ..?

**Comment by albertoh** [comment]
Ne ne, je to v kodu

**Comment by kerschfilip** [comment]
Za mě OK, děkuju!
