### ISSUE TITLE
Nejde smazat e-článek s nadřazeným objektem (pouze na Inovatice)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#409]
V rámci issue https://github.com/proarc/proarc-client/issues/171 jsem zadala toto: "ečlánek nejde trvale smazat, pokud má nadřazený objekt . to je ok, ale hlášku prosíme upravit", řešil @pkudela 

Ukázalo se, že problém je jen na Inovatice, v KNAV na OZČ se to neděje (testováno s nejnovější verzí 4.0.3/2.1.0).  Tj. z Inovatiky se problém zatím nepřenesl dál a ani to nechceme, e-články mají jít mazat aniž by se musely odpojovat.

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, priznam se, ze jsem se ztratil, co mam tedy udelat? Muzes mi to prosim vice specifikovat? Diky

**Comment by ZdenkaSera** [comment]
Když jsem na Inovatice narazila na to, že nejde přiřazený článek smazat, domnívala jsem se, že je to správně, jen je nepřeložená hláška do lidštiny. Po konzultaci s kolegy, kteří s tím pracují, je to tak, že přiřazený článek má jít smazat. Takže na Inovatice je nějaká chyba, která tomu brání, zároveň se ale s poslední verzí nepřenesla dál, v KNAV to funguje správně i s nasazenou v4.0.3/2.1.0.. Takže jde o to na Inovatice to opravit tak, aby se to blokování s nějakoou příští verzí nepřevzalo dál..

**Comment by pkudela** [comment]
ahaaaa, proberu tedy s Albertem, diky
