### ISSUE TITLE
Chyba validace zvuku - nelze uložit dávku do úložiště

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#410]
Ve správě dávek v editaci si popíšu objekty, ale nelze pokračovat dál a uložit je do úložiště. Hlásí chybu validace u zvukových souborů, ale všechna povinná pole, která vidím, jsou vyplněná.  Ať už má zvukový soubor jakýkoli index - zkoušela jsem 1, navazující číslování po obrazových souborech - nechce mě to pustit dál.

![image](https://github.com/proarc/proarc/assets/8912422/1ec8b4d8-b145-4be9-8393-8274442f4cf5)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, jak to vypadá s tímhle? Díky.

**Comment by katerinasirova** [comment]
Otestováno. Na modelu "NDK Fonografický váleček" - dávka o jedno zvukovém souboru a několika obrázcích oindexována, tvářila se jako úspěšně uložena, tváří se jako připojeno, ale pod tím zvukovým válečkem nic nevidím. 
Při snaze spustit validaci zvlášť se to o něco snažilo, ale výsledek se ani po 1/2 hodině nedostavil.
Model "NDK Zvukový dokument"  - tam je pod gramodeskou jen několik zvukových souborů bez obrázků, indexování proběhlo OK, ale nešlo je zařadit přímo pod zvukový dokument. Zkoušela jsem, kde mě to pustí jinde a šlo to připojit zvukové soubory pod NDK Skladba", ale tam to zase navíc vytvořilo další úroveň Skladba - viz obrázek.

![image](https://github.com/proarc/proarc-client/assets/8912422/6dbdaa61-81ca-4a4b-b9fb-059d5b572054)

Při snaze to obejít šlo přesunout jednu z nově vytvořených skladeb pod model NDK zvukový dokument a to se tváří, že proběhlo v pořádku:
![image](https://github.com/proarc/proarc-client/assets/8912422/25f2ed11-52a5-49c7-90c7-6325cca36517)

Validace u zvukových souborů u gramodesek začala na prvním souboru ze 6 a také jí to trvalo tak dlouho až jsem to vzdala.

Rozhodně prosím @SykoraLukas kvůli testování doplnit balíček souborů ke gramodeskám o obraz nebo přidat nový balíček, ať otestuju chování všech typů souborů.

**Comment by katerinasirova** [comment]
@ZdenkaSera ano, chybí jen tohle, ale pro zvukové dokumenty je to zásadní, takže až bude tohle vyřešeno, za nás se může vydat verze. Jinak nelze zvukové dokumenty zpracovat, takže čekáme na vyjádření @SykoraLukas.

**Comment by ZdenkaSera** [comment]
@katerinasirova Díky za rychlou reakci.

**Comment by SykoraLukas** [comment]
Doplněn balíček. vyřešeno ukládání s tvorbou hierarchie (pokud je správně popsáno). Pokud není, napojuje se vše pod vybraný objekt. Rovněž vyřešena validace Zvukové nahrávky.

**Comment by SykoraLukas** [comment]
Nutné přetestovat.

**Comment by katerinasirova** [comment]
Vyzkoušeno a otestováno na válečku i gramodesce. Nalezen jeden problém, a to při přesunu zvukové nahrávky zařazené z NDK Skladba do NDK Část skladby - tahle úroveň je pod tou druhou umístěná:

![image](https://github.com/proarc/proarc-client/assets/8912422/70c0d372-dcac-4c3f-93a4-6a85a1e51081)

Nelze přesunout zvukovou nahrávku 11 z NDK Skladby pod NDK Část skladby
![image](https://github.com/proarc/proarc-client/assets/8912422/6f0d10db-58e8-4f79-a9a2-fb827095bb92)

Situace může nastat, když dojde ke špatné interpretaci na začátku a bude potřeba doplnit další úroveň.

Validaci hlásí OK. 

Testováno včera odpoledne i dnes ráno a odpovědi systému na jakékoli překliknutí v rámci kontroly indexování v úložišti dlouho trvá a často se to celé zasekne. A to jde "jen" o zobrazení metadat - nevím, jestli jste tam ještě něco nedělali, ale je to nepříjemné.

@ZdenkaSera bohužel jsem ještě objevila 2 problémy, které je třeba pro práci se zvukovými soubory s novým klientem vyřešit, aby bylo možné s ním pracovat. Jsou to issue: #412 a #413. Po jejich opravení, pokud to půjde, můžeme vydat verzi. Díky

**Comment by ZdenkaSera** [comment]
@katerinasirova Moc díky za info. @SykoraLukas Vidím čerstvý štítek "probíhá", takže jsou ty dvě věci rychle realizovatelné? Díky!

**Comment by SykoraLukas** [comment]
Zkus prosím problem s tím přesunem znovu, ale nejdřív si refreshni prohlížeč. (Ctrl + F5)

**Comment by SykoraLukas** [comment]
Ještě jsem doplnil informaci o jaký model se jedná. U skladby a části skladby je to často jedinné rozlišení.

<img width="1234" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/76ca4862-83ef-478f-8403-15140f1fb32c">

**Comment by SykoraLukas** [comment]
Pošli prosím screen

**Comment by katerinasirova** [comment]
![image](https://github.com/proarc/proarc-client/assets/8912422/33a1fee6-4a14-40a5-b50e-aa236b114a9d)
Stačí takhle?

**Comment by SykoraLukas** [comment]
V levém slopci nemáš vybraný model, který chceš přesunout.

**Comment by katerinasirova** [comment]
Super, už vidím chybu, problém mezi klávesnicí a židlí. Díky za osvětlení, funguje, vyzkoušeno. I to vypadá, že rychlost odezvy se výrazně vylepšila. Za nás vyřešeno. Děkuju

**Comment by katerinasirova** [comment]
@ZdenkaSera ještě mám k #412 dotaz, ale ostatní vyřešeno, verze se za nás může vydat :-)

**Comment by ZdenkaSera** [comment]
@katerinasirova Super, díky za ten fofr při testech 👍

**Comment by katerinasirova** [comment]
@SykoraLukas - dopisuju sem, protože myslím, že se jedná o podobný problém jako minule - nebo mám založit separátní issue?
Zkouším testovat zvukový dokument s částmi skladby, mám popsáno a chci uložit pod vytvořený objekt NDK Zvukový dokument , po vybrání daného zvukového dokumentu je ikona Uložit neaktivní:

![image](https://github.com/proarc/proarc-client/assets/8912422/fd12ec2d-dbef-4530-93c7-417b2549d192)


![image](https://github.com/proarc/proarc-client/assets/8912422/80930c80-9903-4a67-81a4-e79031055261)

Jedná se o soubory pojmenované podle dohody. V předchozí verzi produkčního PA zpracované.

**Comment by SykoraLukas** [comment]
jakou mate verzi api a klienta?

**Comment by SykoraLukas** [comment]
a zkus udelat validaci objektu, jak ta dopadla?

**Comment by katerinasirova** [comment]
Validaci jsem spouštěla a vše OK a verze: 
klient :v2.1.1 (14.07.2023)
jádro: Verze:4.0.4, Build:20230713162836

**Comment by katerinasirova** [comment]
Otestuji jedině, když mi do testu nahraješ data s nějakou částí  - pošlu ti balíček na mail nebo máš nějaká data z NM?

**Comment by SykoraLukas** [comment]
Pošli mi balíček na mail. Max 5 gb

**Comment by SykoraLukas** [comment]
Nahráno, můžeš otestovat.

**Comment by katerinasirova** [comment]
Otestováno, soubory šly uložit do úložiště pod NDK Zvukový dokument a struktura se vytvořila správně, díky. Nainstalujeme u nás na testu a já zkusím import jiných souborů.

**Comment by ZdenkaSera** [comment]
Zavírám vzhledem k návrhu na zavření od autora issue.
