### ISSUE TITLE
V tabulce se strukturou se neaktualizuje název uloženého objektu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#411]
Po uložení ečlánku občas zůstane viset vlevo ve struktuře otazník a nevidím tam název článku.
Na screenshotu je vidět, že článek má vyplněný title a je uložený, ale vlevo je na místě názvu jen otazník. Při uložení by se měla Tabulka vlevo vždy aktualizovat a načíst znovu, tady se to ale asi nestalo. Když jsem to aktualizovala, pak se to propsalo.

![image](https://github.com/proarc/proarc-client/assets/79305516/3fd34f83-8aa5-41e5-8d42-7989ac84e708)

**Comment by ZdenkaSera** [comment]
@albertoh K tomuhle ještě musíme přidat "Prio 1" - děkuji.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Zdá se to ok, děkujeme.
