### ISSUE TITLE
Chyba ukládání metadat na úrovni "NDK Skladba"

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#413]
Při snaze doplnit metadata na úrovni NDK Skladba (záznam vznikl při automatickém generování struktury, a to ze záznamu staženého z katalogu) to nahlásí chybu u dvou polí: classification (jako takové je R, M je pouze "authority")  a Table of contents (MA). Evidentně pole obsahují nějaké informace, ale když je klasicky umažu přes ikonu Smazat a dám uložit, tak se mi vrátí zpátky a nejdou uložit.
A v XML tato pole vůbec nejsou zobrazená.

![image](https://github.com/proarc/proarc-client/assets/8912422/e51ce0a7-b33d-4149-92d9-c850e880fd41)

**Comment by katerinasirova** [comment]
@albertoh nebo @SykoraLukas  - nevím, na koho je tohle, asi problém se šablonou, můžete se na to také podívat? Díky

**Comment by SykoraLukas** [comment]
Opraveno.

**Comment by katerinasirova** [comment]
Otestováno jak na stávajících datech, tak nově vytvořených - OK. Možno zavřít, díky za opravu.
