### ISSUE TITLE
Konfigurace klienta  - globals - lang

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#414]
@albertoh @pkudela V globals je toto nastavení jazyka: **lang: 'en'**
- Prosím, co konkrétně se jím v klientovi řídí?

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, do ted to nefungovalo spravne Alberto to opravil. Ted to funguje tak, ze pokud mas jazyk v local storage, tak se to ridi tim, jaky jazyk jsi si naposled zvolila. V pripade, ze local storage vymazes, napr. pres nastaveni v profilu, tak pri reloadu prohlizece se nacte jazyk, ktery mas jako default nastaveny v globals.js ovsem do doby, nez opet kliknes na prepnuti jazyku, pak uz se bude brat opet hodnota z local storage. Doufam, ze jsem to vysvetlil spravne :-) je to otestovano a nasazeno na dev server.

**Comment by ZdenkaSera** [comment]
@pkudela Super, moc díky, zdá se mi to jasné, vyzkouším :-)  Jaký jazyk je teď na Inovatiice v globals nastaven? 
(Issue tedy změním na dedikované téhle věci a na další dotazy si otevřu nové ;-))

**Comment by pkudela** [comment]
V konfiguraci na vyvojovem serveru je ted nastaveny default jazyk en -> https://proarc.inovatika.dev/assets/shared/globals.js
Cili kdyz smazes local storage a das tvrdy reload prohlizece, tak by se ti vse melo zobrazit v anglictine, takto to muzes otestovat.

**Comment by pkudela** [comment]
Ted jsem to zkousel, dle meho, pokud to bude fungovat spravne i Tobe, tak to rovnou muzes zavrit.

**Comment by ZdenkaSera** [comment]
za mne ok 👍, otestovala jsem přihlášením v anonymním okně. Díky!
