### ISSUE TITLE
Rychlost klienta

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#416]
Opakovaně na lokální instanci KNAV i na Inovatice narážíme na situaci, kdy se zobrazení dat v klientovi "zadrhává", vázne. Typicky při pohybu ve formuláři je občas skoro nemožné vybrat hodnotu z roletky - rozkliknu ji a čekám na zobrazení hodnot, špatně se z nich pak i vybírá. Protože stav není trvalý, nedokázali jsme jej spojit s možnou příčinou.
Na základě testů na KNAV instanci, kde se zpracovávají e-články, vzniklo podezření, že by toto chování mohlo souviset s délkou zpracovávaného formuláře/množstvím dat v něm zadaných. Bohužel je díky tomu pro zpracování článků klient v současné podobě nevhodný. 
@albertoh @pkudela Prosím, mohli byste zvážit možné důvody a jejich odstranění? Děkujeme.

**Comment by katerinasirova** [comment]
Připojuji se k apelu na rychlost klienta, u zvukových dokumentů jsem o tom psala, ale nebyla jsem si jistá, jestli jste zrovna při testování něco nedělali u vás na serverech. 
Máme nasazeno u nás na testu - odezva tam vždy byla docela slušná a v této verzi trvá neúměrně dlouho hlavně načítání formuláře - kolečko se točí a točí. A když už tam udělám nějakou změnu, tak trvá strašně dlouho než se projeví ve stromě nebo než můžu dál pracovat.

**Comment by ZdenkaSera** [comment]
Narazila jsem na potíže s rychlostí klienta také zde Pomalej klient  https://github.com/proarc/proarc-client/issues/220.

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Od nás je teď klient na https://proarc-2023.inovatika.dev/ tak pomalý, že vybrat hodnotu z roletky nebo přejít do jiného pole je dost obtížné. Během dne to tak nebylo.

**Comment by ZdenkaSera** [comment]
Klient na Inovatice je dnes chvílemi tak pomalý, že se "předbíhá" - při zakládání nového objektu jsem podruhé kliklla na uložení  - zřejmě znovu přidělil stejný PID, protože ten z prvního pokusu asi ještě nebyl uložen;  ale vzápětí se tak asi stalo a systém zahlásil duplicitu

![image](https://github.com/proarc/proarc-client/assets/79305516/a2c62bce-bf6e-429b-a2e1-bc63faa3843f)

**Comment by albertoh** [comment]
Koukam na to. Zatim u me bezi v poradku, a tezko nejdu pricinu :(

**Comment by ZdenkaSera** [comment]
Je to střídavé - teď jsem se tedy znovu přihlásila - a jede bez problémů...

**Comment by ZdenkaSera** [comment]
@albertoh Přechválila jsem, ve formuláři to fakt drhne :-( i teď. Ale za 2 minuty třeba nebude ..

**Comment by katerinasirova** [comment]
Připojuji se, kolem 10.20 jsem ukazovala něco kolegyni a také to drhlo, takže to není připojením KNAV.

**Comment by albertoh** [comment]
Na test jsem nahral prvni zlepseni v rychlosti. Prosim otestujte.

**Comment by ZdenkaSera** [comment]
master nebo 2023 ?

**Comment by albertoh** [comment]
Oboji

**Comment by ZdenkaSera** [comment]
Zkusila jsem na https://proarc-2023.inovatika.dev/ - první dojem super 👍, líp otestujeme až při větším zatížení.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, je tahle úprava zahrnuté v poslední vydané verzi?

**Comment by albertoh** [comment]
Jo, mela by tam byt

**Comment by katerinasirova** [comment]
Otestováno i lokálně, rozhodně je odezva a načítání rychlejší. 
Kde to moc nepomohlo - resp., kde se klient zadrhává:
- dlouhý formulář - načte jen první část a druhou odmítá dočíst, vypadá to, že tam žádná další metadata nesjou - i když vím, že tam jsou, pomůže jedině F5 (takové chování vypozorováno u testu NDK Zvukový dokument, resp. přepínání mezi úrovněmi NDK Skladba a NDK Část skladby)
- při připnutí obrázku a zvuku (celkem připnuto něco ve 2 panelech médií) se odmítají metadata ve formuláři přepnout, pomůže jedině F5

Problematické je, že není nikde vidět, že by systém/klient stále pracoval - tj. řeším, jestli mám počkat, došlo k přepnutí nebo ze zasekl. Typické je to právě u zvukových souborů, protože podúrovně (NDK Skladba a NDK Část skladby) se po uložení do úložiště jmenují všechny stejně podle ZD, takže když začínám upravovat, tak nevím, co upravuji.

**Comment by albertoh** [comment]
Pridal jsem dalsi moznost v editaci metadat pro zlepseni rychlosti:

![image](https://github.com/proarc/proarc-client/assets/5946836/84882699-de07-4e9b-9c7a-59fa3124b5e1)

Nove tlacitko umoznuje editovat formular jen po castech:

![image](https://github.com/proarc/proarc-client/assets/5946836/3f325ee4-0729-46bd-be97-8bcc1952e0b2)


![image](https://github.com/proarc/proarc-client/assets/5946836/f6ff72a5-3a43-444b-bbbd-4c07043d2197)

Pri zobrazeni jen vybraneho elementa rychlost se mnohonasobne zvysi.

Pracuju dal... Oprava celkove rychlosti velkeho formulare ale mi jeste potrva dlouho

**Comment by ZdenkaSera** [comment]
@albertoh Díky za úpravu - v KNAV jsme vyzkoušeli a za nás to vidíme takto:
- Při editaci (opravě metadat)/vyhledávání se funkce může hodit, takže bychom ji ponechali :-)
- Při běžné práci - zakládání objektů - to ale nepůjde používat; připomínám, že jsme naopak chtěli možnost nastavit úplné rozbalení formuláře
- Za nás tedy bude zapotřebí problém s rychlostí klienta vyřešit jinak

**Comment by albertoh** [comment]
Vzhledem k tomu, ze zasah do kodu je prilis velky, na serveru je nove testovaci url.

https://proarc-rychlost.inovatika.dev/

Tam jsou zmeny, ktery by mely zrychlit formular. Prosim o testovani tam.
Jeste jsem nezkoncil, ale nejake zrychleni uz je.

**Comment by katerinasirova** [comment]
Při včerejším testování se při využití klasického formuláře opět nenačetla metadata po klikání na různé úrovně popisu - NDK Skladba a NDK Část skladby (takové chování vypozorováno u testu NDK Zvukový dokument, resp. přepínání mezi úrovněmi NDK Skladba a NDK Část skladby). Pomohlo tentokrát i přepnutí jinam a návrat zpátky na požadovanou úroveň. Rychlost se výrazně zlepšila.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, tohle je issue, o kterém jsme se bavily. Díky :-)

**Comment by katerinasirova** [comment]
Otestováno na inovatice, přepínání se jeví svižně. Za mě tady spokojenost, hlavní test přijde po nasazení na lokál. Díky za úpravu. Za nás spokojenost.

**Comment by ZdenkaSera** [comment]
Tak to je skvěle - přidala jsem otestováno i za KNAV + návrh na uzavření, ale zavřeme až po lokálním testu.
