### ISSUE TITLE
Roletka Type pro `Genre` u eČlánků a NDK eČlánků do češtiny 

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#417]
Prosím o úpravu roletky při výběru Type u `Genre` tak, aby nabízela názvy v češtině. Platí pro eČlánky i NDK eČlánky. Teď je to v klientovi anglicky, v jádře česky. Děkuju
![image](https://github.com/proarc/proarc-client/assets/57805328/8251faae-ca46-455f-a28e-8d22b932c18f)

**Comment by SykoraLukas** [comment]
Vzniklo to tím, že se udělala česká lokalizace ProArcu ale s anglickými názvy polí. Vzhledem k vývoji v #192, bych navrhoval takovéto řešení:
3 lokalizace:

- celá aj (celý proarc v aj, popisky polí ve formuláři v aj, popisky ve výběrových polích v aj)
- celá čj (celý proarc v čj, popisky polí ve formuláři v čj, popisky ve výběrových polích v čj)
- kombinovaný (celý proarc v čj, popisky polí ve formuláři v aj, popisky ve výběrových polích formuláře v podobě čj (aj))


Co si to tomto řešení myslíte? @katerinasirova @kerschfilip @luckajirku @ZdenkaSera @erikamirova

**Comment by kerschfilip** [comment]
@SykoraLukas souhlasím. Šlo by lokalizaci přidat do nastavení profilu, nebo musí být na úrovni konfigurace aplikace?

**Comment by SykoraLukas** [comment]
Neuvažujeme ani o jednom. Představa je, ze vpravo nahoře jak se dá nyní přepínat mezi cs a en se přidá další možnost. Jen místo klikání tam bude rozbalovací seznam (+ bude připraveno pro další jazykové mutace)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Za mne ok, ještě to ale probereme interně s kolegyněmi v DC (po dovolených příští týden).

**Comment by katerinasirova** [comment]
Za nás také OK.

**Comment by ZdenkaSera** [comment]
Souvisí s https://github.com/proarc/proarc-client/issues/192
