### ISSUE TITLE
Verze klienta

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc-client#418]
Zdravím,

nasadil jsem verzi 2.1.2, klient v nabídce "o aplikaci" ale píše tohle:

Verze:v2.1.1 (24.07.2023)

Datum je správně, verze špatně.

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, až budeš (dnes ? 😉) vydávat verzi, prosím, ohlídej údaj o verzi, který se promítá do aplikace, aby to sedělo -  viz výše. Moc díky!

**Comment by SykoraLukas** [comment]
Poslední jsem vydával já a proto to nesedělo. Již snad nenastane.
