### ISSUE TITLE
Import - proč tak složitě?

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#42]
V záložce “Import” se z nepochopitelného důvodu roztřídí načtené dávky do nějakých kategorií - monografie, periodikum atd. Teprve uvnitř jsou pak složky s daty. Proč přibyl zbytečné další krok, kvůli kterému nejde se rychle dostat k datům? Při popisu je toto naprosto zbytečné, typ dokumentu je důležitý až od vytváření objektu.

**Comment by SykoraLukas** [comment]
Jde jen o vytvořené složky na straně serveru.
