### ISSUE TITLE
Vytvoreni rozcestniku pro aplikaci ProArc

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#422]
- [x] vyvorit nove domeny proarc-master.inovatika.dev a proarc-2023.inovatika.dev
- [x] vytvorit nove virtual hosts pro domeny proarc-master.inovatika.dev a proarc-2023.inovatika.dev
- [x] provest konfigurace + zprovoznit https pro tyto domeny
- [x] vytvvorit adresarovou strukturu pro tyto domeny
- [x] vytvorit index.html, kde bude rozcestnik, ktery bude lezet na adrese proarc.inovatika.dev
- [x] otestovat

**Comment by ZdenkaSera** [comment]
@pkudela Petře, jak dlouho bude nedostupný klient na Inovatice? Děkuji.

**Comment by pkudela** [comment]
@ZdenkaSera ahoj, rozcestnik byl uz vcera normalne pristupny -> https://proarc.inovatika.dev/, pokud Ti nefunguje, zkus si dat tvrdy reload prohlizece, nebo vymazat cache prohlizece.

<img width="948" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/c7f0d95e-02ed-44b8-897b-6a2e7cbfebd2">

**Comment by ZdenkaSera** [comment]
@pkudela Ahoj, díky, mám pod současnou adresou rozcestníku uloženou adresu s loginem do klienta, takže to nemohlo fungovat :-) Už dobrý, díky.

**Comment by pkudela** [comment]
Aha, tak to bylo ono, ten rozcestnik jsme udelali proto, ze uz tech ruznych verzi k testovani je vic a nikdo to asi v hlave nedrzi, jakmile napr. redesign bude schvaleny, tak udelame merge do masteru a ten jeden odkaz zmizi, nebude potreba.

**Comment by luckajirku** [comment]
Zeptám se teda úplně hloupě - co a kde teda máme testovat:-). Když zadáme chybu, tak bude v tuhle chvíli opravena jen v to doméně master a ve zbytku se to testovat zatím nemá, protože tam se to zatím opravovat nebude, ok? A v redesignu máme teď řešit čistě jen design, ne to, jestli je to plně funkční?

**Comment by pkudela** [comment]
ahoj Lucko, co se tyce verze k redesignu, tak je to presne jak pises, ano reste ciste novy design, co se tyce toho dalsiho, odpovi Ti @SykoraLukas

**Comment by SykoraLukas** [comment]
Zasadni chyby se budou opravovat vsude (udela se to masteru a z nej se to prebere i do ostatnich). Chyby ohledne vyvoje do visku se resi jen ve visku. V redisignu se resi ciste jen design

**Comment by ZdenkaSera** [comment]
@pkudela Drobný překlep na oušku - chybí "n"

![image](https://github.com/proarc/proarc-client/assets/79305516/708dfe0a-a578-4010-bc46-61c303b81403)

**Comment by pkudela** [comment]
@ZdenkaSera opraveno
<img width="638" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/f6d0bdfd-2c46-4a57-8ed0-0d48eaaf8b6b">

Zaviram
