### ISSUE TITLE
NDK Import do Krameria

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#423]
Po vzoru Krameria, vytvořit export pro NDK PSP s automatickým nahráním do Krameria. Aby se předešlo problémům, bude mít tento export svůj druh exportu (zůstává klasický samotný export + nově rozšířený o policy a instanci Krameria)

**Comment by ZdenkaSera** [comment]
Souvisí s https://github.com/proarc/proarc/issues/1177

**Comment by ZdenkaSera** [comment]
Na masteru v nabídce exportů - ok, test až lokálně.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, výše info, že jsem to v klientovi na inovatice zkoušela. Když se chci podívat dnes, v klientovi možnost výběru nevidím a nejsem si jistá, jak nabídka importu NDK do Krameria vypadala - má se zde nabízet možnost exportovat balíček lokálně nebo do K7? Buď jsem to zapomněla nebo je na Inovatice-masteru chyba. Prosím o vyjasnění, jak je naplánováno uživatelské rozhraní fce. Děkuji.

![image](https://github.com/proarc/proarc-client/assets/79305516/16792593-2a6f-4627-ae7d-6e3a6ac082be)

**Comment by SykoraLukas** [comment]
Varianta nebyla nakonfigurováva: 

<img width="752" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/a32eaca9-afeb-44aa-abf1-fe83cd1c7c30">


Do konfigu klienta je potřeba přidat: `ndk_psp_upload_kramerius` případně `ndk_oldprint_upload_kramerius`.

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Nefungue pro e-modely - viz zápis https://github.com/proarc/proarc/issues/1433

**Comment by ZdenkaSera** [comment]
Verze 4.1.3./2.2.2 - Import NDK PSP do K5 v KNAV ok, zatím jen test na nově vytvořené NDK monografii a importovaném NDK balíčku mongrafie s přílohou.

**Comment by SykoraLukas** [comment]
Doplněna hodnota do konfigurace a překlady.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
