### ISSUE TITLE
Převod "Stran" na NDK a zpět - nehlásí chybu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#424]
Podpora klienta pro [#proarc/proarc:1599](https://github.com/proarc/proarc/issues/1599)

**Comment by ZdenkaSera** [comment]
@albertoh Kopíruji z issue v jádře: V KNAV převody STT stran na NDK a zpět možná využijeme při přechodu na Krameria 7. Prosíme ponechat zeleně označené možnosti. Díky.
![image](https://github.com/proarc/proarc/assets/79305516/a91fcb57-0523-4415-9d84-bd7865ea400d)

**Comment by SykoraLukas** [comment]
Hotove.

**Comment by ZdenkaSera** [comment]
Tohle už bylo v jedné předchozí verzi klienta ok, ale s poslední verzí  z 19.9. se to nedaří. Přetestujeme v příští verzi.

**Comment by ZdenkaSera** [comment]
přetestováno na masteru - ok

**Comment by ZdenkaSera** [comment]
Podařilo se mi v KNAV nasimulovat chybu při převodu stran na NDK strany - klient chybu hlásí, to je ok, počty taky sedí.. Jen prosím o úpravu textu, aby byla celá hláška v jednom jazyce
V češtině např. 
Nepodařilo se převést model. Detail: PID: uuid:d73df964-7712-41c9-9657-0f5ceb46be5d, Převedeno 79 položek z 288..

![image](https://github.com/proarc/proarc-client/assets/79305516/d9380ee1-f581-4ed2-9e1a-b0006fb772c2)

**Comment by ZdenkaSera** [comment]
Tohle zatím zavírám, funkční lokálně i ve verzi 2.2.1/4.1.1.. Text budeme případně řešit později.
