### ISSUE TITLE
Opravy urn:nbn - fáze I - Zneplatnění urn:nbn v ProArcu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#425]
Klientská podpora pro https://github.com/proarc/proarc/issues/1589

@albertoh mohl bys pros9m doplnit novou funkci do branch Visk23?

Volání je!

``` properties
### INVALIDATE URNNBN
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/invalidateLocal
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{uuid}}
```

Otázky pro @ZdenkaSera, @erikamirova, @luckajirku, @katerinasirova 

- Jak to prezentovat uživatelům (jestli URN:NBN udelat jako seznam a dát tam registrovat a zneplatnit)
- Jak pojmenovat? navrhuji `Lokálně zneplatnit`

**Comment by ZdenkaSera** [comment]
Ten krok zneplatnění nebude tak častý, zatímco přidělování urn:nbn je na denním pořádku - proto bych přidělení radši nechala na liště tak, jak je dnes. "Lokální zneplatnění" - s tím názvem souhlasím, aby se to nepletlo, že tohle nesahá do resolveru. Ale i když je to lokální fce, klidně bych ji přidala do skupinky (seznamu) s ostatními opravnými funkcemi resolveru. Záleží, jak to vidí ostatní.

**Comment by SykoraLukas** [comment]
Takže nechat URN:NBN a pak udelat seznam (s nazvem Další URN:NBN) a přidat to pod tento seznam?

**Comment by ZdenkaSera** [comment]
Za KNAV ano, Název toho seznamu jsem pro krátkost a odlišení navrhovala CZIDLO, ale na tom netrváme, přizpůsobíme se

**Comment by SykoraLukas** [comment]
Funkce je dostupná pouze pokud má uživatel roli czidloFunction nebo je superadmin.

**Comment by ZdenkaSera** [comment]
přetestováno na masteru - ok
