### ISSUE TITLE
Nezobrazuje se role autora (KNAV v2.1.3.) + chybné stahování rolí (Inovatika -master)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#426]
Pokud stáhnu z katalogu k autorovi více rolí, z nichž jedna není uvedena v kontrolním seznamu v ProArcu, nezobrazuje se ve formuláři v "RoleTerm" žádná z nich. (KNAV, 4.0.7-DEV/v2.1.2 i v kombinaci   4.0.7-DEV/v2.1.3)

![image](https://github.com/proarc/proarc-client/assets/79305516/5f28811d-106c-4723-a793-d01bc0151196)

![image](https://github.com/proarc/proarc-client/assets/79305516/b9504430-f8d4-42e6-9589-2f4335b610b5)

Chtěla jsem udělat příklad na Inoivatice -masteru (uuid:aa3c9e6b-44e5-4bd6-bf36-b2a0e24155fe (data: KNAV monografie, sysno = 000799794); Tam se ale zatím vrátila už řešená chyb, kdy se stejná (poslední v řadě) role vyplní do všech:

![image](https://github.com/proarc/proarc-client/assets/79305516/4a334ff8-9259-4e5c-82ba-d2cfbd5e6709)

**Comment by SykoraLukas** [comment]
@ZdenkaSera na masteru je vyresena ta chyba se stejnými kody u vice rolí. To se již neděje.

Pokud ale stáhnu roli, kterou nemám v konfiguraci zapnutou nic se nezobrazí - to mi vyřešit nejde. Zobrazí se vždy jen role, které mám v konfiguraci. 

Například takto: 
![image](https://github.com/proarc/proarc-client/assets/27210823/4590b0b9-5419-4158-b71c-7866790f0cf7)


Je to tedy takto v pořádku?

**Comment by SykoraLukas** [comment]
Doplnění - opraveno i v proarc-2023

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, přesně tak jsem si to představovala :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Promazala jsem na Inovatice ty testovací Černé věže", už jich bylo hodně.

**Comment by ZdenkaSera** [comment]
V KNAV ve verzi v2.2.0-VISK23/4.1.0-VISK23 ok.
