### ISSUE TITLE
CZIDLO oprávnění

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#427]
V administraci uživatelů udělat oprávnění CZIDLO. Jen uživatel s touto rolí a superAdmin bude smět pouštět noové funkce CZIDLA.

V API (https://github.com/proarc/proarc/issues/1465)

**Comment by ZdenkaSera** [comment]
V klientovi funguje - pokud nemám oprávnění, funkci CZIDLO ani nevidím v nabídce.
