### ISSUE TITLE
Upravy designu na zaklade pripominek z testovani

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#429]
Upravy designu, na zaklade pripominek ze zaslanych dokumentu uvedenych v issue #247 od KNAV, MZK a SVKHK

**Comment by pkudela** [comment]
Zapracovani podobnych pripominek ze vsech 3 dokumentu

- [ ] hlavni navigacni listu zmenit na puvodni primarni modrou
- [ ] podtrzeni tabu sjednotit na primarni barvu
- [ ] zaskrtnuti checkboxu sjednotit na primarni barvu
- [ ] vystavit nekde seznam vsech typu alert boxu pro testovani a pripadne doladeni barevnosti
- [ ] ikony v toolbaru - zkusit zmenit na z cerne na tmave sedivou

**Comment by pkudela** [comment]
K bodu 4, vytvoril jsem novou stranku totest ->  https://proarc-2023.inovatika.dev/totest, kde bude mozne testovat ruzne elementy jako napr. barevnost alert kart, pripadne pak barevnost labelu atd. Pod tim jsou priklady barevnosti, jak to resi pro jednotlive alerty u jinych frameworku, jako napr. bootstrap, material, podle toho se muzeme inspirovat, toto je spise priprava pro schuzku.

**Comment by pkudela** [comment]
@ZdenkaSera , tak je to hotovo, implementovany nektere upravy z dokumentu, ktere jsou vyjmenovane vyse, je to deployovane na https://proarc-2023.inovatika.dev a z rocestniku odstranen link na redesign, to uz neni potreba -> https://proarc.inovatika.dev/. Myslim, ze nemusite nejak komentovat, ty zmeny spise slouzi jako podklad provedenych zmen pro schuzku. Mozna, ze do te doby jeste v tomto issue zapracuju nektere dalsi zmeny, to dam vedet.

**Comment by pkudela** [comment]
@ZdenkaSera toto uz davno probehlo a myslim, ze lze zavrit, ne?

**Comment by ZdenkaSera** [comment]
@pkudela OK, zavírám s tím, že jsme to prošli na schůzce 19.9. a to, co z toho zbývalo/nesedělo je v jiném issue. Díky.
