### ISSUE TITLE
Založení nového objektu stažením metadat z katalogu - příliš složité

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#43]
Příliš složitá cesta ke stažení metadat do objektu. Založím objekt, v “Režim detailu>metadata>načíst metadata z katalogu” načtu metadata a upravím (pokud se vůbec načtou). 
V okně pro vytvoření nového objektu není žádné pole pro vyplnění čísla záznamu, který má být nahrán. Je to chyba, nebo to bude přidáno?

**Comment by luckajirku** [comment]
Radši upřesním: 
1. nechceme založit prázdný formulář a do něj načítat metadata, ale vyhledat záznam a založit objekt. 
**Nenahrávat metadata k objektu, ale vytvářet objekt k metadatům.** Zkrátka tak, jak je to v současném rozhraní.  
2. chybějící možnost hledat podle sysna (resp. čísla z pole 001) je počítám daná jen konfigurací na testovacím serveru, ale bylo by dobré to tam přidat, aby to bylo možné testovat - u nás je třeba hledání podle 001 nejčastější způsob cesty k záznamu.

**Comment by luckajirku** [comment]
Toto issue úplně zapadlo. Je to jedna z věcí, která byla změněna z původního způsobu, který naprosto vyhovoval, na nový způsob, který nesmyslně vyžaduje klikání navíc. Byli bychom rádi, kdyby se vrátila možnost založit objekt stažením metadat z katalogu hned v prvním kroku.

**Comment by luckajirku** [comment]
Můžu tě Honzo @honza-rychtar  poprosit o stručné vysvětlení, proč je to teď takhle? A jestli to tak zůstane, protože to jinak nejde, nebo se to dá předělat na předchozí způsob, který vyhovoval více? Díky.

**Comment by honza-rychtar** [comment]
@albertoh Spoj prosím ty dva kroky.
1. v navbaru vyberu Nový objekt
2. tam budu mít jako první možnost načíst z katalogu
<img width="1281" alt="Snímek obrazovky 2022-02-21 v 9 53 21" src="https://user-images.githubusercontent.com/1178142/154922208-eaee941d-5cb5-44b0-b7e9-1f0c99158442.png">
3. to otevře hledání v katalogu podobně jako při načítání metadat z katalogu u editace
<img width="586" alt="Snímek obrazovky 2022-02-21 v 10 00 54" src="https://user-images.githubusercontent.com/1178142/154922518-89d48ddf-c933-46be-85a0-4e1067e601ee.png">
4. vyhledám objekt v katalogu a kliknu na vytvořit objekt - jen se přejmenuje tlačítko, ale jen v případě, že objekt vytvářím.
<img width="1318" alt="Snímek obrazovky 2022-02-21 v 9 57 10" src="https://user-images.githubusercontent.com/1178142/154922321-e8b977c8-9e7b-40c7-b831-dcd6e20ffee1.png">
5. po vytvoření objektu se skočí do editace


_Měla by být zachována i současná možnost a) vytvoření objektu bez katalogu a b) načtení metadat z katalogu k existujícímu objektu_

**Comment by ZdenkaSera** [comment]
Po komentáři HR bude snaha předělat podle požadavku, je zatím ve vývoji.

**Comment by albertoh** [comment]
Pridano

![image](https://user-images.githubusercontent.com/5946836/172364407-38a12c67-1af9-47cc-8651-cb3931125995.png)

![image](https://user-images.githubusercontent.com/5946836/172364792-b1b2f87a-c971-410f-b111-b90f5bfc0b33.png)

**Comment by luckajirku** [comment]
Super, funguje! 
Jen ta tlačítka by možná byla lepší jinak - ve starém je sice taky "Vytvořit nový objekt", ale tam se tlačítko vztahuje k oběma možnostem - jak založení prázdného objektu, tak založení objektu s metadaty. Jasnější by tady asi bylo "Prázdný objekt" - vzhledem k tomu, že v novém se tím tlačítkem zakládá jen objekt bez metadat.

**Comment by luckajirku** [comment]
Tak ono to nebude tak jednoduché:-). Při zakládání některých nových objektů ve struktuře je to zas trochu matoucí - protože kliknu na Vytvořit prázdný objekt - a vytvoří se mi číslo, které má vyplněná metadata, protože se kopíruje z titulu.

**Comment by ZdenkaSera** [comment]
Nezkoušela jsem zakládat ve struktuře, jak píše @luckajirku, ale založení nového samostatného objektu je super, mnohem jednodušší/přehlednější - a myslím, že se tím zredukuje počet nechtěně založených prázdných objektů s názvem "?". Díky 👍

**Comment by ZdenkaSera** [comment]
Doplnění k testu: jakmile dovolím vytvořit objekt, tj. nechám zobrazit formulář nového objektu, uloží se i bez manuálního uložení tlačítkem. Je úplně jedno, jestli jsem data stáhla z katalogu nebo založila prázdný objekt. Takže s touhle známou chybou zatím budeme dál počítat. @SykoraLukas Je to časem řešitelné?

**Comment by albertoh** [comment]
To neni problem jadra. Tak se choval klient.
Takze, chcete, aby se ulozil az po manualne tlacitkem v editoru? Zmenim to

**Comment by luckajirku** [comment]
Ano, to by bylo podstatně praktičtější. 
Jinak je tu určitá část uživatelů, kteří mají s (ne)ukládáním problém - pro ty je tu ještě tohle issue https://github.com/proarc/proarc-client/issues/33 - pokud se tam dodělá i hláška s varováním, že člověk opouští neuložený formulář, tak by mohli být spokojeni všichni.

**Comment by ZdenkaSera** [comment]
Huráá :-)

**Comment by albertoh** [comment]
Omlouvam se, spechal jsem s odpovedi. Aby to fungovalo spravne, klient potrebuje z jadra funkce pro nadeleni noveho PIDu.
@SykoraLukas pridas to do API?

**Comment by SykoraLukas** [comment]
API připraveno.

@alberto prosím volat:  

`GET http://localhost:8081/proarc/rest/v1/object/createPid`

odpověď je: 

```
{
  "record": {
    "pid": "uuid:b300f999-775d-4a83-9ff6-7049283ed25f",
    "timestamp": 93632382941700
  }
}
```

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Tohle vypadá, že je to těsně před cílovou páskou, takže přidám milestone. Díky :-)

**Comment by albertoh** [comment]
Muzete testovat

**Comment by luckajirku** [comment]
Chci založit prázdný objekt - a roztočí se kolečko...

**Comment by luckajirku** [comment]
**Vytvoření nového prázdného objektu**. Vyskočí tabulka, dám Uložit, zčervenají některá pole, ta vyplním, dám znovu Uložit, a přestože mám teď už vyplněná všechna červeně vysvícená pole, vyskočí hláška, že dokument je nevalidní.

**Vytvoření objektu stažením metadat z katalogu**. Kliknu na Uložit, hodí to chybu (viz níž). Dám Zrušit - zkontroluju objekty v úložišti - a zjistím, že objekt je založený. 

Chyba<html><head><title>Apache Tomcat/7.0.55 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - Bad Request</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Bad Request</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.55</h3></body></html>

**Comment by albertoh** [comment]
Jeste neni hotovo. Pracuju na tom

**Comment by albertoh** [comment]
Pri vytvoreni noveho objektu, nez ulozime trvale do uloziste, objevi se editor metadat. Ten mel by reagovat stejne jako pri normalnim editaci v pravem okne.
Zaroven jsem odstranil moznost vytvorit stranu, proto ze nedava smysl bez ocr a sken. Strany vyvorime pres import

Problem
> Vytvoření nového prázdného objektu. Vyskočí tabulka, dám Uložit, zčervenají některá pole, ta vyplním, dám znovu Uložit, a přestože mám teď už vyplněná všechna červeně vysvícená pole, vyskočí hláška, že dokument je nevalidní.

byl zpusoben tim, ze nezobrazovaly se povinne elementy vnorene v nepovinnych

**Comment by luckajirku** [comment]
Vypadá to dobře, všechno zdá se funguje. Navíc založení/prvotní editace ve vyskakovacím okně (místo přímo) je skvělý nápad - který by nám navíc mohl umožnit jedno vylepšení pro zrychlení práce - založíme další issue:-).

Co se týká té validace a povinných polí, tam už to neřve, ale narážíme zas na trochu jiný problém s dateIssued (https://github.com/proarc/proarc-client/issues/204)

**Comment by albertoh** [comment]
Jeste dodelam to tak, aby rovnou se oteviralo v podobe po validace, tj, budou cervene povinne policka. To by vyresilo i #204 
Take udelam varovani, pri zavreni editaci bez ulozeni

Ale ted trochu strpeni: rozbilo se nam to po posledni zmene ve formaulari. @SykoraLukas to hned opravuje

**Comment by albertoh** [comment]
Uz je to tam

**Comment by ZdenkaSera** [comment]
Při založení nového objektu (NDK monografie, stažením z katalogu KNAV, sys = 002705702) vyskočí chyba. Zkusila jsem totéž v jádře - objekt se uložil pod uuid:89141883-11ec-4891-b819-af32c2097073

![image](https://user-images.githubusercontent.com/79305516/175028594-10431e48-3ff1-4226-bd78-f382b7494007.png)

**Comment by ZdenkaSera** [comment]
Několik jiných monografií jsem bez problémů založila, tak je v tom konkrétním výše nejspíš nějaká datová kombinace, která se chybně zpracovává.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Děkuji, už funkční.

**Comment by nezbedova** [comment]
NDK monografii jsem založila bez problémů. Vyskakovací okno považuji za vylepšení.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
