### ISSUE TITLE
Výmaz organizace z účtu uživatele

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#430]
@pkudela V klientovi v administraci uživatelů mi roletka se seznamem organizací nedovolí (nebo to neumím) vymazat z dat uživatele  přiřazenou organizaci. Opravy jsme zatím řešili v jádře, kde to lze. Prosím, mohl bys to upravit (přidat prázdnou hodnotu ..)?. Děkuji.

**Comment by pkudela** [comment]
@ZdenkaSera hotovo, otestovano, nasazeno na server -> https://proarc-2023.inovatika.dev/

<img width="845" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/1525c431-f5fd-4760-9b4e-1f054260ad1a">

**Comment by ZdenkaSera** [comment]
@pkudela Moc díky, je to ok.
