### ISSUE TITLE
Původní nezpracované skeny

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#431]
Issue se váže k vývoji 2023 - https://github.com/proarc/proarc/issues/1175

Na serverové části je hotovo, zbývá doplnit prezentaci uživateli.

Nový druh exportů, tak aby si to mohli nastavit jen ti, co to chteji pouzivat, ostatních se to týkat nebude.

- archive_extended - Archivace se surovými skeny
- archive_stt_extended - Archivace starých tisků se surovými skeny
- archive_extended_bagit - Archivace se surovými skeny v BAGIT balíčku
- archive_stt_extended_bagit  - Archivace starých tisků se surovými skeny v BAGIT balíčku

Všechny tyto druhy exportů mají možnost použít přepínač mezi volbami (vždy vybrána jen jedna možnost)

- Skeny nejsou k dispozici
- Přidat Informaci
- Bez výběru

Zároveň v případě zaškrtnutí jedné ze dvou horních možností platí povinnost vyplnit textové pole.

Odesílání na api:
Stejně jako už u existujících exportů archive a archive_stt (s případnou podporou bagit).
Nově přidána 2 pole:

- noTifMessage
- addInfoMessage

V případě, že uživatel zaklikne možnost `Skeny nejsou k dipozici` se povinná textová informace posílá v poli `noTifMessage`.
V případě, že uživatel zaklikne možnost `Přidat informaci` se povinná textová informace posílá v poli `addInfoMessage`.
V případě, že není vybrána ani jedna možnost tak se textová informace neposílá.

**Comment by ZdenkaSera** [comment]
@albertoh Sem přidávám prio, Díky.

**Comment by albertoh** [comment]
Je to tam. @SykoraLukas  muzes to otestovat?

**Comment by SykoraLukas** [comment]
Funkční na testu: 
<img width="1918" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/07e76992-5928-420d-b7e8-abf0af1273ed">

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Prosím, je tady zapotřebí přidat tahle nastavení do globals (podle toho, které varianty jsou pro nás relevantní), resp. je tohle jediná změna v globals k tomuhle issue? Děkuji.

archive_extended', // - Archivace se surovĂ˝mi skeny
'archive_stt_extended', // - Archivace starĂ˝ch tiskĹŻ se surovĂ˝mi skeny
'archive_extended_bagit', // - Archivace se surovĂ˝mi skeny v BAGIT balĂ­ÄŤku
'archive_stt_extended_bagit' // - Archivace starĂ˝ch tiskĹŻ se surovĂ˝mi skeny v BAGIT balĂ­ÄŤku

**Comment by albertoh** [comment]
Ano, lze menit v globals

**Comment by kerschfilip** [comment]
Otestováno na verzi 2.3.0/4.2.0 

nefungují mi ta varianta Archivace se surovými skeny v BAGIT balíčku. Vždy se vytvoří bagit archivního balíčku, ve kterém ty nezpracované skeny nejsou. Když spustím nad stejnými objekty archivní export se surovými skeny, tak se tam objeví. @SykoraLukas podíváš se na to, prosím?

**Comment by SykoraLukas** [comment]
Opraveno, u volby archive extended bagit volal klient jen bagit (bez pridani surovych skenu).

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
