### ISSUE TITLE
Opravy urn:nbn - Následovník

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#432]
Klientská podpora pro https://github.com/proarc/proarc/issues/1588

@albertoh mohl bys prosím doplnit novou funkci do branch Visk23?

Volání je!

``` properties
### REGISTER URNNBN - SUCCESSOR
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/createSuccessor
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8


&pid={{uuid}}&resolverId={{resolverId}}
```

Nová funkce do seznamu CZIDLO popsaného v #425. 

Po spuštění funkce se zobrazí stejné dialogové okno, jako v případě nové registrace URN:NBN. Uživatel vybere registrátora a funkci spustí.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Funkce na straně klienta ok.
