### ISSUE TITLE
Svazek vícedílné monografie - chyby ve v. 4.1.0-VISK23-beta/v2.2.0-VISK23 (12.09.2023)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#433]
Svazek vícedílné monografie lze založit plusem přímo pod vícedílnou monografií, ale nelza založit jako samosttaný objekt

![image](https://github.com/proarc/proarc-client/assets/79305516/54bac149-258f-4af4-8856-3909f907c8ec)

**Comment by ZdenkaSera** [comment]
Když zakládám svazek vícedílné monografie pluskem přímo pod VD, neměla by se mi vícedílná monografie nabízet jako možný objekt k založení - VD pod VD není správně

![image](https://github.com/proarc/proarc-client/assets/79305516/484aa404-443a-44d4-96e7-f40b4f1e27a2)

**Comment by ZdenkaSera** [comment]
V importu nemohu nové skeny přiřadit ke svazku vícedílné monografie

![image](https://github.com/proarc/proarc-client/assets/79305516/f92416b8-f225-4230-8494-d0110abc56dd)

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh  Tmuhle jsem dala prioritu, protože v téhle podobě nelze verzi použít. Předem díky!

**Comment by SykoraLukas** [comment]
Vezmu to postupně:

Založení samostatně opravíme.
VD pod VD se řešilo zde https://github.com/proarc/proarc-client/issues/99#issuecomment-836288501 a je tam i zmíněno, jak toto vzniklo. Zároveň je tam řečeno, že se to rozhodne až vyjde nový standard. Takže jak to má být? @nezbedova, @ZdenkaSera , @katerinasirova, @erikamirova a @luckajirku?

Přiřazení stran opravíme.

Label k modelu je uloženen v cs.json a en.json, ty bude potřeba také přepsat při nasazení, ve vydané verzi to je v pořádku.

**Comment by ZdenkaSera** [comment]
V KNAV rozumíme i novému standardu tak, že VD po VD nelze - řešili jsme s @kerschfilip a @SmejkalovaAnna.

**Comment by luckajirku** [comment]
Ty úpravy podle nového standardu se týkaly rozsahu popisu atd., na to se mělo počkat s novým standardem, ale VD pod VD neměla jít založit nikdy, to byl nesmysl od začátku.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Nenašla jsem zatím problém - @SykoraLukas @albertoh děkuji.

**Comment by ZdenkaSera** [comment]
Testováno v KNAV na posledních verzích 4.0.7-DEV/v2.1.1 (24.07.2023)

Založení svazku VD jako samostatný "nový objekt" se zřejmě nedostalo do verze v kompletně opravené podobě. V seznamu modelů si můžu vybrat model.model:ndkMonographUnit, můžu vyhledat data v katalogu, ale pak končím s chybou:

![image](https://github.com/proarc/proarc-client/assets/79305516/c4bdb213-db72-4815-becd-8b270f2610e0)


Děláme něco špatně?

**Comment by ZdenkaSera** [comment]
Importované skeny svazku VD v KNAV nepřiřadím (4.0.7-DEV/v2.1.1 (24.07.2023)):
![image](https://github.com/proarc/proarc-client/assets/79305516/fbcfb0d6-2f74-411d-8bdf-ba70f4cdeabe)

**Comment by SykoraLukas** [comment]
Nad jakou verzi API a Klienta to prosim delas?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Psala jsem výše  - na posledních vydaných, tj. 4.0.7-DEV/v2.1.1 (24.07.2023); ta verze klienta je asi špatně pojmenovaná, tohle číslo ukazuje v aplikaci,

**Comment by SykoraLukas** [comment]
Tohle ale nejsou poslední verze. Poslední je Klient: verze v2.2.0-VISK23 (31.08.2023) a Jádro: verze 4.1.0-VISK23-beta

Prosím o update na aktuální verze.

**Comment by SykoraLukas** [comment]
Na inovatice toto funguje

<img width="1370" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/85733cea-8e0d-4eac-acf9-a311f9588958">

**Comment by ZdenkaSera** [comment]
@SykoraLukas Promiň, dělalm jsem paralelně něco na ostrém PA a opsala verze odtud - na testu máme 4.1.0-VISK23-beta/v2.2.0-VISK23 (12.09.2023). Jinak všechno výše platí

**Comment by ZdenkaSera** [comment]
Ano, na Inovatice to funguje, tam jsem to testovala dříve a issue označila k uzavření. Podle mého to jen nebylo zahrnuto do verze.

**Comment by SykoraLukas** [comment]
@albertoh mohl bys na to kouknout? Mě se zdá, že to ve verzi zahrnuté je. Nějaký další nápad, proč se jim to takto tváří?

**Comment by ZdenkaSera** [comment]
Tohle je v aplikaci, na nižší verzi to nevypadá ... 

![image](https://github.com/proarc/proarc-client/assets/79305516/0b094d54-bf2e-424d-b737-55f8ee8ed8bb)

**Comment by albertoh** [comment]
Jsem to zbuildoval znovu.
https://github.com/proarc/proarc-client/releases/tag/v2.2.1-VISK23

Zkuste to znovu stahnout a nasadit

**Comment by ZdenkaSera** [comment]
@albertoh  Na https://proarc-master.inovatika.dev/ není ve seznamu k založení jako "nový objekt" ani v seznamu modelů k hledání NDK svazek vícedílné monografie. 
(Je k dispozici jen při zakládání nového objektu pluskem.

**Comment by albertoh** [comment]
Pridano

**Comment by ZdenkaSera** [comment]
@albertoh Díky, funguje.

**Comment by ZdenkaSera** [comment]
@albertoh

**Comment by ZdenkaSera** [comment]
@albertoh Tohle jsem zavřela omylem - potvrzené fungování se týkalo masteru. U nás na testu @PetrKotynek nasadil po vydání verzi v2.2.1-VISK23 uvedenou výše, ta se ale nelišila od té předchozí, snažil se o re-build. 
Svazek vícedílné monografie tedy můžeme založit pluskem,  ale ne samostatně a ne vyhledávat, tam je stále nefunkční  "model.model:ndkMonographUnit"

**Comment by albertoh** [comment]
v global.js musi byt mezi modely tohle:

'model:ndkmonographunit',

Pozor na velka a mala pismena

**Comment by PetrKotynek** [comment]
Změněno na proarc-test@proarc-dc jens test PK

**Comment by ZdenkaSera** [comment]
@albertoh Tak za tohle se moc omlouvám - v globals jsme to měli, to jsme kontrolovali, ale vloudilo se tam velké písmeno podle staršího vzoru, jak to psával tvůj předchůdce. Takže ještě lokálně přetestuju funkčnost, ale tohle bude zřejmě ok.
