### ISSUE TITLE
chyba v reindexaci

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#437]
- týká se jak importu, tak úložiště
- přesunu strany na jinou pozici, uložím, a dám reindexovat. Vyhodí to chybu a tváří se, že akce neproběhla. Když ale dám pak Obnovit z lišty nebo refresh v prohlížeči, tak se změny ukážou - indexy se změní.

**Comment by ZdenkaSera** [comment]
Právě jsem paralelně zakládala issue na chybu reindexace v importu, tak jen potvrzuji 

![image](https://github.com/proarc/proarc-client/assets/79305516/81fd846e-c672-4b9a-a6d5-163219e3e056)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prošla jsem issues "chyba" - za KNAV jen tohle je třeba opravit do nejbližšího releasu

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
vypadá to opraveně - import i úložiště

**Comment by ZdenkaSera** [comment]
souhlasím.

@albertoh Alberto, zkusila jsem to i na  masteru a při výběru nadřazenéhio objektu k uložení importovaných skenů se mi tam nenabídl nový model "svazek vícedílné monografie". Na https://proarc-2023.inovatika.dev/ je to ok. Píšu to jen pro jistotu, hodně nám záleží na tom, aby ve verzi klienta, kterou nám teď budeš vydávat, byly všechy věci visku 2023, které jsou k testu, ale hlavně standardy. Moc díky.

**Comment by katerinasirova** [comment]
Za nás též otestováno lokálně, funguje.
