### ISSUE TITLE
Nepovedený label ke svazku VD

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#438]
@pkudela Petře, v editaci je ke svazku vícedílné monografie trošku naddimenzovaný label bez popisku 😉 

![image](https://github.com/proarc/proarc-client/assets/79305516/5a1e58e3-61cd-40cc-9d0c-abcaade76d6f)

Třeba ve srovnání s VD:

![image](https://github.com/proarc/proarc-client/assets/79305516/c38485f5-98b7-4d65-8c15-3fc099a1ef76)

**Comment by ZdenkaSera** [comment]
@pkudela Možná bylo nové issue zbytečné neb Lukáš asi totéž zmiňuje tady https://github.com/proarc/proarc-client/issues/433, ale už to nebudu zavírat.

**Comment by luckajirku** [comment]
Já bych ty nepovedené labely celkově nechala na schůzku k redesignu. Na tomhle místě nedává jejich použití smysl - a na rozdíl od správy dávek (kde můžu sloupec s labely zúžit na únosnou mez nebo ho vypnout) je tady člověk musí mít pořád na očích.

**Comment by ZdenkaSera** [comment]
@luckajirku Ano, už jsem sem přidala štítek redesign.

**Comment by ZdenkaSera** [comment]
Vzhledem k tomu, že je to už opravené, issue zavírám, pro diskusi k redesignu není zapotřebí, @pkudela Díky!

**Comment by luckajirku** [comment]
ok, založím issue na labely obecně

**Comment by ZdenkaSera** [comment]
aha - já jsem to brala jako zbytečné proto, že k labelům byly poznámky v dokumentech z knihoven, ale je to na Vás :-) Díky.
