### ISSUE TITLE
Formulář nového objektu - nefunkční tlačítka

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#439]
Ve formuláři pro založení nového objektu jsou nefunkční (a tedy možná zbytečná ) tlačítka - přepínače zobrazení. Nejsem si jistá, zda v této fázi před uložením je vůbec co zobrazovat pokud jde o xml a admin data. Pokud není, navrhujeme všechna 3 tlačítka odstranit.

Ale pokud je tento formulář sdílený s editací, pak raději probrat potřebu tlačítek na schůzce k redesignu.

![image](https://github.com/proarc/proarc-client/assets/79305516/ea87b4d7-d30b-4e13-aa8a-aed45edc5b3a)

**Comment by ZdenkaSera** [comment]
@pkudela Prosím, můžeš kouknout na tohle issue, abychom to buď řešili jako chybu nebo tlačítka odstranili? Tlačítko redesign tu bylo jen kvůli evidenci před schůzkou 19.9., ale nedošlo na to. Díky.

**Comment by pkudela** [comment]
@ZdenkaSera podivam se na to.

**Comment by pkudela** [comment]
tak to by uz melo byt v poradku, @albertoh to osetril byl rychlejsi :-) je to nasazeno na master

<img width="684" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/fce72ef5-3d2d-4a9e-bd8d-e37a9bbe76df">

**Comment by ZdenkaSera** [comment]
@pkudela @albertoh super díky - zkusila jsem zatím jen na NDK mono, za KNAV ok.
