### ISSUE TITLE
Labely u modelu v úložišti vs původní klikatelný text

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#440]
Označení modelu v úložišti labelem, jak je navržený v redesignu, nám nevyhovuje. Label tam působí rušivě a jeho použití nedává smysl,  Třeba na githubu se pomocí labelů třídí, ale tady to není stav, vlastnost… Chtěli bychom ponechat původní způsob - klikatelný text, kdy právě otevřená úroveň je jen decentně oddělená - vím, kde jsem, a mám klikatelné i nadřazené úrovně (ročník, titul). 
Nemůžu se dopátrat, kdy a kde se řeklo, že tenhle způsob (viz obr.) je nevyhovující a že se to má v rámci redesignu změnit. (Neřeším teď barvu, jestli ta lišta má být šedě nebo primární barvou.)
![rocnikcislo](https://github.com/proarc/proarc-client/assets/6359479/f9eaed72-098e-4a72-8bbb-b7f429e792c2)

**Comment by pkudela** [comment]
@luckajirku ahoj, toto je popsane v issue ze schuzky https://github.com/proarc/proarc-client/issues/447 , je to hotove a nasazene na serveru https://proarc-2023.inovatika.dev/. Prosim zkontroluj a pripadne toto zavri, at se to nedubluje s vyse uvedenym issue.

**Comment by luckajirku** [comment]
za nás OK, zavírám
