### ISSUE TITLE
Rozložení v editaci - bílý rámeček kolem panelů

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#441]
V návrhu redesignu v editaci nám nevyhovuje to bílé orámování oproti původnímu roztažení panelů až do kraje. Jakože je to na hezko, ale na úkor funkčnosti. Tady potřebujeme mít k dispozici co největší plochu pro práci - a ten bílý okraj nahoře a po stranách zbytečně zabírá místo (v hledání a jinde nevadí, ale tady je nepraktický).

![mezery](https://github.com/proarc/proarc-client/assets/6359479/a129d03b-9b7e-40d3-a779-6fec41eb4b31)

vs 

![bezmezer](https://github.com/proarc/proarc-client/assets/6359479/cb2e9bc4-1479-494d-9d92-74e45570aaf9)

**Comment by pkudela** [comment]
Pro schuzku:

![Uploading image.png…]()

**Comment by pkudela** [comment]
+ ochrana zona je sjednocene na vsech strankach aplikace

**Comment by luckajirku** [comment]
takhle už je to lepší, takže zavírám
