### ISSUE TITLE
Šipky pro posun na nadřaz./podřazený/předchozí/následující objekt - (ne)stabilní umístění

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#442]
Šipky pro posun na nadřaz./podřazený/předchozí/následující objekt na liště by měly být pořád na stejném místě. Takhle v periodiku, když se dostanu na úroveň, kde vidím strany (číslo/příloha), přibude na liště tlačítko reindexace - a šipky se v tu chvíli posunou o jednu doprava a už klikám na jinou šipku, než myslím. 
(Ve starém jsou šipky vlevo, a ta tlačítka, jejichž počet se mění, jsou vpravo.)

**Comment by albertoh** [comment]
Seznam ikon zustava, podle moznosti se aktivujou/deaktivujou

**Comment by luckajirku** [comment]
otestováno na NDK periodiku, za nás je to takhle super

**Comment by ZdenkaSera** [comment]
Zkusila jsem na periodiku a vícedílné monografii - líbí se mi to, dávám za nás ok. Později potvrdí ještě zpracovatelé periodik.

**Comment by SmejkalovaAnna** [comment]
Potvrzuji, už je to takhle dobré

**Comment by katerinasirova** [comment]
Za nás vyhovuje, proklikáno na NDK PER a ZD.
