### ISSUE TITLE
Založení objektu - kurzor nepřeskočí do nevalidního pole

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#443]
@albertoh Při zakládání objektu zvolím na obrazovce níže "neukládat" - kurzor pak skočil do nevalidního elementu, to se teď neděje, Zkusila jsem NDK monografii a vícedílnou monografii na https://proarc-2023.inovatika.dev/

![image](https://github.com/proarc/proarc-client/assets/79305516/99640637-effb-4e6f-abf5-9d5465a00690)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Funguje, díky.

**Comment by ZdenkaSera** [comment]
@albertoh Tahle oprava není zahrnuta v poslední verzi, tak aby nezapadla. Díky.

**Comment by ZdenkaSera** [comment]
Odebírám !k uzavření" přidávám "lokální test" - ověřit, že bude v příští verzi.

**Comment by ZdenkaSera** [comment]
@albertoh Tohle je další věc, která ve verzi 2.2.1. nebyla

**Comment by ZdenkaSera** [comment]
@albertoh vytvořila jsme dočasný label "chyba verze - prio". Označím tak issues, kde se vývoj nedostal do buildu, abys je nemusel znovu hledat.

**Comment by ZdenkaSera** [comment]
@albertoh tohle se nám zase vrátilo, na masteru to zase nefunguje, vyskakovací okno je trochu zakleté. zmíněno taky tady https://github.com/proarc/proarc-client/issues/464

**Comment by albertoh** [comment]
Ja to vidim dobre. Kdyz dam vytvorit, dostanu hlasku "nevalidni data" a pokud dam "neukladat" vyskoci.
Asi budu potrebovat presny postup co tam delate, abych to pochopil

**Comment by ZdenkaSera** [comment]
Můj postup - na https://proarc-master.inovatika.dev/

- nový objekt - NDK svazek monografie - vybírám k katalogu KNAV, SYS = 001992473 (titul Zdobení skla)
- protože už je to zdigitalizované, přidává se do metadat další Location s url, kde chybí sigla a shelf locator
- 
![image](https://github.com/proarc/proarc-client/assets/79305516/5670dc26-b00a-492f-942c-9b081aa66caa)

- to nerozporuji, s tím počítáme a mažeme to, ale pokud bych si toho nevšimla, má mi tady při uložení vyskočit chyba. To se nestane, objekt se rovnou založí
- V editaci pak udělám změnu např.  v názvu a dám ji uložit - chyby jsou sice ve formuláři označené červeně, ale nedostanu upozornění, ani kurzor nepřeskočí do prvního pole s chybou
- navíc tady pořád chybí text a/nebo úprava formuláře (upozorňovala jsem v issue https://github.com/proarc/proarc-client/issues/463)
- 
![image](https://github.com/proarc/proarc-client/assets/79305516/7ae5aa6f-9682-4a7f-879d-81101d453678)

**Comment by albertoh** [comment]
Opraveno (snad :)  )

**Comment by ZdenkaSera** [comment]
@albertoh Zdá se, žes zlomil to prokletí 😊😊😊 - díky! Na tom jednom záznamu to na inovatika-master funguje jako dřív, další testy na i jiných modelech později.

**Comment by ZdenkaSera** [comment]
Lokální test v KNAV ok, zatím jsem nenašla protipříklad. Díky.
