### ISSUE TITLE
Hledání - filtrování podle vlastníka

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#444]
Na testu KNAV jsme zkusili kromě filtru na model přidat filtr na vlastníka objektu. Pokud měl vlastník 15 objektů, trval výběr 1-3 minuty. Jinak jsme po 10 minutách vzdali čekání, hledání ale nejde zrušit jinak než výmazem browseru. Testováno v chromu a firefoxu, na Inovatice s minimem objektů je to bez problémů.
Nelze rychlost ovlivnit způsobem dotazování?

**Comment by SykoraLukas** [comment]
Jak probíhal dotaz? Byl vyplněn jak model tak i vlastník? 

Když to zkusíš ve starém klientovi je rozdíl, když to hledáš jako Rozšířený dotaz a nebo jako Pokročilé hledání?

<img width="560" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/537f7d6f-608c-438a-858d-d5dc093a6bcf">

<img width="567" alt="image" src="https://github.com/proarc/proarc-client/assets/27210823/6fd57ad2-babb-4559-b638-7eb7aebf07e1">

**Comment by SykoraLukas** [comment]
Problémem je v tomto případě hledání proti API fedory. Tento problém řeší přechod na Akubru.

**Comment by ZdenkaSera** [comment]
Promiň zpoždění, díky za průzkum. K Tvým dotazům:
- při hledání v klientovi byl vyplněn model a vlastník
- v jádře se mi zdá trošku rychlejší hledání v rámci rozšířeného dotazu, ale oboje je hodně pomalé; vypadá to, že hledání podle vlastníka/uživatele je obecně problém

**Comment by ZdenkaSera** [comment]
zatím zavírám, vyzkoušíme, až se "usadí" Akubra.
