### ISSUE TITLE
Editace - oznámení o uložení metadat

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#445]
Na většině míst v novém klientovi jsou uložené změny potvrzovány hláškou, v editaci ne. V KNAV jsme se shodli, že by se uložení změn metadat disketou také mělo potvrzovat probliknutím hlášky - např. "Uloženo", jako tomu bylo ve starém rozhraní

![image](https://github.com/proarc/proarc-client/assets/79305516/6c430501-1795-4ca8-bdb9-a189d7605313)

Jak to vidíte u Vás -  @luckajirku @katerinasirova @erikamirova ? Děkuji.

**Comment by luckajirku** [comment]
Za nás určitě ano, v novém klientovi by měly být všechny hlášky, co jsou ve starém. Proto jsem zakládala tohle issue https://github.com/proarc/proarc-client/issues/171 a počítala jsem, že k doplnění chybějících hlášek dojde, tak jsme to nějak extra nezkoumali.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
V editaci se zobrazuje info o uložení při editaci ve formuláři i v xml - ok. Díky.
