### ISSUE TITLE
Redesign metadatových formulářů - nový objekt i úložiště

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#446]
Zakládám sběrné issue k úpravě metadatových formulářů tak, jak jsme se domlouvali na schůzce 7.9.

Za MKP doplňuji toto:
- zmenšení mezer a výšky řádků v jednotlivých rámečcích
- vizuálně výrazněji oddělené rámečky metadatových celků - TitleInfo, Name, OriginInfo, Location atd. 
- vizuální označení povinných polí

Odkazy na související issue: #240, #307

**Comment by luckajirku** [comment]
Nasdílím dokument, který jsme si k tomu u nás udělali - https://docs.google.com/document/d/1cWTrUyX81OZcby1eRe4iVNwk5p4tldzUTBZjM60ZrPs/edit?usp=sharing
Podívejte se, komentujte... My bychom byli pro, kdyby se to neřešilo jen rámečky (kterých je tam prostě moc), ale i tím podbarvením, protože to by přehlednosti fakt dost pomohlo.

**Comment by luckajirku** [comment]
@ZdenkaSera počkej počkej, my nechceme barvičky, jen 50 odstínů šedi:-). Aby ty formuláře byly přehlednější, ale ladily s jakoukoli barvou klienta.

**Comment by ZdenkaSera** [comment]
@luckajirku Aha, tak to jsem se unáhlila :-), Anička @SmejkalovaAnna by ráda opravdu barvičky :-) tak uvidíme, třeba se ukáže, že se vám budou líbit nebo naopak budou odstíny šedi dostatečně odlišitelné a budou se líbit jí ;-)

**Comment by katerinasirova** [comment]
Na schůzce k redesignu formulářů 14.3. dohodnuty hlavní úpravy - řešeno v issue #514. Zavřít souběžně s tímto issue.
