### ISSUE TITLE
Redesign - poznamky ze schuzky

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#447]

**Comment by pkudela** [comment]
- [ ] ochrana zona - ok - #441 
- [ ] label predelat - tucne odstranit a naopak potlacit sedivou barvou
- [ ] label v procesech - po kliknuti filtrovat
- [ ] sprava procesu - v navigaci ok, v breadcrumbs opravit a sjednotit

**Comment by pkudela** [comment]
@albertoh posledni bod, prosim o implementaci, sloupce vcetne prekladu jsou v html komponente pripravene, je to commitnute.

**Comment by luckajirku** [comment]
tohle: _v editoru pokud oznacim nejake polozky v tabulce a zmacku shift, tak se tabulka ohranici_ je odškrtnuté, ale opraveně to nevypadá

**Comment by pkudela** [comment]
@luckajirku mam rozdelane spostu prace, ktere jeste neni na serveru, to ze je to odsrktnute je ted primarne informace pro me, az to dam k testovani a bude to nasazene, tak to bude informace i pro vas :-)

**Comment by pkudela** [comment]
Btw, je zde posledni bod, ten dodelam zitra, nasadim na server a dam k testovani jako celek.

**Comment by albertoh** [comment]
Je to tam, ale preklady nesedi

**Comment by pkudela** [comment]
@albertoh, preklady hotove, prosim podivej se jeste na toto ve sprave procesu v souvislosti s nastavenim sloupcu:

- ve sprave procesu se nezapamatuje zmena sirky sloupcu ani na defaultni strance ani v seznamu vsech procesu
- v nastaveni, kdyz udelas reload, tak zmizi checkboxy v poslednim slouci Správa procesů (fronta načítání) viz. screenshot
- v nastaveni ve slouci Správa procesů by nemela byt polozka "Akce",  tam jsou a budou dalsi ikony pro nejakou akci

<img width="355" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/2e5aaeb7-7f7e-4e0f-a51e-a6c11dbb4a4e">

**Comment by pkudela** [comment]
@ZdenkaSera , @luckajirku , @katerinasirova , @SmejkalovaAnna, @erikamirova + dalsi. Toto issue, ktere vzniklo na minule schuzce je kompet hotove, nasazene na serveru do master -> https://proarc-master.inovatika.dev/
Nakonec jsem zapracoval i bod "v editoru - zkusit vyresit schovavani ikon pod 3 tecky v zavislosti na sirce panelu
" - toto jsem na schuzce vylozene nesllibil, protoze to neni uplne jednoduche. Nyni je to pro testovani pouze v repozitari pouze v hornim panelu viz. screenshot nize, pockam na vasi reakci a pokud vam to takto bude vyhovovat, zapracuju i do ostatnich panelu a do importu. Pro tuto funkcionalitu jsem zalozil separatni issue, protoze je tam vice otazek -> #456 

<img width="502" alt="image" src="https://github.com/proarc/proarc-client/assets/16591052/8868d90a-cf06-4196-a278-5b01400c5d22">

**Comment by pkudela** [comment]
Toto si myslim muzu zavrit.
