### ISSUE TITLE
Správa procesů - proklikávací uuid u exportů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#448]
Ve správě procesů by mělo být uuid objektu, na kterém byl proces spuštěn, proklikávací
Domluva na schůzce 19.9.: proklikávání stačí jen u exportů,  proklikne na daný objekt do úložiště (hledání)

**Comment by albertoh** [comment]
Hotovo

**Comment by ZdenkaSera** [comment]
@albertoh proklikávání je super 👍
