### ISSUE TITLE
vyhledávání ve správě procesů - enter X obnovit

### ISSUE THREAD

**Issue by erikamirova** [proarc/proarc-client#450]
Když zadám stav _vše_, pak vložím uuid a dám enter, tak mi stav přeskočí na _načteno_. Musím tedy vyhledávat přes tlačítko obnovit , enter nefunguje správně.

<img width="1639" alt="image" src="https://github.com/proarc/proarc-client/assets/37616300/58ae1475-39b0-47e9-83c6-bb032d74babe">

ENTER
<img width="1634" alt="image" src="https://github.com/proarc/proarc-client/assets/37616300/049c228f-8969-43e9-87a8-a54b14a60c26">

OBNOVIT
<img width="1641" alt="image" src="https://github.com/proarc/proarc-client/assets/37616300/f6b8b3d5-f08a-4627-a35d-70123e34a6f4">

**Comment by albertoh** [comment]
Opraveno

**Comment by erikamirova** [comment]
@albertoh Aha a je to nasazeno na testovacím prostředí? Já jsem to zkoušela tady a nefunguje to. https://proarc-akubra.inovatika.dev/login

**Comment by albertoh** [comment]
Oprava uz je i tam

**Comment by pkudela** [comment]
@ZdenkaSera pokud to funguje, muzeme zavrit?

**Comment by ZdenkaSera** [comment]
@pkudela Otestovala jsem a za mne ok - enter, obnovit a filtrovat se chová stejně při zadání kritéria (nejen uuid) 👍
 Ale počkala bych se zavíráním, až to otestuje @erikamirova , která to zadávala. Díky.

**Comment by ZdenkaSera** [comment]
Nenašla jsem správné issue, tak doplňuji sem - filtrovat podle "Stavu" už lze i kliknutím na label, vrátit se zpátky buď šipkou prohlížeče nebo ručním výběrem jiného stavu ze seznamu. Hezký.

**Comment by pkudela** [comment]
@ZdenkaSera to klikani na labely + ruseni filtru krizkem je z issue z posledni schuzky #447 , uz zbyva posledni bod a dam k testovani jako celek i kdyz vetsina zmen je uz nasazena, asi zitra.

**Comment by erikamirova** [comment]
už to funguje, díky :)
