### ISSUE TITLE
Posouvání šipkami v tabulce

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#451]
V zobrazení “Tabulka” - jak v úložišti, tak v importu, v poslední verzi došlo k nějakým změnám v posouvání šipkami na klávesnici. 
Klikám  dolů - a místo aby se tabulka samotná posunula až ve chvíli, kdy dojedu na poslední v panelu viditelný sken, posouvají se mi řádky nahoru při každém kliknutí. 
A při hodně rychlém klikání (které se používá při kontrolách, ne že bychom si tady jen tak z nudy soutěžili, kdo to dovede rychleji) se snadno docílí toho, že ten vybraný řádek se dostane úplně mimo tu viditelnou oblast. 
Další věc je pak když člověk klikne na šipku doleva, tak jede po řádcích nahoru. A když klikne na šipku doprava, tak se posouvá dolů po řádcích a zároveň ještě to spodní šoupátko se posouvá doprava.

**Comment by albertoh** [comment]
Hm. Takove chovani uz tam je asi dlouho.
Zmenil jsem to na masteru https://proarc-master.inovatika.dev/repository/uuid:d32a1d5f-dfaa-41f3-8ed9-efbed12830a2

Ma se to tak chovat?

**Comment by luckajirku** [comment]
jj, tohle je ono, takhle se to má chovat
