### ISSUE TITLE
Import - (ne)předvybrané zařízení

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#452]
Ve starém bylo možné mít v importu - zařízení jako default prázdné zařízení ("vybrat"). V novém klientovi to nelze a vždy je některý skener předvybraný. Tady bychom se potřebovali vrátit k tomu starému způsobu - aby člověk, pokud je zařízení víc než jedno, musel vždycky konkrétní skener cíleně zvolit.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
funkční to je, ale vypadá to divně. To Zařízení by mělo být tím malým písmem nahoře (jako Profil, Priorita) a přednastavená volba Vybrat že by byla rovnou vidět (nebo prázdný řádek, tak jak to vypadá ve chvíli, kdy na Vybrat kliknu).
Ono je to tímhle způsobem dělané i jinde, ale tam, kde jsou všechny další hodnoty funkční, to smysl dejme tomu dává, ale tady to vypadá opravdu divně.

**Comment by albertoh** [comment]
Je to tam.
