### ISSUE TITLE
Klient si nepamatuje poslední vyhledávání

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#454]
Pokud se z editace objektu vrátíme zpět na obrazovku hledání, klient by si měl pamatovat horní úroveň editovaného objektu. To se teď děje jen v případě, že vracím jen o jednu úroveň a vrátím se šipkou prohlížeče.

Příklad: zpracuji sadu článků periodika, pak se chci vrátit do úložiště na úroveň titulu a exportovat.

Na schůzce 19.9. jsme se shodli, že potřebujeme funkci, která tento návrat umožní, ale stávající funkce kliknutí na "domeček" nebo na logo ProArc by měly zůstat zachovány.

**Comment by ZdenkaSera** [comment]
@albertoh @pkudela Tohle má určitě nižší prioritu než chyby a issues projektů. Prosíme ale o zvážení, jak na to (nové tlačítko na liště?) a jak náročné to je, Děkujeme.

**Comment by albertoh** [comment]
Jak jsme se domluvili na schuzce, pridal jsem polozku do uloziste

![image](https://github.com/proarc/proarc-client/assets/5946836/719bb8d4-b73d-48a8-ae16-5484b4b9a7ab)

**Comment by ZdenkaSera** [comment]
@albertoh Top byl fofr :-) Koukal jsem se na to na inovatice-masteru - objevuje se to i na nejnižší úrovni (strany, nezkoušela jsem e-borny) - tam by to nemělo být k dispozici. Pokud tam zkusím např. přidělit urn:nbn, dostanu sicechybu, ale lepší by bylo to tam vůbec nemít. Zkusíš?

**Comment by albertoh** [comment]
To ale se objevuje i na obrazovce hledat...

**Comment by ZdenkaSera** [comment]
To máš pravdu, nechám to tedy na rutinních uživatelích. V obrazovce Hledat to totiž vnímám jinak - jako přehlednější. Ale asi jde jen o zvyk.  Díky..

**Comment by ZdenkaSera** [comment]
V KNAV otestováno, odsouhlaseno

**Comment by ZdenkaSera** [comment]
Zavírám, pokud se v provozu objeví problém, založíme nové issue.
