### ISSUE TITLE
V editoru zkusit vyresit schovavani ikon pod 3 tecky v zavislosti na sirce panelu

### ISSUE THREAD

**Issue by pkudela** [proarc/proarc-client#456]
Nyni je to pro testovani pouze v repozitari pouze v hornim panelu viz. screenshot nize, pockam na vasi reakci a pokud vam to takto bude vyhovovat, zapracuju i do ostatnich panelu a do importu. Otazka je chovani v ostatnich panelech napr. formular, xml atd. - budou se schovavat pouze ikony a text + radio buttony zustanou? Dle meho ano, do polozky "vice" by se mely schovat pouze buttony, ktere delaji nejakou akci. Dalsi vec je, ze ve 2 zminenych panelech formular a xml, jsou ikony vpravo a vlevo, ted je otazka jak se zachovat - muj navrh je, ze se 3 tecky objevi vpravo az kdyz se panel zmensi na uroven kdy se zacnou ikony zalamovat a zacnou se schovavat prvni ty ikony, ktere jsou vpravo a pak teprve ty ktere jsou vlevo. Prosim o rekaci.

![image](https://github.com/proarc/proarc-client/assets/16591052/e7ae2ec2-5752-46a8-b1ad-89ab52fe2d37)

**Comment by luckajirku** [comment]
za nás tohle ne - jako první se teď schovají šipky, které ale člověk potřebuje mít pořád k dispozici, zatímco ty jednorázové akce tam zůstávají.

**Comment by pkudela** [comment]
@luckajirku to jsem ostatne ocekaval, definujte tedy poradi schovavani pro repozitar a import pro kazdy panel, podle toho to pak upravim, at to nedelam na nekolikrat Jinak co se tyce sipek, tak pokud se schovavat budou, at jako posledni, nebo jinak, tak jen jako celek, kdyby se schovavala jedna sipka po druhe, tak by to dle meho bylo zmatecne. Budu se tedy tesit na seznam, ktery by mel vypdat takto:

Repozitar (typ panelu - nejlepe se screenshotem)
1. Validovat
2. Ulozit
3. ...
4. ...
5. Sipky atd.

Do doby nez obdrzim seznam s tim hybat nebudu.

**Comment by pkudela** [comment]
No radky dva byt mohou jak to bylo pred tim, ja toto reseni nabidnul na posledni schuce jako mozne, protoze vas to stvalo a vy jste to prijali kladnou odezvou, tak doufam, ze jsem to nedelal zbytecne.

**Comment by luckajirku** [comment]
Na schůzce jsi navrhnul, že by ses nad tím zamyslel, jestli by to nějak šlo udělat, ale nějaké přesné zadání nebylo. Tohle je pro praktické používání horší varianta než ta původní. Nemá smysl to uspěchat a rychle vymýšlet, co schovat (a je otázka, jak moc by to mátlo uživatele, kdyby mizela tlačítka ne popořadě) - nechala bych to chvíli k diskusi a jen někde bokem na testování, ale do verze, která půjde ven, bych to nedávala.

**Comment by luckajirku** [comment]
za nás je to jasné - rovnat ikony do dvou řádků
Ono co by se mělo schovávat a v jakém pořadí, se bude domlouvat těžko, protože ty potřeby se liší jak podle toho, co tam člověk dělá (popis vs kontroly), tak i podle knihovny (např. potřeba mít tam ikonu pro převod stran). 
Když jsme o tom tak přemýšleli, tak co by asi mohlo mizet (nebo zmizet úplně, nezávisle na 3 tečkách) jsou **ikony tabulka a náhledy**. Které zobrazení (z těchhle dvou) budu mít v tom panelu, to si zvolím v Rozložení - a když chci změnu, můžu jít tam. Nebo to někdo používá i na rychlé přepnutí? Tím bychom hezky ušetřili místo... Co na to ostatní knihovny?

**Comment by pkudela** [comment]
Takze dal jsem nazpatek puvodni chovani do masteru a pokud se budou chtit ostatni nyjadrit, tak k testovani je to na [proarc-test.inovatika.dev](https://proarc-test.inovatika.dev/), kam se dostanete i z rozcestniku.

**Comment by katerinasirova** [comment]
Řešení je pěkné, ale co by se případně schovávalo za ikony se obávám, že se neshodneme, jak říká Lucka. Zrovna šipky, které jsou schované, asi většina knihoven používá...
Asi až bude chvíli čas, tak zkusím otestovat na všech typech dokumentů, jestli bychom se vlastně vůbec shodli i v rámci jedné instituce. 
Za nás se klidně schovat ikona tabulky a náhledy může, na rychlé přepnutí ji nepoužíváme.

**Comment by pkudela** [comment]
@katerinasirova to ale mohlo byt zrejme hned na zacatku kdyz jsem vam tuto funkcionalitu nabizel, nemusel jsem s tim ztracet zbytecne cas, cili vidim to tak, ze tuto funkcionalitu implementovat nebudeme a issue zavreme at nam to tu zbytecne nevisi a netravime cas zbytecnou diskusi, @ZdenkaSera souhlasis?

**Comment by ZdenkaSera** [comment]
@pkudela Děkuji za pokus a @luckajirku a @katerinasirova za korentáře a test.
Souhlasím - dávám k tomu štítek "odloženo", abychom to případně snáz našli i v uzavřených issues a zavírám

**Comment by pkudela** [comment]
@ZdenkaSera diky :-)
