### ISSUE TITLE
Pohyb šipkami v řádkovém zobrazení vs pohyb ve formuláři - čísla pod ročníkem

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#457]
v té poslední verzi ze 4.10. nejde v řádkovém zobrazení používat šipky z klávesnice a posouvat se po řádcích - jakmile kliknu šipkou, kurzor skočí do formuláře.

**Comment by luckajirku** [comment]
týká se čísel periodika pod ročníkem - na úrovni titulu se po ročnících normálně posouvat dá.

**Comment by albertoh** [comment]
Problem je v tom, ze pro cisla mame povinne pole v metadatech, a kursor preskoci na prvni povinne, a tim se ztraci focus z te tabulky

**Comment by luckajirku** [comment]
vypadá to opraveně, za nás OK
