### ISSUE TITLE
Rozdíl v aktivaci šipek - panel tabulka / lišta

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#458]
Vysvícení šipek přímo v panelu tabulky a na liště se liší - ale jen někdy. Co jsme tak zkoušeli, tak když pod tím objektem jsou další objekty OK, tak se to shoduje, ale když jsou další (pod, vedle...) objekty prázdné, tak v panelu se vysvicují šipky správně, ale na liště ne. 
![sipkyvpravo](https://github.com/proarc/proarc-client/assets/6359479/4f805971-5216-46a1-8049-0c2208bcd084)

**Comment by ZdenkaSera** [comment]
@pkudela Sem přidávám štítek redesign -díky.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
OK, dávám k zavření.
