### ISSUE TITLE
WorkFlow - převedení do klienta

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#459]
V současné době je zakládání záměrů a celková správa workflow možná jen v jádře. V rámci projektu 2023 by se mělo prostředí z jádra víceméně 1:1 převést do klienta (tj. bez vylepšování funkčnosti i designu).

Dočasné přepínání mezi jádrem (zakládání záměrů a objektů) a klientem (zpracování objektů) je řešeno v issue https://github.com/proarc/proarc/issues/1612

Nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#nov%C3%BD-klient):

## (4.1.1) Url cesta k novému klientovi
proarc.client.url=https://proarc-master.inovatika.dev/

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, kdy bude verze k nahlédnutí? Díky.

**Comment by albertoh** [comment]
Zkusim co nejdrive :)

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, jak jsme na tom s tímhle bodem - bude v nejbližším releasu? Pokud by tenhle bod měl release zdržet, necháme na příští, ale prosím o návrh termínu, kdy by to pak mohlo být k testu. Moc díky.

**Comment by albertoh** [comment]
Visi na @pkudela ... Petre, podivas se?

**Comment by ZdenkaSera** [comment]
@albertoh @pkudela Ahoj, prosím, jak to tady vypadá? Předem díky za info, tety .... :-)

Po nasazení poslední verze na test jsme si uvědomili, že potřebujeme i v záměrech pracovat s novými formuláři, především kvůli vazbě mezi vícedílnou monografií a novým modelem "svazek vícedílné monografie".  Takže přepínání do jádra sice funguje, ale nepokryje část naší činnosti.

**Comment by albertoh** [comment]
Pracuju na tom. U nas na testu dal jsem moznost mit oba odkazy, do stareho a noveho:

![image](https://github.com/proarc/proarc-client/assets/5946836/ba0a1ec8-668f-4cd0-9bf4-4206e61761bb)

**Comment by ZdenkaSera** [comment]
Sem přidávám prioritu - bez nových standardů v záměrech nemůžeme klienta používat na hlavní produkční instanci.

**Comment by albertoh** [comment]
Filtry pridane.
@pkudela  podivej se prosim na to. Css neni tam jeste.
Muzete zacit testovat.

**Comment by pkudela** [comment]
> Filtry pridane. @pkudela podivej se prosim na to. Css neni tam jeste. Muzete zacit testovat.

@albertoh mrknu asi behem zitrka

**Comment by ZdenkaSera** [comment]
@albertoh Díky, kolegyně budou testovat po víkendu. Chtěla jsem na masteru jen vyzkoušet, že lze objekty ukládat, narazila jsem na toto:
- založila jsem nový záměr
- takto jsem upravila údaje v úkolu "skenování"
- 
![image](https://github.com/proarc/proarc-client/assets/79305516/0d81fdc7-c862-4333-91fa-df23c5d56ecc)
- po uložení vyskočilo toto:
![image](https://github.com/proarc/proarc-client/assets/79305516/86e9266d-c80a-439b-a414-e31623ca84f3)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Díky, uložit to už jde, předám kolegyním.

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto, proč je tam toto: 
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/74eab929-5296-4a60-abf3-c2d3e553845b)
 úkoly tam být asi nemusí, stačí tam jen Záměry a Záměry API....

**Comment by albertoh** [comment]
Delam jako ve starem:

![image](https://github.com/proarc/proarc-client/assets/5946836/f95a3a1b-07f6-484f-ac76-3e8ada4f9636)

**Comment by nezbedova** [comment]
@albertoh @SmejkalovaAnna Úkoly jsou v jádru, jedná se o překlopení. Zda jsou potřeba nebo ne, je na diskusi.

**Comment by SmejkalovaAnna** [comment]
@albertoh to tam zbylo z nějaké staré verze, klidně to z nabídky vyhoď, neosvědčilo se to... bylo to tam navíc.

**Comment by SmejkalovaAnna** [comment]
@nezbedova Martino, souhlas?

**Comment by SmejkalovaAnna** [comment]
- [ ] Neotvírá se editační formulář po uložení, jen se to uloží
- [ ] Volba zobrazení sloupců v levé části (všechno, co bylo možné ve starém)
- [ ] Filtrování
- [ ] Možnost založit přez prázdný formulář
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/49f61be7-bed5-42db-875d-a62bdadb962e)

- [ ] Chybí nové modely (např. Svazek vícedílné monografie)
- [ ] Nefunguje vytváření podzáměrů STT (ani NDK, chybí tam ty modely, v nabídce jsou ty staré, ale ani ty nejdou)
- [ ] Po prokliknutí do úkolu nefunguje tlačítko Záměr (resp. návrat do záměru)
- [ ] Upravit všechny úkoly, aby tam bylo, co tam bylo včetně popisků
- [ ] Editace položek v úkolech
- [ ] Nefunguje uložení změny jména v úkolu (ostatní buňky nejde editovat viz výše)
- [ ] Přejmenovat RD Flow na WorkFlow
- [ ] Po vyplnění úkolu např. Skenování, se automaticky nelze vrátit do přehledů záměrů. 
- [ ] Po změně v poli Financováno došlo po zadání Uložit k tomuto:
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/f3bdd9eb-0fa1-4b91-9de9-bae98baa84aa)

- [ ] Nelze editovat bibliografický záznam u vytvořeného záměru
- [ ] Překlady

**Comment by SykoraLukas** [comment]
@SmejkalovaAnna co znamená "Chybí nové modely (např. Svazek vícedílné monografie)"? Modely pro daný profil jsou definované ve workflow.xml. UI jen nabízí data, která jsou v konfiguraci. Nebo je problém ještě jinde?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Po domluvě s @SmejkalovaAnna upřesňuji - v doplnění xml máš nejspíš pravdu :-), to jsme si neuvědomili. Problém je ale stejně s obsahem formulářů, hlavně u vícedílných monografií, kde byly největší změny standardu.
Pokud se nepletu, tak transformační šablona je pořád stejná, takže metadata záměru vícedílné monografie založené v jádře  (a tedy i z něj překlopeného objektu) a metadata vícedílky založené bez záměru rovnou v klientovi budou stejná.
Rozdíl je v tom, že zpracovatel záměru data neuvidí ve formuláři, ale neměl by je kontrolovat ani opravovat v xml.  Pro běžný provoz je to dost nešikovné.

**Comment by SykoraLukas** [comment]
Z pohledu nového klienta by neměl být problém, editovat Mods záměru přímo ve formuláři. Tím by se snad měl vyřešit problém, který zmiňuješ.

**Comment by ZdenkaSera** [comment]
Přesně - tam se budou (předpokládáme a doufáme) volat stejné formuláře se všemi elementy a kontrolami jako v objektu, proto je překlopení pro nás tak důležité.

**Comment by albertoh** [comment]
>  Editace položek v úkolech
> 
>  Nefunguje uložení změny jména v úkolu (ostatní buňky nejde editovat viz výše)

To by melo byt jako driv, nektere polozky nebyly editovalne v starem. 
Mam to zmenit tak, aby vsechno bylo editovatelne?

**Comment by SmejkalovaAnna** [comment]
@nezbedova Martino editovatelné bylo všechno, kromě datumů, ty se propisovaly automaticky a nešly editovat. A kromě Datumu u Skenování dříve, kde se dopisuje ručně. Je to tak? Nebo jsem na něco zapomněla?

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, hodně jsi toho udělal v ostatních issues k workflow (díky!) - je to už na masteru k přetestování celého procesu? Děkuji.

**Comment by albertoh** [comment]
Vsechno co jsem oznacil "k testovani" je na masteru. Pokud mi neuniklo neco, melo by tam byt vsechno

**Comment by ZdenkaSera** [comment]
Dobře, děkujeme.

**Comment by ZdenkaSera** [comment]
Zde zavírám, zbytek řešíme v individuálních issues.
