### ISSUE TITLE
Chyby nalezené při testu rychlosti klienta

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#464]
@albertoh To, co jsme našli jako problém v KNAV, přetestujeme na https://proarc-rychlost.inovatika.dev/ a napíšeme do tohoto issue.

**Comment by ZdenkaSera** [comment]
Import: nechali jsme načíst dva adresáře se skeny, takže naskočil dialog "Hromadné Načítání". - fce „Otevřít správu importních procesů“ nefunguje, nepřepne do správného okna

![image](https://github.com/proarc/proarc-client/assets/79305516/2841d8b0-1a18-4198-b34f-2fc842205c02)

**Comment by ZdenkaSera** [comment]
- [ ] Při zakládání nového objektu se v "plovoucím" formuláři ani v editaci nekontrolují chyby (např. prazdný shelf locator)

**Comment by ZdenkaSera** [comment]
- [ ] Jakmile v editaci poprvé zasáhnu do formuláře, aktivuje se tlačítko pro uložení změny - to je správně, ale toto tlačítko pak zůstává aktivní trvale i po uložení dalších změn, až dokud nepoužiju funkci refresh.

**Comment by kerschfilip** [comment]
Přidávám další problémy:

- [ ] Při scrolování formulářem se někdy část nestačí načíst a už se prostě nezobrazí. Typicky pak chybí buď začátek nebo konec formuláře. Nepomohlo ani čekat, jen přepnout formulář na XML a zase zpět. Stávalo se to bohužel dost často, přikládám video: https://streamable.com/n7ko02 
- [ ] u ečlánků někdy chybí vyplněné hodnoty přepínače recenzovaný/nerecenzovaný, postup: 
  - zakliknu u nějakého článku, že je recenzovaný
  - dám uložit
  - kliknu v tabulce na jiný článek
  - vrátím se zpět na původní článek
  - přepínač není vyplněný, v XML ale informace o recenzování je
- [ ] po uložení nezůstane v tabulce označený ečlánek, který mám otevřený

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, díky za opravy, pro přehlednost jsem připsala výsledky testu pod jednotlivé body. Zatím jsem našla jen nefunkční kontroly ve vyskakovacím okně při zakládání objektu (test jen na NDK monografii, vícedílce a svazku vícedílky).. Prosím, koikneš na to ještě? Díky.

**Comment by albertoh** [comment]
Chapu to tak, ze chces aby rovnou pri otevreni formulare problehla validace? Ted se to deje pri ulozeni/vytvoreni, a nejen tady, ale i na masteru

**Comment by ZdenkaSera** [comment]
Ano, ono to tak bylo, tady je ukázka z naší produktivní instance:
V nově zakládaném objektu zvolím "vytvořit" nebo "vytvořit a přejít do objektu"  Vyskočí mi dialog:

![image](https://github.com/proarc/proarc-client/assets/79305516/24efdc8f-b3b9-4899-96ab-8f548126d89a)

Zvolím "neukládat" a kurzor mi skočí do elementu s chybou

![image](https://github.com/proarc/proarc-client/assets/79305516/bc837032-bc4c-4a1a-802e-179b0692d532)

**Comment by ZdenkaSera** [comment]
@albertoh Promiň - k textu výše - ne při otevření, ale samozřejmě při uložení, jak píšeš. Ale při mých testech to tak nefungovalo, zkusím tedy znovu.

**Comment by ZdenkaSera** [comment]
@albertoh Zkusila jsem i na masteru - ten dialog nevyskakuje.

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, teď jsme znovu zkuisila to dialogové okno (popis viz výše) - to opravdu pořád nevyskakuje.

**Comment by albertoh** [comment]
Melo by to uz skakat

**Comment by ZdenkaSera** [comment]
@albertoh Máš pravdu, okno už vyskakuje - otestovala jsem to na chybě, kterou jsem cíleně vytvořila. Nevyskakuje ale v některých situacích, které se dříve taky hlásily jako chyba. To musíme doladit při přetestování nových standardů. Díky.

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, @kerschfilip potvrdil, že i ty chyby, které zadal on, se zdají ok. Díkiy,

@albertoh @SykoraLukas Prosím, vidíte tedy jako možné sloučit to s masterem a dát nám čas na jeho přetestování, než vydáte verzi k nasazení na lokální instanci?

**Comment by albertoh** [comment]
Slouceno.
Ted master ma zmeny, ktere jsou i na "rychlost"
Otestujte, a vidame verzi

**Comment by ZdenkaSera** [comment]
Super moc díky  👍 o novou verzi požádáme pak mailem. Označím během dneška jako prio ještě některá issues, kde je zapotřebí vývoj, aby je bylo možné lokálně otestovat .

**Comment by ZdenkaSera** [comment]
@albertoh Testuji na **https://proarc-master.inovatika.dev/**
Při založení objektu (zde svazek vícedílné monogr.) jsou sice ve formuláři červeně označené chyby, ale ani v zakládacím okně ani při uložení změn v editaci systém na chyby neupozorní.

**Comment by albertoh** [comment]
Zmenil jsem scroll tak, aby bylo jasne kolik zbyva do konce formulare. 
Scroll neblika (skoro)
Tlacitja end a home fungujou

**Comment by ZdenkaSera** [comment]
Ad scroll - "drhnutí:" formuláře při scrolování kolečkem myši v mém testu super, je to skoro plynulé (test na masteru, zatím jen na delší monografii). Indikace pozice ve formuláři pomocí scrollu je ok, díky.
Home/end - funguje, ale napřed se musí formulářem pohnout pomocí scrollu. Když se formulář jen otevře a člověk stojí např. na prvním elementu, end neudělá nic. Jen poznámka, finální test raději rutinní uživatelé.

**Comment by ZdenkaSera** [comment]
Zatím zavírám, už je to nepřehledné. Pokud narazíme na některou z chyb znovu, založíme na ni samostatné issue
