### ISSUE TITLE
Preferované místo uložení

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#465]
@SykoraLukas @albertoh V uživatelském nastavení klienta máme "Místa uložení"  a z nich si lze vybrat preferované hodnoty. Používá se to někde (ať už ve starém nebo novém klientovi)?
V issues https://github.com/proarc/proarc-client/issues/313 a https://github.com/proarc/proarc/issues/1551 jsme řešili, že sigla se nemá vybírat z roletky, ale jen kontrolovat na hodnoty v konfiguraci jádra, takže tady to nastavení mít vliv nebude.
Děkuji.

![image](https://github.com/proarc/proarc-client/assets/79305516/f0a9bea7-7a02-4bf8-8748-02ed38aee8bd)

**Comment by SykoraLukas** [comment]
To je asi pozůstatek. Myslím, že se to nikde nepoužívá. @albertoh mohl bys to prosím prověřit a případně to odstranit?

Souhlas @ZdenkaSera?

**Comment by ZdenkaSera** [comment]
@luckajirku Nechala bych to zrušit jako nefunkční a matoucí, ale pro jistotu: nevybavuješ si, jaký s tím byl záměr? Podle Tvého - potřebujeme to? Díky.

**Comment by luckajirku** [comment]
@ZdenkaSera tohle se zavedlo kvůli tomu výběru z rolátka, aby člověk nemusel aspoň pro ty svoje sigly rolovat moc daleko. Ale s návratem k původní verzi - zapisovacímu poli - je to tam k ničemu. Jak píše Lukáš, "pozůstatek".
Za nás určitě z nastavení vyhodit.

**Comment by ZdenkaSera** [comment]
@luckajirku 👍 Díky

@SykoraLukas @albertoh Díky za průzkum a prosím tedy o zrušení. Dávám sem label "chyba", aby to nezapadlo.

**Comment by albertoh** [comment]
Uz neni :)

**Comment by ZdenkaSera** [comment]
@albertoh Není, díky 😊
