### ISSUE TITLE
Konflikt načítání

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#466]
Na API je již [vyřešeno](https://github.com/proarc/proarc/issues/1330), je jen potřeba doplnit chování do klienta.

Ve správě dávek se může zobrazit nový stav `LOADING_CONFLICT`.

V reakci na něj je potřeba nová funkce: `Vyřešit konflikt`. Funkce zobrazí nové dialogové okno s přepínačem. Jednou z možností je `Použít původní Metadata` a druhou možností `Použít nová Metadata`.

Poté poslat na API jako v případě Znovu načtení dávky jen se doplní parametr `useOriginalMetadata=true` nebo `useNewMetadata=true`.

Příklad zde:
```properties
PUT {{proarcLocalHostUrl}}/rest/v2/import/batch
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&state=LOADING_CONFLICT&profile=profile.ndk_periodical_kramerius_import&id=86&useNewMetadata=true
```

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
Mám proces ve stavu "konflikt načítání". Tlačítko "Vyřešit konflikt" vyvolá dialog - viz níže. Červený vysvětlující text je v obráceném pořadí, než volby na tlačítkách pod ním - možná by tu stačil jen  např. text " Zvolte způsob pokračování" (nekonzultovala jsem s uživateli).

Když zvolím "zrušit", čekám, že se nebude nic dít, jen se zavře tento dialog - import se ale spustí.

![image](https://github.com/proarc/proarc-client/assets/79305516/19d271a1-cc01-4c89-bae7-5e90fd50afd4)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, přidám sem prio kvůli opravě té chyby -  to je jedna z těch, které prosíme opravit před vydáním nové verze s opravami rychlosti formulářů. Děkuji.

**Comment by albertoh** [comment]
To je take opraveno

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV - volba "zrušit" nespouští proces, text opraven - díky. 
Label "konfigurace" zde odebírám, na klientovi není zapotřebí nic nastavovat.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
