### ISSUE TITLE
Chyba při spuštění dvou importních dávek

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#468]
Testovala jsem toto:
- V importní frontě byly dvě dávky, jednu jsem zastavila
- Druhá se tedy automaticky spustila
- Znovu jsem spustila zastavenou dávku, ta "shodila" import té druhé s chybou a bylo zapotřebí ji následně znovu kompletně načíst

Nejsem si jistá, jestli je načítání striktně sekvenční - pokud ano, je výše popsané očekávané chování. 
Bylo by možné při spouštění zastavené dávky zkontrolovat, zda neběží jiný import a superusera varovat?

Zatím jen dotaz, prio nízké. Děkuji.

**Comment by SykoraLukas** [comment]
Jak se projevilo, že byla načítající dávka "shozena"? Obovená dávka by se měla zařadit za probíhající, tj. nic by nemělo spadnout.

**Comment by ZdenkaSera** [comment]
Zkoušela jsem to znovu nasimulovat na Inovatice i v KNAV a chybu načítání už jsem nedostala. K obrázku níže: Na masteru se "krátká" spustila po zastavení "Krasopisu", po jeho opětovném spuštění se zastavila, postavila do fronty a sama se znovu nespustila. V KNAV se načetly obě dávky. Issue tedy zatím zavírám. Díky


![image](https://github.com/proarc/proarc-client/assets/79305516/88cacd20-d1bc-401b-8de9-8a9369485d02)
