### ISSUE TITLE
RDFlow - ve verzi 2.2.0 chybí funkce přepnutí do záměrů v jádře

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#469]
Na Inovatice-masteru je dostupná fce pro otevření záměrů v jádře, do verze klienta 4.1.0 se nedostala.

![image](https://github.com/proarc/proarc-client/assets/79305516/0d43859b-91df-4763-8825-8be08d2cbe0a)

**Comment by albertoh** [comment]
Nahradil jsem zip v release 2.2.0

**Comment by ZdenkaSera** [comment]
@albertoh Díky za pokus, něco se ale nepodařilo  - @PetrKotynek nám verzi nasadil, ale funkce se neobjevila.

**Comment by PetrKotynek** [comment]
cat globals.js |grep showWorkflow
   // showWorkflow: true,

PK

**Comment by PetrKotynek** [comment]
cat globals.js |grep showWorkflow
   showWorkflow: true,

Další pokus, mělo by být odkomentováno a funkční. PK

**Comment by ZdenkaSera** [comment]
@albertoh @PetrKotynek Děkuji, už to funguje.
