### ISSUE TITLE
eČlánek - nefunguje vytvoření objektu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#470]
Na schůzce 7.11 bylo zmíněno, že nelze vytvořit nový objekt eČlánku.

**Comment by albertoh** [comment]
Muzete podrobnej popsat problem? Me to jde...

**Comment by kerschfilip** [comment]
@albertoh když jsem v NDK eČísle a kliknu na `+` a chci vytvořit NDK eČlánek, tak se mi ukáže v tom vyskakovacím okně prázdný formulář, tady chci kliknout na `Vytvořit a přejít do objektu`, ale nic se nestane. Do konzole se vyhodí chyba: 
![image](https://github.com/proarc/proarc-client/assets/57805328/e594332d-9eb7-4cc5-a80c-22dea964febe)

Stejný problém je když chci založit eČlánek pod NDK Číslem a nebo Svazek eMonografie

**Comment by albertoh** [comment]
Opraveno

**Comment by albertoh** [comment]
https://github.com/proarc/proarc-client/releases/tag/v2.2.0
Zip je novy

**Comment by kerschfilip** [comment]
v aktuální verzi OK, díky!
