### ISSUE TITLE
Tlačítka Home/End ve formuláři

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#471]
Ve starém prostředí fungovala ve ve formulářích tlačítka Home/End - měla by být použitelná i v novém klientovi

**Comment by ZdenkaSera** [comment]
@luckajirku Založila jsem nové issue, protože Alberto tlačítka zprovoznil už dnes v rámci https://github.com/proarc/proarc-client/issues/464 - raději to odděluji, abychom to nehledali.

**Comment by luckajirku** [comment]
Liší se to v úložišti a v tom vyskakovacím formuláři nového objektu. V úložišti to funguje, ale u nového objektu se to chová jinak. Ani Home/End, ani PgUp/PgDn tam na začátku nefungují, nejprve musí člověk kliknout do nějakého pole, a pak začne fungovat PgUp/PgDn, když funguje tohle, tak následně začne fungovat i Home/End. Home/End nejsou pro každého, jen pro toho, kdo se k tomu správným postupem prokliká:-).

**Comment by luckajirku** [comment]
@ZdenkaSera ale to by mělo být OK, že když je focus v poli, tak ta tlačítka nefungují na šoupátko. Ale v tom novém objektu se to chová jinak.

**Comment by ZdenkaSera** [comment]
@luckajirku Díky :-)

**Comment by albertoh** [comment]
Opraveno (chovani, ktere popasala @luckajirku ).
Porad ale plati, ze aby fungovalo scrollovani pomoci klavesnici, focus musi byt na tom scrollovacim elementu. Pokud je v nejakem poli, nebo v jinem panelu, nepujde

**Comment by luckajirku** [comment]
Nevím, jestli to souvisí s touhle úpravou, ale když teď zakládám objekt (ročník, číslo - nevím, jestli to není ještě někde jinde) přes plusko, tak ten vyskakovací formulář při scrollování postupně mění šířku - nejdřív je normálně široký, pak se zúží, a pak ještě jednou. A cestou nahoru se zase rozšiřuje:-). Při zakládání z té horní lišty je šířka OK, dělá to jen přes to plusko.

**Comment by albertoh** [comment]
Nesouvisi, ale opravil jsem to :)

**Comment by luckajirku** [comment]
Tlačítka Home/End atd. už fungují všude a formulář přes plusko drží šířku. Za nás OK.

**Comment by SmejkalovaAnna** [comment]
Za nás taky, hezky to funguje.
