### ISSUE TITLE
Přidat sloupce urn:nbn a RDA/AACR do přehledu v úložišti (Hledání)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#473]
Návrh na rozvoj v roce 2024 ze schůzky 7.9.2023
Realizace pouze na Akubře

**Comment by SykoraLukas** [comment]
Na API hotové. Nutné jen doplnit do klienta.

**Comment by albertoh** [comment]
Pridano

**Comment by ZdenkaSera** [comment]
Za nás ok, ale ještě dotaz ostatním - standard a urn:nbn jsou jen ve spodní části okna úložiště. Potřebuje někdo přidat sloupce i do  horní části? děkuji. @luckajirku @katerinasirova @erikamirova

**Comment by ZdenkaSera** [comment]
Poslední komentář beru zpátky - na masteru jsou standard i urn.nbn také v horním okně. @albertoh Alberto, v čem může být problém, když ve  verzi 2.3.2 nasazené v KNAV máme údaje jen ve spodní části?

![image](https://github.com/user-attachments/assets/cd7ebf59-90e0-44d2-882d-213c2c0c490e)

![image](https://github.com/user-attachments/assets/0f37f2d4-d93c-45ad-9ea1-6ae484fc3f66)

**Comment by ZdenkaSera** [comment]
Tady ponechávám štítek chyba proto, že úprava měla být ve verzi 2.3.2, ale zřejmě nebyla zahrnuta. Na masteru ok.

**Comment by SykoraLukas** [comment]
Bude zahrnuto v příští verzi.

**Comment by ZdenkaSera** [comment]
V nové verzi obsaženo, urn:nbn i standard jsou i v horním okně úložiště.
