### ISSUE TITLE
Zobrazení počtu stran

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc-client#474]
**Hlavní okno-Úložiště:** 
Přidat sloupec s počtem stran v objektu ve spodním okně - u vyšší úrovně by se zobrazoval celkový počet stran ve všech nižších úrovní, po rozkliknutí by se zobrazil počet stran u nižší úrovně - např: u Titulu - celkový počet ve všech výtiscích dohromady, po rozkliknutí na úrovni Ročníku počet stran v ročníku  ( nebo po kliknutí na ročník se to může zobrazit ) a po rozkliknutí ročníku (nebo po kliknutí na výtisk) se to zobrazí u výtisku(ů)
**Editační okno:** 
Po označení bloku stran zobrazit počet označených - idálně např: _"20 z 365"_

**Comment by luckajirku** [comment]
> **Editační okno:** Po označení bloku stran zobrazit počet označených - idálně např: _"20 z 365"_
- tahle část není rozšíření, ale navrácení toho, co bylo ve starém rozhraní (úplně přesně teda ve starém je jen počet aktuálně vybraných, bez infa, z kolika celkem).

**Comment by albertoh** [comment]
Vraceno

**Comment by luckajirku** [comment]
počet už se ukazuje

**Comment by SmejkalovaAnna** [comment]
Ano, navrácená část - _Editační okno: Po označení bloku..._ - funguje dobře.  Na rozšiřující část - _Hlavní okno-Úložiště_ - se budeme těšit :)

**Comment by ZdenkaSera** [comment]
V testu KNAV ve verzi v4.1.1./2.2.1 je to ok (tj. v editaci se zobrazuje počet označených stran, ať jsou označené v bloku nebo pomocí ctrl odděleně).

**Comment by ZdenkaSera** [comment]
Tady odebírám štítky o testování, abychom na dokončení rozvojové části issue nezapomněli v rámci letošního roku.

**Comment by SykoraLukas** [comment]
Domluveno na schůzce, že se bude zobrazovat jen na úrovni objektů, které pod sebou mohou mít stránky.

**Comment by tumovam** [comment]
Funguje jak v Úložišti během vyhledávání, tak při editaci. V editačním okně ještě chybí zobrazit počet označených - ideálně "vybraný počet z celkového počtu" = např: "20 z 365" nebo "20/365" apod.. 
Byla by to velká úprava, je to možné dodělat?
Děkuji

**Comment by tumovam** [comment]
@albertoh prosím dle domluvy na schůzce bude počítat objekty, ne strany.

**Comment by tumovam** [comment]
Funguje ve v2.3.2

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
