### ISSUE TITLE
změna barvy u názvů v úložišti

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#475]
V poslední verzi se teď najednou objevila designová změna, která nás překvapila - ani nevím, že bychom probírali, že se má udělat. Teď se snažíme vychytat chyby z pohledu funkčnosti - a sledovat, co se tam ještě mění pod rukou, nějak nestíháme.
V úložišti jsou názvy, který dřív byly černé, barevně. Jako asi to vypadá na pohled hezky, problém je v tom, že ta barva je méně výrazná než ta černá, takže ten nejpodstatnější údaj na řádku je nejméně výrazný a hlavně - hůř čitelný. A to je modrá, která je ještě v pohodě, ale jak to pak bude vypadat s dalšími barvami v případě změny barevnosti... 

inovace: 
![modrenazvy](https://github.com/proarc/proarc-client/assets/6359479/da743d2e-c96d-47dc-ae12-f36d7fad5303)
původní:
![cernenazvy](https://github.com/proarc/proarc-client/assets/6359479/d07b306c-aab7-4300-91bc-04adaf4f619e)

**Comment by pkudela** [comment]
ahoj, o tom nic nevim, dival jsem se a je tam pridany "a" element, ktery dela to, ze se text odbarvi na modro jako odkaz, ja tam uz dlouhou nic nedelal, @albertoh vis o tom neco?

**Comment by albertoh** [comment]
Moje chyba. Vratim to zpet.

**Comment by albertoh** [comment]
Vraceno

**Comment by luckajirku** [comment]
tak tahle varianta, že to bylo nedopatřením, mě nenapadla:-). takže už OK a zavírám.
