### ISSUE TITLE
Chybná hláška po spuštění importu u náhrady/přidávání souborů

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#476]
Při nahrazování nebo přidávání souborů se po nastavení parametrů importu a klinutí na ikonu Načíst objeví hláška "Import se nezdařil".

![image](https://github.com/proarc/proarc-client/assets/8912422/e97b5522-cd19-412d-8172-3013a7687f84)

Bylo by dobré, aby tam byl jiný text, protože nahrání nebo výměna souborů normálně probíhá a je možné ji najít ve Správě procesů s odpovídajícím statusem.

Souvisí s #1417 a #1372.

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, je tohle opravené a bude v nejbližším releasu? Děkuji.

**Comment by albertoh** [comment]
jj, opravil jsem to. Souviselo to i s API

**Comment by ZdenkaSera** [comment]
Oprava není zahrnutá do verze 2.2.1, chyba trvá (na inovatice neotestujeme)

Prosím zároveň opravit tyto chyby hlášené v issue https://github.com/proarc/proarc/issues/1417. Děkuji.

![image](https://github.com/proarc/proarc-client/assets/79305516/ff3bbf15-a6a2-4112-b8bf-ba1cacc77ec4)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Název už na Inovatioce opraven, našla jsem v procesch toto:

![image](https://github.com/proarc/proarc-client/assets/79305516/f2d3e202-1e4a-49dd-8424-8a68bb08afc0)

Když ale chci podle této hodnoty filtrovat ve sloupci Profil, nevidím ji tam.

**Comment by albertoh** [comment]
Pridano do roletky

**Comment by ZdenkaSera** [comment]
Díky, na master ok.

**Comment by ZdenkaSera** [comment]
@albertoh Tohle je také oprava, kterou prosíme zahrnout do nejbližšího releasu, na masteru to vypadá ok. Moc díky.

**Comment by ZdenkaSera** [comment]
@katerinasirova Tohle se lokálně v KNAV zdí ve verzi 4.1.3./2.2.2 funkční. Zatím tedy navrhuji k zavření a pokud se něco objeví, znovu zadáme. OK?

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, můžeme tohle zavřít? Mělo by to být už v předchozí verzi 2.2.2. Díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by SykoraLukas** [comment]
> Pokud nahrazuji větší množství dat, ve správě procesů se náhrada postaví do fronty a tento status zůstává i po doknčení procesu, tlačítko obnovit zde nepomůže, je nutný refresh prohlížeče. Testováno v chromu.

@albertoh můžeš na to kouknout?
