### ISSUE TITLE
Opravy urn:nbn - fáze II - Deaktivace urn:nbn

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#478]
Klientská část pro https://github.com/proarc/proarc/issues/1627.

Do Menu CZIDLO je potřeba doplnit novouv funkci. Jedním z parametrů je seznam resolverů CZIDLO a druhým hodnota URN:NBN.

Volání na API: 

```
### INVALIDATE REMOTE URNNBN
POST {{proarcRemoteHostUrl}}/rest/v2/object/urnnbn/invalidateRemote
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&valueToDeactivate=aba007-0000xi&resolverId=inovatika
```

**Comment by ZdenkaSera** [comment]
Zavírám, pokud se v provozu objeví problém, založíme nové issue.
