### ISSUE TITLE
Seznam identifikátorů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#479]
V poslední vydané verzi (i na současné inovatice-masteru) ve formulářích chybí asi lokalizace/labely pro seznam identifikátorů (type). Do metadat se stahují správně.

![image](https://github.com/proarc/proarc-client/assets/79305516/ffe53e8d-1f2d-4dcd-bbea-ae7ef9422fb2)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Na inovatice-masteru ok. Díky.
