### ISSUE TITLE
Popisná metadata - formulář neukazuje všechny údaje (vše je vidět jen v xml)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#48]
Ve formuláři musí mít uživatel možnost vidět vše, co je v xml. Pokud potřebují někteří uživatelé zjednodušený formulář, pak to má být jako volba, ale ne jako jediná možnost pro všechny. Teď načtu údaje ze záznamu, v xml vidím vše, ale ve formuláři jen vybraná pole. PROČ? Je to chyba, nebo (nesmyslný) záměr?

**Comment by luckajirku** [comment]
Nechápu label návrh na rozšíření @tumovam... To by přeci měla být základní funkce, že budou všechna popisná metadata vidět ve formuláři. Nebo je cílem nového uživatelského rozhraní, aby se popisovalo/editovalo v xml? 
Defaultně by to mělo zobrazovat vše, a zjednodušený formulář by tam měl být, pokud ho tedy určitý typ uživatelů potřebuje, jen jako volba (ideálně definovatelný v konfiguraci)

**Comment by tumovam** [comment]
Nooo, sama od sebe bych ten label nepřidala. Podle data a času přidání štítku to odpovídá času vývojové schůzky. Pokud si správně vzpomínám, tak "enhancement" se přidával kvůli "_**podbarvení editovaného údaje ve formuláři i v xml**_". 

Obávám se, že teď řešíme x věcí v jednom issue:
1) Nemýlím-li se, tak zjednodušený formulář je pouze u eČlánku. A byla bych ráda, aby se zjednodušené formuláře nezaváděly, od toho máme krásnější ProArc ;) 

2) Jestli toto issue chápu správně, tak chcete, aby **vše, co je v xml, bylo i ve fomuláři**, je to tak @luckajirku ? A k tomu si dovolím poznámku - ani v současném ProArcu nejsou ve formuláři vidět všechny údaje, které se stáhnou z katalogu do xml. A @honza-rychtar už se několikrát ptal, co nám ve formuláři chybí. Dohledala jsem tato issue:  
- rozsah stran - https://github.com/proarc/proarc-client/issues/16
- klíčová slova
- abstrakt (k testování)
- pole do formuláře pro popis ročníku - https://github.com/proarc/proarc-client/issues/50 
- pole do formuláře pro popis čísla - https://github.com/proarc/proarc-client/issues/51

Pokud Vám chybí ještě něco, prosím, doplňte to sem, nebo založte issue. Jinak se z toho asi nikdy nevyhrabeme... 

3) Podbarvení v xml, když se edituje ve formuláři. Kvůli tomu je štítek "2 návrh na rozšíření".

**Comment by luckajirku** [comment]
Na schůzce (resp. na dvou) jsme se o tom bavili, bohužel v těch v těch posledních zápisech se objevuje jen část toho, co se probere, a ještě stručně a ne úplně jasně.
Na těch schůzkách jsme si řekli, že ve formuláři v novém klientovi **má být vše, co je ve formuláři v současném klientovi**. Přijde mi nesmyslné vypisovat jednotlivé oblasti, které je třeba doplnit, když to může Honza projet podle současného klienta, porovnat a doplnit, co v novém není. Extra vypichovat, co je třeba přidat, zakládat na to nové issue, by mělo být u něčeho, co tam předtím nebylo. Právě takhle se z toho nevyhrabeme. Potřebujeme mít něco, co bude plus mínus odpovídat tomu původnímu, a tam teprve můžeme připomínkovat, co tam chceme dát navíc. Současný způsob je nesmyslný.
ad 3. - a právě na tohle by nové issue mělo být a nemělo by se to míchat sem. Podbarvování JE nová funkce, která předtím nebyla a bez které se obejdeme, je to "jen" vylepšení (byť fajn). Zatímco to, co zmiňuju výš, je základ, bez kterého nejde fungovat.

**Comment by tumovam** [comment]
Máte možnost zápis upravovat, pokud tam něco chybí, klidně to dopište. 
Ok, štítek odebírám a založím nové issue na podbarvení xml.

**Comment by honza-rychtar** [comment]
Teď už je u monografie a periodika kromě relatedItem editovatelné víceméně vše.
Zobrazení povinnosti (M/MA, ...), text nápovědy, zobrazení polí a podpolí, seznam voleb některých polí - se bere z šablony, takže se formulář může generovat pro každý model jinak. Teď je to rozlišeno pro monografie a periodika. Zbylé modely zatím používají šablonu pro monografie (kromě stran, čísel a ročníků).

**Comment by luckajirku** [comment]
> Teď už je u monografie a periodika kromě relatedItem editovatelné víceméně vše. .
Co znamená "víceméně vše"? Je to tedy zralé k testování, nebo ne?

**Comment by honza-rychtar** [comment]
Vše ze standardu pro daný model.

**Comment by ZdenkaSera** [comment]
HR: ve formuláři vše podle standardu a role šablon je zobrazení omezit podle modelu. K testu.

**Comment by luckajirku** [comment]
další, co chybí: https://github.com/proarc/proarc-client/issues/186

**Comment by ZdenkaSera** [comment]
Přidávám #206

**Comment by ZdenkaSera** [comment]
A ještě jednou #204

**Comment by ZdenkaSera** [comment]
eČlánky #149 
eMonografie #137

**Comment by luckajirku** [comment]
Tohle asi bude k zavření, stejně se s novým standardem bude muset všechno znovu projít.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
