### ISSUE TITLE
Opravy urn:nbn - fáze II - Nová registrace uuid

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#480]
Klientská část pro https://github.com/proarc/proarc/issues/1626

Do Menu CZIDLO je potřeba doplnit novouv funkci.

Volání na API:

```
### NEW REGISTRATION URNNBN WITH OLD VALUE DEACTIVATION
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/registerAgain
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:91e24ccc-4292-49a4-9674-95192edef5ee&resolverId=inovatika
```

**Comment by albertoh** [comment]
@SykoraLukas  zkontrolujes?

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas CZIDLO/Oprava/Doplnění - v seznamu identifikátorů chybí ččnb - nevím, čím se řídí nabídka v roletce, Test: ččnb v objektu  chybělo, nově jsem je přidala a chtěla doplnit do záznamu v resolveru

**Comment by ZdenkaSera** [comment]
Zavírám, pokud se v provozu objeví problém, založíme nové issue.
