### ISSUE TITLE
Opravy urn:nbn - fáze II - Oprava/doplnění

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#481]
Klientská část k https://github.com/proarc/proarc/issues/1628.

Do Menu CZIDLO je potřeba doplnit novouv funkci.
Funkce má 3 parametry: 
resolverId tak jako u všech jiných funkcí CZIDLA
operation - výběr z comba (hodnota update, delete)
identifier - seznam všech idenfifikátorů kromě urnnbn, ccnb a isbn

```
### UPDATE RESOLVER WITH IDENTIFIER
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/updateIdentifier
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:5d3fba10-2f81-4262-8a24-7c1e38eeba55&resolverId=inovatika&identifier=proarcId&operation=delete
```

**Comment by albertoh** [comment]
@SykoraLukas  zkontrolujes?

**Comment by SykoraLukas** [comment]
Nelze, ccnb neni identifikátor, který lze updatovat (stejne jako isbn a issn) - to jsou přímé identifikátory, kvůli kterým je nutná nová registrace. Aspon podle toho, co povoluje API.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, tohle byl jen rychlý pokus, vrátím se k tomu a vyzkouším chování ostatních oprav.  Níže jen poznámky, neber je zatím jako požadavek na změny.
Koukám do metodiky a zřejmě je tohle jeden z rozporů mezi teorií  a technickými možnostmi, případně jsme teorii chybně interpretovali. Str. 72 metodiky: 
Změny nevyžadující deaktivaci původního dokumentu: Doplnění dosud chybějících údajů (např. identifikátor čČNB)

**Comment by ZdenkaSera** [comment]
Vzhledem k tomu, že do resolveru posíláme pouze povinné údaje, tento nástroj zatím nebudeme využívat, je možno jej použít pouze k modifikaci některých nepovinných údajů (dáno vlastnostmi api reolveru)

**Comment by ZdenkaSera** [comment]
Zavírám, pokud se v provozu objeví problém, založíme nové issue.
