### ISSUE TITLE
nezobrazení většího skenu v panelu Obrázek - import i úložiště, jen v klientovi

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#483]
Narazili jsme na problém se zobrazením většího skenu - máme u knihy jako přílohu složený volební lístek, po rozložení je x krát větší než zbytek skenů. Po naskenování vcelku se nám v novém klientovi v importu ani v úložišti nezobrazuje v panelu Obrázek. Ve starém rozhraní ho ale vidíme. 
Velikost 9944 x 7222 pixelů a 70,1 MB. V našem PA1 je to uuid abdb2ae9-0e9b-4ccb-bd8d-2b1f3537cc61.

**Comment by ZdenkaSera** [comment]
@albertoh a @SykoraLukas se podívají na důvody

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Slíbili jsme dodat obrázek, který se v jádře zobrazuje a v klientovi ne. Chcete-li, můžu vyrobit monografii s touhle mapou a poslat ji jako archiv/NDK/K4 k načtení na inovatice, to si případně vyberte.

![image](https://github.com/proarc/proarc-client/assets/79305516/190074d0-619f-43f1-bf04-a71609f049db)

**Comment by albertoh** [comment]
> @albertoh @SykoraLukas Slíbili jsme dodat obrázek, který se v jádře zobrazuje a v klientovi ne. Chcete-li, můžu vyrobit monografii s touhle mapou a poslat ji jako archiv/NDK/K4 k načtení na inovatice, to si případně vyberte.

Jo, prosim

**Comment by ZdenkaSera** [comment]
@albertoh Odkaz na testovací monografii mailem.

**Comment by SykoraLukas** [comment]
Nahráno sem: https://proarc-master.inovatika.dev/repository/uuid:818649e0-34a2-475b-999e-560708e7694b

**Comment by ZdenkaSera** [comment]
@luckajirku @SykoraLukas Můj komentář výše k detailnímu náhledu v klientovi je nerelevantní - v klientovi jsem po importu pdf měla omylem zapnutý náhled na média Tam je obrázek skutečně vidět,  ale jako "Obrázek" opravdu ne.

**Comment by albertoh** [comment]
Po chvili zkoumani, nasel jsem problem. To se stava jen v prohlizecich Chrome / Chromium. Firefox nema problemy.
Pro zobrazeni obrazku se pouziva knihovna OpenLayers. Tento problem je nahlasen ale vzhleden k tomu, je neni vubec na strane Chrome pri jake velikosti obrazek prestava fungovat, OpenLayers team rozhodl to ignorovat.

Ja muzu nastavit nejakou maximalnou velikosti (v pixels), aby pri prekroceni tohoto limitu nepouzivala se knihovna OpenLayers. Obrazek se muze tim padem zobrazit bez ovladacich prvku (zoom, cela obrazovka...)

**Comment by ZdenkaSera** [comment]
Díky, zkusila jsem firefox - tam je to ok. Pobavíme se o řešení na schůzce.

**Comment by albertoh** [comment]
Nastaveno 6000px jako maximalni velikost pro pouzivani OpenLayers

**Comment by ZdenkaSera** [comment]
Na masteru už ok, mapy se zobrazují. Zdánlivá chyba, kdy se na schůzce zobrazovala část mapy s jinou stránkou, ve skutečnosti chybou nebyla, strana tak vypadá a část mapy opravdu obsahuje.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV na stejných datech, jako jsou k tetu na masteru - ve verzi 2.2.2 fuknční, díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by luckajirku** [comment]
> Ja muzu nastavit nejakou maximalnou velikosti (v pixels), aby pri prekroceni tohoto limitu nepouzivala se knihovna OpenLayers. Obrazek se muze tim padem zobrazit bez ovladacich prvku (zoom, cela obrazovka...)

když je jeden obrázek větší - např. přebal, tak se to u něj přepne do toho jiného zobrazení, ovládací prvky na liště zmizí, sken se na načte. Potud OK. Ale při kliknutí na další, normální stranu, na liště sice vidím tlačítka, ale sken už ne. @albertoh mrkni na to prosím tě, tím časem na načtení, o kterém byla řeč na schůzce, to nebude.

![přebal](https://github.com/proarc/proarc-client/assets/6359479/7491d82d-76a9-48fe-b4f4-05f0659b53d6)





![normalnístrana](https://github.com/proarc/proarc-client/assets/6359479/958e3929-6a59-45a8-98c5-9622fc3e4c6e)

**Comment by albertoh** [comment]
Je to zakerny problem... Vyresil jsem to ale ma to problem: pokud mame ten velky obrazek, objevi se scrollbar.
Zatim se mi nedari to odstranit ale obrazky jsou videt

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
