### ISSUE TITLE
Korekce OCR pomocí nástroje PERO

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#484]
Klienská podpora pro https://github.com/proarc/proarc/issues/1393.

Nutné volat novou funkci, která je dostupná z obrazovky OCR.

```
### GENERATE ALTO FOR PID
POST {{proarcUrl}}/rest/v2/object/generateAlto
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{uuid}}
```

**Comment by albertoh** [comment]
Hotovo na klientu.
@pkudela podivej se do spravy procesu. Stav vygenerovan neni videt

**Comment by ZdenkaSera** [comment]
Vazba na issue https://github.com/proarc/proarc-client/issues/131

**Comment by ZdenkaSera** [comment]
Funkční (komentář v issue https://github.com/proarc/proarc/issues/1393).

**Comment by ZdenkaSera** [comment]
Funkce je bez problémů, jen prosíme o úpravu labelů ve správě procesů:
Místo "jiné" prosíme text "PERO" - to by se mělo promítnout do 
![image](https://github.com/user-attachments/assets/d6753f4f-2beb-402e-ac66-69291bcccec2)

**Comment by ZdenkaSera** [comment]
@albertoh Vracím sem ještě štítek chyba, aby se to ukázalo mezi věcmi k řešení.

**Comment by SykoraLukas** [comment]
@ZdenkaSera toto nepůjde přejmenovat. Generování pomocí PERA je ve stejné skupině jako generování pomocí PDF2Archive. Proto to je nazvané obecně, stejně jako jsou importy a exporty. Rozlišuje se pomocí profilu.

Rovněž se bude upravovat skupina pro reindexaci, kam nově přibudou i procesy mazání.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkuji za vysvětlení, domnívali jsme se, že tady jde o samostatný proces. Zamyslíme se ještě nad případnou změnou názvu, která by dávala smysl. Zatím tedy prosím jen o zelený label u bezchybně dokončeného procesu. Díky.

**Comment by SykoraLukas** [comment]
Zamyslete se ještě nad tím, jestli procesy, které probíhají v ProArcu (Reindexace, mazání) mají být v jedné skupině s procesy, které provádí externí aplikace (PERO, PDF2Archive) nebo zvlášť. Případně prosím o specikování jednotlivých názvů pro stavy (probíhá, hotovo, chyba) u jednotlivých skupin.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Znovu jsme se na to koukli a máme za KNAV pár poznámek, shrnu je znovu:
- [ ] V souvislosti s Perem tu mluvíme o externím procesu, ale název profilu ve správě procesů je "**Interní** - PERO". Ničemu to nevadí, ale možná by to mohlo mást :-)
- [ ] V roletce se seznamem profilů k filtrování tento profil chybí
- [ ] Jen připomínám změnu štítků na červený při chybě a zelený při ok-konci (teď vše šedivé)
- [ ] Název skupiny s Perem by za nás mohl být "Externí" a slučovat tedy (i případné budoucí) zapojené externí nástroje
- [ ] Stavy u všech zmíněných procesů/obou skupin jak navrhuješ (probíhá, hotovo, chyba), zatím nás další nenapadá

**Comment by albertoh** [comment]
![image](https://github.com/user-attachments/assets/e3c8678a-ccc5-4dd3-9e77-1fb6f1ccb56f)

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, to je super, díky; filtrování podle stavu funguje. Měla jsem ale na myslí roletku nazvanou "Profil":

![image](https://github.com/user-attachments/assets/07a1d240-2908-4925-9d5d-bc6c1219bae2)

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
Díky, je to ok.

**Comment by ZdenkaSera** [comment]
Tady asi došlo k posunu pokud jde o shlukování externích a interních procesů 👍, ale prosíme ještě o trochu kosmetiky.  Volání opravy OCR 1 skenu ve v4.2.0/2.3.0 (lokálně v KNAV) teď ve správě procesů vypadá takto (bez ohledu na jazykovou mutaci):

![image](https://github.com/user-attachments/assets/a9f9feb3-10e0-43e0-9855-01f4ee0d2a2c)

Bezchybně dokončený proces prosíme se zeleným štítkem a prosíme upravit filtrování podle stavu a profilu. Děkuji.

**Comment by SykoraLukas** [comment]
Díky, v lokalizaci chybí klíče. Doplníme.

**Comment by SykoraLukas** [comment]
Doplněno.
