### ISSUE TITLE
Zvýraznění repre strany

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#485]
Bylo by dobré, kdyby bylo vidět v tabulce i náhledech, že daná strana je označená jako reprezentativní - teď to nezjistím jinak než ve formuláři té strany. Třeba ji vytučnit - jak řádek v tabulce, tak ten zkrácený popis u náhledů... - nebo jestli někdo vymyslí něco lepšího...

**Comment by ZdenkaSera** [comment]
@luckajirku @pkudela Přidávám label redesign

**Comment by ZdenkaSera** [comment]
@pkudela Pošle návrhy

**Comment by SykoraLukas** [comment]
Přidat pole do indexu SOLRu a na jeho základě zvýraznit řádek ve stromě a v náhledech.

**Comment by SykoraLukas** [comment]
Na API hotové, nutné doplnit pole do Klienta a na jeho základě zvýraznit řádek. @pkudela vymyslí, jak se to udělá.

**Comment by SykoraLukas** [comment]
@luckajirku navrhuje tučné písmo.

**Comment by ZdenkaSera** [comment]
@pkudela Prosím, podíval by ses na tohle issue? Děkuji moc.

**Comment by pkudela** [comment]
hotovo

<img width="746" alt="image" src="https://github.com/user-attachments/assets/235e7122-5396-43b8-b45a-c13eaf7ea49d">

<img width="642" alt="image" src="https://github.com/user-attachments/assets/49230f3a-fe78-4876-bc80-ee8ce1b161ef">

**Comment by pkudela** [comment]
> @pkudela Prosím, podíval by ses na tohle issue? Děkuji moc.

uz se stalo, ani jsem si nevsimnul, ze jsi pred tim psala, je to hotove

**Comment by ZdenkaSera** [comment]
@pkudela Díky :-) Nechci mluvit za @luckajirku, ale možná by se to zvýraznění hodilo i v úložišti ...?

**Comment by ZdenkaSera** [comment]
@pkudela @luckajirku Beru zpátky, je to i tam, byla jsem přihlášená na visk2024 místo na masteru. Super

**Comment by ZdenkaSera** [comment]
@pkudela Naopak to není v paginaci v importu - myslela jsem si, že Tvé ukázky byly odtud.

**Comment by pkudela** [comment]
> @pkudela Naopak to není v paginaci v importu - myslela jsem si, že Tvé ukázky byly odtud.

Ted jsem zmaten, posli mi konkretni url.

**Comment by ZdenkaSera** [comment]
Vysvětleno po telefonu - v paginaci sice můžu nastavit reprezentativní stranu (to už je tam dlouho), ale zatím nelze zvýraznit tučně v přehledu skenů, probíhá úprava na api, která to umožní.

**Comment by SykoraLukas** [comment]
Podpora na API při importu, @pkudela doplníš do importu?

**Comment by pkudela** [comment]
> Podpora na API při importu, @pkudela doplníš do importu?

Jasne, jdu na to.

**Comment by pkudela** [comment]
hotovo, je nasazeno na server k testovani, uz se oznacuje repre strana i v importu

<img width="674" alt="image" src="https://github.com/user-attachments/assets/3d4aaaf6-7352-4aa1-a569-36869200c021">
<img width="497" alt="image" src="https://github.com/user-attachments/assets/54836c35-a21d-448a-a6ba-95d9e78764d2">

**Comment by ZdenkaSera** [comment]
Prima, moc díky. Konečně slovo k testu budou mít zkušení uživatelé :-)

**Comment by ZdenkaSera** [comment]
Tohle se do vydané verze 2.3.1 nedostalo (nasazeno dnes v KNAV).

**Comment by ZdenkaSera** [comment]
Doplňuji, že v úložišti je to ok, zvýraznění chybí jen v paginaci v importu.

**Comment by pkudela** [comment]
> Doplňuji, že v úložišti je to ok, zvýraznění chybí jen v paginaci v importu.

Ahoj Zdenko, dival jsem se na to jeste s Lukasem, jestli oba chapeme to same a v importu to je viz., screenshot nize z masteru, kde je posledni vydana verze. Pokud nemas na mysli toto a mas na mysli neco jineho, posli prosim nejaky screenshot, at to dokazeme s Lukasem nasimulovat.

![image](https://github.com/user-attachments/assets/7971bf9c-94d5-46fb-be35-4bbc19d93b47)

![image](https://github.com/user-attachments/assets/deb61312-6e1c-4f89-9c92-575ec9ca3ec3)

**Comment by ZdenkaSera** [comment]
@pkudela Ano, jde o tohle. V pátek jsem jen v rychlosti testovala nějaký základ a zřejmě jsem si nastavení pod rukou smazala - teď jsem to zkusila znovu a zvýraznění je vidět i v importu. Díky, omlouvám se.

**Comment by luckajirku** [comment]
za nás OK, možno zavřít

**Comment by pkudela** [comment]
Ahoj, posilam par screenshotu jak resit zobrazeni repre strany bez vytucneneho pisma zatim jen pro obrazkove nahledy, dejte vedet, ktery smer by vam vyhovoval, zatim to nenasazuji na server, ale mam to pripravene.

![image](https://github.com/user-attachments/assets/eb36a8cc-0e89-465f-b69f-67766787db98)

![image](https://github.com/user-attachments/assets/01a3428d-52ab-4fb1-9a56-c94da4342f73)

![image](https://github.com/user-attachments/assets/48df2352-c633-4e41-8e67-bab1710cf207)

![image](https://github.com/user-attachments/assets/aa49edc2-d459-45f8-bf47-d0e3de7bb495)9)

**Comment by luckajirku** [comment]
@pkudela za nás je to tučné písmo ok, tohle je to fakt divočina. Takhle výrazné označení evokuje stranu, se kterou se právě pracuje (nakliknutá, která je ve velkém náhledu). Schválně vyzkoušej, jak to bude vypadat v importu v dávce periodika, kde bude repre třeba každá pátá strana...

**Comment by pkudela** [comment]
> @pkudela za nás je to tučné písmo ok, tohle je to fakt divočina. Takhle výrazné označení evokuje stranu, se kterou se právě pracuje (nakliknutá, která je ve velkém náhledu). Schválně vyzkoušej, jak to bude vypadat v importu v dávce periodika, kde bude repre třeba každá pátá strana...

Aha, to jsem nevedel, ze muze byt oznaceno vice repre stran, v tom pripade ano, zkusim vymyslet jeste neco jineho, decentnejsiho.

**Comment by luckajirku** [comment]
ono v úložišti je jen jedna na objekt - ale v importu, když máš dávku periodika zatím nerozřazenou do čísel, jich může být fakt hodně - míváme běžně 4 stránková čísla...

**Comment by pkudela** [comment]
OK, bude to muze byt jen takovy marker - ruzek, ktery jsem tedy zmensil, muze byt v jakekoliv barve, nebo to muze byt treba nejaka ikona, muze by i jina, neco co nebude rusit, ale na prvni pohled budes videt, ze je to reprezentativni strana, jeste se zkusim zamyslet nad jinou variatntou, pripadne muze zustat jen tucne pismo.

![image](https://github.com/user-attachments/assets/6f628673-82cc-40c9-a14f-1bb15ec318a5)

![image](https://github.com/user-attachments/assets/e4613aec-3a99-45d7-b3dc-54aa02bc2e1e)

**Comment by pkudela** [comment]
> tyhle menší, decentnější rožky by šly. a ještě kdybys je zkusil tou tmavě šedou jako jsou ikony...

Co takto? Roh jsem dal sedivou barvou a aby navazoval na hranu nahledu a nebyl trochu mimo obrazek a ty jednotlive polozky  byly vice oddelena dal jsem tam ohraniceni jemnym odstinem sedive, tak dej vedet, jestli vyhovuje.

![image](https://github.com/user-attachments/assets/9aeaf1d0-f2f4-47da-920f-58820a2f5260)

**Comment by pkudela** [comment]
a takto to vypada u tech nahledu na sirku

![image](https://github.com/user-attachments/assets/ec3e031b-379a-45c0-aec6-bb0610309d96)

**Comment by pkudela** [comment]
a jeste s decentejsi sedivou ohraniceni, to je posledni

![image](https://github.com/user-attachments/assets/d2d80aa7-4f07-4338-a4b8-e41d0ea2bba0)

**Comment by luckajirku** [comment]
> ...Tucne pismo jsem dal pryc, aby bylo videt, jestli je to dostatecne poznat.
> 
a můžeš ho tam prosím tě vrátit? aby se na něj pak nezapomnělo:-). my to další zvýraznění (rožky, rámečky) bereme jako něco navíc (pro ty, kterým nestačí tučné písmo) k tomu tučnému, ale ne místo tučného. u toho je fajn, že se dá použít na obou místech - jak v řádkovém zobrazení, tak v náhledech - vidím tučné písmo, vím, že je to repre.

**Comment by pkudela** [comment]
> > ...Tucne pismo jsem dal pryc, aby bylo videt, jestli je to dostatecne poznat.
> 
> a můžeš ho tam prosím tě vrátit? aby se na něj pak nezapomnělo:-). my to další zvýraznění (rožky, rámečky) bereme jako něco navíc (pro ty, kterým nestačí tučné písmo) k tomu tučnému, ale ne místo tučného. u toho je fajn, že se dá použít na obou místech - jak v řádkovém zobrazení, tak v náhledech - vidím tučné písmo, vím, že je to repre.

Neni problem, je to tam nazpatek viz. screenshot, kterou variantu z tech odstinu sediveho ruzku a ohraniceni preferujes z toho co jsem poslal na screenshotech vyse? Ze bych to pak dal uz k testovani.

**Comment by luckajirku** [comment]
za nás ta poslední nejsvětlejší (ale to asi nepřekvapí:-))

**Comment by pkudela** [comment]
Hotovo, nasazeno, muzete testovat, dejte vedet, jestli takto vyhovuje a pokud ano, prosim zavrit toto issue.

https://proarc-master.inovatika.dev/repository/uuid:46132287-9d88-4536-a09f-bf36d1a4aff5
https://proarc-master.inovatika.dev/import/edit/825
https://proarc-master.inovatika.dev/import/edit/810

**Comment by nezbedova** [comment]
@pkudela je to nastavené i pro STT modely? Na našich "specialitkách" to nevidím.

https://proarc-master.inovatika.dev/import/edit/828



![obrazek](https://github.com/user-attachments/assets/d3391984-2b40-467b-b1f9-4cbab593457b)

![obrazek](https://github.com/user-attachments/assets/fee803c7-8807-46bd-9f75-bfc89a450000)

**Comment by pkudela** [comment]
> @pkudela je to nastavené i pro STT modely? Na našich "specialitkách" to nevidím.
> 
> https://proarc-master.inovatika.dev/import/edit/829
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/375632941-d3391984-2b40-467b-b1f9-4cbab593457b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjY0ODgsIm5iZiI6MTcyODYyNjE4OCwicGF0aCI6Ii8xMzgzMTk0Ni8zNzU2MzI5NDEtZDMzOTE5ODQtMmI0MC00NjdiLWIxZjktNGNiYWI1OTM0NTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA1NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODA2NTlhNTUzYjJmNGQ2ODU0NWZlNWU5MTFiYjQxMGM0MzJhODdmMzU3ODYwY2QwOWUyY2RmMTM0YmFlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7zW-RDwfSJIRTStO56Od3A2uVpT9MUMhD3XnvNLqNfw)
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/375632991-fee803c7-8807-46bd-9f75-bfc89a450000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjY0ODgsIm5iZiI6MTcyODYyNjE4OCwicGF0aCI6Ii8xMzgzMTk0Ni8zNzU2MzI5OTEtZmVlODAzYzctODgwNy00NmJkLTlmNzUtYmZjODlhNDUwMDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA1NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjNkYjhmYzExYTU4NjI3MjhlYTFiZGU5MWE1N2MyMDUwNmMzNTE0MzI3MGI2YzJlN2VkODlkODljZmZmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wcZ29XPkcD4Xdpgbo3XtS8a8s-pxoGzD8y_r9HTTfTA)

Asi je to tim, ze mi to nevraci api, @SykoraLukas muzes se na to prosim mrknout? Nevidim to tam viz. screenshot.

![image](https://github.com/user-attachments/assets/e5c505a8-82d2-4a99-8274-1db2ffcf8dd2)

**Comment by ZdenkaSera** [comment]
@pkudela Tady se něco asi změnilo, i když z issue to není zřejmé? 

@nezbedova na tom testovacím záznamu https://proarc-master.inovatika.dev/import/edit/829 už šedé růžky vidím - je to ok?

![image](https://github.com/user-attachments/assets/aac5691b-ce75-4705-bc8b-7341dc18f9e3)

**Comment by nezbedova** [comment]
@ZdenkaSera @pkudela 

Pokud to bude takto, tak nám to vyhovuje.
Děkuji.

**Comment by ZdenkaSera** [comment]
@nezbedova Díky.
@pkudela Většina diskuse výše probíhala po přidání štítku "k uzavření", ale z jejího průběhu soudím, že štítek platí  a je to ok. Prosím o zařazení do nejbližší verze. Děkuji.

**Comment by tumovam** [comment]
Zavírám na základě domluvy na schůzce.
