### ISSUE TITLE
Chybný formát data vytvoření/úpravy objetku na Akubře

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#486]
Při použiítí Akubry se v klientovi zobrazuje datum vytvoření/úpravy objektu ve formátu `MM.DD.RRRR` místo `DD.MM.RRRR`, děje se to i na testu inovatiky, ale jen na Akubře. Ve starém rozhraní je to správně. U instancí na Fedoře je to správně i v klientovi

![obrazek](https://github.com/proarc/proarc-client/assets/57805328/d06a57e9-418c-4e58-a50c-dcbc8fadda2a)

**Comment by SykoraLukas** [comment]
Opraveno na jádře.

**Comment by SykoraLukas** [comment]
Ještě nutné opravit na klientovi.

**Comment by kerschfilip** [comment]
formát data je OK, na poslední schůzce jsme řešili, že u nás je to ale o dvě hodiny špatně - protože je špatně nastavený čas na serveru. Tak jen upozornění, že na Inovatice je to taky špatně, jestli je to teda tím :-) 

![image](https://github.com/proarc/proarc-client/assets/57805328/9ca1ce97-d5bc-433d-8694-30a4c6b57699)
