### ISSUE TITLE
Problémy s poslední verzí klienta na testu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#487]
V poslední verzi klienta v2.2.0 (09.01.2024) je to čím dál rozbitější:
- není vidět sken v panelu Obrázek 
- často se objevuje bílá obrazovka - i třeba po nastavení v profilu, nebo překliknutí do jiné agendy (třeba jsem v importu a kliknu nahoře na Hledat), je pak potřeba refresh
- sloupce, které jsem si pracně nastavila, jsou při dalším přihlášení pryč - vypadá to zas takto:
![srazenesloupecky](https://github.com/proarc/proarc-client/assets/6359479/7f2d8f39-c4ad-4ad3-85e8-d9676a40577f)

**Comment by albertoh** [comment]
To se stalo dnes? Ted koukam na to, a nevidim zadny z tech problem. @SykoraLukas deployoval jsi ted API?

**Comment by ZdenkaSera** [comment]
@albertoh @luckajirku Teď jsem to zkoušela a první dva body potvrzuji. S nastavením sloupců jsem měla trochu víc štěstí - zůstalo, ale jen v případě, že jsem otevřela objekt, který měl skeny. Pokud jsem v editaci otevřela něco bez skenů, chovalo se to jako u Lucky.

**Comment by albertoh** [comment]
@ZdenkaSera @luckajirku Problem sloupcu, kdyz neni zadny objekt jsem opravil.
Muzete mi konkretne napsat ktere skeny nejsou videt? Ja je vidim...
Zatim se mi nepodarilo se dostat na bilou obrazovku, ani po profilu nebo prekliknuti...

**Comment by albertoh** [comment]
> sloupce, které jsem si pracně nastavila, jsou při dalším přihlášení pryč - vypadá to zas takto:

Nastaveni by melo porad platit, neztratilo se

**Comment by ZdenkaSera** [comment]
@albertoh V editaci jsem klikla procházela metadata stran, pak jsem klikla na šipku zpátky (horní lišta prohlížeče) a dostala jsem prázdnou obrazovku

![image](https://github.com/proarc/proarc-client/assets/79305516/0f899d8d-84cb-478b-8f20-fb526f7ae207)

**Comment by ZdenkaSera** [comment]
V importu jsem chtěla editovat metadata - přeskočila jsem do nastavení obrazovky (vypnula jsem jednu podobrazovku) - z editace jsem se dostala na bílou obrazovku, takže jsem se musela vrátit do načtených dávek a začít znovu. Když stojím kurzorem na kterémkoli skenu, v pravém panelu obrázek není vidět. V editaci v úložišti se to chová stejně

![image](https://github.com/proarc/proarc-client/assets/79305516/9f0805b1-d709-4a52-a093-2534b58f9404)

**Comment by albertoh** [comment]
Po telefonickym rozhovoru se Zdenkou jsme nasli, ze chybel jeden soubor na serveru :-O

Uz je tam, obrazky by mely jit vsem

**Comment by ZdenkaSera** [comment]
Znovu jsem vyzkoušela a už se mi nepodařilo nasimulovat ani jeden z problémů, zdá se to ok. Díky.

**Comment by ZdenkaSera** [comment]
@albertoh Tak přece jen - udělala jsem zase nějaké změny v nastavení obrazovky  a po importu nových skenů mi zase chybí možnost uložit je pod objekt

![image](https://github.com/proarc/proarc-client/assets/79305516/fd5398a5-e36b-4aa9-817e-25470a5ae4de)

**Comment by albertoh** [comment]
Uz to vidim i ja, konecne...
Hned opravim

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Tak teď už jsem opravdu nenašla protipříklad, zdá se to ok. Děkuji.

**Comment by luckajirku** [comment]
akorát se nám teď zas nějak nepřepisují popisky - jakože správa dávek je navbar.process-management atp. - musím někde něco udělat já jako uživatel, nebo tam ještě něco chybí?

**Comment by albertoh** [comment]
To je akorat zpusobeno pridani vice jazyku #192 
Lukas pracuje na doplneni prekladu. Prepnuti na cs-en by melo byt v poradku

**Comment by luckajirku** [comment]
No netestuje se to v tomhle mezistavu úplně nejlíp... Jinak bílou obrazovku mám opět - když kliknu na hlášku u kdovíkam zmizelé dávky "Ceska k importní dávce neexistuje! Hledaná cesta: /data/proarc/.proarc/users/svkhkadmin/import/Monografie/Methodika krasopisu/proarc_import" a dám Zavřít, mám bílo. Dám refresh, dostanu hlášku. Dám zavřít, mám bílo...

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem zpracování dříve v minulosti načtené dávky - potvrzuji, že po zavření hlášky o neexistující cestě skončím na bílé obrazovce místo zpátky na seznamu načtených dávek, na ten se dostanu až návratovou šipkou prohlížeče. V konzoli žádná chybová hláška.

**Comment by ZdenkaSera** [comment]
Doplňuj - nezávisí to na prohlížeči (standardně testuji v chromu, zkusila jsem mozillu)

**Comment by albertoh** [comment]
Opraveno. Po zavreni se jiz vraci

**Comment by ZdenkaSera** [comment]
Ano, vrací - díky.

**Comment by ZdenkaSera** [comment]
@luckajirku Na testu KNAV se nám zatím žádná z chyb  tady popsaných neprojevila (v4.1.1./2.2.1)

**Comment by ZdenkaSera** [comment]
Při testech v KNAV jsem ve verzi 4.1.3/2.2.2 na žádný z popsaných problémů nenarazila - @luckajirku navrhuji k uzavření a v případě, že se některé potíže objeví, otevřeme nebo založíme nově. ok?

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
