### ISSUE TITLE
mizející dávky na inovatice

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#488]
Vyhodím to ještě jako extra issue, aby to nezapadlo. Netušíme, co se děje, ale některé dávky z importu mizí. Nepovedlo se nám vysledovat za jakých okolností - někdy se k rozepsané dávce dá vrátit a dopopsat, jindy tam pak už není (a ne, není to tím, že by do ní vlezl někdo jiný pod stejným uživatelem a uložil ji).

**Comment by luckajirku** [comment]
Tak možná něco mám. Pokud načtu dávku a neuložím ji do objektu - a dám zase načíst tu samou dávku, tak vidím pak jen tu druhou, a ta první je prázdná. Což by v normálním provozu problém nebyl, protože člověk takhle dávky opakovaně nenačítá, ale na tom testu to problém je, když jich máme k dispozici tak málo.

**Comment by SykoraLukas** [comment]
Ano, je to přesně jak píšeš. Při každém vytvoření nové dávky se smaže obsah staré (pokud už existoval) a založí se nový proces se speciálním id dávky. Ve správě procesů se poté dá editovt jen ta dávka, jejíž id se shoduje s id zapsaným v souoru proarc_import.log. U ostatních dávek se hlásí, že k cesta k dávce neexistuje.

Rozumím tomu, že na testu to být problém může, ale zároveň sama píšeš, že tohle se na produkci nestane. Takže navrhuji toto issue uzavřít - protože to nemá řešení a tento stav na produkci nenastane.

**Comment by luckajirku** [comment]
no jako je to divné, že to nehodí ani žádnou hlášku.
Ale jinak k tomu testování - původně jsme si měli nahlásit, jak to chceme v těch testovacích dávkách uspořádat, které dávky, pro jednotlivé uživatele atd., což jsme udělali (https://github.com/proarc/proarc-client/issues/339). Ale ve výsledku jsi nám to tam naskládal úplně jinak, dávky dal jiné a hlavně jich je míň - 4 dávky na 4 lidi. Takže - můžeš nám tam teda prosím dát aspoň 10 různých dávek? Díky.

**Comment by SykoraLukas** [comment]
Ne, nakonec se řeklo, že to nejde kvůli místu na serveru, aby se vyhovělo všem musel by být server tak 4x větší než je současný. Jde pouze o testovací server, kde se má otestovat základní funkčnost a funkčnost nových funkcí.

**Comment by luckajirku** [comment]
tak ono kdyby se s každou novou funkcí nějakým způsobem nerozbila ta základní funkčnost, bylo by to jednodušší:-)...

**Comment by ZdenkaSera** [comment]
@luckajirku Můžeme zavřít?

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
