### ISSUE TITLE
tlačítka Přejít na předchozí/nadřazený/následující objekt

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#49]
Tlačítka Přejít na předchozí/nadřazený/následující objekt nemají být aktivní, pokud tam možnost přechodu není. Teď je to klikatelné, ale nic se nestane, ani to nevyhodí upozornění, že žádný takový objekt tam není.

**Comment by luckajirku** [comment]
Obecně s tím zviditelněním tlačítek je to v rámci celého klienta trochu zvláštní. Někdy to, že je tlačítko vysvícené, znamená, že je ta volba právě použitá, a jinde zas jsou vysvícené všechny volby, které lze použít...

**Comment by honza-rychtar** [comment]
Teď jsou tlačítka zešedlá, pokud načtený objekt už nad sebou nic nemá.
Při přechodu na předchozí/následující objekt, když už žádná před/za není, tak se zobrazí varovná hláška.
Dohodli jsme se, že společně s hláškou se i to tlačítko přechodu deaktivuje.

**Comment by luckajirku** [comment]
asi úplně nerozumím tomu chování. jsem v periodiku v ročníku, kliknu na prvním čísle na levou šipku, hodí to hlášku, že už tam nic není. ale když dojdu na poslední objekt v tom ročníku, kliknu na pravou šipku, tak to nehodí hlášku, ale otevře ten objekt. proč se to u prvního chová jinak než u posledního, když z pohledu přechodu na předchozí/následující objekt na stejné úrovni by to mělo být stejné?

**Comment by honza-rychtar** [comment]
Hotovo. 
Všechny šipky se chovají stejně - zašednou pokud není přechod umožněn.
