### ISSUE TITLE
Nelze upravit dávku po načtení ani v editaci

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#490]
Po načtení dávky není možné cokoli upravit, celé okno je šedivé:
![image](https://github.com/proarc/proarc-client/assets/8912422/87f68686-4587-4ef4-8c9a-94c91a07bab6)

Vyzkoušeno na dvou odlišných importních dávkách.
Klient: verze v2.2.1 (17.01.2024)Jádro: verze 4.1.1 - build 20240116232718, nasazeno u nás na testu.

**Comment by albertoh** [comment]
U nas na Inovatice taky to tak vidis?

**Comment by ZdenkaSera** [comment]
V KNAV se to chová maličko odlišně - je šedé všechno kromě formuláře pro změnu metadat prvního skenu. Jinak také nelze nic vybrat, označit ... Na inovatice-masteru je to ok.

![image](https://github.com/proarc/proarc-client/assets/79305516/4011b905-62d7-4174-bf16-81cdb387ff67)

**Comment by katerinasirova** [comment]
Přesně, testovala jsem v úterý na inovatice na masteru a tam se to chovalo normálně.

**Comment by albertoh** [comment]
A to se stava jen po nacteni? Kdyz jdete z "Sprava procesu" se chova dobre?

**Comment by ZdenkaSera** [comment]
Právě jsem upravila název issue, nové poznatky:
- moje dávka výše byla vybraná ze správy procesů, ne čerstvě načtená
- v úložišti v editaci po otevření je vše ok, ale pokud označím v tabulce některou stranu, všechno ostatní zašedne

**Comment by albertoh** [comment]
Divny...
Muzete, prosim, v profilu "resetovat vsechna nastaveni"?

**Comment by ZdenkaSera** [comment]
Po resetu se to chová pořád stejně.

**Comment by albertoh** [comment]
Potrebuju videt pripadne chyby v consoli prohlizece...

**Comment by katerinasirova** [comment]
U nás to vypadá takto:
![image](https://github.com/proarc/proarc-client/assets/8912422/cdc37404-66df-41b9-bbe6-70ded01aa766)

Potvrzuji, že se to děje i v úložišti, jakmile kliknu na stránky (ve smyslu obrázky). U zvukových dokumentů tj. u zvukové nahrávky se to neděje.

**Comment by albertoh** [comment]
Opraveno!
Problem byl v tom, ze na Inovatice se stranky generovaly defualtne jako ndkstrana a u vas jako strana. A byla chyba v kontrole zmen pro typ "strana", a tvarilo se to jako zmeneno.

Nahradil jsem ten zip v release. Stahnete novy a otestujte, prosim

**Comment by albertoh** [comment]
Staci zip.

Ja jsem poprosil Lukase zmenit u nas na Inovatice na stranu, abych mohl najit a opravit chybu. To je konfigurace backendu.
@SykoraLukas muzes to dat zpet na ndkstranu

**Comment by ZdenkaSera** [comment]
@albertoh K dotazu @luckajirku  - předpokládám, žes to upravil tak, aby klient správně pracoval se stranou i NDK stranou, To, jestli se při importu automaticky nastaví strana nebo NDK strana, je lokální konfigurace jádra, která se tímhle nijak nepřepíše - prosím, je to tak? Díky.

**Comment by albertoh** [comment]
Je to tak, ted by to melo fungovat pro oba modely

**Comment by ZdenkaSera** [comment]
V KNAV se to zdá v pořádku, zatím jsem nenašla protipříklad. Díky.

**Comment by katerinasirova** [comment]
U nás též otestováno na několika dávkách, chyba vypadá odstraněna.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, zatím tohle zavřu, v případě potíží znovu otevřeme, v KNAV se znovu neobjevilo.
