### ISSUE TITLE
Problémy s rychlostí klienta po nasazení na lokále

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#491]
Po nasazení nové verze na testovací server je bohužel rychlost klienta pro zpracování limitující. Na většinu úkonů čekám vteřinu až dvě než mi vůbec systém dal nějakou odezvu, že se něco děje - například chci znovu importovat nějakou dávku, kliknu na šipku obnovit v seznamu a čekám 3 vteřiny než můžu zaškrtnout dávku a pokračovat dál. Už se naštěstí neděje to, že by se objevila bílá obrazovka, místo toho tu máme lištu s průběhem akce - která se zasekne v polovině a člověk čeká a čeká, jestli se něco stane nebo ne.
Takto pomalá odezva byla i při snaze o načtení metadat z katalogu, a to jsem čekala jen na otevření okna a nabídku s výběrem katalogu, ze kterého chci stahovat. Tedy žádné úkony nad daty. A to jsem byla jediná, kdo na testovacím serveru u nás v tu chvíli v ProArcu pracoval. 
Budeme pokračovat v testování během dneška, tohle jsou první dojmy.

Protože jsme asi první, kdo novou verzi nasadil na lokál u sebe, tak mě zajímá - jak jsou na tom s rychlostí klienta ostatní?

**Comment by ZdenkaSera** [comment]
Verzi máme nasazenou, ale řešíme problém s importem, tak zatím nemůžeme otestovat proces. Při úpravě metadat v editaci se zatím velké zpomalení neprojevilo, ozveme se, jakmile dokážeme otestovat.

**Comment by ZdenkaSera** [comment]
Doplňuji po otestování - souvisí s https://github.com/proarc/proarc-client/issues/499

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, sem dávám prio, stejně tak do https://github.com/proarc/proarc-client/issues/499. Díky moc.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, můžeme tohle issue zavřít vzhledem k vývoji/testům v rámci https://github.com/proarc/proarc-client/issues/499? Přidávám návrh na zavření, ale prosím o tvé rozhodnutí, děkuji.

**Comment by katerinasirova** [comment]
@ZdenkaSera Ano, můžeme uzavřít.
