### ISSUE TITLE
Konverze svazků vícedílné monografie vytvořené ve starším standardu - lze jen na úrovni jednotlivých svazků

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#492]
Pokud exportuji vícedílnou monografii, která vznikla ve starší verzi standardu a svazky mají model "NDK svazek monografie", export (pro Krameria, archiv, NDK balíček) nelze provést, systém hlásí "Nepovolená vazba - Ndk Svazek monografie pod Ndk Vícedílnou monografii."
Pokud použiju funkci pro převod modelu NDK svazku na NDK svazek vícedílné monografie, exporty následně proběhnou.

Issue otevírám k diskusi, zda to má takto zůstat nebo máme zachovat možnost exportu původní vazby.

**Comment by ZdenkaSera** [comment]
VD s nezkonvertovanými svazky nelze ani přidělit urn:nbn

**Comment by ZdenkaSera** [comment]
Ze schůzky vývojového týmu 26.1.2024
- Výjimky z povolených vazeb mezi objekty nebudeme povolovat
- Konverze "NDK svazku monografie" zařazeného pod vícedílnou monografii na "NDK svazek vícedílné monografie" je nutná

- Funkce konverze je dostupná v úložišti pod třemi tečkami

![image](https://github.com/proarc/proarc-client/assets/79305516/c739deb0-9172-4e18-bc9a-ba17b9bb68d4)

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Tady jsem při psaní komentáře výše objevila chybu - konverze NDK svazku na NDK svazek vícedílky je dostupná pouze tehdy, když stojím přímo na svazku, tj. musela bych je převádět po jednom. 

Tohle vidím v úložišti při označeném 1 svazku:
![image](https://github.com/proarc/proarc-client/assets/79305516/f441521b-d754-4b4b-ad5b-09524e5dc142)

Na schůzce jsme omylem tvrdili, že z úrovně vícedílky lze převést všechny podřízené svazky najednou, ale funkce tu není dostupná:

![image](https://github.com/proarc/proarc-client/assets/79305516/570f8195-a349-498f-aa9b-e594c5098660)

**Comment by ZdenkaSera** [comment]
Tady jsem změnila název issue, aby odpovídal řešenému problému.

**Comment by ZdenkaSera** [comment]
Funkce převodu NDK svazku na NDK svazek vícedílné monografie je na úrovni nadřazené VD dostupná, otestujeme až lokálně, na Inovatice nemáme vhodná data.

**Comment by ZdenkaSera** [comment]
Funkce převodu NDK svazku na NDK svazek vícedílné monografie je sice dostupná na úrovni vícedílky a vydá hlášku, že převod proběhl, ale ve skutečnosti se nic nestane. (test lokálně v KNAV 2.2.4/4.1.5).
(Převod na úrovni jednotlivých svazků zůstal funkční, takže to lze obejít.)

**Comment by ZdenkaSera** [comment]
Ve verzi 4.2.3/2.3.2 stále platí, že
- funkce převodu NDK svazku monografie na NDK svazek vícedílné monografie je na úrovni VD dostupná
- po spuštění není žádná odezva, zda proces probíhá, ale po chvíli je vydána hláška, že převod proběhl - to se ale nestalo
- jednotlivé svazky lze převést
- testovací data pro master můžeme dodat v podobě archivního balíčku VD, ten se při importu do PA nekonvertuje rovnou na rozdíl od NDK PSP

**Comment by SykoraLukas** [comment]
Opraveno, k testování.

**Comment by ZdenkaSera** [comment]
Na masteru jsem našla data - a funguje! Super, moc díky. Issue zavřeme po lokálním testu.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
