### ISSUE TITLE
Chyba archivu bez surových skenů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#493]
Pokud máme v konfiguraci povolen rozšířený archivní export se surovými skeny, nejde spustit původní "prostý" archiv, i ten vyžaduje definovanou "cestu k archivním kopiím" Vyzkoušela jsem i na Inovatoce masteru na objektu 462f7106-b11d-4f08-8ffe-08a427e3d85e

![image](https://github.com/proarc/proarc-client/assets/79305516/c47fac04-8d75-42e1-a7f5-ed8a5df7597e)

**Comment by SykoraLukas** [comment]
Nasazeno na test.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV s nasazeným buildem z 20.2. - je to ok, díky.

**Comment by ZdenkaSera** [comment]
Zavírám vzhledem k testu.
