### ISSUE TITLE
Správa procesů - konflikt načítání - chybí překlad a barva ikony Stav

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#494]
Podařilo se mi nasimulovat "Konflikt načítání" - ve správě procesů chybí překlad profilu a podbarvení ikony "stav", takže je tu špatně čitelná bílá na bílém

![image](https://github.com/proarc/proarc-client/assets/79305516/69423625-8970-435e-8bcf-40d12e0d878c)

**Comment by ZdenkaSera** [comment]
Souvisí s https://github.com/proarc/proarc-client/issues/466

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Na inovatice vypadá ok, díky.
