### ISSUE TITLE
mlha po zvolení nevalidní hodnoty ve formuláři - chybí hláška

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#496]
U některých změn v popise obrazovka zesvětlá (není to ta bílá prázdná obrazovka, je to jen v mlze) a nejde nic dělat. Když dám refresh, tak se to vrátí do posledního přijatelného stavu. V případě, že je to změna v M poli (třeba u issuance) - vidím aspoň skrz mlhu, že je to pole červené a chyba bude asi tam. Ale když se ukliknu třeba u Title info - type nebo Place term - authority atp. a zvolím v rolátku místo hodnoty pomlčku, jsem v mlze - a vůbec nevím proč. Neměla by vyskočit nějaká hláška?
![mlha](https://github.com/proarc/proarc-client/assets/6359479/89df08b1-22b0-442d-a41e-2d295052f050)

**Comment by luckajirku** [comment]
tohle asi bude ten samý problém, co jsem měla tady https://github.com/proarc/proarc-client/issues/524, dám to k zavření.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
