### ISSUE TITLE
Formulář - chyby při načítání elementů

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#499]
Při testování verze v KNAV (v2.2.1 (18.01.2024)) jsme narazili na několik problémů ve formuláři. Typicky u ečlánků, ale myslím, že to platí obecně. Zkusil jsem k většině udělat video pro lepší pochopení :-)

- [x] 1) Někdy formulář nekončí a dá se scrollovat donekonečna
https://github.com/proarc/proarc-client/assets/57805328/75db0770-48c9-4331-91a7-60566986749b
- [x] 2) Někdy formulář končí, ale na konci se zasekne:  
https://drive.google.com/file/d/1pLfugMCrP37qrHDmlg01xYypkZjnYUte/view?usp=drive_link
- [x] 3) Při zobrazování jen vybraných elementů se jejich karty nezarovnávají nahoru do formuláře ale je potřeba je najít 👀 Někdy se nahoru zarovnají, ale stejně je potřeba ve formuláři vyjet až nahoru, jinak je uživatel nevidí  
https://drive.google.com/file/d/1zQ5p7sMFqnDhZuGF3HGrJ0K3Z7_B-9D9/view?usp=drive_link  
- [x] 4) Dynamické načítání elementů způsobuje, že se někdy uživatel nemůže dostat do toho elementu, který potřebuje - třeba na videu je vidět, že když si vytvořím novou kartu pro klíčové slovo, tak už ji kvůli množství dalších klíčových slov na obrazovce nevidím, když ale scrolluju dolu, skryje mi proarc všechna klíčová slova a zobrazuje další element. Jediné řešení je formulář celý oddálit, abych mohl klíčové slovo zapsat
https://drive.google.com/file/d/1_yZps6au3UetvwlWb98wZiSdLkj-Y0o3/view?usp=drive_link
- [x] 5) Při rychlém pohybu ve formuláři a přepínání mezi více objekty ve stromu se stává, že se elementy začnou načítat hodně pomalu a uživatel musí čekat, než se správná karta objeví. Stalo se nám i, že se prostě neobjevila a formulář ečlánku měl nahoře element Název místo Žánr, který nebyl k dohledání. Pomohl až refresh.

**Comment by albertoh** [comment]
Na Inovatice jsem nahral verze s vylepsenim scrollovanim.

**Comment by ZdenkaSera** [comment]
@albertoh  Na inovatice-masteru teď nelze v "zakládacím" okně zobrazit celý formulář, nutí mě vybrat si jen určitý element. Navíc výběr nefunguje - ať vyberu cokoli, stále vidím jen element název.

![image](https://github.com/proarc/proarc-client/assets/79305516/e1f4219e-05e7-41e7-9411-361ba9c912b2)

**Comment by ZdenkaSera** [comment]
Zkusila jsem tedy na https://proarc-rychlost.inovatika.dev/ - tam  si lze zapnout celý formluář, ale v zakládacím okně se nekontrolují chyby, objekt se do úložiště zapíše i s nimi. V úložišti jsem zkusila jen test, kdy vymažu rychle za sebou všechny elementy "name" - to ve verzi 2.2.1 způsobí mezeru ve formuláři a pomůže od ní refresh. tady na inovatice se to neděje - takže to vypadá nadějně. @kerschfilip

**Comment by ZdenkaSera** [comment]
Rychlé scrollování ve formuláři nahoru a dolů je taky lepší, i když posuvník stále trochu poskakuje. Ani tady ale nefunguje ideálně kontrola - při prvním uložení změny v úložišti mě upozorní na chybu. Pokud ale uložím i s ní, při další změně už mě na ni neupozorní.

**Comment by albertoh** [comment]
Problem se zakladanim objektu opraven.
https://proarc-rychlost.inovatika.dev/  byl neaktualni. Ted master a rychlost jsou stejne.

**Comment by ZdenkaSera** [comment]
> Problem se zakladanim objektu opraven.
> https://proarc-rychlost.inovatika.dev/ byl neaktualni. Ted master a rychlost jsou stejne.

To se nějak nepovedlo, za masteru to zatím je s popsanou chybou. Nepomohlo ani kompletní vymazání historie. Prosím, koukni na to ještě - díky.

**Comment by albertoh** [comment]
Uz skakuje

**Comment by kerschfilip** [comment]
@albertoh díky, vypadá to o hodně líp. Body 1, 2 a 4 jsou podle mě vyřešené. Zbytek ještě testuju. 

Zkoušel jsem to teda hlavně na proarc-master. Na proarc-rychlost je nějak rozbité to tlačítko "Zobrazit pouze element" (nezobrazuje element a když se vypne, tak už se nezobrazí celý formulář). Je tam ale nasazená nějaká starší verze oproti proarc-master... Má vůbec smysl udržovat proarc-rychlost?

**Comment by kerschfilip** [comment]
Narazil jsem ještě na jeden problém: 
- [ ] 7) V NDK Periodiku se mi nedaří přidat element pro Název - nejdřív se mi přidaný element překrývá s ostatními, potom za ním zůstane taková divná mezera: https://drive.google.com/file/d/1g1Hztr1zRFRB_k1hZQfWaR-UkM-gGmHk/view?usp=drive_link

**Comment by albertoh** [comment]
> Má vůbec smysl udržovat proarc-rychlost?
 
Nema. Zrusim

**Comment by albertoh** [comment]
Opraven problem s pridanim elementu

**Comment by ZdenkaSera** [comment]
Zkusila jsem teď na masteru (jen na monografii s dlouhým formulářem):
- Rychlé scrollování nahoru i dolů bylo plynulé, mezera vznikla za klasifikací (to místo ale nemusí být pravidlo) - ta se ale rychle doplnila, podle mého nevadí plynulosti. 
- Mazání i přidávání elementů taky ok, jen po uložení změny skončím na prázdném okně (viz níže). Data se objeví okamžitě po pohybu scrollovacím kolečkem myši, není třeba chytat svislý posuvník ani jiná operace. Nepřipadá mi to jako problém, ale nechám posouzení na zkušených uživatelích.

![image](https://github.com/proarc/proarc-client/assets/79305516/aeff9101-d923-4302-be89-31888669417b)

- Červeně označený chybný element v rozbalovací roletce je super, ale to není novinka, jen jsme to nekomentovali jako výhodu 👍 

![image](https://github.com/proarc/proarc-client/assets/79305516/f1a4b28e-e4d9-496a-8ee8-f49f963c1302)

**Comment by katerinasirova** [comment]
U nás za mě otestováno, rychlost se výrazně zlepšila, plynulost také. Jediné, co mi trochu vadí je chování při mazání elementu, které skončí, jak psala Zdena, prázdným oknem. Po scrollu myší kamkoli se vše načte, ale v první chvíli je uživatel vyděšený, že nemá žádná data. Dokážu si představit s tím fungovat, míru toho, zda nám to bude vadit bych klidně nechala na posouzení na lokálním testu, až s tím budeme pracovat víc.

**Comment by ZdenkaSera** [comment]
Na schůzce 26.3. rychlost klienta potvrzena jako ok - tedy issue zavírám.
