### ISSUE TITLE
Funkce na zobrazení fronty běžících procesů při importu

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc-client#5]

**Comment by zabak** [comment]
viz https://github.com/proarc/proarc/issues/1360 - chtělo by to stejně tak monitorovat reindexaci a exporty - mělo by být součástí klienta ale předpokládám, že to bude chtít i nějaké API na straně serveru

**Comment by SykoraLukas** [comment]
Funkce na zobrazení běžících importních procesů je nasazená na testu.

Procesy reindexace a exportů se musí dodělat.

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Prosím o vyjasnění, které issue se bude testovat.

**Comment by ZdenkaSera** [comment]
@zabak Zavírám na základě nerozporovaného návrhu na uzavření.
