### ISSUE TITLE
Import NDK balíčků do ProArcu - problémy ve správě procesů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#500]
Issue má vazbu na https://github.com/proarc/proarc/issues/1177, tam byly chyby původně nahlášeny.

Po spuštění importu NDK balíčku se nelze podívat na průběh procesu, dokud není dávka uložena. Při pokusu zobrazit např. všechny procesy ("Vše" ve filtru) opakovaně vyskakuje hláška "Importní dávku nelze editovat".

![image](https://github.com/proarc/proarc-client/assets/79305516/9ced6cef-df99-460e-8bb2-f3f1c82b1c06)

Profil v přehledu nemá label

![image](https://github.com/proarc/proarc-client/assets/79305516/16b495f7-b99d-48e8-b1ab-81dfbe70e3e3)

**Comment by ZdenkaSera** [comment]
Import NDK balíčku k e-publikacím (zatím test na e-monografii s pdf) nelze spustit bez zadaného zařízení. Tlačítko "načíst" je sice aktivní i bez zařízení, ale proces se nespustí. Zařízení by zde nemělo být vyžadováno, pro e-publikace není relevantní.

![image](https://github.com/proarc/proarc-client/assets/79305516/e045c1b1-5f14-410d-afa5-e542494f7d94)

**Comment by ZdenkaSera** [comment]
Hláška "Importní dávku nelze editovat" vyskakuje i při importu archivu.

**Comment by ZdenkaSera** [comment]
Zkusila jsem na inovatice-masteru načíst NDK PSP balíčky k NDK e-monografii a NDK svazku monografie - všechno proběhlo bez chybových hlášek. 

@albertoh 
- K e-objektům (nevím, jak ke zvukovým dokumentům) by mělo být možné načíst NDK balíček bez výběru zařízení - to teď lze 👍
- Pokud vím, pro skenované NDK dokumenty by naopak mělo být zařízení povinné pro případ díry v datech, což teď není - tuhle povinnost by to asi chtělo vrátit. že? @SykoraLukas

**Comment by SykoraLukas** [comment]
Ne, je to takto správně. U NDK dokumentů se hledám mezi všemi zařízeními. Pokud není, zařízení se založí samo a samo se přiřadí.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tak jsem tě špatně pochopila - kdybys teoreticky (standardně teď NDK balíček bez zařízení z PA ani nejde vyexportovat) měl importovat balíček, kde u žádné strany nebude zařízení vyplněno - jak se to zachová? skončí chybou a nepůjde naimportovat? Nemůže se stát, že může někdo chtít importovat k opravě NDK balíčky vzniklé v jiném programu?

**Comment by ZdenkaSera** [comment]
Dobře, my jsme se tu interně s @kerschfilip domlouvali, zda se přimlouvat za možnost importu i nějakých "nedokonalých" NDK;.-)
V tom případě za nás OK. Díky.

**Comment by SykoraLukas** [comment]
Nedokonalým NDK balíčkům bych se vyhnul, protože by např. mohl chybět mastercopy, usercopy nebo i mets. A to jsou informace, bez kterých to nejde dát dohromady.

**Comment by ZdenkaSera** [comment]
Zavírám, na případné chyby přijdeme při lokálních testech procesů po příštím releasu klienta.
