### ISSUE TITLE
Kopírování objektu - nepřevezme se date issued

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#501]
Při zkopírování objektu se nepřevzalo datum vydání - test zatím na NDK svazku monografie (v2.2.1 (18.01.2024)/4.1.1-SNAPSHOT (20.2.2024))

**Comment by ZdenkaSera** [comment]
K tomu ještě dotaz - možná je to záměr? Vzhledem k poznámce, že jde o kopírovaný objekt a je třeba změnit partnumber a date issued bych to datum čekala vyplněné. zatím tedy měním chybu na otázku, možná to je tak historicky domluvené. Díky. @SykoraLukas

**Comment by SykoraLukas** [comment]
Ano bylo to schválně. Nepředpokládá se, že kopírovaný objekt má stejné datum vydání ani partnumber, proto se doplní jen info, že je to nutné změnit, ale původní hodnoty se vymažou.

**Comment by ZdenkaSera** [comment]
@SykoraLukas S díkem a omluvou tedy zavírám.
