### ISSUE TITLE
Chybová hláška při importu NDK  monografie s přílohou

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#502]
Při načítání NDK monografie s přílohami ve formátu pro Krameria (tj. importovaná s profilem NDK Monografie Kramerius) se objevuje chybová hláška - viz níže. Dávka byla exportována z objektu s "NDK stranami", importovaná monografie má "strany". Jinak data vypadají v pořádku.

![image](https://github.com/proarc/proarc-client/assets/79305516/ba538eda-8401-48de-9169-5436b5544cb2)

**Comment by SykoraLukas** [comment]
Vyřešeno na jádře.

**Comment by ZdenkaSera** [comment]
Otestováno ve verzi 4.1.3./2.2.2 - funkční, díky.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně - zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
