### ISSUE TITLE
Export NDK PSP neproběhne a nezobrazí se ve správě procesů

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#503]
V novém klientovi nasazeném u nás na testu (Klient: verze v2.2.1 z 18.01.2024, Jádro: verze 4.1.1 - build 20240116232718) neproběhne NDK PSP export a ani se nezaloží proces ve Správě procesů. Zajímavé je, že tato chyba nastala u NDK Svazek monografie a NDK Periodikum. Modely NDK Zvukový dokument a NDK Hudebnina šly normálně exportovat a proces se založil (sice to chvíli trvalo než se zobrazil, ale povedlo se). 
Titul monografie, který mi nešel exportovat v novém klientovi, jsem se starém spustila, export proběhl v pořádku. Ve Správě procesů se zobrazil, a to jak ve starém klientovi, tak poté i v novém.

**Comment by ZdenkaSera** [comment]
@katerinasirova Zkusila jsem export NDK balíčku monografie, kterou mám naimportovanou z našeho ostrého ProArcu (tj. vznikla v nižší verzi standardu) - proběhlo dobře i v klientovi.

**Comment by SykoraLukas** [comment]
Nedaří se mi replikovat, chová se správně jak na lokálu tak na testovacím serveru. Nejšpíše bude něco u vás na serveru.

**Comment by ZdenkaSera** [comment]
@SykoraLukas bude řešit lokálně

**Comment by katerinasirova** [comment]
Při zadání exportu to hodí do prohlížeče následující chybu a proces se nenaplánuje (a stále tím pádem není v seznamu procesů):

```
main.c13f2ef088b3d65e.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'krameriusInstanceId')
    at o.onExport (main.c13f2ef088b3d65e.js:1:247467)
    at main.c13f2ef088b3d65e.js:1:246180
    at jf (main.c13f2ef088b3d65e.js:1:3565960)
    at P (main.c13f2ef088b3d65e.js:1:3566099)
    at HTMLButtonElement.<anonymous> (main.c13f2ef088b3d65e.js:1:4112808)
    at v.invokeTask (polyfills.30bd5aba77d2be79.js:1:7183)
    at Object.onInvokeTask (main.c13f2ef088b3d65e.js:1:3600257)
    at v.invokeTask (polyfills.30bd5aba77d2be79.js:1:7104)
    at M.runTask (polyfills.30bd5aba77d2be79.js:1:2578)
    at p.invokeTask [as invoke] (polyfills.30bd5aba77d2be79.js:1:8234)
```

**Comment by albertoh** [comment]
@katerinasirova  ta chyba je u nas na testu, nebo u vas lokalne?

**Comment by katerinasirova** [comment]
Chyba je u nás na lokále. Na testu u vás jsem zkoušela export naposledy při testu exportu zvukových dokumentů ještě loni. 
Mám zkusit něco exportovat na testu? 
Ale pokud si dobře pamatuji, Zdenka testovala exporty i letos kvůli něčemu jinému u nich na lokále a vše ok (viz #502).

**Comment by SykoraLukas** [comment]
Prosím o zaslání konfigu proarc.cfg pro API a globals.js pro klienta. Vypadá to na nějakou chybu v konfiguraci.

**Comment by albertoh** [comment]
Tak to je problem konfigurace backendu. Tady asi pomuze Lukas, co vam tam chybi.
Volani na API/export/kramerius4 musi vratit seznam nakonfigurovanych kramerius instance
Ja jsem opravil kod, aby nehazel chybu kdyz nejsou zadne Kramerius napojene

**Comment by svetlym** [comment]
Mám pocit, že jsme upravovali verzi resolveru, jinak se v konfiguraci nic neměnilo.

Konfigurační soubory jsem poslal mailem.

**Comment by SykoraLukas** [comment]
Nefunkční to je na verzi Klient: verze v2.2.1 z 18.01.2024, Jádro: verze 4.1.1 - build 20240116232718. Jaké verze tam byly dříve?

**Comment by SykoraLukas** [comment]
V konfiguraci jsem nenašel informace o nakonfigurovaných instancích Krameria. Můžete prosím přidat do konfigu proarc.cfg tento řádek: 
`krameriusInstances=local`

**Comment by svetlym** [comment]
Předchozí (funkční) verze byly jádro 4.1.2 a klient, myslím, v2.2.0.

**Comment by katerinasirova** [comment]
Po posílení výkonu serveru, na kterém máme instalaci PA to vypadá, že exporty fungují, jak mají. Po testování exportu různých typů dokumentů to vypadá dobře. Navrhuji tedy issue k zavření.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
