### ISSUE TITLE
Překlady typů stran

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#509]
Do rolátka u typů strany v mutaci CS/CS nechat českou verzi a do závorky za českou verzi přidat původní anglickou hodnotu.

**Comment by luckajirku** [comment]
@SykoraLukas Tohle jsme chtěli do CS/EN - nevím, jestli to chtěla i KNAV do té CS/CS, ale primárně to mělo být pro CS/EN. A tam to není (a chybí nám to, jsme zvyklí si to podle toho kontrolovat).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Doplnit do verze CS/EN

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosíme o zahrnutí do nejbližší verze. Děkujeme.

**Comment by ZdenkaSera** [comment]
Anglické názvy v závorkách jsou v CS/CS i CS/EN verzi v importu i v úložišti. Díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
