### ISSUE TITLE
Doplnit pole do formuláře pro popis čísla

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#51]
Do formuláře pro popis čísla přidat minimálně
- podnázev (Part Name)
- signatura (Shelf Locator)
- poznámka (Note) 
a hodilo by se tam mít někde zobrazené identifikátory, minimálně urn:nbn a uuid (Identifier)

**Comment by honza-rychtar** [comment]
U čísla periodika je už vše.

**Comment by luckajirku** [comment]
Za nás OK, možno zavřít.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, podle mne je tohle ok - jak to vidíš? Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Vidim, jako OK.

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, můžu to uzavřít? Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera pokud se tam od ledna, kdy jsem dala návrh na zavření, nic nezměnilo, tak ano
