### ISSUE TITLE
eČlánek - Physical description

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#512]
Prosím o úpravu formuláře pro ečlánky tak, aby bylo možné v kartě "Form" vybrat `autority` a `value` z roletek obdobně, jako ve starém rozhraní. Odstranit také kartu "Extent".

![image](https://github.com/proarc/proarc-client/assets/57805328/30570335-4e50-494b-abac-5bfcc51c8f9c)

**Comment by kerschfilip** [comment]
Otestováno, díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
