### ISSUE TITLE
panel Obrázek - nepamatuje si volbu "Přizpůsobit obrazovce"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#515]
V panelu Obrázek to doteď (asi než se začalo řešit tohle issue https://github.com/proarc/proarc-client/issues/483) fungovalo tak, že když jsem si zvolila "Přizpůsobit obrazovce", tak si to proarc pamatoval. Teď to s každým nově nakliknutým skenem zapomene, což dost zpomaluje práci.

**Comment by albertoh** [comment]
Opraveno.
Kouknete. Pokud bude ok, nahradim ten zip v release

**Comment by luckajirku** [comment]
@albertoh a kde to je prosím tě, v masteru? tam to teď nezobrazuje obrázek vůbec

**Comment by albertoh** [comment]
Mimochodem, uz neblika, a ta cara, ktera ukazuje, ze obrazek se nacita, je tam az dokonce nacitani

**Comment by luckajirku** [comment]
- jenže ten panel media je o řádek vyšší, jak má dvojitou lištu, čili mi zmenší prostor pro obrázek. 
- na načítací čára je nepříjemná, jak to tam probíhá - když pak proklikáváš při kontrole stranu za stranou... 

nejde to vrátit k tomu stavu panelů a chování, jak to bylo třeba ještě před 14 dny?

**Comment by albertoh** [comment]
Opraveno.

Nacitaci cara byla i pred tim. Jen jsem udelal, aby tam byla do te doby, nez se plne nacita obrazek. Vratil jsem to zpet, ale na chvilku ji vidim i jako pred 14 dny :)

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Alberto na schůzce opravil "zpoždění" při zobrazování obrázků a zmínil využití funkce v jádře - to bude součástí nového zipu pro release 2.2.2 nebo je dokonce zapotřebí nový zip i pro jádro 4.1.3.? Díky za upřesnění.

**Comment by luckajirku** [comment]
@albertoh máš pravdu, byla tam i předtím. ale tam se načítaly ty obrázky rychleji, takže jsme to moc neregistrovali.
Jsem pro tu poslední verzi, co je teď na masteru, nasadit u nás na PA1 a otestujeme to v běžném provozu.

**Comment by albertoh** [comment]
OK, novy zip je. @pkudela , prosim nasad u nich

**Comment by pkudela** [comment]
@luckajirku muzu nasadit ted obratem a upresni jeste jestli na proarc1, nebo proarc2, uz si to presne nepamatuju.

**Comment by luckajirku** [comment]
@pkudela PA1=proarc1:-). je to tvoje

**Comment by pkudela** [comment]
@luckajirku hotovo, nasazeno, otestovat uz musis sama

**Comment by luckajirku** [comment]
> @luckajirku hotovo, nasazeno, otestovat uz musis sama

díky, sama nemusím, je nás na to víc:-). otestováno, za nás dobrý, jste kluci šikovný

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
