### ISSUE TITLE
Přepínání z klienta do jádra (záměry) - konfigurovatelnost

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#517]
@albertoh Při přepínání z jádra do klienta se konfiguruje adresa klienta - řešili jsem zde https://github.com/proarc/proarc/issues/1643. Dokud nebude kompletně funkční zpracování záměrů v klientovi, potřebovali bychom tlačítko "Záměry" v klientovi směřovat do jádra, jinak nemůžeme klienta nasadit. Byl by možný rychlý fix do nově vydané verze 2.2.3?

**Comment by albertoh** [comment]
Ve verzi v2.2.3 je link na api. Jenom jsem nechal tam misto "záměry" "RDFlow". Nevadi?

**Comment by albertoh** [comment]
Tam je novy zip

**Comment by ZdenkaSera** [comment]
@albertoh Máme nasazenou novou verzi s fixem, ale tlačítko RDFlow je pořád rozbalovací, asi se úprava do zipu nedostala (prohlížeč kompletně resetován a promazán, tím to nebude)
![image](https://github.com/proarc/proarc-client/assets/79305516/4a3e3075-8cf4-43de-a9f6-670fe279215d)

**Comment by albertoh** [comment]
Pardon, nahral jsem zase stary zip.
Ted uz je OK

**Comment by ZdenkaSera** [comment]
Díky, zkusíme zítra a potvrdíme :-)

**Comment by ZdenkaSera** [comment]
Funguje i lokálně.
