### ISSUE TITLE
Přizpůsobení karty formuláře délce vloženého textu

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#518]
Narazil jsem na to, že při vložení delšího textu do formuláře - například abstrakt nebo poznámka - se pole formuláře neumí dostatečně roztáhnout a text začne překrývat další karty. Vyřeší se to až když kartu zavřu a znovu otevřu nebo když překliknu na jinou kartu

![image](https://github.com/proarc/proarc-client/assets/57805328/228cae97-39d6-409a-beb1-7587998ce58d)

Pokud dlouhý text z karty smažu, tak mi pod ní zůstane prázdné místo: 

![image](https://github.com/proarc/proarc-client/assets/57805328/fdb09430-080c-4e0b-a151-25ddc233d5a4)

**Comment by pkudela** [comment]
@albertoh dival jsem se na to, ale to je asi na tebe, tam se to bude muset nejak dopocitavat, ne?

**Comment by albertoh** [comment]
Uz jsem to opravil. Ale neni nasazeno

**Comment by albertoh** [comment]
Nasazeno

**Comment by ZdenkaSera** [comment]
@albertoh Prosím, je možné, žes touhle úpravou na inovatice opravil i tohle?

V KNAV se přece jen vytvářejí "díry" ve formulářích - např. toto se zobrazilo po uložení změny textu v názvu. Na inovatice-masteru jsem právě vyzkoušela totéž, tam je to bez problémů. Díky.

![image](https://github.com/proarc/proarc-client/assets/79305516/c8fc6570-7d91-42b3-b13a-5618e358ae1d)

**Comment by ZdenkaSera** [comment]
Tak úplně přece je ne - při zakládání STT monografie na masteru jsem zvolila variantu, že nechci uložit nevalidní data - tohle se mi zobrazilo (chybný element je location).
Testovací data: katalog Knihovna AV ČR monografie, sysno = 001819798)

![image](https://github.com/proarc/proarc-client/assets/79305516/e21f7ac6-40f8-4ee0-a184-19aed9aa13dd)

**Comment by ZdenkaSera** [comment]
Asi se děje to, že v zakládacím formuláři se po výmazu elementu nastaví element, který po vymazaném následuje a zafunguje ne jako informace, kde právě jsem, ale jako filtr. Tady jsem vymazala "location" a ve formuláři zůstal jen element otigininfo a nad ním i pod ním jen šedá prázndá obrazovka

![image](https://github.com/proarc/proarc-client/assets/79305516/70961753-bac5-4205-874c-59928be2af0a)

**Comment by albertoh** [comment]
Na inovatice k testu

**Comment by ZdenkaSera** [comment]
@albertoh Lepší - v zakládacím okně se mizatím nepodařilo "díru" nasimulovat. V úložišti po změně elementu ano:

![image](https://github.com/proarc/proarc-client/assets/79305516/82575363-850f-43e2-92ee-1682cba0ac15)

**Comment by ZdenkaSera** [comment]
@albertoh Nevím, jestli lze usuzovat na pravidlo, ale 2x se mi podařilo zopakovat stejný výsledek: když jsem z "hledání" rozklikla objekt a udělala v něm změnu, uložila se správně bez mezery ve formuláři. Každá další změna už mezeru vytvořila. Pokud jsem se ale vrátila do hledání a pak zpátky do editace, opakovalo se totéž - první změna bez problémů, další s mezerou. (Měnila jsem jen název - přidávala a mazala znaky).

**Comment by albertoh** [comment]
Jeste jednou

**Comment by ZdenkaSera** [comment]
Zatím se mi na masteru nepovedlo chybu nasimulovat, vypadá to slibně :-) Díky moc!

**Comment by ZdenkaSera** [comment]
@kerschfilip Zkoušela jsem na masteru i vložení dlouhého textu do poznámky  a do abstraktu - oboje ok, pole se prodloužilo a objevil se svislá posuvník. Test jen na monografii, tak případně koukni na články, pokud jsi na to narazil tam. Díky.

**Comment by kerschfilip** [comment]
Za mě je to OK

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
