### ISSUE TITLE
Opakování elementu `genre` u eČlánků a NDK eČlánků

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#519]
Při zakládání nových eČlánků a NDK eČlánků přes klienta se do MODSu zopakuje 2x element `genre`: První je výsledkem výběru mezi recenzovaný/nerecenzovaný článek. Druhý je z karty Žánr pro volbu typu článku (obálka, hlavní článek apod.):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre>electronic_article</mods:genre>
    <mods:genre type="cover">electronic_article</mods:genre>
    <mods:identifier type="uuid">6d643366-57e9-4fc6-9c9b-5bfe3db9a80d</mods:identifier>
[...]
```

Chyba je v tom, že `genre` by se měl opakovat pouze v případě, že je článek recenzovaný a je potřeba zapsat např.
```xml
    <mods:genre type="peer-reviewed">article</mods:genre>
    <mods:genre type="main article">article</mods:genre>
```

V případě, že recenzovaný článek není, měl by se vytvořit jen jeden element `genre`. První příklad by tedy měl vypadat takto:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre type="cover">electronic_article</mods:genre>
    <mods:identifier type="uuid">6d643366-57e9-4fc6-9c9b-5bfe3db9a80d</mods:identifier>
[...]
```

Zakládám to tady, protože při vytváření článků přes staré rozhraní je to v pořádku a nadbytečný element se netvoří.

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Test na Klient: verze v2.2.3 (06.05.2024)Jádro: verze 4.1.3-SNAPSHOT - build 20240503122535:

- [x] `genre` se do MODS propisuje jen jednou

Ve formuláři se to ale chová divně: 

- [ ] Kromě zaškrtávátka recenzovaný/nerecenzovaný a Genre pro typ článků se mi tam po uložení ukáže ještě jedna karta genre, která je ale zbytečná:  
![image](https://github.com/proarc/proarc-client/assets/57805328/40a71681-62eb-4476-8954-f97e0db8e870)

Stalo se mi to např. u uuid:6021dc90-2b8d-4f2f-86c0-c10f3560503c, kde jsem při zakládání vyplnil jen, že článek je nerecenzovaný a že je to anotace
- [ ] Když překliknu z nerecenzovaný na recenzovaný, neaktivuje se ikona pro uložení

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prosím, podíváš se na tohle? To bychom potřebovali doladit. Moc díky.

**Comment by albertoh** [comment]
Na testu

**Comment by kerschfilip** [comment]
v pořádku, děkuju

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by kerschfilip** [comment]
Znovu otevírám, protože ve verzi `Klient: verze v2.2.4 (11.06.2024)Jádro: verze 4.2.0-SNAPSHOT - build 20240711100059` je problém zpět:

- Založím nový eČlánek, vyberu, že je recenzovaný a že je to hlavní článek

<img width="651" alt="image" src="https://github.com/user-attachments/assets/282143fe-bb12-4369-86c1-ce3d9ac7ba10">

- Dám Vytvořit a přejít do objektu

- Překliknu, že se vlastně jedná o nerecenzovaný článek a dám uložit

- Objeví se mi karta Žánr navíc
<img width="529" alt="image" src="https://github.com/user-attachments/assets/c396de33-5830-4e48-9be3-51e09d7ee047">

**Comment by kerschfilip** [comment]
@albertoh vidím tu commit, má smysl to testovat nebo ještě ne? Děkuju

**Comment by albertoh** [comment]
Jo

**Comment by kerschfilip** [comment]
Díky, ale nějak mi to furt blbne:

Mám nerecenzovaný hlavní článek (to je OK):
![image](https://github.com/user-attachments/assets/8a10dfa3-6038-4d30-a148-e68e27cbf38f)

Zakliknu, že je recenzovaný a vyskočí mi pole žánr navíc a do XML se propíše ` <mods:genre>article</mods:genre>` :
![image](https://github.com/user-attachments/assets/b113d03b-9e7a-4676-9778-88d3e64a63e2)

----

Testuju to na masteru, tak snad je to dobře. Navíc se mi tam děje, že když dám založit nový objekt e-článek, tak se mi nenačte formulář:
![image](https://github.com/user-attachments/assets/bb7f3b66-ca74-4669-8e2d-91aa5c61a597)

**Comment by kerschfilip** [comment]
Problém s tím nezobrazujícím se formulářem u nového objektu mám i u NDK eČlánku:
![image](https://github.com/user-attachments/assets/f390ba61-30a0-46e8-b7a9-725f5565cf6a)

**Comment by albertoh** [comment]
Prosim o kontrole znovu. Pokud chovani nebude vyhovovat, muzeme si dat call

**Comment by kerschfilip** [comment]
Nyní je to OK, moc děkuju!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
