### ISSUE TITLE
Vrátit možnost popisu stran PŘED uložením do objektu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#52]
Vrátit do importu možnost popsat strany v dávce ještě před uložením do objektu (v současném tlačítko "pokračovat v tvorbě metadat"). Bavili jsme se o tom na schůzce 8. 7., ale v zápise to chybí.

**Comment by luckajirku** [comment]
Jen doplňuju, že tohle je klíčová věc. Aspoň pro nás, ale předpokládám, že i pro Jenštejn @nezbedova ?

**Comment by nezbedova** [comment]
Souhlasím s luckajirku.

**Comment by pavelkocourek** [comment]
Součástí úkolu "Importy" zahrnujícího
- dávkový import složek dokumentů určených pro zpracování
- zobrazení fronty běžících procesů a jejich stavu
- editaci strukturálních metadat před jejich načtením a uložením

**Comment by luckajirku** [comment]
> Součástí úkolu "Importy" zahrnujícího
> 
> * dávkový import složek dokumentů určených pro zpracování
> * zobrazení fronty běžících procesů a jejich stavu
> * editaci strukturálních metadat před jejich načtením a uložením

abychom se nezasekali na tom, že toho bude naráz hodně a bude to kvůli tomu dlouho trvat - tak pokud to jde oddělit, resp. dělat postupně, tak je z pohledu zpracování nejdřív třeba mít ten základ - "dávkový import složek dokumentů určených pro zpracování" + "editace strukturálních metadat před jejich načtením a uložením", bez toho se dělat nedá. 
a pak až to "zobrazení fronty běžících procesů a jejich stavu", což je skvělá věc, ale dá se bez ní pracovat, jestli to teda chápu správně, že se tím míní to, co v současném klientovi není.

**Comment by nezbedova** [comment]
V nejhorším lze odsunout i dávkový import složek. Pokud je tím myšleno to, že si označím více složek a ty najednou pošlu. Dosud je tam dáváme postupně. Ale bez `editaci strukturálních metadat před jejich načtením a uložením` nemůžeme pracovat.

**Comment by luckajirku** [comment]
Pořád nerozumím tomu, v čem nám rozdělení na dva sloupce vylepšilo práci. 
V levém sloupci si teď musím najít, ve které složce to je, potom v pravém najít správnou dávku, potom dát načíst, ale až se načte, tak z tohohle okna to neotevřu, takže musím kliknout ještě vpravo nahoře na Správu importních dávek. 
Ve stávajícím klientovi najdu dávku, dám načíst, a když je malá, hodí mě to rovnou na popis, nebo na ni přejdu buď dvojklikem nebo přes Pokračovat pořád z jedné obrazovky.

**Comment by luckajirku** [comment]
Ok, takže tohle je vyřešené.
Ještě by u těch složek bylo logické (ale to nefunguje ani v současném rozhraní, tam se taky neukáže na úrovni složky "načteno"), aby složka, kde už je vše načtené, taky zešedla.

**Comment by honza-rychtar** [comment]
> Ještě by u těch složek bylo logické (ale to nefunguje ani v současném rozhraní, tam se taky neukáže na úrovni složky "načteno"), aby složka, kde už je vše načtené, taky zešedla.

Tohle by bylo výpočetně náročné. ProArc se vždycky zeptá jen na obsah daného adresáře v rámci jedné úrovně. Takže neví, jestli už je v nějaké složce vše načteno - to by musel načíst komplet celou strukturu té složky.

Co bychom mohli udělat, je použít to samé jako u hledání - rozbalit celý podstrom od vybrané složky. Pak by už i klient znal celou strukturu a stavy všech podsložek a mohl takto probublávat stavy nahoru. 
K tomuto bychom mohli založit nové issue a tohle issue zavřít.

**Comment by luckajirku** [comment]
Jo, to rozbalení by bylo fajn, ale není to nijak akutní. Tohle můžeme zavřít.
