### ISSUE TITLE
Nezobrazují se "obrázky" v úložišti

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#522]
Test v KNAV lokálně : V poslední verzi klienta 2.2.3 se v importu zobrazují "obrázky", po uložení do objektu v úložišti už nikoli. Na horní liště běhá linka, která zřejmě signalizuje probíhající proces přípravy zobrazení, ten ale nedoběhne.
![image](https://github.com/proarc/proarc-client/assets/79305516/9e8a8635-50bb-4108-8b7c-c7f83f4fefdf)

Pokud v nastavení okna vyberu "náhledy" místo "obrázků", výsledek je správný.

![image](https://github.com/proarc/proarc-client/assets/79305516/ebf8cb71-07bc-4e65-8c59-3947b67fe785)

Dnes načtené skeny na inovatice-masteru se zobrazily bez problémů i v úložišti- prosíme o radu - můžeme mít problém v nastavení (Kakadu)? Děkuji.

**Comment by ZdenkaSera** [comment]
Obrázky se neozobrazují ani u dříve importovaných skenů, a to ani v jádře. Prosím, podívali byste se na hlášení, která @PetrKotynek vytáhl z konzole? Testy jsou z chromu. Moc děkujeme. 

[ch1.txt](https://github.com/proarc/proarc-client/files/14916723/ch1.txt)

![generovanichyby](https://github.com/proarc/proarc-client/assets/79305516/a3689f52-1ed1-4e6c-b4f5-12a7561e1e47)

**Comment by ZdenkaSera** [comment]
Test ve Firefoxu se stejným výsledkem.

**Comment by SykoraLukas** [comment]
Můžu poprosit o zaslání logů tomcatu?

**Comment by luckajirku** [comment]
@ZdenkaSera Máme v2.2.3 (04.04.2024) a 4.1.3 (Build:20240315100958) a tenhle problém nemáme (nemusíme mít taky všechno, že:-)).

**Comment by ZdenkaSera** [comment]
@luckajirku Moc díky (i když jsi mě moc nepotěšila :-))

**Comment by erikamirova** [comment]
@ZdenkaSera My máme 4.1.3/2.2.2, takže asi nepomůžeme. Ale funguje nám to. :D

**Comment by ZdenkaSera** [comment]
@PetrKotynek @SykoraLukas Hurá - Petře, díky za nápad, super - pomohlo, zatím všechny otevřené obrázky viditelné. issue zatím zavírám.
