### ISSUE TITLE
U periodik se na některých úrovních rozbila validace

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#523]
U periodik přestala na některých úrovních fungovat validace - vyskočí červené varování (toho se zbavím refreshem)
- na úrovni titulu validace ročníků nefunguje
- na úrovni ročníku validace čísel nefunguje
- uvnitř čísla validace stran OK, funguje
![rozbitavalidaceper1](https://github.com/proarc/proarc-client/assets/6359479/d99c7dda-58f6-433b-836a-7ac2a6d6c3fe)

**Comment by luckajirku** [comment]
to ještě radši upřesním, není to asi úplně jasné - vyhodnotí to jako nevalidní objekty, které jsou ale podle všeho v pořádku

**Comment by SmejkalovaAnna** [comment]
dospěla jsem včera k úplně stejnému zjištění, ještě detail - u 
![obrazek](https://github.com/proarc/proarc-client/assets/24409660/1729cf4f-bba2-4c4f-9c31-2bbb4cd6b3da)
 přidat do okna tlačítko zavřít, takto se z toho dostanu jen F5 a nijak jinak

**Comment by albertoh** [comment]
Opravil jsem chybu. Otestujte, prosim

**Comment by SmejkalovaAnna** [comment]
@albertoh Zkoušela jsem, vypadá to v pořádku.

**Comment by luckajirku** [comment]
za nás taky OK

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
