### ISSUE TITLE
nemožnost editovat pole ve formuláři

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#524]
Mám problém s editací (resp. nemožností editace) polí ve formulářích v úložišti. Změním hodnotu v nějakém poli, na obrazovku padne mlha - a nemůžu nic. Když promažu cookies atd., tak to chvíli funguje - třeba u periodik načtu dva tři formuláře, udělám pár změn, uložím, ale za chvíli jsem zas na tom samém. Mezi tím narůstá počet problémů viz obr. , jak to naroste hodně, další změnu neuložím.
Dělá mi to jak v Chromu, tak v Mozille, jak v našem PA (PA1), tak na testu (master).
![form_for_id2](https://github.com/proarc/proarc-client/assets/6359479/e3ab52fc-2aa2-4edb-8e89-8c143cb01454)

**Comment by luckajirku** [comment]
Vtipné je, že kolegyni se mlha nedělá, i když ty hlášky tam má taky. Takže otázka zní - co proti mně proarc má:-)? @albertoh @pkudela máte nějaký nápad, co můžu ještě zkusit?

**Comment by albertoh** [comment]
Zkusim najit ty problemy (Incorrect use .... )
Dela se ti to i u nas na testu?

**Comment by albertoh** [comment]
Jake mas rozlozeni obrazovky?

**Comment by albertoh** [comment]
Hlasky "Incorrect use of <label for=FORM_ELEMENT>" zpusobujou chyby v Google Material knihovne. Nemely by byt vliv na funkcnost. Doufam, ze vydaji opravu, ale problem bude, ze ikdyz oni to opravi, my asi nebudeme moct pouzivat, protoze mame starou verzi, a upgrade vyzaduje vice casu

**Comment by luckajirku** [comment]
> Jake mas rozlozeni obrazovky?

hele tohle bude asi ono - pravděpodobně to nastává, když mám "popisná metadata" otevřená ve dvou panelech současně (měla jsem to jak dole v tom prvním sloupci, tak velký formulář uprostřed. A to jsme teď zkusili, že se to pak děje i jiným, nejen mně:-)))

**Comment by albertoh** [comment]
OK, zkusim s tim se vyporadat...

**Comment by albertoh** [comment]
Uz neblokuje. Kazdopadne neni to dobry napad pro rychlosti mit dva panely s metadaty. Ale ted jde to.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
