### ISSUE TITLE
eČlánek - chyby ve validaci

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#526]
ve formuláři ečlánku se mi ve verzi v2.2.3 (18.04.2024) chybně označují jako povinné `genre` a Edition v rámci `classification`:

Genre se zobrazuje v roletce červeně, i když je to vyplněné správně, možná to souvisí s #519?:
![image](https://github.com/proarc/proarc-client/assets/57805328/5e426e19-ebb5-40d7-9533-ad89580c1efb)

V Classification prosím nastavit pole Edition jako MA. Obecně se to řešilo v #142, ale u těch ečlánků ten problém přetrval. 
![image](https://github.com/proarc/proarc-client/assets/57805328/0f387ff6-9b3f-415b-bc99-cb36153362d1)

Díky!

**Comment by SykoraLukas** [comment]
Klasifikace vyřešena.

**Comment by SykoraLukas** [comment]
Validace genre vyřešena pomocí #519

**Comment by kerschfilip** [comment]
Klasifikace OK, díky
