### ISSUE TITLE
NDK Periodikum (Standard 2.0)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#528]
- [x] mods:language:languageTerm - změnit povinnost na MA - má zůstat vynucováno uživatelem?
- [x] mods:note:type - přidat element s povinností O
- [x] mods:subject:geographicCode - změnit povinnost na R
- [x] mods:classification:edition - změnit povinnost na MA (viz. #142)
- [x] mods:location:physicalLocation:authority - změnit povinnost na O

Součást issue #527

**Comment by ZdenkaSera** [comment]
@SykoraLukas  V KNAV jsme se shodli, že prosíme zohlednit již v této verzi budoucí opravu standardu v souladu s issue https://github.com/NLCR/Standard_NDK/issues/215. Za jeho založení děkujeme.

@luckajirku Zřejmě se to teď týká hlavně vás - prosím, napiš sem, pokud byste nesouhlasili. Děkuji.

**Comment by SykoraLukas** [comment]
Ano bude, ona je chyba jen u definice toho mutačního vydání. U klasického je to v pořádku, podle něj se řídím. Jen jsem chtěl, aby opravili tu nesrovnalost, protože ani MODS standard jimi zmiňovanou strukturu nedovoluje.

**Comment by ZdenkaSera** [comment]
Zápis v issue je jen proto, aby bylo jasné, že souhlasíme, máš samozřejmě pravdu.

**Comment by ZdenkaSera** [comment]
NDK periodikum - prosíme o úpravu
- [ ] namePart:type – je MA, raději R podle nadřazeného elementu 
- [ ] roleTerm – je MA, má být R 
- [ ] physicalDescription:form:authority – je MA, má být M (jen AACR) 
- [ ] classification (value) – je M, spíše R podle celého elementu 
- [ ] classification:edition – chybí ve formuláři (jen AACR); nastavit jako MA 
- [ ] shelfLocator:url:usage – nadbytečné pole 
- [ ] recordIdentifier (value) – je MA, spíše R podle celého elementu 
- [ ] originInfo:frequency (value) – je M, spíše R podle celého elementu (jen v RDA)
