### ISSUE TITLE
V zobrazení "mřížka" nelze rozpoznat typ objektu 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#53]
V zobrazení "mřížka" nelze rozpoznat typ objektu (příloha periodika od strany).

**Comment by luckajirku** [comment]
To samé u zobrazení "náhledy".

**Comment by luckajirku** [comment]
Problém stále trvá, pořád žádná reakce už rok a půl... Jako ano, můžu používat zobrazení "tabulka", kde se dozvím, co je co, ale pokud tam jsou i další možnosti zobrazení, měly uživateli poskytovat stejné informace jako tabulka. 
Souvisí to nějakým způsobem s tímhle issue https://github.com/proarc/proarc-client/issues/86 ?

**Comment by nezbedova** [comment]
Funguje. Testováno na NDK monografie a STT.

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, můžu to uzavřít? Děkuji.

**Comment by luckajirku** [comment]
@ZdenkaSera podle přidaných screenshotů to vypadá ok, ale neověřím - přihlášení na testovací PA nám už nefunguje
