### ISSUE TITLE
NDK Článek (Standard 2.0)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#530]
- [x] mods:subject:topic - změnit povinnost na MA. Dle standardu má být M, ale bude řešeno podle komentáře @ZdenkaSera v #350:
>  Subject je R, "topic" v rámci něj je nelogicky M – navrhuji v AACR nastavit MA, ač to není v souladu se standardem (v RDA už je MA)
- [x] mods:classification:edition - změnit povinnost na MA (viz. #142)
- [x] mods:part:extent - doplnit element, chybí u AACR pravidel
- [x] mods:part:caption - odstranit element u AACR pravidel

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
Vnitřní část periodických dokumentů - prosíme o opravu
- [ ] classification (value) – je M, spíše R podle celého elementu
- [ ] classification:edition – chybí ve formuláři (jen v AACR); nastavit jako MA

**Comment by ZdenkaSera** [comment]
@SykoraLukas Test lokálně ve verzi 2.3.2. Prosím, koukl bys ještě na tohle? V prvním kole mi to uniklo :-(
- [ ] NDK standard u vnitřní části nerozlišuje descriptionStandard (jen na úrovni titulu), ale ve formulářích jej máme všude - tady se nám k AACR periodiku nabízí RDA článek (nadřazené číslo je AACR) - při založení pluskem bez užití katalogu. Stažením z katalogu lze dostat AACR
- [ ] mods:subject:topic - v AACR zůstal M místo MA (viz komentář v záhlaví)
- [ ] mods:part:extent - doplnit element, chybí u AACR pravidel
- [ ] mods:part:caption - odstranit element u AACR pravidel

**Comment by ZdenkaSera** [comment]
Zdá se to ok, díky.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
