### ISSUE TITLE
NDK Vícesvazková monografie (Standard 2.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#532]
- [x] Zvážit možnost přejmenování - dle standardu jde o Vícesvazkovou monografii v ProArcu ale pod názvem Vícedílná monografie
- [x] mods:abstract - změnit povinnost na R
- [x] mods:location:physicalLocation:authority - povinnost O

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
> * Zvážit možnost přejmenování - dle standardu jde o Vícesvazkovou monografii v ProArcu ale pod názvem Vícedílná monografie

V KNAV jsme se shodli, že můžeme přejmenovat. Jediná nevýhoda "oficiálního" názvu je, že je zase o kousek delší :-)

**Comment by ZdenkaSera** [comment]
@kerschfilip Na schůzce vývojového týmu 4.9.2024 jsme se dohodli, že to pojmenování pro tuto chvíli rozhodneš :-)

**Comment by ZdenkaSera** [comment]
@kerschfilip Na Inovatice už máme vícedílnou monografii a svazek vícedílné monografie, takže zatím vyřešeno ;-)

**Comment by kerschfilip** [comment]
> Zvážit možnost přejmenování - dle standardu jde o Vícesvazkovou monografii v ProArcu ale pod názvem Vícedílná monografie

> Na Inovatice už máme vícedílnou monografii a svazek vícedílné monografie, takže zatím vyřešeno ;-) - vlastně to tu máme ještě, ne už, ale to jsme chtěli od NK, že? :-)

Odebírám label čeká na NK. Ve standardu i dalších dokumentech (třeba katalogizace podle RDA) se pracuje s pojmem vícesvazková monografie. Pokud by se něco mělo přejmenovat, pak je to naše označení v ProArcu.

Zároveň ale nevím o tom, že by označení "vícedílná" oproti "vícesvazková" dělalo někomu problém. V rámci ProArcu jsme na to tak nějak naučení a delší popisek by mohl rozhodit roletky na některých obrazovkách. Nevidím tedy důvod k tomu to řešit a navrhuju věnovat se důležitějším věcem :-)

**Comment by ZdenkaSera** [comment]
**genre** - na úrovni vícedílné monografie stahovat jen povinný genre s hodnotou title
- tady se pořád stahují i nepovinné elementy genre, ale zatím to nebudeme rozporovat vzhledem k issue https://github.com/proarc/proarc-client/issues/506 - ve svazcích naopak chceme i nepovinné elementy a z úrovně VD by nebyly údaje k převzetí do svazku
- ověříme, zda projde validátorem
