### ISSUE TITLE
NDK Svazek Vícesvazkové monografie (Standard 2.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#533]
- [x] mods:abstract - změnit povinnost na R
- [x] mods:location:physicalLocation:authority - povinnost O

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
@SykoraLukas Aby bylo názvosloví konzistentní, měl by se NDK svazek vícedílné monografie spíše  jmenovat NDK svazek vícesvazkové monografie.

**Comment by SykoraLukas** [comment]
Upravim.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosíme opravit:
- [ ] OriginInfo:dateIssued:value - je MA, má být M
- [ ] physicalDescription:form:authority (jen AACR) - je MA, má být M
- [ ] recordIdentifier (value) – je MA, má být R
- [ ] location:physicalLocation:url – ve formuláři je navíc navíc pole usage
- [ ] relateditem:type – v roletce nejsou všechny povolené hodnoty

**Comment by ZdenkaSera** [comment]
Komentář k názvu zde https://github.com/proarc/proarc-client/issues/532#issuecomment-2334002353, zůstaneme u NDK svazku vícedílné monografie.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tyhle změny se zatím nepromítly do verze k testu - test 6.11.2024 na masteru. Prosím, koukneš na to? Děkuji.

**Comment by ZdenkaSera** [comment]
Zdá se ok, díky.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
