### ISSUE TITLE
NDK Svazek monografie (Standard 2.1) 

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#534]
- [x] mods:genre:authority - odstranit element
- [x] mods:abstract - změnit povinnost na R
- [x] mods:location:physicalLocation:authority - povinnost O

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosíme opravit:
- [ ] recordIdentifier (value) – je MA, má být R
- [ ] location:physicalLocation:url – ve formuláři je navíc navíc pole usage
- [ ] relateditem:type – v roletce nejsou všechny povolené hodnoty

**Comment by SykoraLukas** [comment]
@ZdenkaSera prosím o dodání českých překladů pro `relatedItem:type`.

- isReferencedBy
- preceding
- succeeding
- host
- constituent
- otherVersion
- otherFormat
