### ISSUE TITLE
NDK Kartografický dokument (Standard 2.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#535]
- [x] mods:titleInfo:partNumber - změnit povinnost na MA
- [x] mods:titleInfo:partName - změnit povinnost na MA
- [x] mods:name:type - změnit povinnost na MA
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:classification:edition - změnit povinnost na MA (viz. #142)
- [x] mods:location:physicalLocation:authority - změnit povinnost na O

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
NDK Kartografický dokument - prosíme o opravu.

- [ ] placeTerm:autority – je MA, má být M (AACR)
- [ ] originInfo:dateissued (value) -  je MA , má být M
- [ ] physicalDescription: form: authority – je R má být M (AACR)
- [ ] subject:name:namePart – je MA, má být M (nerozporujeme vzhledem k povinnosti R na úrovni name))
- [ ] classification:edition – chybí ve formuláři AACR; má být M, ale nastavit jako MA (povinné jen někdy)
- [ ] classification:value – je M, raději R podle celého elementu
- [ ] identifer:type – je MA, má být M
- [ ] location:url:usage – je ve formluáři zbytečně, standard nezmiňuje
- [ ] part:detail – ve formuláři chybí jako nadřazený pro caption (do xml se ale doplňuje správně, takže nerozporujeme)
- [ ] recordInfo:descriptionStandard -  je MA, má být M
- [ ] recordIdentifier:encoding – správně není ve formuláři, to je chyba standardu a nemá tady ani co dělat (asi kopie pole z datecreated/changed)
- [ ] recordIdentifier (value) – je MA, má být R
- [ ] languageOfCataloging – ve formuláři není, ale do xml se dotahuje (nerozporujeme)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tady jsem ještě zapomněla komentář - chápala jsem tohle issue tak, že opravdu jde o samostatný kartografický dokument (genre = "cartographic) Mapa by pak měla být jen speciálním případem vnitřní části dokumentu (genre = picture, type = map). Pokud se nemýlím, prosím, zvaž přejmenování tohoto issue. Moc díky.

**Comment by SykoraLukas** [comment]
> recordIdentifier:encoding – správně není ve formuláři, to je chyba standardu a nemá tady ani co dělat (asi kopie pole z datecreated/changed)

Neřeším.
