### ISSUE TITLE
NDK Kapitola (Standard 2.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#538]
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:classification:edition - změnit povinnost na MA (viz. #142)

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
NDK Kapitola - prosíme opravu
- [ ] titleInfo:type – podle standardu se zde nepoužívá, ve formuláři je navíc
- [ ] classification:edition – chybí v AACR, přidat s povinností MA
- [ ] recordInfo:recordChangeDate:encoding – je R, má být M
- [ ] genre:type  - v roletce pro typ kapitoly (chapter) chybí "unspecified"

Další rozdíly oproti standardu nerozporujeme
- [ ] subject:topic – je MA, má být M (vzhledem k povinnosti subjectu R ok)
- [ ] subject – ve formuláři nastaven jako v monografii (nerozporujeme)
- [ ] recordInfo:descriptionstandard - – ve standardu není
- [ ] recordInfo:Record identifier – ve standardu není

...
