### ISSUE TITLE
Při výrazném zúžení levé strany zmizí část lišty

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#54]
Při výrazném zúžení levé strany zmizí část lišty (Vytvořit nový objekt, Změna pozice, Přesunout vybrané objekty, Smazat vybrané objekty a Uložit).

**Comment by honza-rychtar** [comment]
Od určité velikost se tam vše nevejde. Otázka co s tím. Buď to zalomit nebo nezobrazovat. Případně nedovolit tak velké zmenšení.

**Comment by luckajirku** [comment]
Určitě ZALOMIT. Nezobrazovat je nesmysl. Resp. jednoho adepta na "Nezobrazovat" mám - jedno místo vyšetříš, když vyhodíš tu fajfku, co přepíná hromadný/jednoduchý výběr. Její přínos jsme nepochopili - přepne se to tím, že označím víc jak jednu stranu, nepotřebuju předtím ještě klikat na tlačítko.

**Comment by tumovam** [comment]
14.9. - nyní se zalamuje
