### ISSUE TITLE
NDK Příloha monografie (Standard 2.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#540]
- [x] mods:name:type - změnit povinnost na MA
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:originInfo:frequency - změnit povinnost na RA
- [x] mods:classification:edition - změnit povinnost na MA (viz. #142)

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
NDK příloha monografie - prosíme o úpravu
- [ ] dateCreated:qualifier – chybí ve formuláři (v AACR), povinnost R
- [ ] physicalDescription:form:authority – má být M, je MA (platí v AACR)
- [ ] classification:edition – není ve formuláři (v AACR)
- [ ] dateOther:qualifier – chybí ve formuláři (v RDA), povinnost R
- [ ] physicalDescription:form:type – má být M (v RDA)
- [ ] recordInfo:descriptionStandard – je MA, má být M
- [ ] subject:name:namePart – je MA, má být R
- [ ] originInfo:frequency  - v RDA chybí ve standardu, což je spíše chyba; ve formuláři je, nerozporujeme to
- [ ] recordInfo:record identifier – ve standardu není, z formuláře netřeba mazat (je s povinností R)
