### ISSUE TITLE
NDK ePříloha Monografie (Standard 2.3)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#543]
- [x] mods:name:namePart - změnit povinnost na M
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:name:affiliation - přidat element s povinností O
- [x] mods:classification - přidat element s povinností R

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by tumovam** [comment]
NDK Příloha eMonografie lze vytvořit pouze přes Nový objekt. 
NDK Příloha eMonografie nejde vytvořit ve struktuře (bývalé Vazby), chybí v roletce u NDK Svazku eMonografie.

_Testováno na masteru ve v2.3.x-dev (04.12.2024)._

**Comment by SykoraLukas** [comment]
Doplněno. K testu.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
