### ISSUE TITLE
NDK ePeriodikum (Standard 1.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#544]
- [x] mods:name:namePart - změnit povinnost na RA
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:note - změnit povinnost na RA

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by ZdenkaSera** [comment]
NDK ePeriodikum - prosíme o úpravu:
- [ ] location:physicalLocation:authority - nyní MA, ve std. M
- [ ] location:shelfLocator:value - M, ale celý element MA
- [ ] recordInfo:recordIdentifier - nyní R, ve std. M
- [ ] recordInfo:recordIdentifier:recordIdentifier - nyní MA, ve std. M
- [ ] recordInfo:languageOfCataloging - R, chybí
- [ ] recordInfo:languageOfCataloging:languageTerm - R, chybí
- [ ] subject:name:namePart - nyní RA, ve std. R (nerozporujeme)
- [ ] subject:name:nameIdentifier - nyní MA, ve std. RA (nerozporujeme)
- [ ] genre - předvyplněno electronic_title (nově by mělo být bez podtržítka)

**Comment by ZdenkaSera** [comment]
U signatury je uvedena povinnost M u řádky pro vložení hodnoty. Celý element sice může zůstat prázdný a nekřičí to jako chyba, v elementu location, ale je to trošku matoucí

![image](https://github.com/user-attachments/assets/a284f9ef-a89f-4ddf-b66e-ac95c1442c82)

**Comment by SykoraLukas** [comment]
Takže mám změnit `Value` na MA?

**Comment by ZdenkaSera** [comment]
Promiň - ano, MA. Díky.

**Comment by tumovam** [comment]
- [ ] originInfo:issuance - v roletce chyba Integrationg resource, správně Integrating resource (verze CS/EN i EN/EN)
- [ ] titleInfo:title:type - chybí type "abbreviated"

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
