### ISSUE TITLE
NDK eČíslo Periodika (Standard 1.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#546]
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:location:physicalLocation:authority - změnit povinnost na M

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by tumovam** [comment]
- [ ] name:note - úplně chybí (Poznámka, sloužící k doplnění kontaktu na autora, například e-mailové adresy)
- [ ]  genre:value - předvyplněno electronic_issue (má být bez podtržítka)
- [ ]  originInfo:place:placeTerm:type - nyní M, ve std. O (neřešila bych)
- [ ]  originInfo:place:placeTerm:authority - nyní MA, ve std. O (neřešila bych)
- [ ]  subject:name:namePart - nyní MA, ve std. M (neřešila bych)
- [ ]  subject:name:nameIdentifier - nyní MA, ve std. RA (neřešila bych)
- [ ]  recordInfo - nyní M, ve std. MA
- [ ]  Record info:record identifier - myslím, že je navíc

**Comment by SykoraLukas** [comment]
Name:note je chyba standardu, viz https://github.com/NLCR/Standard_NDK/issues/189 kde jsme to řešili s NK

**Comment by SykoraLukas** [comment]
Opraveno, nasazeno. K testování.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
