### ISSUE TITLE
NDK eČlánek (Standard 1.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#547]
- [x] mods:name:namePart - změnit povinnost na M
- [x] mods:name:namePart:type - změnit povinnost na MA

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by tumovam** [comment]
@SykoraLukas předem se omlouvám, bude toho víc i v dašlích issues...

- [ ] titleInfo:title:type - chybí type "abbreviated"
- [ ]  genre:value - předvyplněno electronic_article (mělo by být bez podtržítka)
- [ ]  subject:name:nameIdentifier - nyní MA, ve std. RA (neřešila bych)
- [ ]  name:note - úplně chybí (Poznámka, sloužící k doplnění kontaktu na autora, například e-mailové adresy)
- [ ]  recordInfo - nyní M, ve std. MA (neřešila bych)

**Comment by SykoraLukas** [comment]
Name:note je chyba standardu, viz https://github.com/NLCR/Standard_NDK/issues/189 kde jsme to řešili s NK

**Comment by tumovam** [comment]
@SykoraLukas aha, to jsem nevěděla. Díky! V tom případě v pořádku, příp. kontakt (e-mail) se bude psát do affiliation.

**Comment by SykoraLukas** [comment]
Nasazeno k testování.
