### ISSUE TITLE
NDK ePříloha Periodika (Standard 1.1)

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#548]
- [x] mods:name:namePart - změnit povinnost na M
- [x] mods:name:namePart:type - změnit povinnost na MA
- [x] mods:classification:edition -  změnit povinnost na MA (viz #142)

Součást issue https://github.com/proarc/proarc-client/issues/527

**Comment by tumovam** [comment]
- [ ] titleInfo:title:type - v roletce chybí type "abbreviated"
- [ ] genre:value - předvyplněno electronic_supplement (má být pouze **supplement**)
- [ ] originInfo:dateIssued:point - v PA navíc, není ve std.
- [ ] subject:name:nameIdentifier - nyní MA, ve std. RA (neřešila bych)

**Comment by tumovam** [comment]
NDK Přiloha ePeriodika lze vytvořit pouze přes Nový objekt. NDK Přiloha ePeriodika **nejde vytvořit ve struktuře** (bývalé Vazby), chybí v roletce u NDK eČísla. 
_Testováno lokálně i na masteru ve v2.3.2._

**Comment by SykoraLukas** [comment]
Opraveno, nasazeno. K testování.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
