### ISSUE TITLE
hromadný výběr - po o(d)závorkování pořád běhá modrá čára

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#549]
Už nějakou dobu se děje u hromadného výběru tohle:
označím strany, dám ozávorkovat (nebo odzávorkovat) - změna se sice provede hned, ale u formuláře pořád běhá ta modrá čára, dokud někam nekliknu a tím ten výběr nezruším. 
Asi je PA zmatený, že se tady nepotvrzuje uložení disketou, tak mu to asi musíš @albertoh vysvětlit, že to udělal správně a že po provedení změny může přestat běhat:-).   
![poradbeha](https://github.com/proarc/proarc-client/assets/6359479/7e36b364-d77b-413e-9901-e19bc6c28418)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
