### ISSUE TITLE
Hromadné označování - pamatuje si pozici i po zrušeném výběru

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#55]
Při hromadném označování obrázků si klient pamatuje pozici posledního nakliknutého i při zrušení výběru. Při dalším hromadném označení pak začíná z této zapamatované pozice. Problém to působí při kliknutí na jednoduchý výběr, kdy z dříve označených zůstane označený pouze první, ale další označování probíhá od posledního dříve nakliknutého.

**Comment by hosak** [comment]
Stav k 14.9.2020:
Pořád při starém, problém přetrvává.

**Comment by luckajirku** [comment]
Při testování tohohle narážím na věci, které mi nedávají smysl. Označím jednu stranu. Dám “vybrat vše”. Rozmyslím si to a kliknu na “Jednoduchý výběr”. Hodí mě to na poslední stranu, kterou jsem měla označenou před tím, než jsem dala “vybrat vše”. 
Schválně?

**Comment by luckajirku** [comment]
Vzhledem k tomu, že se opravuje bez komentářů, tak nevím, jestli to takhle fungovat má a jestli to, že ta strana se teď viditelně označí, má být ta oprava problému. Opravdu by dost ulehčilo testování a ušetřil by se čas, kdyby v issues probíhala nějaká komunikace.

**Comment by luckajirku** [comment]
Nemá smysl testovat, dokud nebude hotovo https://github.com/proarc/proarc-client/issues/76

**Comment by honza-rychtar** [comment]
#76 už je ohotové.

**Comment by luckajirku** [comment]
Vypadá to OK, asi se může zavřít.
