### ISSUE TITLE
WorkFlow - založil záměr

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#552]
Přidat sloupec na to, kdo založil záměr.

**Comment by SykoraLukas** [comment]
Na API hotové. Nutné přidat nový sloupec ownerName, který se zobrazuje, ale filtruje se podle hodnoty ownerId.

**Comment by albertoh** [comment]
Hotovo

**Comment by nezbedova** [comment]
Funguje. Ve sloupci lze filtrovat.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
