### ISSUE TITLE
WorkFlow - mazání záměrů

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#553]
Vytvořit novou schopnost uživatele mazat záměry.

Obdobně jako je možnost "Smí spouštet převody modelů" bude "Smí mazat záměry".

V RDflow založit novou funkci mazat Záměry. Smažou se všechny úkoly záměru (podzáměru), všechny podzáměry a samotný záměr.

**Comment by SykoraLukas** [comment]
Na API je hotové.

```
### DELETE JOB
DELETE {{proarcLocalHostUrl}}/rest/v2/workflow?id=16
Content-Type: application/json
```

id může být i array hodnot pro jobId.

Nutné nejprve zkontrolovat, že uživatel má roli `wfDeleteJobFunction=true`, až poté mu zobrazit funkci na mazání záměrů. Po stisknutí tlačítka `Smazat záměr` ještě zobrazit vyskakující okno a nechat to ještě jednou potvrdit. Jedná se o funkci, kterou nelze vrátit, proto je lepší mít 2x potvrzeno, že se má smazat.

Vyvíjet ve větvi visk2024-beta ať se to neplete s formuláři, které budou vydány nejdříve.

**Comment by SykoraLukas** [comment]
Do uživatelského profilu přidat novou hodnotu pro mazání záměrů ve WorkFlow viz starý klient.

**Comment by albertoh** [comment]
Pridano

![image](https://github.com/proarc/proarc-client/assets/5946836/fc64b965-bb2e-4ab2-8f48-c94bac1241c8)

**Comment by SykoraLukas** [comment]
K testování.

**Comment by nezbedova** [comment]
Funguje. Po jednom i hromadné mazání záměrů.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
