### ISSUE TITLE
WorkFlow - základní nastavení sloupců

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#554]
Doplnit, o které sloupce máme zájem.

**Comment by SykoraLukas** [comment]
Srovnat jména podle abecedy
Doplnit všechny sloupce

Defaultní nastavení sloupců: signatura, čarovy kod, nazev

**Comment by albertoh** [comment]
> Srovnat jména podle abecedy
Ma smysl? Uzivatel m,uze menit poradi sloupcu...

> Doplnit všechny sloupce
Aktualne: 'signature', 'barcode', 'label', 'rawPath', 'profileName', 'state', 'taskName', 'taskUser', 'priority', 'created', 'edition', 'field001', 'financed', 'id', 'model', 'modified', 'ownerId', 'pid', 'sigla', 'year', 'deviceLabel'
Prosim o doplneni/odstraneni

> Defaultní nastavení sloupců: signatura, čarovy kod, nazev
Hotovo

**Comment by nezbedova** [comment]
@albertoh Bylo myšleno seřazení  podle abecedy v roletce pro výběr. 
Tady:

![obrazek](https://github.com/user-attachments/assets/a22a8a46-8113-48ed-b1f5-c88f2392d46a)

**Comment by nezbedova** [comment]
@albertoh Teď mám správnou roletku, přímo od Vás.

První tři řádky prosím nechat nahoře. Ostatní srovnat podle abecedy.

V roletce chybí na výběr, prosím přidat:

Číslo
Detail
Datum dok. úkolu
Poznámka
Ročník
Vytvořeno

A na ten samý řádek před slovo "úkol" přidat slovo "Dokončený"

![obrazek](https://github.com/user-attachments/assets/fd0893a9-9ef0-4c30-9c87-3a31571013be)

**Comment by albertoh** [comment]
Ja muzu na zacatku seradit, ale potom kazdy muze to zmenit, posouvat na horu - dolu.
 Proto nevim jestli ma smysl seradit. To bych musel seradit zvlast cesky a anglicky podle popisku, ale jen pokud se neco nezmenilo...

**Comment by albertoh** [comment]
Jsem to vyresil tak, ze na zatacku jsou vybrana pole, v tom poradi jak uzivatel posouva, a potom neviditelne sloupce serazene abecedne.

**Comment by nezbedova** [comment]
Teda! To je rychlost a je to krásné a přehledné. Děkuji.

**Comment by nezbedova** [comment]
Ještě prosím přidat na výběr chybějící sloupce. Je to výše, ale aby to nezapadlo. Děkuji.

V roletce chybí na výběr, prosím přidat:

Číslo
Detail
Datum dok. úkolu
Poznámka
Ročník
Vytvořeno

**Comment by albertoh** [comment]
Ony jsou tam.

![image](https://github.com/user-attachments/assets/44e02251-06c3-49f7-880a-0841709638c6)

 Je nutne smazat local storage, aby se dostaly zakladni nastaveni

![image](https://github.com/user-attachments/assets/8bdeb715-9c5a-478c-9de8-1d0f8ca58eaa)

**Comment by nezbedova** [comment]
Děkuji za upozornění a za opravu.

Bylo by možné, aby si sloupce pamatovaly šířku, kterou jim nastavím nebo si s tím musím vždy šoupat?

**Comment by nezbedova** [comment]
Prosím přidat chybějící i do dolního okna, kde je strom.

![obrazek](https://github.com/user-attachments/assets/cc843ae7-2ff9-47c6-b8fb-ea98305f5d15)

**Comment by albertoh** [comment]
Sloupce pridane (nutno smazat cache)
Sirky uz se pamatovavaji

**Comment by nezbedova** [comment]
V obou oknech je v roletce 2x Rok. 

![obrazek](https://github.com/user-attachments/assets/7dd2e7ce-5fd8-4c53-9db9-1d823c6703ae)

**Comment by albertoh** [comment]
Opraveno

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto ve výběru sloupců chybí položka "číslo" - je to číslo buď výtisku nebo číslo svazku vícedílky, prosím doplnit!

**Comment by albertoh** [comment]
Rekl bych, ze musis smazat cache.
Prehazovat sloupce jde ve okne vyberu sloupcu

**Comment by SmejkalovaAnna** [comment]
@albertoh super, je to tam, díky!

**Comment by nezbedova** [comment]
Funguje. Děkuji

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto prosím tě, bylo by možné, aby ve sloupci Financováno, filtr ignoroval velká a malá písmena? V signatuře to funguje... díky!

**Comment by albertoh** [comment]
To je vec backendu... @SykoraLukas muze to byt?

**Comment by SykoraLukas** [comment]
Založte k tomuto issue na jadru. Zde tedy můžeme pak zavřít.

**Comment by SmejkalovaAnna** [comment]
Založeno, zavírám.
