### ISSUE TITLE
WorkFlow - zachování sloupců 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#555]
Upravit v RDflow zachování sloupců jako to je u Zachovani sloupcu (#10) proarc/proarc#36

Nebo je možné nastavit sloupce v jednotlivých institucích? Např. v DC používají jednotlivci většinu sloupců stejných, jen občas si někdo některý přidá nebo odebere. Přednastavené sloupce nám nevyhovují.

**Comment by SykoraLukas** [comment]
Představa je přednastavený set sloupců, které si uživatel bude moct ve svém profilu měnit (podobně jako u hledání -> zobrazí si jen ty, které ho zajímají).

**Comment by albertoh** [comment]
Hotovo

**Comment by SmejkalovaAnna** [comment]
@albertoh nastavení sloupců už je dobré, ale proč mi nejde zúžit úplně ten levý sloupec? Přehazovat sloupce nejde a ten první Signatura je zbytečně široký a nejde zúžit....jde s tím něco dělat? Zúží se jen když šoupnu prostřední čárou - resp. protáhnu celé pravé okno, ale to se  mi zúží i sloupec se jménem, který zase potřebuji většinou širší

**Comment by SmejkalovaAnna** [comment]
@albertoh Alberto ve výběru sloupců chybí položka "číslo" - je to číslo buď výtisku nebo číslo svazku vícedílky, prosím doplnit!

**Comment by albertoh** [comment]
Rekl bych, ze musis smazat cache.
Prehazovat sloupce jde ve okne vyberu sloupcu

**Comment by SmejkalovaAnna** [comment]
@albertoh přehazovat sloupce jde, super, ale ten levý sloupec se prostě nezmenší když chci, skáče to pořád zpátky

**Comment by nezbedova** [comment]
Funguje.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
