### ISSUE TITLE
RDflow - doplnění popisu na Github

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#556]
Na stránkách s návodem https://github.com/proarc/proarc/wiki/Popis-workflow.xml#definice-profilu-zpracov%C3%A1n%C3%AD-job
je sice návod jak zprovoznit rozbalovátko "Vytvořit nový záměr" <model pid="model:monograph" />
ale není to v ukázkovém xml, které na těchto stránkách je.
Také tam chybí možnost stáhnout si validátor doplněný o tuto změnu.

**Comment by SykoraLukas** [comment]
Na odkazu výše je aktuální dokumentace. Navrhuji tedy toto issue zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
