### ISSUE TITLE
RDFlow - Filtr Úkolu podle pracovníka - "prázdný"

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc-client#557]
Bylo by užitečné, kdyby mezi hodnotami, které lze označit checkboxem byl i "prázdný", abych si mohla vyfiltrovat úkoly, které jsou buď zadané přímo mě nebo ještě nepřiřazené apod.

**Comment by nezbedova** [comment]
Momentálně úkoly nepřiřazujeme. Navrhuji zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
