### ISSUE TITLE
Sloupce a jejich obsah

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#56]
Reálně chybí jedno okno, v současném ProArcu je vlevo nahoře struktura, vlevo dole metadatový popis, uprostřed jsou náhledy všech stran a vpravo větší náhled označené strany. VŠE SE POUŽÍVÁ. V novém klientovi jsou dvě nastavitelná okna, která ovšem mají smysl pouze pokud je levé nastaveno na režim procházení, v režimu detailu se obě okna změní v kopie jedna druhého. Tlačítko “Otevřít obrázek v novém panelu” sice vyvolá panel náhledu, ten ale zmizí při nakliknutí více objektů, nebo při nakliknutí jiného objektu, než je strana (příloha, kapitola…) a po kliknutí zpět na stranu je třeba jej znovu otevřít.
Co se týká prvního (levého) sloupce, nedává moc smysl mít tam možnost překliknout na něco jiného než strukturu, ta se používá vždy. Druhé dva ať jsou potom volitelné.

**Comment by luckajirku** [comment]
problém s mizením třetího panelu řešen tady: https://github.com/proarc/proarc-client/issues/67

**Comment by luckajirku** [comment]
Chybí tam další možnosti u využití třetího panelu. Teď se v novém klientovi dá zapnout jen pro náhled skenů při popisu stran, ale ve stávajícím klientovi šel využít i pro jiné editory. Dost využívané je např. vidět současně popis ve formuláři a v xml - ve stávajícím klientovi ta možnost je, v novém jde mezi nimi jen přepínat, ale ne je vidět současně.

**Comment by honza-rychtar** [comment]
> Chybí tam další možnosti u využití třetího panelu. Teď se v novém klientovi dá zapnout jen pro náhled skenů při popisu stran, ale ve stávajícím klientovi šel využít i pro jiné editory. Dost využívané je např. vidět současně popis ve formuláři a v xml - ve stávajícím klientovi ta možnost je, v novém jde mezi nimi jen přepínat, ale ne je vidět současně.

Přidal jsem do toho třetího panelu zobrazení MODS XML.
Takže se tam dá volit mezi obrázkem a xml. 
To xml jde zobrazovat nejen u stránek, takže je teď třetí panel dostupný u všech modelů v režimu procházení, ale u ne-stránek je tam možné zobrazit jen xml a zapamatované volby (zobrazovat 3. panel?, co zobrazovat v třetím panelu) jsou různé pro stránky a zbylé objekty.

**Comment by luckajirku** [comment]
Za nás OK, možno zavřít.
