### ISSUE TITLE
zvukový dokument i skladba - validace hlásí chybu u physical description

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#560]
Pravděpodobně s úpravou nových verzí DMF se jako nevalidní jeví element ```physical description```, i když má všechny údaje vyplněné stejně jako dříve (před úpravou).
U hodnot "sound recording" a "sound disc" se žádný type neuvádí.

**NDK Zvukový dokument**
![image](https://github.com/proarc/proarc-client/assets/8912422/9120306e-db21-41df-a8c8-8455163a303a)

 ```
<mods:physicalDescription>
        <mods:form authority="marccategory">sound recording</mods:form>
        <mods:form authority="marcsmd">sound disc</mods:form>
        <mods:form type="media" authority="rdamedia">audio</mods:form>
        <mods:form type="carrier" authority="rdacarrier">audiodisk</mods:form>
        <mods:extent>1 gramofonová deska ;  25 cm</mods:extent>
    </mods:physicalDescription>
```

**Skladba:**
![image](https://github.com/proarc/proarc-client/assets/8912422/a9718484-ac6c-450b-b1d4-811317e77e5b)
```
<mods:physicalDescription>
        <mods:form authority="marccategory">sound recording</mods:form>
        <mods:form authority="marcsmd">sound disc</mods:form>
        <mods:form type="media" authority="rdamedia">audio</mods:form>
        <mods:form type="carrier" authority="rdacarrier">audiodisk</mods:form>
        <mods:extent>1 gramofonová deska ;  25 cm</mods:extent>
    </mods:physicalDescription>
```

**Comment by tumovam** [comment]
@katerinasirova měli jste čas testovat? Děkuji

**Comment by katerinasirova** [comment]
Otestováno, funguje. Navrhuji na zavření.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
