### ISSUE TITLE
Neúplné zobrazení elementu name ve formuláři při stažení jmenné autority z NK

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#561]
Znovu jsem otestovala stahování jmenných autorit z NK - lokálně v KNAV (v 4.1.4./2.2.3) funguje, ale kromě dlouhé doby do zobrazení dat (cca 10 vteřin) zlobí i formulář: zobrazí se vyplněná jen část s name parts (v xml je uloženo včetně data a identifikátoru). Zbytek přidaného elementu name zobrazí až refresh.

![image](https://github.com/proarc/proarc-client/assets/79305516/b45aa190-42f1-4b6b-99bf-4e3a14d2cb2f)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
👍 super - nejenže se zobrazila všechna pole, ale data se na inovatice-masteru zobrazila okamžitě. Díky.
