### ISSUE TITLE
MultiSelect v obrazovce Hledat

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#564]
V obrazovce hledat dovolit multiselect více objektů. 

Po zakliknutí bude možné objekty exportovat, smazat a přidělit UNR:NBN

**Comment by ZdenkaSera** [comment]
Souvisí i s https://github.com/proarc/proarc-client/issues/389

**Comment by kerschfilip** [comment]
omlouvám se za hloupý dotaz, ale jak funguje ten multiselect? myslel jsem, že prostě zakliknu víc objektů když držím shift, jako to funguje běžně včetně starého rozhraní, ale to mi nějak nejde, díky

**Comment by kerschfilip** [comment]
abych to upřesnil tak, s ctrl ty objekty vybrat hromadně zvládnu, se shiftem to jde, ale vypadá to divně (označí se  mi zároveň text):
![image](https://github.com/user-attachments/assets/8b5a1d80-879b-4b50-b064-5e14d4e83d5c)

Ale funguje to jen v té horní polovině okna, ve spodní ne.

**Comment by albertoh** [comment]
Opraveno. Da se hromadne vybirat i dole

**Comment by kerschfilip** [comment]
je to tak, díky :-)

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
