### ISSUE TITLE
WorfkFlow - editované pořadí sloupců

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#566]
Umožnit přesouvání sloupců  / u každého si nastavit pořadí

**Comment by albertoh** [comment]
Hotovo

![image](https://github.com/user-attachments/assets/75d871cf-b0a2-462b-b91f-b7760d9e7bb1)

Pro poradi lze posunout sloupce ve okne vyberu

![image](https://github.com/user-attachments/assets/8a0bd0fe-7f0a-4641-b1a7-be0007dc242e)

**Comment by nezbedova** [comment]
Jako výchozí prosím nastavit abecedu. Děkuji.

**Comment by nezbedova** [comment]
Otestováno. Funguje. Je to moc pěkné.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
