### ISSUE TITLE
WorkFlow - přidat krok v úkolech

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#567]
Nad úkoly ve WorkFlow přidat možnost "Přidat krok", který se přidá na lištu záhlaví Úkolů.

**Comment by albertoh** [comment]
Hotovo
![image](https://github.com/user-attachments/assets/a2e74eb9-c541-4a40-9810-40500535be1e)

**Comment by nezbedova** [comment]
Otestováno. Funguje. Děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
