### ISSUE TITLE
WorkFlow - popUp okno při rozkliknutí úkolu z podzáměru

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#568]
Při kliku na úkol v záměrech se zobrazí popUp okno s informacemi o daném úkolu.

**Comment by nezbedova** [comment]
@albertoh Při jednom kliku se nic neděje.

Při "doubleClick" otevira se obrazovka Úkoly.

Až když kliknu na úkol, tak se vpravo objeví formulář pro vyplňování.

Test na Chromu, cache vymazaná.

**Comment by albertoh** [comment]
Zmeneno na jeden klik
Otevira se automaticky

**Comment by nezbedova** [comment]
Toto funguje.
Ale úkol nelze vyplnit. Nejde změnit výběr v roletkách ani dopsat počet skenů.

**Comment by albertoh** [comment]
Opraveno

**Comment by nezbedova** [comment]
@albertoh Zmizely všechny úkoly. Místo tabulky s úkoly mám sloupce a možnost přidat krok.

![obrazek](https://github.com/user-attachments/assets/7bd4fcbe-b031-4fb1-bc2f-de1cb34fb2f8)

Chybí mi všechno označené na obrázku žlutě.

![obrazek](https://github.com/user-attachments/assets/7d489c87-bba8-4abf-a678-384241cd18b4)

**Comment by albertoh** [comment]
Opraveno.

**Comment by nezbedova** [comment]
@albertoh Děkuji. V jádru máme tyto sloupce.

![obrazek](https://github.com/user-attachments/assets/d01cbb3d-657b-4a0f-8f08-099c57e1f53b)


Prosím přidat sloupce _Uživatel_ a _Poznámka_. A sloupec _Uživatel_ prosím mezi _Úkol_ a _Stav_.

![obrazek](https://github.com/user-attachments/assets/f8bc22e4-3468-493c-92af-ffa786ca077b)

_Poznámka_ - zařadit podle abecedy.

**Comment by albertoh** [comment]
Pridano.
Zaroven jsem pridal tlacitko "reset": a by se nemuselo odstranit veskere nastaveni

![image](https://github.com/user-attachments/assets/1ea02d65-a911-4a88-8eba-2aa305328b98)

**Comment by nezbedova** [comment]
@albertoh Skvělé. Mám, co potřebujeme. Za to Resetování nastavení moc děkuji, to je šikovné.

**Comment by nezbedova** [comment]
Otestovala jsem zapisování jednotlivých úkolů. Až po Export pro Krameria to funguje pěkně. 

U exportu Archivace mi nešlo přidělit urn:nbn, takže export neproběhl. Předpokládám, že by se také do úkolů zapsal.
Využila jsem to k testu zrušení úkolu.

Objekt jsem smazala. Záměr se dokončil. 

Při testu jsem narazila na tři drobné chyby, na které založím issues.

**Comment by ZdenkaSera** [comment]
Přidělování urn:nbn teď opravdu nefunguje, ale je to problém NK, testovací resolver https://resolver-test.nkp.cz/ teď není dostupný.
