### ISSUE TITLE
WorkFlow - editace stažením z Katalogu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#569]
Přidat možnost při editaci metadat již stávajícího záměru stažením dat z katalogu.

**Comment by albertoh** [comment]
Lze editovat standardne pomoci formulare, kde lze stahovat z katalogu data pro urcita pole.

![image](https://github.com/user-attachments/assets/8e5dd398-e139-4624-9eae-1e72f2f9973e)

![image](https://github.com/user-attachments/assets/21c912bc-10b2-420d-b2fe-50b2484a22c7)

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
