### ISSUE TITLE
WorkFlow - hromadný výběr záměrů

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#571]
V záměrech umožnit hromadný výběr záměrů/podzáměrů.

S více vybranými záměry jsou spojené 2 akce
 - hromadně smazat
 - editovat pole financováno, priorita, stav, poznámka

**Comment by albertoh** [comment]
Klient pripraven. Cekam na API pro dokonceni

**Comment by SykoraLukas** [comment]
Mazat můžeš už teď, stačí poslat id záměrů ke smazáni jako list v parametru: id

**Comment by albertoh** [comment]
Odstraneni je hotovo

**Comment by SykoraLukas** [comment]
U hromadné editace to je jak u jednotlivé editace, jen se to posílá na adresu `/rest/v2/workflow/editorJobs` a místo parametrů `id` je parametr `ids`, který očekává list `id` jobů.

**Comment by albertoh** [comment]
Hotovo

**Comment by nezbedova** [comment]
Hromadně jsem přidala všechno. Záměry jsem odstranila.

Jen mám problém s Poznámkou. Ta se mi v hlavičce neobjevila.

 
![obrazek](https://github.com/user-attachments/assets/cbf737b1-edff-4e94-a1a8-2fc38c999162)

**Comment by nezbedova** [comment]
Když jsem zapsala poznámku k titulu a dala Uložit, tak se mi poznámka zapsala všude.

Ke všem záměrům. Ale ve sloupci Poznámka ji nevidím.

![obrazek](https://github.com/user-attachments/assets/4fff081f-35c2-4ac2-b606-264bcda96f9a)

**Comment by nezbedova** [comment]
Poznámka se zapsala všude po přzavření chyby:

![obrazek](https://github.com/user-attachments/assets/fb88e0cb-3bfc-4125-8f6f-464bfb584839)

Obnovit nepomáhá. Vše zmizí až po znovunačtení celé stránky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
