### ISSUE TITLE
V objektu naimportovaném do ProArcu jako archivní balíček se nezobrazují náhledy skenů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#572]
Pokud naimportuji do ProArcu archivní balíček, místo náhledu skenů v klientovi jen běhá modrá čára, obrázek se neukáže ani po delším čekání.  (Chrome, 2.2.4/4.1.5, lokálně v KNAV
![image](https://github.com/proarc/proarc-client/assets/79305516/18f369bb-9b6d-48dc-9a4d-594b405b0d1b)

v jádře skeny vidím
![image](https://github.com/proarc/proarc-client/assets/79305516/3bad8476-009c-41dd-91bb-b4966316c214)

**Comment by SykoraLukas** [comment]
Prosím o zaslání FOXML.

**Comment by ZdenkaSera** [comment]
Ještě doplňuji - stejný problém je po načtení NDK PSP.

**Comment by ZdenkaSera** [comment]
@SykoraLukas FOXML jsem poslala v pondělí mailem, doplňuji jen pro úplnost.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Po přechodu na Akubru na produktivní instanci jsem stejný archivní balíček naimportovala tam - v Akubře  se náhledy zobrazily. Issue tedy zatím zavírám a pokud by se vyskytly potíže při provozu, znovu otevřeme.
