### ISSUE TITLE
Blokování změn - nefunguje při přesunu strany přes Změnu pozice 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#573]
Pokud přesouvám sken pomocí fce Změna pozice, tak k zablokování změn (https://github.com/proarc/proarc-client/issues/397) nedochází. Nemělo by se to chovat stejně jako když přesouvám stranu tažením myši?

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
vypadá to OK
