### ISSUE TITLE
Workflow - nelze založit záměr

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#574]
Prosíme o radu/nápad, kde máme hledat příčinu - předem děkuji.

Na ostré instanci PA přestalo být možné vytvářet záměry - podle testů se zdá, že problémem jsou pouze RDA záznamy.  Potíže začaly během června (verze byla nezměněná od loňského srpna). Dnes jsme nasadili verze 4.1.5/2.2.4 a konvertovali na Akubru (zdá se, že zcela bez problémů :-)), chování záměrů  se nezměnilo k lepšímu.

Problém je zřejmě u nás lokálně, na testovací instanci se stejnou verzí PA záměry fungují, workflow xml je na obou instancích stejné.
Nepodařilo se mi nasimulovat chybu v jádře, prostě se jen nic nestane.  V klientovi dostanu tuto hlášku:
![image](https://github.com/proarc/proarc-client/assets/79305516/ca4c90e5-07d3-474f-b5fa-0dee43eb0157)

@nezbedova dostala tuto chybovou hlášku v jádře:
![image](https://github.com/proarc/proarc-client/assets/79305516/56fc4d59-6a57-43e9-8370-bf45dd249d23)

**Comment by SykoraLukas** [comment]
@ZdenkaSera z toho nic nezjistím. Prosím o zaslání kompletního logu proarc.log, konfiguraci workflow, id stahovaného záznamu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zatím díky a zavírám, @PetrKotynek to vyřešil, zatím nemám z testů protipříklad.
