### ISSUE TITLE
Náhledy v klientovi nejsou vidět celé

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#576]
Náhledy na skeny nejsou v klientovi vidět celé, dolní okraj chybí, což hlavně v paginaci komplikuje práci. Prosím, kouknete na to? Děkuji.

![image](https://github.com/proarc/proarc-client/assets/79305516/daf32ab4-9116-4a8b-b582-0b0122c4bb89)

**Comment by luckajirku** [comment]
u nás se tohle asi neděje, a ani na testu jsem na to nenarazila... normálně jsou vidět celé skeny

**Comment by ZdenkaSera** [comment]
@luckajirku Díky za zprávu, podíváme se znovu ještě na naše interní nastavení

**Comment by kerschfilip** [comment]
Myslím, že problém souvisí s tím, že jsme v konfiguraci ProArcu změnili požadovanou velikost thumbnailů. V návaznosti na https://github.com/ceskaexpedice/kramerius-web-client/issues/754 jsme změnili velikost náhledů takto:

```
#Náhledy v klientovi nejsou vidět celé
import.image.thumbnail.maxWidth=170
import.image.thumbnail.maxHeight=256
``` 
Zdá se, že klient se s tím nějak neumí vypořádat :-) 

Při původním nastavení viz níže je vše v pořádku.
```
# Náhledy OK
import.image.thumbnail.maxWidth=120
import.image.thumbnail.maxHeight=128
```

**Comment by ZdenkaSera** [comment]
Issue necháváme zatím otevřené jako otázku  - s dotazem, zda lze při vygenerování jiné velikosti náhledů uzpůsobit jejich zobrazení v klientovi.

Dnes jsme navíc znovu narazili na výjimku, kde byla v náhledech špatně viditelná spodní řádka s číslem strany. To ale budeme dál sledovat a při dalších výskytech připravíme příklady.

**Comment by ZdenkaSera** [comment]
Příklad - porovnání náhledu a celého skenu.

![image](https://github.com/user-attachments/assets/d9c86c37-4b58-4667-b328-2ae2d678d74c)

![image](https://github.com/user-attachments/assets/60578e06-235a-443a-9a5e-8b9d15aa93f1)

**Comment by ZdenkaSera** [comment]
@pkudela Po domluvě s @SykoraLukas je ti přiřadila.

**Comment by ZdenkaSera** [comment]
Ze schůzky 6.8.:
- zachovat pevnou výšku a šířku podle prvního obrázku
- pokud bude obrázek větší, centrovat na střed (např. skenovaná dvojstrana)

**Comment by ZdenkaSera** [comment]
@nezbedova Návrh na řešení popisků u náhledů - ostatní knihovny k odsouhlasení.

**Comment by nezbedova** [comment]
Návrh úpravy popisků pod náhledy zahrnuje několik položek, které rozdělím do jednotlivých vláken. Prosím ostatní knihovny o vyjádření.

1) Zobrazovat popisky stran podle zvoleného jazyka. Dle potřeby je možné si jazyk přepnout. 

U CS/EN zobrazovat obě varianty nebo jen anglické popisky.

**Comment by nezbedova** [comment]
2) V Úložišti zobrazovat pouze jeden popisek. Nyní tam jsou zdvojené. 

![obrazek](https://github.com/user-attachments/assets/6b536fdc-96e8-4602-a75c-df2d39d180d3)

**Comment by nezbedova** [comment]
3) Nezvětšovat pole pro popis podle nejdelšího popisu. V jádru je vidět, že se část textu (index) skryje. Typ strany "Přední strana přebalu" je asi nejdelší.

![obrazek](https://github.com/user-attachments/assets/c8a9925f-e312-4ac9-9714-a7663add72c6)

![obrazek](https://github.com/user-attachments/assets/d703a3ee-fe81-4799-8fc0-9d27eae6b942)

**Návrh - zobrazit max. dva řádky, zbytek by pod náhledy nebyl vidět. V Tabulce by byl celý.**

![obrazek](https://github.com/user-attachments/assets/a13a4949-d703-4618-8be9-036f6c2174af)

**Comment by nezbedova** [comment]
4) Pole s popisky pod náhledy zabírá příliš místa. V jádru zabírají asi 20% velikosti náhledu, v klientovi 40%.

**Navrhuji zmenšit řádky.**

Porovnání klient/jádro (malé rozestupy jsou správně, ty neměnit):

![obrazek](https://github.com/user-attachments/assets/9bc72380-16c9-411b-b339-8c3ce1014737)

**Návrh pro větší a menší náhled**

![obrazek](https://github.com/user-attachments/assets/6f1baeb6-e220-4b97-bcd7-40b379ccc8e8)

**Comment by nezbedova** [comment]
5) Odlišení čísla strany od čísla indexu.

Zde je možností více.

Nyní: 

![obrazek](https://github.com/user-attachments/assets/c080047b-4852-41e7-a5fc-3b99a6c71d52)

**A.** Jako první, podle mne nejjednodušší, je doplnit čárku za číslem strany: 

![obrazek](https://github.com/user-attachments/assets/fd669140-30e4-4edd-8d4f-1919b1af999d)


**B.** Další možností je barevné odlišení. Upozadit číslo indexu šedivou barvou: 

![obrazek](https://github.com/user-attachments/assets/f16bdcc3-e1d5-46b7-8044-17c5d2e2cafb)

**C.** Změna stylu písma. Upozadit index strany kurzívou nebo zvýraznění čísla strany tučně.

![obrazek](https://github.com/user-attachments/assets/4cca160b-de99-4a8d-9ea3-5495cd719646)


**D.** Kombinace všeho, ale to nám přijde příliš, proto bez ukázky.

@albertoh Nevím, zda je nějaké odlišení barvou nebo stylem písma možné.

**Za KNAV by bylo nejlpší - přidání čárky, zesvětlení indexu šedou.**


![obrazek](https://github.com/user-attachments/assets/b717c76c-fc86-4ba6-9a9d-ec48b5adc175)

**Comment by nezbedova** [comment]
Vzhledem k tomu, že se dosud nevyjádřila @luckajirku , @katerinasirova ani @erikamirova prosíme o malou úpravu v popisku pod stranou, a to přidání čárky za číslo strany (stejně jako to je u čísla indexu).

![obrazek](https://github.com/user-attachments/assets/7cdf54f4-57f1-46fc-bff2-9cd32602f3a7)

Děkuji

**Comment by erikamirova** [comment]
@nezbedova nejvíce se nám líbí varianta A

**Comment by ZdenkaSera** [comment]
Na masteru připravit příklady @nezbedova

**Comment by ZdenkaSera** [comment]
Poslat FOXML k testu.

**Comment by pkudela** [comment]
> Poslat FOXML k testu.

Muzete mi prosim poslat url na nejaky ten test, at to muzu odladovat na konkretnim objektu?

**Comment by ZdenkaSera** [comment]
@pkudela Prosím, zkus se napřed podívat v importu na tuhle načtenou dávku - když si pak zvolíš funkci "pokračovat", otevře se dávka v paginaci - tam je na skenech vidět ten překryv: stránky mají i dole rámečky, ty nejsou vidět. FOXML pošleme, tam to pak uvidíš už jen v úložišti. Díky

![image](https://github.com/user-attachments/assets/225329af-7fef-48e0-894f-42f81cd56f46)

![image](https://github.com/user-attachments/assets/9025656f-3419-4541-bb19-006153dcce7c)

**Comment by pkudela** [comment]
> @pkudela Prosím, zkus se napřed podívat v importu na tuhle načtenou dávku - když si pak zvolíš funkci "pokračovat", otevře se dávka v paginaci - tam je na skenech vidět ten překryv: stránky mají i dole rámečky, ty nejsou vidět. FOXML pošleme, tam to pak uvidíš už jen v úložišti. Díky
> 
> ![image](https://private-user-images.githubusercontent.com/79305516/365109988-225329af-7fef-48e0-894f-42f81cd56f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjEwODMsIm5iZiI6MTcyNTYyMDc4MywicGF0aCI6Ii83OTMwNTUxNi8zNjUxMDk5ODgtMjI1MzI5YWYtN2ZlZi00OGUwLTg5NGYtNDJmODFjZDU2ZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzMxY2RkN2YyZmYyMjM3MDljMmIwNWMxZTU3OWZiOWRmMjVmZDdkZDljNGExODgxNDIyM2IzNjZjMDc1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-caljWFmETNrMUYlbowyRPgzIb5ajZEGDsGel4cdpMQ)
> 
> ![image](https://private-user-images.githubusercontent.com/79305516/365110804-9025656f-3419-4541-bb19-006153dcce7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjEwODMsIm5iZiI6MTcyNTYyMDc4MywicGF0aCI6Ii83OTMwNTUxNi8zNjUxMTA4MDQtOTAyNTY1NmYtMzQxOS00NTQxLWJiMTktMDA2MTUzZGNjZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODM0YWMyYTA3NmEyNjNhNmFhOThjODQxNjI3NTU3MzZkZmM0NDA3OWE1ZjI4MDk0NGViZjJlNTY0Zjg0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lWTcM1b39V1lf20s9BR5-ZGnM0r8TkXcWPUtb5-14wQ)

Kdyz mi posles url, bude to rychlejsi, prosim, kopiruj url z browseru a to mi posli, jinak musim proklikavat vsechny veci z importu.

**Comment by pkudela** [comment]
> > @pkudela Prosím, zkus se napřed podívat v importu na tuhle načtenou dávku - když si pak zvolíš funkci "pokračovat", otevře se dávka v paginaci - tam je na skenech vidět ten překryv: stránky mají i dole rámečky, ty nejsou vidět. FOXML pošleme, tam to pak uvidíš už jen v úložišti. Díky
> > ![image](https://private-user-images.githubusercontent.com/79305516/365109988-225329af-7fef-48e0-894f-42f81cd56f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjEwODMsIm5iZiI6MTcyNTYyMDc4MywicGF0aCI6Ii83OTMwNTUxNi8zNjUxMDk5ODgtMjI1MzI5YWYtN2ZlZi00OGUwLTg5NGYtNDJmODFjZDU2ZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzMxY2RkN2YyZmYyMjM3MDljMmIwNWMxZTU3OWZiOWRmMjVmZDdkZDljNGExODgxNDIyM2IzNjZjMDc1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-caljWFmETNrMUYlbowyRPgzIb5ajZEGDsGel4cdpMQ)
> > ![image](https://private-user-images.githubusercontent.com/79305516/365110804-9025656f-3419-4541-bb19-006153dcce7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjEwODMsIm5iZiI6MTcyNTYyMDc4MywicGF0aCI6Ii83OTMwNTUxNi8zNjUxMTA4MDQtOTAyNTY1NmYtMzQxOS00NTQxLWJiMTktMDA2MTUzZGNjZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODM0YWMyYTA3NmEyNjNhNmFhOThjODQxNjI3NTU3MzZkZmM0NDA3OWE1ZjI4MDk0NGViZjJlNTY0Zjg0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lWTcM1b39V1lf20s9BR5-ZGnM0r8TkXcWPUtb5-14wQ)
> 
> Kdyz mi posles url, bude to rychlejsi, prosim, kopiruj url z browseru a to mi posli, jinak musim proklikavat vsechny veci z importu.

uz jsem to nasel, ale priste prosim o url, je to pro me rychlejsi, jen zkopiruju do radku prohlizece a jsem tam, dekuji

**Comment by ZdenkaSera** [comment]
@pkudela V importu to url nemá, ale připojila jsem ty skeny k STT monografii. My si to pak v importu vyzkoušíme, ty náhledy je zapotřebí upravit hlavně tam; v úložišti sice taky, ale paginace v importu je důležitější a já nevím, zda tu úpravu musíš udělat jen jednou nebo pro každé t těch dvou míst samostatně  ;-)  Zkus tedy tohle. Díky.
https://proarc-master.inovatika.dev/repository/uuid:46132287-9d88-4536-a09f-bf36d1a4aff5

**Comment by pkudela** [comment]
> @pkudela V importu to url nemá, ale připojila jsem ty skeny k STT monografii. My si to pak v importu vyzkoušíme, ty náhledy je zapotřebí upravit hlavně tam; v úložišti sice taky, ale paginace v importu je důležitější a já nevím, zda tu úpravu musíš udělat jen jednou nebo pro každé t těch dvou míst samostatně ;-) Zkus tedy tohle. Díky. https://proarc-master.inovatika.dev/repository/uuid:46132287-9d88-4536-a09f-bf36d1a4aff5

Diky, @ZdenkaSera, @nezbedova muzete vyzkouset? Nahral jsem tam novou verzi, na master -> https://proarc-master.inovatika.dev/repository/uuid:46132287-9d88-4536-a09f-bf36d1a4aff5

![image](https://github.com/user-attachments/assets/e674320a-b094-494e-a49e-f4f4d5a567b5)

**Comment by nezbedova** [comment]
@pkudela Mezery mezi obrázky super. 

Mohl byste, prosím, ještě přidat čárku za číslo strany, jak se dohodlo na schůzce? Děkuji.

![obrazek](https://github.com/user-attachments/assets/b820dbf6-f9ba-485a-94a8-c58cea93d933)

**Comment by ZdenkaSera** [comment]
@pkudela Za mě je překryv pryč v importu i v úložišti, takže 👍, díky! Tady ale poslední slovo musí mít @nezbedova a @SmejkalovaAnna.

**Comment by nezbedova** [comment]
@pkudela v importu ani v úložišti překryv není. Ale chtěla jsem zkontrolovat jak to vypadá u STT, ale nejde mi nahrát #608

**Comment by nezbedova** [comment]
Na změnu zobrazení popisků u náhledů jsem založila #610  a přesunula tam vše, co k tomu patří.

**Comment by nezbedova** [comment]
Otestováno.

V Importu trochu "zlobí" delší názvy. Pokud kliknu na následující náhled, tak se zobrazí text z minulého.

![obrazek](https://github.com/user-attachments/assets/79386b03-41db-4c8b-9fbc-f753e154f668)

Bez kliknutí/označení následujícího náhledu to není vidět.

![obrazek](https://github.com/user-attachments/assets/84caf5b3-6081-4a69-8708-c3e3e06ee2f1)


Za mě je to pouze estetická záležitost, která nevadí funkčnosti.

**Comment by SmejkalovaAnna** [comment]
Za mě náhledy už super, nechybí snad nic.

**Comment by pkudela** [comment]
> Otestováno.
> 
> V Importu i v Úložišti trochu "zlobí" delší názvy. Pokud kliknu na následující náhled, tak se zobrazí text z minulého.
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/365224073-79386b03-41db-4c8b-9fbc-f753e154f668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjkwMTksIm5iZiI6MTcyNTg2ODcxOSwicGF0aCI6Ii8xMzgzMTk0Ni8zNjUyMjQwNzMtNzkzODZiMDMtNDFkYi00YzhiLTlmYmMtZjc1M2UxNTRmNjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA3NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNTczZDQ5ZWViMjlhNTc4YjYzYTIzNmU2NDgyOGVkMWFlZTllNjdhM2E0MmQyNGM1NzhiMTQyNjJhNTIwMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Sw0funURV9WdiQ3yaxp_MaIqGQaHfVKz_KAJi-VbT4)
> 
> Bez kliknutí/označení následujícího náhledu to není vidět.
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/365224646-84caf5b3-6081-4a69-8708-c3e3e06ee2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjkwMTksIm5iZiI6MTcyNTg2ODcxOSwicGF0aCI6Ii8xMzgzMTk0Ni8zNjUyMjQ2NDYtODRjYWY1YjMtNjA4MS00YTY5LTg3MDgtYzNlM2UwNmVlMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA3NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWM1MmQ1MjcwMTJmMzllYjU5Nzc5NDFhOTYzZjdiNDZlOGE1YWM4N2U1OTNjMzJkMzU3NjlmZGQxOWQ5YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CMayP4rZc4voW5b_Gdj0bePBNNesu1JFvxRa0ECD2nw)
> 
> Za mě je to pouze estetická záležitost, která nevadí funkčnosti.
 
Dobry den, o tom vim, text budu orezavat az budu resit zobrazeni popisku jen na 2 radky viz. issue #610, plny obsah popisku by pak mohl byt dostupny v tooltipu po najeti mysi.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Lukáši, jak ti mám předat ty čtvercový skeny? Přez filesender?

**Comment by SykoraLukas** [comment]
Ano prosím, nebo přes uschovnu.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Lukáši zde: https://filesender.cesnet.cz/?s=download&token=7b5ca9e9-6b0e-4ef6-8f07-87d93bcea907

**Comment by SykoraLukas** [comment]
Nahráno na server. K vyzkoušení https://proarc-master.inovatika.dev/import/edit/809. @pkudela koukneš se na to?

**Comment by pkudela** [comment]
> Nahráno na server. K vyzkoušení https://proarc-master.inovatika.dev/import/edit/809. @pkudela koukneš se na to?

ano, jdu na to

**Comment by pkudela** [comment]
Toto je hotove, opravil jsem to, je to nasazene a pripravene k testovani. Prosim, pokud nekdo budete moct, zkuste tam nahrat jeste nejake jine, nez ctvercove obrazky, napr. nejake nuldle na vysku, pripadne nejake nudle na sirku, at jsme si jisty, ze nahledy funguji v jakemkoliv formatu.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1c0269c8-dde0-457a-95fd-62ee71448bdf">

**Comment by nezbedova** [comment]
@SykoraLukas @pkudela 

Další formáty k testu jsou ke stažení zde:

https://filesender.cesnet.cz/?s=download&token=ba86c974-129f-40c0-b9b9-e0c53a4ec6f5

**Comment by pkudela** [comment]
@SmejkalovaAnna a jinak se ti zda to zobrazeni v poradku? Mimo tech speku, ktere si poslala, ty jeste otestujeme :-)

**Comment by SmejkalovaAnna** [comment]
@pkudela Petře čtverce špatný:
![obrazek](https://github.com/user-attachments/assets/4ce65bcc-1e25-4a77-9cd4-f9bdbd49790e)

**Comment by pkudela** [comment]
> @pkudela Petře čtverce špatný: ![obrazek](https://private-user-images.githubusercontent.com/24409660/371467397-4ce65bcc-1e25-4a77-9cd4-f9bdbd49790e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjgzNTIsIm5iZiI6MTcyNzQyODA1MiwicGF0aCI6Ii8yNDQwOTY2MC8zNzE0NjczOTctNGNlNjViY2MtMWUyNS00YTc3LTljZDQtZjliZGJkNDk3OTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA5MDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NzJmNjAyMjc5ZWY3YzlmNWI3MjAwZDkzOTQwOGJmODJhMGVhMjU4ZDA0NmRiODkyMmYzOTk2OWE3ZDhkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fnKH_0WIoS_QA3o4XRDYZf7U2rVLoO8qjelatlgF95k)

Pockej, zkousis to masteru a dala si si tvrdy reload prohlizece, pripadne vymazala cache?

**Comment by SmejkalovaAnna** [comment]
@pkudela Ano, reload, vymazala cash, dělám to v Mozzile...

**Comment by pkudela** [comment]
> https://proarc-master.inovatika.dev/import/

hm, mas pravdu, tak nevim, kde je chyba, vcera jsem tam daval novou verzi a ten screenshot vyse se spravnymi nahledy je z masteru, cili asi nekdo prmazl moji verzi, dam to tam znova, vydrz

**Comment by pkudela** [comment]
> > https://proarc-master.inovatika.dev/import/
> 
> hm, mas pravdu, tak nevim, kde je chyba, vcera jsem tam daval novou verzi a ten screenshot vyse se spravnymi nahledy je z masteru, cili asi nekdo prmazl moji verzi, dam to tam znova, vydrz

@SmejkalovaAnna tak vysvetleno, Alberto tam musel vratit verzi z releasu, vkuli cislu verze, ted jsem to nasadil i se spravnym cislem verze a melo byt to byt ok, dej si tvrdy reload a dej mi prosim vedet

<img width="965" alt="image" src="https://github.com/user-attachments/assets/5067f2a7-fa24-4ee5-bb3e-88466fe789e3">

**Comment by SmejkalovaAnna** [comment]
@pkudela Zobrazuje se to už dobře. Zkuste prosím ještě ty nudle a soubory od Martiny, co posílala... díky!

**Comment by pkudela** [comment]
> @pkudela Zobrazuje se to už dobře. Zkuste prosím ještě ty nudle a soubory od Martiny, co posílala... díky!

jasne, uz jsem poprosil @SykoraLukas az bude mit chvilku, ja to pak otestuju

**Comment by SmejkalovaAnna** [comment]
@pkudela Petře za mě perfektní!

**Comment by pkudela** [comment]
> @pkudela Petře za mě perfektní!

slaaaava :-)

**Comment by ZdenkaSera** [comment]
V KNAV ok, nikdo jiný problém neměl - tedy zavírám a děkuji.

**Comment by nezbedova** [comment]
Znovu otvírám.

V KNAV v Klient: Verze v2.3.2 (02.10.2024)Jádro: Verze 4.2.3 - Build 2024092613574

nelze použít tlačítka pro přiblížení obrázku (1 náhledu) - tlačítka jsou zašedlá:

![obrazek](https://github.com/user-attachments/assets/3114e5b6-7602-4576-8e64-95a6d74aeb1e)

V Inovatice v Klient: Verze v2.3.2 (09.10.2024)Jádro: Verze 4.2.3-SNAPSHOT - Build 20241008204328

to jde:

![obrazek](https://github.com/user-attachments/assets/af042385-25d3-48f6-a1d4-da2a7ad1173e)


Netušíte, co by s tím mohlo být?

Je to sken ze složky Knav/StareTisky/specialitky/

**Comment by pkudela** [comment]
> Znovu otvírám.
> 
> V KNAV v Klient: Verze v2.3.2 (02.10.2024)Jádro: Verze 4.2.3 - Build 2024092613574
> 
> nelze použít tlačítka pro přiblížení obrázku (1 náhledu) - tlačítka jsou zašedlá:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/374931315-3114e5b6-7602-4576-8e64-95a6d74aeb1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzM2NjIsIm5iZiI6MTcyODQ3MzM2MiwicGF0aCI6Ii8xMzgzMTk0Ni8zNzQ5MzEzMTUtMzExNGU1YjYtNzYwMi00NTc2LThlNjQtOTVhNmQ3NGFlYjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTY5YWE0MjUxMjVjNzc1MzMyOWI3NmZmZGQ3ZWQ3MWJiOTUwZDZhYWRjYmVjZTE1OGZlM2I4MmE1MGU2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zgH4-2lPERS3q311px9O9--GT48KAe1W71z77_hO7xE)
> 
> V Inovatice v Klient: Verze v2.3.2 (09.10.2024)Jádro: Verze 4.2.3-SNAPSHOT - Build 20241008204328
> 
> to jde:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/374931834-af042385-25d3-48f6-a1d4-da2a7ad1173e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzM2NjIsIm5iZiI6MTcyODQ3MzM2MiwicGF0aCI6Ii8xMzgzMTk0Ni8zNzQ5MzE4MzQtYWYwNDIzODUtMjVkMy00OGY2LWExZDQtZGEyYTdhZDExNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTJkNDA0MmFkZTQ3Yzg5MzExODU2ZTAyNGE0YTY0ZjdiMTc3Nzg3ZGQ3ZjRjZTVjYWFkMzZjMDA0NWEzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9lChryMZYwNodAGuCtNFGP1YBoEjI8RE-eRb0VERCa8)
> 
> Netušíte, co by s tím mohlo být?
> 
> Je to sken ze složky Knav/StareTisky/specialitky/

Dobry den @nezbedova toto ale nesouvisi s problemem zobrazovani nahledu, ktery jsme resili v tomto issue, jedna se o funkcionalitu tlacitek, prosim, toto issue zavrete a zalozte na to nove issue, dekuji.

**Comment by nezbedova** [comment]
Založeno issue #636 . Zde zavírám.

**Comment by albertoh** [comment]
Ja bych rekl, ze to je kvuli tomu, ze mate neulozene zmeny, a tim mate zablokovany panel obrazku

**Comment by nezbedova** [comment]
@albertoh Tím to, bohužel, není.
