### ISSUE TITLE
rozřazování stran do čísel - posun oblasti v hledání

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#579]
Při rozřazování stran do čísel periodik přes Přesunout se tabulka s cílovým titulem neposouvá na ten poslední objekt, kam se právě přesunuly strany, ale ukáže titul od prvního dostupného ročníku s rozbaleným ročníkem, kam ukládám, zase od prvního čísla. Označené to číslo periodika, kam se přesouvalo, sice je, správně je i rozbalené, potud super - ale nevidím ho hned, musím k němu vždycky rolovat. Což při velkém množství ročníků a desítkách/stovkách čísel v ročníku dost zdržuje. Šlo by tohle udělat, aby po uložení byla vidět ta oblast, kam se ukládalo? 

současný stav:

![jiskra_presunoutstrany1](https://github.com/user-attachments/assets/83f4b432-8927-4a78-988d-77694c932dd0)

žádoucí stav:

![jiskra_presunoutstrany2](https://github.com/user-attachments/assets/42f995d9-2c55-4f80-8e1d-cb06928de0a3)

**Comment by albertoh** [comment]
Hotovo (myslim si). Prosim o kontrolu, jestli jsem to spravne pochopil

**Comment by luckajirku** [comment]
jj, pochopil jsi to správně, tohle potřebujeme. teď už je vždycky viditelné (a rozbalené) to číslo, do kterého se ukládalo. akorát teda když se to uloží, tak se ta oblast načte, a pak při rozbalování ještě o kousek poskočí. jestli to je z radosti, že se to povedlo:-), tak OK, ale kdyby to šlo v jednom kroku, bylo by to příjemnější.

**Comment by albertoh** [comment]
Nejde :(
Nejdriv aplikace musi ziskat z backendu objekty, potom renderovat, a az to je hezke v browseru muzu scrollovat na prislusny radek.

**Comment by luckajirku** [comment]
Hm, škoda. Tak v tom případě je to za nás OK (a k zavření).

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
