### ISSUE TITLE
Možnost výběru dvojklikem

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#58]
V obrazovce Import/ Správa importních dávek přidat možnost výběru dvojím kliknutím myší na vybraný řádek.

Nyní to je možné jen kliknutím na tlačítko "Přejít na objekt".

**Comment by honza-rychtar** [comment]
Doplněno.

**Comment by nezbedova** [comment]
Funguje na jeden klik.

**Comment by tumovam** [comment]
Funguje, zavírám na scházce k vývoj. týmu.
