### ISSUE TITLE
ATM - pole archivalCopies

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#580]
Do ATM prosím přidat pole archivalCopies. (Textové pole, label: Cesta k archivním skenům).

Pole je editovatelné.

Ve starém klientovi je již vyplněno a může se testovat na pidu: uuid:33244df3-e448-4a2c-b69f-3a0fb96fc8c7

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
Díky, zkusíme. P/rosím ještě o doplnění labelů v CS a EN:

![image](https://github.com/user-attachments/assets/9f989b3b-9c33-4a0b-a987-77056844e595)

**Comment by albertoh** [comment]
ctrl+f5 ?

**Comment by ZdenkaSera** [comment]
:-) ... CS ok, EN mluví česky

**Comment by kerschfilip** [comment]
> :-) ... CS ok, EN mluví česky

@albertoh stále platí, viz: https://github.com/proarc/proarc-client/blob/e8d257c7a5d576c56bc16458ae21cbaf9f2c6e94/src/assets/i18n/en.json#L293

prosím přepsat v EN/EN na "Path to original scans"

A prosím nakonec upravit i tu češtinu na: "Cesta k původním skenům"   
(za archivní skeny se v rámci standardů digitalizace NK považují ty JPG2000, tak to někoho nepletlo)

Díky!

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
V pořádku, díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
