### ISSUE TITLE
Uložení manuální změny OCR neaktivuje okna

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#581]
Při testování oprav OCR pomocí Pera jsme zjistili, že pokud ručně upravíme OCR a uložíme, okna se neaktivují, nelze např. překliknout na jinou stranu. Pomůže ale např. kliknutí na odkaz na titul na liště nebo překliknutí z textového přepisu T na metadata M. 
Máme to považovat za vlastnost? OCR se ručně obvykle nemění, takže tohle není prio a pokud není oprava jednoduchá, budeme s tímto chováním počítat. Díky za reakci.

![image](https://github.com/user-attachments/assets/d0dc3569-f0ed-4b7d-ae99-7b90fa44d3d9)

**Comment by albertoh** [comment]
Opraveno.

**Comment by ZdenkaSera** [comment]
Na masteru vypadá ok, díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
