### ISSUE TITLE
Úložiště - hledání -přestaly fungovat některé funkce

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#582]
@albertoh Alberto, prosím, zkontroluj/projdi si obrazovku úložiště. Při testu na masteru jsem např. nemohla na dolní liště spustit export, přidělení urn:nbn, rozbalení objektu ... Objekt šel zamknout a odemknout, ale dolní obrazovku je zapotřebí obnovit, neaktualizuje se automaticky ...
Děkuji.

**Comment by albertoh** [comment]
Opraveno. Krome "Rozbalit". To jeste potrebuju promyslet jak nejlepe implementovat

**Comment by ZdenkaSera** [comment]
Vypadá to opravené, kromě zmíněné funkce rozbalit. Díky. Navrhuji k uzavření s tím, že fce rozbalit se řeší tady https://github.com/proarc/proarc-client/issues/578

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
