### ISSUE TITLE
V dolní části úložiště zmizela ikona pro kopírování uuid

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#584]
Na inovatice-masteru chybí ikonka pro kopírování uuid - prosíme o opravu, často používáme u víceúrovňových objektů. Děkujeme.
Ve verzi 4.1.6./2.2.4 v KNAV je:

![image](https://github.com/user-attachments/assets/1651bdc2-653a-44a9-954f-5ee2ff35f35a)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Je tam, funkční. Díky,

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
