### ISSUE TITLE
Zmizelo nastavení audio linky v Zařízení + nelze přidat info ke zvukovým souborům

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc-client#588]
V současné verzi PA nám zmizelo nastavení audio linky z loňského roku. Je možné editovat jen část týkající se skenerů, informace ke zvukovým souborům nelze přidat - resp. po uložení se nikde nezobrazí - buď se neuloží nebo to nevidíme. 
Kontrola proběhla u nás také na API, ani tam se nezobrazí již jednou uložené info ke zvukovým souborům z loňska a ani tam nejde uložit nové.
Týká se jak PA v MKP - v 2.2.4, tak PA v NM-ČMH v 2.3.0
Viz obrázek spodní část obrazovky - information about audio files:

![image](https://github.com/user-attachments/assets/63cb765c-5d65-4f78-96a1-7606db95f258)

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, zdá se nám to důležité - nastavuji prio. OK?

**Comment by katerinasirova** [comment]
Bez toho nevyexportujeme letošní VISK. Takže budeme potřebovat během podzimu. Děkuji

**Comment by ZdenkaSera** [comment]
schůzka 3.9. - prio oprava do nejbližší verze

**Comment by tumovam** [comment]
@katerinasirova měli jste čas testovat? Děkuji

**Comment by katerinasirova** [comment]
Ano, otestováno u nás a minulý týden i v Českém muzeu hudby. Můžeme uzavřít. Děkuji

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
