### ISSUE TITLE
Rozbité funkce v editačním okně

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#589]
Ve verzi 4.2.0/2.3.0. nepracují funkce na horní liště editačního okna:

![image](https://github.com/user-attachments/assets/38395302-0c12-4c3d-8a00-8280543b5b47)

**1. Exporty do Krameria (FOXML i NDK PSP) nenabízejí instance ani možnost exportovat na "local"**

![image](https://github.com/user-attachments/assets/32aeaf31-7bc4-4785-8d39-92239edcc5d0)

**2. Export archivu zamrzl v této fázi a ve správě objektů se neobjevil:**

![image](https://github.com/user-attachments/assets/24cf9a06-b188-4f95-a9e6-2467c353c1af)

**3. Přidělení urn:nbn končí takto:**

![image](https://github.com/user-attachments/assets/9eccf87a-4436-4f43-aeca-41152f30973a)

**4. Kopírování objektu vyzkoušené jen na monografii  zafungovalo správně.**

**Comment by ZdenkaSera** [comment]
Toto označuji jako prioritní, zpracování článků bez toho nemůže přejít do klienta. Děkuji.

**Comment by kerschfilip** [comment]
Vypadá v pořádku, díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
