### ISSUE TITLE
Nevidím náhledy

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#59]
Nevidím náhledy u Methodiky krasopisu. Nemohu vyzkoušt hromadný popis.

![obrazek](https://user-images.githubusercontent.com/13831946/90242811-f4ca1380-de2d-11ea-8666-61aa12d12c91.png)

**Comment by luckajirku** [comment]
co jsem tak zkusmo proklikala, tak to vypadá, že se u objektů, které nemají pod sebou strany, zobrazuje i ikonka "náhledy", ale u těch, které strany mají, ikonka není:-)

**Comment by honza-rychtar** [comment]
Byla tam podmínka, že **všechny** objekty musí být typu _strana_, aby se zobrazila možnost prohlížení přes náhledy.
Změnil jsem to, aby se možnost nabídla, pokud je **alespoň jeden** objekt typu _strana_.

**Comment by nezbedova** [comment]
Funguje.
