### ISSUE TITLE
Generování PDF-A

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#591]
Podpora v klientovi pro [issue na API](https://github.com/proarc/proarc/issues/915).  V API hotové.

Přidat novou funkci vedle tlačítka pro nahrání PDF. Funkce je dostupná, pokud objekt obsahuje stream RAW ve formátu PDF.

Volání funkce je:

```
### GENERATE PDF-A
POST {{proarcUrl}}/rest/v2/object/generatePdfA
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

pid={{uuid}}
```

Funkce vrací jen info, že byl naplánován nový proces.

**Comment by albertoh** [comment]
Na klientovi je. Je potreba zkontrolovat API 
https://proarc-master.inovatika.dev/repository/uuid:6d643366-57e9-4fc6-9c9b-5bfe3db9a80d

**Comment by ZdenkaSera** [comment]
Pokud mažu pdf, nyní mažu obě. @kerschfilip  založí issue na možnost výběru (rozvoj)

**Comment by tumovam** [comment]
Převod PDF do PDF/A ve v2.3.2 funguje. Některá PDF jsou "rozsypaná", což už je ale jiný problém.
