### ISSUE TITLE
Informace o záznamu z katalogu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#593]
Pokud stahují záznam z katalogu (založení nebo přepis metadat) tak se neposílá informace o tom, z jakého katalogu data jsou.

Starý klient tyto informace posílá a dá se s tím jinak pracovat (ignorovat validace při importu dat z katalogu). 

Prosím přidat do parametr `catalogId` s hodnotu id katalogu, ze kterého se data stáhla.

**Comment by ZdenkaSera** [comment]
Po domluvě v issue https://github.com/proarc/proarc/issues/1532 se tato kontrola nebude provádět při založení objektu, too issue tedy zavírám.

**Comment by SykoraLukas** [comment]
Znovu otvírám, tyto informace potřebuji abych mohl ignorovat validace při stažení z katalogů.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
V KNAV jsme zatím nenarazili na protipříklad v zakládání objektů (jen ve workflow při založení záměrů, budeme řešit samostatně). Navrhujeme k uzavření.
