### ISSUE TITLE
Exporty

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#60]
Nenašla jsem možnost popsaný titul vyexportovat ven.

**Comment by krizovj** [comment]
![export](https://user-images.githubusercontent.com/21309201/90485569-fb130500-e137-11ea-805d-a098fbb3561c.jpg)

**Comment by tumovam** [comment]
KNAV chce změnu ikony...

**Comment by luckajirku** [comment]
Tlačítko Exportovat tam teď je, ale zase zmizely některé sloupce vč. Status a Export...

**Comment by honza-rychtar** [comment]
@luckajirku Sloupce se nastavují v Profil -> Nastavení -> Hledání.

**Comment by luckajirku** [comment]
U těch exportů budou jen ta písmena? Vypadá to trochu zavádějícně, A vypadá jako ano, N jako ne:-), ale asi to je Archiv a NDK...

**Comment by honza-rychtar** [comment]
> U těch exportů budou jen ta písmena? Vypadá to trochu zavádějícně, A vypadá jako ano, N jako ne:-), ale asi to je Archiv a NDK...

Jo no. Tak jak? Tooltipy na písmena, ikony místo písmen, ...

**Comment by nezbedova** [comment]
Archive, NDK, K4?

**Comment by SmejkalovaAnna** [comment]
Exporty už fungují ve 1.0.8 (6.9.2021), ale je tam napsáno, že mohu dialog zavřít, že to probíhá na pozadí, ale jaksi není čím ho zavřít... prosím o úpravu okna, a zůstane se tam točít načítací kolečko, což se značně zavádějící... prosím, aby zmizelo....

**Comment by honza-rychtar** [comment]
@SmejkalovaAnna 
Dialog je možné zavřít přes tlačítko **Zavřít** (teď jsem ho přejmenoval, původně bylo **Zrušit**) nebo kliknutím kamkoli mimo dialog.

To točící kolečko znamená, že export probíhá.

<img width="573" alt="Snímek obrazovky 2021-09-28 v 18 10 27" src="https://user-images.githubusercontent.com/1178142/135125470-92a61ee4-43d7-4e90-a18d-acd7b5d684cd.png">

**Comment by SmejkalovaAnna** [comment]
Fajn.... díky.

**Comment by luckajirku** [comment]
Na pohled v klientovi OK, bohužel nemůžeme na testu zkontrolovat výsledky.

**Comment by ZdenkaSera** [comment]
Export K4, archivu i NDK balíčku jsem zatím zkusila na NDK monografii - okometrická kontrola exportů vypadá dobře. 
Simulované chyby při exportu archivu:
1. **Chybná indexace** - archiv doběhl s chybou, vytvořila se složka "error" se stausem popisujícím chybu = ok chování jako v jádře
Chybová hláška v dialogu - pod levou ikonkou "!" text chybové hlášky jako ve staus logu - ok; pod pravou ikonkou nic, ale to je kosmetika
![image](https://user-images.githubusercontent.com/79305516/150770071-3cb57fb6-0540-4138-bf65-ff323e82d3fc.png)


2. nastavila jsem **urn:nbn jako neplatné** a nepřidělila nové
Exportovala jsem archiv - balíček se vytvořil, statusy ok. Jen na konci exportu v dialogu chybová hláška jako výše, ale pod žádným "!" není informace. Pokud při exportu zavřu dialogové okno a nečekám na konec procesu, o chybě se nedovím.
 
@SykoraLukas Chybu "neplatné urn:nbn" nezkontroluje ani export archivu v jádře.

**Comment by ZdenkaSera** [comment]
@albertoh Exporty znovu přetestujeme na vlastním ProArcu, ale tady prosím o opravu dialogu. Díky.

**Comment by SykoraLukas** [comment]
Problém je na serverové čísti. Opravím

**Comment by ZdenkaSera** [comment]
@SykoraLukas Export archivu s chybným indexem nebo s  chybějícím urn:nbn se hlídá, výpis chyby je ok, díky.
Exportu archivu s neplatným urn:nbn zatím proběhne, to se ještě nehlídá.

**Comment by SykoraLukas** [comment]
Pravě jsem nasadil novou verzi. Vyzkoušejte nyní.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, testovala jsem u nás, ale všechny exporty budeme muset přetestovat s příští verzí. Zatím dávám k uzavření.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
