### ISSUE TITLE
Úprava šířky sloupců v Hledat/Dotaz

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#609]
V obrazovce Hledat/Dotaz je sloupec s roletkou zbytečně moc široký a jeho šířka se mění společně se šířkou okna.

Nyní:

![obrazek](https://github.com/user-attachments/assets/9aa0b709-3052-4c5a-8b20-050c0f4ebe82)

Uvítala bych šířku na 20 znaků nebo 2x délka tlačítka Vyhledat. Asi jako to je v Pokročilém hledání při běžném šířce

![obrazek](https://github.com/user-attachments/assets/f6a8791a-6e0d-4ade-a22e-f67298a68cf2)

@pkudela Doumlouvali jsme se na tom na schůzce.

**Comment by pkudela** [comment]
hotovo, model je nastaven na pevnou sirku odpovidajici nejdelsimu nazvu v seznamu, nasazeno, prosim otestovat a pripadne dat k zavreni, nebo rovnou zavrit

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7e2bd78d-f484-4d7e-8133-f765d0534a96">

**Comment by nezbedova** [comment]
@pkudela Moc děkuji.
Zavírám.
