### ISSUE TITLE
Změna zobrazení popisků u náhledů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#610]
Odděluji od #576 

Návrh úpravy popisků pod náhledy zahrnuje několik položek, které rozdělím do jednotlivých vláken. Prosím ostatní knihovny o vyjádření.

**Comment by nezbedova** [comment]
1. Změna popisků podle jazyku.

Zobrazovat popisky stran podle zvoleného jazyka. Dle potřeby je možné si jazyk přepnout.

U CS/EN zobrazovat obě varianty nebo jen anglické popisky.

**Comment by nezbedova** [comment]
3. Zobrazit max. dva řádky, zbytek by pod náhledy nebyl vidět. V Tabulce by byl celý.
![obrazek](https://github.com/user-attachments/assets/5ccf4653-4ee2-4082-a4a9-170a721ea197)

**Comment by nezbedova** [comment]
4.    Pole s popisky pod náhledy zabírá příliš místa. V jádru zabírají asi 20% velikosti náhledu, v klientovi došlo 06.09.2024 ke zmenšení na 30% náhledu. Myslím si, že by to ještě chtělo zmenšit.

![obrazek](https://github.com/user-attachments/assets/2f327a92-fdea-4b54-ba72-e8343cb4f65b)

**Comment by nezbedova** [comment]
Odlišení čísla strany od čísla indexu.

Zde je možností více.

Původní:

![obrazek](https://github.com/user-attachments/assets/38fbac25-12cd-4ca9-b423-5a5359210981)

A. Po poslední schůzce byla doplněna čárka za číslo strany. Nyní máme toto:

![obrazek](https://github.com/user-attachments/assets/1c87d971-1124-4c43-b9e7-66b69f1fae04)

B. Další možností je barevné odlišení. Upozadit číslo indexu šedivou barvou:

![obrazek](https://github.com/user-attachments/assets/2d6d6b4f-cc6d-4507-a638-5fd88f8f877a)

C. Změna stylu písma. Upozadit index strany kurzívou nebo zvýraznění čísla strany tučně.

![obrazek](https://github.com/user-attachments/assets/ae2c5423-e5d9-4f4c-96f8-b20e4f4ccb53)

D. Kombinace všeho, ale to nám přijde příliš, proto bez ukázky.

@albertoh Nevím, zda je nějaké odlišení barvou nebo stylem písma možné.

Za KNAV by bylo nejlpší - přidání čárky, zesvětlení indexu šedou.

![obrazek](https://github.com/user-attachments/assets/9001b238-e5d6-451b-9bf9-9016e809207b)

![obrazek](https://github.com/user-attachments/assets/18fffe38-ff08-49db-b9e5-dafd91f16a3c)

**Comment by SmejkalovaAnna** [comment]
@albertoh aby se na to nezapomnělo, na masteru se jazyková mutace CS/CS zobrazuje úplně stejně jako ta hybridní CS/EN. Měl by tam být ten popisek jen v  CS, jako je to ve variantě EN/EN.

**Comment by pkudela** [comment]
@nezbedova pokusim se nejak poskladat, upravit radky atd. a dam to k testovani, kdyz tak opripominkujete. Nicmene bavil jsem se s Lukasem a tam je jedna dulezita vec. Vyse uvedene upravy jdou provest pouze v pripade, ze se jedna o uloziste akubra, pak to lze na strane klienta poskladat, ale pokud se jedna o uloziste fedora, tak tam uz api vraci poskladany retezec a do toho bohuzel nelze sahat i kvuli pripadnym vykonostnim problemum. Cili to co udelam se bude zobrazovat jen v pripade, ze dana instance proarc bezi pod akubrou, jinak to bude postaru, ale s ohledem na to, ze vetsina postupne na akubru prechazi, nebo prejde, tak v tom problem nevidim.

**Comment by pkudela** [comment]
Dobry den @nezbedova nasadil jsem novou verzi na master, prosim otestujte tuto url -> https://proarc-master.inovatika.dev/import/edit/654 - je nutne to otestovat pri zmensovani sirky bloku, pak se texty zobrazuji ruzne v zavislosti na konkretnim rozliseni

Provedl jsem nasledujici upravy zatim pouze pro import:

- v importu zobrazuji: pageNumber, pageIndex, pageType
- zmensil jsem velikost/odsazeni radku v popisku
- omezil vysku bloku popisku aby se zobrazovaly jen prvni 2 radky
- doplnil tooltip, takze plny text se zobrazuje po najeti mysi
- zobrazuji jen to, co existuje, takze napr. u 3 polozky s vyse uvedeneho odkazu se nezobrazuje pageType, protoze v datech neni a u vsech ostatnich mimo posledni polozky chybi pageNumber
- ztucnil jsem page number, aby to bylo vice odlisene, ale muzu zase odstranit, pokud by nevyhovovalo
- pokud by byl nejaky retezec delsi, bez mezery a figuroval na prvnim, nebo druhem radku, tak se orizne a doplni texkama viz. screenshot s prikladem nize

<img width="148" alt="image" src="https://github.com/user-attachments/assets/3eb6f37d-41d7-4b7c-b9dd-cb4be241b109">

**Comment by pkudela** [comment]
@nezbedova v jakem formatu se to ma zobrazovat v ulozisti? Muzete mi poslat textove zformatovane co a jak mam v ulozisti zobrazovat? Dekuji

**Comment by nezbedova** [comment]
@pkudela 
Skvělé! Děkuji.

Jen u u indexu strany se vlevo zobrazuje složená závorka místo kulaté.

> doplnil tooltip, takze plny text se zobrazuje po najeti mysi

![obrazek](https://github.com/user-attachments/assets/0f29e05c-7fb6-42f0-85ca-9663424bd1e5)

K tomuto:

> ztucnil jsem page number, aby to bylo vice odlisene, ale muzu zase odstranit, pokud by nevyhovovalo

se musí vyjádřit i ostatní knihovny. 

Udělala jsem sem nějaké ukázky pro ostatní:

![obrazek](https://github.com/user-attachments/assets/eb6dda7d-dd0d-4d8c-b8e6-7e0e928a5011)

**Comment by nezbedova** [comment]
@pkudela 

> v jakem formatu se to ma zobrazovat v ulozisti? Muzete mi poslat textove zformatovane co a jak mam v ulozisti zobrazovat? Dekuji


Než se dohodneme s ostatními, tak takto:
![obrazek](https://github.com/user-attachments/assets/462a9d29-f188-432e-a37a-a670e8e8336a)



Tj. stejně jako na importu jen bez čísel indexu a bez tučného čísla strany.

A bez této chybky, která je nyní v úložišti.

![obrazek](https://github.com/user-attachments/assets/33a1cb97-d005-4985-b543-71f0e6809aeb)

**Comment by pkudela** [comment]
> @pkudela
> 
> > v jakem formatu se to ma zobrazovat v ulozisti? Muzete mi poslat textove zformatovane co a jak mam v ulozisti zobrazovat? Dekuji
> 
> Než se dohodneme s ostatními, tak takto: ![obrazek](https://private-user-images.githubusercontent.com/13831946/366441702-462a9d29-f188-432e-a37a-a670e8e8336a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTU2NzYsIm5iZiI6MTcyNjA1NTM3NiwicGF0aCI6Ii8xMzgzMTk0Ni8zNjY0NDE3MDItNDYyYTlkMjktZjE4OC00MzJlLWEzN2EtYTY3MGU4ZTgzMzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MWE3ZWYzMDliYzZhNWUzM2UzY2Q1OWRiNWZkYmUyMjIzOWVhZjJlY2ZlZDFhM2U3NGYxMTlmYTdlZDA0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yB3dhICGlfjSpuIUAlsOCRQDWO--6oElfqXFmXaRUyQ)
> 
> Tj. stejně jako na importu jen bez čísel indexu a bez tučného čísla strany.

OK, rozumim

> 
> A bez této chybky, která je nyní v úložišti.

To bylo pro debugovani, omylem jsem na to zapomel.

> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/366440611-33a1cb97-d005-4985-b543-71f0e6809aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTU2NzYsIm5iZiI6MTcyNjA1NTM3NiwicGF0aCI6Ii8xMzgzMTk0Ni8zNjY0NDA2MTEtMzNhMWNiOTctZDAwNS00OTg1LWI1NDMtNzFmMGU2ODA5YWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZTBhOTExYmRmMTg1Mjg4NWNiOGFmNDYzYmE5MDE2MjJhNzM3NjA1OTRhNTA5ZGU2OTJmNDBlMjA2ODQ3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZBX8dfRXbjdD7eDqatRrpXOpfOVEWL5F_nr_SJy6Uw)

**Comment by pkudela** [comment]
> @pkudela Skvělé! Děkuji.
> 
> Jen u u indexu strany se vlevo zobrazuje složená závorka místo kulaté.

To opravim.

> 
> > doplnil tooltip, takze plny text se zobrazuje po najeti mysi
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/366430622-0f29e05c-7fb6-42f0-85ca-9663424bd1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTU2NzYsIm5iZiI6MTcyNjA1NTM3NiwicGF0aCI6Ii8xMzgzMTk0Ni8zNjY0MzA2MjItMGYyOWUwNWMtN2ZiNi00MmYwLTg1Y2EtOTY2MzQyNGJkMWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTM4ZTM3NDI4Njg3MWVlNTNhNWU0ZjMwNWVlMDZjZjQwNDM5ODNhOTIzYWRjNjFiZGI0OWYxOWRjMWVjZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TdrM10xjZdqopCsM8xgNVlMVSGCNk4C6GrW0ON3uhBs)
> 
> K tomuto:
> 
> > ztucnil jsem page number, aby to bylo vice odlisene, ale muzu zase odstranit, pokud by nevyhovovalo
> 
> **se musí vyjádřit i ostatní knihovny.**

OK, neni problem to dat pripadne pryc, pockam tedy.

> 
> Udělala jsem sem nějaké ukázky pro ostatní:
> 
> ![obrazek](https://private-user-images.githubusercontent.com/13831946/366432518-eb6dda7d-dd0d-4d8c-b8e6-7e0e928a5011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTU2NzYsIm5iZiI6MTcyNjA1NTM3NiwicGF0aCI6Ii8xMzgzMTk0Ni8zNjY0MzI1MTgtZWI2ZGRhN2QtZGQwZC00ZDhjLWI4ZTYtN2UwZTkyOGE1MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGExMTY3Y2FjNjMxYTE4NTA5NjE4YzI5MjVmMGNhYmZlNzQzNjcxNGI1NGJmYTRjMGQwYTE2ZTQyMzA2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4nO-om1KdQ_DXixxOggfqzUiEfdYgaRMLMOpO_X-E8)

**Comment by SmejkalovaAnna** [comment]
@pkudela Petře proč je v úložišti u prázdné strany v mutaci CS/CS (blank)? To by tam asi nemělo být...? 
![obrazek](https://github.com/user-attachments/assets/a83576e8-174a-4490-adad-342a0e378279)

**Comment by SmejkalovaAnna** [comment]
Za mě jsou ty popisky absolutně geniální! Jen bych dala tučně i čísla stran v repozitáři...? @nezbedova ?

**Comment by pkudela** [comment]
> @pkudela Petře proč je v úložišti u prázdné strany v mutaci CS/CS (blank)? To by tam asi nemělo být...? ![obrazek](https://private-user-images.githubusercontent.com/24409660/366735191-a83576e8-174a-4490-adad-342a0e378279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzEyODcsIm5iZiI6MTcyNjEzMDk4NywicGF0aCI6Ii8yNDQwOTY2MC8zNjY3MzUxOTEtYTgzNTc2ZTgtMTc0YS00NDkwLWFkYWQtMzQyYTBlMzc4Mjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZWZkNzA3MWQ2NjdiMTJmNmYzNDlkN2QzMDZhZTgxZjA1OTM1YjEzZDYxYzMxZmNjZmJhMzdlMDhhYTc5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XXNqcnmF5EygXfQOWxbAkLqVM8dnuA5atJyQTnZKEto)

Ahoj, muzes mi prosim poslat i url? Podivam se a prozkoumam.

**Comment by SmejkalovaAnna** [comment]
@pkudela https://proarc-master.inovatika.dev/repository/uuid:a5765130-73e7-4526-9c01-dbe423721b2b

**Comment by ZdenkaSera** [comment]
@pkudela Prosím, úpravu popisků neuspěchejte pro nejbližší verzi, tady musí být prostor pro ostatní, aby se vyjádřili a musíme pak najít řešení přijatelné pro všechny. Moc díky!

**Comment by pkudela** [comment]
> @pkudela Prosím, úpravu popisků neuspěchejte pro nejbližší verzi, tady musí být prostor pro ostatní, aby se vyjádřili a musíme pak najít řešení přijatelné pro všechny. Moc díky!

@ZdenkaSera necham to tedy v tomto stavu, aby bylo k testovani a po vydani verze a otestovani budu resit a doladovat dle vyjadreni vsech, ok?

**Comment by ZdenkaSera** [comment]
@pkudela Ano, prosím 👍

**Comment by luckajirku** [comment]
ještě to projdeme pořádně, ale určitě nechceme to tučné číslo strany. Tučně bychom nechali jen celý popisek u represtrany. 
Oddělení čárkou nám vyhovuje.

**Comment by pkudela** [comment]
> ještě to projdeme pořádně, ale určitě nechceme to tučné číslo strany. Tučně bychom nechali jen celý popisek u represtrany. Oddělení čárkou nám vyhovuje.

ok, az to projdete, shrn to v bodech a ja dle toho upravim

**Comment by SmejkalovaAnna** [comment]
@luckajirku Lucko prosím tě, rozmyslete si to s tím tučným číslem ještě, pro nás je to hrozně příjemný a přehledný.... díky.

**Comment by luckajirku** [comment]
za nás to tučný fakt ne, to tam hrozně řve. Pokud se má odlišit teda číslo strany a index, tak jsme pro to upozadit ten index (dát ho šedě), ale ne zvýrazňovat stranu.

**Comment by SmejkalovaAnna** [comment]
Já zase nechci, aby to bylo celý slitý do jednoho optickýho nepřehlednýho chumlu, takhle je na první pohled vidět, co je číslo strany, tím, že uděláme šedivý index, to bude ještě nevýraznější....

**Comment by luckajirku** [comment]
Domluva byla, že se dá do verze pouze to oddělení stránky čárkou a nad zbytkem návrhů se pobavíme (ne že hned nejvýraznější návrh implementujeme) později, až se tomu budou moci věnovat i další knihovny. Bohužel se právě tohle začalo intenzivně řešit přesně v tom jediném měsíci, kdy jsme se my a MKP potřebovali naplno věnovat projektu z výzvy, na kterou jsme čekali 3 roky... 
Co jsme prošli tady ty komenty, tak i z MZK bylo, že nejvíc se líbí varianta A (tzn. nechat jak je, jen doplnit čárku)...

Takže pro @pkudela v bodech, jak si přál:-) - co by vyhovovalo nám:
- tučné písmo nechat pouze pro celý popis u represtrany
- oddělit čárkou číslo strany / index
- písmo jinak nechat stejné, max. pokud budou ostatní trvat na nějakém zvýraznění, tak upozadit ten index (dát ho šedě)

**Comment by SmejkalovaAnna** [comment]
@luckajirku Dobře, pobavíme se o tom na schůzce i s MZK a MKP.

**Comment by pkudela** [comment]
> @luckajirku Dobře, pobavíme se o tom na schůzce i s MZK a MKP.

Zatim tedy nechavam a upravim na zaklade dohody ze schuzky.

**Comment by luckajirku** [comment]
a nejde už teď vrátit verzi bez toho vytučněného čísla strany jen s tou čárkou, jak byla původní dohoda?

**Comment by luckajirku** [comment]
jen ještě přidám poznámku - pokud by mělo zůstat to tučné číslo strany, je potřeba pak změnit zvýraznění represtrany (https://github.com/proarc/proarc-client/issues/485) z tučného písma na něco jiného - třeba podbarvení toho řádku, resp. panelu s náhledem.

**Comment by pkudela** [comment]
> a nejde už teď vrátit verzi bez toho vytučněného čísla strany jen s tou čárkou, jak byla původní dohoda?

Ahoj, vratim to tak jak pises a sem jen hodim screenshoty pro ukazku jak to bylo.

**Comment by pkudela** [comment]
> > a nejde už teď vrátit verzi bez toho vytučněného čísla strany jen s tou čárkou, jak byla původní dohoda?
> 
> Ahoj, vratim to tak jak pises a sem jen hodim screenshoty pro ukazku jak to bylo.

tak je to tam, nasazeno na masteru, je to jak si chcela viz. screenshot

<img width="688" alt="image" src="https://github.com/user-attachments/assets/c421411f-30b2-45cd-a5f0-00d57241b036">

**Comment by ZdenkaSera** [comment]
@pkudela **Verze B** s čárkou za číslem strany, upozadit index. - dohoda na schůzce 8.10.2025

**Comment by pkudela** [comment]
hotovo, nasazeno na serveru

**Comment by nezbedova** [comment]
@pkudela Za nás super. Děkujeme.

![obrazek](https://github.com/user-attachments/assets/6cfc1f7a-0cac-4942-8701-c5b1600c348d)

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, je to ok i pro vás? Děkuji.

**Comment by ZdenkaSera** [comment]
@luckajirku Navrhuji to k uzavření, protože nikdo nerozporoval poslední verzi - @luckajirku - díky za případný komentář.
