### ISSUE TITLE
Formulář Nový záměr - chybí upozornění na nevyplněná pole

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#612]
Inovatika - Klient: Verze v2.3.0 (12.09.2024)Jádro: Verze 4.2.0-SNAPSHOT - Build 20240904180804

Při zakládání nového záměru chybí varován, že nejsou vyplněna povinná pole. Záměr lze uložit. 

Prosím o doplnění stejně jako tomu je při zakládání Nového objektu.

![obrazek](https://github.com/user-attachments/assets/4baf67dc-c330-48a4-a341-18920d7c10b4)

Není nutné to dávat do nejbližší verze.

**Comment by SykoraLukas** [comment]
Při stažení záznamu z katalogu je tato kontrola dle jiných issue vypnuta. Při editaci ve formuláři vy poté již mělo křičet upozornění na některá pole.

**Comment by nezbedova** [comment]
@SykoraLukas Při stažení i editaci to je stejné. Mám červená pole, která mám vyplnit. Pokud je nevyplním, tak se formulář uloží bez varování s nevyplněnými poli. 

Pokud by to dávalo hlášku o nevyplnění povinných polí při editaci, tak by to bylo dobré.

**Comment by SykoraLukas** [comment]
Našel jsem chybu, nevaliduje se totiž vůbec při ukládání formuláře ve workflow. Opravím s tím, že při načtení do formuláře z katalogu ponechám vypnuté kontroly ale ve formuláři poté již budou fungovat jako při zakládání objektů mimo workflow.

**Comment by nezbedova** [comment]
Otestováno. Funguje. Děkuji.
