### ISSUE TITLE
Chyba v zobrazení při návratu do záměru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#613]
Pokud dokončím úkola kliknu na tlačítko Záměr, tak se objeví toto:

![obrazek](https://github.com/user-attachments/assets/aaf6c447-faa8-4462-b4cf-b16a63ade56f)

Až po kliknutí na slovo WorkFlow se zobrazí to, co tam má být vidět. 

Není nutné upravovat to do nejbližší verze.

**Comment by albertoh** [comment]
Opraveno
