### ISSUE TITLE
Ukládání poznámky vyskočí chyba

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#614]
Při doplnění poznámky do záměru nebo podzáměru vyskočí chybová hláška.:

![obrazek](https://github.com/user-attachments/assets/978211a1-18f4-4910-9859-2f9e6d22d5af)

Po jejím zavřením se poznámka zapíše. 

Oprava nespěchá.

**Comment by albertoh** [comment]
Jiz opraveno
