### ISSUE TITLE
WorkFlow - úprava sloupce Datum dok. úkolu v záměrech

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#615]
1) Prosím o upravení datumu dokončeného úkolu na stejný tvar jako je to ve sloupci Upraveno
 
![obrazek](https://github.com/user-attachments/assets/3765bbb8-4b43-4880-bf79-b03da1c09347)

2) Sloupec Datum dokončeného úkolu se špatně řadí. Řadí se podle číslic a ne podle data.

![obrazek](https://github.com/user-attachments/assets/d1b332db-13a9-4d12-8d88-db324b07fd67)

3) Po dokončení úkolu se sloupec seřadí "nevím podle čeho". Upravovala jsem Úprava skenů LIMB ve žlutě označeném záměru.

![obrazek](https://github.com/user-attachments/assets/ee95a201-87d9-4041-bfd9-94c30d6b5e9b)

**Comment by albertoh** [comment]
Opraveno. Je nutne resetovat sloupce

**Comment by nezbedova** [comment]
Ve WorkFlow to je správně, ale hodiny zmizely i v Úložišti. Tam je potřeba, aby zůstaly. V jádru to tak bylo. Půjde to rozdílně nastavit i zde?

**Comment by albertoh** [comment]
Opraveno

**Comment by nezbedova** [comment]
Otestováno. Děkuji.
