### ISSUE TITLE
WorkFlow - chybí blokace a info o nevyplněných povinných polích v úkolech

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#617]
U úkolu skenování a Úprava skenů v Limb je v xml zadaný blokátor u polí Počet skenů. Je to nastavené tak, aby nebylo možné dokončit úkol s nevyplněným polem (počtem skenů, které se zpracovaly).

V jádru to je takto zvýrazněné:

![obrazek](https://github.com/user-attachments/assets/a3e53d91-544e-45a3-a7dd-e7841e6e4620)

V klientovi se úkol dokončí bez varování.

**Comment by albertoh** [comment]
Doplneno
