### ISSUE TITLE
WorkFlow - návrat z úkolů do záměrů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#618]
Po dokončení úkolu se automaticky nepřepnu na seznam záměrů. Zůstanu na vyplněném úkolu a musím kliknout na tlačítko Záměr. 

Zatím s tím dokážeme žít, ale v jádru jsme to už měli upravené.

**Comment by albertoh** [comment]
To znamena pri ulozeni a stav = dokoncen vratit na zamer?

**Comment by nezbedova** [comment]
@albertoh Ano. Po kliknutí na dokončen a Uložit automaticky přeskočit do záměrů.

**Comment by albertoh** [comment]
Opraveno
