### ISSUE TITLE
V editaci nejsou vidět názvy podřízených objektů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#621]
V úložišti v editaci  zmizely názvy podřízených objektů - příklad vícedílná monografie se dvěma díly:

![image](https://github.com/user-attachments/assets/597f6086-af0b-4826-a13b-040caaeb89f9)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Díky, na masteru vypadá ok pro VD, přílohy i periodika.

**Comment by ZdenkaSera** [comment]
Přetestováno lokálně v KNAV na 4.2.3/2.3.2 - je to ok, díky. Zavírám.
