### ISSUE TITLE
Příloha je ve validaci v úložišti nesprávně vyhodnocena jako chybná

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#623]
Pokud v editaci v úložišti spustíme (původní historickou) validaci nad monografií s přílohou, je příloha označena jako chybná. Narazili jsme na to už před časem (není to tedy problém nejnovější verze). Tato chyba nebrání další práci s přílohou. 
Napadlo mě, jestli tu není podobnost s https://github.com/proarc/proarc/issues/1717 , tj. že validace nerespektuje začátek nového objektu.

Dnešní příklad na masteru:

![image](https://github.com/user-attachments/assets/8cc5180c-5c35-4fd9-ad7f-5b3bda3220ed)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Na masteru test na monografii s přílohou a vícedílné monografii - vypadá to dobře, díky.

**Comment by ZdenkaSera** [comment]
Přetestováno lokálně na 4.2.3/2.3. 2 - validace v editaci funguje na strukturovaných objektech správně, jen je zapotřebí doladit chování počitadla kontrolovaných objektů. Založím nové issue + testovací data na masteru, toto zavírám.
