### ISSUE TITLE
Nezobrazování čísla a data vydání ve sloupci Název

### ISSUE THREAD

**Issue by lepsij** [proarc/proarc-client#624]
V nové verzi ProArcu se nám v tabulce nezobrazují informace ve sloupci Název (číslo a datum vydání) po jejich rozkliknutí, vždy jen probliknou a zmizí, problém se objevil již v předchozí verzi. Dosud se tam zobrazovalo to, co se teď zobrazí až po najetí kurzoru (viz přílohy).

![chyba](https://github.com/user-attachments/assets/897eaa9a-0a39-4689-b1fb-a67053f8c266)
![chyba2](https://github.com/user-attachments/assets/7c5018c5-b92a-4aa5-90fe-881416aea134)

**Comment by ZdenkaSera** [comment]
Dobrý den, už je to na masteru na inovatice vyřešené - zde issue https://github.com/proarc/proarc-client/issues/621
