### ISSUE TITLE
Verze klienta 2.3.2 nedovoluje přihlášení

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#626]
Nasadil jsme novou verzi klienta 2.3.2 - nelze se do ní přihlásit. Zatím tedy máme nasazenu kombinaci klienta 2.3.1 s jádrem 4.2.3

**Comment by albertoh** [comment]
Co presne dela?

**Comment by ZdenkaSera** [comment]
Issue je zatím založeno jen jako upozornění, doplníme později.

**Comment by ZdenkaSera** [comment]
Po odkliknutí "přihlášení" se systém vrátí zpátky na toto okno, uživatel i heslo zůstanou vyplněné. Zdá se, že neprobíhá autorizace/autentizace.

![image](https://github.com/user-attachments/assets/b740abd2-2317-4592-ac98-862569b79b71)

**Comment by PetrKotynek** [comment]
[hlasky.txt](https://github.com/user-attachments/files/17187235/hlasky.txt)
![chyba4](https://github.com/user-attachments/assets/96652b86-2294-4eee-ad8b-35e2a9000201)
![chyba](https://github.com/user-attachments/assets/9aab55f1-090d-4023-9da5-22f38f690a8c)
![chyba2](https://github.com/user-attachments/assets/26c16f3f-4217-4913-a556-cc3c7004cbb4)
![chyba3](https://github.com/user-attachments/assets/ff616e44-6357-4837-8510-d55d95b6b0f0)

**Comment by PetrKotynek** [comment]
On tam očekává JSON a dostává html PK

Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by PetrKotynek** [comment]
![jsonerr](https://github.com/user-attachments/assets/85bb1195-dd32-493e-bdf1-74e8f400227e)

**Comment by SykoraLukas** [comment]
Jak se chová starý klient? Tam přihlášení funguje?

**Comment by PetrKotynek** [comment]
Tady máme endpoint  dotazujem se špatně 

https://proarc-ozc-old.lib.cas.cz/api/isLogged 

máme tady a nikde jinde ( to api je tam navrch )
https://proarc-ozc-old.lib.cas.cz/proarc/isLogged
{"login":"proarc","state":"logged","remaining":17950,"maximum":18000}

PK

**Comment by PetrKotynek** [comment]
Ano starý funguje, vyhazuje to až novinka v js isLogged PK

**Comment by PetrKotynek** [comment]
Zkusim to přepsat ve zdroji. PK

**Comment by PetrKotynek** [comment]
Po oprave checkLogged(): Observable<any> { atd
to zapomene vymazat  login ale app funguje včetně nějakého odpočtu. Takže se těším na profi opravu. PK


![po_oprave](https://github.com/user-attachments/assets/cf086358-5f59-4bb2-ac69-617a9fd581fb)

**Comment by albertoh** [comment]
Jo problem je v volani pres api
Opravim a zbuilduju znova

**Comment by albertoh** [comment]
Novy zip je k dispozici. Otestujte, prosim

**Comment by PetrKotynek** [comment]
Dekuji,
ale zustava tam viset ten login a po tuknuti se to rozjede.  Ještě to zkusím vedle. PK

![visici_login](https://github.com/user-attachments/assets/bf69b553-d71a-4d7c-8a41-0eb690b1b12a)

![po_tuknuti](https://github.com/user-attachments/assets/eac53254-3887-41eb-a04e-d498b26ae1ee)

**Comment by PetrKotynek** [comment]
Ano na druhé mašině to samé, login nemizí, až když se zvolí nějaká akce začne odpočet a PA. PK

**Comment by PetrKotynek** [comment]
Bez ohledu na konfiguraci se isLogged počítá od 3600. PK

{"login":"proarc","state":"logged","remaining":3550,"maximum":3600}

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Odpočty zatím nemohu komentovat, zde jen ilustrace k uživatelskému pohledu na přihlášení. 
Jak zmiňují příklady výše, po zadání uživatele a hesla jsem na této obrazovce a ta zůstává "viset" i po použití enteru nebo tlačítka "přihlásit". Pokud ale na této obrazovce vyberu funkci z horní lišty (např. "Hledat"), úložiště se otevře.  Je to tedy sice funkční, ale matoucí.


![image](https://github.com/user-attachments/assets/128ea709-c9b3-4997-aa9b-a72d2e1842b2)

**Comment by PetrKotynek** [comment]
Zdá se, že hodnota logged se nějakým záhadným způsobem odvozuje přímo z frameworku potažmo Tomcatu
na mašině kde je v Tomcatu session-timeout 30 se startuje na 18000  i když je nastaveno
proarc@proarc-ozc-old-test:~$ cat ~/work_data/proarc.cfg |grep sessionTimeout
#proarc.sessionTimeout=180000
proarc.sessionTimeout=17925
ale může tam být libovolně cokoli jiného. Na mašině kde je session-timeout 180 to hází výchozí hodnotu  dokonce 3600. 
To jsem z toho jelen. PK

![hodnota_logged](https://github.com/user-attachments/assets/b418a8f6-3340-4d42-bce0-b09de2a1ebaa)

**Comment by ZdenkaSera** [comment]
Otestovala jsem odhlašování - po vypršení času naskočila hláška a po jejím odkliknutí se klient vrátil na login, za mne funkčnost ok, ještě počkáme na reakci uživatelů.

![image](https://github.com/user-attachments/assets/9ddba580-2181-4a27-a970-2c311d005609)

**Comment by ZdenkaSera** [comment]
Označila jsem issue jako prioritní - prio se týká přihlašování https://github.com/proarc/proarc-client/issues/626#issuecomment-2384896985

**Comment by SykoraLukas** [comment]
Přihlášení opraveno, novy build klienta v releasu 2.3.2

**Comment by PetrKotynek** [comment]
Vyzkoušeno v prostředí KNAV , login proběhne jak je zvykem. Děkuji PK

**Comment by PetrKotynek** [comment]
sessionTimeout: Zkoušeno v Edge , neodpojí ani po 1/2 hodině, ani po hodině. Ukazatel času vpravo nahoře přeskočí na 59:59 a dál odčítá. Navrhuji oddělit do extra issue , ač to "trochu" souvisí ta podstatná část tohoto případku byla vyřešena.PK 
Client: version v2.3.2 (02.10.2024)Core: version 4.2.3 - build 20240926135745
proarc.sessionTimeout=1800

**Comment by albertoh** [comment]
Nemuzu reprodukovat. U me funguje (proti masteru)

**Comment by PetrKotynek** [comment]
Ještě  poznámka, pozoruji to na další mašině. Výchozí hodnota pro odpočet odpovídá Tomcatu a při jetí naprázdno to má po 1/2 hodině to natočilo 111 requests  62.2 kB transferred. Neprobozi to ten isLogged ? PK

**Comment by PetrKotynek** [comment]
Když zakometuji proarc.sessionTimeout odpočet se nastaví na hodinu, i na stroji který má 3 hodiny na Tomcatu. PK 
proarc-test@proarc-ozc:~$ cat apache-tomcat-9.0.91/conf/web.xml |grep session\-timeout
        <session-timeout>180</session-timeout>

proarc-test@proarc-ozc:~$ cat ~/work_data/proarc.cfg |grep sessionTimeout
 #proarc.sessionTimeout=180000
#proarc.sessionTimeout=180000

login: "proarc", state: "logged", remaining: 3191, maximum: 3600}
login
: 
"proarc"
maximum
: 
3600
remaining
: 
3191
state
: 
"logged"

**Comment by PetrKotynek** [comment]
A na stroji s 30 minutovým Tomcatem
proarc@proarc-ozc-old-test:~$  cat apache-tomcat-9.0.91/conf/web.xml |grep session\-timeout
        <session-timeout>30</session-timeout>

to nasaje 18000 jakoby řádově špatně 1800. Co je v konfigu lhostejno. PK

{login: "proarc", state: "logged", remaining: 17981, maximum: 18000}
login
: 
"proarc"
maximum
: 
18000
remaining
: 
17981
state
: 
"logged"

**Comment by PetrKotynek** [comment]
Tak konečně. Platí to co je v Tomcatu nebo to co je v proarc.sessionTimeout ale pouze v rámci běhu Tomcatu, tj. změna rovná se nastavit předem a VOTOČIT celé i s Tomcatatem. Bezva fíčura. PK
