### ISSUE TITLE
eČlánek - nevalidní element Genre

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#627]
Pokud u článku, který není recenzovaný, vyplním v  Žánru (genre) typ obsahu (type), ve formuláři pro eČlánek se objeví, že je element Žánr nevalidní. 
![nevalid-genre](https://github.com/user-attachments/assets/824b74e6-9b0a-49c1-9b03-42740d6597a9)
U recenzovaného eČlánku je vše v pořádku. 
Testováno v PA klient: v2.3.2, jádro: 4.2.3
Vím, že kolem eČlánku a žánru bylo hodně práce, ale už se blížíme ke zdárnému konci! :)
Díky! M.

**Comment by tumovam** [comment]
Tak trochu jiná chyba. Zkusím popsat... ve "vazbách" pod Číslem zakládám Nový objekt - eČlánek. Nestahuji, ale vyplňuji ručně. Zaškrtnu, že jde o nerecenzovaný článek. Vyplním "News" a další údaje ve formuláři. Uložím. Po uložení si ale uvědomím, že to vlastně není Zpráva (News), ale třeba "Introduction". Vyberu z roletky. Uložím. A v XML se objeví dva elementy:
![obrazek](https://github.com/user-attachments/assets/7e0b57f6-68f8-4479-a21d-8a1463c73867)

Namísto očekávaného:
![obrazek](https://github.com/user-attachments/assets/edcaf2a6-8798-4a2a-b6a3-217f2c9e189b)

Jako pozitivní beru, že elementy se nenásobí s každým dalším uložením. Když opravuji ještě jednou, stále jsou pouze dva elementy, ne tři atd.
@SykoraLukas podíváš se na to ještě, prosím? U recenzovaného eČlánku se mi stejnou chybu nepodařilo nasimulovat, asi je to chyba jen u nerecenzovaného eČl. Díky

**Comment by SykoraLukas** [comment]
Opraveno, na testu

**Comment by tumovam** [comment]
> Opraveno, na testu

Super! Díky moc za rychlé opravení. Přidávám štítek u zavření. M.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
