### ISSUE TITLE
Pořadí objektů v roletce Model při vytváření nového objektu

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#633]
Prosím upravit chování roletky v dialogovém okně při zakládání nového objektu přes ´+´ tak, aby se respektovalo pořadí modelů zadané v konfiguraci. Případně prosím o vysvětlení, jak docílit toho, aby se eČlánek zobrazoval v roletce v tomto případě jako první:
![image](https://github.com/user-attachments/assets/7138c8a1-a478-4157-a3f7-8733080ae4e3)

**Comment by albertoh** [comment]
Je to tam

**Comment by ZdenkaSera** [comment]
@albertoh Alberto, prosím, je to někde v konfiguraci a můžeme to pořadí sami přeházet na jiných instancích nebo dostaneme s buildem tuhle verzi pro všechny?

**Comment by albertoh** [comment]
Zmenili jsme konfiguraci u nas, aby bylo videt eClanek na zacatku. Otestujte

**Comment by tumovam** [comment]
Na masteru _(v2.3.x-dev (04.12.2024))_ stále v pořádku - eČlánek je první. Zatím nedávám "Návrh na zavření", ale pouze "Lokální test". Po nasazení nové verze ihned otestujeme i v KNAV. Díky
