### ISSUE TITLE
Zmizela informace o exportu v úložišti

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#634]
V horním okně úložiště se místo informace o proběhlých typech exportů zobrazuje pouze příznak 0/1 - prosíme o opravu.

**Comment by albertoh** [comment]
Nemuzu to najit. U nas na masteru je poradku.

**Comment by ZdenkaSera** [comment]
Tohle je obrázek z masteru (horní okno). Nemáš v profilu vypnuté zobrazení sloupce "Export", takže to nevidíš?:

![image](https://github.com/user-attachments/assets/a9752207-0b4e-40ba-af7f-39524cf7566a)

**Comment by albertoh** [comment]
Zkus resetovat nastaveni sloupcu

**Comment by albertoh** [comment]
Ja to vidim tak:
![image](https://github.com/user-attachments/assets/b2ec2da2-a708-4d86-9809-0491f1fe7df7)

**Comment by ZdenkaSera** [comment]
@albertoh Nejsi v nějaké své lokální verzi? V horním okně máš zobrazené i urn:nbn a standard, ty já mám jen ve spodním okně a pro horní ono je ani nemám v profilu v nabídce:

![image](https://github.com/user-attachments/assets/d33e318c-7369-4550-aa93-c623f9aa6f8c)

Nepomohl reset nastavení, úplný výmaz historie prohlížeče ..

**Comment by SykoraLukas** [comment]
Na jaké verzi toto prosím zkoušíš? Na Inovatice to vypadá takto: 
![image](https://github.com/user-attachments/assets/724eecbe-b168-4742-b1ee-075471b56214)

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
👍 Díky, je to ok, včetně přidaných sloupců urn:nbn a standard.
