### ISSUE TITLE
V klientovi chybí funkce obnovení smazaného objektu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc-client#635]
V jádře je ve skupině "Administrace" v úložišti funkce umožňující obnovit objekt, který nebyl smazán trvale. V klientovi jsme ji nenašli. 

![image](https://github.com/user-attachments/assets/3b3a13fb-7672-4dca-bcfa-0935ea93b754)

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Tady to asi ještě není k testu, myslím, že chybí funkce v klientovi (hledala jsem pod třemi tečkami). Prosím, kouknete na to? Díky.

**Comment by SykoraLukas** [comment]
Je to tam.
![Image](https://github.com/user-attachments/assets/44170ffd-fe39-4644-a7c5-fba588970a0c)

**Comment by ZdenkaSera** [comment]
Už ok, obnovení funkční.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
