### ISSUE TITLE
Funkčnost tlačítek u jednotlivých náhledů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#636]
Přesun z #576, kam to nepatří.

![obrazek](https://github.com/user-attachments/assets/051e208b-2ee1-4deb-a5f9-80ca26503b44)

**Comment by albertoh** [comment]
Ja bych rekl, ze to je kvuli tomu, ze mate neulozene zmeny, a tim mate zablokovany panel obrazku

**Comment by SykoraLukas** [comment]
Prosím, jak toto vypadá? Potvrdil se komentář @albertoh?

**Comment by SmejkalovaAnna** [comment]
Funguje dobře, na Inovatice to nevyzkouším, na naší verzi už funguje. Zavírám.

**Comment by SmejkalovaAnna** [comment]
Chlapi zase mi to nefunguje na současném testu v2.3.2 (11.12.2024) , mám tam nějaké plány v kombinaci s deskami, na deskách to lze příblížit u těch plánů ne.... chcete poslat ty skeny přez filesender?
