### ISSUE TITLE
Zalamování textu ve formuláři - název (titleInfo:title)

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#638]
Při zpracování eČlánku jsme narazili na problém s dlouhým názvem. 

Někdy se stává, že má článek (nejspíš to bude i u monografie) dlouhý název. V takovém případě se v současném klientovi (v2.3.2) text "ztratí":

![obrazek](https://github.com/user-attachments/assets/fd5896cb-5395-4505-988f-6de1c734bad7)

Částečně se vyřeší upravením šířky sloupců/oken, ale některé názvy jsou opravdu dlouhé a když pracujeme s více panely, tak ani to nepomůže. Nebylo by proto možné rozšířit okno pro název nebo **zalamovat i název**? U poznámek a abstraku už funguje (https://github.com/proarc/proarc-client/issues/518).

Děkuji

**Comment by pkudela** [comment]
Dobry den @tumovam , ten priklad ohledne abstraktu, ktery jste uvedla, tak tam je jiny typ pole, misto input je tam textarea, musim se podivat jak to tam ja a zkusim upravit.

**Comment by albertoh** [comment]
Opraveno

**Comment by tumovam** [comment]
Super! Děkujeme! Test 10.12.2024 na masteru. Zavírám, M.
