### ISSUE TITLE
Formulář: zvýraznit M/MA atributy

### ISSUE THREAD

**Issue by hosak** [proarc/proarc-client#64]
Včera to padlo na schůzce, tak to dám ještě sem. 
V současné verzi ProArcu je vidět, které atributy jsou M/MA a tedy vyžadují zvláštní pozornost. 
![image](https://user-images.githubusercontent.com/19148958/96080195-d5e01000-0eb6-11eb-86d5-72c794cf35b6.png)
Nový klient nic takového nemá. Chtělo by to nějak graficky odlišit prvky s touto povinností, buď přidáním povinnosti na konec názvu pole jako teď, případně jakýmkoliv jiným, chytrým řešením.

**Comment by honza-rychtar** [comment]
**Formulář**
<img width="672" alt="Snímek obrazovky 2021-04-07 v 22 54 16" src="https://user-images.githubusercontent.com/1178142/113933174-8a1e7b80-97f4-11eb-9206-8df4ecbee4b1.png">

**Nápověda**
<img width="549" alt="Snímek obrazovky 2021-04-07 v 22 55 53" src="https://user-images.githubusercontent.com/1178142/113933184-8db20280-97f4-11eb-9b49-66885537ff47.png">
