### ISSUE TITLE
Fyzický popis (physicalDescription:form)

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#640]
V novém klientovi (v2.3.2), když vyplním hodnotu "počítač" a uložím, tak se správně přidá i druhý element "online zdroj":

![obrazek](https://github.com/user-attachments/assets/cb73f7bf-768f-428b-85f7-d9092ba69efb)

Když ale vyplním hodnotu "bez media", očekávám, že se po uložení přidá druhý nový element s hodnotou "svazek" (mods:form authority="rdacarrier" type="carrier">svazek</mods:form) , to se ale nestane. 

S dovolením přidávám label "chyba" 🙂

**Comment by SykoraLukas** [comment]
Týká se jen eČlánku nebo mám oboje udělat i pro NDK eČlánek?

**Comment by tumovam** [comment]
> Týká se jen eČlánku nebo mám oboje udělat i pro NDK eČlánek?

Zpracovatele v tuto chvíli nejvíce pálí eČlánek - ten je prioritní. Ideální by ale bylo, mít to časem připravené i pro NDK eČlánek. Díky

**Comment by SykoraLukas** [comment]
Takže to rovnou uděláme jak pro hodnotu _počítač_ tak pro hodnotu _bez media_ i u NDK eČlánku.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
