### ISSUE TITLE
Automatický přesun na poslední vytvořený objekt

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#641]
Automatické "přeskakování" na poslední vytvořený objekt (např. eČlánek, NDK Číslo nebo NDK Ročník) bez nutnosti scrollování.

Když zpracovatel tvoří hodně eČlánků (stejně tak NDK Čísel nebo NDK Ročníků), tak se v Tabulce sice nově založený objekt objeví na posledním místě, ale "neposune/nepřeskočí" se v Tabulce. Pořád jsou vidět jen ty články, co zpracovatel vytvořil první. Pokud potřebuje vidět ty naposledy vytvořené, musí scrollovat dolů, což při běžné práci hodně držuje. 

Současný stav:

![obrazek](https://github.com/user-attachments/assets/93ddb0a9-43b6-4e24-9aee-8639ae2fdbbf)
![obrazek](https://github.com/user-attachments/assets/57b6d7b8-da66-4070-b4ac-d1661c33bdb8)

Dříve, podle zpracovatelů lépe, po založení eČlánku se ve Vazbách rovnou automaticky posunulo dolů na označený nově vytvořený článek:

![obrazek](https://github.com/user-attachments/assets/ae06ed62-d46f-4612-9a4d-675789ff7221)

Testováno v klientovi v2.3.2

**Comment by tumovam** [comment]
Za nás v pořádku 👍 
Obrazovka se ihned po uložení automaticky posune dolů na nově vytvořený a označený (podbarvený) objekt. Vše bez nutnosti doplňkového scrollování. Děkujeme
_(test na masteru 3.12.2024 ve v2.3.2 (02.12.2024), jádro 4.2.3-SNAPSHOT)_

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
