### ISSUE TITLE
v úložišti nejsou vidět objekty

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#645]
V poslední verzi přestaly být v klientovi vidět v úložišti objekty - v Hledat je úplně prázdno. Zkoušeli jsme u nás na PA3 a na testu na masteru. V jádře objekty vidět jsou.

**Comment by SykoraLukas** [comment]
Nedaří se nasimulovat, data normálně vidím. Můžeš prosím poslat screenshot včetně url adresy a uživatele, pod kterým to nejde?

**Comment by luckajirku** [comment]
třeba na masteru pod svkhkadmin:
![BEZOBJEKTU](https://github.com/user-attachments/assets/2e2047cc-b76f-4189-ad63-2b8a3432c915)

**Comment by SykoraLukas** [comment]
Můžeš prosím vybrat nějaké model a dát znovu filtrovat? A poslat screenshot včetně url adresy?

**Comment by albertoh** [comment]
Muzes, prosim, vycistit cache?

**Comment by luckajirku** [comment]
OK, vyčistěno a jde to. Ale ten klient je teda dost přecitlivělej, nešlo to u nás nikomu, ani kolegům, který toho zase tolik neotevírají...

**Comment by albertoh** [comment]
Byly tam dost zasadne zmeny. Az to prepisu na nastaveni podle #594 zkusim to udelat odolneji
