### ISSUE TITLE
Klient hlásí chybu 500 při delší operaci

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#647]
V posledních dnech nám ProArc hlásil error - chybu 500. Vždy při delších operacích (např. reindexace). Konkrétně:
![500](https://github.com/user-attachments/assets/e56f50e3-f0d7-47c4-924b-2200e64a68c5)

Naši admini přišli na to, že se 500 objeví přesně po 5 minutách a odpovídá parametru Timeout 300 v konfiguraci apache2. Nyní máme timeout zvýšený na 1800s. Chyba se zatím znovu neobjevila. 

Domníváme se, že spoléhat na timeout je špatné (mj. proto že dopředu nejsme schopni odhadnout celkovou dobu procesu). Možná bychom se měli zamyslet nad úpravou ProArcu - spustit proces, a pak přes callback se z prohlížeče dotazovat na stav.

**Comment by SykoraLukas** [comment]
Toto je duplicitní k https://github.com/proarc/proarc-client/issues/326.

Nejlepší by bylo najít všechny procesy, které trvají déle a předělat je po vzoru exportů na procesy zapsané ve správě procesů.
Bohužel zrovna proces reindexace je taková sporná věc, protože by se nereindexovalo hned, ale až ve chvíli, když na proces přijde řada. Museli by si uživatelé zvyknout na jiné chování aplikace - proto navrhuji toto projít na schůzce.
