### ISSUE TITLE
Možnost zapisovat v rámci `<note>` URL

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc-client#649]
Prosím o rozšíření elementu `<note>` (a korespondující karty ve formulářích) o možnost vyplnit `typ` a `xlink`

Cílem je umožnit vyplnit v rámci poznámky URL jiného dokumentu (nebo jen UUID) a dosáhnout tak toho, že jednotlivé dokumenty (třeba staré tisky, výstřižky, tituly navazujících periodik) bude možné mezi sebou propojit. 

Návrh pro zápis URL:
```xml
<mods:note xlink:href="https://kramerius.lib.cas.cz/uuid/uuid:fbef59a0-0521-4737-adb8-6c1d148262ad">Přívazek k: Cesta Swato-Cellenská ...</mods:note>
```

Varianta pouze s UUID:
```xml
<mods:note type="uuid" xlink:href="uuid:4cb20369-7789-4b74-8283-73ddbca4f534"> Obsahuje přívazek: Pautnjček Maryánský ... </mods:note>
```

Děkuji!

**Comment by kerschfilip** [comment]
ještě doplním, že standard NDK nyní s touto možností nepočítá - vytvořil jsem proto i issue s dotazem na NK: https://github.com/NLCR/Standard_NDK/issues/220

**Comment by SykoraLukas** [comment]
K testování.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
