### ISSUE TITLE
Přidat modely pro e-born dokumenty 

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#65]
Dobrý den,
prosím o přidání modelů pro e-born dokumenty:

- NDK Vícedílná eMonografie
- NDK Svazek eMonografie
- NDK eKapitola
- NDK ePeriodikum
- NDK eRočník
- NDK eČíslo
- NDK eČlánek
- eČlánek

Přidat jak do vytváření Nového objektu, tak do Vyhledávání.
Děkuji, M.

**Comment by honza-rychtar** [comment]
Doplněno

**Comment by tumovam** [comment]
Zapsala jsem to do špatného issue, pardon. Bylo potřeba povolit modely:
'model:ndkeperiodical',
'model:ndkeperiodicalvolume',
'model:ndkeperiodicalissue',
'model:ndkearticle',
'model:ndkemonographtitle',
'model:ndkemonographvolume',
'model:ndkechapter',
'model:bdmarticle'
