### ISSUE TITLE
hledání podle názvu v pokročilém hledání

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#656]
Narazili jsme na problém při hledání, ale nevím, jestli to takhle není schválně. Chci vyhledat titul Z register tajemství lotrovského. Při hledání přes Dotaz mi to titul najde bez problémů. Když to ale zadám do pole název v pokročilém hledání, tak to rozloží na jednotlivá slova? a vyhodí vše, co tomu odpovídá - nejdřív zřejmě vše, co má v názvu Z... Pak je ale to pojmenování Název matoucí, měla by to pak být třeba Slova z názvu, pokud už se to má teda chovat takhle?
 
![pokrocilehledani](https://github.com/user-attachments/assets/4fd531d6-b46d-41fb-8777-b687f80e86b1)

**Comment by tumovam** [comment]
@luckajirku souvisí s tímto: https://github.com/proarc/proarc/issues/1734 Kterou máte nasazenou verzi?

**Comment by luckajirku** [comment]
> @luckajirku souvisí s tímto: [proarc/proarc#1734](https://github.com/proarc/proarc/issues/1734) Kterou máte nasazenou verzi?

aha, díky, já hledala v issues jen v klientovi. máme jádro 4.2.3 a klienta v2.3.2 (11.10.2024).

**Comment by tumovam** [comment]
@luckajirku jo, tak tohle rozšířené vyhledávání je snad opravené v nejnovější verzi (4.2.4), kterou ještě testujeme. Zatím s dovolením zavřu. Kdyby problém přetrvával, otevřeme, souhlasíš?

**Comment by luckajirku** [comment]
@tumovam ook, zavírám
