### ISSUE TITLE
Editor digitalizovaných dat (+- PDF)

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#66]
Dobrý den,
prosím o přidání možnosti "Media" pro e-born dokumenty.  

![obrazek](https://user-images.githubusercontent.com/31240271/96084879-260fa000-0ec0-11eb-9b73-a9098bff07f5.png)

V Editoru digitalizovaných dat pomocí ![obrazek](https://user-images.githubusercontent.com/31240271/96085591-51df5580-0ec1-11eb-9783-6b2b8c6e3c57.png) (= Načíst nový digitální obsah...) a ![obrazek](https://user-images.githubusercontent.com/31240271/96085654-67547f80-0ec1-11eb-8065-1ec4233ccd04.png) (= Smazat digitální obsah) v současném PA přidáváme (případně odebíráme) PDF u e-born dokumentů. 

Zároveň prosím o zaintegrování čtečky PDF dokumentů, současný stav ve v 3.6:

![obrazek](https://user-images.githubusercontent.com/31240271/96085052-80a8fc00-0ec0-11eb-9e71-eaee6410c54c.png)

Ve Vazbách (Editor připojených objektů) to nyní vypadá následovně:

![obrazek](https://user-images.githubusercontent.com/31240271/96086082-011c2c80-0ec2-11eb-855d-29424a3cbec4.png)

Velice děkujeme, 
KNAV

**Comment by honza-rychtar** [comment]
Hotovo. 

<img width="1336" alt="Snímek obrazovky 2021-05-08 v 19 12 56" src="https://user-images.githubusercontent.com/1178142/117547755-a00c9f80-b031-11eb-823d-9b489ee3e1d0.png">

PDF prohlížečka se použije nativní z prohlížeče jako je to v jádře Proarcu.

**Comment by tumovam** [comment]
@honza-rychtar děkujeme. Otestováno v https://proarc.inovatika.dev/ a tam vše funguje. Ale když jsme nasadili klienta (1.0.6 nad jádrem 3.6.5) nad naše data v KNAV, tak ani nedokážu založit eMonografii (eČlánek aj.). Je potřeba něco nakonfigurovat? Děkuji za odpověď.

**Comment by PetrKotynek** [comment]
globals.js
doplnit ????  Petr Kotýnek
   'model:ndkperiodical',
        'model:ndkperiodicalvolume',
        'model:ndkperiodicalissue',
        'model:ndkperiodicalsupplement',
        'model:ndkarticle',
        'model:ndkpicture',
        'model:ndkmonographtitle',
        'model:ndkmonographvolume',
        'model:ndkmonographsupplement',
        'model:ndkchapter',
        'model:ndkmap',
        'model:ndksheetmusic',
        'model:ndkpage',
        'model:page',
        'model:oldprintomnibusvolume',
        'model:oldprintmonographtitle',
        'model:oldprintvolume',
        'model:oldprintsupplement',
        'model:oldprintchapter',
        'model:oldprintgraphics',
        'model:oldprintmap',
        'model:oldprintsheetmusic',
        'model:oldprintpage',
        'model:ndkeperiodical',
        'model:ndkeperiodicalvolume',
        'model:ndkeperiodicalissue',
        'model:ndkearticle',
        'model:ndkemonographtitle',
        'model:ndkemonographvolume',
        'model:ndkechapter',
        'model:ndkphonographcylinder',
        'model:ndkmusicdocument',
        'model:ndksong',
        'model:ndktrack',
        'model:ndkaudiopage',
        'model:chronicletitle',
        'model:chroniclevolume',
        'model:chroniclesupplement',
        'model:bdmarticle' 

models: [
        'model:ndkmonographvolume',
        'model:ndkmonographtitle',
        'model:ndkmonographsupplement',
        'model:ndkperiodical',
        'model:ndkperiodicalvolume',
        'model:ndkperiodicalissue',
        'model:ndkperiodicalsupplement',
        'model:ndkarticle',
        'model:ndkchapter',
        'model:ndkmap',
        'model:ndksheetmusic',
        'model:ndkpage',
        'model:chroniclevolume',
        'model:chronicletitle',
        'model:chroniclesupplement',
        'model:page'
    ],

**Comment by tumovam** [comment]
Po povolení e-modelů už přidání/odebrání PDF funguje.
