### ISSUE TITLE
Zobrazení 3. sloupce (náhled skenu) při hromadné editaci stran

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#67]
"Při zobrazení tří panelů (seznam objektů, metadata a náhled obrázku stránky) se při hromadném výběru vypne náhled obrázků..." (zkopírované z https://github.com/proarc/proarc-client/issues/40)

![obrazek](https://user-images.githubusercontent.com/31240271/96087361-067a7680-0ec4-11eb-9221-cff4ccceb6ce.png)

Po výběru více stran zmizí náhled:
![obrazek](https://user-images.githubusercontent.com/31240271/96087415-1a25dd00-0ec4-11eb-8a1c-bed664548020.png)

Prosím @luckajirku a @nezbedova o doplnění, jak si představujete funkčnost 3. sloupce (3. panelu). 
Co by se mělo zobrazit místo náhledu skenu? 
Chcete, aby v náhledu zůstal náhled poslední strany, která je označená?
Prosím o doplnění. 
Děkuji

**Comment by luckajirku** [comment]
Poslední vybraná strana není špatná volba, hlavní ale je, aby to okno s náhledem nemizelo a člověk jej nemusel po každém hromadném označení, nebo přechodu v rámci struktury znovu naklikávat.

**Comment by nezbedova** [comment]
Souhlasím s @luckajirku

**Comment by luckajirku** [comment]
při testování jsem narazila na další věc, dávám samostatně: https://github.com/proarc/proarc-client/issues/77

**Comment by luckajirku** [comment]
Vypadá OK, možno zavřít.
