### ISSUE TITLE
Popis stran - uložit entrem a posunout

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#68]
Prosím o vrácení stávající funkčnosti pro popis jednotlivých stran.
Po zapsání čísla strany dát enter. Číslo se uloží a automaticky se poskočí na následující obrázek a ntím i následující tabulku pro popis strany. Kurzor je v poli číslo strany.
Co je mi platné uložení entrem, když musím myší najet na další obrázek.

Slovem "číslo" nemyslím jen číslici, ale i písmena.

 Zkuste za sebou vyplnit čísla stran: FC, FS, SP, F1, F2, A1r, A1v.

A pro pořádek přidávám staré, uzavřené issue https://github.com/proarc/proarc/issues/2

**Comment by luckajirku** [comment]
Funguje to, jen pokud hodnotu změním na jinou. Pokud ji ponechám a odentruju, na další stranu mi neskočí. To je schválně?

**Comment by luckajirku** [comment]
Vypadá to OK, asi se může zavřít.

**Comment by nezbedova** [comment]
Na čísla stran to funguje, ale na typy stran ne. Prosím upravit i to.

**Comment by luckajirku** [comment]
To samé jako u typu strany je i u vyhledávání u volby modelu, ve starém jde jen odentrovat, v novém klientovi nelze.

**Comment by albertoh** [comment]
Otestujte prosim, jestli tak si chovani tak predstavujete

**Comment by ZdenkaSera** [comment]
@luckajirku @nezbedova @SmejkalovaAnna Prosím, mohly byste na tohle kouknout raději všechny? Moc díky!

**Comment by SmejkalovaAnna** [comment]
Funguje to dobře v režimu Tabulka i v režimu Mžížka. Co je ale divné, a to bude asi prohlížečem ( mám Mozillu ) nebo čím, že navlkádám takto čísla stránek a když se vrátím zase na začátek, tak už to nereaguje a uloží mi to jen to číslo na první stránce a dál mi to už nepřeskočí, když dám F5, tak to zase funguje dobře...... to není uplně asi OK....

**Comment by albertoh** [comment]
Kdyz kliknete vlevo na jinou stranu ztracite focus z toho vyberu. Tim padem enter reaguje na levou stranu.
Ne potrebujete f5, staci kliknout vpravo na ten element, ktere chcete mit aktivni.

**Comment by SmejkalovaAnna** [comment]
Díky, tak je to asi OK....

**Comment by nezbedova** [comment]
Na typy stran to funguje tak, že po vybrání typu strany, dám enter a nic. Musím dát ještě jednou enter a skočí mi to na první obrázek (sken), nikoli na ten další.

Pro test doporučuji zkusit např přední desky, př. přídeští, titulka, prázdná strana, obsah. to jsou začátky monografií, které doplňujeme ručně.

Prohlížeč Chrom, test na Inovatika, náhledy i mřížka.

**Comment by luckajirku** [comment]
Funguje to při editaci ve vazbách, ale ne v importu - tam po změně v popisu strany a odentrování zůstanu na té straně, která byla editována. Mělo by to fungovat i v importu úplně stejně jako ve vazbách.

**Comment by albertoh** [comment]
Opraveno

**Comment by luckajirku** [comment]
Nám to pořád v importu nefunguje.

**Comment by albertoh** [comment]
Omlouvam se, nekopirovalo se spravne na testovaci server.
Uz je tam

**Comment by luckajirku** [comment]
Je to tam, ale... Vypadá to, že to funguje jen v případě, že člověk začne dělat změny od první strany. Pokud si sama kliknu na jinou, tak tam to po změně zůstane na té editované straně.

**Comment by nezbedova** [comment]
U STT nefunguje ani od první strany

**Comment by albertoh** [comment]
Opraveno.

STT funguje stejne

**Comment by nezbedova** [comment]
Otestováno. U STT funguje jako v jádře - posun Entrem.

**Comment by luckajirku** [comment]
Tohle už vypadá taky opraveně, za nás OK.

**Comment by nezbedova** [comment]
Posun Entrem funguje na typu i čísle strany.
Za nás lze zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě Labelu a Milestonu
