### ISSUE TITLE
V úložišti (Hledat) vrátit rozdělení na horní (přehled) a spodní část (detail vybraného objektu), jak je to v současném rozhraní  

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#69]
V úložišti (Hledat) by bylo žádoucí vrátit zpět rozdělení na horní (přehled) a spodní část (detail vybraného objektu), jak je to v současném rozhraní. Opravdu se to používá. 
U monografie většinou potřebujeme rychle zkontrolovat (bez rozklikávání a kontroly přímo v objektu ve vazbách), jestli tam jsou strany, u periodik zase vidět, jaké tam jsou ročníky, čísla, jestli tam jsou všechny strany, nebo které ročníky už byly exportovány atd. Je to pro kontrolu přehledné a rychlé.

**Comment by luckajirku** [comment]
Radši sem dopíšu, co bylo probráno na schůzce:
- dělicí lištu udělat výraznější
- ve spodní části potřebujeme zobrazení ve stromové struktuře a vidět tam vše včetně úrovně titulu (tak jak je to v současném klientovi)

**Comment by honza-rychtar** [comment]
- Spodní část je strom
- Dělení horní a spodní částí je výraznější
- Celý podstrom od vybraného objektu je možné načíst přes tlačítko **Rozbalit**
- V obou částech jednoduchým klikem vybírám a dvojklikem přecházím do editace vybraného obejktu

<img width="1792" alt="Snímek obrazovky 2020-12-03 v 16 51 22" src="https://user-images.githubusercontent.com/1178142/101053615-471f7380-3588-11eb-9f41-223659320848.png">

**Comment by luckajirku** [comment]
Funguje. Jen ještě chybí ten slíbený přesun nabídky Exportovat, URN:NBN atd. do levé části.

**Comment by honza-rychtar** [comment]
Už je vlevo.

**Comment by luckajirku** [comment]
OK, možno zavřít.
