### ISSUE TITLE
Tlačítko reindexace stran

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#71]
Přidat do vazeb tlačítko **Reindexovat všechny strany**

- Bude se zobrazovat pouze pokud je v seznamu alespoň jedna strana
- Buse se vztahovat na všechny strany (ne jen vybrané)
- Po kliknutí se ještě zobrazí dialog s potvrzením **Opravdu chcete přeindexovat všechny strany?**

**Comment by zabak** [comment]
viz též https://github.com/proarc/proarc/issues/1360

**Comment by honza-rychtar** [comment]
Od verze **1.0.8** zatím bez potvrzujícího dialogu. Přidám v další verzi.

**Comment by hosak** [comment]
Tlačítko nefunguje. 
Zkoušeno v periodiku "ABCDEFGH...", ročník 1990, druhé číslo. Stránky mají různé indexy, které by funkce měla opravit na řadu 1 až xy. Nic se ale nestane, po stisknutí tlačítka "reindexace" mají stránky i nadále špatné indexy. Je jedno, jestli jsem vybral nějaké stránky nebo ne, nic se nezmění ani v jednom případě.

**Comment by ZdenkaSera** [comment]
Vyzkoušeno v chromu, funguje ok.

Prosím o doplnění, jak se bude používat, pokud dojde k chybě při indexaci - stává se nám to u titulů s velkým počtem skenů. Bude se jen funkce tak dlouho opakovat, až vydá hlášku o úspěšné reindexaci? Zatím se mi chybu v testu nepodařilo nasimulovat. Děkuji.

**Comment by albertoh** [comment]
Musi se globalne resit #107

**Comment by ZdenkaSera** [comment]
@hosak Dávám sem návrh na uzavření, souhlasíte? Děkuji.
Přetrvávající chyba v reindexaci se řeší tady: nefunkční tlačítko reindexace #160

**Comment by luckajirku** [comment]
> * Po kliknutí se ještě zobrazí dialog s potvrzením **Opravdu chcete přeindexovat všechny strany?**

@ZdenkaSera  zatím bych to nezavírala, ještě chybí tenhle slíbený dialog

**Comment by albertoh** [comment]
Dialog pridan

**Comment by luckajirku** [comment]
dialog vyskakuje, vynutí si potvrzení akce, za nás OK, může se zavřít

**Comment by SykoraLukas** [comment]
Ano, zpreprodukoval jsem si problem. Nelze zatím reindexovat, pokud není vyplněno číslo strany/typ strany.

Reindexace se pouští nad všemi stranami pod daným modelem. Nereguje na označené strany. Vždy bere od první strany pod daným modelem. Takže i když budete stát na druhé straně, tak nedostane index 1, ale dostane index 2.

**Comment by ZdenkaSera** [comment]
@SykoraLukas super, děkujeme 😊

**Comment by SykoraLukas** [comment]
@albertoh pokud se vola funkce reindexace je potřeba doplnit při volani parametr batchId.Protože to nemá rodiče, tak se to tam musí udělat jinak a právě proto potřebuji batchId.

API jsem na to už připravil a nasadil na test.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@albertoh funguje, děkujeme. Vracím label k uzavření.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
