### ISSUE TITLE
Zobrazovat u editace názvy nadřazených obejktů

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#73]
Např. u čísla periodika by se (asi v toolbaru) zobrazil _Název periodikaka -> Ročník -> Číslo_

**Comment by luckajirku** [comment]
Nám by se tohle hodilo, rozhodně je dobré vědět, ve kterém periodiku se právě člověk nachází (hlavně při kontrolách apod.).

**Comment by albertoh** [comment]
Pridal jsem cestu k objektu na diskuze:
![image](https://user-images.githubusercontent.com/5946836/155292875-f9d2a9cc-c976-4e06-89dd-c08c8f452acc.png)

**Comment by SmejkalovaAnna** [comment]
Moc pěkné, díky.

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
