### ISSUE TITLE
Možnost Vytvořit nový objekt - NDK Kapitola

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#74]
Novém PA klientovi chybí možnost (pod úroveň svazku monografie) Vytvořit nový objekt NDK Kapitola. 

Nevím, jak je tento seznam aktuální, ale whitelist vazeb mezi objekty je zde: https://docs.google.com/spreadsheets/d/1bkSaNm7RjG3pfOI41sDqwRwSO9A7aYYOh1bGxNMjsT4/edit#gid=0

**Comment by honza-rychtar** [comment]
NDK Kapitola už tam je. Povolené vazby mezi modely pojďme řešit tady #99, kde je aktuální tabulka s vazbami aktualizovaná o nové modely.
