### ISSUE TITLE
Správa importů - chybí varování po kliknutí na "načíst znovu"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#75]
Když dám ve správě importů “načíst znovu”, u současného rozhraní vyskočí hláška “Již vytvořená metadata budou smazána! Pokračovat?” “Ano/Ne”. U nového klienta to projde bez varování.

**Comment by honza-rychtar** [comment]
On tam vyskočil dialog s opětovným načtením, kde se vybírá profil, ale chyběla tam ta varovná hláška. Přidal jsem.
<img width="484" alt="Snímek obrazovky 2020-12-03 v 16 57 18" src="https://user-images.githubusercontent.com/1178142/101054077-c90f9c80-3588-11eb-90df-451b53aef71e.png">

**Comment by luckajirku** [comment]
Vypadá to v pořádku, bude se moci zavřít..
