### ISSUE TITLE
Přepínání mezi jednoduchým a hromadným výběrem

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#76]
K čemu potřebujeme “jednoduchý výběr”? Snažila jsem se to dohledat v issues, vím, že jsme to probírali na schůzce, že nám to přepínání mezi jednoduchým a hromadným přišlo zbytečné. V issues jsem to nedohledala, buď špatně hledám, nebo to zůstalo jen v zápise ze schůzky. Ono teda i v tom zápise je to tak divně zařazené, ale nákres je jasný - ikona pro jednoduchý výběr je tam škrtnutá.  
Tady, str. 2 dole: https://docs.google.com/document/d/1Tl1eOXrb_bKHAV7aG8cDhbjIkG9TESKvT7XGqgRkvXE/edit

**Comment by luckajirku** [comment]
Můžu poprosit o názor @nezbedova, @tumovam a další uživatele - nevadí vám to neustálé přepínání? Je to navržené řešení pro vás lepší, než to současné?

**Comment by luckajirku** [comment]
Na schůzce 15.12.2020 se dohodlo, že toto přepínání bude zrušeno a vrátíme se ke způsobu, který je v současném rozhraní - bez nutnosti volit mezi výběry. Tedy mám označenou jednu stranu - mám formulář pro popis jedné strany. Označím více stran - automaticky se mi to přepne do hromadného popisu.  
Na tuhle věc je vázané testování dalších oprav - nemá smysl testovat cokoli, co se týká hromadného výběru, dokud nebude tahle úprava hotová.

**Comment by honza-rychtar** [comment]
Hotovo.
- nechalo se jen tlačítko vybrat vše 
- odstranily se checkboxy u zobrazení tabulkou
- pokud mám hromadný výběr a kliknu bez cmd, ctrl, shift, tak se přepne do jednoduchého výběru a vybere se kliknutý objekt 
- do hromadného výběru se přepnu přes cmd/ctrl, shift, nebo tlačítko vše

**Comment by luckajirku** [comment]
Vypadá OK, asi se může zavřít.
