### ISSUE TITLE
Chování náhledu při úpravě šířky třetího sloupce  

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#77]
Při úpravě šířky sloupců se ten třetí sloupec chová jinak než první dva. U těch se automaticky obsah při potáhnutí svislou lištou hned přizpůsobuje šířce, u třetí ale zobrazený náhled zůstává jak byl, a až když kliknu na jinou stranu, tak teprve ta velikostně sedí. Má to tak být?

**Comment by honza-rychtar** [comment]
Můžu při změně automaticky vycentrovat obrázek.
Otázka je, jestli se to vlastně chce. Pokud si v obrázku zazoomuju a pak změním šířku, tak se mi ten zoom vyresetuje.
Obě varianty dávají smysl. Teď která bude přirozenější.
Z druhé strany, pokud by zůstala současná varianta a změním šířku a chci vycentrovat obrázek, tak na to mám tlačítko
<img width="618" alt="Snímek obrazovky 2020-12-03 v 17 06 27" src="https://user-images.githubusercontent.com/1178142/101055579-51427180-358a-11eb-9bb3-184745fd8d85.png">

**Comment by luckajirku** [comment]
Jak tohle vidí KNAV? @nezbedova @ZdenkaSera ?

**Comment by ZdenkaSera** [comment]
@luckajirku Zkoušela jsem si to když jsem v minulých dnech procházela issues a teď znovu s poznámkou @honza-rychtar  - za sebe nevidím problém se stávající variantou, ale nepracuji v ProASrcu rutinně, za nás bude důležitý názor @nezbedova a @SmejkalovaAnna - můžu prosit? Díky.

**Comment by SmejkalovaAnna** [comment]
Mě to přijde taky dostačující tak, jak je to teď.... nemám s tím problém.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, můžeme tohle uzavřít? Díky.

**Comment by luckajirku** [comment]
Asi jde fakt jen o zvyk, nechme to takhle.

**Comment by ZdenkaSera** [comment]
@luckajirku Díky

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku, po jehož přidání issue nikdo nekomentoval.
