### ISSUE TITLE
Fce Změna pozice nehlásí chybu při neplatné hodnotě

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#78]
Fce změna pozice umožňuje vepsat číslo pozice ručně. Pokud vepíšu číslo, které je mimo rozsah té dávky, tak se to tváří, že to proběhlo, ale strana se nikam nepřesune. Mělo by to místo toho hodit chybovou hlášku.

**Comment by honza-rychtar** [comment]
Pokud teď zadám číslo, které je mimo rozsah, tak tlačítko **Přesunout** zašedne a nejde zmáčknout.
Pokud zadám číslo přes maxim a zmáčknu šipku dolů (na klávesnici nebo u toho vstupního pole), tak se vyplní maximum.
<img width="412" alt="Snímek obrazovky 2020-12-03 v 17 01 07" src="https://user-images.githubusercontent.com/1178142/101054693-6ff43880-3589-11eb-8d44-7b4568975d16.png">

**Comment by luckajirku** [comment]
Funguje. Jen nevím, koho by napadlo při vysoké hodnotě, když mu tlačítko zešedne, dávat šipku dolů, ale ok.

**Comment by honza-rychtar** [comment]
@luckajirku Co takhle tam přidat tlačítko něco jako Na konec. A to by vyplnilo pozici poslední stránky.

**Comment by luckajirku** [comment]
Je tam nějaká možnost, aby uživatel viděl celkový rozsah?

**Comment by albertoh** [comment]
Pridano rozmezi do popisku
![image](https://user-images.githubusercontent.com/5946836/154908894-a49576fe-c9d2-4431-9030-4b8d25f9b1fb.png)

**Comment by ZdenkaSera** [comment]
Přidán celkový rozsah v textu + hlídání zadaného rozsahu je hotové. K testu.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Zkoušela jsem, podle mne ok.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera funguje

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
