### ISSUE TITLE
Nápověda - zvětšit písmo

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#8]
Navrhuji zvětšit písmo v nápovědě. pokud je vidět jen, když se na ní najede, tak to běžné práci nepřekáží. Pokud se na ní chci podívat, tak ať je k přečtení.

**Comment by tumovam** [comment]
Prosíme zkopírovat to, co je v nápovědě ve stávající verzi ProArcu + ze standardu

**Comment by luckajirku** [comment]
Ta ukázka u "Název", "Autor", "Nakladatel" vypadá dobře, ale je to potom potřeba udělat stejně i u ostatních polí.

**Comment by honza-rychtar** [comment]
Nápověda je teď u všech polí. Znění je přepsané ze standardu a rozlišuje se pro periodikum a monografii (stejným způsobem se pak dodělají další modely).
V nápovědě je vedle povinnosti (M/MA/...) i odkaz do MODS XML (element, subelement, atribut, hodnota, ...)
Např. 
Číslo části MA originInfo/partNumber

<img width="549" alt="Snímek obrazovky 2021-04-07 v 22 42 40" src="https://user-images.githubusercontent.com/1178142/113931669-0912b480-97f3-11eb-9eba-520a7be21f91.png">
<img width="511" alt="Snímek obrazovky 2021-04-07 v 22 48 01" src="https://user-images.githubusercontent.com/1178142/113931931-598a1200-97f3-11eb-9df7-9ce59e4099a7.png">

**Comment by zabak** [comment]
@honza-rychtar když říkáš přepsané, rozumím tomu tak, že by se mělo do budoucna při změně standardu ručně aktualizovat i zde, že?

**Comment by honza-rychtar** [comment]
@zabak Ano

**Comment by nezbedova** [comment]
Prosím o trošku zvětšit písmo v bublinách:

![obrazek](https://user-images.githubusercontent.com/13831946/113968142-cec90780-9832-11eb-921f-837f60a0f8f8.png)

**Comment by honza-rychtar** [comment]
> Prosím o trošku zvětšit písmo v bublinách:


Zvětšeno.
