### ISSUE TITLE
Typ strany - v rolátku je 2x "obálka" - pro jacket i pro FrontJacket

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#80]
V rolátku u typu strany je teď nevím proč 2x "obálka". Jak pro "jacket" - pod náhledem se u ní zobrazuje "Přebal (Jacket)", tak pro "front jacket" - pod náhledem se zobrazuje "Přední strana přebalu (Front Jacket)".
Jinak ta obálka se řešila už tady https://github.com/proarc/proarc/issues/953 a tady https://github.com/NLCR/Standard_NDK/issues/72
Bordel, co se v tom nadělal, se už asi nespraví, ale aby se teď nenadělal ještě větší:-). 

z aktuálních pravidel (2.2)

● **_Obálka (jacket)_** 
Ochranný obal knihy zhotovený zpravidla z kvalitního papíru vyšší plošné hmotnosti, často s
křídovou úpravou nebo z jiného trvanlivého materiálu. Kromě funkce ochranné a ozdobné
uvádí na přední a zadní straně a na obou záložkách základní bibliografické informace o díle a
životopisné údaje o autorovi.
V rámci těchto pravidel je to **papírový přebal focený vcelku z přední strany** (zadní strana bývá
bílá bez Informace), nebo taky papírový přebal (šanon) do kterého jsou volně vloženy listy
dokumentu nebo sešity kroužkovou vazbou.
Zařadí se dozadu za zadní desky, potažmo hřbet.

● **_Reprezentativní obálka knihy (frontJacket)_**
Jako reprezentaci označujeme **část obálky pokrývající přední desky**. Je vždy na prvním místě.
**Vytváří se z papírového přebalu knihy (obálky)**, naopak nevytváří se z obálky (šanonu), do
kterých jsou listy pouze volně vloženy nebo sešity kroužkovou vazbou

**Comment by honza-rychtar** [comment]
Opraveno.
_frontjacket_ se zobrazí jako **reprezentativní obálka knihy**
_jacket_ jako **obálka**

V Krameriovi zůstává pro obojí označení **obálka**
