### ISSUE TITLE
Upravit popisek u třetího panelu 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#81]
Vzhledem k tomu, že ve třetím sloupci už je možné mít nejen náhled obrázku (#56), je potřeba upravit popisek - teď je tam "Otevřít obrázek v novém panelu"/"Zavřít panel s obrázkem".

**Comment by honza-rychtar** [comment]
Změněno na _Otevřít třetí panel_, _Zavřít třetí panel_.

**Comment by luckajirku** [comment]
OK
