### ISSUE TITLE
Sloupec s náhledy - spodní část poslední řady není přes panel vidět

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#82]
Ve sloupci s náhledy, pokud jich mám víc a musím rolovat, se mi dole spodek poslední řady skenů skryje za panel. Měl by tam být kus volného místa, aby se dal ten kousek ještě odrolovat a skeny byly vidět i s popisky celé. 

![skeny_panel](https://user-images.githubusercontent.com/6359479/103657814-a9dea300-4f6a-11eb-8df9-f49fdb185855.png)

**Comment by honza-rychtar** [comment]
Opraveno. Stávalo se, pokud se zmenšil panel s náhledy tak, že se zalomilo menu s ovládacími prvky.

**Comment by luckajirku** [comment]
Vypadá OK, může se zavřít.
