### ISSUE TITLE
U modelu NDK příloha periodika chybí ve 2. sloupci možnost zobrazení metadat ve formuláři

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#83]
V režimu procházení mám u ročníků a čísel periodika ve 2. sloupci na výběr M/xml. Ale jak najedu na přílohu - ročníku nebo čísla - tak mi možnost M zmizí a ukazuje to jen xml.

**Comment by honza-rychtar** [comment]
To už funguje.

**Comment by luckajirku** [comment]
Za nás funguje, může se zavřít.

**Comment by ZdenkaSera** [comment]
Za KNAV taky ok, díky.

**Comment by albertoh** [comment]
Prosíme o kontrolu dle zadání Issue a zavření

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna test, díky

**Comment by ZdenkaSera** [comment]
Uzavírám dle domluvy ze schůzky 16.3.2022
