### ISSUE TITLE
Zobrazení indexů a zkrácených nebo celých popisků stran

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#84]
v okně - původní vazby - se mi vlevo zobrazí seznam stran např. v čísle periodika ( nebo v náhledech ). Lze si nastavit buď Zobrazení zkácených popisků nebo celých. V případě, že budu mít zobrazený celý popisek, by bylo velmi užitečné, kdyby se vedle čísel stran, zobrazoval i sloupec s indexy stran - třeba červeně nebo prostě jinak barevně odlišené ( stejně tak i v možnosti zobrazení náhledů se může u každého náhledu vedle čísla a typu strany zobrazit i index ). Vím, že indexy ke každé straně jsou pak v pravo v Metadatech, ale dost často se hodí vidět souvislou řadu indexů v kuse....

Zkopírované z https://github.com/proarc/proarc/issues/1265

**Comment by nezbedova** [comment]
U periodik se zobrazují indexy stran, u monografií ne. Také by bylo lepší řešení, pokud by čísla indexů byla ve sloupci, kterým by šel roztahovat nebo zužovat. Jako to je teď. Tento požadavek na upravitelné sloupce nechci proto, že odmítám nové, ale protože zase zmizelo to, co fungovalo.

**Comment by ZdenkaSera** [comment]
Sloupec s indexem ve vazbách chybí i v jádře. Pokud by se měl přidat sloupec s indexem, musí se načíst z modsu a zpomalí se načítání. Ideální: abubra + solr. Odloženo, až bude Akubra.

**Comment by ZdenkaSera** [comment]
Tady vracím do kategorie "návrh na rozšíření".

**Comment by luckajirku** [comment]
Vzhledem k tomu, že už se tam objevil sloupec pro typ strany, víme už přesněji, kdy půjdou přidat i sloupce pro index a pozici strany? S tím provizorním řešením s indexy v závorce je to nepřehledné.

**Comment by albertoh** [comment]
Index strany budu moc pridat az prejdeme na akubru

**Comment by luckajirku** [comment]
A víme, kdy to cca bude?

**Comment by albertoh** [comment]
Je to na @SykoraLukas

**Comment by SykoraLukas** [comment]
Probíhá vedlejší instalace na uložiště AKUBRA, až bude zprovozněno pošleme přístupy.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Myslím, že tohle by mělo být k otestování na https://proarc-akubra.inovatika.dev/ - máme tam přístupy? Díky.

**Comment by luckajirku** [comment]
za nás OK - v tabulce v úložišti už se zobrazují sloupce s indexy i pozice strany, ty jdou zapnout/vypnout i upravit do šířky... máme co jsme chtěli:-)

**Comment by ZdenkaSera** [comment]
Za nás funkčnost taky ok. 
Mám jen poznámku ohledně sjednocení zobrazení v importu a editaci - když mám zapnutý klient v češtině, vidím v importu toto
![image](https://github.com/proarc/proarc-client/assets/79305516/3c55c31d-0cf9-4690-a15a-159e1c974a2b)

a v editaci toto
![image](https://github.com/proarc/proarc-client/assets/79305516/d9d850ea-75e4-470d-8850-5ac26e6187ef)

**Comment by ZdenkaSera** [comment]
Roletky sjednoceny, k uzavření.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
