### ISSUE TITLE
Zobrazit verzi klienta

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#85]

**Comment by honza-rychtar** [comment]
Přidána položka v menu **O aplikaci**, která zobrazí dialog s verzí klienta i jádra.
Ještě přidáme datum vydání klienta #87

<img width="486" alt="Snímek obrazovky 2021-02-19 v 10 24 21" src="https://user-images.githubusercontent.com/1178142/108485070-cf1a3d00-729c-11eb-9674-dcb3bab6c049.png">

**Comment by luckajirku** [comment]
OK, může se zavřít.
