### ISSUE TITLE
Datum vydání klienta u verze v dialogu O Aplikaci

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#87]

**Comment by honza-rychtar** [comment]
Přidáno. 
<img width="463" alt="Snímek obrazovky 2021-02-23 v 18 30 09" src="https://user-images.githubusercontent.com/1178142/108883152-6537c580-7605-11eb-9a35-7a77b984caed.png">

**Comment by luckajirku** [comment]
OK, může se zavřít.
