### ISSUE TITLE
Přidat filtry ve správě dávek

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#88]
Složka, vytvořeno, upraveno, uživatel

**Comment by albertoh** [comment]
To bych resil spolu s #109

**Comment by ZdenkaSera** [comment]
Issue 109 uzavřeno, řeší se pouze toto.

**Comment by ZdenkaSera** [comment]
@albertoh Není tohle už duplicita k https://github.com/proarc/proarc-client/issues/17, a tedy tay k uzavření? Díky.

**Comment by albertoh** [comment]
Neni. Zrejme tady se ma pridat moznost filtrovat podle tech zminenych dat: 
"Složka, vytvořeno, upraveno, uživatel"

**Comment by ZdenkaSera** [comment]
@albertoh Ok, děkuji.

**Comment by albertoh** [comment]
Pridal jsem.
Akorat v jadre ten filter "Slozka/nazev"

![image](https://user-images.githubusercontent.com/5946836/171848982-30487c2d-5893-4245-9dc6-2e71058731f3.png)

ve zkutecnosti najde nejen podle jmeno slozky a nazev, ale i dalsi udaje (na priklad uzivatel)

Podivejte se, prosim, staci li tak

**Comment by albertoh** [comment]
ad "prosím, jak má fungovat checkbox "Automaticky obnovit"? " 
      viz #17

ad "filtrování podle názvu složky je case sensitive"
     tak to dela jadro. Je mozne menit, Lukasi  ?

**Comment by ZdenkaSera** [comment]
@albertoh Děkuji, moje nepozornost :-(

**Comment by erikamirova** [comment]
@ZdenkaSera My asi nepotřebujeme filtrování podle názvu složky. Používáme vyhledávací pole, které v novém klientovi zatím chybí (ve správě import. dávek).

![image](https://user-images.githubusercontent.com/37616300/172557681-3e8fbebd-a122-4aa8-ad0d-305ca0466cc6.png)

**Comment by luckajirku** [comment]
- case sensitive hledání v názvu je nám celkem jedno, velká písmena v názvech složek nepoužíváme
- úplně nerozumím tomu, proč to v tom poli pro název hledá i podle uživatele, proč je to spojené
- nejvíc užijeme hledání podle stavu - a to je OK, takže za nás asi v pohodě

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji :-)

**Comment by albertoh** [comment]
To hledani funguje tady stejne jako v jadru.

To vyhledavaci pole v jadru
![image](https://user-images.githubusercontent.com/5946836/172575663-34d86115-9303-44f9-a186-13979fbc7f58.png)

V novem odpovida tomu:
![image](https://user-images.githubusercontent.com/5946836/172575782-fedf55ee-fa84-4056-b94d-ebf57a351a40.png)

v novem. Chova se stejne, a jak pise @luckajirku hleda i uzivatele.

**Comment by SykoraLukas** [comment]
Opraveno.

**Comment by luckajirku** [comment]
Uživatel už sice není dohromady s názvem, ale nejde ho nijak vyfiltrovat (nebo jde?). V jádře můžu vyhledávat i filtrovat, uživatele si seskupit, tady to nejde a vyhledávací pole pro uživatele tu není.

**Comment by SykoraLukas** [comment]
@albertoh prosím přidat pole pro uživatele.

**Comment by albertoh** [comment]
Filtr pripraven.
Posilam userId. Prosim @SykoraLukas dodelat v jadru

![image](https://user-images.githubusercontent.com/5946836/173034795-03bd763c-acdc-478c-b5c1-1b135fa5ee16.png)

**Comment by SykoraLukas** [comment]
API připraveno a nasazeno. K testování

**Comment by SykoraLukas** [comment]
Pozor filtr na uživatel funguje pouze v případě uživatel s rolí SUPERADMIN. Klasický uživatel vždy vidí pouze svou dávku.

**Comment by luckajirku** [comment]
Za nás OK.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
