### ISSUE TITLE
problem s prihlasenim 1.0.2

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc-client#89]
Dobrý den,
instaloval jsem ze zipu. V index.html je pravděpodobně odkaz na neexistující soubor
<link rel="stylesheet" href="styles.d7876bd20a7b3d6b6826.css"></head>
Po přejmenování se styl "srovná".

Poté je přihlášení možné ale končí hlášením Přihlášení se nezdařilo/login failed.
Zkoušel jsem variany na straně klienta, flush cache, inkognito session, jiný browser, restart PC.
Na straně serveru vyčistit celé a nechat pouze /assets/shared/ , i něco jako inkrementální instalaci ( přepsat nové věci ze zipu ). Opět různé úrovně restart apache, restart tomcat, celý server.  Verse proarcu 3.6.2. Není nutná vyšší ???
Po navrácení původních souborů ver. 1.0.0 je přihlášení možné.
Petr Kotýnek

**Comment by PetrKotynek** [comment]
Zkoušel jsem na další naistalované instanci s jádrem 3.6.3 a opět to končí "Přihlášení se nezdařilo".
Petr Kotýnek

**Comment by honza-rychtar** [comment]
Máte klienta na stejné doméně jako běží jádro ProArcu? Kvůli současnému způsobu přihlašování je tohle nutná podmínka.
Jediný chybějící soubor, na který index.html odkazuje, je /assets/shared/globals.js, kde je konfigurace, která není součásti distribuce. Aktualizuju tu dokumentaci, protože v konfiguraci je teď dost polí navíc a některá jsou nutná pro běh aplikace.
Např. takto vypadá konfigurace globals.js na testu https://proarc.inovatika.dev/assets/shared/globals.js
Nicméně tohle nemá vliv na přihlášení. Pokud máte klienta i jádro na stejné doméně a přesto vám nefunguje přihlašování, tak mi prosím pošlete výpis konzole (console i network) z prohlížeče. Nebo mi pošlete přímo link, pokud je to veřejně dostupné.

**Comment by PetrKotynek** [comment]
Přifoukl jsem globals.js podle vzoru, ano bez vlivu na přihlášení. Doména nevím, zkoušel jsem to na domácím serveru přes IP.
Něco jsem se pokusil nachytat. Petr
[err_login.txt](https://github.com/proarc/proarc-client/files/6027156/err_login.txt)
![login_net_1](https://user-images.githubusercontent.com/37083676/108810967-9932cc80-75ac-11eb-971d-b050a491ef24.png)
![login_1](https://user-images.githubusercontent.com/37083676/108810980-9e901700-75ac-11eb-9384-d75fab20a6f3.png)

**Comment by PetrKotynek** [comment]
Zkoušel jsem rozšířenou konfiguraci na "standardněší" instalaci s doménou. V 1.0.0 /login vrací status 200. V 1.0.2 skočí rovnou do 
/login 404 not found aniž to přihlášení nabídlo. Ještě jsem zkoušel flush cache na straně browseru, stejné, bohužel otočit apache na serveru bezprostředně nemohu. Petr

**Comment by honza-rychtar** [comment]
Problém byl ve změně klíče v konfiguraci. Na url jádra ProArcu se odkazovalo přes `proarc_backend_url`, nově je to `proarcUrl`. Omlouvám se.
Wiki s nasazením klienta jsem aktualizoval včetně rozšířených voleb konfigurace https://github.com/proarc/proarc-client/wiki/Nasazen%C3%AD-klienta
Vydal jsem taky novou verzi klienta https://github.com/proarc/proarc-client/releases/tag/v1.0.3 - je tam seznam změn od minula. Od teď budu takto popisovat každou novou verzi a taky hned aktualizovat wiki.

Pokud jde o problém s 404, tak to se děje, když v address baru rovnou odpálíte nějakou jinou než hlavní stránku že?
Je to popsané tady - https://github.com/proarc/proarc-client/wiki/Nasazen%C3%AD-klienta#konfigurace-web-serveru - konfigurace web serveru.
Ta klientská aplikace je vlastně jediná stránka, běžící na /, resp. na /index.html a veškeré routování se děje na straně prohlížeče. Např. stránka /search z pohledu serveru neexistuje. Řešením je poslat každý request na neexistující stránku na /index.html a to už si ten framework zpracuje na klientské straně. Ta konfigurace je popsaná na odkazu výše.

**Comment by PetrKotynek** [comment]
Ano, 
103 už chybu 404 negeneruje.
Po záměně proarc_backend_url na  proarcUrl to projde přes proarclogin a rest/v1/user?whoAmI=true ( 200 ) až k cílové metě:
Klient
Verze 1.0.3 (23.2.2021)
Jádro
Verze 3.6.3
Build 20210216110726
Revize 2750c078af9fea0f5655d54ab81358e64103f143

Děkuji, Petr Kotýnek

**Comment by PetrKotynek** [comment]
Nemám k dispozici "ozubené kolečko"/settings v sekci  "labels", ale jinak jsem pro -> návrh na zavření.

Petr Kotýnek
