### ISSUE TITLE
Import - chybí možnost mít pouze 2 náhledy v řádku

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#90]
Dávám jako další issue, v https://github.com/proarc/proarc-client/issues/4 to zapadlo.
V novém klientovi už není v Importu možnost nastavit si dva náhledy na řádek, méně jak tři to nastavení nedovolí. Problém je, že pro přehledný popis člověk potřebuje zpravidla sudý počet stran, s lichým se pracuje málokdy. A často se právě srovnání do řádků po dvou hodí nejvíc. 
Chápu, že to omezení asi vzniklo zase kvůli jiným funkcím, ale tuhle možnost je potřeba tam mít.

**Comment by honza-rychtar** [comment]
Ok, změním to, aby s tím šlo šoupat libovolně. V určitém zmenšení toho panelu už budou ovládací prvky nepoužitelné. Ale necháme to na uživateli, ať si to nastaví, jak chce.
Ten zlom pro zobrazení dvou sloupců je tam v pohodě při editaci i po importu.
<img width="303" alt="Snímek obrazovky 2021-02-22 v 17 34 46" src="https://user-images.githubusercontent.com/1178142/108739353-dc515900-7534-11eb-80b4-9e6357a19fc3.png">

<img width="302" alt="Snímek obrazovky 2021-02-22 v 17 35 19" src="https://user-images.githubusercontent.com/1178142/108739391-e410fd80-7534-11eb-8488-eae2203fa539.png">

**Comment by honza-rychtar** [comment]
Teď jde měnit šířku levého sloupce libovolně.

**Comment by luckajirku** [comment]
Super, funguje, může se zavřít.
