### ISSUE TITLE
Uložení změn v popisu strany a následný posun šipkami mezi skeny

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc-client#92]
Po změně v popisu strany (číslo strany, index strany) přestává fungovat v prvním sloupci přesouvání na další obrázky pomocí šipek, jasné, pohybujeme se ve formuláři ve druhém sloupci. Ale... 
Pokud ukládám enterem, pro návrat možnosti pohybu ve skenech přes šipky je potřeba refresh, nestačí kliknout jinam.
Kdežto když ukládám přes ikonku, postačí kliknout na jiný sken a šipky zase fungují.
Je to takhle schválně? Ve stávajícím rozhraní stačí kliknout na jiný sken a možnost posunu šipkami se vrátí i po uložení enterem.

**Comment by honza-rychtar** [comment]
Je to chyba.

**Comment by luckajirku** [comment]
A je to chyba, která stále trvá. Kdy bude opraveno?

**Comment by albertoh** [comment]
Nemuzu reprodukovat. Prosim o kontrolu, jestli problem stale existuje

**Comment by honza-rychtar** [comment]
@albertoh Chyba je tam pořád.
1) vlevo mám strany, vpravo formulář s vybranou stranou. Šipkami se můžu posouvat mezi stranami.
<img width="1196" alt="Snímek obrazovky 2022-02-21 v 9 33 58" src="https://user-images.githubusercontent.com/1178142/154917903-67b058f5-6ae6-468c-8cde-0a9e084dd176.png">

2) vpravo ve formuláři udělám změnu a uložím to **entrem** (když mám focus v poli číslo strany nebo index).

3) odteď se **vynucuje** focus do toho pole, kde jsem to odpálil entrem (číslo strany nebo index) a šípky proto fungují jako kurzor uvnitř toho pole místo posunu stran.

**Comment by albertoh** [comment]
Ok. Vidim. Opraveno

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, mohly byste se na tohle taky podívat? Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera @luckajirku @nezbedova @albertoh podle mne, to funguje pořád stejně ( 3. odteď se vynucuje focus do toho pole, kde jsem to odpálil entrem (číslo strany nebo index) a šípky proto fungují jako kurzor uvnitř toho pole místo posunu stran. ) , teď jsem to zkoušela...

**Comment by luckajirku** [comment]
@ZdenkaSera jak už jsem psala dříve do nějakého issue - na test na inovatice se už nedostaneme (zřejmě bylo změněno heslo).

**Comment by ZdenkaSera** [comment]
@luckajirku Moje chyba, vzpomínám si - ráda Vám je pošlu - kam můžu?

**Comment by albertoh** [comment]
Opravil jsem chybu, tj nutnost znovu nacist stranku, aby moznost pohybu sipkami byla funkcni.
Ted staci klikout na obrazek, a zase sipky reagujou jako posun mezi obrazky. Pokud zustavame v editaci, sipky reagujou v ramci editovaciho policka. 
Myslim si, ze to je ocekavane chovani.

**Comment by SmejkalovaAnna** [comment]
@albertoh Aha, tak jsem to špatně pochopila. V tom případě to funguje.

**Comment by luckajirku** [comment]
> @luckajirku Moje chyba, vzpomínám si - ráda Vám je pošlu - kam můžu?
na mail lucie.jirku@svkhk.cz

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
