### ISSUE TITLE
Barevné zobrazení xml i při editaci

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#94]
Bylo by možné, ale xml zůstalo barevné i při editaci tohoto záznamu?

**Comment by albertoh** [comment]
Pro nove prohlizece lze to delat

**Comment by pavelkocourek** [comment]
> Pro nove prohlizece lze to delat

Pak je to uvést doporučenou verzi prohlížeče na Wiki

**Comment by ZdenkaSera** [comment]
Prosíme doplnit prohlížeče.

**Comment by ZdenkaSera** [comment]
Doplnit indikaci, že jsme v režimu editace (např. změna barvy pozadí ...).

**Comment by nezbedova** [comment]
Podbarvení žlutou je pěkné. Za mě je to ale moc syté. 
Prosím o vyjádření ostatních.

**Comment by ZdenkaSera** [comment]
@nezbedova Tohle jsem zkoušela později a podbarvení bylo (a stále je) světle žluté - možná došlo ke změně? Prosím, koukni na to - jsem pro návrh na uzavření. Děkuji.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím o komentář komentáře (mého) :-),  navrhla bych to k uzavření, pokud souhlasíš. Děkuji.

**Comment by nezbedova** [comment]
Základní podbarvení je béžové. Když se přepnu do režimu úpravy, změní se na bílou. To je stejné jako když popisuji ve formuláři. Myslím si, že by to takto mohlo vyhovovat i ostatním. Děkuji.
Navrhuji issue zavřít.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
