### ISSUE TITLE
Propojení s RDflow

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc-client#95]
Přidat tlačítko Záměry na horní lištu mezi Import a Zařízení. Po kliknutí dojde na přepnutí do obrazovky záměrů.

**Comment by honza-rychtar** [comment]
<img width="750" alt="Snímek obrazovky 2021-04-07 v 22 36 17" src="https://user-images.githubusercontent.com/1178142/113930882-209d6d80-97f2-11eb-9cc3-28ee32fea834.png">

**Comment by nezbedova** [comment]
To se mi líbí. Bude také vypínací?

**Comment by nezbedova** [comment]
Po kliknutí na Záměry se v novém okně otevřou Záměry. Nový objekt monografie založený v záměrech se objevil v Hledat.

**Comment by nezbedova** [comment]
Na testu u nás: https://proarc-test.libj.cas.cz/search Verze 1.0.4 (7.4.2021) se po kliknutí na záměry v nové záložce otevře https://proarc.inovatika.dev/api/#workflow:%7B%22type%22:%22JOBS%22%7D

**Comment by nezbedova** [comment]
@honza-rychtar kdy to bude opravené?

**Comment by honza-rychtar** [comment]
Opraveno ve verzi 1.0.6

**Comment by nezbedova** [comment]
Vyzkoušeno. Funguje. Otevře se v novém okně.

Navrhuji issue zavřít.
