### ISSUE TITLE
Horní lišta (záhlaví) v klientovi

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc-client#97]
Na dnešní vývojové schůzce napadl nápad, přeuspořádat horní lišty v klientovi: 

![obrazek](https://user-images.githubusercontent.com/31240271/111968630-a8e4f880-8af9-11eb-879a-a16da454c21d.png)

**Comment by tumovam** [comment]
Např.:
- admin a super admin uvidí “Zařízení” 
- kdo nepoužívá RDFlow, nepotřebuje “Záměry”, a zároveň, kdo využívá “Záměry”, tak nepotřebuje “Nový objekt” 
o další doplnění prosím @nezbedova

**Comment by nezbedova** [comment]
Dávám ostatním ke zvážení jak jednotlivá tlačítka sestavit. Osobně preferuji stejné pořadí jak je nyní v roletce a na liště v původním PA. Tj. Nová dávka, Historie, Nový objekt, Hledat, Záměry. Toto pořadí kopíruje postup jednotlivých kroků.

Jednotlivá tlačítka by se dala skrýt v nastavení.

**Comment by luckajirku** [comment]
A jaké jsou/by mohly být možnosti pro konfiguraci? Co by bylo nastavitelné v cfg u konkrétní instalace, co u konkrétního uživatele nebo stanice? Mohl bys to prosím Honzo nějak shrnout? Díky.

**Comment by tumovam** [comment]
Ještě se prosím domluvit, co dát vlevo a vpravo...

**Comment by honza-rychtar** [comment]
Návrh

<img width="1415" alt="Snímek obrazovky 2021-04-21 v 10 18 47" src="https://user-images.githubusercontent.com/1178142/115521017-03a17980-a28b-11eb-9c76-8ff96ebebdf2.png">

Záměry se dají vypnout v konfiguraci na úrovni aplikace.
Pokud bude potřeba, tak přidáme i do lokálního nastavení pro jednotlivé uživatele možnost zobrazení pro každou položku kromě profilu.

**Comment by tumovam** [comment]
Za mě pěkné 👍 Ale o konečné vyjádření prosím @nezbedova a @luckajirku , které s PA více pracují, a které toto navrhovaly. Děkuji

**Comment by luckajirku** [comment]
Za nás takhle super - je to přehledné a funkční. 
Jestli platí to, že "Zařízení" uvidí jen admini (tam by běžný uživatel lézt neměl) a "Záměry" půjdou vypnout v cfg, tak pro nás v podstatě už jiné nastavení netřeba.

**Comment by nezbedova** [comment]
Nám se to také takto líbí. A také doufám, že Zařízení běžný uživatel neuvidí.
A kde bude mít Super Admin možnost přidávat a upravovat uživatele? Nyní to je v rozbalovátku.

**Comment by honza-rychtar** [comment]
> ... Jestli platí to, že "Zařízení" uvidí jen admini (tam by běžný uživatel lézt neměl) ...
> ... A také doufám, že Zařízení běžný uživatel neuvidí. ...

Ok, zobrazí se jen adminovi a super adminovi.

> A kde bude mít Super Admin možnost přidávat a upravovat uživatele? Nyní to je v rozbalovátku.

Založil jsem k tomu issue #106

**Comment by nezbedova** [comment]
@honza-rychtar kdy to bude k testování?

**Comment by honza-rychtar** [comment]
Hotovo ve verzi 1.0.6

**Comment by nezbedova** [comment]
Běžný uživatel zařízení nevidí.
 SuperAdmin ho vidí a může zařízení přidávat, upravovat i mazat.

Záměry jsou v #95 měla jsem je vypnuté a po povolení je mám funkční.

Navrhuji issue zavřít.
