### ISSUE TITLE
Povolené vazby mezi modely

### ISSUE THREAD

**Issue by honza-rychtar** [proarc/proarc-client#99]
Tady
https://docs.google.com/spreadsheets/d/1mQOLRP2kpxhLTJe9bviBCunfhmQFCy2FbaRX3DH7YJo/edit?usp=sharing
je tabulka se všemi modely a jejich vazbami. Fajfka v buňce znamená, že model v řádku může obsahovat model ve sloupci. Modrá fajfka je pak výchozí model.

Prosím o připomínky, ať to můžeme nějak finálně nastavit.

**Comment by luckajirku** [comment]
NDK strana pod NDK Kapitola - tahle vazba nedává smysl, fyzicky tam žádné strany uložené nejsou, jen je rozsah popsaný v extent

**Comment by luckajirku** [comment]
NDK strana pod NDK ročník - samotná strana nedává smysl. Ani tady straně nelze přidělit URN:NBN, jestli se nepletu - takže jak by šla exportovat? Na základě čeho se tahle vazba dostala do tabulky?

**Comment by luckajirku** [comment]
Prošli jsme obě tabulky, resp. ty modely, které používáme (tj. **NDK Monografie, resp. Vícedílná monografie a NDK Periodikum** + odpovídající podřazené modely) a za nás v podstatě platí, co už jsem psala:

- NDK Strana pod NDK Kapitola zrušit
- NDK Strana pod NDK Ročník zrušit (ty strany pod ročníky, které lze najít stávájících Krameriích, jsou, co jsme se dívali, všechny z 20 let staré digitalizace a z pohledu NDK je to špatně)

- NDK Článek pod NDK Ročník zrušit? (nepřišli jsme na případ, kdy by se to mělo použít, to dává smysl asi jen u e-per, ne u tištěných) - nebo má někdo příklad?


? NDK Obrázek - tady vůbec netušíme, jak se používá Obrázek jako model, používáme jen jako typ strany, takže nevím, jestli je to OK. 

? strana - tím úplným zrušením strany si nejsem jistá. Jako u nově založených objektů je to jasné, že pod NDK modely budeme zakládat jen NDK stranu. Ale pokud by došlo na opravu titulu, který byl zpracovaný ještě před zavedením NDK stran, to bychom museli všechno převádět? 

! neprocházeli jsme to, co (teď) neděláme - STT / e-PER, e-MON / audio / kroniky

**Comment by honza-rychtar** [comment]
Přidal jsem všechny modely a povolil vazby podle nové tabulky https://docs.google.com/spreadsheets/d/1H_afNvAt8SLdXH1Dpst8R3Vl7AaC0556kIpD44vftLw/edit?usp=sharing
Tam už jsou zapracované poznámky od Lucky.

Pokud jde o NDK Obrázek, zeptám se stejně jako Lucka, používá to někdo?
V Krameriovi model _picture_ některé knihovny mají, konkrétně jsem se s tím setkal ve Zlíně.
Ale klient Krameria model _picture_ ignoruje a doteď si nikdo nestěžoval.
Tady jsou množství dokumentů s modelem picture ve vybraných knihovnách.
- Zlín → **5066**
- MZK → **56**
- KNAV → **1**
- Hradec Králové → **1**
- NKP → **0**

A ještě mi připadá podezřelá povolená vazba, kde Vícedílná monografie může obsahovat Vícedílnou monografii, @SykoraLukas, @luckajirku je to překlep, nebo to se to skutečně může neomezeně vnořovat?

**Comment by luckajirku** [comment]
to tam musí být překlep, vícedílka pod vícedílkou je nesmysl.

**Comment by SykoraLukas** [comment]
Toto bylo řešeno zde https://github.com/proarc/proarc/issues/782 a proto vznikla možnost vícedílky pod vícedílkou. Dříve to nešlo.

**Comment by honza-rychtar** [comment]
To ale pořád nemění nic na tom, že je to nesmysl ne? 
Má někdo reálný příklad, který by vyžadoval vazbu, kdy je vícedílka pod vícedílkou?

V Krameriovi jsou modely u vícedílek opačně.
- V ProArcu má obálka (Vícedílná monografie) speciální model a jednotlivé svazky (Monografie) mají stejný model jako samostatná monografie.
- V Krameriovi má naopak obálka stejný model jako samostatná monografie a jednotlivé svazky mají speciální model (monographunit)

To násobné vnoření vícedílka -> vícedílka -> svazek by se muselo převést do Krameria tak, aby tam nevznikal monografie pod monografií. 

Nejlepší bude se té vazbě úplně vyhnout.

**Comment by luckajirku** [comment]
Honzo, tenhle celý problém začíná u blbě udělaného standardu pro vícedílky. Kdy bude na světě takový, který bude respektovat letitou katalogizační praxi (a nebude postavený na hlavu jako je to od začátku v NDK), je otázka...

**Comment by luckajirku** [comment]
Po kontrole u nás: 

- povolené vazby odpovídají tabulce a až na jednu výjimku se to chová logicky (pod vícedílnou eMonografií se defaultně nabízí eKapitola, místo eMonografie - ale e-cokoli v PA neděláme, takže neposoudím, jestli to tak někdo třeba nechtěl úmyslně)

- co se týká standardu pro vícedílky, tak by NK měla vydat v dohledné době DMF mon. 2.0, kde je to upravené - takže předpokládám, že potom se k vícedílkám ještě vrátíme.

**Comment by ZdenkaSera** [comment]
@kerschfilip Filipe, prosím, uměli bychom se v rámci práce v OZČ vyjádřit k těm e-modelům nebo to zatím navrhneme uzavřít a případně se k tomu vrátit, objeví-li se problém? Díky.

**Comment by ZdenkaSera** [comment]
Měním štítky, protože @albertoh zmiňoval, že issue "k testování" nebude řešit :-)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
omlouvám se, nevšiml jsem si toho dřív, ale podle téhle tabulky (https://docs.google.com/spreadsheets/d/1H_afNvAt8SLdXH1Dpst8R3Vl7AaC0556kIpD44vftLw/edit?usp=sharing) a testu na Inovatice teď nejde, ale mělo by jít:

- Přidat NDK Článek pod Přílohu periodika
- Přidat eČlánek pod Přílohu periodika (specifický usecase KNAV) 
- Přidat NDK Kapitolu pod Přílohu monografie

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
